-- supabase/sql/exam_question_bank_ssc_cgl_set1.sql
--
-- First curated question-bank batch for 'SSC-CGL' (see exam_patterns_ssc_cgl.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (100% single-best-response,
-- matching the real Tier I exam). The "General Awareness" chapters stick to durable, evergreen
-- static facts rather than time-sensitive news. Non-verbal reasoning is normally figure-based
-- (mirror images, figure counting) and can't be rendered as images here, so that chapter instead
-- uses the classic numeric cube-painting/paper-folding puzzles that SSC exams commonly phrase in
-- pure text. 16 chapters (4 per section x 4 sections) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_cgl.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General Intelligence and Reasoning: Verbal Reasoning (Analogies, Classification, Series)
('SSC-CGL', 'General Intelligence and Reasoning', 'Verbal Reasoning (Analogies, Classification, Series)', 'easy', 'mcq',
 'Complete the analogy: Doctor is to Hospital as Teacher is to:',
 '[{"text":"Classroom","isCorrect":false},{"text":"School","isCorrect":true},{"text":"Book","isCorrect":false},{"text":"Student","isCorrect":false}]'::jsonb,
 null, 'A doctor primarily works at a hospital; the analogous primary workplace for a teacher is a school, the broader institution.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Verbal Reasoning (Analogies, Classification, Series)', 'easy', 'mcq',
 'Find the odd one out: Apple, Mango, Potato, Banana.',
 '[{"text":"Apple","isCorrect":false},{"text":"Mango","isCorrect":false},{"text":"Potato","isCorrect":true},{"text":"Banana","isCorrect":false}]'::jsonb,
 null, 'Apple, Mango, and Banana are all fruits, while Potato is a vegetable, making it the odd one out.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Verbal Reasoning (Analogies, Classification, Series)', 'medium', 'mcq',
 'Find the next number in the series: 3, 9, 27, 81, ?',
 '[{"text":"162","isCorrect":false},{"text":"243","isCorrect":true},{"text":"216","isCorrect":false},{"text":"324","isCorrect":false}]'::jsonb,
 null, 'Each term is multiplied by 3 to get the next term, so after 81 the next term is 81*3=243.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Verbal Reasoning (Analogies, Classification, Series)', 'medium', 'mcq',
 'Find the odd one out: 8, 27, 64, 100.',
 '[{"text":"8","isCorrect":false},{"text":"27","isCorrect":false},{"text":"64","isCorrect":false},{"text":"100","isCorrect":true}]'::jsonb,
 null, '8, 27, and 64 are perfect cubes (2^3, 3^3, 4^3), while 100 is not a perfect cube, making it the odd one out.'),

-- General Intelligence and Reasoning: Non-Verbal and Figural Reasoning
('SSC-CGL', 'General Intelligence and Reasoning', 'Non-Verbal and Figural Reasoning', 'medium', 'mcq',
 'A cube is painted red on all its faces and then cut into 27 equal smaller cubes. How many of the smaller cubes have exactly one face painted red?',
 '[{"text":"6","isCorrect":true},{"text":"8","isCorrect":false},{"text":"12","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'In a 3x3x3 cube, the single cube at the center of each of the 6 faces has exactly one painted face, giving 6 such cubes.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Non-Verbal and Figural Reasoning', 'medium', 'mcq',
 'A cube is painted red on all its faces and cut into 27 equal smaller cubes. How many smaller cubes have no face painted at all?',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"8","isCorrect":false},{"text":"27","isCorrect":false}]'::jsonb,
 null, 'Only the single cube at the very center of the 3x3x3 arrangement, completely surrounded by other cubes, has no painted face.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Non-Verbal and Figural Reasoning', 'medium', 'mcq',
 'A square sheet of paper is folded in half twice (into quarters), and then a hole is punched through the folded center. How many holes will appear when the paper is fully unfolded?',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":false},{"text":"4","isCorrect":true},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'Folding a sheet in half twice creates 4 layers; punching through the center of all 4 layers produces 4 holes when the paper is unfolded.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Non-Verbal and Figural Reasoning', 'hard', 'mcq',
 'A cube is painted red on all its faces and cut into 64 equal smaller cubes (a 4x4x4 arrangement). How many smaller cubes have exactly two faces painted red?',
 '[{"text":"12","isCorrect":false},{"text":"24","isCorrect":true},{"text":"8","isCorrect":false},{"text":"36","isCorrect":false}]'::jsonb,
 null, 'In a 4x4x4 cube, each of the 12 edges has 2 non-corner cubes with exactly two painted faces, giving 12*2=24 such cubes.'),

-- General Intelligence and Reasoning: Logical Reasoning (Syllogism, Statements and Conclusions)
('SSC-CGL', 'General Intelligence and Reasoning', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'medium', 'mcq',
 'Given: "All pens are pencils" and "All pencils are erasers." Which conclusion follows?',
 '[{"text":"All pens are erasers.","isCorrect":true},{"text":"All erasers are pens.","isCorrect":false},{"text":"No pens are erasers.","isCorrect":false},{"text":"Some pencils are not erasers.","isCorrect":false}]'::jsonb,
 null, 'By transitive syllogism, since all pens are pencils and all pencils are erasers, it necessarily follows that all pens are erasers.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'hard', 'mcq',
 'Statement: "All cats are black." Conclusion I: Some black things are cats. Conclusion II: No cats are white. Which of the conclusions logically follow(s)?',
 '[{"text":"Only Conclusion I follows","isCorrect":true},{"text":"Only Conclusion II follows","isCorrect":false},{"text":"Both conclusions follow","isCorrect":false},{"text":"Neither conclusion follows","isCorrect":false}]'::jsonb,
 null, '"All cats are black" implies at least some black things are cats (Conclusion I follows), but it does not by itself rule out the possibility of non-black cats existing outside this specific statement''s scope in strict syllogistic terms, so Conclusion II does not strictly follow.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'medium', 'mcq',
 'Given: "Some A are B" and "All B are C." Which conclusion follows?',
 '[{"text":"Some A are C.","isCorrect":true},{"text":"All A are C.","isCorrect":false},{"text":"No A are C.","isCorrect":false},{"text":"All C are A.","isCorrect":false}]'::jsonb,
 null, 'Since some A are B, and all B are C, those particular A that are B must also be C, so it follows that some A are C.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'medium', 'mcq',
 'Given: "No fish is a mammal" and "All whales are mammals." Which conclusion follows?',
 '[{"text":"No whale is a fish.","isCorrect":true},{"text":"All whales are fish.","isCorrect":false},{"text":"Some fish are whales.","isCorrect":false},{"text":"No conclusion can be drawn.","isCorrect":false}]'::jsonb,
 null, 'Since all whales are mammals, and no fish is a mammal, it follows that no whale can be a fish.'),

-- General Intelligence and Reasoning: Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)
('SSC-CGL', 'General Intelligence and Reasoning', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'medium', 'mcq',
 'In a certain code, "BOOK" is written as "DQQM". How is "PAGE" written in the same code?',
 '[{"text":"RCIG","isCorrect":true},{"text":"RCHF","isCorrect":false},{"text":"QCIG","isCorrect":false},{"text":"RCIH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by 2 positions in the alphabet (B to D, O to Q, O to Q, K to M); applying the same shift to P-A-G-E gives R-C-I-G.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'hard', 'mcq',
 'Pointing to a photograph, a man says, "She is the daughter of my grandfather''s only son." How is the woman related to the man?',
 '[{"text":"Mother","isCorrect":false},{"text":"Sister","isCorrect":true},{"text":"Aunt","isCorrect":false},{"text":"Wife","isCorrect":false}]'::jsonb,
 null, 'The man''s grandfather''s only son must be the man''s own father (since he has no brothers), so the daughter of the man''s father is his sister.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'medium', 'mcq',
 'Ravi walks 5 km towards north, then turns right and walks 3 km, then turns right again and walks 5 km. How far is he from his starting point?',
 '[{"text":"3 km","isCorrect":true},{"text":"5 km","isCorrect":false},{"text":"8 km","isCorrect":false},{"text":"13 km","isCorrect":false}]'::jsonb,
 null, 'After walking north 5 km, east 3 km, and south 5 km, the northward and southward legs cancel out, leaving Ravi 3 km east of his starting point.'),
('SSC-CGL', 'General Intelligence and Reasoning', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'medium', 'mcq',
 'A man walks 4 km towards east, then turns left and walks 4 km, then turns left again and walks 4 km. In which direction is he now from his starting point?',
 '[{"text":"North","isCorrect":true},{"text":"South","isCorrect":false},{"text":"East","isCorrect":false},{"text":"West","isCorrect":false}]'::jsonb,
 null, 'Tracking the path: east 4km, then north 4km (left turn from east), then west 4km (left turn from north) -- the net displacement from the start is 4km due north.'),

-- General Awareness: Indian History and Culture
('SSC-CGL', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'The Indian National Congress was founded in the year:',
 '[{"text":"1857","isCorrect":false},{"text":"1885","isCorrect":true},{"text":"1905","isCorrect":false},{"text":"1920","isCorrect":false}]'::jsonb,
 null, 'The Indian National Congress was founded in 1885 by Allan Octavian Hume.'),
('SSC-CGL', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Which Mughal emperor built the Taj Mahal?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Shah Jahan","isCorrect":true},{"text":"Aurangzeb","isCorrect":false},{"text":"Jahangir","isCorrect":false}]'::jsonb,
 null, 'Shah Jahan commissioned the Taj Mahal in Agra as a mausoleum for his wife, Mumtaz Mahal.'),
('SSC-CGL', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Bharatanatyam, a classical Indian dance form, originated in which state?',
 '[{"text":"Kerala","isCorrect":false},{"text":"Tamil Nadu","isCorrect":true},{"text":"Odisha","isCorrect":false},{"text":"Gujarat","isCorrect":false}]'::jsonb,
 null, 'Bharatanatyam originated in the temples of Tamil Nadu as a form of devotional dance.'),
('SSC-CGL', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'The Quit India Movement was launched in which year?',
 '[{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":true},{"text":"1947","isCorrect":false},{"text":"1919","isCorrect":false}]'::jsonb,
 null, 'The Quit India Movement was launched by Mahatma Gandhi in August 1942, demanding an end to British rule.'),

-- General Awareness: Indian Polity and Geography
('SSC-CGL', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'The Fundamental Rights of Indian citizens are enshrined in which part of the Constitution?',
 '[{"text":"Part II","isCorrect":false},{"text":"Part III","isCorrect":true},{"text":"Part IV","isCorrect":false},{"text":"Part V","isCorrect":false}]'::jsonb,
 null, 'Fundamental Rights are enumerated in Part III of the Indian Constitution.'),
('SSC-CGL', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'The longest river flowing entirely within India is the:',
 '[{"text":"Yamuna","isCorrect":false},{"text":"Ganga","isCorrect":true},{"text":"Brahmaputra","isCorrect":false},{"text":"Godavari","isCorrect":false}]'::jsonb,
 null, 'The Ganga, at approximately 2,525 km, is the longest river flowing within India.'),
('SSC-CGL', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Who is the ceremonial (constitutional) head of the Indian state?',
 '[{"text":"The Prime Minister","isCorrect":false},{"text":"The President","isCorrect":true},{"text":"The Chief Justice of India","isCorrect":false},{"text":"The Speaker of the Lok Sabha","isCorrect":false}]'::jsonb,
 null, 'The President of India is the constitutional (ceremonial) head of state, while the Prime Minister holds real executive authority.'),
('SSC-CGL', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'The Tropic of Cancer passes through how many Indian states?',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":true},{"text":"10","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'The Tropic of Cancer passes through 8 Indian states, including Gujarat, Rajasthan, Madhya Pradesh, and West Bengal.'),

-- General Awareness: Indian Economy
('SSC-CGL', 'General Awareness', 'Indian Economy', 'medium', 'mcq',
 'The Reserve Bank of India (RBI) was established in the year:',
 '[{"text":"1935","isCorrect":true},{"text":"1947","isCorrect":false},{"text":"1950","isCorrect":false},{"text":"1969","isCorrect":false}]'::jsonb,
 null, 'The Reserve Bank of India was established in 1935 under the Reserve Bank of India Act, 1934.'),
('SSC-CGL', 'General Awareness', 'Indian Economy', 'easy', 'mcq',
 'The Goods and Services Tax (GST) in India is an example of which kind of tax?',
 '[{"text":"Direct tax","isCorrect":false},{"text":"Indirect tax","isCorrect":true},{"text":"Wealth tax","isCorrect":false},{"text":"Corporate tax","isCorrect":false}]'::jsonb,
 null, 'GST is levied on the supply of goods and services and passed on to the consumer, making it an indirect tax.'),
('SSC-CGL', 'General Awareness', 'Indian Economy', 'medium', 'mcq',
 'NITI Aayog replaced which earlier planning body of the Government of India?',
 '[{"text":"Finance Commission","isCorrect":false},{"text":"Planning Commission","isCorrect":true},{"text":"Election Commission","isCorrect":false},{"text":"National Development Council","isCorrect":false}]'::jsonb,
 null, 'NITI Aayog was established in 2015, replacing the Planning Commission as India''s premier policy think tank.'),
('SSC-CGL', 'General Awareness', 'Indian Economy', 'medium', 'mcq',
 'Inflation is best described as:',
 '[{"text":"A sustained increase in the general price level","isCorrect":true},{"text":"A sustained decrease in the general price level","isCorrect":false},{"text":"A one-time price spike only","isCorrect":false},{"text":"An increase in the value of currency","isCorrect":false}]'::jsonb,
 null, 'Inflation refers to a sustained, general rise in the price level of goods and services in an economy over time.'),

-- General Awareness: General Science and Current Affairs
('SSC-CGL', 'General Awareness', 'General Science and Current Affairs', 'easy', 'mcq',
 'The chemical formula of common salt is:',
 '[{"text":"NaCl","isCorrect":true},{"text":"KCl","isCorrect":false},{"text":"CaCl2","isCorrect":false},{"text":"NaOH","isCorrect":false}]'::jsonb,
 null, 'Common table salt is sodium chloride, with the chemical formula NaCl.'),
('SSC-CGL', 'General Awareness', 'General Science and Current Affairs', 'easy', 'mcq',
 'The SI unit of electric current is the:',
 '[{"text":"Volt","isCorrect":false},{"text":"Ampere","isCorrect":true},{"text":"Ohm","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'Electric current is measured in amperes (A), one of the seven base SI units.'),
('SSC-CGL', 'General Awareness', 'General Science and Current Affairs', 'medium', 'mcq',
 'ISRO''s Chandrayaan missions are primarily aimed at exploring:',
 '[{"text":"Mars","isCorrect":false},{"text":"The Moon","isCorrect":true},{"text":"Venus","isCorrect":false},{"text":"The Sun","isCorrect":false}]'::jsonb,
 null, 'The Chandrayaan series of missions, run by the Indian Space Research Organisation (ISRO), are dedicated to lunar exploration.'),
('SSC-CGL', 'General Awareness', 'General Science and Current Affairs', 'medium', 'mcq',
 'The headquarters of the World Health Organization (WHO) is located in:',
 '[{"text":"Geneva","isCorrect":true},{"text":"New York","isCorrect":false},{"text":"Paris","isCorrect":false},{"text":"Rome","isCorrect":false}]'::jsonb,
 null, 'The World Health Organization, a specialized agency of the United Nations, is headquartered in Geneva, Switzerland.'),

-- Quantitative Aptitude: Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)
('SSC-CGL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'easy', 'mcq',
 'If the marked price of an item is Rs. 1000 and a discount of 10% is given, the selling price is:',
 '[{"text":"Rs. 900","isCorrect":true},{"text":"Rs. 950","isCorrect":false},{"text":"Rs. 800","isCorrect":false},{"text":"Rs. 990","isCorrect":false}]'::jsonb,
 null, 'A 10% discount on Rs. 1000 is Rs. 100, so the selling price is 1000-100=900.'),
('SSC-CGL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'medium', 'mcq',
 'A sum of Rs. 5000 is invested at 10% per annum compound interest for 2 years. Find the compound interest earned.',
 '[{"text":"Rs. 1000","isCorrect":false},{"text":"Rs. 1050","isCorrect":true},{"text":"Rs. 1100","isCorrect":false},{"text":"Rs. 500","isCorrect":false}]'::jsonb,
 null, 'Amount = 5000*(1.1)^2 = 5000*1.21 = 6050; Compound Interest = 6050-5000 = 1050.'),
('SSC-CGL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'medium', 'mcq',
 'Two numbers are in the ratio 5:7. If their sum is 144, find the smaller number.',
 '[{"text":"55","isCorrect":false},{"text":"60","isCorrect":true},{"text":"65","isCorrect":false},{"text":"70","isCorrect":false}]'::jsonb,
 null, 'Let the numbers be 5x and 7x; 5x+7x=144 gives x=12, so the smaller number is 5*12=60.'),
('SSC-CGL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'hard', 'mcq',
 'If the cost price of 10 articles equals the selling price of 8 articles, find the profit percentage.',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"12.5%","isCorrect":false},{"text":"30%","isCorrect":false}]'::jsonb,
 null, '10*CP = 8*SP, so SP/CP = 10/8 = 1.25, meaning a 25% profit.'),

-- Quantitative Aptitude: Algebra
('SSC-CGL', 'Quantitative Aptitude', 'Algebra', 'medium', 'mcq',
 'Find the roots of the equation x^2 - 5x + 6 = 0.',
 '[{"text":"2 and 3","isCorrect":true},{"text":"1 and 6","isCorrect":false},{"text":"-2 and -3","isCorrect":false},{"text":"2 and -3","isCorrect":false}]'::jsonb,
 null, 'Factoring x^2-5x+6=(x-2)(x-3)=0 gives roots x=2 and x=3.'),
('SSC-CGL', 'Quantitative Aptitude', 'Algebra', 'easy', 'mcq',
 'Simplify: (a+b)^2 - (a-b)^2.',
 '[{"text":"2ab","isCorrect":false},{"text":"4ab","isCorrect":true},{"text":"a^2+b^2","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'Expanding both squares: (a^2+2ab+b^2) - (a^2-2ab+b^2) = 4ab.'),
('SSC-CGL', 'Quantitative Aptitude', 'Algebra', 'easy', 'mcq',
 'If 2x + 3y = 12 and x = 3, find the value of y.',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"3","isCorrect":false},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'Substituting x=3: 2*3+3y=12, so 6+3y=12, giving 3y=6 and y=2.'),
('SSC-CGL', 'Quantitative Aptitude', 'Algebra', 'easy', 'mcq',
 'Find the value of x if 3x - 7 = 11.',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":true},{"text":"7","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, '3x-7=11 gives 3x=18, so x=6.'),

-- Quantitative Aptitude: Geometry and Mensuration
('SSC-CGL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'The sum of the interior angles of a triangle is:',
 '[{"text":"90 degrees","isCorrect":false},{"text":"180 degrees","isCorrect":true},{"text":"270 degrees","isCorrect":false},{"text":"360 degrees","isCorrect":false}]'::jsonb,
 null, 'The interior angles of any triangle always sum to 180 degrees.'),
('SSC-CGL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'The area of a circle with radius r is given by:',
 '[{"text":"2*pi*r","isCorrect":false},{"text":"pi*r^2","isCorrect":true},{"text":"pi*r","isCorrect":false},{"text":"4*pi*r^2","isCorrect":false}]'::jsonb,
 null, 'The area of a circle is given by the formula pi*r^2, where r is the radius.'),
('SSC-CGL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'The volume of a cube with side length 4 cm is:',
 '[{"text":"16 cubic cm","isCorrect":false},{"text":"48 cubic cm","isCorrect":false},{"text":"64 cubic cm","isCorrect":true},{"text":"32 cubic cm","isCorrect":false}]'::jsonb,
 null, 'Volume of a cube = side^3 = 4^3 = 64 cubic cm.'),
('SSC-CGL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'In a right triangle, the side opposite the right angle is called the:',
 '[{"text":"Base","isCorrect":false},{"text":"Hypotenuse","isCorrect":true},{"text":"Perpendicular","isCorrect":false},{"text":"Altitude","isCorrect":false}]'::jsonb,
 null, 'The hypotenuse is the longest side of a right triangle, situated opposite the 90-degree angle.'),

-- Quantitative Aptitude: Trigonometry and Data Interpretation
('SSC-CGL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'easy', 'mcq',
 'The value of sin(0 degrees) is:',
 '[{"text":"0","isCorrect":true},{"text":"1","isCorrect":false},{"text":"Undefined","isCorrect":false},{"text":"-1","isCorrect":false}]'::jsonb,
 null, 'sin(0 degrees) equals 0, a standard trigonometric value.'),
('SSC-CGL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'medium', 'mcq',
 'A bar graph shows sales of 200 units in Q1 and 250 units in Q2. Find the percentage increase in sales.',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"30%","isCorrect":false},{"text":"50%","isCorrect":false}]'::jsonb,
 null, 'Percentage increase = (250-200)/200 * 100 = 25%.'),
('SSC-CGL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'easy', 'mcq',
 'The value of tan(45 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"sqrt(3)","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'tan(45 degrees) = sin(45)/cos(45) = 1, a standard trigonometric value.'),
('SSC-CGL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'medium', 'mcq',
 'The average of 3 numbers is 18. If two of the numbers are 15 and 20, find the third number.',
 '[{"text":"17","isCorrect":false},{"text":"19","isCorrect":true},{"text":"21","isCorrect":false},{"text":"16","isCorrect":false}]'::jsonb,
 null, 'Total sum = 18*3 = 54; third number = 54-15-20 = 19.'),

-- English Comprehension: Grammar and Error Spotting
('SSC-CGL', 'English Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Identify the error in the sentence: "She don''t like coffee."',
 '[{"text":"''She'' should be ''Her''","isCorrect":false},{"text":"''don''t'' should be ''doesn''t''","isCorrect":true},{"text":"''like'' should be ''likes'' and ''don''t'' should stay","isCorrect":false},{"text":"There is no error","isCorrect":false}]'::jsonb,
 null, 'With the third-person singular subject "She", the correct auxiliary verb is "doesn''t", not "don''t".'),
('SSC-CGL', 'English Comprehension', 'Grammar and Error Spotting', 'hard', 'mcq',
 'Choose the correct verb to complete: "Neither the manager nor the employees ___ available."',
 '[{"text":"is","isCorrect":false},{"text":"are","isCorrect":true},{"text":"was","isCorrect":false},{"text":"has been","isCorrect":false}]'::jsonb,
 null, 'With "neither...nor", the verb agrees with the subject nearer to it -- here "employees" (plural), so "are" is correct.'),
('SSC-CGL', 'English Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Which of the following sentences is grammatically correct?',
 '[{"text":"He has been working here since five years.","isCorrect":false},{"text":"He has been working here for five years.","isCorrect":true},{"text":"He is working here since five years.","isCorrect":false},{"text":"He has working here for five years.","isCorrect":false}]'::jsonb,
 null, '"For" is used with a duration of time (five years), while "since" is used with a specific starting point in time (like a year or date).'),
('SSC-CGL', 'English Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Choose the correct form to complete: "If I ___ rich, I would travel the world."',
 '[{"text":"am","isCorrect":false},{"text":"was","isCorrect":false},{"text":"were","isCorrect":true},{"text":"be","isCorrect":false}]'::jsonb,
 null, 'In a hypothetical (subjunctive mood) conditional sentence, "were" is used regardless of subject, as in "If I were rich...".'),

-- English Comprehension: Vocabulary (Synonyms, Antonyms, One-word Substitution)
('SSC-CGL', 'English Comprehension', 'Vocabulary (Synonyms, Antonyms, One-word Substitution)', 'medium', 'mcq',
 'Choose the word closest in meaning to "Abundant".',
 '[{"text":"Scarce","isCorrect":false},{"text":"Plentiful","isCorrect":true},{"text":"Minimal","isCorrect":false},{"text":"Rare","isCorrect":false}]'::jsonb,
 null, '"Abundant" means existing in large quantities; "plentiful" is its closest synonym.'),
('SSC-CGL', 'English Comprehension', 'Vocabulary (Synonyms, Antonyms, One-word Substitution)', 'medium', 'mcq',
 'Choose the antonym of "Genuine".',
 '[{"text":"Authentic","isCorrect":false},{"text":"Fake","isCorrect":true},{"text":"Real","isCorrect":false},{"text":"Sincere","isCorrect":false}]'::jsonb,
 null, '"Genuine" means authentic or real; its antonym is "fake", meaning not genuine or counterfeit.'),
('SSC-CGL', 'English Comprehension', 'Vocabulary (Synonyms, Antonyms, One-word Substitution)', 'medium', 'mcq',
 'Choose the one word that means "a person who studies and treats diseases of the heart".',
 '[{"text":"Neurologist","isCorrect":false},{"text":"Cardiologist","isCorrect":true},{"text":"Dermatologist","isCorrect":false},{"text":"Pediatrician","isCorrect":false}]'::jsonb,
 null, 'A cardiologist is a medical specialist who studies and treats diseases and disorders of the heart.'),
('SSC-CGL', 'English Comprehension', 'Vocabulary (Synonyms, Antonyms, One-word Substitution)', 'hard', 'mcq',
 'Choose the one word that means "one who cannot be corrected".',
 '[{"text":"Incorrigible","isCorrect":true},{"text":"Incredible","isCorrect":false},{"text":"Inevitable","isCorrect":false},{"text":"Indelible","isCorrect":false}]'::jsonb,
 null, '"Incorrigible" describes a person or habit that cannot be corrected, reformed, or controlled.'),

-- English Comprehension: Cloze Test and Fill in the Blanks
('SSC-CGL', 'English Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "She has been living in Delhi ___ 2015."',
 '[{"text":"since","isCorrect":true},{"text":"for","isCorrect":false},{"text":"from","isCorrect":false},{"text":"at","isCorrect":false}]'::jsonb,
 null, '"Since" is used with a specific point in time (2015), correctly indicating when the action began.'),
('SSC-CGL', 'English Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "He is good ___ mathematics."',
 '[{"text":"in","isCorrect":false},{"text":"at","isCorrect":true},{"text":"on","isCorrect":false},{"text":"with","isCorrect":false}]'::jsonb,
 null, 'The idiomatic preposition used with "good" to describe skill in a subject is "at" -- "good at mathematics".'),
('SSC-CGL', 'English Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "The train arrived ___ time."',
 '[{"text":"in","isCorrect":false},{"text":"on","isCorrect":true},{"text":"at","isCorrect":false},{"text":"by","isCorrect":false}]'::jsonb,
 null, 'The idiomatic phrase "on time" means punctually, as expected.'),
('SSC-CGL', 'English Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "They congratulated him ___ his success."',
 '[{"text":"for","isCorrect":false},{"text":"on","isCorrect":true},{"text":"at","isCorrect":false},{"text":"about","isCorrect":false}]'::jsonb,
 null, 'The idiomatic preposition used with "congratulate" is "on" -- "congratulated him on his success".'),

-- English Comprehension: Reading Comprehension and Para Jumbles
('SSC-CGL', 'English Comprehension', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'Read the passage: "Discipline is not about punishment; it is about teaching individuals to make better choices through structure and consistency." According to the passage, discipline is fundamentally about:',
 '[{"text":"Punishing wrongdoing severely","isCorrect":false},{"text":"Teaching better choices through structure and consistency","isCorrect":true},{"text":"Avoiding all rules entirely","isCorrect":false},{"text":"Enforcing strict, unchanging punishment","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states discipline is about teaching better choices through structure and consistency, not punishment.'),
('SSC-CGL', 'English Comprehension', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'Arrange the sentences into a coherent paragraph: (P) Then he decided to start his own business. (Q) After graduating, Ravi worked for a multinational company. (R) He struggled initially but eventually succeeded. (S) His dedication paid off within a few years. Choose the correct sequence.',
 '[{"text":"Q, P, R, S","isCorrect":true},{"text":"P, Q, R, S","isCorrect":false},{"text":"Q, R, P, S","isCorrect":false},{"text":"S, Q, P, R","isCorrect":false}]'::jsonb,
 null, 'The logical order is: Ravi works after graduating (Q), then starts his own business (P), struggles but succeeds (R), and his dedication pays off (S).'),
('SSC-CGL', 'English Comprehension', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'Read the passage: "The rise of remote work has changed how companies evaluate employee productivity, shifting focus from hours logged to actual output delivered." According to the passage, the primary shift in productivity evaluation is from:',
 '[{"text":"Output delivered to hours logged","isCorrect":false},{"text":"Hours logged to output delivered","isCorrect":true},{"text":"In-office work to no evaluation at all","isCorrect":false},{"text":"Salary to bonuses","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states the shift is "from hours logged to actual output delivered".'),
('SSC-CGL', 'English Comprehension', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'Arrange the sentences into a coherent paragraph: (P) It began raining heavily. (Q) We decided to cancel the picnic. (R) We had planned a picnic for the weekend. (S) As a result, we stayed indoors. Choose the correct sequence.',
 '[{"text":"R, P, Q, S","isCorrect":true},{"text":"P, R, Q, S","isCorrect":false},{"text":"R, Q, P, S","isCorrect":false},{"text":"S, R, P, Q","isCorrect":false}]'::jsonb,
 null, 'The logical order is: a picnic was planned (R), heavy rain began (P), the picnic was cancelled (Q), and as a result they stayed indoors (S).');
