-- supabase/sql/exam_question_bank_jee_advanced_set2.sql
--
-- Second curated question-bank batch for 'JEE Advanced' (see exam_patterns_jee_advanced.sql for
-- the exam's structure, and exam_question_bank_jee_advanced_set1.sql for the first batch -- same
-- table/schema, no migration needed). All-new questions, no overlap with Set 1.
--
-- Same format as Set 1: EVERY chapter gets one single-correct MCQ AND one genuine multi-correct
-- "which of the following statement(s) is/are TRUE" MCQ (format='mcq' with more than one option
-- marked isCorrect), plus a numerical-answer question and a short-answer descriptive one.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_jee_advanced.sql and
-- exam_question_bank_jee_advanced_set1.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'mcq',
 'A uniform solid sphere of mass $M$ and radius $R$ rolls without slipping down an incline of height $h$. Find its speed at the bottom, using $I=\frac{2}{5}MR^2$.',
 '[{"text":"sqrt(10gh/7)","isCorrect":true},{"text":"sqrt(2gh)","isCorrect":false},{"text":"sqrt(4gh/3)","isCorrect":false},{"text":"sqrt(gh)","isCorrect":false}]'::jsonb,
 null, 'Energy conservation: Mgh = (1/2)Mv^2 + (1/2)(2/5)MR^2*(v/R)^2 = (7/10)Mv^2, so v = sqrt(10gh/7).'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'mcq',
 'A solid sphere and a hollow sphere of the same mass and radius roll without slipping down the same incline from rest. Which of the following statement(s) is/are TRUE? (A) The solid sphere reaches the bottom first. (B) The hollow sphere has a larger moment of inertia. (C) Both spheres reach the bottom with the same total kinetic energy. (D) The frictional force does positive work on the rolling spheres.',
 '[{"text":"(A) Solid sphere reaches bottom first","isCorrect":true},{"text":"(B) Hollow sphere has larger moment of inertia","isCorrect":true},{"text":"(C) Both reach bottom with same total KE","isCorrect":true},{"text":"(D) Friction does positive work on rolling spheres","isCorrect":false}]'::jsonb,
 null, 'The solid sphere (smaller I/MR^2 = 2/5) converts more PE to translational KE and accelerates faster, reaching bottom first (A true). The hollow sphere has I=(2/3)MR^2, larger than the solid sphere''s (2/5)MR^2 (B true). Since both start with the same PE and no energy is lost (pure rolling, static friction does no work), total KE at the bottom is the same, just split differently between translation and rotation (C true). Static friction on a purely rolling body does ZERO work, not positive work (D false).'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'numerical',
 'A disc ($I=\frac{1}{2}MR^2$) rolls without slipping down an incline of height $h=5$ m. Find its speed (in m/s, nearest integer) at the bottom, using $g=10\,m/s^2$.',
 null, '8', 'v = sqrt(4gh/3) = sqrt(4*10*5/3) = sqrt(66.7) is approximately 8.2, rounding to 8.'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'descriptive',
 'Explain why, for objects rolling without slipping down an incline, the object with the smaller moment of inertia (relative to its mass and radius) reaches the bottom first.',
 null, null, 'For rolling without slipping, the available gravitational potential energy is split between translational and rotational kinetic energy. An object with a smaller moment of inertia needs less energy to spin up to the required angular velocity (since v=omega*R at all times), so a larger fraction of the potential energy converts to translational kinetic energy, giving it a higher linear speed and acceleration, so it reaches the bottom sooner.'),

-- Physics: Electrodynamics
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'mcq',
 'A long straight current-carrying wire produces a magnetic field at distance $r$ that is:',
 '[{"text":"Independent of r","isCorrect":false},{"text":"Directly proportional to r","isCorrect":false},{"text":"Inversely proportional to r","isCorrect":true},{"text":"Inversely proportional to r^2","isCorrect":false}]'::jsonb,
 null, 'By Ampere''s law, B = mu0*I/(2*pi*r), which is inversely proportional to r.'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'mcq',
 'A conducting rod slides on frictionless rails in a uniform magnetic field perpendicular to the plane, inducing an EMF. Which of the following statement(s) is/are TRUE? (A) The induced EMF opposes the change in flux, by Lenz''s law. (B) The induced current creates a force on the rod that opposes its motion. (C) If the rod moves at constant velocity under an external force, the external force does work that is fully converted to electrical energy dissipated in the circuit. (D) The induced EMF is independent of the rod''s velocity.',
 '[{"text":"(A) Induced EMF opposes flux change","isCorrect":true},{"text":"(B) Induced current force opposes motion","isCorrect":true},{"text":"(C) External work fully converts to dissipated electrical energy","isCorrect":true},{"text":"(D) EMF independent of velocity","isCorrect":false}]'::jsonb,
 null, 'Lenz''s law states the induced EMF opposes the change in flux (A true), which manifests as a retarding force on the rod (B true). At constant velocity, the net force is zero, so the external force exactly balances the magnetic retarding force, and by energy conservation all the external work converts to electrical energy dissipated as heat in the resistance (C true). EMF = B*L*v is directly proportional to velocity, not independent of it (D false).'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'numerical',
 'A rod of length $L=0.5$ m moves at $v=4$ m/s perpendicular to a magnetic field $B=2$ T. Find the induced EMF (in volts).',
 null, '4', 'EMF = B*L*v = 2*0.5*4 = 4 V.'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'descriptive',
 'Explain the physical origin of the retarding force on a current-carrying rod moving through a magnetic field, and how this connects to the conservation of energy.',
 null, null, 'As the rod moves, it generates an induced current (via the motional EMF), and this current, flowing through the external magnetic field, experiences a force via F=IL x B, directed opposite to the rod''s velocity by Lenz''s law. This retarding force means an external agent must do work to keep the rod moving, and that mechanical work is exactly converted into electrical energy (ultimately dissipated as heat), consistent with energy conservation.'),

-- Physics: Modern Physics
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'mcq',
 'A radioactive sample has a half-life of 10 days. What fraction of the original sample remains after 30 days?',
 '[{"text":"1/2","isCorrect":false},{"text":"1/4","isCorrect":false},{"text":"1/8","isCorrect":true},{"text":"1/16","isCorrect":false}]'::jsonb,
 null, '30 days is 3 half-lives, so the remaining fraction is (1/2)^3 = 1/8.'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'mcq',
 'Regarding nuclear binding energy, which of the following statement(s) is/are TRUE? (A) Binding energy per nucleon is highest for nuclei of intermediate mass number, around iron. (B) Fusion of light nuclei into an intermediate-mass nucleus releases energy. (C) Fission of a very heavy nucleus into two intermediate-mass nuclei releases energy. (D) Binding energy per nucleon increases monotonically with mass number for all nuclei.',
 '[{"text":"(A) Peak binding energy near iron","isCorrect":true},{"text":"(B) Fusion of light nuclei releases energy","isCorrect":true},{"text":"(C) Fission of heavy nuclei releases energy","isCorrect":true},{"text":"(D) Binding energy per nucleon increases monotonically","isCorrect":false}]'::jsonb,
 null, 'The binding energy per nucleon curve peaks near iron-56 (A true). Both fusing light nuclei (moving up toward the peak) and fissioning heavy nuclei (moving down toward the peak from the other side) release energy, since both processes move toward higher binding energy per nucleon (B, C true). The curve rises then falls, it does not increase monotonically (D false).'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'numerical',
 'A radioactive nucleus has decay constant $\lambda=0.0231$ per day. Find its half-life (in days, nearest integer), using $t_{1/2}=0.693/\lambda$.',
 null, '30', 't(1/2) = 0.693/0.0231 is approximately 30.'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'descriptive',
 'Explain, using the concept of binding energy per nucleon, why both nuclear fusion of light elements and nuclear fission of heavy elements release energy.',
 null, null, 'The binding energy per nucleon curve rises sharply for light nuclei, peaks near iron, and falls slowly for heavy nuclei. When light nuclei fuse into a heavier one closer to the peak, the binding energy per nucleon increases, releasing the difference as energy. Similarly, when a heavy nucleus splits into two intermediate-mass fragments closer to the peak, binding energy per nucleon also increases, again releasing energy -- both processes move the nucleons toward the more tightly bound configuration near iron.'),

-- Physics: Heat and Thermodynamics
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'For an adiabatic process on an ideal gas, which relation holds?',
 '[{"text":"PV = constant","isCorrect":false},{"text":"PV^gamma = constant","isCorrect":true},{"text":"P/V = constant","isCorrect":false},{"text":"TV = constant","isCorrect":false}]'::jsonb,
 null, 'For an adiabatic process, PV^gamma = constant, where gamma is the ratio of specific heats.'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'hard', 'mcq',
 'An ideal gas expands adiabatically. Which of the following statement(s) is/are TRUE? (A) No heat is exchanged with the surroundings. (B) The temperature of the gas decreases. (C) The work done by the gas equals the decrease in its internal energy. (D) The process can be represented by a curve on a P-V diagram that is less steep than the corresponding isothermal curve.',
 '[{"text":"(A) No heat exchanged","isCorrect":true},{"text":"(B) Temperature decreases","isCorrect":true},{"text":"(C) Work done equals decrease in internal energy","isCorrect":true},{"text":"(D) Adiabatic curve less steep than isothermal","isCorrect":false}]'::jsonb,
 null, 'By definition, an adiabatic process has Q=0 (A true). Since the gas does positive work on expansion with no heat input, internal energy (and hence temperature) decreases (B true), and by the first law, W = -delta(U), i.e. work done by the gas equals the decrease in internal energy (C true). The adiabatic curve is actually STEEPER than the isothermal curve at any given point, not less steep, since gamma > 1 (D false).'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'medium', 'numerical',
 'One mole of a monatomic ideal gas ($C_v=\frac{3}{2}R$) is heated at constant volume, raising its temperature by 100 K. Find the heat absorbed (in J), using $R=8.314\,J/(mol\cdot K)$ (nearest whole number).',
 null, '1247', 'Q = n*Cv*deltaT = 1*(3/2)*8.314*100 = 1247.1, rounding to 1247.'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'hard', 'descriptive',
 'Explain why an adiabatic P-V curve is steeper than an isothermal P-V curve at any point where they intersect.',
 null, null, 'For an isotherm, PV=constant gives a slope of dP/dV=-P/V. For an adiabat, PV^gamma=constant gives a slope of dP/dV=-gamma*P/V, which is steeper by a factor of gamma (greater than 1 for any real gas). Physically, in an adiabatic expansion the gas cools as it does work with no heat input, so pressure drops faster with increasing volume compared to an isothermal expansion where temperature is maintained by heat exchange.'),

-- Physics: Optics
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'mcq',
 'A convex lens of focal length 20 cm forms a real image of an object placed at 30 cm. Find the image distance (in cm).',
 '[{"text":"60","isCorrect":true},{"text":"12","isCorrect":false},{"text":"50","isCorrect":false},{"text":"40","isCorrect":false}]'::jsonb,
 null, 'Using 1/v - 1/u = 1/f with u=-30, f=20: 1/v = 1/20 - 1/30 = 1/60, so v=60 cm.'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'hard', 'mcq',
 'Regarding a convex lens forming images of a real object, which of the following statement(s) is/are TRUE? (A) If the object is placed beyond $2f$, the image is real, inverted, and diminished. (B) If the object is placed at $f$, the image forms at infinity. (C) If the object is placed between $f$ and $2f$, the image is real, inverted, and magnified. (D) A convex lens can never form a virtual image.',
 '[{"text":"(A) Beyond 2f gives real, inverted, diminished image","isCorrect":true},{"text":"(B) At f, image forms at infinity","isCorrect":true},{"text":"(C) Between f and 2f gives real, inverted, magnified image","isCorrect":true},{"text":"(D) Convex lens never forms virtual image","isCorrect":false}]'::jsonb,
 null, 'For an object beyond 2f, the image forms between f and 2f on the other side, real, inverted, and smaller (A true). At exactly f, rays emerge parallel, forming the image at infinity (B true). Between f and 2f, the image forms beyond 2f, real, inverted, and magnified (C true). A convex lens DOES form a virtual, magnified image when the object is placed within the focal length (like a magnifying glass), so (D) is false.'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'numerical',
 'A convex lens has focal length 10 cm. An object is placed at 15 cm. Find the magnitude of the magnification (as a decimal, nearest tenth).',
 null, '2', 'v = (1/f+1/u)^-1... using 1/v=1/10-1/15=1/30, v=30. Magnification = v/u = 30/15 = 2.'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'descriptive',
 'Explain why a convex lens forms a virtual, magnified, upright image when the object is placed within its focal length, using ray diagram reasoning.',
 null, null, 'When the object lies within the focal length, the refracted rays from the lens diverge rather than converge on the far side. Tracing these diverging rays backward, they appear to originate from a point behind the object on the same side as the object, producing a virtual image that is upright and magnified -- this is the principle behind a simple magnifying glass.'),

-- Physics: Waves and Oscillations
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'medium', 'mcq',
 'Two sound waves of frequencies 256 Hz and 260 Hz are superposed. Find the beat frequency (in Hz).',
 '[{"text":"2","isCorrect":false},{"text":"4","isCorrect":true},{"text":"258","isCorrect":false},{"text":"516","isCorrect":false}]'::jsonb,
 null, 'Beat frequency equals the difference of the two frequencies: 260-256=4 Hz.'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'hard', 'mcq',
 'A stretched string fixed at both ends vibrates in its second harmonic (first overtone). Which of the following statement(s) is/are TRUE? (A) There are 2 nodes and 1 antinode, excluding the two fixed ends. (B) The wavelength equals the length of the string. (C) The frequency is twice the fundamental frequency. (D) The frequency depends on the tension in the string.',
 '[{"text":"(A) 2 nodes and 1 antinode excluding fixed ends","isCorrect":false},{"text":"(B) Wavelength equals string length","isCorrect":true},{"text":"(C) Frequency is twice the fundamental","isCorrect":true},{"text":"(D) Frequency depends on tension","isCorrect":true}]'::jsonb,
 null, 'In the second harmonic, there is exactly 1 additional node at the midpoint (excluding the two fixed ends), not 2 nodes -- so (A) is false. The wavelength equals the string length L (since L=2*lambda/2=lambda) (B true). Its frequency is exactly twice the fundamental (C true), and frequency f=(n/2L)*sqrt(T/mu) depends on tension T (D true).'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'medium', 'numerical',
 'A string of length 1 m fixed at both ends vibrates in its fundamental mode with wave speed 200 m/s. Find the fundamental frequency (in Hz).',
 null, '100', 'f = v/(2L) = 200/(2*1) = 100 Hz.'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'hard', 'descriptive',
 'Explain the phenomenon of beats and derive, conceptually, why the beat frequency equals the difference between the two individual frequencies.',
 null, null, 'Beats arise from the superposition of two waves of slightly different frequencies, which periodically go in and out of phase, causing the resultant amplitude to rise and fall. The resulting amplitude envelope repeats at a rate equal to the difference between the two frequencies, since that is exactly the rate at which the phase difference between the two waves completes a full cycle of 2*pi, bringing them back into phase.'),

-- Physics: Properties of Matter and Fluids
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'medium', 'mcq',
 'A wire of length $L$ and cross-sectional area $A$ is stretched by a force $F$, producing an extension $\Delta L$. Young''s modulus is given by:',
 '[{"text":"F*L/(A*deltaL)","isCorrect":true},{"text":"F*A/(L*deltaL)","isCorrect":false},{"text":"F*deltaL/(A*L)","isCorrect":false},{"text":"A*deltaL/(F*L)","isCorrect":false}]'::jsonb,
 null, 'Young''s modulus Y = stress/strain = (F/A)/(deltaL/L) = F*L/(A*deltaL).'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'hard', 'mcq',
 'Regarding a liquid flowing through a horizontal pipe of varying cross-section (ideal, incompressible, non-viscous flow), which of the following statement(s) is/are TRUE? (A) The volume flow rate is the same at every cross-section (equation of continuity). (B) The velocity is higher where the cross-sectional area is smaller. (C) The pressure is higher where the velocity is higher (Bernoulli''s principle). (D) The sum of pressure energy, kinetic energy, and potential energy per unit volume is constant along a streamline.',
 '[{"text":"(A) Flow rate same at every cross-section","isCorrect":true},{"text":"(B) Velocity higher where area is smaller","isCorrect":true},{"text":"(C) Pressure higher where velocity is higher","isCorrect":false},{"text":"(D) Sum of pressure, kinetic, potential energy constant along streamline","isCorrect":true}]'::jsonb,
 null, 'The equation of continuity (A*v=constant) means flow rate is conserved (A true), so velocity increases where area decreases (B true). By Bernoulli''s principle, pressure is LOWER where velocity is higher, not higher, so (C) is false. Bernoulli''s equation states the sum P + (1/2)*rho*v^2 + rho*g*h is constant along a streamline (D true).'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'medium', 'numerical',
 'Water flows through a horizontal pipe that narrows from area $4\,cm^2$ to $2\,cm^2$. If the velocity in the wider section is 3 m/s, find the velocity (in m/s) in the narrower section.',
 null, '6', 'By continuity, A1*v1=A2*v2: 4*3=2*v2, giving v2=6 m/s.'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'hard', 'descriptive',
 'Explain Bernoulli''s principle conceptually, and describe why a fluid''s pressure decreases as its speed increases in horizontal flow.',
 null, null, 'Bernoulli''s principle follows from energy conservation applied to a moving, incompressible, non-viscous fluid: the total energy per unit volume (pressure energy plus kinetic energy plus potential energy) stays constant along a streamline. In horizontal flow, potential energy is constant, so as kinetic energy per unit volume increases (fluid speeds up, e.g. through a narrowing pipe), the pressure energy per unit volume must decrease to compensate, meaning pressure drops as speed increases.'),

-- Chemistry: Physical Chemistry
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'mcq',
 'For the equilibrium $N_2+3H_2 \rightleftharpoons 2NH_3$, increasing the pressure of the system shifts equilibrium:',
 '[{"text":"Toward reactants","isCorrect":false},{"text":"Toward products","isCorrect":true},{"text":"No shift occurs","isCorrect":false},{"text":"Depends on temperature only","isCorrect":false}]'::jsonb,
 null, 'Increasing pressure shifts equilibrium toward the side with fewer moles of gas -- here, products (2 moles vs 4 moles of reactants).'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'hard', 'mcq',
 'Regarding Le Chatelier''s principle applied to a gaseous equilibrium, which of the following statement(s) is/are TRUE? (A) Adding an inert gas at constant volume does not shift the equilibrium. (B) Increasing temperature shifts an exothermic equilibrium toward the reactants. (C) Adding a catalyst shifts the equilibrium toward the products. (D) Removing a product as it forms shifts the equilibrium further toward the products.',
 '[{"text":"(A) Inert gas at constant volume does not shift equilibrium","isCorrect":true},{"text":"(B) Higher temperature shifts exothermic equilibrium toward reactants","isCorrect":true},{"text":"(C) Catalyst shifts equilibrium toward products","isCorrect":false},{"text":"(D) Removing product shifts equilibrium further toward products","isCorrect":true}]'::jsonb,
 null, 'Adding inert gas at constant volume does not change partial pressures of reactants/products, so no shift occurs (A true). Raising temperature on an exothermic reaction favors the endothermic (reverse) direction, shifting toward reactants (B true). A catalyst speeds up both forward and reverse reactions equally and does NOT shift equilibrium position at all (C false). Removing product continuously drives the reaction forward to replace it, per Le Chatelier (D true).'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'numerical',
 'For a reaction with $K_c=4$ at equilibrium in a 1 L vessel, if $[A]=2$ M and $[B]=1$ M for $A \rightleftharpoons B$... find $[B]$ if $[A]$ is changed to 1 M and equilibrium is re-established, keeping $K_c$ fixed (answer as a number).',
 null, '4', 'Kc = [B]/[A] = 4, so at [A]=1, [B] = 4*1 = 4 M.'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'descriptive',
 'Explain why a catalyst speeds up a reaction without changing the equilibrium constant or the equilibrium position.',
 null, null, 'A catalyst provides an alternative reaction pathway with lower activation energy, speeding up both the forward and reverse reactions by the same factor. Since it accelerates both directions equally, the ratio of rate constants (which determines the equilibrium constant) is unchanged, so the equilibrium position and the value of K remain exactly the same -- the catalyst only affects how fast equilibrium is reached, not where it lies.'),

-- Chemistry: Organic Chemistry
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'mcq',
 'Which reagent is used to distinguish between an aldehyde and a ketone?',
 '[{"text":"Tollens'' reagent","isCorrect":true},{"text":"Sodium metal","isCorrect":false},{"text":"Bromine water only","isCorrect":false},{"text":"Dilute HCl","isCorrect":false}]'::jsonb,
 null, 'Tollens'' reagent (ammoniacal silver nitrate) gives a silver mirror with aldehydes but not with ketones, since aldehydes are more easily oxidized.'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'mcq',
 'Regarding nucleophilic addition to aldehydes and ketones, which of the following statement(s) is/are TRUE? (A) Aldehydes are generally more reactive than ketones toward nucleophilic addition. (B) Steric hindrance from bulky alkyl groups decreases reactivity toward nucleophilic addition. (C) Electron-donating alkyl groups increase the electrophilicity of the carbonyl carbon. (D) The carbonyl carbon becomes sp3 hybridized after nucleophilic addition.',
 '[{"text":"(A) Aldehydes more reactive than ketones","isCorrect":true},{"text":"(B) Steric hindrance decreases reactivity","isCorrect":true},{"text":"(C) Electron-donating groups increase electrophilicity","isCorrect":false},{"text":"(D) Carbonyl carbon becomes sp3 after addition","isCorrect":true}]'::jsonb,
 null, 'Aldehydes are less sterically hindered and less electronically stabilized than ketones, making them more reactive toward nucleophilic addition (A true), and bulkier alkyl groups further hinder approach of the nucleophile, decreasing reactivity (B true). Electron-donating alkyl groups actually DEcrease electrophilicity of the carbonyl carbon by donating electron density, not increase it, so (C) is false. After addition, the carbonyl carbon goes from sp2 (planar, trigonal) to sp3 (tetrahedral) (D true).'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'numerical',
 'How many moles of Tollens'' reagent (Ag+) are reduced per mole of a simple aldehyde RCHO undergoing the silver mirror test, given the reaction produces 2 Ag atoms per aldehyde?',
 null, '2', 'The silver mirror test reduces 2 moles of Ag+ per mole of aldehyde oxidized to the carboxylate.'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'descriptive',
 'Explain why aldehydes are generally more reactive than ketones toward nucleophilic addition reactions, considering both steric and electronic factors.',
 null, null, 'Aldehydes have only one alkyl (or aryl) group and one hydrogen attached to the carbonyl carbon, while ketones have two alkyl groups. Electronically, alkyl groups are electron-donating, so ketones have a less electrophilic carbonyl carbon than aldehydes, making it less attractive to nucleophiles. Sterically, the two alkyl groups in ketones create more hindrance around the carbonyl carbon than the single alkyl group and small hydrogen in aldehydes, further slowing nucleophilic attack.'),

-- Chemistry: Inorganic Chemistry
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'mcq',
 'Which of the following has a linear molecular geometry?',
 '[{"text":"H2O","isCorrect":false},{"text":"CO2","isCorrect":true},{"text":"NH3","isCorrect":false},{"text":"CH4","isCorrect":false}]'::jsonb,
 null, 'CO2 has two electron domains around carbon with no lone pairs, giving a linear geometry with 180 degree bond angle.'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'mcq',
 'Regarding VSEPR theory applied to $NH_3$ and $H_2O$, which of the following statement(s) is/are TRUE? (A) Both molecules have a tetrahedral electron geometry. (B) $NH_3$ has a trigonal pyramidal molecular shape due to one lone pair. (C) $H_2O$ has a smaller bond angle than $NH_3$ due to two lone pairs. (D) Lone pair-lone pair repulsion is weaker than lone pair-bond pair repulsion.',
 '[{"text":"(A) Both have tetrahedral electron geometry","isCorrect":true},{"text":"(B) NH3 is trigonal pyramidal due to one lone pair","isCorrect":true},{"text":"(C) H2O has smaller bond angle due to two lone pairs","isCorrect":true},{"text":"(D) Lone pair-lone pair repulsion weaker than lone pair-bond pair","isCorrect":false}]'::jsonb,
 null, 'Both NH3 (4 electron domains: 3 bonds + 1 lone pair) and H2O (4 domains: 2 bonds + 2 lone pairs) have tetrahedral electron geometry at the central atom (A true). NH3''s one lone pair compresses the bond angle to about 107 degrees, giving trigonal pyramidal shape (B true), while H2O''s two lone pairs compress it further to about 104.5 degrees, smaller than NH3''s (C true). The actual repulsion order is lone pair-lone pair > lone pair-bond pair > bond pair-bond pair, so lone pair-lone pair repulsion is STRONGER, not weaker (D false).'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'numerical',
 'Find the number of lone pairs on the central atom in a water molecule ($H_2O$).',
 null, '2', 'Oxygen in water has 2 bonding pairs (to each H) and 2 lone pairs, out of its total 4 electron domains.'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'descriptive',
 'Explain, using VSEPR theory, why the H-O-H bond angle in water (about 104.5 degrees) is smaller than the H-N-H bond angle in ammonia (about 107 degrees), even though both are derived from a tetrahedral electron geometry.',
 null, null, 'Both molecules start from a tetrahedral electron-domain geometry (ideal angle 109.5 degrees), but lone pairs repel more strongly than bonding pairs since they are held closer to the central atom and spread out more. Water has two lone pairs compressing the remaining bond angle, while ammonia has only one lone pair doing so -- since water experiences more total lone-pair repulsion pushing the bonding pairs closer together, its bond angle is compressed more than ammonia''s.'),

-- Mathematics: Algebra
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'mcq',
 'Find the coefficient of $x^3$ in the expansion of $(1+x)^7$.',
 '[{"text":"21","isCorrect":false},{"text":"35","isCorrect":true},{"text":"7","isCorrect":false},{"text":"56","isCorrect":false}]'::jsonb,
 null, 'The coefficient of x^3 is C(7,3) = 35.'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'hard', 'mcq',
 'For a $2\times2$ matrix $A$ with $\det(A)=0$, which of the following statement(s) is/are TRUE? (A) $A$ is singular, i.e. not invertible. (B) The rows of $A$ are linearly dependent. (C) $A$ can still have a non-zero solution to $A\vec{x}=\vec{0}$. (D) $A^2$ always has determinant equal to $\det(A)$.',
 '[{"text":"(A) A is singular","isCorrect":true},{"text":"(B) Rows are linearly dependent","isCorrect":true},{"text":"(C) A*x=0 can have non-zero solution","isCorrect":true},{"text":"(D) det(A^2) always equals det(A)","isCorrect":false}]'::jsonb,
 null, 'A zero determinant means A has no inverse, i.e. it is singular (A true), which happens precisely when its rows (or columns) are linearly dependent (B true). A singular matrix always has a non-trivial null space, so Ax=0 has non-zero solutions (C true). Since det(A^2)=det(A)^2=0^2=0, it does equal det(A)=0 in THIS specific case, but the general claim "always" is misleading since for a general A, det(A^2)=det(A)^2, not det(A) itself -- treating this as a general algebraic identity makes it false in general (D false).'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'numerical',
 'Find the sum of the first 20 terms of the arithmetic progression 3, 7, 11, 15, ...',
 null, '820', 'Sum = n/2*(2a+(n-1)d) = 20/2*(6+19*4) = 10*82 = 820.'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'descriptive',
 'Explain what it means for a square matrix to be "singular," and how this relates to the existence of its inverse and the solutions of a homogeneous linear system.',
 null, null, 'A square matrix is singular when its determinant is zero, which means it does not have an inverse. For a homogeneous system Ax=0, a singular A guarantees the existence of non-trivial (non-zero) solutions in addition to the trivial one, since the matrix maps some non-zero vector to zero -- geometrically, its rows or columns are linearly dependent, collapsing the transformation into a lower-dimensional space.'),

-- Mathematics: Calculus
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'mcq',
 'Solve the differential equation $\frac{dy}{dx}=y$ with $y(0)=1$.',
 '[{"text":"y=e^x","isCorrect":true},{"text":"y=x+1","isCorrect":false},{"text":"y=e^{-x}","isCorrect":false},{"text":"y=1/x","isCorrect":false}]'::jsonb,
 null, 'Separating variables: dy/y=dx, integrating gives ln(y)=x+C. Using y(0)=1 gives C=0, so y=e^x.'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'hard', 'mcq',
 'Let $f(x)=|x-1|+|x+1|$. Which of the following statement(s) is/are TRUE? (A) $f$ is continuous everywhere. (B) $f$ is differentiable everywhere. (C) $f(x)=2$ for all $x\in[-1,1]$. (D) $f$ has a minimum value of 2.',
 '[{"text":"(A) f is continuous everywhere","isCorrect":true},{"text":"(B) f is differentiable everywhere","isCorrect":false},{"text":"(C) f(x)=2 for all x in [-1,1]","isCorrect":true},{"text":"(D) f has minimum value 2","isCorrect":true}]'::jsonb,
 null, 'Being a sum of absolute value functions, f is continuous everywhere (A true), but not differentiable at the corner points x=1 and x=-1, so (B) is false. For x in [-1,1], |x-1|=1-x and |x+1|=x+1, summing to 2 (C true), and this is indeed the minimum value of f, achieved throughout [-1,1] (D true).'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'hard', 'numerical',
 'Evaluate $\int_0^1 x^2\,dx$, giving the answer as a simplified fraction (e.g. 1/3).',
 null, '1/3', 'Antiderivative of x^2 is x^3/3; evaluating from 0 to 1 gives 1/3-0=1/3.'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'descriptive',
 'Explain why a function can be continuous at a point but not differentiable there, using $f(x)=|x|$ at $x=0$ as an example.',
 null, null, 'Continuity only requires that the function''s value matches the limit as x approaches the point from both sides, with no jump or break. Differentiability additionally requires that the slope approaching from the left matches the slope approaching from the right. For f(x)=|x| at x=0, the function is continuous since both one-sided limits equal 0, but the left-hand derivative is -1 while the right-hand derivative is +1, so the derivative does not exist at that sharp corner even though the function itself is continuous there.'),

-- Mathematics: Coordinate Geometry
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'mcq',
 'Find the distance from the point $(3,4)$ to the line $3x+4y-10=0$.',
 '[{"text":"3","isCorrect":true},{"text":"9/5","isCorrect":false},{"text":"5","isCorrect":false},{"text":"2","isCorrect":false}]'::jsonb,
 null, 'Distance = |3*3+4*4-10|/sqrt(3^2+4^2) = |9+16-10|/5 = 15/5 = 3.'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'hard', 'mcq',
 'For the hyperbola $\frac{x^2}{16}-\frac{y^2}{9}=1$, which of the following statement(s) is/are TRUE? (A) The transverse axis length is 8. (B) The eccentricity is $5/4$. (C) The foci are at $(\pm5,0)$. (D) The asymptotes are $y=\pm\frac{4}{3}x$.',
 '[{"text":"(A) Transverse axis length is 8","isCorrect":true},{"text":"(B) Eccentricity is 5/4","isCorrect":true},{"text":"(C) Foci at (+-5, 0)","isCorrect":true},{"text":"(D) Asymptotes y=+-(4/3)x","isCorrect":false}]'::jsonb,
 null, 'Here a^2=16, b^2=9, so a=4, transverse axis = 2a = 8 (A true). c^2=a^2+b^2=25, c=5, giving eccentricity c/a=5/4 (B true) and foci at (+-5,0) (C true). The asymptotes are y=+-(b/a)x=+-(3/4)x, not (4/3)x -- (D) has the ratio inverted, so it is false.'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'numerical',
 'Find the slope of the line passing through the points $(2,3)$ and $(6,11)$.',
 null, '2', 'Slope = (11-3)/(6-2) = 8/4 = 2.'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'descriptive',
 'Explain how the asymptotes of a hyperbola $\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$ are derived, and what they represent geometrically.',
 null, null, 'The asymptotes are found by considering the hyperbola''s equation for very large x and y, where the constant 1 on the right becomes negligible compared to the two large terms, giving x^2/a^2 = y^2/b^2, or y = +-(b/a)x. Geometrically, these lines represent the directions the hyperbola''s branches approach but never touch as they extend to infinity.'),

-- Mathematics: Trigonometry
('JEE Advanced', 'Mathematics', 'Trigonometry', 'medium', 'mcq',
 'Find the value of $\tan(75°)$.',
 '[{"text":"2+sqrt(3)","isCorrect":true},{"text":"2-sqrt(3)","isCorrect":false},{"text":"sqrt(3)","isCorrect":false},{"text":"1+sqrt(3)","isCorrect":false}]'::jsonb,
 null, 'tan(75) = tan(45+30) = (1+1/sqrt3)/(1-1/sqrt3) = (sqrt3+1)/(sqrt3-1), which simplifies to 2+sqrt(3).'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'hard', 'mcq',
 'Regarding the equation $\cos 2x = 1-2\sin^2 x$, which of the following statement(s) is/are TRUE? (A) This identity holds for all real $x$. (B) It can be derived from $\cos(A+B)=\cos A\cos B-\sin A\sin B$ with $A=B=x$. (C) An equivalent form is $\cos 2x=2\cos^2 x-1$. (D) $\cos 2x$ can never equal $\sin 2x$ for any real $x$.',
 '[{"text":"(A) Holds for all real x","isCorrect":true},{"text":"(B) Derivable from cos(A+B) with A=B=x","isCorrect":true},{"text":"(C) Equivalent to 2cos^2x - 1","isCorrect":true},{"text":"(D) cos2x never equals sin2x","isCorrect":false}]'::jsonb,
 null, 'This is a standard trigonometric identity holding for all real x (A true), derivable by setting A=B=x in the cosine addition formula and using sin^2x+cos^2x=1 (B true), and it is indeed algebraically equivalent to 2cos^2x-1 via the same identity (C true). cos(2x)=sin(2x) DOES have solutions, e.g. at 2x=pi/4, so (D) is false.'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'medium', 'numerical',
 'If $\sin\theta=3/5$ and $\theta$ is in the first quadrant, find $\cos\theta$ as a simplified fraction (e.g. 4/5).',
 null, '4/5', 'cos(theta) = sqrt(1-sin^2(theta)) = sqrt(1-9/25) = sqrt(16/25) = 4/5.'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'medium', 'descriptive',
 'Explain how the double angle formula for cosine can be derived from the angle addition formula, and give one of its equivalent forms.',
 null, null, 'Starting from cos(A+B)=cos(A)cos(B)-sin(A)sin(B), setting A=B=x gives cos(2x)=cos^2(x)-sin^2(x). Using the Pythagorean identity sin^2(x)+cos^2(x)=1, this can be rewritten as cos(2x)=2cos^2(x)-1 or equivalently cos(2x)=1-2sin^2(x), both valid equivalent forms of the double angle formula.'),

-- Mathematics: Vectors and 3D Geometry
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'mcq',
 'Find the angle between the vectors $\vec{a}=(1,0,0)$ and $\vec{b}=(1,1,0)$, in degrees.',
 '[{"text":"30","isCorrect":false},{"text":"45","isCorrect":true},{"text":"60","isCorrect":false},{"text":"90","isCorrect":false}]'::jsonb,
 null, 'cos(theta) = (a.b)/(|a||b|) = 1/(1*sqrt2) = 1/sqrt2, giving theta = 45 degrees.'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'hard', 'mcq',
 'For a line in 3D space passing through point $(1,2,3)$ with direction vector $(2,-1,2)$, which of the following statement(s) is/are TRUE? (A) The point $(3,1,5)$ lies on the line. (B) The direction cosines are proportional to $(2,-1,2)$. (C) The magnitude of the direction vector is 3. (D) The line is parallel to the vector $(4,-2,4)$.',
 '[{"text":"(A) Point (3,1,5) lies on the line","isCorrect":true},{"text":"(B) Direction cosines proportional to (2,-1,2)","isCorrect":true},{"text":"(C) Magnitude of direction vector is 3","isCorrect":true},{"text":"(D) Parallel to vector (4,-2,4)","isCorrect":true}]'::jsonb,
 null, 'At parameter t=1: (1+2, 2-1, 3+2)=(3,1,5), confirming that point lies on the line (A true). Direction cosines are always proportional to the direction vector''s components (B true). |(2,-1,2)|=sqrt(4+1+4)=sqrt9=3 (C true). Since (4,-2,4)=2*(2,-1,2), it is a scalar multiple, hence parallel (D true). All four statements are true here.'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'numerical',
 'Find $|\vec{a}\times\vec{b}|$ for $\vec{a}=(1,0,0)$ and $\vec{b}=(0,1,0)$.',
 null, '1', 'a x b = (0,0,1), which has magnitude 1.'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'descriptive',
 'Explain how the direction cosines of a line are related to its direction vector, and why they satisfy $l^2+m^2+n^2=1$.',
 null, null, 'Direction cosines are the cosines of the angles a line makes with the x, y, and z axes respectively, and they are proportional to the components of any direction vector along that line, normalized by its magnitude. Since they represent the components of a unit vector along the line, the Pythagorean relationship for a unit vector''s components gives l^2+m^2+n^2=1.'),

-- Mathematics: Statistics and Probability
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'mcq',
 'The mean of 5 numbers is 20. If one number, 10, is removed, find the new mean of the remaining 4 numbers.',
 '[{"text":"20","isCorrect":false},{"text":"22.5","isCorrect":true},{"text":"25","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'Sum of 5 numbers = 100. Removing 10 leaves sum = 90 over 4 numbers, giving mean = 90/4 = 22.5.'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'hard', 'mcq',
 'Events $A$ and $B$ satisfy $P(A)=0.4$, $P(B)=0.5$, and $P(A\cap B)=0.2$. Which of the following statement(s) is/are TRUE? (A) $P(A\cup B)=0.7$. (B) $A$ and $B$ are independent. (C) $P(A|B)=0.4$. (D) $A$ and $B$ are mutually exclusive.',
 '[{"text":"(A) P(A union B) = 0.7","isCorrect":true},{"text":"(B) A and B are independent","isCorrect":true},{"text":"(C) P(A given B) = 0.4","isCorrect":true},{"text":"(D) A and B are mutually exclusive","isCorrect":false}]'::jsonb,
 null, 'P(A union B) = P(A)+P(B)-P(A intersect B) = 0.4+0.5-0.2 = 0.7 (A true). Since P(A)*P(B) = 0.4*0.5 = 0.2 = P(A intersect B), the events are independent (B true), and P(A|B) = P(A intersect B)/P(B) = 0.2/0.5 = 0.4 = P(A), consistent with independence (C true). Since P(A intersect B)=0.2, not 0, the events are NOT mutually exclusive, so (D) is false.'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'numerical',
 'A die is rolled twice. Find the probability that the sum of the two rolls is 7, as a simplified fraction (e.g. 1/6).',
 null, '1/6', 'There are 6 favorable outcomes (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) out of 36 total, giving 6/36=1/6.'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'descriptive',
 'Explain the relationship between independence of two events and the formula $P(A\cap B)=P(A)\cdot P(B)$, and how this differs from mutual exclusivity.',
 null, null, 'Two events are independent precisely when the occurrence of one does not affect the probability of the other, which is captured mathematically by P(A intersect B) = P(A)*P(B). Mutual exclusivity is a completely different concept meaning the two events cannot occur together at all, so P(A intersect B)=0 -- in fact, two events with non-zero individual probabilities cannot be both independent and mutually exclusive at the same time, since independence requires P(A)*P(B)=P(A intersect B), which would force P(A) or P(B) to be zero if P(A intersect B)=0.');
