-- supabase/sql/exam_question_bank_neet_ug_set1.sql
--
-- First curated question-bank batch for 'NEET UG' (see exam_patterns_neet_ug.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Like NEET PG (and unlike the JEE sets), NEET UG's real format is 100% single-best-response MCQ
-- (4 options, exactly one correct) -- no multi-correct, numerical, or descriptive format in the
-- actual exam. Each of the 16 chapters (4 each across Physics, Chemistry, Botany, Zoology) gets 4
-- classic, high-yield NCERT-based questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_ug.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of impulse is the same as the SI unit of:',
 '[{"text":"Force","isCorrect":false},{"text":"Momentum","isCorrect":true},{"text":"Energy","isCorrect":false},{"text":"Power","isCorrect":false}]'::jsonb,
 null, 'Impulse equals the change in momentum (Impulse = F*t = deltaP), so it shares the same SI unit, kg m/s, as momentum.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'A body moving in a circle at constant speed experiences an acceleration that is:',
 '[{"text":"Zero, since speed is constant","isCorrect":false},{"text":"Constant in magnitude, directed toward the center","isCorrect":true},{"text":"Constant in magnitude, directed away from the center","isCorrect":false},{"text":"Increasing continuously","isCorrect":false}]'::jsonb,
 null, 'Even at constant speed, the direction of velocity keeps changing, producing a centripetal acceleration of constant magnitude v^2/r directed toward the center.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The work done by the centripetal force on a particle undergoing uniform circular motion is:',
 '[{"text":"Positive","isCorrect":false},{"text":"Negative","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Depends on the radius","isCorrect":false}]'::jsonb,
 null, 'The centripetal force is always directed perpendicular to the particle''s velocity (and hence displacement), so it does no work on the particle.'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The escape velocity from the surface of the Earth is approximately:',
 '[{"text":"1.12 km/s","isCorrect":false},{"text":"11.2 km/s","isCorrect":true},{"text":"112 km/s","isCorrect":false},{"text":"0.112 km/s","isCorrect":false}]'::jsonb,
 null, 'The escape velocity from Earth''s surface, given by sqrt(2gR), is approximately 11.2 km/s.'),

-- Physics: Electrodynamics
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of electrical resistance is the:',
 '[{"text":"Ohm","isCorrect":true},{"text":"Farad","isCorrect":false},{"text":"Henry","isCorrect":false},{"text":"Weber","isCorrect":false}]'::jsonb,
 null, 'Electrical resistance is measured in ohms, defined by Ohm''s law as V/I.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'In a purely resistive AC circuit, the voltage and current are:',
 '[{"text":"In phase with each other","isCorrect":true},{"text":"90 degrees out of phase","isCorrect":false},{"text":"180 degrees out of phase","isCorrect":false},{"text":"Always independent of each other","isCorrect":false}]'::jsonb,
 null, 'In a purely resistive AC circuit, voltage and current reach their maximum and zero values simultaneously, so they remain in phase.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The magnetic field at the center of a circular current-carrying loop of radius R carrying current I is given by:',
 '[{"text":"mu0*I/(2R)","isCorrect":true},{"text":"mu0*I/(2*pi*R)","isCorrect":false},{"text":"mu0*I*R/2","isCorrect":false},{"text":"mu0*I^2/(2R)","isCorrect":false}]'::jsonb,
 null, 'The magnetic field at the center of a circular current loop is B = mu0*I/(2R), derived from the Biot-Savart law.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'Lenz''s law, which determines the direction of an induced current, is a direct consequence of which conservation principle?',
 '[{"text":"Conservation of charge","isCorrect":false},{"text":"Conservation of energy","isCorrect":true},{"text":"Conservation of momentum","isCorrect":false},{"text":"Conservation of angular momentum","isCorrect":false}]'::jsonb,
 null, 'Lenz''s law states the induced current opposes the change producing it; if it did not, energy could be created from nothing, so the law is a consequence of energy conservation.'),

-- Physics: Optics and Wave Phenomena
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The splitting of white light into its component colors on passing through a prism is called:',
 '[{"text":"Dispersion","isCorrect":true},{"text":"Diffraction","isCorrect":false},{"text":"Polarization","isCorrect":false},{"text":"Interference","isCorrect":false}]'::jsonb,
 null, 'Dispersion is the separation of white light into its constituent wavelengths (colors) because the refractive index of a medium varies with wavelength.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'In Young''s double slit experiment, the fringe width beta is given by:',
 '[{"text":"lambda*D/d","isCorrect":true},{"text":"lambda*d/D","isCorrect":false},{"text":"D*d/lambda","isCorrect":false},{"text":"lambda/(D*d)","isCorrect":false}]'::jsonb,
 null, 'Fringe width beta = lambda*D/d, where lambda is the wavelength, D is the slit-to-screen distance, and d is the slit separation.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The apparent change in frequency of a wave due to relative motion between the source and the observer is called the:',
 '[{"text":"Doppler effect","isCorrect":true},{"text":"Photoelectric effect","isCorrect":false},{"text":"Compton effect","isCorrect":false},{"text":"Zeeman effect","isCorrect":false}]'::jsonb,
 null, 'The Doppler effect describes the apparent shift in observed frequency caused by relative motion between a wave source and an observer.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'Myopia (near-sightedness) is corrected using which type of lens?',
 '[{"text":"Convex (converging) lens","isCorrect":false},{"text":"Concave (diverging) lens","isCorrect":true},{"text":"Cylindrical lens","isCorrect":false},{"text":"Bifocal lens only","isCorrect":false}]'::jsonb,
 null, 'In myopia, the image forms in front of the retina; a concave (diverging) lens diverges incoming rays slightly before they enter the eye, pushing the focal point back onto the retina.'),

-- Physics: Modern Physics and Semiconductor Devices
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The photoelectric effect was successfully explained by:',
 '[{"text":"Newton, using the corpuscular theory","isCorrect":false},{"text":"Einstein, using the photon concept","isCorrect":true},{"text":"Huygens, using the wave theory","isCorrect":false},{"text":"Maxwell, using electromagnetic theory","isCorrect":false}]'::jsonb,
 null, 'Einstein explained the photoelectric effect by proposing that light consists of discrete photons, each carrying energy hf, that can eject electrons on collision if their energy exceeds the work function.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'In a p-type semiconductor, the majority charge carriers are:',
 '[{"text":"Electrons","isCorrect":false},{"text":"Holes","isCorrect":true},{"text":"Protons","isCorrect":false},{"text":"Photons","isCorrect":false}]'::jsonb,
 null, 'A p-type semiconductor is doped with trivalent impurities, creating an excess of holes, which act as the majority charge carriers.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'An alpha particle is equivalent to the nucleus of which atom?',
 '[{"text":"Hydrogen","isCorrect":false},{"text":"Helium","isCorrect":true},{"text":"Lithium","isCorrect":false},{"text":"Carbon","isCorrect":false}]'::jsonb,
 null, 'An alpha particle consists of 2 protons and 2 neutrons, identical to the nucleus of a helium atom.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Which semiconductor device is typically used as a voltage regulator, operating in reverse breakdown?',
 '[{"text":"Zener diode","isCorrect":true},{"text":"Photodiode","isCorrect":false},{"text":"Light-emitting diode","isCorrect":false},{"text":"Solar cell","isCorrect":false}]'::jsonb,
 null, 'A Zener diode is specifically designed to operate in reverse breakdown at a stable voltage, making it useful as a voltage regulator.'),

-- Chemistry: Physical Chemistry
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The pH of a neutral aqueous solution at 25 degrees C is:',
 '[{"text":"0","isCorrect":false},{"text":"7","isCorrect":true},{"text":"14","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'At 25 degrees C, pure water has equal concentrations of H+ and OH- ions, giving a pH of 7, which defines neutrality.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The SI-derived unit commonly used for molar conductivity is:',
 '[{"text":"S cm^2 mol^-1","isCorrect":true},{"text":"S cm^-1","isCorrect":false},{"text":"S mol^-1","isCorrect":false},{"text":"ohm cm mol^-1","isCorrect":false}]'::jsonb,
 null, 'Molar conductivity, defined as conductivity divided by molar concentration, is conventionally expressed in S cm^2 mol^-1.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The law stating that the rate of a reaction is proportional to the product of the concentrations of reactants, each raised to an appropriate power, is called the:',
 '[{"text":"Law of mass action","isCorrect":true},{"text":"Law of conservation of mass","isCorrect":false},{"text":"Law of multiple proportions","isCorrect":false},{"text":"Raoult''s law","isCorrect":false}]'::jsonb,
 null, 'The law of mass action states that reaction rate is proportional to the product of the active masses (concentrations) of the reactants raised to powers matching their stoichiometric coefficients (for elementary reactions).'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The number of moles of solute dissolved per liter of solution is called:',
 '[{"text":"Molarity","isCorrect":true},{"text":"Molality","isCorrect":false},{"text":"Normality only","isCorrect":false},{"text":"Mole fraction","isCorrect":false}]'::jsonb,
 null, 'Molarity is defined as moles of solute per liter of solution, distinct from molality, which uses mass of solvent instead of solution volume.'),

-- Chemistry: Organic Chemistry
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The functional group -COOH represents which class of organic compounds?',
 '[{"text":"Carboxylic acids","isCorrect":true},{"text":"Aldehydes","isCorrect":false},{"text":"Ketones","isCorrect":false},{"text":"Esters","isCorrect":false}]'::jsonb,
 null, 'The -COOH group defines the carboxylic acid functional class, combining a carbonyl and hydroxyl group on the same carbon.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Markovnikov''s rule is applied to predict the product of which type of reaction?',
 '[{"text":"Addition of HX to an unsymmetrical alkene","isCorrect":true},{"text":"Esterification of a carboxylic acid","isCorrect":false},{"text":"Nucleophilic substitution on an alkyl halide","isCorrect":false},{"text":"Oxidation of a primary alcohol","isCorrect":false}]'::jsonb,
 null, 'Markovnikov''s rule predicts that in the addition of HX to an unsymmetrical alkene, the H atom attaches to the carbon with more hydrogens already, and X attaches to the more substituted carbon (via the more stable carbocation intermediate).'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'hard', 'mcq',
 'Which reagent is commonly used to distinguish between primary, secondary, and tertiary alcohols based on differing reaction rates?',
 '[{"text":"Lucas reagent","isCorrect":true},{"text":"Tollens'' reagent","isCorrect":false},{"text":"Fehling''s solution","isCorrect":false},{"text":"Grignard reagent","isCorrect":false}]'::jsonb,
 null, 'Lucas reagent (concentrated HCl with anhydrous ZnCl2) distinguishes alcohols by the differing rates at which they form an insoluble alkyl chloride -- tertiary alcohols react immediately, secondary within minutes, and primary alcohols very slowly.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The IUPAC name of the compound commonly known as acetone is:',
 '[{"text":"Propan-2-one","isCorrect":true},{"text":"Propan-1-ol","isCorrect":false},{"text":"Methyl formate","isCorrect":false},{"text":"Ethanal","isCorrect":false}]'::jsonb,
 null, 'Acetone, CH3-CO-CH3, is systematically named propan-2-one (propanone) under IUPAC nomenclature.'),

-- Chemistry: Inorganic Chemistry
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Among the noble gases, which has the highest ionization enthalpy?',
 '[{"text":"Helium","isCorrect":true},{"text":"Neon","isCorrect":false},{"text":"Argon","isCorrect":false},{"text":"Xenon","isCorrect":false}]'::jsonb,
 null, 'Helium, being the smallest noble gas with electrons held closest to the nucleus, has the highest ionization enthalpy among the noble gases.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The oxidation state of manganese in KMnO4 is:',
 '[{"text":"+2","isCorrect":false},{"text":"+4","isCorrect":false},{"text":"+7","isCorrect":true},{"text":"+6","isCorrect":false}]'::jsonb,
 null, 'In KMnO4, K is +1 and each O is -2; balancing the overall neutral charge gives Mn an oxidation state of +7.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which of the following is commonly used as a bleaching agent?',
 '[{"text":"Chlorine","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Helium","isCorrect":false},{"text":"Argon","isCorrect":false}]'::jsonb,
 null, 'Chlorine (and chlorine-derived compounds like bleaching powder) is widely used as a bleaching agent due to its strong oxidizing action.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'According to valence bond theory, the hybridization of the central nitrogen atom in NH3 is:',
 '[{"text":"sp","isCorrect":false},{"text":"sp2","isCorrect":false},{"text":"sp3","isCorrect":true},{"text":"sp3d","isCorrect":false}]'::jsonb,
 null, 'Nitrogen in NH3 has 4 electron domains (3 bond pairs and 1 lone pair), corresponding to sp3 hybridization with a pyramidal shape.'),

-- Chemistry: Biomolecules and Environmental Chemistry
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'The primary storage form of energy in plants is:',
 '[{"text":"Starch","isCorrect":true},{"text":"Cellulose","isCorrect":false},{"text":"Glycogen","isCorrect":false},{"text":"Chitin","isCorrect":false}]'::jsonb,
 null, 'Starch, a polysaccharide made of glucose units, is the primary energy storage molecule in plants, while cellulose serves a structural role.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Enzymes, which catalyze biochemical reactions, are chemically composed mainly of:',
 '[{"text":"Proteins","isCorrect":true},{"text":"Carbohydrates","isCorrect":false},{"text":"Lipids","isCorrect":false},{"text":"Nucleic acids only","isCorrect":false}]'::jsonb,
 null, 'Enzymes are biological catalysts that are, with rare exceptions (like ribozymes), proteins whose specific 3D structure enables substrate binding and catalysis.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'The ozone layer in the stratosphere primarily absorbs which type of radiation, protecting life on Earth?',
 '[{"text":"Infrared radiation","isCorrect":false},{"text":"Ultraviolet radiation","isCorrect":true},{"text":"Visible light","isCorrect":false},{"text":"Radio waves","isCorrect":false}]'::jsonb,
 null, 'The ozone layer absorbs most of the sun''s harmful ultraviolet radiation, preventing it from reaching the Earth''s surface in damaging amounts.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Which greenhouse gas is the largest overall contributor to global warming by volume of emissions?',
 '[{"text":"Carbon dioxide","isCorrect":true},{"text":"Methane","isCorrect":false},{"text":"Ozone","isCorrect":false},{"text":"Nitrous oxide","isCorrect":false}]'::jsonb,
 null, 'Carbon dioxide, released primarily from fossil fuel combustion, is the greenhouse gas emitted in the largest quantity and is the largest overall contributor to the enhanced greenhouse effect.'),

-- Botany: Plant Physiology
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'Photosynthesis occurs in which cell organelle?',
 '[{"text":"Mitochondria","isCorrect":false},{"text":"Chloroplast","isCorrect":true},{"text":"Golgi apparatus","isCorrect":false},{"text":"Ribosome","isCorrect":false}]'::jsonb,
 null, 'Chloroplasts contain chlorophyll and the enzymatic machinery needed to carry out both the light and dark reactions of photosynthesis.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The light-independent reactions of photosynthesis (Calvin cycle) occur in which part of the chloroplast?',
 '[{"text":"Thylakoid membrane","isCorrect":false},{"text":"Stroma","isCorrect":true},{"text":"Outer membrane","isCorrect":false},{"text":"Granum stack only","isCorrect":false}]'::jsonb,
 null, 'The Calvin cycle, which fixes CO2 into sugars, takes place in the stroma, the fluid-filled matrix surrounding the thylakoids.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Which plant hormone promotes stomatal closure during water stress?',
 '[{"text":"Auxin","isCorrect":false},{"text":"Gibberellin","isCorrect":false},{"text":"Abscisic acid","isCorrect":true},{"text":"Cytokinin","isCorrect":false}]'::jsonb,
 null, 'Abscisic acid (ABA), often called the stress hormone, promotes stomatal closure to reduce water loss under drought conditions.'),
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'Transpiration in plants occurs mainly through which structure?',
 '[{"text":"Stomata","isCorrect":true},{"text":"Root hairs","isCorrect":false},{"text":"Xylem vessels","isCorrect":false},{"text":"Cuticle only","isCorrect":false}]'::jsonb,
 null, 'The majority of water lost through transpiration exits via the stomata, tiny pores mainly on the leaf surface that also regulate gas exchange.'),

-- Botany: Cell Biology and Genetics
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'Which cell organelle is referred to as the "powerhouse of the cell"?',
 '[{"text":"Mitochondria","isCorrect":true},{"text":"Nucleus","isCorrect":false},{"text":"Endoplasmic reticulum","isCorrect":false},{"text":"Lysosome","isCorrect":false}]'::jsonb,
 null, 'Mitochondria generate most of the cell''s ATP through aerobic respiration, earning them the nickname "powerhouse of the cell".'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'According to Mendel''s law of segregation, the two alleles of a gene separate from each other during:',
 '[{"text":"Mitosis","isCorrect":false},{"text":"Gamete formation (meiosis)","isCorrect":true},{"text":"Fertilization","isCorrect":false},{"text":"Cell differentiation","isCorrect":false}]'::jsonb,
 null, 'Mendel''s law of segregation states that the two alleles of a gene separate from each other during gamete formation, so each gamete carries only one allele.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'DNA replication is best described as being:',
 '[{"text":"Conservative","isCorrect":false},{"text":"Semiconservative","isCorrect":true},{"text":"Dispersive","isCorrect":false},{"text":"Random","isCorrect":false}]'::jsonb,
 null, 'DNA replication is semiconservative -- each new DNA double helix retains one original (parental) strand and one newly synthesized strand, as demonstrated by the Meselson-Stahl experiment.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'The cell wall of plant cells is primarily composed of:',
 '[{"text":"Chitin","isCorrect":false},{"text":"Cellulose","isCorrect":true},{"text":"Peptidoglycan","isCorrect":false},{"text":"Keratin","isCorrect":false}]'::jsonb,
 null, 'Plant cell walls are primarily composed of cellulose, a polysaccharide of glucose units that provides structural rigidity.'),

-- Botany: Ecology and Environment
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'The flow of energy through an ecosystem, from producers to successive trophic levels, is:',
 '[{"text":"Bidirectional","isCorrect":false},{"text":"Cyclic","isCorrect":false},{"text":"Unidirectional","isCorrect":true},{"text":"Random","isCorrect":false}]'::jsonb,
 null, 'Unlike nutrients, which cycle through an ecosystem, energy flows unidirectionally from producers through successive trophic levels, being progressively lost as heat.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'Which ecological pyramid is always upright, regardless of the ecosystem?',
 '[{"text":"Pyramid of numbers","isCorrect":false},{"text":"Pyramid of biomass","isCorrect":false},{"text":"Pyramid of energy","isCorrect":true},{"text":"None of these is always upright","isCorrect":false}]'::jsonb,
 null, 'The pyramid of energy is always upright because energy is progressively lost as heat at each trophic transfer, so energy available at each successive level must be less than the level below it.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'The gradual replacement of one biotic community by another over time in a given area is called:',
 '[{"text":"Ecological succession","isCorrect":true},{"text":"Ecological pyramid","isCorrect":false},{"text":"Biomagnification","isCorrect":false},{"text":"Symbiosis","isCorrect":false}]'::jsonb,
 null, 'Ecological succession is the natural, gradual process by which the species composition of a community changes over time, often progressing toward a stable climax community.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'Biological Oxygen Demand (BOD) is used as a measure of:',
 '[{"text":"Organic pollutant load in water","isCorrect":true},{"text":"Total dissolved solids","isCorrect":false},{"text":"Radioactivity of water","isCorrect":false},{"text":"pH of water","isCorrect":false}]'::jsonb,
 null, 'BOD measures the amount of dissolved oxygen consumed by microorganisms decomposing organic matter in water, making it a key indicator of organic pollution.'),

-- Botany: Plant Morphology and Anatomy
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The type of root system typically found in monocot plants is:',
 '[{"text":"Tap root system","isCorrect":false},{"text":"Fibrous root system","isCorrect":true},{"text":"Adventitious tap root system","isCorrect":false},{"text":"Prop root system only","isCorrect":false}]'::jsonb,
 null, 'Monocot plants typically have a fibrous root system, consisting of many thin, similarly sized roots arising from the base of the stem, rather than one dominant taproot.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Which tissue is responsible for the lateral growth (increase in girth) of dicot stems?',
 '[{"text":"Apical meristem","isCorrect":false},{"text":"Vascular cambium","isCorrect":true},{"text":"Epidermis","isCorrect":false},{"text":"Pith","isCorrect":false}]'::jsonb,
 null, 'Vascular cambium, a lateral meristem between xylem and phloem, produces secondary xylem and phloem, increasing the girth of dicot stems.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'The main water-conducting elements in angiosperms are:',
 '[{"text":"Tracheids","isCorrect":false},{"text":"Vessels","isCorrect":true},{"text":"Sieve tubes","isCorrect":false},{"text":"Companion cells","isCorrect":false}]'::jsonb,
 null, 'While both tracheids and vessels conduct water, vessels (present mainly in angiosperms) are the more efficient, dominant water-conducting elements due to their wider lumen and perforated end walls.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Aestivation refers to the mode of arrangement of which floral part within a flower bud?',
 '[{"text":"Petals (or sepals)","isCorrect":true},{"text":"Ovules within the ovary","isCorrect":false},{"text":"Anthers within the stamen","isCorrect":false},{"text":"Leaves on the stem","isCorrect":false}]'::jsonb,
 null, 'Aestivation describes the arrangement of sepals or petals relative to one another in a flower bud, with patterns like valvate, twisted, or imbricate.'),

-- Zoology: Human Physiology
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'The functional and structural unit of the kidney is the:',
 '[{"text":"Nephron","isCorrect":true},{"text":"Neuron","isCorrect":false},{"text":"Alveolus","isCorrect":false},{"text":"Villus","isCorrect":false}]'::jsonb,
 null, 'The nephron is the basic structural and functional unit of the kidney, responsible for filtration, reabsorption, and secretion in urine formation.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which chamber of the human heart pumps oxygenated blood to the entire body?',
 '[{"text":"Right atrium","isCorrect":false},{"text":"Right ventricle","isCorrect":false},{"text":"Left ventricle","isCorrect":true},{"text":"Left atrium","isCorrect":false}]'::jsonb,
 null, 'The left ventricle receives oxygenated blood from the left atrium and pumps it at high pressure through the aorta to the systemic circulation.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Insulin is secreted by which cells of the pancreas?',
 '[{"text":"Alpha cells of islets of Langerhans","isCorrect":false},{"text":"Beta cells of islets of Langerhans","isCorrect":true},{"text":"Acinar cells","isCorrect":false},{"text":"Delta cells only","isCorrect":false}]'::jsonb,
 null, 'Insulin, which lowers blood glucose, is secreted by the beta cells of the islets of Langerhans in the pancreas.'),
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'Which part of the brain regulates body temperature?',
 '[{"text":"Cerebellum","isCorrect":false},{"text":"Hypothalamus","isCorrect":true},{"text":"Medulla oblongata","isCorrect":false},{"text":"Cerebrum","isCorrect":false}]'::jsonb,
 null, 'The hypothalamus acts as the body''s thermostat, regulating body temperature along with several other homeostatic functions.'),

-- Zoology: Human Reproduction and Reproductive Health
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Spermatogenesis occurs in which part of the testis?',
 '[{"text":"Seminiferous tubules","isCorrect":true},{"text":"Epididymis","isCorrect":false},{"text":"Vas deferens","isCorrect":false},{"text":"Prostate gland","isCorrect":false}]'::jsonb,
 null, 'Spermatogenesis, the production of sperm cells, occurs within the seminiferous tubules of the testis.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Fertilization in humans normally occurs in which part of the female reproductive tract?',
 '[{"text":"Ampulla of the fallopian tube","isCorrect":true},{"text":"Uterus","isCorrect":false},{"text":"Cervix","isCorrect":false},{"text":"Vagina","isCorrect":false}]'::jsonb,
 null, 'Fertilization normally occurs in the ampulla, the widest part of the fallopian tube (oviduct), where the sperm meets the ovum.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'hard', 'mcq',
 'Which hormone maintains the corpus luteum during early pregnancy, before the placenta takes over?',
 '[{"text":"Human chorionic gonadotropin (hCG)","isCorrect":true},{"text":"Follicle-stimulating hormone (FSH)","isCorrect":false},{"text":"Luteinizing hormone (LH)","isCorrect":false},{"text":"Oxytocin","isCorrect":false}]'::jsonb,
 null, 'Human chorionic gonadotropin (hCG), secreted by the developing embryo, maintains the corpus luteum so it continues producing progesterone during early pregnancy.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'easy', 'mcq',
 'Which of the following is a commonly used barrier method of contraception?',
 '[{"text":"Condom","isCorrect":true},{"text":"Oral contraceptive pill","isCorrect":false},{"text":"Copper-T (IUD)","isCorrect":false},{"text":"Tubectomy","isCorrect":false}]'::jsonb,
 null, 'A condom is a barrier contraceptive that physically prevents sperm from reaching the egg, and also offers protection against sexually transmitted infections.'),

-- Zoology: Genetics and Evolution
('NEET UG', 'Zoology', 'Genetics and Evolution', 'easy', 'mcq',
 'The number of chromosomes present in a normal human somatic cell is:',
 '[{"text":"23","isCorrect":false},{"text":"46","isCorrect":true},{"text":"44","isCorrect":false},{"text":"48","isCorrect":false}]'::jsonb,
 null, 'A normal human somatic cell is diploid, containing 46 chromosomes (23 pairs), while gametes are haploid with 23 chromosomes.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'Sickle cell anemia results from a mutation affecting which protein?',
 '[{"text":"Hemoglobin (beta-globin chain)","isCorrect":true},{"text":"Insulin","isCorrect":false},{"text":"Collagen","isCorrect":false},{"text":"Myosin","isCorrect":false}]'::jsonb,
 null, 'Sickle cell anemia is caused by a point mutation in the beta-globin gene, producing abnormal hemoglobin (HbS) that distorts red blood cells into a sickle shape under low oxygen.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'According to Darwin''s theory, evolution occurs primarily through the mechanism of:',
 '[{"text":"Natural selection","isCorrect":true},{"text":"Use and disuse of organs","isCorrect":false},{"text":"Inheritance of acquired characters","isCorrect":false},{"text":"Random genetic drift alone","isCorrect":false}]'::jsonb,
 null, 'Darwin proposed that differential survival and reproduction of individuals with favorable heritable variations -- natural selection -- is the primary driving mechanism of evolution.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'A genetic cross between a heterozygous individual and a homozygous recessive individual is called a:',
 '[{"text":"Test cross","isCorrect":true},{"text":"Monohybrid cross","isCorrect":false},{"text":"Reciprocal cross","isCorrect":false},{"text":"Back cross only","isCorrect":false}]'::jsonb,
 null, 'A test cross, between a heterozygous individual and a homozygous recessive individual, is used to determine the unknown genotype of the heterozygote based on the phenotype ratio of offspring.'),

-- Zoology: Biotechnology and its Applications
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Restriction enzymes function in genetic engineering by:',
 '[{"text":"Cutting DNA at specific recognition sequences","isCorrect":true},{"text":"Joining DNA fragments together","isCorrect":false},{"text":"Synthesizing new DNA strands","isCorrect":false},{"text":"Degrading RNA molecules","isCorrect":false}]'::jsonb,
 null, 'Restriction enzymes (restriction endonucleases) recognize specific DNA sequences and cut the DNA at or near those sites, an essential tool for creating recombinant DNA.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'hard', 'mcq',
 'The Ti plasmid, commonly used as a vector for gene transfer into plants, is naturally found in which bacterium?',
 '[{"text":"Escherichia coli","isCorrect":false},{"text":"Agrobacterium tumefaciens","isCorrect":true},{"text":"Bacillus thuringiensis","isCorrect":false},{"text":"Salmonella typhi","isCorrect":false}]'::jsonb,
 null, 'Agrobacterium tumefaciens naturally carries the Ti (tumor-inducing) plasmid, which is engineered and widely used as a vector to transfer genes into plant cells.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'The Polymerase Chain Reaction (PCR) technique is primarily used to:',
 '[{"text":"Amplify a specific DNA sequence","isCorrect":true},{"text":"Sequence an entire genome directly","isCorrect":false},{"text":"Separate proteins by size","isCorrect":false},{"text":"Cut DNA at specific sites","isCorrect":false}]'::jsonb,
 null, 'PCR uses repeated cycles of denaturation, annealing, and extension with a heat-stable polymerase to exponentially amplify a specific target DNA sequence.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Bt cotton is genetically modified to express a toxin gene derived from which organism?',
 '[{"text":"Bacillus thuringiensis","isCorrect":true},{"text":"Agrobacterium tumefaciens","isCorrect":false},{"text":"Escherichia coli","isCorrect":false},{"text":"Saccharomyces cerevisiae","isCorrect":false}]'::jsonb,
 null, 'Bt cotton expresses a crystal (Cry) toxin gene from the soil bacterium Bacillus thuringiensis, which is toxic to specific insect larvae (like the cotton bollworm) but safe for humans.');
