-- supabase/sql/exam_question_bank_ssc_chsl_set1.sql
--
-- First curated question-bank batch for 'SSC-CHSL' (see exam_patterns_ssc_chsl.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Pitched at a 12th-standard level -- easier than SSC-CGL (see
-- exam_question_bank_ssc_cgl_set1.sql) but a step up from SSC-MTS's 10th-standard syllabus (see
-- exam_question_bank_ssc_mts_set1.sql). Non-Verbal Reasoning again uses text-describable
-- cube-painting/paper-folding/clock-angle puzzles in place of figure-based questions, which need
-- images this schema can't provide. 16 chapters (4 per section x 4 sections) each get 4
-- questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_chsl.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General Intelligence: Verbal Reasoning (Analogies, Classification, Series)
('SSC-CHSL', 'General Intelligence', 'Verbal Reasoning (Analogies, Classification, Series)', 'easy', 'mcq',
 'Book is to Read as Knife is to:',
 '[{"text":"Cut","isCorrect":true},{"text":"Sharp","isCorrect":false},{"text":"Kitchen","isCorrect":false},{"text":"Metal","isCorrect":false}]'::jsonb,
 null, 'A book is used to read, just as a knife is used to cut.'),
('SSC-CHSL', 'General Intelligence', 'Verbal Reasoning (Analogies, Classification, Series)', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Apple","isCorrect":false},{"text":"Mango","isCorrect":false},{"text":"Potato","isCorrect":true},{"text":"Banana","isCorrect":false}]'::jsonb,
 null, 'Apple, Mango and Banana are fruits, while Potato is a vegetable.'),
('SSC-CHSL', 'General Intelligence', 'Verbal Reasoning (Analogies, Classification, Series)', 'medium', 'mcq',
 'Find the next number in the series: 2, 6, 12, 20, 30, ?',
 '[{"text":"40","isCorrect":false},{"text":"42","isCorrect":true},{"text":"44","isCorrect":false},{"text":"36","isCorrect":false}]'::jsonb,
 null, 'The differences between terms increase by 2 each time (4, 6, 8, 10, 12), so the next term is 30 + 12 = 42.'),
('SSC-CHSL', 'General Intelligence', 'Verbal Reasoning (Analogies, Classification, Series)', 'medium', 'mcq',
 '5 is to 25 as 7 is to:',
 '[{"text":"35","isCorrect":false},{"text":"49","isCorrect":true},{"text":"14","isCorrect":false},{"text":"56","isCorrect":false}]'::jsonb,
 null, 'Each number relates to its square: 5^2 = 25, so 7^2 = 49.'),

-- General Intelligence: Non-Verbal and Figural Reasoning
('SSC-CHSL', 'General Intelligence', 'Non-Verbal and Figural Reasoning', 'easy', 'mcq',
 'A sheet of paper is folded in half twice, and a hole is punched through the center. How many holes will there be when the paper is unfolded?',
 '[{"text":"2","isCorrect":false},{"text":"4","isCorrect":true},{"text":"8","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'Folding the paper in half twice creates 4 layers, so a single punch through the center produces 4 holes when unfolded.'),
('SSC-CHSL', 'General Intelligence', 'Non-Verbal and Figural Reasoning', 'medium', 'mcq',
 'A cube is painted red on all its faces and then cut into 27 identical smaller cubes. How many of the smaller cubes have exactly one face painted?',
 '[{"text":"6","isCorrect":true},{"text":"8","isCorrect":false},{"text":"12","isCorrect":false},{"text":"9","isCorrect":false}]'::jsonb,
 null, 'In a 3x3x3 cube, the 6 face-center cubes each have exactly one painted face (corners have 3, edges have 2).'),
('SSC-CHSL', 'General Intelligence', 'Non-Verbal and Figural Reasoning', 'medium', 'mcq',
 'How many triangles are formed in a figure consisting of a triangle with all three of its medians drawn?',
 '[{"text":"4","isCorrect":false},{"text":"6","isCorrect":true},{"text":"8","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'Drawing all three medians of a triangle divides it into 6 smaller triangles.'),
('SSC-CHSL', 'General Intelligence', 'Non-Verbal and Figural Reasoning', 'hard', 'mcq',
 'What is the angle between the hour and minute hands of a clock at 3:15?',
 '[{"text":"0 degrees","isCorrect":false},{"text":"7.5 degrees","isCorrect":true},{"text":"15 degrees","isCorrect":false},{"text":"30 degrees","isCorrect":false}]'::jsonb,
 null, 'At 3:15, the minute hand is at 90 degrees and the hour hand has moved 7.5 degrees past the 3, giving an angle of 7.5 degrees.'),

-- General Intelligence: Logical Reasoning (Syllogism, Statements and Conclusions)
('SSC-CHSL', 'General Intelligence', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'easy', 'mcq',
 'Statement: All roses are flowers. All flowers need water. Conclusion: All roses need water. Is the conclusion valid?',
 '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false},{"text":"Cannot be determined","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'Since all roses are flowers and all flowers need water, it logically follows that all roses need water.'),
('SSC-CHSL', 'General Intelligence', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'medium', 'mcq',
 'Statements: Some pens are books. All books are papers. Conclusion I: Some pens are papers. Conclusion II: All papers are books. Which conclusion(s) follow?',
 '[{"text":"Only I","isCorrect":true},{"text":"Only II","isCorrect":false},{"text":"Both I and II","isCorrect":false},{"text":"Neither I nor II","isCorrect":false}]'::jsonb,
 null, 'Since some pens are books and all books are papers, some pens must be papers (Conclusion I). Conclusion II reverses the relationship and does not follow.'),
('SSC-CHSL', 'General Intelligence', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'medium', 'mcq',
 'P is the brother of Q. Q is the sister of R. How is P related to R?',
 '[{"text":"Brother","isCorrect":true},{"text":"Sister","isCorrect":false},{"text":"Father","isCorrect":false},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'Since P is described as a brother (male) and is a sibling of Q, who is a sibling of R, P is R''s brother.'),
('SSC-CHSL', 'General Intelligence', 'Logical Reasoning (Syllogism, Statements and Conclusions)', 'hard', 'mcq',
 'Statement: No cats are dogs. All dogs are animals. Conclusion I: No cats are animals. Conclusion II: Some animals are dogs. Which conclusion(s) follow?',
 '[{"text":"Only I","isCorrect":false},{"text":"Only II","isCorrect":true},{"text":"Both I and II","isCorrect":false},{"text":"Neither I nor II","isCorrect":false}]'::jsonb,
 null, 'Since all dogs are animals, at least some animals must be dogs (Conclusion II). Conclusion I does not follow, since cats could still be animals through some other category.'),

-- General Intelligence: Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)
('SSC-CHSL', 'General Intelligence', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'easy', 'mcq',
 'In a certain code, CAT is written as DBU. How is DOG written in that code?',
 '[{"text":"EPH","isCorrect":true},{"text":"EPI","isCorrect":false},{"text":"FQH","isCorrect":false},{"text":"EQH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: D->E, O->P, G->H, giving EPH.'),
('SSC-CHSL', 'General Intelligence', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'easy', 'mcq',
 'Pointing to a photograph, a man says, "She is the daughter of my grandfather''s only son." How is the girl related to the man?',
 '[{"text":"Sister","isCorrect":true},{"text":"Cousin","isCorrect":false},{"text":"Daughter","isCorrect":false},{"text":"Niece","isCorrect":false}]'::jsonb,
 null, 'The man''s grandfather''s only son is the man''s own father, so the girl (his daughter) is the man''s sister.'),
('SSC-CHSL', 'General Intelligence', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'medium', 'mcq',
 'A man walks 5 km east, then 3 km south, then 5 km west. How far is he from his starting point and in which direction?',
 '[{"text":"3 km South","isCorrect":true},{"text":"8 km South","isCorrect":false},{"text":"3 km North","isCorrect":false},{"text":"5 km East","isCorrect":false}]'::jsonb,
 null, 'The eastward and westward movements of 5 km each cancel out, leaving only the 3 km southward movement.'),
('SSC-CHSL', 'General Intelligence', 'Analytical Reasoning (Coding-Decoding, Blood Relations, Direction Sense)', 'medium', 'mcq',
 'In a certain code language, GARDEN is written as HBSEFO. How is FLOWER written in that code?',
 '[{"text":"GMPXFS","isCorrect":true},{"text":"GMPXFT","isCorrect":false},{"text":"GNPXFS","isCorrect":false},{"text":"HMPXFS","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so FLOWER becomes GMPXFS.'),

-- General Awareness: Indian History and Culture
('SSC-CHSL', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who is known as the "Father of the Indian Constitution"?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"B.R. Ambedkar","isCorrect":true},{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Sardar Patel","isCorrect":false}]'::jsonb,
 null, 'Dr. B.R. Ambedkar chaired the Drafting Committee of the Indian Constitution and is known as its father.'),
('SSC-CHSL', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'The Quit India Movement was launched in which year?',
 '[{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":true},{"text":"1947","isCorrect":false},{"text":"1935","isCorrect":false}]'::jsonb,
 null, 'The Quit India Movement was launched by Mahatma Gandhi in August 1942.'),
('SSC-CHSL', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Who founded the Mughal Empire in India?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Humayun","isCorrect":false},{"text":"Babur","isCorrect":true},{"text":"Shah Jahan","isCorrect":false}]'::jsonb,
 null, 'Babur founded the Mughal Empire in India after winning the First Battle of Panipat in 1526.'),
('SSC-CHSL', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'The Battle of Plassey was fought in which year?',
 '[{"text":"1757","isCorrect":true},{"text":"1764","isCorrect":false},{"text":"1857","isCorrect":false},{"text":"1748","isCorrect":false}]'::jsonb,
 null, 'The Battle of Plassey was fought in 1757 between the British East India Company and the Nawab of Bengal.'),

-- General Awareness: Indian Polity and Geography
('SSC-CHSL', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'How many fundamental rights are guaranteed by the Indian Constitution?',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":true},{"text":"7","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'The Indian Constitution guarantees 6 fundamental rights to its citizens.'),
('SSC-CHSL', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the longest river in India?',
 '[{"text":"Yamuna","isCorrect":false},{"text":"Godavari","isCorrect":false},{"text":"Ganga","isCorrect":true},{"text":"Brahmaputra","isCorrect":false}]'::jsonb,
 null, 'The Ganga is the longest river in India, flowing about 2,525 km.'),
('SSC-CHSL', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'The Indian Constitution was adopted by the Constituent Assembly on which date?',
 '[{"text":"26 January 1950","isCorrect":false},{"text":"26 November 1949","isCorrect":true},{"text":"15 August 1947","isCorrect":false},{"text":"26 January 1949","isCorrect":false}]'::jsonb,
 null, 'The Constitution was adopted on 26 November 1949 and came into force on 26 January 1950.'),
('SSC-CHSL', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which state has the longest coastline in India?',
 '[{"text":"Tamil Nadu","isCorrect":false},{"text":"Kerala","isCorrect":false},{"text":"Gujarat","isCorrect":true},{"text":"Maharashtra","isCorrect":false}]'::jsonb,
 null, 'Gujarat has the longest coastline among Indian states, at over 1,600 km.'),

-- General Awareness: Indian Economy and General Science
('SSC-CHSL', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'Which is the central bank of India?',
 '[{"text":"SBI","isCorrect":false},{"text":"RBI","isCorrect":true},{"text":"NABARD","isCorrect":false},{"text":"SEBI","isCorrect":false}]'::jsonb,
 null, 'The Reserve Bank of India (RBI) is the central bank of India.'),
('SSC-CHSL', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'What is the SI unit of force?',
 '[{"text":"Joule","isCorrect":false},{"text":"Newton","isCorrect":true},{"text":"Watt","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'The SI unit of force is the Newton (N).'),
('SSC-CHSL', 'General Awareness', 'Indian Economy and General Science', 'medium', 'mcq',
 'The term "GDP" stands for:',
 '[{"text":"Gross Domestic Product","isCorrect":true},{"text":"General Domestic Price","isCorrect":false},{"text":"Government Development Plan","isCorrect":false},{"text":"Gross Development Product","isCorrect":false}]'::jsonb,
 null, 'GDP stands for Gross Domestic Product, the total value of goods and services produced in a country.'),
('SSC-CHSL', 'General Awareness', 'Indian Economy and General Science', 'medium', 'mcq',
 'Which gas is most abundant in the Earth''s atmosphere?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":false},{"text":"Nitrogen","isCorrect":true},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Nitrogen makes up about 78% of the Earth''s atmosphere, making it the most abundant gas.'),

-- General Awareness: Current Affairs and Static GK
('SSC-CHSL', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'Which is the national bird of India?',
 '[{"text":"Peacock","isCorrect":true},{"text":"Sparrow","isCorrect":false},{"text":"Eagle","isCorrect":false},{"text":"Parrot","isCorrect":false}]'::jsonb,
 null, 'The peacock is the national bird of India.'),
('SSC-CHSL', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'The headquarters of the United Nations is located in which city?',
 '[{"text":"Geneva","isCorrect":false},{"text":"New York","isCorrect":true},{"text":"Paris","isCorrect":false},{"text":"London","isCorrect":false}]'::jsonb,
 null, 'The United Nations headquarters is located in New York City, USA.'),
('SSC-CHSL', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'Which Indian city is known as the "Silicon Valley of India"?',
 '[{"text":"Hyderabad","isCorrect":false},{"text":"Chennai","isCorrect":false},{"text":"Bengaluru","isCorrect":true},{"text":"Pune","isCorrect":false}]'::jsonb,
 null, 'Bengaluru is known as the Silicon Valley of India due to its large concentration of IT companies.'),
('SSC-CHSL', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'The Nobel Prize is awarded in memory of whom?',
 '[{"text":"Alfred Nobel","isCorrect":true},{"text":"Albert Einstein","isCorrect":false},{"text":"Isaac Newton","isCorrect":false},{"text":"Marie Curie","isCorrect":false}]'::jsonb,
 null, 'The Nobel Prize was established by and is awarded in memory of Alfred Nobel, the inventor of dynamite.'),

-- Quantitative Aptitude: Number System and Simplification
('SSC-CHSL', 'Quantitative Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 45 - 15 / 3 + 2',
 '[{"text":"32","isCorrect":false},{"text":"42","isCorrect":true},{"text":"10","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Following order of operations: 15/3 = 5, then 45 - 5 + 2 = 42.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following is a prime number?',
 '[{"text":"51","isCorrect":false},{"text":"57","isCorrect":false},{"text":"59","isCorrect":true},{"text":"63","isCorrect":false}]'::jsonb,
 null, '59 has no divisors other than 1 and itself, while 51, 57, and 63 are all divisible by 3.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Number System and Simplification', 'medium', 'mcq',
 'Find the value of 0.25 x 0.4.',
 '[{"text":"0.1","isCorrect":true},{"text":"1.0","isCorrect":false},{"text":"0.01","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, '0.25 x 0.4 = 0.1.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Number System and Simplification', 'medium', 'mcq',
 'What is the sum of the first 10 natural numbers?',
 '[{"text":"45","isCorrect":false},{"text":"55","isCorrect":true},{"text":"50","isCorrect":false},{"text":"60","isCorrect":false}]'::jsonb,
 null, 'The sum of the first n natural numbers is n(n+1)/2. For n=10, this is 10x11/2 = 55.'),

-- Quantitative Aptitude: Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)
('SSC-CHSL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'easy', 'mcq',
 '25% of 200 is:',
 '[{"text":"25","isCorrect":false},{"text":"50","isCorrect":true},{"text":"75","isCorrect":false},{"text":"100","isCorrect":false}]'::jsonb,
 null, '25% of 200 = (25/100) x 200 = 50.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'easy', 'mcq',
 'A shopkeeper buys an item for Rs. 80 and sells it for Rs. 100. Find the profit percentage.',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"30%","isCorrect":false},{"text":"15%","isCorrect":false}]'::jsonb,
 null, 'Profit = 100 - 80 = 20. Profit percentage = (20/80) x 100 = 25%.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'medium', 'mcq',
 'Find the simple interest on Rs. 2000 at 5% per annum for 3 years.',
 '[{"text":"Rs. 200","isCorrect":false},{"text":"Rs. 300","isCorrect":true},{"text":"Rs. 100","isCorrect":false},{"text":"Rs. 400","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = (Principal x Rate x Time) / 100 = (2000 x 5 x 3) / 100 = Rs. 300.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Arithmetic (Percentage, Profit-Loss, SI-CI, Ratio)', 'medium', 'mcq',
 'Rs. 900 is divided between A and B in the ratio 4:5. Find B''s share.',
 '[{"text":"Rs. 400","isCorrect":false},{"text":"Rs. 500","isCorrect":true},{"text":"Rs. 450","isCorrect":false},{"text":"Rs. 600","isCorrect":false}]'::jsonb,
 null, 'Total parts = 4+5 = 9. B''s share = (5/9) x 900 = Rs. 500.'),

-- Quantitative Aptitude: Geometry and Mensuration
('SSC-CHSL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'The sum of the angles in a triangle is:',
 '[{"text":"90 degrees","isCorrect":false},{"text":"180 degrees","isCorrect":true},{"text":"270 degrees","isCorrect":false},{"text":"360 degrees","isCorrect":false}]'::jsonb,
 null, 'The sum of the interior angles of any triangle is always 180 degrees.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'easy', 'mcq',
 'Find the area of a rectangle with length 8 cm and breadth 5 cm.',
 '[{"text":"13 cm^2","isCorrect":false},{"text":"40 cm^2","isCorrect":true},{"text":"26 cm^2","isCorrect":false},{"text":"45 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a rectangle = length x breadth = 8 x 5 = 40 cm^2.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'medium', 'mcq',
 'Find the perimeter of a square with side 7 cm.',
 '[{"text":"14 cm","isCorrect":false},{"text":"21 cm","isCorrect":false},{"text":"28 cm","isCorrect":true},{"text":"49 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a square = 4 x side = 4 x 7 = 28 cm.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Geometry and Mensuration', 'medium', 'mcq',
 'Find the circumference of a circle with radius 7 cm (use pi = 22/7).',
 '[{"text":"22 cm","isCorrect":false},{"text":"44 cm","isCorrect":true},{"text":"154 cm","isCorrect":false},{"text":"14 cm","isCorrect":false}]'::jsonb,
 null, 'Circumference = 2 x pi x r = 2 x (22/7) x 7 = 44 cm.'),

-- Quantitative Aptitude: Trigonometry and Data Interpretation
('SSC-CHSL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'easy', 'mcq',
 'The value of sin(90 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"-1","isCorrect":false},{"text":"1/2","isCorrect":false}]'::jsonb,
 null, 'sin(90 degrees) = 1, a standard trigonometric value.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'easy', 'mcq',
 'The value of cos(0 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"-1","isCorrect":false},{"text":"1/2","isCorrect":false}]'::jsonb,
 null, 'cos(0 degrees) = 1, a standard trigonometric value.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'medium', 'mcq',
 'If tan(theta) = 1, find theta (where 0 <= theta <= 90 degrees).',
 '[{"text":"30 degrees","isCorrect":false},{"text":"45 degrees","isCorrect":true},{"text":"60 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":false}]'::jsonb,
 null, 'tan(45 degrees) = 1, so theta = 45 degrees.'),
('SSC-CHSL', 'Quantitative Aptitude', 'Trigonometry and Data Interpretation', 'medium', 'mcq',
 'A pie chart represents total sales of 360 units across a full circle. If one sector spans 90 degrees, how many units does it represent?',
 '[{"text":"60","isCorrect":false},{"text":"90","isCorrect":true},{"text":"120","isCorrect":false},{"text":"180","isCorrect":false}]'::jsonb,
 null, 'The sector represents (90/360) of the total, so (90/360) x 360 = 90 units.'),

-- English Language: Grammar and Error Spotting
('SSC-CHSL', 'English Language', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Recieve","isCorrect":false},{"text":"Receive","isCorrect":true},{"text":"Receve","isCorrect":false},{"text":"Receeve","isCorrect":false}]'::jsonb,
 null, '"Receive" follows the rule "i before e except after c" and is the correct spelling.'),
('SSC-CHSL', 'English Language', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Fill in the blank: "She ___ to school every day."',
 '[{"text":"go","isCorrect":false},{"text":"goes","isCorrect":true},{"text":"going","isCorrect":false},{"text":"gone","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject ("She") in the present tense, the verb takes an -s: "goes".'),
('SSC-CHSL', 'English Language', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Identify the part with an error: "Neither of the boys (A) have (B) completed their (C) homework. No error (D)."',
 '[{"text":"A","isCorrect":false},{"text":"B","isCorrect":true},{"text":"C","isCorrect":false},{"text":"D","isCorrect":false}]'::jsonb,
 null, '"Neither" is singular, so the verb should be "has", not "have".'),
('SSC-CHSL', 'English Language', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Choose the correct passive voice of: "She writes a letter."',
 '[{"text":"A letter is written by her.","isCorrect":true},{"text":"A letter was written by her.","isCorrect":false},{"text":"A letter has written by her.","isCorrect":false},{"text":"A letter written by her.","isCorrect":false}]'::jsonb,
 null, 'The present tense active "writes" becomes "is written" in the passive voice.'),

-- English Language: Vocabulary (Synonyms, Antonyms, Spelling)
('SSC-CHSL', 'English Language', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the synonym of "Happy".',
 '[{"text":"Sad","isCorrect":false},{"text":"Joyful","isCorrect":true},{"text":"Angry","isCorrect":false},{"text":"Tired","isCorrect":false}]'::jsonb,
 null, '"Joyful" means feeling or expressing great happiness, making it a synonym of "Happy".'),
('SSC-CHSL', 'English Language', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the antonym of "Ancient".',
 '[{"text":"Old","isCorrect":false},{"text":"Modern","isCorrect":true},{"text":"Historic","isCorrect":false},{"text":"Aged","isCorrect":false}]'::jsonb,
 null, '"Modern" means relating to the present time, the opposite of "Ancient".'),
('SSC-CHSL', 'English Language', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the synonym of "Abundant".',
 '[{"text":"Scarce","isCorrect":false},{"text":"Plentiful","isCorrect":true},{"text":"Rare","isCorrect":false},{"text":"Little","isCorrect":false}]'::jsonb,
 null, '"Plentiful" means existing in large quantities, making it a synonym of "Abundant".'),
('SSC-CHSL', 'English Language', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the antonym of "Diligent".',
 '[{"text":"Hardworking","isCorrect":false},{"text":"Lazy","isCorrect":true},{"text":"Careful","isCorrect":false},{"text":"Sincere","isCorrect":false}]'::jsonb,
 null, '"Lazy" means unwilling to work hard, the opposite of "Diligent".'),

-- English Language: Cloze Test and Fill in the Blanks
('SSC-CHSL', 'English Language', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "He is good ___ mathematics."',
 '[{"text":"at","isCorrect":true},{"text":"in","isCorrect":false},{"text":"on","isCorrect":false},{"text":"with","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "good at" a subject.'),
('SSC-CHSL', 'English Language', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "She has been living here ___ 2010."',
 '[{"text":"for","isCorrect":false},{"text":"since","isCorrect":true},{"text":"from","isCorrect":false},{"text":"at","isCorrect":false}]'::jsonb,
 null, '"Since" is used with a specific point in time, while "for" is used with a duration.'),
('SSC-CHSL', 'English Language', 'Cloze Test and Fill in the Blanks', 'medium', 'mcq',
 'Fill in the blank: "The train arrived ___ time."',
 '[{"text":"on","isCorrect":true},{"text":"in","isCorrect":false},{"text":"at","isCorrect":false},{"text":"by","isCorrect":false}]'::jsonb,
 null, 'The idiomatic phrase is "on time", meaning punctual.'),
('SSC-CHSL', 'English Language', 'Cloze Test and Fill in the Blanks', 'medium', 'mcq',
 'Fill in the blank: "He apologized ___ his mistake."',
 '[{"text":"for","isCorrect":true},{"text":"of","isCorrect":false},{"text":"with","isCorrect":false},{"text":"about","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "apologize for" something.'),

-- English Language: Reading Comprehension and Para Jumbles
('SSC-CHSL', 'English Language', 'Reading Comprehension and Para Jumbles', 'easy', 'mcq',
 'Choose the word closest in meaning to "commence" as used in formal writing.',
 '[{"text":"End","isCorrect":false},{"text":"Begin","isCorrect":true},{"text":"Pause","isCorrect":false},{"text":"Continue","isCorrect":false}]'::jsonb,
 null, '"Commence" means to begin or start something.'),
('SSC-CHSL', 'English Language', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'What does the proverb "The early bird catches the worm" mean?',
 '[{"text":"Birds eat worms","isCorrect":false},{"text":"Those who act early gain an advantage","isCorrect":true},{"text":"Worms are caught by birds","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'This proverb means that people who start early or act promptly are more likely to succeed.'),
('SSC-CHSL', 'English Language', 'Reading Comprehension and Para Jumbles', 'medium', 'mcq',
 'Choose the sentence that is grammatically correct.',
 '[{"text":"He don''t like tea.","isCorrect":false},{"text":"He doesn''t like tea.","isCorrect":true},{"text":"He not like tea.","isCorrect":false},{"text":"He isn''t liking tea.","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject, the correct negative form uses "doesn''t".'),
('SSC-CHSL', 'English Language', 'Reading Comprehension and Para Jumbles', 'hard', 'mcq',
 'Arrange the sentences in logical order: 1. Then she made breakfast. 2. She woke up early. 3. After that she went for a walk.',
 '[{"text":"2, 1, 3","isCorrect":true},{"text":"1, 2, 3","isCorrect":false},{"text":"3, 2, 1","isCorrect":false},{"text":"2, 3, 1","isCorrect":false}]'::jsonb,
 null, 'The logical sequence of events is: she woke up early (2), then made breakfast (1), then went for a walk (3).');
