-- supabase/sql/exam_question_bank_class2_set1.sql
--
-- First curated question-bank batch for 'Class 2' (see exam_patterns_class2.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 2's MCQ-only,
-- no-negative-marking pattern. 9 chapters (3 per subject x 3 subjects) each get 4 questions, mostly
-- easy with one or two medium, reflecting the easy-skewed weightage in exam_patterns_class2.sql.
-- Pitched one notch above Class 1 (see exam_question_bank_class1_set1.sql) -- 3-digit numbers,
-- plurals, and slightly broader EVS topics.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class2.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Naming Words, Action Words and Simple Sentences
('Class 2', 'English', 'Naming Words, Action Words and Simple Sentences', 'easy', 'mcq',
 'Which of the following is a naming word (noun)?',
 '[{"text":"Run","isCorrect":false},{"text":"Table","isCorrect":true},{"text":"Jump","isCorrect":false},{"text":"Sing","isCorrect":false}]'::jsonb,
 null, 'A naming word (noun) names a person, place, or thing. ''Table'' is a thing, so it is a noun.'),
('Class 2', 'English', 'Naming Words, Action Words and Simple Sentences', 'easy', 'mcq',
 'Which of the following is an action word (verb)?',
 '[{"text":"Chair","isCorrect":false},{"text":"Happy","isCorrect":false},{"text":"Jump","isCorrect":true},{"text":"Book","isCorrect":false}]'::jsonb,
 null, 'An action word (verb) tells us what someone is doing. ''Jump'' is an action, so it is a verb.'),
('Class 2', 'English', 'Naming Words, Action Words and Simple Sentences', 'easy', 'mcq',
 'Choose the sentence that is written correctly.',
 '[{"text":"the cat is sleeping","isCorrect":false},{"text":"The cat is sleeping.","isCorrect":true},{"text":"The cat is sleeping","isCorrect":false},{"text":"the Cat is Sleeping","isCorrect":false}]'::jsonb,
 null, 'A correct sentence starts with a capital letter and ends with a full stop.'),
('Class 2', 'English', 'Naming Words, Action Words and Simple Sentences', 'medium', 'mcq',
 'Which word in the sentence "Riya sings a song" is the naming word for a person?',
 '[{"text":"Sings","isCorrect":false},{"text":"Riya","isCorrect":true},{"text":"A","isCorrect":false},{"text":"Song","isCorrect":false}]'::jsonb,
 null, '''Riya'' names a person, making it the naming word (noun) for a person in the sentence.'),

-- English: Rhyming Words, Opposites and Plurals
('Class 2', 'English', 'Rhyming Words, Opposites and Plurals', 'easy', 'mcq',
 'Which word rhymes with ''LIGHT''?',
 '[{"text":"Night","isCorrect":true},{"text":"Late","isCorrect":false},{"text":"Loud","isCorrect":false},{"text":"Line","isCorrect":false}]'::jsonb,
 null, '''Night'' rhymes with ''Light'' because they both end with the same ''-ight'' sound.'),
('Class 2', 'English', 'Rhyming Words, Opposites and Plurals', 'easy', 'mcq',
 'What is the opposite of ''FULL''?',
 '[{"text":"Empty","isCorrect":true},{"text":"Heavy","isCorrect":false},{"text":"Big","isCorrect":false},{"text":"Wet","isCorrect":false}]'::jsonb,
 null, 'The opposite of ''Full'' is ''Empty''.'),
('Class 2', 'English', 'Rhyming Words, Opposites and Plurals', 'easy', 'mcq',
 'What is the plural of ''BOX''?',
 '[{"text":"Boxs","isCorrect":false},{"text":"Boxes","isCorrect":true},{"text":"Boxies","isCorrect":false},{"text":"Box","isCorrect":false}]'::jsonb,
 null, 'Words ending in ''x'' usually form their plural by adding ''es'', so the plural of ''Box'' is ''Boxes''.'),
('Class 2', 'English', 'Rhyming Words, Opposites and Plurals', 'medium', 'mcq',
 'What is the plural of ''CHILD''?',
 '[{"text":"Childs","isCorrect":false},{"text":"Childes","isCorrect":false},{"text":"Children","isCorrect":true},{"text":"Childrens","isCorrect":false}]'::jsonb,
 null, '''Child'' has an irregular plural form: ''Children''.'),

-- English: Reading Comprehension and Picture Vocabulary
('Class 2', 'English', 'Reading Comprehension and Picture Vocabulary', 'easy', 'mcq',
 'A place where books are kept for people to read or borrow is called a:',
 '[{"text":"Library","isCorrect":true},{"text":"Kitchen","isCorrect":false},{"text":"Garden","isCorrect":false},{"text":"Playground","isCorrect":false}]'::jsonb,
 null, 'A library is a place where books are kept for reading and borrowing.'),
('Class 2', 'English', 'Reading Comprehension and Picture Vocabulary', 'easy', 'mcq',
 'A young dog is called a:',
 '[{"text":"Kitten","isCorrect":false},{"text":"Puppy","isCorrect":true},{"text":"Calf","isCorrect":false},{"text":"Cub","isCorrect":false}]'::jsonb,
 null, 'A young dog is called a puppy.'),
('Class 2', 'English', 'Reading Comprehension and Picture Vocabulary', 'medium', 'mcq',
 'Read: "Maya has a red umbrella. She uses it when it rains." What colour is Maya''s umbrella?',
 '[{"text":"Blue","isCorrect":false},{"text":"Red","isCorrect":true},{"text":"Yellow","isCorrect":false},{"text":"Green","isCorrect":false}]'::jsonb,
 null, 'The passage says Maya has a red umbrella.'),
('Class 2', 'English', 'Reading Comprehension and Picture Vocabulary', 'medium', 'mcq',
 'Read: "Sam plays football every evening with his friends." When does Sam play football?',
 '[{"text":"Every morning","isCorrect":false},{"text":"Every evening","isCorrect":true},{"text":"Only on Sundays","isCorrect":false},{"text":"At night","isCorrect":false}]'::jsonb,
 null, 'The passage says Sam plays football every evening with his friends.'),

-- Mathematics: Numbers up to 1000 (Place Value, Before-After-Between)
('Class 2', 'Mathematics', 'Numbers up to 1000 (Place Value, Before-After-Between)', 'easy', 'mcq',
 'What number comes just after 199?',
 '[{"text":"198","isCorrect":false},{"text":"200","isCorrect":true},{"text":"201","isCorrect":false},{"text":"209","isCorrect":false}]'::jsonb,
 null, 'Counting up from 199, the next number is 200.'),
('Class 2', 'Mathematics', 'Numbers up to 1000 (Place Value, Before-After-Between)', 'easy', 'mcq',
 'What number comes just before 500?',
 '[{"text":"499","isCorrect":true},{"text":"501","isCorrect":false},{"text":"490","isCorrect":false},{"text":"510","isCorrect":false}]'::jsonb,
 null, 'Counting down from 500, the number right before it is 499.'),
('Class 2', 'Mathematics', 'Numbers up to 1000 (Place Value, Before-After-Between)', 'medium', 'mcq',
 'In the number 356, what is the digit in the tens place?',
 '[{"text":"3","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'In 356, 3 is in the hundreds place, 5 is in the tens place, and 6 is in the ones place.'),
('Class 2', 'Mathematics', 'Numbers up to 1000 (Place Value, Before-After-Between)', 'medium', 'mcq',
 'Which number is between 645 and 647?',
 '[{"text":"644","isCorrect":false},{"text":"646","isCorrect":true},{"text":"648","isCorrect":false},{"text":"650","isCorrect":false}]'::jsonb,
 null, '646 comes right between 645 and 647 when counting in order.'),

-- Mathematics: Addition and Subtraction (up to 3-Digit Numbers)
('Class 2', 'Mathematics', 'Addition and Subtraction (up to 3-Digit Numbers)', 'easy', 'mcq',
 '124 + 35 = ?',
 '[{"text":"159","isCorrect":true},{"text":"149","isCorrect":false},{"text":"169","isCorrect":false},{"text":"158","isCorrect":false}]'::jsonb,
 null, '124 + 35 = 159.'),
('Class 2', 'Mathematics', 'Addition and Subtraction (up to 3-Digit Numbers)', 'easy', 'mcq',
 '250 - 120 = ?',
 '[{"text":"110","isCorrect":false},{"text":"130","isCorrect":true},{"text":"140","isCorrect":false},{"text":"120","isCorrect":false}]'::jsonb,
 null, '250 - 120 = 130.'),
('Class 2', 'Mathematics', 'Addition and Subtraction (up to 3-Digit Numbers)', 'easy', 'mcq',
 '308 + 90 = ?',
 '[{"text":"388","isCorrect":false},{"text":"398","isCorrect":true},{"text":"408","isCorrect":false},{"text":"318","isCorrect":false}]'::jsonb,
 null, '308 + 90 = 398.'),
('Class 2', 'Mathematics', 'Addition and Subtraction (up to 3-Digit Numbers)', 'medium', 'mcq',
 '450 - 75 + 25 = ?',
 '[{"text":"400","isCorrect":true},{"text":"390","isCorrect":false},{"text":"410","isCorrect":false},{"text":"380","isCorrect":false}]'::jsonb,
 null, 'First 450 - 75 = 375, then 375 + 25 = 400.'),

-- Mathematics: Shapes, Patterns, Measurement and Time
('Class 2', 'Mathematics', 'Shapes, Patterns, Measurement and Time', 'easy', 'mcq',
 'How many sides does a rectangle have?',
 '[{"text":"3","isCorrect":false},{"text":"4","isCorrect":true},{"text":"5","isCorrect":false},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'A rectangle has 4 sides.'),
('Class 2', 'Mathematics', 'Shapes, Patterns, Measurement and Time', 'easy', 'mcq',
 'How many minutes are there in one hour?',
 '[{"text":"30","isCorrect":false},{"text":"45","isCorrect":false},{"text":"60","isCorrect":true},{"text":"100","isCorrect":false}]'::jsonb,
 null, 'There are 60 minutes in one hour.'),
('Class 2', 'Mathematics', 'Shapes, Patterns, Measurement and Time', 'easy', 'mcq',
 'Which of these is used to measure length?',
 '[{"text":"Clock","isCorrect":false},{"text":"Ruler","isCorrect":true},{"text":"Weighing scale","isCorrect":false},{"text":"Thermometer","isCorrect":false}]'::jsonb,
 null, 'A ruler is used to measure the length of an object.'),
('Class 2', 'Mathematics', 'Shapes, Patterns, Measurement and Time', 'medium', 'mcq',
 'In the pattern 2, 4, 6, 8, ___, what comes next?',
 '[{"text":"9","isCorrect":false},{"text":"10","isCorrect":true},{"text":"11","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'The pattern increases by 2 each time, so after 8 comes 10.'),

-- EVS: My Family, Food and Housing
('Class 2', 'EVS', 'My Family, Food and Housing', 'easy', 'mcq',
 'What do we call the brother of your father?',
 '[{"text":"Uncle","isCorrect":true},{"text":"Cousin","isCorrect":false},{"text":"Nephew","isCorrect":false},{"text":"Grandfather","isCorrect":false}]'::jsonb,
 null, 'Your father''s brother is called your uncle.'),
('Class 2', 'EVS', 'My Family, Food and Housing', 'easy', 'mcq',
 'Which of these foods is made from wheat?',
 '[{"text":"Rice","isCorrect":false},{"text":"Chapati","isCorrect":true},{"text":"Milk","isCorrect":false},{"text":"Egg","isCorrect":false}]'::jsonb,
 null, 'Chapati is made from wheat flour.'),
('Class 2', 'EVS', 'My Family, Food and Housing', 'easy', 'mcq',
 'Which of these is a basic need of every human being?',
 '[{"text":"Television","isCorrect":false},{"text":"Shelter","isCorrect":true},{"text":"Bicycle","isCorrect":false},{"text":"Toys","isCorrect":false}]'::jsonb,
 null, 'Food, clothing, and shelter are the basic needs of every human being.'),
('Class 2', 'EVS', 'My Family, Food and Housing', 'medium', 'mcq',
 'A family that has parents, children, grandparents, uncles, and aunts all living together is called a:',
 '[{"text":"Nuclear family","isCorrect":false},{"text":"Joint family","isCorrect":true},{"text":"Single family","isCorrect":false},{"text":"Small family","isCorrect":false}]'::jsonb,
 null, 'A family where grandparents, parents, children, and other relatives live together is called a joint family.'),

-- EVS: Plants, Animals and Water
('Class 2', 'EVS', 'Plants, Animals and Water', 'easy', 'mcq',
 'Which part of the plant absorbs water from the soil?',
 '[{"text":"Leaf","isCorrect":false},{"text":"Flower","isCorrect":false},{"text":"Root","isCorrect":true},{"text":"Fruit","isCorrect":false}]'::jsonb,
 null, 'The root absorbs water and nutrients from the soil.'),
('Class 2', 'EVS', 'Plants, Animals and Water', 'easy', 'mcq',
 'Which of these animals lives in water?',
 '[{"text":"Fish","isCorrect":true},{"text":"Goat","isCorrect":false},{"text":"Horse","isCorrect":false},{"text":"Camel","isCorrect":false}]'::jsonb,
 null, 'A fish lives in water and breathes using gills.'),
('Class 2', 'EVS', 'Plants, Animals and Water', 'easy', 'mcq',
 'What do plants need, along with water and air, to make their own food?',
 '[{"text":"Sunlight","isCorrect":true},{"text":"Sand","isCorrect":false},{"text":"Salt","isCorrect":false},{"text":"Ice","isCorrect":false}]'::jsonb,
 null, 'Plants need sunlight, along with water and air, to make their own food.'),
('Class 2', 'EVS', 'Plants, Animals and Water', 'medium', 'mcq',
 'Which of these is a way to save water at home?',
 '[{"text":"Leaving the tap running","isCorrect":false},{"text":"Turning off the tap while brushing teeth","isCorrect":true},{"text":"Washing hands for a long time","isCorrect":false},{"text":"Filling more water than needed","isCorrect":false}]'::jsonb,
 null, 'Turning off the tap while brushing our teeth helps save water.'),

-- EVS: Our Neighbourhood, Transport and Safety
('Class 2', 'EVS', 'Our Neighbourhood, Transport and Safety', 'easy', 'mcq',
 'Who helps us when we are sick?',
 '[{"text":"Doctor","isCorrect":true},{"text":"Postman","isCorrect":false},{"text":"Farmer","isCorrect":false},{"text":"Tailor","isCorrect":false}]'::jsonb,
 null, 'A doctor helps us when we are sick by treating our illness.'),
('Class 2', 'EVS', 'Our Neighbourhood, Transport and Safety', 'easy', 'mcq',
 'Which of these is a mode of transport that travels on water?',
 '[{"text":"Bus","isCorrect":false},{"text":"Boat","isCorrect":true},{"text":"Train","isCorrect":false},{"text":"Car","isCorrect":false}]'::jsonb,
 null, 'A boat travels on water, unlike a bus, train, or car which travel on land.'),
('Class 2', 'EVS', 'Our Neighbourhood, Transport and Safety', 'easy', 'mcq',
 'What number should we call in India during an emergency?',
 '[{"text":"100","isCorrect":false},{"text":"112","isCorrect":true},{"text":"911","isCorrect":false},{"text":"000","isCorrect":false}]'::jsonb,
 null, '112 is the common emergency helpline number in India.'),
('Class 2', 'EVS', 'Our Neighbourhood, Transport and Safety', 'medium', 'mcq',
 'Which of these people helps deliver letters and parcels to our home?',
 '[{"text":"Postman","isCorrect":true},{"text":"Doctor","isCorrect":false},{"text":"Police officer","isCorrect":false},{"text":"Teacher","isCorrect":false}]'::jsonb,
 null, 'A postman delivers letters and parcels to our homes.');
