-- supabase/sql/exam_question_bank_ssc_mts_set1.sql
--
-- First curated question-bank batch for 'SSC-MTS' (see exam_patterns_ssc_mts.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (100% single-best-response,
-- matching the real exam). Pitched noticeably easier than SSC-CGL (see
-- exam_question_bank_ssc_cgl_set1.sql), reflecting MTS's 10th-standard-level syllabus. Non-Verbal
-- Reasoning again uses text-describable cube-painting/paper-folding puzzles in place of
-- figure-based questions, which need images this schema can't provide. 16 chapters (4 per section
-- x 4 sections) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_mts.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Numerical Aptitude: Number System and Simplification
('SSC-MTS', 'Numerical Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 15 + 3 x 4 - 2',
 '[{"text":"25","isCorrect":true},{"text":"22","isCorrect":false},{"text":"58","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Following order of operations, first multiply 3x4=12, then 15+12-2=25.'),
('SSC-MTS', 'Numerical Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'Find the value of 144 divided by 12, multiplied by 3.',
 '[{"text":"36","isCorrect":true},{"text":"4","isCorrect":false},{"text":"432","isCorrect":false},{"text":"48","isCorrect":false}]'::jsonb,
 null, '144/12=12, then 12*3=36.'),
('SSC-MTS', 'Numerical Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following is a prime number?',
 '[{"text":"15","isCorrect":false},{"text":"17","isCorrect":true},{"text":"21","isCorrect":false},{"text":"27","isCorrect":false}]'::jsonb,
 null, '17 has no divisors other than 1 and itself, making it a prime number, while 15, 21, and 27 are all divisible by numbers other than 1 and themselves.'),
('SSC-MTS', 'Numerical Aptitude', 'Number System and Simplification', 'easy', 'mcq',
 'The smallest whole number is:',
 '[{"text":"0","isCorrect":true},{"text":"1","isCorrect":false},{"text":"-1","isCorrect":false},{"text":"There is no smallest whole number","isCorrect":false}]'::jsonb,
 null, 'Whole numbers include 0, 1, 2, 3, and so on, making 0 the smallest whole number.'),

-- Numerical Aptitude: Percentage and Ratio
('SSC-MTS', 'Numerical Aptitude', 'Percentage and Ratio', 'easy', 'mcq',
 '20% of 150 is:',
 '[{"text":"20","isCorrect":false},{"text":"30","isCorrect":true},{"text":"25","isCorrect":false},{"text":"35","isCorrect":false}]'::jsonb,
 null, '20% of 150 = (20/100)*150 = 30.'),
('SSC-MTS', 'Numerical Aptitude', 'Percentage and Ratio', 'medium', 'mcq',
 'The ratio of boys to girls in a class is 3:2. If there are 30 students in total, find the number of boys.',
 '[{"text":"12","isCorrect":false},{"text":"18","isCorrect":true},{"text":"15","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Let boys=3x and girls=2x; 3x+2x=30 gives x=6, so boys = 3*6=18.'),
('SSC-MTS', 'Numerical Aptitude', 'Percentage and Ratio', 'medium', 'mcq',
 'If a number is increased by 25%, it becomes 100. Find the original number.',
 '[{"text":"75","isCorrect":false},{"text":"80","isCorrect":true},{"text":"85","isCorrect":false},{"text":"90","isCorrect":false}]'::jsonb,
 null, 'If x increased by 25% equals 100, then 1.25x=100, giving x=80.'),
('SSC-MTS', 'Numerical Aptitude', 'Percentage and Ratio', 'easy', 'mcq',
 'Express 3/4 as a percentage.',
 '[{"text":"34%","isCorrect":false},{"text":"75%","isCorrect":true},{"text":"43%","isCorrect":false},{"text":"25%","isCorrect":false}]'::jsonb,
 null, '3/4 = 0.75 = 75%.'),

-- Numerical Aptitude: Profit Loss and Simple/Compound Interest
('SSC-MTS', 'Numerical Aptitude', 'Profit Loss and Simple/Compound Interest', 'easy', 'mcq',
 'If the cost price of an item is Rs. 200 and the profit is Rs. 40, find the profit percentage.',
 '[{"text":"15%","isCorrect":false},{"text":"20%","isCorrect":true},{"text":"25%","isCorrect":false},{"text":"40%","isCorrect":false}]'::jsonb,
 null, 'Profit% = (Profit/Cost Price)*100 = (40/200)*100 = 20%.'),
('SSC-MTS', 'Numerical Aptitude', 'Profit Loss and Simple/Compound Interest', 'easy', 'mcq',
 'A sum of Rs. 1000 is invested at 5% simple interest per annum for 3 years. Find the interest earned.',
 '[{"text":"Rs. 100","isCorrect":false},{"text":"Rs. 150","isCorrect":true},{"text":"Rs. 50","isCorrect":false},{"text":"Rs. 200","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = P*R*T/100 = 1000*5*3/100 = 150.'),
('SSC-MTS', 'Numerical Aptitude', 'Profit Loss and Simple/Compound Interest', 'easy', 'mcq',
 'A shopkeeper sells an article at a loss of 10%. If the cost price is Rs. 500, find the selling price.',
 '[{"text":"Rs. 450","isCorrect":true},{"text":"Rs. 480","isCorrect":false},{"text":"Rs. 550","isCorrect":false},{"text":"Rs. 400","isCorrect":false}]'::jsonb,
 null, 'A 10% loss on Rs. 500 is Rs. 50, so the selling price is 500-50=450.'),
('SSC-MTS', 'Numerical Aptitude', 'Profit Loss and Simple/Compound Interest', 'medium', 'mcq',
 'For a sum invested for exactly 1 year, the compound interest (compounded annually) and the simple interest are:',
 '[{"text":"Always different","isCorrect":false},{"text":"Always equal","isCorrect":true},{"text":"Compound interest is always lower","isCorrect":false},{"text":"Simple interest is always lower","isCorrect":false}]'::jsonb,
 null, 'Since compounding only makes a difference across multiple periods, for exactly one year (with annual compounding), compound interest and simple interest give the same result.'),

-- Numerical Aptitude: Mensuration and Basic Geometry
('SSC-MTS', 'Numerical Aptitude', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'The perimeter of a square with side 5 cm is:',
 '[{"text":"10 cm","isCorrect":false},{"text":"20 cm","isCorrect":true},{"text":"25 cm","isCorrect":false},{"text":"15 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a square = 4*side = 4*5=20 cm.'),
('SSC-MTS', 'Numerical Aptitude', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'The area of a rectangle with length 8 cm and breadth 5 cm is:',
 '[{"text":"13 sq cm","isCorrect":false},{"text":"40 sq cm","isCorrect":true},{"text":"26 sq cm","isCorrect":false},{"text":"35 sq cm","isCorrect":false}]'::jsonb,
 null, 'Area of a rectangle = length * breadth = 8*5=40 sq cm.'),
('SSC-MTS', 'Numerical Aptitude', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'The number of sides in a hexagon is:',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":true},{"text":"7","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A hexagon is a polygon with 6 sides.'),
('SSC-MTS', 'Numerical Aptitude', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'The sum of the interior angles of a quadrilateral is:',
 '[{"text":"180 degrees","isCorrect":false},{"text":"270 degrees","isCorrect":false},{"text":"360 degrees","isCorrect":true},{"text":"450 degrees","isCorrect":false}]'::jsonb,
 null, 'The interior angles of any quadrilateral always sum to 360 degrees.'),

-- Reasoning Ability and Problem Solving: Analogy and Classification
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Analogy and Classification', 'easy', 'mcq',
 'Complete the analogy: Fish is to Water as Bird is to:',
 '[{"text":"Nest","isCorrect":false},{"text":"Air","isCorrect":true},{"text":"Tree","isCorrect":false},{"text":"Feather","isCorrect":false}]'::jsonb,
 null, 'Just as a fish primarily lives in water, a bird primarily flies through air.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Analogy and Classification', 'easy', 'mcq',
 'Find the odd one out: Rose, Lily, Lotus, Mango.',
 '[{"text":"Rose","isCorrect":false},{"text":"Lily","isCorrect":false},{"text":"Lotus","isCorrect":false},{"text":"Mango","isCorrect":true}]'::jsonb,
 null, 'Rose, Lily, and Lotus are all flowers, while Mango is a fruit, making it the odd one out.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Analogy and Classification', 'easy', 'mcq',
 'Complete the analogy: Pen is to Write as Scissors is to:',
 '[{"text":"Cut","isCorrect":true},{"text":"Sharpen","isCorrect":false},{"text":"Paper","isCorrect":false},{"text":"Draw","isCorrect":false}]'::jsonb,
 null, 'Just as a pen''s function is to write, a pair of scissors'' function is to cut.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Analogy and Classification', 'medium', 'mcq',
 'Find the odd one out: Circle, Square, Triangle, Sphere.',
 '[{"text":"Circle","isCorrect":false},{"text":"Square","isCorrect":false},{"text":"Triangle","isCorrect":false},{"text":"Sphere","isCorrect":true}]'::jsonb,
 null, 'Circle, Square, and Triangle are all flat (2D) shapes, while a Sphere is a solid (3D) shape, making it the odd one out.'),

-- Reasoning Ability and Problem Solving: Series and Coding-Decoding
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 1, 4, 9, 16, ?',
 '[{"text":"20","isCorrect":false},{"text":"25","isCorrect":true},{"text":"24","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'The series consists of perfect squares: 1^2, 2^2, 3^2, 4^2, so the next term is 5^2=25.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 2, 4, 6, 8, ?',
 '[{"text":"9","isCorrect":false},{"text":"10","isCorrect":true},{"text":"11","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'This is a simple series of even numbers, increasing by 2 each time, so the next term after 8 is 10.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Series and Coding-Decoding', 'medium', 'mcq',
 'In a certain code, "DOG" is written as "EPH". How is "CAT" written in the same code?',
 '[{"text":"DBU","isCorrect":true},{"text":"DBV","isCorrect":false},{"text":"CBU","isCorrect":false},{"text":"DBT","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one position in the alphabet (D to E, O to P, G to H); applying the same shift to C-A-T gives D-B-U.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the missing number in the series: 5, 10, 15, ?, 25.',
 '[{"text":"18","isCorrect":false},{"text":"20","isCorrect":true},{"text":"22","isCorrect":false},{"text":"19","isCorrect":false}]'::jsonb,
 null, 'This series increases by 5 each time: 5,10,15,20,25 -- so the missing number is 20.'),

-- Reasoning Ability and Problem Solving: Blood Relations and Direction Sense
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A is the mother of B. B is the father of C. What is A''s relationship to C?',
 '[{"text":"Aunt","isCorrect":false},{"text":"Grandmother","isCorrect":true},{"text":"Sister","isCorrect":false},{"text":"Mother","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s mother and B is C''s father, A is C''s paternal grandmother.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a boy, a woman says, "He is the son of my only daughter." Who is the woman to the boy?',
 '[{"text":"Mother","isCorrect":false},{"text":"Grandmother","isCorrect":true},{"text":"Aunt","isCorrect":false},{"text":"Sister","isCorrect":false}]'::jsonb,
 null, 'Since the boy is the son of the woman''s daughter, the woman is the boy''s grandmother.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A man walks 3 km north, then 4 km east. How far is he from his starting point?',
 '[{"text":"5 km","isCorrect":true},{"text":"7 km","isCorrect":false},{"text":"4 km","isCorrect":false},{"text":"1 km","isCorrect":false}]'::jsonb,
 null, 'Using the Pythagorean theorem, the direct distance is sqrt(3^2+4^2) = sqrt(9+16) = sqrt(25) = 5 km.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'If you are facing north and turn 90 degrees clockwise, which direction are you now facing?',
 '[{"text":"West","isCorrect":false},{"text":"East","isCorrect":true},{"text":"South","isCorrect":false},{"text":"North","isCorrect":false}]'::jsonb,
 null, 'Turning 90 degrees clockwise from north takes you to face east.'),

-- Reasoning Ability and Problem Solving: Non-Verbal Reasoning
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A cube is painted red on all its faces and cut into 27 equal smaller cubes. How many smaller cubes have exactly two faces painted?',
 '[{"text":"8","isCorrect":false},{"text":"12","isCorrect":true},{"text":"6","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'In a 3x3x3 cube, each of the 12 edges has exactly one non-corner cube with two painted faces, giving 12 such cubes.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'A cube is painted red on all faces and cut into 8 equal smaller cubes (a 2x2x2 arrangement). How many smaller cubes have three faces painted?',
 '[{"text":"4","isCorrect":false},{"text":"8","isCorrect":true},{"text":"6","isCorrect":false},{"text":"2","isCorrect":false}]'::jsonb,
 null, 'In a 2x2x2 cube, every one of the 8 smaller cubes is a corner cube, so all 8 have exactly three painted faces.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'A sheet of paper is folded once in half, and a hole is punched through the folded layers. How many holes will appear when the paper is unfolded?',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"4","isCorrect":false},{"text":"3","isCorrect":false}]'::jsonb,
 null, 'Folding once creates 2 layers, so punching through both layers produces 2 holes when the paper is unfolded.'),
('SSC-MTS', 'Reasoning Ability and Problem Solving', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A cube painted on all outer faces is cut into 27 equal smaller cubes. How many of the smaller cubes have no face painted at all?',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"2","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'Only the single cube at the very center of the 3x3x3 arrangement, fully surrounded, has no painted face.'),

-- General Awareness: Indian History and Culture
('SSC-MTS', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who is known as the "Father of the Nation" in India?',
 '[{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Mahatma Gandhi","isCorrect":true},{"text":"Sardar Patel","isCorrect":false},{"text":"Subhas Chandra Bose","isCorrect":false}]'::jsonb,
 null, 'Mahatma Gandhi is popularly known as the "Father of the Nation" in India.'),
('SSC-MTS', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'The Battle of Plassey was fought in the year:',
 '[{"text":"1757","isCorrect":true},{"text":"1857","isCorrect":false},{"text":"1707","isCorrect":false},{"text":"1764","isCorrect":false}]'::jsonb,
 null, 'The Battle of Plassey, a decisive victory for the British East India Company over the Nawab of Bengal, was fought in 1757.'),
('SSC-MTS', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Which classical Indian dance form originated in Odisha?',
 '[{"text":"Kathak","isCorrect":false},{"text":"Odissi","isCorrect":true},{"text":"Kathakali","isCorrect":false},{"text":"Manipuri","isCorrect":false}]'::jsonb,
 null, 'Odissi is a classical dance form that originated in the state of Odisha.'),
('SSC-MTS', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who was the first President of independent India?',
 '[{"text":"Dr. Rajendra Prasad","isCorrect":true},{"text":"Dr. S. Radhakrishnan","isCorrect":false},{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Zakir Husain","isCorrect":false}]'::jsonb,
 null, 'Dr. Rajendra Prasad served as the first President of independent India, from 1950 to 1962.'),

-- General Awareness: Indian Polity and Geography
('SSC-MTS', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'The national emblem of India is adopted from the:',
 '[{"text":"Lion Capital of Ashoka at Sarnath","isCorrect":true},{"text":"Red Fort inscriptions","isCorrect":false},{"text":"Ajanta cave paintings","isCorrect":false},{"text":"Konark Sun Temple","isCorrect":false}]'::jsonb,
 null, 'India''s national emblem is adapted from the Lion Capital of Ashoka, originally erected at Sarnath.'),
('SSC-MTS', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'The largest state in India by area is:',
 '[{"text":"Madhya Pradesh","isCorrect":false},{"text":"Rajasthan","isCorrect":true},{"text":"Maharashtra","isCorrect":false},{"text":"Uttar Pradesh","isCorrect":false}]'::jsonb,
 null, 'Rajasthan is the largest Indian state by geographical area.'),
('SSC-MTS', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'How many Fundamental Duties are listed in the Indian Constitution?',
 '[{"text":"6","isCorrect":false},{"text":"11","isCorrect":true},{"text":"10","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'The Indian Constitution lists 11 Fundamental Duties for citizens, under Article 51A.'),
('SSC-MTS', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'The Indian Parliament consists of the President, the Lok Sabha, and the:',
 '[{"text":"Rajya Sabha","isCorrect":true},{"text":"Vidhan Sabha","isCorrect":false},{"text":"Supreme Court","isCorrect":false},{"text":"Election Commission","isCorrect":false}]'::jsonb,
 null, 'The Indian Parliament comprises the President, the Lok Sabha (House of the People), and the Rajya Sabha (Council of States).'),

-- General Awareness: Indian Economy and General Science
('SSC-MTS', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'The currency of India is the:',
 '[{"text":"Indian Rupee","isCorrect":true},{"text":"Indian Dollar","isCorrect":false},{"text":"Indian Dinar","isCorrect":false},{"text":"Indian Pound","isCorrect":false}]'::jsonb,
 null, 'The official currency of India is the Indian Rupee (INR).'),
('SSC-MTS', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'The SI unit of electric power is the:',
 '[{"text":"Volt","isCorrect":false},{"text":"Watt","isCorrect":true},{"text":"Ampere","isCorrect":false},{"text":"Ohm","isCorrect":false}]'::jsonb,
 null, 'Electric power is measured in watts (W).'),
('SSC-MTS', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'Which organ of the human body is primarily responsible for pumping blood?',
 '[{"text":"Lungs","isCorrect":false},{"text":"Heart","isCorrect":true},{"text":"Kidney","isCorrect":false},{"text":"Liver","isCorrect":false}]'::jsonb,
 null, 'The heart pumps blood throughout the body via the circulatory system.'),
('SSC-MTS', 'General Awareness', 'Indian Economy and General Science', 'easy', 'mcq',
 'The process by which green plants prepare their own food is called:',
 '[{"text":"Respiration","isCorrect":false},{"text":"Photosynthesis","isCorrect":true},{"text":"Transpiration","isCorrect":false},{"text":"Digestion","isCorrect":false}]'::jsonb,
 null, 'Photosynthesis is the process by which green plants use sunlight, water, and carbon dioxide to produce glucose and oxygen.'),

-- General Awareness: Current Affairs and Static GK
('SSC-MTS', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'The national bird of India is the:',
 '[{"text":"Sparrow","isCorrect":false},{"text":"Peacock","isCorrect":true},{"text":"Parrot","isCorrect":false},{"text":"Eagle","isCorrect":false}]'::jsonb,
 null, 'The peacock is the national bird of India.'),
('SSC-MTS', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'The national animal of India is the:',
 '[{"text":"Lion","isCorrect":false},{"text":"Tiger","isCorrect":true},{"text":"Elephant","isCorrect":false},{"text":"Leopard","isCorrect":false}]'::jsonb,
 null, 'The Bengal Tiger is the national animal of India.'),
('SSC-MTS', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'The headquarters of the United Nations is located in:',
 '[{"text":"Geneva","isCorrect":false},{"text":"New York","isCorrect":true},{"text":"Vienna","isCorrect":false},{"text":"The Hague","isCorrect":false}]'::jsonb,
 null, 'The United Nations headquarters is located in New York City, United States.'),
('SSC-MTS', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'India''s national anthem, "Jana Gana Mana", was composed by:',
 '[{"text":"Bankim Chandra Chattopadhyay","isCorrect":false},{"text":"Rabindranath Tagore","isCorrect":true},{"text":"Sarojini Naidu","isCorrect":false},{"text":"Muhammad Iqbal","isCorrect":false}]'::jsonb,
 null, 'India''s national anthem, "Jana Gana Mana", was composed by Nobel laureate Rabindranath Tagore.'),

-- English Language and Comprehension: Grammar and Error Spotting
('SSC-MTS', 'English Language and Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Identify the error in the sentence: "He go to school every day."',
 '[{"text":"''He'' should be ''His''","isCorrect":false},{"text":"''go'' should be ''goes''","isCorrect":true},{"text":"''school'' should be ''schools''","isCorrect":false},{"text":"There is no error","isCorrect":false}]'::jsonb,
 null, 'With the third-person singular subject "He", the verb must take the "-s" form: "goes", not "go".'),
('SSC-MTS', 'English Language and Comprehension', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Choose the grammatically correct sentence.',
 '[{"text":"She have a car.","isCorrect":false},{"text":"She has a car.","isCorrect":true},{"text":"She having a car.","isCorrect":false},{"text":"She has have a car.","isCorrect":false}]'::jsonb,
 null, 'With the singular subject "She", the correct verb form is "has", not "have".'),
('SSC-MTS', 'English Language and Comprehension', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Choose the grammatically correct sentence.',
 '[{"text":"I are going to market.","isCorrect":false},{"text":"I am going to market.","isCorrect":true},{"text":"I is going to market.","isCorrect":false},{"text":"I be going to market.","isCorrect":false}]'::jsonb,
 null, 'With the subject "I", the correct form of the verb "to be" in present continuous is "am": "I am going".'),
('SSC-MTS', 'English Language and Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Choose the correct form to complete: "They ___ playing football yesterday."',
 '[{"text":"is","isCorrect":false},{"text":"were","isCorrect":true},{"text":"are","isCorrect":false},{"text":"will be","isCorrect":false}]'::jsonb,
 null, 'Since "yesterday" indicates the past, and the subject "They" is plural, the correct past tense form is "were".'),

-- English Language and Comprehension: Vocabulary (Synonyms, Antonyms, Spelling)
('SSC-MTS', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the word closest in meaning to "Happy".',
 '[{"text":"Joyful","isCorrect":true},{"text":"Sad","isCorrect":false},{"text":"Angry","isCorrect":false},{"text":"Tired","isCorrect":false}]'::jsonb,
 null, '"Joyful" is a close synonym of "Happy", both describing a state of pleasure or contentment.'),
('SSC-MTS', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the antonym of "Brave".',
 '[{"text":"Bold","isCorrect":false},{"text":"Cowardly","isCorrect":true},{"text":"Fearless","isCorrect":false},{"text":"Courageous","isCorrect":false}]'::jsonb,
 null, '"Brave" means showing courage; its antonym is "cowardly", meaning lacking courage.'),
('SSC-MTS', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Beutiful","isCorrect":false},{"text":"Beautiful","isCorrect":true},{"text":"Beautifull","isCorrect":false},{"text":"Beatiful","isCorrect":false}]'::jsonb,
 null, '"Beautiful" is the correct spelling.'),
('SSC-MTS', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the word closest in meaning to "Big".',
 '[{"text":"Large","isCorrect":true},{"text":"Small","isCorrect":false},{"text":"Tiny","isCorrect":false},{"text":"Short","isCorrect":false}]'::jsonb,
 null, '"Large" is a close synonym of "Big", both describing considerable size.'),

-- English Language and Comprehension: Fill in the Blanks and Cloze Test
('SSC-MTS', 'English Language and Comprehension', 'Fill in the Blanks and Cloze Test', 'easy', 'mcq',
 'Fill in the blank: "I ___ to school every day."',
 '[{"text":"go","isCorrect":true},{"text":"goes","isCorrect":false},{"text":"going","isCorrect":false},{"text":"gone","isCorrect":false}]'::jsonb,
 null, 'With the subject "I" in the simple present tense, the base form "go" is correct.'),
('SSC-MTS', 'English Language and Comprehension', 'Fill in the Blanks and Cloze Test', 'easy', 'mcq',
 'Fill in the blank: "She ___ a book right now."',
 '[{"text":"reads","isCorrect":false},{"text":"is reading","isCorrect":true},{"text":"read","isCorrect":false},{"text":"has read","isCorrect":false}]'::jsonb,
 null, '"Right now" indicates an ongoing action, requiring the present continuous tense: "is reading".'),
('SSC-MTS', 'English Language and Comprehension', 'Fill in the Blanks and Cloze Test', 'medium', 'mcq',
 'Fill in the blank: "He ___ his homework already."',
 '[{"text":"finishes","isCorrect":false},{"text":"has finished","isCorrect":true},{"text":"finishing","isCorrect":false},{"text":"finish","isCorrect":false}]'::jsonb,
 null, '"Already" typically signals the present perfect tense, so "has finished" is correct.'),
('SSC-MTS', 'English Language and Comprehension', 'Fill in the Blanks and Cloze Test', 'easy', 'mcq',
 'Fill in the blank: "They ___ to the market yesterday."',
 '[{"text":"go","isCorrect":false},{"text":"went","isCorrect":true},{"text":"goes","isCorrect":false},{"text":"going","isCorrect":false}]'::jsonb,
 null, '"Yesterday" indicates the simple past tense, so "went" (the past tense of "go") is correct.'),

-- English Language and Comprehension: Reading Comprehension
('SSC-MTS', 'English Language and Comprehension', 'Reading Comprehension', 'easy', 'mcq',
 'Read the passage: "Water is essential for all forms of life. Without water, no living organism can survive for long." According to the passage, water is:',
 '[{"text":"Only needed by plants","isCorrect":false},{"text":"Essential for the survival of all living organisms","isCorrect":true},{"text":"Not important for survival","isCorrect":false},{"text":"Only useful for drinking","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states water is "essential for all forms of life" and needed for any living organism to survive.'),
('SSC-MTS', 'English Language and Comprehension', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Exercise keeps the body fit and the mind sharp. Regular physical activity reduces the risk of many diseases." According to the passage, regular exercise:',
 '[{"text":"Has no effect on disease risk","isCorrect":false},{"text":"Reduces the risk of many diseases while keeping body and mind healthy","isCorrect":true},{"text":"Only benefits the mind, not the body","isCorrect":false},{"text":"Increases the risk of injury only","isCorrect":false}]'::jsonb,
 null, 'The passage states exercise "keeps the body fit and the mind sharp" and "reduces the risk of many diseases".'),
('SSC-MTS', 'English Language and Comprehension', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Trees provide oxygen, shelter for animals, and help prevent soil erosion." Which of the following is NOT mentioned as a benefit of trees in this passage?',
 '[{"text":"Providing oxygen","isCorrect":false},{"text":"Providing shelter for animals","isCorrect":false},{"text":"Preventing soil erosion","isCorrect":false},{"text":"Providing medicine","isCorrect":true}]'::jsonb,
 null, 'The passage mentions oxygen, shelter for animals, and preventing soil erosion, but does not mention trees providing medicine.'),
('SSC-MTS', 'English Language and Comprehension', 'Reading Comprehension', 'easy', 'mcq',
 'Read the passage: "Reading books improves vocabulary, enhances knowledge, and develops imagination." According to the passage, reading books helps in:',
 '[{"text":"Improving physical fitness only","isCorrect":false},{"text":"Improving vocabulary, enhancing knowledge, and developing imagination","isCorrect":true},{"text":"Reducing the need for education","isCorrect":false},{"text":"Only entertainment, with no other benefit","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly lists improved vocabulary, enhanced knowledge, and developed imagination as benefits of reading books.');
