-- supabase/sql/exam_question_bank_mht_cet_set1.sql
--
-- First curated question-bank batch for 'MHT-CET' (see exam_patterns_mht_cet.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Like NEET/BITSAT (and unlike the JEE sets), MHT-CET's real format is 100% single-best-response
-- MCQ (4 options, exactly one correct) -- no multi-correct, numerical, or descriptive format in
-- the actual exam. 16 chapters (5 Physics, 5 Chemistry, 6 Mathematics) each get 4 classic,
-- NCERT/Maharashtra-board-level questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_mht_cet.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('MHT-CET', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The SI unit of angular momentum is:',
 '[{"text":"kg m/s","isCorrect":false},{"text":"kg m^2/s","isCorrect":true},{"text":"kg m/s^2","isCorrect":false},{"text":"kg m^2/s^2","isCorrect":false}]'::jsonb,
 null, 'Angular momentum L = I*omega (or r x p) has units of kg m^2/s, combining moment of inertia (kg m^2) with angular velocity (1/s).'),
('MHT-CET', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The center of mass of a uniform circular ring lies:',
 '[{"text":"On the ring itself","isCorrect":false},{"text":"At the geometric center of the ring","isCorrect":true},{"text":"Outside the plane of the ring","isCorrect":false},{"text":"At one-quarter of the radius from the center","isCorrect":false}]'::jsonb,
 null, 'By symmetry, the center of mass of a uniform ring lies at its geometric center, even though no material of the ring exists at that exact point.'),
('MHT-CET', 'Physics', 'Mechanics', 'easy', 'mcq',
 'A rigid body is said to be in mechanical equilibrium when:',
 '[{"text":"Its net force is zero, regardless of net torque","isCorrect":false},{"text":"Both net force and net torque acting on it are zero","isCorrect":true},{"text":"Its net torque is zero, regardless of net force","isCorrect":false},{"text":"It is moving with constant non-zero acceleration","isCorrect":false}]'::jsonb,
 null, 'A rigid body is in complete mechanical equilibrium only when both the net external force and the net external torque on it are zero.'),
('MHT-CET', 'Physics', 'Mechanics', 'easy', 'mcq',
 'As we go higher above the Earth''s surface, the value of acceleration due to gravity g:',
 '[{"text":"Increases","isCorrect":false},{"text":"Decreases","isCorrect":true},{"text":"Remains constant","isCorrect":false},{"text":"First increases, then decreases","isCorrect":false}]'::jsonb,
 null, 'Since g = GM/r^2, as the distance r from the Earth''s center increases with altitude, g decreases.'),

-- Physics: Electrodynamics
('MHT-CET', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The equivalent resistance of two resistors R1 and R2 connected in parallel is:',
 '[{"text":"R1 + R2","isCorrect":false},{"text":"(R1*R2)/(R1+R2)","isCorrect":true},{"text":"(R1+R2)/2","isCorrect":false},{"text":"R1 - R2","isCorrect":false}]'::jsonb,
 null, 'For resistors in parallel, 1/R_eq = 1/R1 + 1/R2, which simplifies to R_eq = (R1*R2)/(R1+R2).'),
('MHT-CET', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The direction of an induced current in a circuit is given by:',
 '[{"text":"Coulomb''s law","isCorrect":false},{"text":"Lenz''s law","isCorrect":true},{"text":"Ohm''s law","isCorrect":false},{"text":"Ampere''s law","isCorrect":false}]'::jsonb,
 null, 'Lenz''s law states that the induced current flows in a direction that opposes the change in magnetic flux that produced it.'),
('MHT-CET', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'Coulomb''s law describes the electrostatic force between:',
 '[{"text":"Two point charges","isCorrect":true},{"text":"A charge and a magnetic field","isCorrect":false},{"text":"Two current-carrying wires","isCorrect":false},{"text":"A charge and a neutral object only","isCorrect":false}]'::jsonb,
 null, 'Coulomb''s law gives the electrostatic force between two point charges as proportional to the product of the charges and inversely proportional to the square of the distance between them.'),
('MHT-CET', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The SI unit of electric field intensity is:',
 '[{"text":"N/C","isCorrect":true},{"text":"C/N","isCorrect":false},{"text":"J/C","isCorrect":false},{"text":"C*m","isCorrect":false}]'::jsonb,
 null, 'Electric field intensity, defined as force per unit charge, has SI unit newton per coulomb (N/C), equivalent to volt per meter (V/m).'),

-- Physics: Optics
('MHT-CET', 'Physics', 'Optics', 'medium', 'mcq',
 'The refractive index of a medium is defined as the ratio of:',
 '[{"text":"Speed of light in vacuum to speed of light in the medium","isCorrect":true},{"text":"Speed of light in the medium to speed of light in vacuum","isCorrect":false},{"text":"Wavelength in vacuum to wavelength in the medium, inverted","isCorrect":false},{"text":"Frequency in vacuum to frequency in the medium","isCorrect":false}]'::jsonb,
 null, 'Refractive index n = c/v, the ratio of the speed of light in vacuum to its speed in the given medium.'),
('MHT-CET', 'Physics', 'Optics', 'medium', 'mcq',
 'A concave (diverging) lens, for any real object placed in front of it, always forms an image that is:',
 '[{"text":"Real, inverted, and magnified","isCorrect":false},{"text":"Virtual, erect, and diminished","isCorrect":true},{"text":"Real, erect, and diminished","isCorrect":false},{"text":"Virtual, inverted, and magnified","isCorrect":false}]'::jsonb,
 null, 'A concave lens always diverges incoming rays, producing a virtual, erect, and diminished image regardless of where the real object is placed.'),
('MHT-CET', 'Physics', 'Optics', 'medium', 'mcq',
 'In a compound microscope, compared to the eyepiece, the objective lens has:',
 '[{"text":"A longer focal length","isCorrect":false},{"text":"A shorter focal length","isCorrect":true},{"text":"The same focal length","isCorrect":false},{"text":"No focal length (it is a plane mirror)","isCorrect":false}]'::jsonb,
 null, 'In a compound microscope, the objective lens has a small focal length to produce a highly magnified real image, which the eyepiece then further magnifies.'),
('MHT-CET', 'Physics', 'Optics', 'easy', 'mcq',
 'The phenomenon responsible for the blue color of the clear daytime sky is:',
 '[{"text":"Rayleigh scattering","isCorrect":true},{"text":"Total internal reflection","isCorrect":false},{"text":"Diffraction","isCorrect":false},{"text":"Polarization only","isCorrect":false}]'::jsonb,
 null, 'Rayleigh scattering of sunlight by air molecules is much stronger for shorter (blue) wavelengths, scattering blue light across the sky and giving it its color.'),

-- Physics: Modern Physics
('MHT-CET', 'Physics', 'Modern Physics', 'medium', 'mcq',
 'The work function of a metal is defined as the:',
 '[{"text":"Total energy of an electron in the metal","isCorrect":false},{"text":"Minimum energy required to eject an electron from the metal surface","isCorrect":true},{"text":"Energy released when an electron is captured by the metal","isCorrect":false},{"text":"Kinetic energy of the fastest photoelectron","isCorrect":false}]'::jsonb,
 null, 'The work function is the minimum energy needed to remove an electron from the surface of a metal, a key quantity in the photoelectric effect.'),
('MHT-CET', 'Physics', 'Modern Physics', 'easy', 'mcq',
 'The half-life of a radioactive substance is the time required for:',
 '[{"text":"All the nuclei to decay","isCorrect":false},{"text":"Half of the initial number of nuclei to decay","isCorrect":true},{"text":"The substance to become non-radioactive","isCorrect":false},{"text":"A quarter of the nuclei to decay","isCorrect":false}]'::jsonb,
 null, 'Half-life is defined as the time taken for exactly half of the initial number of radioactive nuclei in a sample to decay.'),
('MHT-CET', 'Physics', 'Modern Physics', 'medium', 'mcq',
 'Which of the following particles has no charge and no rest mass?',
 '[{"text":"Electron","isCorrect":false},{"text":"Proton","isCorrect":false},{"text":"Photon","isCorrect":true},{"text":"Neutron","isCorrect":false}]'::jsonb,
 null, 'A photon, the quantum of light, is chargeless and massless (has no rest mass), always traveling at the speed of light.'),
('MHT-CET', 'Physics', 'Modern Physics', 'medium', 'mcq',
 'The Bohr model of the atom successfully explained:',
 '[{"text":"The wave nature of all matter","isCorrect":false},{"text":"The hydrogen atom''s discrete spectral lines","isCorrect":true},{"text":"The structure of the atomic nucleus","isCorrect":false},{"text":"The uncertainty principle","isCorrect":false}]'::jsonb,
 null, 'The Bohr model, by postulating quantized electron orbits, successfully explained the discrete spectral lines observed in the hydrogen atom''s emission spectrum.'),

-- Physics: Heat and Thermodynamics
('MHT-CET', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'The zeroth law of thermodynamics establishes the concept of:',
 '[{"text":"Entropy","isCorrect":false},{"text":"Temperature (thermal equilibrium)","isCorrect":true},{"text":"Internal energy","isCorrect":false},{"text":"Enthalpy","isCorrect":false}]'::jsonb,
 null, 'The zeroth law states that if two systems are each in thermal equilibrium with a third, they are in thermal equilibrium with each other -- this underlies the concept of temperature as a measurable, comparable quantity.'),
('MHT-CET', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'The efficiency of a Carnot engine depends only on:',
 '[{"text":"The working substance used","isCorrect":false},{"text":"The temperatures of the source and sink","isCorrect":true},{"text":"The size of the engine","isCorrect":false},{"text":"The pressure of the gas used","isCorrect":false}]'::jsonb,
 null, 'Carnot''s theorem states that the efficiency of a Carnot engine depends solely on the absolute temperatures of the hot source and cold sink, not on the working substance.'),
('MHT-CET', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'In an isothermal process, the temperature of the system:',
 '[{"text":"Increases steadily","isCorrect":false},{"text":"Remains constant","isCorrect":true},{"text":"Decreases steadily","isCorrect":false},{"text":"Fluctuates randomly","isCorrect":false}]'::jsonb,
 null, 'An isothermal process, by definition, occurs at constant temperature throughout.'),
('MHT-CET', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'The SI unit of specific heat capacity is:',
 '[{"text":"J/(kg K)","isCorrect":true},{"text":"J/kg","isCorrect":false},{"text":"J/K","isCorrect":false},{"text":"kg/(J K)","isCorrect":false}]'::jsonb,
 null, 'Specific heat capacity, the heat required to raise the temperature of unit mass by one degree, has SI unit J/(kg K).'),

-- Chemistry: Physical Chemistry
('MHT-CET', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'Avogadro''s number is approximately:',
 '[{"text":"6.022 x 10^23","isCorrect":true},{"text":"3.011 x 10^23","isCorrect":false},{"text":"6.022 x 10^20","isCorrect":false},{"text":"1.602 x 10^19","isCorrect":false}]'::jsonb,
 null, 'Avogadro''s number, 6.022 x 10^23 per mole, is the number of constituent particles (atoms, molecules, ions) in one mole of a substance.'),
('MHT-CET', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The pH scale conventionally ranges from:',
 '[{"text":"0 to 7","isCorrect":false},{"text":"0 to 14","isCorrect":true},{"text":"1 to 10","isCorrect":false},{"text":"-7 to 7","isCorrect":false}]'::jsonb,
 null, 'The pH scale conventionally spans 0 to 14 for aqueous solutions at 25 degrees C, with 7 representing neutrality.'),
('MHT-CET', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'A buffer solution is characterized by its ability to resist a change in:',
 '[{"text":"Volume upon dilution","isCorrect":false},{"text":"pH upon addition of small amounts of acid or base","isCorrect":true},{"text":"Color upon heating","isCorrect":false},{"text":"Temperature upon stirring","isCorrect":false}]'::jsonb,
 null, 'A buffer solution, typically a weak acid/conjugate base (or weak base/conjugate acid) pair, resists significant pH change when small amounts of acid or base are added.'),
('MHT-CET', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The rate of a zero-order reaction is:',
 '[{"text":"Directly proportional to reactant concentration","isCorrect":false},{"text":"Independent of reactant concentration","isCorrect":true},{"text":"Inversely proportional to reactant concentration","isCorrect":false},{"text":"Proportional to the square of concentration","isCorrect":false}]'::jsonb,
 null, 'For a zero-order reaction, rate = k[A]^0 = k, meaning the rate remains constant and independent of the reactant''s concentration.'),

-- Chemistry: Organic Chemistry
('MHT-CET', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Which functional group is present in an ester?',
 '[{"text":"-COOH","isCorrect":false},{"text":"-COO-","isCorrect":true},{"text":"-CHO","isCorrect":false},{"text":"-NH2","isCorrect":false}]'::jsonb,
 null, 'Esters are characterized by the -COO- (carbonyl-oxygen) linkage formed from a carboxylic acid and an alcohol.'),
('MHT-CET', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Which of the following species acts as a nucleophile in organic reactions?',
 '[{"text":"H+","isCorrect":false},{"text":"OH- (hydroxide ion)","isCorrect":true},{"text":"BF3","isCorrect":false},{"text":"AlCl3","isCorrect":false}]'::jsonb,
 null, 'A nucleophile is an electron-rich species that donates an electron pair; the hydroxide ion, with its lone pairs and negative charge, is a classic nucleophile.'),
('MHT-CET', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The general molecular formula of alkanes is:',
 '[{"text":"CnH2n","isCorrect":false},{"text":"CnH2n+2","isCorrect":true},{"text":"CnH2n-2","isCorrect":false},{"text":"CnHn","isCorrect":false}]'::jsonb,
 null, 'Alkanes are saturated hydrocarbons with the general formula CnH2n+2.'),
('MHT-CET', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The reaction converting an alkyl halide into an alkene by removing a hydrogen halide is called:',
 '[{"text":"Dehydrohalogenation","isCorrect":true},{"text":"Halogenation","isCorrect":false},{"text":"Hydrohalogenation","isCorrect":false},{"text":"Hydrolysis","isCorrect":false}]'::jsonb,
 null, 'Dehydrohalogenation is an elimination reaction in which an alkyl halide loses a hydrogen and a halide ion to form an alkene, typically under strong base treatment.'),

-- Chemistry: Inorganic Chemistry
('MHT-CET', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Among naturally abundant elements, which is considered the most electropositive?',
 '[{"text":"Sodium","isCorrect":false},{"text":"Cesium","isCorrect":true},{"text":"Lithium","isCorrect":false},{"text":"Potassium","isCorrect":false}]'::jsonb,
 null, 'Cesium, being at the bottom-left of the practically stable portion of the periodic table, has the lowest ionization energy among common elements and is considered the most electropositive.'),
('MHT-CET', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The oxidation state of chromium in K2Cr2O7 (potassium dichromate) is:',
 '[{"text":"+3","isCorrect":false},{"text":"+4","isCorrect":false},{"text":"+6","isCorrect":true},{"text":"+7","isCorrect":false}]'::jsonb,
 null, 'In K2Cr2O7, K is +1 and O is -2; balancing charges across the formula gives each chromium atom an oxidation state of +6.'),
('MHT-CET', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which of the following is classified as a transition element?',
 '[{"text":"Sodium","isCorrect":false},{"text":"Iron","isCorrect":true},{"text":"Calcium","isCorrect":false},{"text":"Aluminum","isCorrect":false}]'::jsonb,
 null, 'Iron, with a partially filled d-subshell in its common oxidation states, is classified as a transition (d-block) element.'),
('MHT-CET', 'Chemistry', 'Inorganic Chemistry', 'hard', 'mcq',
 'The lanthanide contraction refers to:',
 '[{"text":"The gradual increase in atomic/ionic radii across the lanthanide series","isCorrect":false},{"text":"The gradual decrease in atomic/ionic radii across the lanthanide series","isCorrect":true},{"text":"The sudden loss of f-electrons in lanthanides","isCorrect":false},{"text":"The color change observed across lanthanide salts","isCorrect":false}]'::jsonb,
 null, 'Lanthanide contraction is the steady decrease in atomic and ionic radii across the lanthanide series, caused by poor shielding of nuclear charge by 4f electrons.'),

-- Chemistry: Electrochemistry and Chemical Kinetics
('MHT-CET', 'Chemistry', 'Electrochemistry and Chemical Kinetics', 'medium', 'mcq',
 'In an electrochemical cell, oxidation occurs at the:',
 '[{"text":"Anode","isCorrect":true},{"text":"Cathode","isCorrect":false},{"text":"Salt bridge","isCorrect":false},{"text":"External circuit only","isCorrect":false}]'::jsonb,
 null, 'By convention, oxidation (loss of electrons) always occurs at the anode of an electrochemical cell, whether galvanic or electrolytic.'),
('MHT-CET', 'Chemistry', 'Electrochemistry and Chemical Kinetics', 'medium', 'mcq',
 'The commonly used unit for molar conductivity is:',
 '[{"text":"S cm^2 mol^-1","isCorrect":true},{"text":"S cm^-1","isCorrect":false},{"text":"ohm mol^-1","isCorrect":false},{"text":"S mol","isCorrect":false}]'::jsonb,
 null, 'Molar conductivity, defined as conductivity divided by molar concentration, is conventionally expressed in S cm^2 mol^-1.'),
('MHT-CET', 'Chemistry', 'Electrochemistry and Chemical Kinetics', 'medium', 'mcq',
 'The rate constant of a chemical reaction primarily depends on:',
 '[{"text":"The concentration of reactants","isCorrect":false},{"text":"Temperature (and the presence of a catalyst)","isCorrect":true},{"text":"The volume of the reaction vessel","isCorrect":false},{"text":"The order in which reactants are mixed","isCorrect":false}]'::jsonb,
 null, 'Unlike the rate itself, the rate constant k is independent of reactant concentration -- it depends on temperature and the presence of a catalyst, as captured by the Arrhenius equation.'),
('MHT-CET', 'Chemistry', 'Electrochemistry and Chemical Kinetics', 'medium', 'mcq',
 'According to the Arrhenius equation, the rate constant of a reaction:',
 '[{"text":"Decreases with increasing temperature","isCorrect":false},{"text":"Increases with increasing temperature","isCorrect":true},{"text":"Is independent of temperature","isCorrect":false},{"text":"Increases only if pressure also increases","isCorrect":false}]'::jsonb,
 null, 'The Arrhenius equation k = A*e^(-Ea/RT) shows that the rate constant increases exponentially as temperature increases, since more molecules acquire the activation energy needed to react.'),

-- Chemistry: Solid State and Solutions
('MHT-CET', 'Chemistry', 'Solid State and Solutions', 'medium', 'mcq',
 'The number of atoms per unit cell in a simple cubic lattice is:',
 '[{"text":"1","isCorrect":true},{"text":"2","isCorrect":false},{"text":"4","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A simple cubic unit cell has an atom at each of its 8 corners, each shared among 8 adjacent cells, contributing 8*(1/8) = 1 atom per unit cell.'),
('MHT-CET', 'Chemistry', 'Solid State and Solutions', 'medium', 'mcq',
 'Which colligative property is commonly used to determine the molar mass of a solute via freezing point measurements?',
 '[{"text":"Relative lowering of vapor pressure","isCorrect":false},{"text":"Depression in freezing point","isCorrect":true},{"text":"Elevation in boiling point only","isCorrect":false},{"text":"Osmotic pressure only","isCorrect":false}]'::jsonb,
 null, 'Depression in freezing point (cryoscopy), being easily measurable with good precision, is a common method for determining a solute''s molar mass.'),
('MHT-CET', 'Chemistry', 'Solid State and Solutions', 'medium', 'mcq',
 'Henry''s law relates the solubility of a gas in a liquid to:',
 '[{"text":"The temperature of the liquid alone","isCorrect":false},{"text":"The partial pressure of the gas above the liquid","isCorrect":true},{"text":"The molar mass of the gas alone","isCorrect":false},{"text":"The density of the liquid","isCorrect":false}]'::jsonb,
 null, 'Henry''s law states that the solubility of a gas in a liquid is directly proportional to the partial pressure of that gas above the liquid, at constant temperature.'),
('MHT-CET', 'Chemistry', 'Solid State and Solutions', 'hard', 'mcq',
 'The coordination number of atoms in a face-centered cubic (FCC) lattice is:',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":false},{"text":"12","isCorrect":true},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'In a face-centered cubic (cubic close-packed) lattice, each atom touches 12 nearest neighbors, giving it a coordination number of 12.'),

-- Mathematics: Algebra
('MHT-CET', 'Mathematics', 'Algebra', 'easy', 'mcq',
 'The sum of the first n terms of an arithmetic progression with first term a and common difference d is:',
 '[{"text":"n/2 * [2a + (n-1)d]","isCorrect":true},{"text":"n * [a + (n-1)d]","isCorrect":false},{"text":"n/2 * [a + d]","isCorrect":false},{"text":"a + (n-1)d","isCorrect":false}]'::jsonb,
 null, 'The standard formula for the sum of the first n terms of an AP is S_n = n/2 * [2a + (n-1)d].'),
('MHT-CET', 'Mathematics', 'Algebra', 'medium', 'mcq',
 'If A is a square matrix such that A^2 = A, then A is called:',
 '[{"text":"An orthogonal matrix","isCorrect":false},{"text":"An idempotent matrix","isCorrect":true},{"text":"A nilpotent matrix","isCorrect":false},{"text":"A skew-symmetric matrix","isCorrect":false}]'::jsonb,
 null, 'A square matrix A satisfying A^2 = A is called an idempotent matrix.'),
('MHT-CET', 'Mathematics', 'Algebra', 'easy', 'mcq',
 'In the binomial expansion of (a+b)^n, the total number of terms is:',
 '[{"text":"n","isCorrect":false},{"text":"n+1","isCorrect":true},{"text":"n-1","isCorrect":false},{"text":"2n","isCorrect":false}]'::jsonb,
 null, 'The binomial expansion of (a+b)^n has n+1 terms, corresponding to powers of b ranging from 0 to n.'),
('MHT-CET', 'Mathematics', 'Algebra', 'easy', 'mcq',
 'The determinant of the 2x2 matrix [[a,b],[c,d]] is:',
 '[{"text":"ad - bc","isCorrect":true},{"text":"ac - bd","isCorrect":false},{"text":"ad + bc","isCorrect":false},{"text":"ab - cd","isCorrect":false}]'::jsonb,
 null, 'For a 2x2 matrix [[a,b],[c,d]], the determinant is computed as ad - bc.'),

-- Mathematics: Differentiation and Applications
('MHT-CET', 'Mathematics', 'Differentiation and Applications', 'easy', 'mcq',
 'The derivative of e^x with respect to x is:',
 '[{"text":"e^x","isCorrect":true},{"text":"x*e^(x-1)","isCorrect":false},{"text":"e","isCorrect":false},{"text":"1/e^x","isCorrect":false}]'::jsonb,
 null, 'The exponential function e^x is its own derivative: d/dx[e^x] = e^x.'),
('MHT-CET', 'Mathematics', 'Differentiation and Applications', 'medium', 'mcq',
 'If a differentiable function f has a local maximum at x=a, then f''(a) is:',
 '[{"text":"Positive","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Negative","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'At a local maximum (or minimum) of a differentiable function, the tangent is horizontal, so the derivative equals zero there.'),
('MHT-CET', 'Mathematics', 'Differentiation and Applications', 'easy', 'mcq',
 'The derivative of ln(x) with respect to x is:',
 '[{"text":"1/x","isCorrect":true},{"text":"x","isCorrect":false},{"text":"ln(x)","isCorrect":false},{"text":"1/x^2","isCorrect":false}]'::jsonb,
 null, 'By standard differentiation rules, d/dx[ln(x)] = 1/x for x > 0.'),
('MHT-CET', 'Mathematics', 'Differentiation and Applications', 'medium', 'mcq',
 'L''Hopital''s rule is applicable when evaluating a limit that results in which indeterminate form?',
 '[{"text":"0/0 or infinity/infinity","isCorrect":true},{"text":"1/0 only","isCorrect":false},{"text":"0*1","isCorrect":false},{"text":"Any finite value divided by zero","isCorrect":false}]'::jsonb,
 null, 'L''Hopital''s rule applies specifically to limits producing the indeterminate forms 0/0 or infinity/infinity, allowing the limit to be evaluated via the ratio of derivatives.'),

-- Mathematics: Integration and Differential Equations
('MHT-CET', 'Mathematics', 'Integration and Differential Equations', 'easy', 'mcq',
 'The integral of e^x dx is:',
 '[{"text":"e^x + C","isCorrect":true},{"text":"x*e^x + C","isCorrect":false},{"text":"e^(x+1)/(x+1) + C","isCorrect":false},{"text":"ln(x) + C","isCorrect":false}]'::jsonb,
 null, 'Since e^x is its own derivative, its antiderivative is also e^x, plus a constant of integration.'),
('MHT-CET', 'Mathematics', 'Integration and Differential Equations', 'medium', 'mcq',
 'The order of a differential equation is determined by:',
 '[{"text":"The number of arbitrary constants in its general solution","isCorrect":false},{"text":"The highest-order derivative present in the equation","isCorrect":true},{"text":"The degree of the dependent variable","isCorrect":false},{"text":"The number of independent variables","isCorrect":false}]'::jsonb,
 null, 'The order of a differential equation is defined as the order of the highest derivative appearing in it.'),
('MHT-CET', 'Mathematics', 'Integration and Differential Equations', 'easy', 'mcq',
 'The integral of cos(x) dx is:',
 '[{"text":"sin(x) + C","isCorrect":true},{"text":"-sin(x) + C","isCorrect":false},{"text":"-cos(x) + C","isCorrect":false},{"text":"tan(x) + C","isCorrect":false}]'::jsonb,
 null, 'The antiderivative of cos(x) is sin(x), plus a constant of integration.'),
('MHT-CET', 'Mathematics', 'Integration and Differential Equations', 'medium', 'mcq',
 'A differential equation of the form dy/dx = f(x)*g(y) is classified as:',
 '[{"text":"Linear","isCorrect":false},{"text":"Variable separable","isCorrect":true},{"text":"Homogeneous only","isCorrect":false},{"text":"Exact","isCorrect":false}]'::jsonb,
 null, 'When dy/dx can be written as a product of a function of x alone and a function of y alone, the variables can be separated and integrated independently -- hence "variable separable".'),

-- Mathematics: Coordinate Geometry
('MHT-CET', 'Mathematics', 'Coordinate Geometry', 'medium', 'mcq',
 'The equation representing a pair of straight lines passing through the origin has the general form:',
 '[{"text":"ax^2 + 2hxy + by^2 = 0","isCorrect":true},{"text":"ax + by + c = 0","isCorrect":false},{"text":"x^2 + y^2 = r^2","isCorrect":false},{"text":"ax^2 + by^2 = 1","isCorrect":false}]'::jsonb,
 null, 'A homogeneous second-degree equation in x and y, ax^2 + 2hxy + by^2 = 0, represents a pair of straight lines passing through the origin.'),
('MHT-CET', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The eccentricity of a parabola is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"Between 0 and 1","isCorrect":false},{"text":"Greater than 1","isCorrect":false}]'::jsonb,
 null, 'By definition, a parabola has eccentricity exactly equal to 1, distinguishing it from ellipses (e<1) and hyperbolas (e>1).'),
('MHT-CET', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The general equation of a circle in a plane is:',
 '[{"text":"x^2 + y^2 + 2gx + 2fy + c = 0","isCorrect":true},{"text":"ax^2 + by^2 = 1","isCorrect":false},{"text":"y = mx + c","isCorrect":false},{"text":"x^2 - y^2 = a^2","isCorrect":false}]'::jsonb,
 null, 'The general second-degree equation for a circle is x^2 + y^2 + 2gx + 2fy + c = 0, with center (-g,-f) and radius sqrt(g^2+f^2-c).'),
('MHT-CET', 'Mathematics', 'Coordinate Geometry', 'medium', 'mcq',
 'The angle between the asymptotes of a rectangular hyperbola is:',
 '[{"text":"45 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":true},{"text":"60 degrees","isCorrect":false},{"text":"180 degrees","isCorrect":false}]'::jsonb,
 null, 'A rectangular hyperbola has perpendicular asymptotes, so the angle between them is 90 degrees.'),

-- Mathematics: Trigonometric Functions
('MHT-CET', 'Mathematics', 'Trigonometric Functions', 'medium', 'mcq',
 'The principal value branch of sin^-1(x) is:',
 '[{"text":"[0, pi]","isCorrect":false},{"text":"[-pi/2, pi/2]","isCorrect":true},{"text":"(-pi, pi)","isCorrect":false},{"text":"[0, 2*pi]","isCorrect":false}]'::jsonb,
 null, 'By convention, the principal value branch of sin^-1(x) is restricted to [-pi/2, pi/2] to make the inverse function well-defined.'),
('MHT-CET', 'Mathematics', 'Trigonometric Functions', 'easy', 'mcq',
 'The value of cos(60 degrees) is:',
 '[{"text":"1","isCorrect":false},{"text":"1/2","isCorrect":true},{"text":"sqrt(3)/2","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'cos(60 degrees) is a standard trigonometric value equal to 1/2.'),
('MHT-CET', 'Mathematics', 'Trigonometric Functions', 'medium', 'mcq',
 'The period of the function tan(x) is:',
 '[{"text":"pi","isCorrect":true},{"text":"2*pi","isCorrect":false},{"text":"pi/2","isCorrect":false},{"text":"4*pi","isCorrect":false}]'::jsonb,
 null, 'Unlike sin(x) and cos(x), which have period 2*pi, tan(x) repeats every pi radians.'),
('MHT-CET', 'Mathematics', 'Trigonometric Functions', 'easy', 'mcq',
 'The expansion of sin(A+B) is:',
 '[{"text":"sinA*cosB + cosA*sinB","isCorrect":true},{"text":"sinA*sinB + cosA*cosB","isCorrect":false},{"text":"sinA*cosB - cosA*sinB","isCorrect":false},{"text":"cosA*cosB - sinA*sinB","isCorrect":false}]'::jsonb,
 null, 'The angle addition formula for sine states sin(A+B) = sinA*cosB + cosA*sinB.'),

-- Mathematics: Vectors and 3D Geometry
('MHT-CET', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'mcq',
 'Two non-zero vectors are collinear if their cross product is:',
 '[{"text":"Equal to their dot product","isCorrect":false},{"text":"The zero vector","isCorrect":true},{"text":"Always positive","isCorrect":false},{"text":"Equal to 1","isCorrect":false}]'::jsonb,
 null, 'Two non-zero vectors are collinear (parallel) precisely when the angle between them is 0 or 180 degrees, making their cross product the zero vector.'),
('MHT-CET', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'mcq',
 'The direction ratios of the line joining points (x1,y1,z1) and (x2,y2,z2) are:',
 '[{"text":"(x2-x1, y2-y1, z2-z1)","isCorrect":true},{"text":"(x1+x2, y1+y2, z1+z2)","isCorrect":false},{"text":"(x1*x2, y1*y2, z1*z2)","isCorrect":false},{"text":"(x1/x2, y1/y2, z1/z2)","isCorrect":false}]'::jsonb,
 null, 'The direction ratios of a line joining two points are simply the differences of their respective coordinates: (x2-x1, y2-y1, z2-z1).'),
('MHT-CET', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'mcq',
 'The scalar triple product [a b c] of three vectors represents:',
 '[{"text":"The area of the triangle formed by the vectors","isCorrect":false},{"text":"The volume of the parallelepiped formed by the vectors","isCorrect":true},{"text":"The sum of the magnitudes of the vectors","isCorrect":false},{"text":"The angle between the vectors","isCorrect":false}]'::jsonb,
 null, 'The scalar triple product a.(b x c) gives the (signed) volume of the parallelepiped formed by the three vectors as coterminous edges.'),
('MHT-CET', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'mcq',
 'If two lines in space are parallel, then their direction ratios are:',
 '[{"text":"Equal to zero","isCorrect":false},{"text":"Proportional","isCorrect":true},{"text":"Perpendicular","isCorrect":false},{"text":"Unrelated","isCorrect":false}]'::jsonb,
 null, 'Two lines are parallel exactly when their direction ratios are proportional to each other (i.e. one is a scalar multiple of the other).');
