-- supabase/sql/exam_question_bank_rrb_alp_set1.sql
--
-- First curated question-bank batch for 'RRB ALP' (see exam_patterns_rrb_alp.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Non-Verbal Reasoning again uses text-describable puzzles in place of
-- figure-based questions, which need images this schema can't provide. 16 chapters (4 per section
-- x 4 sections) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_rrb_alp.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Mathematics: Number System and Simplification
('RRB ALP', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 60 - 24 / 6 + 5',
 '[{"text":"61","isCorrect":true},{"text":"55","isCorrect":false},{"text":"65","isCorrect":false},{"text":"50","isCorrect":false}]'::jsonb,
 null, 'Following order of operations: 24/6 = 4, then 60 - 4 + 5 = 61.'),
('RRB ALP', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following is a prime number?',
 '[{"text":"21","isCorrect":false},{"text":"27","isCorrect":false},{"text":"29","isCorrect":true},{"text":"33","isCorrect":false}]'::jsonb,
 null, '29 has no divisors other than 1 and itself, while 21, 27 and 33 are all divisible by 3.'),
('RRB ALP', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the value of 15^2 - 10^2.',
 '[{"text":"125","isCorrect":true},{"text":"225","isCorrect":false},{"text":"100","isCorrect":false},{"text":"325","isCorrect":false}]'::jsonb,
 null, '15^2 = 225 and 10^2 = 100, so 225 - 100 = 125.'),
('RRB ALP', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the HCF of 24 and 36.',
 '[{"text":"6","isCorrect":false},{"text":"12","isCorrect":true},{"text":"8","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'The highest common factor of 24 and 36 is 12.'),

-- Mathematics: Percentage and Ratio
('RRB ALP', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 '60% of 150 is:',
 '[{"text":"80","isCorrect":false},{"text":"90","isCorrect":true},{"text":"100","isCorrect":false},{"text":"70","isCorrect":false}]'::jsonb,
 null, '60% of 150 = (60/100) x 150 = 90.'),
('RRB ALP', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 'Express the ratio 4:5 as a percentage.',
 '[{"text":"45%","isCorrect":false},{"text":"80%","isCorrect":true},{"text":"54%","isCorrect":false},{"text":"85%","isCorrect":false}]'::jsonb,
 null, '4:5 as a fraction is 4/5, which equals 80%.'),
('RRB ALP', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'If 20% of a number is 60, find the number.',
 '[{"text":"240","isCorrect":false},{"text":"300","isCorrect":true},{"text":"320","isCorrect":false},{"text":"280","isCorrect":false}]'::jsonb,
 null, 'If 20% of x = 60, then x = 60 / 0.20 = 300.'),
('RRB ALP', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'Rs. 720 is divided in the ratio 3:5. Find the larger share.',
 '[{"text":"Rs. 270","isCorrect":false},{"text":"Rs. 450","isCorrect":true},{"text":"Rs. 400","isCorrect":false},{"text":"Rs. 500","isCorrect":false}]'::jsonb,
 null, 'Total parts = 3+5 = 8. Larger share = (5/8) x 720 = Rs. 450.'),

-- Mathematics: Profit Loss and Interest
('RRB ALP', 'Mathematics', 'Profit Loss and Interest', 'easy', 'mcq',
 'A man buys an item for Rs. 300 and sells it for Rs. 360. Find his profit.',
 '[{"text":"Rs. 40","isCorrect":false},{"text":"Rs. 60","isCorrect":true},{"text":"Rs. 50","isCorrect":false},{"text":"Rs. 70","isCorrect":false}]'::jsonb,
 null, 'Profit = Selling Price - Cost Price = 360 - 300 = Rs. 60.'),
('RRB ALP', 'Mathematics', 'Profit Loss and Interest', 'easy', 'mcq',
 'The cost price of an item is Rs. 250 and the selling price is Rs. 225. Find the loss percentage.',
 '[{"text":"5%","isCorrect":false},{"text":"10%","isCorrect":true},{"text":"15%","isCorrect":false},{"text":"20%","isCorrect":false}]'::jsonb,
 null, 'Loss = 250 - 225 = 25. Loss percentage = (25/250) x 100 = 10%.'),
('RRB ALP', 'Mathematics', 'Profit Loss and Interest', 'medium', 'mcq',
 'Find the compound interest on Rs. 2000 at 10% per annum for 2 years.',
 '[{"text":"Rs. 400","isCorrect":false},{"text":"Rs. 420","isCorrect":true},{"text":"Rs. 440","isCorrect":false},{"text":"Rs. 200","isCorrect":false}]'::jsonb,
 null, 'Amount = 2000 x (1.1)^2 = 2420. Compound Interest = 2420 - 2000 = Rs. 420.'),
('RRB ALP', 'Mathematics', 'Profit Loss and Interest', 'medium', 'mcq',
 'Find the simple interest on Rs. 1200 at 6% per annum for 5 years.',
 '[{"text":"Rs. 300","isCorrect":false},{"text":"Rs. 360","isCorrect":true},{"text":"Rs. 400","isCorrect":false},{"text":"Rs. 320","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = (Principal x Rate x Time) / 100 = (1200 x 6 x 5) / 100 = Rs. 360.'),

-- Mathematics: Time Speed Distance and Mensuration
('RRB ALP', 'Mathematics', 'Time Speed Distance and Mensuration', 'easy', 'mcq',
 'A bus travels 240 km in 4 hours. Find its speed.',
 '[{"text":"50 km/h","isCorrect":false},{"text":"60 km/h","isCorrect":true},{"text":"55 km/h","isCorrect":false},{"text":"65 km/h","isCorrect":false}]'::jsonb,
 null, 'Speed = Distance / Time = 240 / 4 = 60 km/h.'),
('RRB ALP', 'Mathematics', 'Time Speed Distance and Mensuration', 'easy', 'mcq',
 'Find the area of a square with side 8 cm.',
 '[{"text":"16 cm^2","isCorrect":false},{"text":"64 cm^2","isCorrect":true},{"text":"32 cm^2","isCorrect":false},{"text":"48 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a square = side x side = 8 x 8 = 64 cm^2.'),
('RRB ALP', 'Mathematics', 'Time Speed Distance and Mensuration', 'medium', 'mcq',
 'A train 150 m long crosses a pole in 15 seconds. Find its speed in m/s.',
 '[{"text":"8 m/s","isCorrect":false},{"text":"10 m/s","isCorrect":true},{"text":"12 m/s","isCorrect":false},{"text":"15 m/s","isCorrect":false}]'::jsonb,
 null, 'Speed = Distance / Time = 150 / 15 = 10 m/s.'),
('RRB ALP', 'Mathematics', 'Time Speed Distance and Mensuration', 'medium', 'mcq',
 'Find the volume of a cube with side 5 cm.',
 '[{"text":"25 cm^3","isCorrect":false},{"text":"100 cm^3","isCorrect":false},{"text":"125 cm^3","isCorrect":true},{"text":"150 cm^3","isCorrect":false}]'::jsonb,
 null, 'Volume of a cube = side^3 = 5^3 = 125 cm^3.'),

-- General Intelligence and Reasoning: Analogies and Classification
('RRB ALP', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Pilot is to Airplane as Driver is to:',
 '[{"text":"Road","isCorrect":false},{"text":"Car","isCorrect":true},{"text":"License","isCorrect":false},{"text":"Fuel","isCorrect":false}]'::jsonb,
 null, 'A pilot operates an airplane, just as a driver operates a car.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Rose","isCorrect":false},{"text":"Marigold","isCorrect":false},{"text":"Sunflower","isCorrect":false},{"text":"Neem","isCorrect":true}]'::jsonb,
 null, 'Rose, Marigold and Sunflower are flowers, while Neem is a tree.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Key is to Lock as Password is to:',
 '[{"text":"Computer","isCorrect":false},{"text":"Account","isCorrect":true},{"text":"Screen","isCorrect":false},{"text":"Login","isCorrect":false}]'::jsonb,
 null, 'A key is used to open a lock, just as a password is used to access an account.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Guitar","isCorrect":false},{"text":"Violin","isCorrect":false},{"text":"Sitar","isCorrect":false},{"text":"Trumpet","isCorrect":true}]'::jsonb,
 null, 'Guitar, Violin and Sitar are string instruments, while a Trumpet is a brass wind instrument.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('RRB ALP', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 6, 12, 18, 24, ?',
 '[{"text":"26","isCorrect":false},{"text":"28","isCorrect":false},{"text":"30","isCorrect":true},{"text":"32","isCorrect":false}]'::jsonb,
 null, 'The series increases by 6 each time, so the next number is 24 + 6 = 30.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'In a certain code, CAT is written as DBU. How is CUP written in that code?',
 '[{"text":"DVQ","isCorrect":true},{"text":"DVP","isCorrect":false},{"text":"DUQ","isCorrect":false},{"text":"EVQ","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: C->D, U->V, P->Q, giving DVQ.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 1, 2, 6, 24, 120, ?',
 '[{"text":"600","isCorrect":false},{"text":"700","isCorrect":false},{"text":"720","isCorrect":true},{"text":"740","isCorrect":false}]'::jsonb,
 null, 'This series follows factorials (1!, 2!, 3!, 4!, 5!...), so the next term is 6! = 720.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If SIGNAL is coded as TJHOBM, how is DRIVER coded in the same language?',
 '[{"text":"ESJWFS","isCorrect":true},{"text":"ESJWFT","isCorrect":false},{"text":"ESJVFS","isCorrect":false},{"text":"FSJWFS","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so DRIVER becomes ESJWFS.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('RRB ALP', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many faces does a square pyramid have?',
 '[{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A square pyramid has 5 faces: 1 square base and 4 triangular side faces.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'If today is Wednesday, what day will it be after 10 days?',
 '[{"text":"Friday","isCorrect":false},{"text":"Saturday","isCorrect":true},{"text":"Sunday","isCorrect":false},{"text":"Thursday","isCorrect":false}]'::jsonb,
 null, '10 days is 1 full week (7 days) plus 3 extra days, so the day advances from Wednesday to Saturday.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'How many total rectangles (of any size) are there in a figure made of a 1x3 row of small squares?',
 '[{"text":"3","isCorrect":false},{"text":"4","isCorrect":false},{"text":"6","isCorrect":true},{"text":"9","isCorrect":false}]'::jsonb,
 null, 'A 1x3 row has 3 single squares, 2 combinations of two adjacent squares, and 1 combination of all three, giving 3+2+1 = 6 rectangles.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'In a queue, a person is 10th from the front and 21st from the back. How many people are in the queue?',
 '[{"text":"30","isCorrect":true},{"text":"31","isCorrect":false},{"text":"29","isCorrect":false},{"text":"32","isCorrect":false}]'::jsonb,
 null, 'Total = (position from front) + (position from back) - 1 = 10 + 21 - 1 = 30.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('RRB ALP', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'A is the sister of B. B is the son of C. How is A related to C?',
 '[{"text":"Daughter","isCorrect":true},{"text":"Niece","isCorrect":false},{"text":"Mother","isCorrect":false},{"text":"Sister","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s sister and B is C''s son, A is also C''s child, i.e. C''s daughter.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A man walks 7 km west, then 24 km north. How far is he from his starting point?',
 '[{"text":"25 km","isCorrect":true},{"text":"31 km","isCorrect":false},{"text":"20 km","isCorrect":false},{"text":"28 km","isCorrect":false}]'::jsonb,
 null, 'By the Pythagorean theorem, the distance is sqrt(7^2 + 24^2) = sqrt(625) = 25 km.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a boy, a man said, "His mother is my wife''s mother''s only daughter," and the man''s wife has no siblings. How is the boy related to the man?',
 '[{"text":"Son","isCorrect":true},{"text":"Nephew","isCorrect":false},{"text":"Brother","isCorrect":false},{"text":"Grandson","isCorrect":false}]'::jsonb,
 null, 'Since the man''s wife has no siblings, "my wife''s mother''s only daughter" refers to the wife herself, so the boy''s mother is the man''s wife -- making the boy his son.'),
('RRB ALP', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A man walks 6 km north, 8 km east, then 6 km south. How far and in which direction is he from his starting point?',
 '[{"text":"8 km East","isCorrect":true},{"text":"8 km West","isCorrect":false},{"text":"6 km North","isCorrect":false},{"text":"14 km","isCorrect":false}]'::jsonb,
 null, 'The 6 km north and 6 km south movements cancel out, leaving only the 8 km eastward movement.'),

-- General Science: Physics Basics
('RRB ALP', 'General Science', 'Physics Basics', 'easy', 'mcq',
 'What is the SI unit of mass?',
 '[{"text":"Newton","isCorrect":false},{"text":"Kilogram","isCorrect":true},{"text":"Meter","isCorrect":false},{"text":"Second","isCorrect":false}]'::jsonb,
 null, 'The SI unit of mass is the kilogram.'),
('RRB ALP', 'General Science', 'Physics Basics', 'easy', 'mcq',
 'Which simple machine is used in a see-saw?',
 '[{"text":"Pulley","isCorrect":false},{"text":"Lever","isCorrect":true},{"text":"Wheel","isCorrect":false},{"text":"Inclined plane","isCorrect":false}]'::jsonb,
 null, 'A see-saw works on the principle of a lever, pivoting around a central fulcrum.'),
('RRB ALP', 'General Science', 'Physics Basics', 'medium', 'mcq',
 'What is the SI unit of energy?',
 '[{"text":"Joule","isCorrect":true},{"text":"Watt","isCorrect":false},{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'The SI unit of energy is the Joule.'),
('RRB ALP', 'General Science', 'Physics Basics', 'medium', 'mcq',
 'Which type of lens is used to correct short-sightedness (myopia)?',
 '[{"text":"Convex lens","isCorrect":false},{"text":"Concave lens","isCorrect":true},{"text":"Cylindrical lens","isCorrect":false},{"text":"Bifocal lens","isCorrect":false}]'::jsonb,
 null, 'A concave lens diverges light rays and is used to correct short-sightedness (myopia).'),

-- General Science: Chemistry Basics
('RRB ALP', 'General Science', 'Chemistry Basics', 'easy', 'mcq',
 'What is the chemical symbol for Sodium?',
 '[{"text":"So","isCorrect":false},{"text":"Na","isCorrect":true},{"text":"S","isCorrect":false},{"text":"Sd","isCorrect":false}]'::jsonb,
 null, 'The chemical symbol for Sodium is Na, from its Latin name "natrium".'),
('RRB ALP', 'General Science', 'Chemistry Basics', 'easy', 'mcq',
 'Which gas is essential for respiration in living beings?',
 '[{"text":"Carbon dioxide","isCorrect":false},{"text":"Oxygen","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Oxygen is essential for respiration in most living beings.'),
('RRB ALP', 'General Science', 'Chemistry Basics', 'medium', 'mcq',
 'What is the chemical formula of common salt?',
 '[{"text":"NaCl","isCorrect":true},{"text":"CaCO3","isCorrect":false},{"text":"Na2CO3","isCorrect":false},{"text":"NaHCO3","isCorrect":false}]'::jsonb,
 null, 'Common salt is chemically sodium chloride, with the formula NaCl.'),
('RRB ALP', 'General Science', 'Chemistry Basics', 'medium', 'mcq',
 'Which acid is present in vinegar?',
 '[{"text":"Citric acid","isCorrect":false},{"text":"Acetic acid","isCorrect":true},{"text":"Lactic acid","isCorrect":false},{"text":"Sulfuric acid","isCorrect":false}]'::jsonb,
 null, 'Vinegar contains acetic acid, which gives it its characteristic sour taste.'),

-- General Science: Biology Basics
('RRB ALP', 'General Science', 'Biology Basics', 'easy', 'mcq',
 'Which gas do humans exhale during respiration?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Humans exhale carbon dioxide as a waste product of respiration.'),
('RRB ALP', 'General Science', 'Biology Basics', 'easy', 'mcq',
 'Which organ is responsible for pumping oxygen-rich blood to the body?',
 '[{"text":"Heart","isCorrect":true},{"text":"Lungs","isCorrect":false},{"text":"Kidney","isCorrect":false},{"text":"Liver","isCorrect":false}]'::jsonb,
 null, 'The heart pumps oxygen-rich blood from the lungs to the rest of the body.'),
('RRB ALP', 'General Science', 'Biology Basics', 'medium', 'mcq',
 'How many bones are there in an adult human body?',
 '[{"text":"196","isCorrect":false},{"text":"206","isCorrect":true},{"text":"216","isCorrect":false},{"text":"186","isCorrect":false}]'::jsonb,
 null, 'An adult human body has 206 bones.'),
('RRB ALP', 'General Science', 'Biology Basics', 'medium', 'mcq',
 'Which blood cells help in fighting infections?',
 '[{"text":"Red blood cells","isCorrect":false},{"text":"White blood cells","isCorrect":true},{"text":"Platelets","isCorrect":false},{"text":"Plasma","isCorrect":false}]'::jsonb,
 null, 'White blood cells are part of the immune system and help fight infections.'),

-- General Science: Everyday Science and Technology
('RRB ALP', 'General Science', 'Everyday Science and Technology', 'easy', 'mcq',
 'Which instrument is used to measure atmospheric pressure?',
 '[{"text":"Thermometer","isCorrect":false},{"text":"Barometer","isCorrect":true},{"text":"Hygrometer","isCorrect":false},{"text":"Odometer","isCorrect":false}]'::jsonb,
 null, 'A barometer is used to measure atmospheric pressure.'),
('RRB ALP', 'General Science', 'Everyday Science and Technology', 'easy', 'mcq',
 'What does CPU stand for in computers?',
 '[{"text":"Central Processing Unit","isCorrect":true},{"text":"Central Program Unit","isCorrect":false},{"text":"Computer Processing Unit","isCorrect":false},{"text":"Central Processor Utility","isCorrect":false}]'::jsonb,
 null, 'CPU stands for Central Processing Unit, the main processing component of a computer.'),
('RRB ALP', 'General Science', 'Everyday Science and Technology', 'medium', 'mcq',
 'Which part of a vehicle converts fuel energy into mechanical energy?',
 '[{"text":"Battery","isCorrect":false},{"text":"Engine","isCorrect":true},{"text":"Radiator","isCorrect":false},{"text":"Gearbox","isCorrect":false}]'::jsonb,
 null, 'The engine converts the chemical energy of fuel into mechanical energy to power the vehicle.'),
('RRB ALP', 'General Science', 'Everyday Science and Technology', 'medium', 'mcq',
 'What is the main function of a transformer in an electrical system?',
 '[{"text":"Store energy","isCorrect":false},{"text":"Change voltage levels","isCorrect":true},{"text":"Generate current","isCorrect":false},{"text":"Measure current","isCorrect":false}]'::jsonb,
 null, 'A transformer changes the voltage level of alternating current, stepping it up or down as needed.'),

-- General Awareness on Current Affairs: Indian History and Culture
('RRB ALP', 'General Awareness on Current Affairs', 'Indian History and Culture', 'easy', 'mcq',
 'Who was the first Governor-General of independent India?',
 '[{"text":"Lord Mountbatten","isCorrect":true},{"text":"C. Rajagopalachari","isCorrect":false},{"text":"Lord Wavell","isCorrect":false},{"text":"Warren Hastings","isCorrect":false}]'::jsonb,
 null, 'Lord Mountbatten served as the first Governor-General of independent India.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian History and Culture', 'easy', 'mcq',
 'In which year was the Indian Constitution enforced?',
 '[{"text":"1947","isCorrect":false},{"text":"1950","isCorrect":true},{"text":"1949","isCorrect":false},{"text":"1952","isCorrect":false}]'::jsonb,
 null, 'The Indian Constitution came into force on 26 January 1950.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian History and Culture', 'medium', 'mcq',
 'Who was the founder of the Sikh religion?',
 '[{"text":"Guru Nanak","isCorrect":true},{"text":"Guru Gobind Singh","isCorrect":false},{"text":"Guru Arjan Dev","isCorrect":false},{"text":"Guru Tegh Bahadur","isCorrect":false}]'::jsonb,
 null, 'Guru Nanak founded the Sikh religion in the 15th century.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian History and Culture', 'medium', 'mcq',
 'The Cripps Mission came to India in which year?',
 '[{"text":"1942","isCorrect":true},{"text":"1935","isCorrect":false},{"text":"1946","isCorrect":false},{"text":"1930","isCorrect":false}]'::jsonb,
 null, 'The Cripps Mission arrived in India in 1942 to discuss constitutional reforms.'),

-- General Awareness on Current Affairs: Indian Polity and Geography
('RRB ALP', 'General Awareness on Current Affairs', 'Indian Polity and Geography', 'easy', 'mcq',
 'Who appoints the Governor of a state in India?',
 '[{"text":"Prime Minister","isCorrect":false},{"text":"President","isCorrect":true},{"text":"Chief Minister","isCorrect":false},{"text":"Parliament","isCorrect":false}]'::jsonb,
 null, 'The President of India appoints the Governor of each state.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the largest river island in India?',
 '[{"text":"Majuli","isCorrect":true},{"text":"Andaman","isCorrect":false},{"text":"Diu","isCorrect":false},{"text":"Elephanta","isCorrect":false}]'::jsonb,
 null, 'Majuli, located on the Brahmaputra river in Assam, is the largest river island in India.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian Polity and Geography', 'medium', 'mcq',
 'How many Fundamental Duties are listed in the Indian Constitution?',
 '[{"text":"10","isCorrect":false},{"text":"11","isCorrect":true},{"text":"12","isCorrect":false},{"text":"9","isCorrect":false}]'::jsonb,
 null, 'The Indian Constitution lists 11 Fundamental Duties for citizens.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which is the highest waterfall in India?',
 '[{"text":"Jog Falls","isCorrect":false},{"text":"Kunchikal Falls","isCorrect":true},{"text":"Nohkalikai Falls","isCorrect":false},{"text":"Dudhsagar Falls","isCorrect":false}]'::jsonb,
 null, 'Kunchikal Falls in Karnataka is considered the highest waterfall in India.'),

-- General Awareness on Current Affairs: Current Affairs and Sports
('RRB ALP', 'General Awareness on Current Affairs', 'Current Affairs and Sports', 'easy', 'mcq',
 'How many players are there in a kabaddi team on the field?',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":false},{"text":"7","isCorrect":true},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A kabaddi team fields 7 players at a time.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Current Affairs and Sports', 'easy', 'mcq',
 'The Hockey World Cup 2023 was held in which country?',
 '[{"text":"India","isCorrect":true},{"text":"Netherlands","isCorrect":false},{"text":"Germany","isCorrect":false},{"text":"Australia","isCorrect":false}]'::jsonb,
 null, 'The 2023 Hockey World Cup was held in India, in Bhubaneswar and Rourkela.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Current Affairs and Sports', 'medium', 'mcq',
 'Who won the Miss World title representing India in 2017?',
 '[{"text":"Manushi Chhillar","isCorrect":true},{"text":"Priyanka Chopra","isCorrect":false},{"text":"Aishwarya Rai","isCorrect":false},{"text":"Sushmita Sen","isCorrect":false}]'::jsonb,
 null, 'Manushi Chhillar won the Miss World title in 2017.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Current Affairs and Sports', 'medium', 'mcq',
 'The Chandrayaan-3 mission successfully landed near which region of the Moon?',
 '[{"text":"North Pole","isCorrect":false},{"text":"South Pole","isCorrect":true},{"text":"Equator","isCorrect":false},{"text":"Far side","isCorrect":false}]'::jsonb,
 null, 'Chandrayaan-3 made a successful soft landing near the South Pole of the Moon in 2023.'),

-- General Awareness on Current Affairs: Railways General Knowledge
('RRB ALP', 'General Awareness on Current Affairs', 'Railways General Knowledge', 'easy', 'mcq',
 'What is the primary role of an Assistant Loco Pilot in Indian Railways?',
 '[{"text":"Ticket checking","isCorrect":false},{"text":"Assisting the train driver","isCorrect":true},{"text":"Track maintenance","isCorrect":false},{"text":"Station management","isCorrect":false}]'::jsonb,
 null, 'An Assistant Loco Pilot assists the Loco Pilot (train driver) in operating the locomotive.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Railways General Knowledge', 'easy', 'mcq',
 'Which of these is a high-speed conventional (non-Vande Bharat) train in India?',
 '[{"text":"Gatimaan Express","isCorrect":true},{"text":"Passenger Train","isCorrect":false},{"text":"Local Train","isCorrect":false},{"text":"MEMU","isCorrect":false}]'::jsonb,
 null, 'The Gatimaan Express is known as one of India''s fastest conventional trains.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Railways General Knowledge', 'medium', 'mcq',
 'Which organization is responsible for railway safety research and standards in India?',
 '[{"text":"RDSO","isCorrect":true},{"text":"CRIS","isCorrect":false},{"text":"IRCTC","isCorrect":false},{"text":"RITES","isCorrect":false}]'::jsonb,
 null, 'RDSO (Research Designs and Standards Organisation) is responsible for research, design, and standards for Indian Railways.'),
('RRB ALP', 'General Awareness on Current Affairs', 'Railways General Knowledge', 'medium', 'mcq',
 'Which zone of Indian Railways has its headquarters in Kolkata?',
 '[{"text":"Eastern Railway","isCorrect":true},{"text":"Northern Railway","isCorrect":false},{"text":"Western Railway","isCorrect":false},{"text":"Southern Railway","isCorrect":false}]'::jsonb,
 null, 'Eastern Railway has its headquarters in Kolkata.');
