-- supabase/sql/exam_question_bank_neet_ug_set5.sql
--
-- Fifth curated question-bank batch for 'NEET UG' (see exam_patterns_neet_ug.sql for the exam's
-- structure, and Sets 1-4 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1, 2, 3, or 4.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET UG's 100% single-best-response format. 16 chapters (4 each across Physics,
-- Chemistry, Botany, Zoology) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_ug.sql and
-- exam_question_bank_neet_ug_set1.sql through set4.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The dimensional formula of angular momentum is:',
 '[{"text":"[MLT^-1]","isCorrect":false},{"text":"[ML^2T^-1]","isCorrect":true},{"text":"[ML^2T^-2]","isCorrect":false},{"text":"[MLT^-2]","isCorrect":false}]'::jsonb,
 null, 'Angular momentum L = I*omega has dimensions [ML^2]*[T^-1] = [ML^2T^-1].'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'A body moving in uniform circular motion has constant:',
 '[{"text":"Velocity","isCorrect":false},{"text":"Speed (and kinetic energy)","isCorrect":true},{"text":"Acceleration direction","isCorrect":false},{"text":"Displacement","isCorrect":false}]'::jsonb,
 null, 'In uniform circular motion, the speed (and hence kinetic energy) remains constant, even though the velocity''s direction is continuously changing.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The coefficient of static friction between two surfaces is generally:',
 '[{"text":"Less than the coefficient of kinetic friction","isCorrect":false},{"text":"Greater than or equal to the coefficient of kinetic friction","isCorrect":true},{"text":"Always exactly zero","isCorrect":false},{"text":"Unrelated to the coefficient of kinetic friction","isCorrect":false}]'::jsonb,
 null, 'The coefficient of static friction is generally greater than or equal to the coefficient of kinetic friction, since more force is typically needed to start motion than to sustain it.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'According to the work-energy theorem, negative work done on an object results in:',
 '[{"text":"An increase in its kinetic energy","isCorrect":false},{"text":"A decrease in its kinetic energy","isCorrect":true},{"text":"No change in its kinetic energy","isCorrect":false},{"text":"An increase in its mass","isCorrect":false}]'::jsonb,
 null, 'Since work done equals the change in kinetic energy, negative work (such as from a retarding force) causes a decrease in an object''s kinetic energy.'),

-- Physics: Electrodynamics
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of inductance is the:',
 '[{"text":"Farad","isCorrect":false},{"text":"Henry","isCorrect":true},{"text":"Weber","isCorrect":false},{"text":"Tesla","isCorrect":false}]'::jsonb,
 null, 'Inductance is measured in henries (H), named after physicist Joseph Henry.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'Kirchhoff''s current law (junction rule) is based on which conservation principle?',
 '[{"text":"Conservation of energy","isCorrect":false},{"text":"Conservation of electric charge","isCorrect":true},{"text":"Conservation of momentum","isCorrect":false},{"text":"Conservation of mass","isCorrect":false}]'::jsonb,
 null, 'Kirchhoff''s current law states that the total current entering a junction equals the total current leaving it, reflecting conservation of electric charge.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The force between the two oppositely charged plates of a charged parallel plate capacitor is:',
 '[{"text":"Repulsive","isCorrect":false},{"text":"Attractive","isCorrect":true},{"text":"Zero","isCorrect":false},{"text":"Dependent on the plate material only","isCorrect":false}]'::jsonb,
 null, 'Since the two plates of a charged capacitor carry opposite charges, they attract each other electrostatically.'),
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'An ammeter, used to measure current, is always connected in ___ with the circuit.',
 '[{"text":"Parallel","isCorrect":false},{"text":"Series","isCorrect":true},{"text":"Neither series nor parallel","isCorrect":false},{"text":"Series-parallel combination only","isCorrect":false}]'::jsonb,
 null, 'An ammeter must be connected in series so that the entire current to be measured flows through it.'),

-- Physics: Optics and Wave Phenomena
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'The phenomenon of interference of light is explained based on which principle?',
 '[{"text":"The principle of superposition of waves","isCorrect":true},{"text":"The particle nature of light alone","isCorrect":false},{"text":"The law of reflection","isCorrect":false},{"text":"Snell''s law","isCorrect":false}]'::jsonb,
 null, 'Interference occurs due to the superposition of two or more coherent light waves, where their amplitudes add algebraically at each point.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The power of a concave (diverging) lens is always:',
 '[{"text":"Positive","isCorrect":false},{"text":"Negative","isCorrect":true},{"text":"Zero","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'By convention, a concave (diverging) lens has a negative focal length, and hence its power (1/f) is always negative.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'In a compound microscope, the final image formed (as seen by the eye) is:',
 '[{"text":"Real, erect, and diminished","isCorrect":false},{"text":"Virtual, inverted, and magnified","isCorrect":true},{"text":"Real, inverted, and diminished","isCorrect":false},{"text":"Virtual, erect, and diminished","isCorrect":false}]'::jsonb,
 null, 'In a compound microscope, the eyepiece forms a virtual, inverted, and highly magnified final image of the intermediate real image produced by the objective lens.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'Total internal reflection can occur only when light travels:',
 '[{"text":"From a rarer medium to a denser medium","isCorrect":false},{"text":"From a denser medium to a rarer medium, beyond the critical angle","isCorrect":true},{"text":"Through a perfect vacuum only","isCorrect":false},{"text":"Along the normal to the surface","isCorrect":false}]'::jsonb,
 null, 'Total internal reflection requires light to travel from an optically denser medium into a rarer medium, striking the interface at an angle greater than the critical angle.'),

-- Physics: Modern Physics and Semiconductor Devices
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'The half-life of a radioactive element is defined as:',
 '[{"text":"The total time for all nuclei to decay","isCorrect":false},{"text":"The time taken for half of the radioactive nuclei to decay","isCorrect":true},{"text":"The time taken for the substance to become stable","isCorrect":false},{"text":"A fixed universal constant for all elements","isCorrect":false}]'::jsonb,
 null, 'Half-life is the time required for exactly half of the radioactive nuclei in a sample to undergo decay.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'In an intrinsic (pure) semiconductor, the number of free electrons is:',
 '[{"text":"Much greater than the number of holes","isCorrect":false},{"text":"Equal to the number of holes","isCorrect":true},{"text":"Much less than the number of holes","isCorrect":false},{"text":"Always zero","isCorrect":false}]'::jsonb,
 null, 'In an intrinsic (undoped) semiconductor, electrons and holes are generated in pairs, so their numbers are equal.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Compared to an insulator, the energy gap between the valence band and conduction band in a conductor is:',
 '[{"text":"Very large","isCorrect":false},{"text":"Very small or overlapping (near zero)","isCorrect":true},{"text":"Exactly equal to that of an insulator","isCorrect":false},{"text":"Infinite","isCorrect":false}]'::jsonb,
 null, 'In conductors, the valence and conduction bands overlap or have a negligible energy gap, allowing electrons to move freely, unlike the large energy gap in insulators.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Nuclear fusion, the process that powers the sun, involves:',
 '[{"text":"Splitting heavy nuclei into lighter ones","isCorrect":false},{"text":"Combining light nuclei into heavier nuclei, releasing energy","isCorrect":true},{"text":"The decay of a single unstable nucleus","isCorrect":false},{"text":"The absorption of neutrons without any nuclear change","isCorrect":false}]'::jsonb,
 null, 'Nuclear fusion combines light atomic nuclei (like hydrogen) into heavier ones, releasing enormous energy, as occurs continuously in the sun''s core.'),

-- Chemistry: Physical Chemistry
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The rate of a chemical reaction generally increases with:',
 '[{"text":"Decreasing temperature","isCorrect":false},{"text":"Increasing temperature","isCorrect":true},{"text":"Decreasing concentration of reactants only","isCorrect":false},{"text":"Removing the catalyst","isCorrect":false}]'::jsonb,
 null, 'Increasing temperature raises the kinetic energy of reacting molecules, increasing the frequency and effectiveness of collisions, and hence the reaction rate.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'Which law states that equal volumes of gases at the same temperature and pressure contain equal numbers of moles?',
 '[{"text":"Boyle''s law","isCorrect":false},{"text":"Avogadro''s law","isCorrect":true},{"text":"Charles'' law","isCorrect":false},{"text":"Dalton''s law","isCorrect":false}]'::jsonb,
 null, 'Avogadro''s law states that equal volumes of gases, at the same temperature and pressure, contain equal numbers of moles (or molecules).'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'A buffer solution resists significant change in pH upon the addition of:',
 '[{"text":"Small amounts of acid or base","isCorrect":true},{"text":"Large amounts of pure water only","isCorrect":false},{"text":"Heat alone","isCorrect":false},{"text":"Any amount of a strong acid, without limit","isCorrect":false}]'::jsonb,
 null, 'A buffer solution, typically a weak acid/conjugate base pair, resists significant pH change when small amounts of acid or base are added.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The osmotic pressure of a solution is directly proportional to its:',
 '[{"text":"Color","isCorrect":false},{"text":"Molar concentration (at constant temperature)","isCorrect":true},{"text":"Viscosity","isCorrect":false},{"text":"Boiling point alone","isCorrect":false}]'::jsonb,
 null, 'Osmotic pressure (pi = CRT) is directly proportional to the molar concentration of solute particles in the solution, at a given temperature.'),

-- Chemistry: Organic Chemistry
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The functional group present in an ether is:',
 '[{"text":"-OH","isCorrect":false},{"text":"-O- (an oxygen atom bonded to two carbon groups)","isCorrect":true},{"text":"-COOH","isCorrect":false},{"text":"-CHO","isCorrect":false}]'::jsonb,
 null, 'Ethers are characterized by an oxygen atom bonded to two alkyl or aryl groups (R-O-R'').'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The reaction that converts an alcohol into an alkene by removal of a water molecule is called:',
 '[{"text":"Hydration","isCorrect":false},{"text":"Dehydration","isCorrect":true},{"text":"Hydrogenation","isCorrect":false},{"text":"Oxidation","isCorrect":false}]'::jsonb,
 null, 'Dehydration of an alcohol, typically using an acid catalyst and heat, removes a water molecule to form an alkene.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Optical isomers (enantiomers) are best described as:',
 '[{"text":"Molecules with different molecular formulas","isCorrect":false},{"text":"Non-superimposable mirror images of each other","isCorrect":true},{"text":"Identical molecules with different names","isCorrect":false},{"text":"Molecules differing only in physical state","isCorrect":false}]'::jsonb,
 null, 'Enantiomers are pairs of optical isomers that are non-superimposable mirror images of one another, typically differing in their interaction with plane-polarized light.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Which reagent is commonly used to test for the presence of unsaturation (carbon-carbon double or triple bonds) in an organic compound?',
 '[{"text":"Bromine water (which gets decolorized)","isCorrect":true},{"text":"Dilute HCl","isCorrect":false},{"text":"Sodium metal","isCorrect":false},{"text":"Litmus paper","isCorrect":false}]'::jsonb,
 null, 'Bromine water is decolorized when it reacts with unsaturated compounds (alkenes/alkynes) via addition across the double or triple bond, providing a simple test for unsaturation.'),

-- Chemistry: Inorganic Chemistry
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Which element exhibits allotropy, existing in forms such as graphite and diamond?',
 '[{"text":"Carbon","isCorrect":true},{"text":"Silicon","isCorrect":false},{"text":"Sulfur","isCorrect":false},{"text":"Phosphorus","isCorrect":false}]'::jsonb,
 null, 'Carbon exhibits allotropy, existing in multiple structural forms including graphite, diamond, and fullerenes, each with distinct properties.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The general outer electronic configuration of halogens (group 17) is:',
 '[{"text":"ns1","isCorrect":false},{"text":"ns2np5","isCorrect":true},{"text":"ns2np6","isCorrect":false},{"text":"ns2","isCorrect":false}]'::jsonb,
 null, 'Halogens (group 17 elements) have the general outer electronic configuration ns2np5, needing just one more electron to achieve a stable octet.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which gas turns lime water milky when passed through it?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Carbon dioxide reacts with the calcium hydroxide in lime water to form insoluble calcium carbonate, causing the characteristic milky appearance.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Alkaline earth metals belong to which group of the periodic table?',
 '[{"text":"Group 1","isCorrect":false},{"text":"Group 2","isCorrect":true},{"text":"Group 17","isCorrect":false},{"text":"Group 18","isCorrect":false}]'::jsonb,
 null, 'Alkaline earth metals, including beryllium, magnesium, and calcium, belong to group 2 of the periodic table.'),

-- Chemistry: Biomolecules and Environmental Chemistry
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Vitamins are broadly classified into which two categories based on their solubility?',
 '[{"text":"Fat-soluble and water-soluble","isCorrect":true},{"text":"Acidic and basic","isCorrect":false},{"text":"Organic and inorganic","isCorrect":false},{"text":"Natural and synthetic","isCorrect":false}]'::jsonb,
 null, 'Vitamins are broadly classified as fat-soluble (like vitamins A, D, E, K) or water-soluble (like vitamin C and the B-complex vitamins).'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'The primary structure of a protein refers to:',
 '[{"text":"Its overall 3D folded shape","isCorrect":false},{"text":"The linear sequence of amino acids","isCorrect":true},{"text":"Its interaction with other proteins","isCorrect":false},{"text":"Its enzymatic activity","isCorrect":false}]'::jsonb,
 null, 'The primary structure of a protein is simply the linear sequence in which amino acids are joined by peptide bonds, forming the polypeptide chain.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Biological magnification (biomagnification) refers to:',
 '[{"text":"The increasing concentration of a toxic substance at higher trophic levels","isCorrect":true},{"text":"The decreasing size of organisms up the food chain","isCorrect":false},{"text":"The growth rate of a single population","isCorrect":false},{"text":"The magnification power of a microscope","isCorrect":false}]'::jsonb,
 null, 'Biomagnification describes how the concentration of certain persistent toxic substances (like DDT) increases as they move up successive trophic levels in a food chain.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Although present in smaller atmospheric quantities than carbon dioxide, which greenhouse gas has a much higher global warming potential per molecule?',
 '[{"text":"Methane","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Argon","isCorrect":false},{"text":"Helium","isCorrect":false}]'::jsonb,
 null, 'Methane, though present in smaller quantities than CO2, traps significantly more heat per molecule, giving it a much higher global warming potential.'),

-- Botany: Plant Physiology
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The growth response of a plant in relation to gravity is called:',
 '[{"text":"Phototropism","isCorrect":false},{"text":"Geotropism (gravitropism)","isCorrect":true},{"text":"Hydrotropism","isCorrect":false},{"text":"Thigmotropism","isCorrect":false}]'::jsonb,
 null, 'Geotropism (gravitropism) refers to the directional growth response of a plant part in relation to the pull of gravity.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Which accessory pigment, alongside chlorophyll, contributes to light absorption in photosynthesis and gives some plant parts a yellow-orange color?',
 '[{"text":"Carotenoids","isCorrect":true},{"text":"Hemoglobin","isCorrect":false},{"text":"Melanin","isCorrect":false},{"text":"Anthocyanin exclusively","isCorrect":false}]'::jsonb,
 null, 'Carotenoids are accessory pigments that absorb light in wavelengths not efficiently captured by chlorophyll, contributing yellow and orange coloration.'),
('NEET UG', 'Botany', 'Plant Physiology', 'hard', 'mcq',
 'C4 plants are more efficient than C3 plants in hot, dry climates primarily because they:',
 '[{"text":"Have larger leaves for more light absorption","isCorrect":false},{"text":"Minimize photorespiration through a specialized carbon-fixation pathway","isCorrect":true},{"text":"Require no sunlight at all","isCorrect":false},{"text":"Lack stomata entirely","isCorrect":false}]'::jsonb,
 null, 'C4 plants use a specialized carbon-fixation pathway that concentrates CO2 around RuBisCO, minimizing wasteful photorespiration, making them more efficient in hot, dry conditions.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The opening and closing of stomata is primarily regulated by changes in:',
 '[{"text":"The color of the leaf","isCorrect":false},{"text":"The turgor pressure of guard cells","isCorrect":true},{"text":"The thickness of the cuticle","isCorrect":false},{"text":"The number of chloroplasts in the epidermis","isCorrect":false}]'::jsonb,
 null, 'Changes in the turgor pressure of the guard cells surrounding each stomatal pore cause them to bulge or relax, opening or closing the stomata.'),

-- Botany: Cell Biology and Genetics
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'Which structure is primarily responsible for spindle fiber formation during cell division in animal cells?',
 '[{"text":"Centriole/centrosome","isCorrect":true},{"text":"Golgi apparatus","isCorrect":false},{"text":"Ribosome","isCorrect":false},{"text":"Vacuole","isCorrect":false}]'::jsonb,
 null, 'The centrosome (containing centrioles in animal cells) organizes the microtubules that form the mitotic spindle during cell division.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'According to Mendel''s law of independent assortment, genes for different traits:',
 '[{"text":"Always segregate together as a fixed unit","isCorrect":false},{"text":"Segregate independently of one another during gamete formation","isCorrect":true},{"text":"Never separate during meiosis","isCorrect":false},{"text":"Only apply to a single trait at a time","isCorrect":false}]'::jsonb,
 null, 'The law of independent assortment states that alleles of different genes (on different chromosomes) segregate independently of one another during gamete formation.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'A heterozygous individual carries:',
 '[{"text":"Two identical alleles for a particular gene","isCorrect":false},{"text":"Two different alleles for a particular gene","isCorrect":true},{"text":"No alleles for that gene","isCorrect":false},{"text":"Three alleles for that gene","isCorrect":false}]'::jsonb,
 null, 'A heterozygous individual carries two different alleles for a given gene, one inherited from each parent.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'The endoplasmic reticulum that is studded with ribosomes on its surface is called the:',
 '[{"text":"Smooth endoplasmic reticulum","isCorrect":false},{"text":"Rough endoplasmic reticulum","isCorrect":true},{"text":"Golgi endoplasmic reticulum","isCorrect":false},{"text":"Sarcoplasmic reticulum only","isCorrect":false}]'::jsonb,
 null, 'The rough endoplasmic reticulum has ribosomes attached to its outer surface, giving it a "rough" appearance and enabling protein synthesis directly into its lumen.'),

-- Botany: Ecology and Environment
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'Mutualism is a type of interspecies interaction in which:',
 '[{"text":"One species benefits while the other is harmed","isCorrect":false},{"text":"Both species benefit","isCorrect":true},{"text":"Both species are harmed","isCorrect":false},{"text":"Neither species is affected","isCorrect":false}]'::jsonb,
 null, 'Mutualism describes a relationship in which both interacting species derive a benefit, such as bees pollinating flowers while obtaining nectar.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'The Red Data Book primarily contains information on:',
 '[{"text":"Endangered and threatened species","isCorrect":true},{"text":"All species that have gone extinct only","isCorrect":false},{"text":"Only domesticated animal breeds","isCorrect":false},{"text":"Common, abundant species","isCorrect":false}]'::jsonb,
 null, 'The Red Data Book, maintained by the IUCN, documents the conservation status of species, particularly those that are endangered or threatened with extinction.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'Primary ecological succession begins on:',
 '[{"text":"A bare, previously uninhabited substrate (e.g. bare rock)","isCorrect":true},{"text":"An area that already has a fully developed community","isCorrect":false},{"text":"Agricultural farmland only","isCorrect":false},{"text":"An urban city center","isCorrect":false}]'::jsonb,
 null, 'Primary succession begins on a bare, lifeless substrate (such as bare rock or newly formed volcanic land) with no pre-existing soil or organisms.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'Which international agreement, adopted in 1992, aims to conserve global biological diversity?',
 '[{"text":"The Convention on Biological Diversity (CBD)","isCorrect":true},{"text":"The Kyoto Protocol","isCorrect":false},{"text":"The Montreal Protocol","isCorrect":false},{"text":"The Paris Agreement","isCorrect":false}]'::jsonb,
 null, 'The Convention on Biological Diversity, adopted in 1992 at the Rio Earth Summit, is an international treaty dedicated to conserving biological diversity worldwide.'),

-- Botany: Plant Morphology and Anatomy
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The part of a flower that receives pollen grains during pollination is the:',
 '[{"text":"Stigma","isCorrect":true},{"text":"Ovary","isCorrect":false},{"text":"Filament","isCorrect":false},{"text":"Sepal","isCorrect":false}]'::jsonb,
 null, 'The stigma, the receptive tip of the pistil (female reproductive part), is where pollen grains land and germinate during pollination.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'Xylem tissue in plants is primarily responsible for the transport of:',
 '[{"text":"Sugars produced during photosynthesis","isCorrect":false},{"text":"Water and dissolved minerals","isCorrect":true},{"text":"Hormones only","isCorrect":false},{"text":"Oxygen gas","isCorrect":false}]'::jsonb,
 null, 'Xylem transports water and dissolved minerals absorbed by the roots upward to the rest of the plant.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The corolla of a flower is made up of the:',
 '[{"text":"Sepals","isCorrect":false},{"text":"Petals","isCorrect":true},{"text":"Stamens","isCorrect":false},{"text":"Carpels","isCorrect":false}]'::jsonb,
 null, 'The corolla refers collectively to the petals of a flower, which are often brightly colored to attract pollinators.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Adventitious roots arise from parts of the plant other than the:',
 '[{"text":"Primary (radicle-derived) root","isCorrect":true},{"text":"Stem exclusively","isCorrect":false},{"text":"Leaf exclusively","isCorrect":false},{"text":"Flower exclusively","isCorrect":false}]'::jsonb,
 null, 'Adventitious roots develop from plant parts other than the primary root (which develops from the radicle), such as stems or leaves.'),

-- Zoology: Human Physiology
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which heart valve prevents backflow of blood from the left ventricle into the left atrium?',
 '[{"text":"Tricuspid valve","isCorrect":false},{"text":"Mitral (bicuspid) valve","isCorrect":true},{"text":"Pulmonary valve","isCorrect":false},{"text":"Aortic valve","isCorrect":false}]'::jsonb,
 null, 'The mitral (bicuspid) valve, located between the left atrium and left ventricle, prevents backflow of blood into the left atrium during ventricular contraction.'),
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'The hormone thyroxine is secreted by the:',
 '[{"text":"Pancreas","isCorrect":false},{"text":"Thyroid gland","isCorrect":true},{"text":"Adrenal gland","isCorrect":false},{"text":"Pituitary gland","isCorrect":false}]'::jsonb,
 null, 'Thyroxine is the primary hormone secreted by the thyroid gland, regulating the body''s metabolic rate.'),
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'Peristalsis in the digestive tract is primarily responsible for:',
 '[{"text":"Digesting proteins chemically","isCorrect":false},{"text":"Propelling food through the alimentary canal","isCorrect":true},{"text":"Absorbing nutrients directly","isCorrect":false},{"text":"Producing digestive enzymes","isCorrect":false}]'::jsonb,
 null, 'Peristalsis refers to the coordinated, wave-like muscular contractions that propel food along the digestive tract.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which part of the human brain is primarily responsible for coordinating voluntary muscle movements and maintaining balance?',
 '[{"text":"Cerebrum","isCorrect":false},{"text":"Cerebellum","isCorrect":true},{"text":"Medulla oblongata","isCorrect":false},{"text":"Hypothalamus","isCorrect":false}]'::jsonb,
 null, 'The cerebellum coordinates voluntary muscle movements, posture, and balance, fine-tuning motor commands initiated elsewhere in the brain.'),

-- Zoology: Human Reproduction and Reproductive Health
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'After fertilization, the zygote undergoes repeated divisions to eventually form a structure called the:',
 '[{"text":"Blastocyst","isCorrect":true},{"text":"Corpus luteum","isCorrect":false},{"text":"Follicle","isCorrect":false},{"text":"Endometrium","isCorrect":false}]'::jsonb,
 null, 'The zygote divides repeatedly to form a blastocyst, which then implants into the uterine wall (endometrium).'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Which hormone, secreted by the anterior pituitary, stimulates the maturation of an ovarian follicle?',
 '[{"text":"Follicle-Stimulating Hormone (FSH)","isCorrect":true},{"text":"Oxytocin","isCorrect":false},{"text":"Prolactin","isCorrect":false},{"text":"Testosterone","isCorrect":false}]'::jsonb,
 null, 'Follicle-Stimulating Hormone (FSH), secreted by the anterior pituitary, stimulates the growth and maturation of ovarian follicles.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Tubectomy, a permanent method of contraception, is performed in:',
 '[{"text":"Males, by blocking the vas deferens","isCorrect":false},{"text":"Females, by blocking the fallopian tubes","isCorrect":true},{"text":"Males, by removing the testes","isCorrect":false},{"text":"Females, by removing the ovaries","isCorrect":false}]'::jsonb,
 null, 'Tubectomy is a permanent surgical contraceptive procedure performed in females, in which the fallopian tubes are blocked or cut to prevent the egg from meeting sperm.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'The average duration of human pregnancy, counted from the date of fertilization, is approximately:',
 '[{"text":"20 weeks","isCorrect":false},{"text":"38 weeks","isCorrect":true},{"text":"50 weeks","isCorrect":false},{"text":"60 weeks","isCorrect":false}]'::jsonb,
 null, 'Counted from the actual date of fertilization, human pregnancy lasts approximately 38 weeks (this is about 2 weeks shorter than the commonly cited 40-week figure, which is instead counted from the last menstrual period).'),

-- Zoology: Genetics and Evolution
('NEET UG', 'Zoology', 'Genetics and Evolution', 'easy', 'mcq',
 'Down syndrome is caused by the presence of an extra copy of which chromosome?',
 '[{"text":"Chromosome 18","isCorrect":false},{"text":"Chromosome 21","isCorrect":true},{"text":"Chromosome 13","isCorrect":false},{"text":"The X chromosome","isCorrect":false}]'::jsonb,
 null, 'Down syndrome results from trisomy of chromosome 21 -- the presence of an extra copy of this chromosome.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'According to Darwin''s theory of natural selection, individuals with favorable heritable variations are more likely to:',
 '[{"text":"Survive and reproduce, passing on their traits","isCorrect":true},{"text":"Become extinct immediately","isCorrect":false},{"text":"Remain completely unchanged across generations","isCorrect":false},{"text":"Lose their favorable traits over time","isCorrect":false}]'::jsonb,
 null, 'Natural selection favors individuals with heritable traits that improve survival and reproductive success, allowing those traits to become more common in future generations.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'easy', 'mcq',
 'A gene that is only expressed in the absence of a corresponding dominant allele is called a:',
 '[{"text":"Dominant gene","isCorrect":false},{"text":"Recessive gene (allele)","isCorrect":true},{"text":"Lethal gene","isCorrect":false},{"text":"Sex-linked gene exclusively","isCorrect":false}]'::jsonb,
 null, 'A recessive allele is only phenotypically expressed when present in the homozygous state (i.e. no dominant allele is present to mask it).'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'Comparing the anatomical structures of different species to infer evolutionary relationships is known as the study of:',
 '[{"text":"Comparative anatomy (homologous structures)","isCorrect":true},{"text":"Comparative genomics only","isCorrect":false},{"text":"Molecular biology exclusively","isCorrect":false},{"text":"Ecology exclusively","isCorrect":false}]'::jsonb,
 null, 'Comparative anatomy, particularly the study of homologous structures, provides key evidence for evolutionary relationships among different species.'),

-- Zoology: Biotechnology and its Applications
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'DNA fingerprinting is primarily used for:',
 '[{"text":"Identifying individuals based on unique DNA sequence variations","isCorrect":true},{"text":"Curing genetic diseases directly","isCorrect":false},{"text":"Increasing crop yield","isCorrect":false},{"text":"Producing antibiotics","isCorrect":false}]'::jsonb,
 null, 'DNA fingerprinting analyzes unique, highly variable regions of an individual''s DNA, widely used in forensic identification and paternity testing.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Which enzyme is used to join (ligate) DNA fragments together in genetic engineering?',
 '[{"text":"DNA polymerase","isCorrect":false},{"text":"DNA ligase","isCorrect":true},{"text":"Restriction endonuclease","isCorrect":false},{"text":"RNA polymerase","isCorrect":false}]'::jsonb,
 null, 'DNA ligase catalyzes the formation of phosphodiester bonds, joining DNA fragments together, complementing the cutting action of restriction enzymes.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'The Hepatitis B vaccine, produced using biotechnology, is manufactured using:',
 '[{"text":"Genetically engineered yeast cells expressing the viral surface antigen","isCorrect":true},{"text":"Live, fully infectious hepatitis B virus","isCorrect":false},{"text":"Extraction from infected human blood only, with no genetic engineering","isCorrect":false},{"text":"Chemical synthesis with no biological component","isCorrect":false}]'::jsonb,
 null, 'The modern Hepatitis B vaccine is produced by inserting the gene for the viral surface antigen into yeast cells, which then express and produce the antigen used in the vaccine.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Plant tissue culture, used to propagate plants from small tissue samples, relies on the principle of:',
 '[{"text":"Totipotency (the ability of a single cell to develop into a complete organism)","isCorrect":true},{"text":"Apoptosis","isCorrect":false},{"text":"Photosynthesis alone","isCorrect":false},{"text":"Osmosis alone","isCorrect":false}]'::jsonb,
 null, 'Plant tissue culture exploits totipotency -- the inherent capacity of a single plant cell to develop into an entire new organism under suitable conditions.');
