-- supabase/sql/exam_question_bank_set2.sql
--
-- Second curated batch for JEE Main, on top of exam_question_bank.sql's first 64 rows — same
-- table, same schema, no migration needed here beyond the base exam_question_bank.sql already
-- being run. Two things are different this time:
--
--  1. All-new question content per chapter (not duplicates of Set 1) — this widens the pool
--     fetchBankQuestions() shuffles from, so a user generating multiple "Set N" full tests for
--     JEE Main sees more variety instead of the same handful of questions repeating.
--  2. Deliberately weaves in LaTeX math notation ($...$ inline) throughout, and includes one
--     genuine multi-correct "which of the following statement(s) is/are true" MCQ per chapter (16
--     total) in the JEE-Advanced style — these still use format='mcq' (NOT a separate format
--     value): FullTestViewModel.toQuestion() / AiQuizRepository already derive MULTI_CHOICE
--     automatically whenever more than one option in an 'mcq' row is marked isCorrect, so no
--     schema or app change was needed to add these, just more than one true in options.
--
-- Run this once in the Supabase SQL Editor, after exam_question_bank.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'easy', 'mcq',
 'A car accelerates uniformly from $u = 5$ m/s to $v = 25$ m/s in $10$ s. Find the distance covered.',
 '[{"text":"100 m","isCorrect":false},{"text":"150 m","isCorrect":true},{"text":"200 m","isCorrect":false},{"text":"250 m","isCorrect":false}]'::jsonb,
 null, 'Average velocity = (5+25)/2 = 15 m/s. Distance = 15 * 10 = 150 m.'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'mcq',
 'A projectile is launched with initial speed $u=20$ m/s at $30^\circ$ above the horizontal ($g=10$ m/s^2). Find the maximum height reached.',
 '[{"text":"2.5 m","isCorrect":false},{"text":"5 m","isCorrect":true},{"text":"10 m","isCorrect":false},{"text":"20 m","isCorrect":false}]'::jsonb,
 null, 'H = u^2 sin^2(theta) / (2g) = 400 * 0.25 / 20 = 5 m.'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'numerical',
 'A uniform rod of mass $3$ kg and length $2$ m is pivoted at one end. Find its moment of inertia about that end (in $kg\,m^2$), using $I=\frac{1}{3}mL^2$.',
 null, '4', 'I = (1/3) * 3 * 2^2 = (1/3) * 3 * 4 = 4 kg m^2.'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'descriptive',
 'State the work-energy theorem and explain when it can be applied to a system with friction.',
 null, null, 'The work-energy theorem states the net work done by all forces on an object equals its change in kinetic energy. It applies even with friction present, as long as the work done by friction is included in the net work -- friction simply contributes negative work.'),

-- Physics: Electrodynamics
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'easy', 'mcq',
 'Two capacitors of $4\,\mu F$ and $12\,\mu F$ are connected in series. Find the equivalent capacitance.',
 '[{"text":"3 uF","isCorrect":true},{"text":"8 uF","isCorrect":false},{"text":"16 uF","isCorrect":false},{"text":"48 uF","isCorrect":false}]'::jsonb,
 null, '1/C = 1/4 + 1/12 = 4/12, so C = 3 uF.'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'mcq',
 'A parallel plate capacitor is connected to a battery of constant EMF. A dielectric slab of constant $K>1$ is then inserted, completely filling the gap, while the battery stays connected. Which of the following statement(s) is/are TRUE? (A) The capacitance increases by a factor of $K$. (B) The charge on the plates increases by a factor of $K$. (C) The electric field between the plates increases. (D) The energy stored decreases.',
 '[{"text":"(A) Capacitance increases by factor K","isCorrect":true},{"text":"(B) Charge increases by factor K","isCorrect":true},{"text":"(C) Electric field increases","isCorrect":false},{"text":"(D) Energy stored decreases","isCorrect":false}]'::jsonb,
 null, 'With the battery connected, V stays fixed. C becomes KC0, so Q=CV also scales by K (A, B true). Since E=V/d and both V and d are unchanged, E stays the same (C false). Energy = (1/2)CV^2 increases since C increases (D false).'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'easy', 'numerical',
 'A current of $2$ A flows through a $5\,\Omega$ resistor for $60$ s. Find the heat dissipated (in kJ), using $H=I^2Rt$.',
 null, '1.2', 'H = 2^2 * 5 * 60 = 1200 J = 1.2 kJ.'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'descriptive',
 'State Kirchhoff''s voltage law and explain the physical principle behind it.',
 null, null, 'Kirchhoff''s voltage law states the sum of all potential changes around any closed loop in a circuit is zero. It follows from conservation of energy: a charge returning to its starting point around a loop undergoes zero net change in electric potential energy.'),

-- Physics: Modern Physics
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'mcq',
 'In the photoelectric effect, if the frequency of incident light is doubled (staying above the threshold frequency), the maximum kinetic energy of the emitted electrons:',
 '[{"text":"Stays the same","isCorrect":false},{"text":"Exactly doubles","isCorrect":false},{"text":"Increases, but does not necessarily double","isCorrect":true},{"text":"Decreases","isCorrect":false}]'::jsonb,
 null, 'KE_max = hf - W. Doubling f increases hf by more than the work function subtracts proportionally, so KE_max increases but not exactly by a factor of 2, since W stays fixed.'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'mcq',
 'Regarding the Bohr model of the hydrogen atom, which of the following statement(s) is/are TRUE? (A) The angular momentum of the electron in the nth orbit is $\frac{nh}{2\pi}$. (B) The radius of the nth orbit is proportional to $n$. (C) The energy of the electron in the nth orbit is proportional to $-\frac{1}{n^2}$. (D) The speed of the electron in the nth orbit is proportional to $n$.',
 '[{"text":"(A) Angular momentum is nh/2pi","isCorrect":true},{"text":"(B) Radius proportional to n","isCorrect":false},{"text":"(C) Energy proportional to -1/n^2","isCorrect":true},{"text":"(D) Speed proportional to n","isCorrect":false}]'::jsonb,
 null, 'Bohr''s postulate directly gives angular momentum = nh/2pi (A true). Radius is proportional to n^2, not n (B false). Energy is proportional to -1/n^2 (C true). Speed is proportional to 1/n, not n (D false).'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'numerical',
 'A radioactive sample has decay constant $\lambda = 0.0693$ per minute. Find its half-life (in minutes), using $t_{1/2}=\frac{\ln 2}{\lambda}$ (take $\ln 2 = 0.693$).',
 null, '10', 't(1/2) = 0.693 / 0.0693 = 10 minutes.'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'descriptive',
 'Explain what "binding energy per nucleon" means and why it first increases then decreases across the periodic table.',
 null, null, 'Binding energy per nucleon is the average energy needed to remove one nucleon from a nucleus -- it measures nuclear stability. It rises for light nuclei as more nucleons bind together (peaking near iron), then falls for heavy nuclei because long-range Coulomb repulsion between protons grows faster than the short-range strong force holding the nucleus together.'),

-- Physics: Heat and Thermodynamics
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'In an adiabatic process for an ideal gas, which of the following quantities is zero throughout the process?',
 '[{"text":"Change in temperature","isCorrect":false},{"text":"Change in internal energy","isCorrect":false},{"text":"Heat exchanged with surroundings","isCorrect":true},{"text":"Work done","isCorrect":false}]'::jsonb,
 null, 'An adiabatic process is defined by Q = 0 throughout -- no heat is exchanged with the surroundings, even though temperature, internal energy, and work done can all change.'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'hard', 'mcq',
 'For an ideal gas undergoing an isothermal expansion, which of the following statement(s) is/are TRUE? (A) Internal energy remains constant. (B) The gas does positive work on the surroundings. (C) Heat is released by the gas. (D) $PV$ remains constant.',
 '[{"text":"(A) Internal energy constant","isCorrect":true},{"text":"(B) Gas does positive work","isCorrect":true},{"text":"(C) Heat is released","isCorrect":false},{"text":"(D) PV remains constant","isCorrect":true}]'::jsonb,
 null, 'For an ideal gas, internal energy depends only on temperature, so at constant T, dU=0 (A true). Expansion means the gas does positive work (B true). Since dU=0, Q=W>0, meaning heat is absorbed, not released (C false). Isothermal condition for an ideal gas means PV=constant (D true).'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'hard', 'numerical',
 'An ideal monoatomic gas ($n=2$ mol, $R=8.31\,J/mol\,K$) expands adiabatically and its temperature drops by $100$ K. Find the magnitude of the work done by the gas (in J), using $W=nC_v\Delta T$ with $C_v=\frac{3}{2}R$ (nearest whole number).',
 null, '2493', 'C_v = 1.5 * 8.31 = 12.465 J/mol.K. W = 2 * 12.465 * 100 = 2493 J.'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'medium', 'descriptive',
 'Explain the concept of entropy as a measure of disorder, and state why the entropy of the universe tends to increase.',
 null, null, 'Entropy measures the number of microscopic arrangements consistent with a system''s macroscopic state -- higher entropy means more possible arrangements, i.e. more disorder. The universe''s entropy tends to increase because spontaneous, real (irreversible) processes always move toward more probable, higher-entropy states, per the second law of thermodynamics.'),

-- Physics: Optics
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'medium', 'mcq',
 'The refractive index of water is $\frac{4}{3}$. Find the critical angle for light travelling from water to air (given $\sin^{-1}(0.75) \approx 48.6^\circ$).',
 '[{"text":"30 degrees","isCorrect":false},{"text":"41.8 degrees","isCorrect":false},{"text":"48.6 degrees","isCorrect":true},{"text":"60 degrees","isCorrect":false}]'::jsonb,
 null, 'Critical angle = sin^-1(1/n) = sin^-1(3/4) = sin^-1(0.75) is approximately 48.6 degrees.'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'medium', 'mcq',
 'A concave mirror forms an image of an object placed between its focus and its pole. Which of the following statement(s) is/are TRUE about this image? (A) It is virtual. (B) It is erect. (C) It is magnified. (D) It is formed behind the mirror.',
 '[{"text":"(A) Virtual","isCorrect":true},{"text":"(B) Erect","isCorrect":true},{"text":"(C) Magnified","isCorrect":true},{"text":"(D) Formed behind the mirror","isCorrect":true}]'::jsonb,
 null, 'For an object placed between the pole and focus of a concave mirror, the image formed is virtual, erect, magnified, and located behind the mirror -- all four statements are true for this specific case.'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'medium', 'numerical',
 'Light passes from a medium of refractive index $1.5$ into another of index $1.2$ at an angle where $\sin\theta_1 = 0.6$. Find $\sin\theta_2$ using Snell''s law $n_1\sin\theta_1=n_2\sin\theta_2$ (as a decimal).',
 null, '0.75', '1.5 * 0.6 = 1.2 * sin(theta2), so sin(theta2) = 0.9 / 1.2 = 0.75.'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'medium', 'descriptive',
 'Explain why the sky appears blue during the day, referencing the relevant scattering phenomenon.',
 null, null, 'Sunlight is scattered by gas molecules in the atmosphere via Rayleigh scattering, whose intensity is proportional to 1/(wavelength)^4. Since blue light has a shorter wavelength than red, it scatters far more strongly in all directions, making the sky appear blue.'),

-- Physics: Waves and Oscillations
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'mcq',
 'A mass-spring system has spring constant $k=200$ N/m and mass $m=2$ kg. Find its angular frequency $\omega$ (in rad/s), using $\omega=\sqrt{k/m}$.',
 '[{"text":"5 rad/s","isCorrect":false},{"text":"10 rad/s","isCorrect":true},{"text":"20 rad/s","isCorrect":false},{"text":"100 rad/s","isCorrect":false}]'::jsonb,
 null, 'omega = sqrt(200/2) = sqrt(100) = 10 rad/s.'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'hard', 'mcq',
 'A stretched string, fixed at both ends, vibrates in its 3rd harmonic. Which of the following statement(s) is/are TRUE? (A) There are 3 nodes and 4 antinodes. (B) The frequency is 3 times the fundamental frequency. (C) The wavelength is $\frac{2L}{3}$, where $L$ is the string length. (D) The string forms 3 full loops.',
 '[{"text":"(A) 3 nodes, 4 antinodes","isCorrect":false},{"text":"(B) Frequency is 3x fundamental","isCorrect":true},{"text":"(C) Wavelength is 2L/3","isCorrect":true},{"text":"(D) 3 full loops","isCorrect":true}]'::jsonb,
 null, 'The 3rd harmonic actually has 4 nodes and 3 antinodes, not 3 nodes and 4 antinodes (A false). Its frequency is 3 times the fundamental (B true), its wavelength is 2L/3 (C true), and the string forms exactly 3 loops (D true).'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'numerical',
 'Two coherent sources produce waves of wavelength $\lambda=0.5$ m. Find the path difference (in m) needed for 2nd-order constructive interference (path difference $=2\lambda$).',
 null, '1', 'Path difference = 2 * 0.5 = 1 m.'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'descriptive',
 'Explain the Doppler effect and state whether the observed frequency increases or decreases when a source moves away from a stationary observer.',
 null, null, 'The Doppler effect is the change in observed wave frequency due to relative motion between source and observer. When a source moves away from a stationary observer, the observed frequency decreases (the sound appears lower-pitched).'),

-- Physics: Properties of Matter and Fluids
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'easy', 'mcq',
 'Bernoulli''s equation for a flowing fluid is a statement of conservation of which physical quantity?',
 '[{"text":"Momentum","isCorrect":false},{"text":"Energy","isCorrect":true},{"text":"Mass","isCorrect":false},{"text":"Charge","isCorrect":false}]'::jsonb,
 null, 'Bernoulli''s equation expresses conservation of mechanical energy per unit volume along a streamline.'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'medium', 'mcq',
 'An incompressible, non-viscous fluid flows steadily through a horizontal pipe of varying cross-section. Which of the following statement(s) is/are TRUE? (A) Where the pipe narrows, the fluid speed increases. (B) Where the pipe narrows, the pressure increases. (C) The mass flow rate is the same at every cross-section. (D) $Av$ (area times velocity) is constant along the pipe.',
 '[{"text":"(A) Speed increases where pipe narrows","isCorrect":true},{"text":"(B) Pressure increases where pipe narrows","isCorrect":false},{"text":"(C) Mass flow rate is constant","isCorrect":true},{"text":"(D) Av is constant","isCorrect":true}]'::jsonb,
 null, 'The continuity equation Av=constant means speed increases where the pipe narrows (A, D true), and mass flow rate stays the same everywhere (C true). By Bernoulli''s principle, pressure DECREASES where speed increases, not increases (B false).'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'easy', 'numerical',
 'Water flows through a pipe of area $4\,cm^2$ at speed $2$ m/s. Find the speed (in m/s) where the area narrows to $2\,cm^2$, using $A_1v_1=A_2v_2$.',
 null, '4', '4 * 2 = 2 * v2, so v2 = 4 m/s.'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'medium', 'descriptive',
 'Explain what is meant by the "angle of contact" of a liquid with a solid surface, and how it determines whether the liquid wets the surface.',
 null, null, 'The angle of contact is the angle between the tangent to the liquid surface and the solid surface, measured through the liquid, at the point of contact. An angle of contact less than 90 degrees means the liquid wets the surface (e.g. water on glass); greater than 90 degrees means it does not (e.g. mercury on glass).'),

-- Chemistry: Physical Chemistry
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'easy', 'mcq',
 'Find the molarity of a solution containing $4$ g of NaOH (molar mass $40$ g/mol) in $500$ mL of solution.',
 '[{"text":"0.1 M","isCorrect":false},{"text":"0.2 M","isCorrect":true},{"text":"0.5 M","isCorrect":false},{"text":"1 M","isCorrect":false}]'::jsonb,
 null, 'Moles = 4/40 = 0.1 mol. Molarity = 0.1 mol / 0.5 L = 0.2 M.'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'hard', 'mcq',
 'For a reaction at chemical equilibrium, which of the following statement(s) is/are TRUE? (A) The forward and reverse reaction rates are equal. (B) The concentrations of reactants and products are always equal. (C) $\Delta G = 0$ for the reaction at equilibrium. (D) The equilibrium constant $K$ changes with temperature.',
 '[{"text":"(A) Forward and reverse rates equal","isCorrect":true},{"text":"(B) Concentrations always equal","isCorrect":false},{"text":"(C) Delta G = 0","isCorrect":true},{"text":"(D) K changes with temperature","isCorrect":true}]'::jsonb,
 null, 'At equilibrium, forward and reverse rates are equal by definition (A true), but concentrations need not be equal -- only their rates balance (B false). Delta G = 0 at equilibrium (C true), and K is temperature-dependent per the van''t Hoff relation (D true).'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'numerical',
 'For a reaction, $\Delta H = -50$ kJ/mol and $\Delta S = -100$ J/(mol K). Find the temperature (in K) at which $\Delta G = 0$, using $\Delta G=\Delta H-T\Delta S$.',
 null, '500', '0 = -50000 - T*(-100), so T = 50000/100 = 500 K.'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'hard', 'descriptive',
 'State Raoult''s law for an ideal solution and explain what a positive deviation from it indicates about intermolecular forces.',
 null, null, 'Raoult''s law states the partial vapor pressure of a component in an ideal solution equals its mole fraction times its pure vapor pressure. A positive deviation means the solution''s vapor pressure is higher than Raoult''s law predicts, indicating weaker solute-solvent interactions than the solute-solute/solvent-solvent interactions in the pure components.'),

-- Chemistry: Organic Chemistry
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'easy', 'mcq',
 'Which functional group is present in an aldehyde?',
 '[{"text":"-COOH","isCorrect":false},{"text":"-CHO","isCorrect":true},{"text":"-OH","isCorrect":false},{"text":"-NH2","isCorrect":false}]'::jsonb,
 null, 'The aldehyde functional group is -CHO.'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'mcq',
 'Which of the following compound(s) will give a positive Tollens'' test (silver mirror test)? (A) Acetaldehyde ($CH_3CHO$) (B) Acetone ($CH_3COCH_3$) (C) Formic acid ($HCOOH$) (D) Benzaldehyde ($C_6H_5CHO$)',
 '[{"text":"(A) Acetaldehyde","isCorrect":true},{"text":"(B) Acetone","isCorrect":false},{"text":"(C) Formic acid","isCorrect":true},{"text":"(D) Benzaldehyde","isCorrect":true}]'::jsonb,
 null, 'Aldehydes (acetaldehyde, benzaldehyde) are readily oxidized and give a positive Tollens'' test (A, D true). Formic acid has an aldehyde-like hydrogen and also gives a positive test (C true). Ketones like acetone are not oxidized by Tollens'' reagent (B false).'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'numerical',
 'How many degrees of unsaturation does benzene ($C_6H_6$) have, using degrees of unsaturation $=\frac{2C+2-H}{2}$?',
 null, '4', 'Degrees of unsaturation = (2*6+2-6)/2 = 8/2 = 4.'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'descriptive',
 'Explain what is meant by "aromaticity" and state Huckel''s rule for a ring to be aromatic.',
 null, null, 'Aromaticity refers to the special extra stability of certain cyclic, planar, fully conjugated molecules due to delocalized pi electrons. Huckel''s rule states a ring is aromatic if it is planar, fully conjugated, and has 4n+2 pi electrons, where n is a non-negative integer.'),

-- Chemistry: Inorganic Chemistry
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'mcq',
 'Among the following period-3 elements, which has the highest first ionization energy?',
 '[{"text":"Na","isCorrect":false},{"text":"Mg","isCorrect":false},{"text":"Al","isCorrect":false},{"text":"Cl","isCorrect":true}]'::jsonb,
 null, 'Ionization energy generally increases across a period as atomic radius decreases and nuclear charge increases; among these, Cl (closest to a stable noble-gas configuration) has the highest first ionization energy.'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'mcq',
 'Regarding periodic trends across Period 3 (Na to Cl), which of the following statement(s) is/are TRUE? (A) Atomic radius generally decreases from Na to Cl. (B) Electronegativity generally increases from Na to Cl. (C) Metallic character increases from Na to Cl. (D) First ionization energy generally increases from Na to Cl (with some exceptions).',
 '[{"text":"(A) Atomic radius decreases","isCorrect":true},{"text":"(B) Electronegativity increases","isCorrect":true},{"text":"(C) Metallic character increases","isCorrect":false},{"text":"(D) Ionization energy generally increases","isCorrect":true}]'::jsonb,
 null, 'Across a period, atomic radius decreases and electronegativity increases as nuclear charge grows (A, B true). Metallic character DEcreases across a period, not increases (C false). First ionization energy generally increases, with some well-known exceptions (D true).'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'numerical',
 'Find the number of unpaired electrons in $Fe^{3+}$ (Z=26; $Fe^{3+}$ has configuration $[Ar]3d^5$).',
 null, '5', 'A d5 configuration in the free ion is high-spin, with all 5 d-orbitals singly occupied, giving 5 unpaired electrons.'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'descriptive',
 'Explain why transition metal ions are often colored, referencing d-orbital splitting.',
 null, null, 'In transition metal complexes, surrounding ligands split the d-orbitals into different energy levels (crystal field splitting). Electrons can absorb visible light to jump between these split levels, and the observed color is complementary to the wavelength absorbed.'),

-- Mathematics: Algebra
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'easy', 'mcq',
 'If $z = 1 + i$, find $|z|^2$.',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"4","isCorrect":false},{"text":"sqrt(2)","isCorrect":false}]'::jsonb,
 null, '|z|^2 = 1^2 + 1^2 = 2.'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'hard', 'mcq',
 'For a non-zero complex number $z$, let $\arg(z)$ denote the principal argument with $-\pi < \arg(z) \le \pi$. Which of the following statement(s) is/are TRUE? (A) $\arg(\bar{z}) = -\arg(z)$ for any $z$ that is not a negative real number. (B) $\arg(z) + \arg(-z)$ equals $\pi$ or $-\pi$, depending on which half-plane $z$ lies in. (C) $\arg(z_1 z_2) = \arg(z_1) + \arg(z_2)$ always holds exactly, with no exceptions. (D) $\arg(z)$ is always a rational multiple of $\pi$.',
 '[{"text":"(A) arg(conjugate z) = -arg(z)","isCorrect":true},{"text":"(B) arg(z) + arg(-z) = +-pi","isCorrect":true},{"text":"(C) arg(z1 z2) = arg(z1)+arg(z2) always exactly","isCorrect":false},{"text":"(D) arg(z) always a rational multiple of pi","isCorrect":false}]'::jsonb,
 null, 'Reflecting z across the real axis negates its argument (A true, except when z is a negative real, where arg is exactly pi and its own negative is also pi under the principal branch convention used here). Negating z rotates it by pi, landing arg(z)+arg(-z) at +-pi depending on which half-plane z started in (B true). Since arg is restricted to the principal range, arg(z1 z2) can differ from arg(z1)+arg(z2) by a multiple of 2*pi -- it does not always hold exactly (C false). Most complex numbers, such as 2+i, have an argument that is not a rational multiple of pi (D false).'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'easy', 'numerical',
 'If $z=2-3i$, find $z+\bar{z}$ (a real number).',
 null, '4', 'z + z-conjugate = 2*Re(z) = 2*2 = 4.'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'descriptive',
 'Explain what the principal argument of a complex number represents geometrically, and state its range.',
 null, null, 'The principal argument of z = x+iy is the angle that the line from the origin to the point (x,y) makes with the positive real axis, measured counterclockwise. Its principal value is conventionally restricted to the range (-pi, pi].'),

-- Mathematics: Calculus
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'mcq',
 'Find $\frac{d}{dx}\left(\ln(x^2+1)\right)$.',
 '[{"text":"1/(x^2+1)","isCorrect":false},{"text":"2x/(x^2+1)","isCorrect":true},{"text":"x/(x^2+1)","isCorrect":false},{"text":"2x ln(x^2+1)","isCorrect":false}]'::jsonb,
 null, 'By the chain rule, d/dx[ln(u)] = u''/u with u=x^2+1, u''=2x, giving 2x/(x^2+1).'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'hard', 'mcq',
 'Let $f(x) = x^3-3x$. Which of the following statement(s) is/are TRUE? (A) $f$ has a local maximum at $x=-1$. (B) $f$ has a local minimum at $x=1$. (C) $f$ is increasing on the interval $(-1,1)$. (D) $f(0)=0$.',
 '[{"text":"(A) Local maximum at x=-1","isCorrect":true},{"text":"(B) Local minimum at x=1","isCorrect":true},{"text":"(C) Increasing on (-1,1)","isCorrect":false},{"text":"(D) f(0)=0","isCorrect":true}]'::jsonb,
 null, 'f''(x)=3x^2-3=0 at x=+-1. f''''(-1)=-6<0 gives a local max at x=-1 (A true); f''''(1)=6>0 gives a local min at x=1 (B true). Since f''(x)<0 on (-1,1), f is actually DEcreasing there, not increasing (C false). f(0)=0-0=0 (D true).'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'numerical',
 'Evaluate $\int_1^2 \frac{1}{x}\,dx$. It equals $\ln(k)$ for some integer $k$ -- report just $k$.',
 null, '2', 'Integral of 1/x from 1 to 2 is ln(2) - ln(1) = ln(2), so k=2.'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'descriptive',
 'State the Mean Value Theorem and explain its geometric interpretation.',
 null, null, 'If f is continuous on [a,b] and differentiable on (a,b), the Mean Value Theorem guarantees some c in (a,b) where f''(c) equals the average rate of change (f(b)-f(a))/(b-a). Geometrically, there is a point where the tangent line is parallel to the secant line joining the curve''s endpoints.'),

-- Mathematics: Coordinate Geometry
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'easy', 'mcq',
 'Find the equation of the line through $(1,2)$ with slope $3$.',
 '[{"text":"y = 3x - 1","isCorrect":true},{"text":"y = 3x + 1","isCorrect":false},{"text":"y = x - 1","isCorrect":false},{"text":"y = 3x - 2","isCorrect":false}]'::jsonb,
 null, 'y - 2 = 3(x-1) simplifies to y = 3x - 1.'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'hard', 'mcq',
 'For the circle $x^2+y^2-4x-6y+9=0$, which of the following statement(s) is/are TRUE? (A) The center is $(2,3)$. (B) The radius is $2$. (C) The circle passes through the origin. (D) The circle is tangent to the x-axis.',
 '[{"text":"(A) Center is (2,3)","isCorrect":true},{"text":"(B) Radius is 2","isCorrect":true},{"text":"(C) Passes through origin","isCorrect":false},{"text":"(D) Tangent to x-axis","isCorrect":false}]'::jsonb,
 null, 'Completing the square: (x-2)^2+(y-3)^2 = 4+9-9 = 4, giving center (2,3) and radius 2 (A, B true). The distance from the origin to the center is sqrt(13), not equal to the radius, so it does not pass through the origin (C false). The distance from the center to the x-axis is 3, not equal to the radius 2, so it is not tangent to the x-axis (D false).'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'numerical',
 'Find the distance from $(3,4)$ to the line $3x+4y-10=0$, using $d=\frac{|3(3)+4(4)-10|}{\sqrt{3^2+4^2}}$.',
 null, '3', '|9+16-10|/5 = 15/5 = 3.'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'hard', 'descriptive',
 'Derive the general condition for a line $y=mx+c$ to be tangent to the circle $x^2+y^2=r^2$.',
 null, null, 'A line y=mx+c is tangent to the circle x^2+y^2=r^2 exactly when the perpendicular distance from the origin to the line equals the radius: |c|/sqrt(1+m^2) = r, equivalently c^2 = r^2(1+m^2).'),

-- Mathematics: Trigonometry
('JEE Main', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'Find the value of $\tan(45^\circ) + \sin(90^\circ)$.',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"sqrt(2)","isCorrect":false}]'::jsonb,
 null, 'tan(45) = 1 and sin(90) = 1, so their sum is 2.'),
('JEE Main', 'Mathematics', 'Trigonometry', 'medium', 'mcq',
 'Which of the following statement(s) is/are TRUE about $\theta=\frac{\pi}{3}$? (A) $\sin\theta=\frac{\sqrt{3}}{2}$. (B) $\cos\theta=\frac{1}{2}$. (C) $\tan\theta=\sqrt{3}$. (D) $\theta=90^\circ$.',
 '[{"text":"(A) sin(theta) = sqrt(3)/2","isCorrect":true},{"text":"(B) cos(theta) = 1/2","isCorrect":true},{"text":"(C) tan(theta) = sqrt(3)","isCorrect":true},{"text":"(D) theta = 90 degrees","isCorrect":false}]'::jsonb,
 null, 'pi/3 radians equals 60 degrees, where sin=sqrt(3)/2, cos=1/2, and tan=sqrt(3) are all standard values (A, B, C true). pi/3 is 60 degrees, not 90 degrees (D false).'),
('JEE Main', 'Mathematics', 'Trigonometry', 'easy', 'numerical',
 'Solve for $x$ in $[0^\circ,90^\circ]$: $2\sin x = 1$. Give $x$ in degrees.',
 null, '30', 'sin(x) = 0.5, so x = 30 degrees.'),
('JEE Main', 'Mathematics', 'Trigonometry', 'medium', 'descriptive',
 'Derive the formula for $\cos(A-B)$ and state one use of this identity.',
 null, null, 'cos(A-B) = cos(A)cos(B) + sin(A)sin(B), derived from the dot product of two unit vectors at angles A and B on the unit circle. It is used to compute exact trigonometric values of angle differences and to simplify trigonometric expressions.'),

-- Mathematics: Vectors and 3D Geometry
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'mcq',
 'Find the angle between $\vec{a}=(1,0,0)$ and $\vec{b}=(0,1,0)$.',
 '[{"text":"0 degrees","isCorrect":false},{"text":"45 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":true},{"text":"180 degrees","isCorrect":false}]'::jsonb,
 null, 'a.b = 0, so cos(theta)=0 and theta=90 degrees.'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'hard', 'mcq',
 'Let $\vec{a}=(1,2,2)$. Which of the following statement(s) is/are TRUE? (A) $|\vec{a}|=3$. (B) The unit vector along $\vec{a}$ is $\left(\frac{1}{3},\frac{2}{3},\frac{2}{3}\right)$. (C) $\vec{a}$ is perpendicular to $(2,-1,0)$. (D) $\vec{a}$ is a unit vector.',
 '[{"text":"(A) |a| = 3","isCorrect":true},{"text":"(B) Unit vector is (1/3,2/3,2/3)","isCorrect":true},{"text":"(C) Perpendicular to (2,-1,0)","isCorrect":true},{"text":"(D) a is a unit vector","isCorrect":false}]'::jsonb,
 null, '|a| = sqrt(1+4+4) = 3 (A true), so the unit vector is a/3 = (1/3,2/3,2/3) (B true). The dot product with (2,-1,0) is 2-2+0=0, so they are perpendicular (C true). Since |a|=3, not 1, a is not itself a unit vector (D false).'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'numerical',
 'Find the scalar triple product $[\vec{a}\,\vec{b}\,\vec{c}]$ for $\vec{a}=(1,0,0)$, $\vec{b}=(0,1,0)$, $\vec{c}=(0,0,1)$ (an integer).',
 null, '1', 'This is the determinant of the identity matrix, which equals 1.'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'descriptive',
 'Explain what the scalar triple product $[\vec{a}\,\vec{b}\,\vec{c}]$ represents geometrically.',
 null, null, 'The scalar triple product a.(b x c) equals the signed volume of the parallelepiped formed by the three vectors as edges from a common vertex. If it equals zero, the three vectors are coplanar.'),

-- Mathematics: Statistics and Probability
('JEE Main', 'Mathematics', 'Statistics and Probability', 'easy', 'mcq',
 'Two dice are rolled. Find the probability that the sum is $7$.',
 '[{"text":"1/6","isCorrect":true},{"text":"1/12","isCorrect":false},{"text":"1/36","isCorrect":false},{"text":"1/4","isCorrect":false}]'::jsonb,
 null, '6 out of 36 outcomes sum to 7, giving probability 6/36 = 1/6.'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'medium', 'mcq',
 'A bag contains 3 red and 2 blue balls. One ball is drawn at random. Which of the following statement(s) is/are TRUE? (A) $P(\text{red}) = \frac{3}{5}$. (B) $P(\text{blue}) = \frac{2}{5}$. (C) $P(\text{red}) + P(\text{blue}) = 1$. (D) $P(\text{red}) = P(\text{blue})$.',
 '[{"text":"(A) P(red) = 3/5","isCorrect":true},{"text":"(B) P(blue) = 2/5","isCorrect":true},{"text":"(C) P(red)+P(blue)=1","isCorrect":true},{"text":"(D) P(red)=P(blue)","isCorrect":false}]'::jsonb,
 null, 'There are 5 balls total: P(red)=3/5 and P(blue)=2/5 (A, B true), and since red/blue are the only outcomes, they sum to 1 (C true). Since 3/5 does not equal 2/5, the two probabilities are not equal (D false).'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'easy', 'numerical',
 'The variance of a data set is $16$. Find its standard deviation.',
 null, '4', 'Standard deviation = sqrt(variance) = sqrt(16) = 4.'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'medium', 'descriptive',
 'Explain the difference between independent and mutually exclusive events, using an example of each.',
 null, null, 'Two events are independent if one occurring does not change the probability of the other (e.g. two separate coin flips). Two events are mutually exclusive if they cannot both occur at once (e.g. rolling a 2 and rolling a 5 on the same single die roll) -- mutually exclusive events with nonzero probabilities are actually always dependent, since one occurring makes the other''s probability zero.');
