-- supabase/sql/exam_question_bank_upsc_cse_set1.sql
--
-- First curated question-bank batch for 'UPSC CSE (IAS)' (see exam_patterns_upsc_cse.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed. Models Prelims only (both GS Paper I and CSAT Paper II) -- Mains/Interview are not
-- MCQ-based and don't fit this schema.
--
-- Like NEET/BITSAT/MHT-CET/WBJEE/VITEEE, every row here is format='mcq' with a single
-- isCorrect:true option (100% single-best-response, matching the real exam). The "Current Affairs"
-- chapter deliberately sticks to durable, evergreen institutional facts (headquarters, founding
-- years, regional groupings) rather than time-sensitive news, since a static question bank would
-- otherwise go stale. 16 chapters (10 GS Paper I, 6 CSAT Paper II) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_upsc_cse.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- GS Paper I: Ancient Indian History
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'medium', 'mcq',
 'The Indus Valley Civilization site of Mohenjo-daro is located in present-day:',
 '[{"text":"India","isCorrect":false},{"text":"Pakistan","isCorrect":true},{"text":"Afghanistan","isCorrect":false},{"text":"Bangladesh","isCorrect":false}]'::jsonb,
 null, 'Mohenjo-daro, one of the largest Indus Valley Civilization cities, is located in the Sindh province of present-day Pakistan, on the banks of the Indus river.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'medium', 'mcq',
 'Which Mauryan ruler embraced Buddhism after the Kalinga war?',
 '[{"text":"Chandragupta Maurya","isCorrect":false},{"text":"Bindusara","isCorrect":false},{"text":"Ashoka","isCorrect":true},{"text":"Brihadratha","isCorrect":false}]'::jsonb,
 null, 'Emperor Ashoka embraced Buddhism after witnessing the devastation of the Kalinga war, subsequently promoting non-violence (ahimsa) and Dhamma across his empire.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'easy', 'mcq',
 'The rock-cut caves of Ajanta are renowned for their:',
 '[{"text":"Buddhist paintings and sculptures","isCorrect":true},{"text":"Jain temple architecture only","isCorrect":false},{"text":"Islamic calligraphy","isCorrect":false},{"text":"Sikh gurdwaras","isCorrect":false}]'::jsonb,
 null, 'The Ajanta Caves in Maharashtra are a series of Buddhist rock-cut monuments famous for their exquisite paintings and sculptures dating back over two millennia.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'easy', 'mcq',
 'Which Veda is considered the oldest and consists primarily of hymns?',
 '[{"text":"Yajurveda","isCorrect":false},{"text":"Samaveda","isCorrect":false},{"text":"Rigveda","isCorrect":true},{"text":"Atharvaveda","isCorrect":false}]'::jsonb,
 null, 'The Rigveda, a collection of hymns dedicated to various deities, is considered the oldest of the four Vedas.'),

-- GS Paper I: Medieval Indian History
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'Who founded the Delhi Sultanate?',
 '[{"text":"Qutb-ud-din Aibak","isCorrect":true},{"text":"Muhammad Ghori","isCorrect":false},{"text":"Iltutmish","isCorrect":false},{"text":"Balban","isCorrect":false}]'::jsonb,
 null, 'Qutb-ud-din Aibak, a former general of Muhammad Ghori, founded the Delhi Sultanate and the Mamluk (Slave) dynasty in 1206.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'The First Battle of Panipat (1526) was fought between Babur and:',
 '[{"text":"Ibrahim Lodi","isCorrect":true},{"text":"Rana Sanga","isCorrect":false},{"text":"Sher Shah Suri","isCorrect":false},{"text":"Hemu","isCorrect":false}]'::jsonb,
 null, 'The First Battle of Panipat (1526) was fought between Babur and Ibrahim Lodi, the last ruler of the Delhi Sultanate, marking the beginning of Mughal rule in India.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'easy', 'mcq',
 'Which Mughal emperor commissioned the construction of the Taj Mahal?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Jahangir","isCorrect":false},{"text":"Shah Jahan","isCorrect":true},{"text":"Aurangzeb","isCorrect":false}]'::jsonb,
 null, 'Shah Jahan commissioned the Taj Mahal in memory of his wife Mumtaz Mahal, completing this iconic mausoleum in Agra.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'The Bhakti movement primarily emphasized:',
 '[{"text":"Ritualistic sacrifices to please the gods","isCorrect":false},{"text":"Personal devotion to a god, transcending caste distinctions","isCorrect":true},{"text":"Strict adherence to Sanskrit scriptures alone","isCorrect":false},{"text":"Military conquest in the name of religion","isCorrect":false}]'::jsonb,
 null, 'The Bhakti movement emphasized a personal, devotional relationship with god, often conducted in local vernacular languages and cutting across caste barriers.'),

-- GS Paper I: Modern Indian History and Freedom Struggle
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'easy', 'mcq',
 'The Indian National Congress was founded in the year:',
 '[{"text":"1857","isCorrect":false},{"text":"1885","isCorrect":true},{"text":"1905","isCorrect":false},{"text":"1919","isCorrect":false}]'::jsonb,
 null, 'The Indian National Congress was founded in 1885 by Allan Octavian Hume, with its first session held in Bombay.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'The Quit India Movement was launched in the year:',
 '[{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":true},{"text":"1947","isCorrect":false},{"text":"1920","isCorrect":false}]'::jsonb,
 null, 'The Quit India Movement, calling for an end to British rule, was launched by Mahatma Gandhi in August 1942.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'Who gave the famous slogan "Swaraj is my birthright and I shall have it"?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"Bal Gangadhar Tilak","isCorrect":true},{"text":"Subhas Chandra Bose","isCorrect":false},{"text":"Bhagat Singh","isCorrect":false}]'::jsonb,
 null, 'Bal Gangadhar Tilak famously declared "Swaraj is my birthright and I shall have it", becoming a rallying cry of the Indian independence movement.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'easy', 'mcq',
 'The Jallianwala Bagh massacre of 1919 took place in which city?',
 '[{"text":"Lahore","isCorrect":false},{"text":"Amritsar","isCorrect":true},{"text":"Delhi","isCorrect":false},{"text":"Chandigarh","isCorrect":false}]'::jsonb,
 null, 'The Jallianwala Bagh massacre occurred in Amritsar, Punjab, in April 1919, when British troops under General Dyer fired on an unarmed gathering.'),

-- GS Paper I: Indian Art and Culture
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'medium', 'mcq',
 'Bharatanatyam, one of India''s classical dance forms, originated in which state?',
 '[{"text":"Kerala","isCorrect":false},{"text":"Tamil Nadu","isCorrect":true},{"text":"Odisha","isCorrect":false},{"text":"Andhra Pradesh","isCorrect":false}]'::jsonb,
 null, 'Bharatanatyam is a classical dance form that originated in the temples of Tamil Nadu, traditionally performed as a form of worship.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'medium', 'mcq',
 'The Khajuraho temples, known for their intricate carvings, are located in which state?',
 '[{"text":"Madhya Pradesh","isCorrect":true},{"text":"Rajasthan","isCorrect":false},{"text":"Uttar Pradesh","isCorrect":false},{"text":"Gujarat","isCorrect":false}]'::jsonb,
 null, 'The Khajuraho group of temples, a UNESCO World Heritage Site known for their intricate sculptural artistry, is located in Madhya Pradesh.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'easy', 'mcq',
 'Pandit Ravi Shankar was internationally renowned as a master of which musical instrument?',
 '[{"text":"Tabla","isCorrect":false},{"text":"Sitar","isCorrect":true},{"text":"Flute","isCorrect":false},{"text":"Sarod","isCorrect":false}]'::jsonb,
 null, 'Pandit Ravi Shankar was a world-renowned sitar virtuoso, credited with popularizing Indian classical music globally.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'hard', 'mcq',
 'Sangam literature is a body of classical works primarily associated with which language?',
 '[{"text":"Sanskrit","isCorrect":false},{"text":"Tamil","isCorrect":true},{"text":"Telugu","isCorrect":false},{"text":"Pali","isCorrect":false}]'::jsonb,
 null, 'Sangam literature refers to the earliest known corpus of classical Tamil literature, composed roughly between 300 BCE and 300 CE.'),

-- GS Paper I: Indian and World Geography
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'The longest river flowing entirely within India is the:',
 '[{"text":"Yamuna","isCorrect":false},{"text":"Ganga","isCorrect":true},{"text":"Brahmaputra","isCorrect":false},{"text":"Godavari","isCorrect":false}]'::jsonb,
 null, 'The Ganga, at approximately 2,525 km, is the longest river in India.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'Mount Kilimanjaro, the highest peak in Africa, is located in which country?',
 '[{"text":"Kenya","isCorrect":false},{"text":"Tanzania","isCorrect":true},{"text":"Ethiopia","isCorrect":false},{"text":"Uganda","isCorrect":false}]'::jsonb,
 null, 'Mount Kilimanjaro, Africa''s highest peak at about 5,895 meters, is located in Tanzania.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'The Tropic of Cancer passes through how many Indian states?',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":true},{"text":"10","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'easy', 'mcq',
 'Which type of soil, rich in iron and known for its moisture retention, is most suitable for cotton cultivation in India?',
 '[{"text":"Alluvial soil","isCorrect":false},{"text":"Black (regur) soil","isCorrect":true},{"text":"Laterite soil","isCorrect":false},{"text":"Desert soil","isCorrect":false}]'::jsonb,
 null, 'Black soil (regur soil), formed from volcanic (Deccan trap) rock and rich in moisture-retaining properties, is especially suitable for cotton cultivation, particularly across Maharashtra and Gujarat.'),

-- GS Paper I: Indian Polity and Governance
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'The Constitution of India was adopted by the Constituent Assembly on:',
 '[{"text":"15 August 1947","isCorrect":false},{"text":"26 November 1949","isCorrect":true},{"text":"26 January 1950","isCorrect":false},{"text":"2 October 1949","isCorrect":false}]'::jsonb,
 null, 'The Constituent Assembly adopted the Constitution of India on 26 November 1949, which came into effect on 26 January 1950 (Republic Day).'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'The Fundamental Rights of Indian citizens are enshrined in which part of the Constitution?',
 '[{"text":"Part II","isCorrect":false},{"text":"Part III","isCorrect":true},{"text":"Part IV","isCorrect":false},{"text":"Part V","isCorrect":false}]'::jsonb,
 null, 'Fundamental Rights are enumerated in Part III of the Indian Constitution, covering rights like equality, freedom, and constitutional remedies.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'easy', 'mcq',
 'Who serves as the ceremonial (constitutional) head of the Indian state?',
 '[{"text":"The Prime Minister","isCorrect":false},{"text":"The President","isCorrect":true},{"text":"The Chief Justice of India","isCorrect":false},{"text":"The Speaker of the Lok Sabha","isCorrect":false}]'::jsonb,
 null, 'The President of India is the constitutional (ceremonial) head of state, while the Prime Minister is the head of government and holds real executive authority.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'The minimum age required to become a member of the Lok Sabha is:',
 '[{"text":"21 years","isCorrect":false},{"text":"25 years","isCorrect":true},{"text":"30 years","isCorrect":false},{"text":"35 years","isCorrect":false}]'::jsonb,
 null, 'A candidate must be at least 25 years old to be eligible for membership in the Lok Sabha (the minimum age for the Rajya Sabha is 30 years).'),

-- GS Paper I: Indian Economy
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'The Reserve Bank of India (RBI) was established in the year:',
 '[{"text":"1935","isCorrect":true},{"text":"1947","isCorrect":false},{"text":"1950","isCorrect":false},{"text":"1969","isCorrect":false}]'::jsonb,
 null, 'The Reserve Bank of India was established in 1935 under the Reserve Bank of India Act, 1934, and was nationalized in 1949.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'easy', 'mcq',
 'NITI Aayog replaced which earlier planning body of the Government of India?',
 '[{"text":"Finance Commission","isCorrect":false},{"text":"Planning Commission","isCorrect":true},{"text":"National Development Council","isCorrect":false},{"text":"Election Commission","isCorrect":false}]'::jsonb,
 null, 'NITI Aayog (National Institution for Transforming India) was established in 2015, replacing the Planning Commission as India''s premier policy think tank.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'The Goods and Services Tax (GST) in India is an example of which kind of tax?',
 '[{"text":"Direct tax","isCorrect":false},{"text":"Indirect tax","isCorrect":true},{"text":"Wealth tax","isCorrect":false},{"text":"Corporate tax","isCorrect":false}]'::jsonb,
 null, 'GST is levied on the supply of goods and services and is passed on to the consumer, making it a form of indirect tax, unlike income tax which is direct.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'The term "Green Revolution" in India is primarily associated with a significant increase in the production of:',
 '[{"text":"Foodgrains (especially wheat and rice)","isCorrect":true},{"text":"Textiles","isCorrect":false},{"text":"Dairy products","isCorrect":false},{"text":"Automobiles","isCorrect":false}]'::jsonb,
 null, 'The Green Revolution, starting in the mid-1960s, involved the introduction of high-yielding variety seeds, fertilizers, and irrigation, dramatically boosting foodgrain (especially wheat and rice) production.'),

-- GS Paper I: Environment and Ecology
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'The Western Ghats of India are internationally recognized as a:',
 '[{"text":"UNESCO World Heritage Site and biodiversity hotspot","isCorrect":true},{"text":"Desert biome","isCorrect":false},{"text":"Man-made forest","isCorrect":false},{"text":"Coral reef system","isCorrect":false}]'::jsonb,
 null, 'The Western Ghats are recognized as one of the world''s biodiversity hotspots and are inscribed as a UNESCO World Heritage Site for their exceptional biological diversity.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'Which international agreement primarily aims to limit global warming to well below 2 degrees Celsius above pre-industrial levels?',
 '[{"text":"Kyoto Protocol","isCorrect":false},{"text":"Paris Agreement","isCorrect":true},{"text":"Montreal Protocol","isCorrect":false},{"text":"Basel Convention","isCorrect":false}]'::jsonb,
 null, 'The Paris Agreement (2015), adopted under the UNFCCC, aims to limit global temperature rise to well below 2 degrees Celsius, pursuing efforts to limit it to 1.5 degrees.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'The Ramsar Convention is an international treaty related to the conservation of:',
 '[{"text":"Forests","isCorrect":false},{"text":"Wetlands","isCorrect":true},{"text":"Coral reefs only","isCorrect":false},{"text":"Endangered mammals only","isCorrect":false}]'::jsonb,
 null, 'The Ramsar Convention, signed in Ramsar, Iran in 1971, is an international treaty for the conservation and sustainable use of wetlands.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'easy', 'mcq',
 'Project Tiger, aimed at conserving India''s tiger population, was launched in the year:',
 '[{"text":"1973","isCorrect":true},{"text":"1980","isCorrect":false},{"text":"1991","isCorrect":false},{"text":"2000","isCorrect":false}]'::jsonb,
 null, 'Project Tiger was launched by the Government of India in 1973 to protect the country''s dwindling tiger population and their habitats.'),

-- GS Paper I: General Science and Technology
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'The SI unit of electric current is the:',
 '[{"text":"Volt","isCorrect":false},{"text":"Ampere","isCorrect":true},{"text":"Ohm","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'Electric current is measured in amperes (A), one of the seven base SI units.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'A deficiency of Vitamin C in the human diet causes which disease?',
 '[{"text":"Rickets","isCorrect":false},{"text":"Scurvy","isCorrect":true},{"text":"Night blindness","isCorrect":false},{"text":"Beriberi","isCorrect":false}]'::jsonb,
 null, 'Vitamin C deficiency causes scurvy, characterized by bleeding gums, joint pain, and poor wound healing.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'ISRO''s Chandrayaan missions are primarily aimed at exploring:',
 '[{"text":"Mars","isCorrect":false},{"text":"The Moon","isCorrect":true},{"text":"Venus","isCorrect":false},{"text":"The Sun","isCorrect":false}]'::jsonb,
 null, 'The Chandrayaan series of missions, run by the Indian Space Research Organisation (ISRO), are dedicated to lunar exploration.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'The pH value of pure water at 25 degrees Celsius is:',
 '[{"text":"0","isCorrect":false},{"text":"7","isCorrect":true},{"text":"14","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'Pure water has an equal concentration of H+ and OH- ions, giving it a neutral pH of 7 at 25 degrees Celsius.'),

-- GS Paper I: Current Affairs and International Relations
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'The headquarters of the United Nations is located in:',
 '[{"text":"Geneva","isCorrect":false},{"text":"New York","isCorrect":true},{"text":"Vienna","isCorrect":false},{"text":"The Hague","isCorrect":false}]'::jsonb,
 null, 'The United Nations headquarters is located in New York City, United States, though several UN agencies are headquartered elsewhere, like Geneva and Vienna.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'BRICS, an economic grouping of major emerging economies, originally comprised Brazil, Russia, India, China, and:',
 '[{"text":"South Africa","isCorrect":true},{"text":"Indonesia","isCorrect":false},{"text":"Mexico","isCorrect":false},{"text":"Egypt","isCorrect":false}]'::jsonb,
 null, 'BRICS originally comprised Brazil, Russia, India, China, and South Africa (which joined in 2010), before later expansion to add further member countries.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'The World Health Organization (WHO) has its headquarters in:',
 '[{"text":"Geneva","isCorrect":true},{"text":"New York","isCorrect":false},{"text":"Paris","isCorrect":false},{"text":"Rome","isCorrect":false}]'::jsonb,
 null, 'The World Health Organization, a specialized agency of the United Nations, is headquartered in Geneva, Switzerland.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'easy', 'mcq',
 'India is a founding member of which regional organization, alongside Pakistan, Bangladesh, and other South Asian nations?',
 '[{"text":"ASEAN","isCorrect":false},{"text":"SAARC","isCorrect":true},{"text":"European Union","isCorrect":false},{"text":"African Union","isCorrect":false}]'::jsonb,
 null, 'SAARC (South Asian Association for Regional Cooperation), founded in 1985, includes India, Pakistan, Bangladesh, Nepal, Bhutan, Sri Lanka, Maldives, and Afghanistan.'),

-- CSAT Paper II: Reading Comprehension
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "The success of any organization depends not on individual brilliance but on the ability of its members to work cohesively toward a common goal." According to the passage, organizational success primarily depends on:',
 '[{"text":"Hiring the most individually brilliant employees","isCorrect":false},{"text":"Cohesive teamwork among members toward a shared goal","isCorrect":true},{"text":"Strict top-down management control","isCorrect":false},{"text":"Minimizing the number of employees","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states success depends on members working cohesively toward a common goal, not on individual brilliance alone.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Renewable energy sources, unlike fossil fuels, do not deplete over time, though their availability can be intermittent depending on weather conditions." Which of the following can be correctly inferred from the passage?',
 '[{"text":"Renewable energy sources are always more reliable than fossil fuels","isCorrect":false},{"text":"Renewable energy availability can be inconsistent due to weather","isCorrect":true},{"text":"Fossil fuels never deplete","isCorrect":false},{"text":"Weather conditions have no effect on energy production","isCorrect":false}]'::jsonb,
 null, 'The passage states that renewable sources'' availability "can be intermittent depending on weather conditions", directly supporting the inference about inconsistency due to weather.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'hard', 'mcq',
 'Read the passage: "A democracy thrives not merely on the right to vote, but on an informed electorate capable of holding its representatives accountable." According to the passage, what is central to a thriving democracy?',
 '[{"text":"Frequent elections alone","isCorrect":false},{"text":"An informed and accountable-holding electorate","isCorrect":true},{"text":"A large voting population","isCorrect":false},{"text":"The absence of political parties","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly emphasizes that democracy requires more than voting rights -- it needs an informed electorate that holds representatives accountable.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Economic growth alone does not guarantee human development; equitable distribution of resources is equally important." According to the passage, genuine human development requires:',
 '[{"text":"Economic growth alone","isCorrect":false},{"text":"Both economic growth and equitable resource distribution","isCorrect":true},{"text":"Equitable distribution alone, regardless of growth","isCorrect":false},{"text":"Neither growth nor equitable distribution","isCorrect":false}]'::jsonb,
 null, 'The passage states growth "alone does not guarantee" development and stresses that equitable distribution is "equally important", implying both factors are needed together.'),

-- CSAT Paper II: Logical Reasoning and Analytical Ability
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'medium', 'mcq',
 'Given: "All doctors are scientists" and "All scientists are researchers." Which conclusion logically follows?',
 '[{"text":"All doctors are researchers.","isCorrect":true},{"text":"All researchers are doctors.","isCorrect":false},{"text":"No doctors are researchers.","isCorrect":false},{"text":"Some scientists are not researchers.","isCorrect":false}]'::jsonb,
 null, 'By transitive syllogism, since all doctors are scientists and all scientists are researchers, it necessarily follows that all doctors are researchers.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'easy', 'mcq',
 'Find the next number in the series: 5, 10, 20, 40, ?',
 '[{"text":"60","isCorrect":false},{"text":"80","isCorrect":true},{"text":"50","isCorrect":false},{"text":"100","isCorrect":false}]'::jsonb,
 null, 'Each term is double the previous term, so after 40 the next term is 40*2=80.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'medium', 'mcq',
 'A is the son of B. C is the mother of A. What is the relationship between B and C?',
 '[{"text":"B and C are siblings","isCorrect":false},{"text":"B and C are spouses (husband and wife)","isCorrect":true},{"text":"B is the grandmother of C","isCorrect":false},{"text":"There is no possible relationship","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s son and C is A''s mother, B and C are both parents of A, making them spouses (assuming a standard two-parent family relationship).'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'hard', 'mcq',
 'In a certain code, "BOOK" is written as "CPPL". How is "PAGE" written in the same code?',
 '[{"text":"QBHF","isCorrect":true},{"text":"QBGF","isCorrect":false},{"text":"PBHF","isCorrect":false},{"text":"QAHF","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one position in the alphabet (B to C, O to P, O to P, K to L); applying the same shift to P-A-G-E gives Q-B-H-F.'),

-- CSAT Paper II: Decision Making and Problem Solving
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'You notice a colleague taking sole credit for a project you both worked on, during a team meeting. What is the most appropriate immediate action?',
 '[{"text":"Publicly confront the colleague during the meeting","isCorrect":false},{"text":"Speak to the colleague privately afterward to clarify the facts","isCorrect":true},{"text":"Say nothing and let it go permanently","isCorrect":false},{"text":"Complain to other colleagues informally","isCorrect":false}]'::jsonb,
 null, 'Addressing the issue privately and calmly after the meeting allows for a professional resolution without creating public conflict, which is generally the most constructive first step.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'As a team manager, if two team members have a conflict that is affecting their work, what should you do first?',
 '[{"text":"Immediately transfer one of them to another team","isCorrect":false},{"text":"Listen to both parties separately to understand the issue","isCorrect":true},{"text":"Ignore the conflict since it may resolve itself","isCorrect":false},{"text":"Publicly reprimand both individuals","isCorrect":false}]'::jsonb,
 null, 'Understanding both perspectives individually before taking action ensures a fair, informed resolution, rather than acting on incomplete information.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'Which approach best exemplifies effective decision-making under conditions of uncertainty?',
 '[{"text":"Acting purely on instinct without considering evidence","isCorrect":false},{"text":"Weighing available evidence and potential outcomes before acting","isCorrect":true},{"text":"Delaying every decision indefinitely to avoid risk","isCorrect":false},{"text":"Following whatever the majority prefers, regardless of evidence","isCorrect":false}]'::jsonb,
 null, 'Effective decision-making under uncertainty involves carefully weighing the available evidence and considering likely outcomes, rather than acting purely on instinct or avoiding the decision altogether.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'If you receive credible information suggesting an imminent public safety risk, what is the most appropriate first step?',
 '[{"text":"Report it promptly to the relevant competent authority","isCorrect":true},{"text":"Post about it on social media immediately","isCorrect":false},{"text":"Wait to see if the situation resolves on its own","isCorrect":false},{"text":"Discuss it only with friends and family","isCorrect":false}]'::jsonb,
 null, 'Promptly reporting credible safety risk information to the appropriate authority is the responsible and effective first step, ensuring it can be properly verified and acted upon.'),

-- CSAT Paper II: Basic Numeracy
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 '15% of 200 is:',
 '[{"text":"20","isCorrect":false},{"text":"30","isCorrect":true},{"text":"25","isCorrect":false},{"text":"35","isCorrect":false}]'::jsonb,
 null, '15% of 200 = (15/100)*200 = 30.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 'If a train travels 60 km in 1.5 hours, its average speed is:',
 '[{"text":"30 km/hr","isCorrect":false},{"text":"40 km/hr","isCorrect":true},{"text":"45 km/hr","isCorrect":false},{"text":"90 km/hr","isCorrect":false}]'::jsonb,
 null, 'Speed = distance/time = 60/1.5 = 40 km/hr.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 'The LCM (least common multiple) of 4 and 6 is:',
 '[{"text":"12","isCorrect":true},{"text":"24","isCorrect":false},{"text":"2","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'The multiples of 4 are 4,8,12,16... and of 6 are 6,12,18... the smallest common multiple is 12.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'medium', 'mcq',
 'The smallest positive integer that leaves a remainder of 3 when divided by 5 is:',
 '[{"text":"3","isCorrect":true},{"text":"5","isCorrect":false},{"text":"8","isCorrect":false},{"text":"13","isCorrect":false}]'::jsonb,
 null, '3 divided by 5 gives a quotient of 0 with a remainder of 3, making 3 itself the smallest such positive integer.'),

-- CSAT Paper II: Data Interpretation
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'medium', 'mcq',
 'A company''s expenses are divided as: Salaries 40%, Rent 20%, Utilities 15%, Marketing 15%, Miscellaneous 10%. What percentage is spent on Rent and Utilities combined?',
 '[{"text":"30%","isCorrect":false},{"text":"35%","isCorrect":true},{"text":"40%","isCorrect":false},{"text":"25%","isCorrect":false}]'::jsonb,
 null, 'Rent (20%) + Utilities (15%) = 35% of total expenses.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'medium', 'mcq',
 'If a company''s sales were 100 units in January and 150 units in February, the percentage increase in sales is:',
 '[{"text":"33%","isCorrect":false},{"text":"50%","isCorrect":true},{"text":"66%","isCorrect":false},{"text":"150%","isCorrect":false}]'::jsonb,
 null, 'Percentage increase = (150-100)/100 * 100 = 50%.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'easy', 'mcq',
 'If the average of 5 numbers is 20, what is their total sum?',
 '[{"text":"20","isCorrect":false},{"text":"100","isCorrect":true},{"text":"25","isCorrect":false},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'Sum = average * count = 20*5 = 100.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'medium', 'mcq',
 'A dataset shows five students'' marks: 60, 70, 80, 90, 100. What is the median of this dataset?',
 '[{"text":"70","isCorrect":false},{"text":"80","isCorrect":true},{"text":"90","isCorrect":false},{"text":"75","isCorrect":false}]'::jsonb,
 null, 'When sorted, the middle (third) value of the five numbers (60,70,80,90,100) is 80, making it the median.'),

-- CSAT Paper II: Interpersonal and Communication Skills
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'easy', 'mcq',
 'Active listening primarily involves:',
 '[{"text":"Interrupting frequently to share your own views","isCorrect":false},{"text":"Giving full attention to the speaker and understanding before responding","isCorrect":true},{"text":"Planning your reply while the other person is speaking","isCorrect":false},{"text":"Only listening to what confirms your own opinion","isCorrect":false}]'::jsonb,
 null, 'Active listening means giving the speaker full, undivided attention and genuinely understanding their message before formulating a response.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'medium', 'mcq',
 'In a team setting, the most effective way to resolve a disagreement is generally through:',
 '[{"text":"Avoiding the topic altogether","isCorrect":false},{"text":"Open dialogue and mutual respect for differing viewpoints","isCorrect":true},{"text":"Insisting on one''s own viewpoint without compromise","isCorrect":false},{"text":"Escalating immediately to a higher authority","isCorrect":false}]'::jsonb,
 null, 'Open, respectful dialogue that considers differing viewpoints is generally the most effective and sustainable way to resolve team disagreements.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'medium', 'mcq',
 'Which of the following best characterizes emotional intelligence?',
 '[{"text":"The ability to solve complex mathematical problems","isCorrect":false},{"text":"The ability to recognize and manage one''s own emotions and those of others","isCorrect":true},{"text":"The ability to memorize large amounts of information","isCorrect":false},{"text":"The ability to work without any social interaction","isCorrect":false}]'::jsonb,
 null, 'Emotional intelligence refers to the capacity to recognize, understand, and manage one''s own emotions, as well as recognize and influence the emotions of others.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'easy', 'mcq',
 'Effective communication in a professional setting requires:',
 '[{"text":"Using complex jargon to sound authoritative","isCorrect":false},{"text":"Clarity, empathy, and active listening","isCorrect":true},{"text":"Speaking as much as possible without pausing","isCorrect":false},{"text":"Avoiding any feedback from others","isCorrect":false}]'::jsonb,
 null, 'Clear expression, empathy toward the listener, and active listening together form the foundation of effective professional communication.');
