-- supabase/sql/exam_question_bank_neet_ug_set3.sql
--
-- Third curated question-bank batch for 'NEET UG' (see exam_patterns_neet_ug.sql for the exam's
-- structure, and Set 1/Set 2 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Set 1 or Set 2.
--
-- Same format as Set 1/Set 2: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET UG's 100% single-best-response format. 16 chapters (4 each across Physics,
-- Chemistry, Botany, Zoology) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_ug.sql,
-- exam_question_bank_neet_ug_set1.sql, and exam_question_bank_neet_ug_set2.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of force is the:',
 '[{"text":"Joule","isCorrect":false},{"text":"Newton","isCorrect":true},{"text":"Watt","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'Force is measured in newtons (N), where 1 N = 1 kg m/s^2, in accordance with Newton''s second law.'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The kinetic energy of a body of mass m moving with velocity v is given by:',
 '[{"text":"mv","isCorrect":false},{"text":"(1/2)mv^2","isCorrect":true},{"text":"mv^2","isCorrect":false},{"text":"(1/2)mv","isCorrect":false}]'::jsonb,
 null, 'Kinetic energy is defined as (1/2)mv^2, representing the energy a body possesses due to its motion.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The law of conservation of momentum applies to:',
 '[{"text":"Any system, regardless of external forces","isCorrect":false},{"text":"An isolated system with no net external force","isCorrect":true},{"text":"Only systems at rest","isCorrect":false},{"text":"Only rotating systems","isCorrect":false}]'::jsonb,
 null, 'Total momentum is conserved only for an isolated system on which no net external force acts.'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'Frictional force between two surfaces in contact acts:',
 '[{"text":"In the same direction as motion","isCorrect":false},{"text":"Opposite to the direction of relative motion (or attempted motion)","isCorrect":true},{"text":"Perpendicular to the surfaces","isCorrect":false},{"text":"In a random direction","isCorrect":false}]'::jsonb,
 null, 'Friction always opposes relative motion (or the tendency toward relative motion) between two surfaces in contact.'),

-- Physics: Electrodynamics
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'For most metallic conductors, electrical resistance:',
 '[{"text":"Decreases with increasing temperature","isCorrect":false},{"text":"Increases with increasing temperature","isCorrect":true},{"text":"Remains constant regardless of temperature","isCorrect":false},{"text":"Is unrelated to temperature","isCorrect":false}]'::jsonb,
 null, 'In most metals, increased temperature causes greater lattice vibration, impeding electron flow and increasing resistance.'),
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The power dissipated in a resistor R carrying current I can be calculated using the formula:',
 '[{"text":"I/R","isCorrect":false},{"text":"I^2*R","isCorrect":true},{"text":"I*R^2","isCorrect":false},{"text":"I+R","isCorrect":false}]'::jsonb,
 null, 'Power dissipated in a resistor is given by P=I^2*R (also expressible as V^2/R or VI).'),
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'A galvanometer is primarily used to:',
 '[{"text":"Generate electric current","isCorrect":false},{"text":"Detect and measure small electric currents","isCorrect":true},{"text":"Store electric charge","isCorrect":false},{"text":"Convert AC to DC","isCorrect":false}]'::jsonb,
 null, 'A galvanometer is a sensitive instrument used to detect and measure small electric currents based on the deflection they cause.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The phenomenon of electromagnetic induction was discovered by:',
 '[{"text":"James Clerk Maxwell","isCorrect":false},{"text":"Michael Faraday","isCorrect":true},{"text":"Andre-Marie Ampere","isCorrect":false},{"text":"Georg Ohm","isCorrect":false}]'::jsonb,
 null, 'Michael Faraday discovered electromagnetic induction, showing that a changing magnetic field can induce an EMF in a conductor.'),

-- Physics: Optics and Wave Phenomena
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The image formed by a plane mirror is:',
 '[{"text":"Real, inverted, and magnified","isCorrect":false},{"text":"Virtual, erect, and the same size as the object","isCorrect":true},{"text":"Real, erect, and diminished","isCorrect":false},{"text":"Virtual, inverted, and diminished","isCorrect":false}]'::jsonb,
 null, 'A plane mirror always forms a virtual, erect image that is the same size as the object, located as far behind the mirror as the object is in front.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The SI unit of frequency is the:',
 '[{"text":"Hertz","isCorrect":true},{"text":"Second","isCorrect":false},{"text":"Watt","isCorrect":false},{"text":"Joule","isCorrect":false}]'::jsonb,
 null, 'Frequency, the number of oscillations per second, is measured in hertz (Hz).'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'The twinkling of stars is primarily explained by which optical phenomenon?',
 '[{"text":"Total internal reflection","isCorrect":false},{"text":"Atmospheric refraction","isCorrect":true},{"text":"Polarization","isCorrect":false},{"text":"Diffraction only","isCorrect":false}]'::jsonb,
 null, 'Continuously varying atmospheric density causes starlight to refract irregularly as it passes through the atmosphere, producing the twinkling effect.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'The refractive index of a transparent medium, relative to vacuum, is always:',
 '[{"text":"Less than 1","isCorrect":false},{"text":"Greater than or equal to 1","isCorrect":true},{"text":"Exactly equal to 0","isCorrect":false},{"text":"Negative","isCorrect":false}]'::jsonb,
 null, 'Since light travels fastest in vacuum, the refractive index (ratio of speed in vacuum to speed in the medium) of any transparent medium is always at least 1.'),

-- Physics: Modern Physics and Semiconductor Devices
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'The number of protons in an atom''s nucleus determines its:',
 '[{"text":"Mass number only","isCorrect":false},{"text":"Atomic number (and identity as an element)","isCorrect":true},{"text":"Number of isotopes","isCorrect":false},{"text":"Chemical reactivity alone","isCorrect":false}]'::jsonb,
 null, 'The atomic number, defined as the number of protons, uniquely determines which element an atom represents.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Isotopes of an element have the same number of:',
 '[{"text":"Neutrons but different numbers of protons","isCorrect":false},{"text":"Protons but different numbers of neutrons","isCorrect":true},{"text":"Protons and neutrons, but different numbers of electrons","isCorrect":false},{"text":"Electrons only, with different numbers of protons","isCorrect":false}]'::jsonb,
 null, 'Isotopes are atoms of the same element (same number of protons) that differ in their number of neutrons, giving them different mass numbers.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'A transistor, as an electronic device, can function as:',
 '[{"text":"Only a resistor","isCorrect":false},{"text":"An amplifier or a switch","isCorrect":true},{"text":"Only a capacitor","isCorrect":false},{"text":"Only a source of light","isCorrect":false}]'::jsonb,
 null, 'Transistors are versatile semiconductor devices commonly used either to amplify electronic signals or to act as electronic switches.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The large energy released during nuclear fission arises from:',
 '[{"text":"Chemical bond breaking","isCorrect":false},{"text":"Conversion of mass into energy (mass defect)","isCorrect":true},{"text":"Electron transitions between energy levels","isCorrect":false},{"text":"Friction within the nucleus","isCorrect":false}]'::jsonb,
 null, 'In nuclear fission, a small amount of mass is converted into a large amount of energy according to Einstein''s E=mc^2, since the products have slightly less total mass than the original nucleus.'),

-- Chemistry: Physical Chemistry
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'Avogadro''s number is approximately:',
 '[{"text":"6.022 x 10^23","isCorrect":true},{"text":"3.011 x 10^23","isCorrect":false},{"text":"6.022 x 10^20","isCorrect":false},{"text":"1.602 x 10^19","isCorrect":false}]'::jsonb,
 null, 'Avogadro''s number, 6.022 x 10^23 per mole, is the number of constituent particles in one mole of a substance.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The process by which a solid changes directly into a gas, without passing through the liquid state, is called:',
 '[{"text":"Evaporation","isCorrect":false},{"text":"Sublimation","isCorrect":true},{"text":"Condensation","isCorrect":false},{"text":"Deposition","isCorrect":false}]'::jsonb,
 null, 'Sublimation is the direct transition of a substance from solid to gas, as seen in substances like dry ice (solid CO2).'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'Colligative properties of a solution depend primarily on:',
 '[{"text":"The chemical identity of the solute","isCorrect":false},{"text":"The number of solute particles present","isCorrect":true},{"text":"The color of the solute","isCorrect":false},{"text":"The molar mass of the solvent alone","isCorrect":false}]'::jsonb,
 null, 'Colligative properties (like boiling point elevation and freezing point depression) depend on the number of solute particles in solution, not their chemical identity.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'An endothermic reaction is one that:',
 '[{"text":"Releases heat to the surroundings","isCorrect":false},{"text":"Absorbs heat from the surroundings","isCorrect":true},{"text":"Has no heat exchange","isCorrect":false},{"text":"Only occurs at low temperature","isCorrect":false}]'::jsonb,
 null, 'An endothermic reaction absorbs heat energy from its surroundings, typically causing a drop in the surrounding temperature.'),

-- Chemistry: Organic Chemistry
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The characteristic functional group of a ketone is:',
 '[{"text":"-COOH","isCorrect":false},{"text":"A carbonyl group (C=O) flanked by two carbon groups","isCorrect":true},{"text":"-OH","isCorrect":false},{"text":"-NH2","isCorrect":false}]'::jsonb,
 null, 'Ketones are characterized by a carbonyl group (C=O) bonded to two carbon-containing groups, distinguishing them from aldehydes, where the carbonyl is bonded to at least one hydrogen.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Which of the following is an example of an aromatic compound?',
 '[{"text":"Methane","isCorrect":false},{"text":"Benzene","isCorrect":true},{"text":"Ethane","isCorrect":false},{"text":"Propane","isCorrect":false}]'::jsonb,
 null, 'Benzene, with its ring of delocalized pi electrons, is the classic example of an aromatic compound.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Polymerization is the process of:',
 '[{"text":"Breaking down large molecules into smaller ones","isCorrect":false},{"text":"Combining many small monomer molecules into a large polymer","isCorrect":true},{"text":"Converting a solid directly to a gas","isCorrect":false},{"text":"Removing hydrogen from a compound","isCorrect":false}]'::jsonb,
 null, 'Polymerization is the chemical process by which many small repeating monomer units join together to form a large polymer molecule.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Denatured alcohol refers to ethanol that has been:',
 '[{"text":"Purified for drinking","isCorrect":false},{"text":"Made unfit for drinking by adding a toxic or unpleasant substance","isCorrect":true},{"text":"Converted into methanol entirely","isCorrect":false},{"text":"Diluted with water only","isCorrect":false}]'::jsonb,
 null, 'Denatured alcohol is ethanol to which additives (like methanol or other substances) have been added to make it unsuitable for human consumption, while remaining usable for industrial purposes.'),

-- Chemistry: Inorganic Chemistry
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The most electronegative element on the periodic table is:',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Fluorine","isCorrect":true},{"text":"Chlorine","isCorrect":false},{"text":"Nitrogen","isCorrect":false}]'::jsonb,
 null, 'Fluorine, being small with a strong pull on bonding electrons, has the highest electronegativity of all elements.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which raw material is primarily used in the manufacture of cement?',
 '[{"text":"Limestone (calcium carbonate)","isCorrect":true},{"text":"Sodium chloride","isCorrect":false},{"text":"Sulfur","isCorrect":false},{"text":"Graphite","isCorrect":false}]'::jsonb,
 null, 'Limestone (calcium carbonate) is the primary raw material used in cement manufacturing, along with clay and other additives.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The chemical formula of baking soda is:',
 '[{"text":"NaHCO3","isCorrect":true},{"text":"Na2CO3","isCorrect":false},{"text":"NaOH","isCorrect":false},{"text":"NaCl","isCorrect":false}]'::jsonb,
 null, 'Baking soda is sodium bicarbonate, with the chemical formula NaHCO3.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Which metal is liquid at room temperature?',
 '[{"text":"Sodium","isCorrect":false},{"text":"Mercury","isCorrect":true},{"text":"Iron","isCorrect":false},{"text":"Aluminum","isCorrect":false}]'::jsonb,
 null, 'Mercury is the only metal that is liquid at standard room temperature, due to its unusually low melting point.'),

-- Chemistry: Biomolecules and Environmental Chemistry
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Carbohydrates are primarily composed of which elements?',
 '[{"text":"Carbon, Hydrogen, and Oxygen","isCorrect":true},{"text":"Carbon, Hydrogen, and Nitrogen","isCorrect":false},{"text":"Carbon and Sulfur only","isCorrect":false},{"text":"Nitrogen and Phosphorus only","isCorrect":false}]'::jsonb,
 null, 'Carbohydrates are composed of carbon, hydrogen, and oxygen, typically in a ratio approximating Cn(H2O)n.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Which of the following is a nucleic acid?',
 '[{"text":"DNA","isCorrect":true},{"text":"Cellulose","isCorrect":false},{"text":"Keratin","isCorrect":false},{"text":"Glycogen","isCorrect":false}]'::jsonb,
 null, 'DNA (deoxyribonucleic acid) is a nucleic acid, a biomolecule that stores and transmits genetic information.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Eutrophication in water bodies is primarily caused by an excess of:',
 '[{"text":"Dissolved oxygen","isCorrect":false},{"text":"Nutrients (like nitrogen and phosphorus) leading to algal overgrowth","isCorrect":true},{"text":"Salt content","isCorrect":false},{"text":"Sunlight alone","isCorrect":false}]'::jsonb,
 null, 'Excess nutrients (especially nitrogen and phosphorus from runoff) cause eutrophication, triggering excessive algal growth that depletes dissolved oxygen when the algae decompose.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Biodegradable waste is waste that can be:',
 '[{"text":"Broken down by natural biological processes","isCorrect":true},{"text":"Never decomposed under any conditions","isCorrect":false},{"text":"Only destroyed by burning","isCorrect":false},{"text":"Converted directly into metal","isCorrect":false}]'::jsonb,
 null, 'Biodegradable waste can be broken down into simpler substances by natural biological processes, such as the action of bacteria and fungi.'),

-- Botany: Plant Physiology
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'The process by which plants lose excess water vapor mainly through their stomata is called:',
 '[{"text":"Transpiration","isCorrect":true},{"text":"Photosynthesis","isCorrect":false},{"text":"Respiration","isCorrect":false},{"text":"Guttation","isCorrect":false}]'::jsonb,
 null, 'Transpiration is the loss of water vapor from plant surfaces, primarily through the stomata of leaves.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Which plant hormone is primarily responsible for triggering fruit ripening?',
 '[{"text":"Auxin","isCorrect":false},{"text":"Ethylene","isCorrect":true},{"text":"Gibberellin","isCorrect":false},{"text":"Cytokinin","isCorrect":false}]'::jsonb,
 null, 'Ethylene, a gaseous plant hormone, plays the primary role in triggering and coordinating fruit ripening.'),
('NEET UG', 'Botany', 'Plant Physiology', 'hard', 'mcq',
 'Photorespiration in plants tends to occur under conditions of:',
 '[{"text":"High carbon dioxide and low oxygen","isCorrect":false},{"text":"High oxygen and low carbon dioxide concentrations, in light","isCorrect":true},{"text":"Complete darkness","isCorrect":false},{"text":"Low temperature only","isCorrect":false}]'::jsonb,
 null, 'Photorespiration occurs when RuBisCO binds oxygen instead of carbon dioxide, favored under conditions of high oxygen and low carbon dioxide concentration in the presence of light.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The light-dependent reactions of photosynthesis primarily occur at the:',
 '[{"text":"Stroma","isCorrect":false},{"text":"Thylakoid membrane","isCorrect":true},{"text":"Cell wall","isCorrect":false},{"text":"Mitochondrial membrane","isCorrect":false}]'::jsonb,
 null, 'The light reactions of photosynthesis, which capture light energy and produce ATP and NADPH, occur at the thylakoid membrane within the chloroplast.'),

-- Botany: Cell Biology and Genetics
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'The cell organelle primarily responsible for protein synthesis is the:',
 '[{"text":"Ribosome","isCorrect":true},{"text":"Golgi apparatus","isCorrect":false},{"text":"Lysosome","isCorrect":false},{"text":"Vacuole","isCorrect":false}]'::jsonb,
 null, 'Ribosomes are the cellular structures responsible for translating mRNA into proteins.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'Meiosis results in the formation of:',
 '[{"text":"Two diploid daughter cells","isCorrect":false},{"text":"Four haploid daughter cells (gametes)","isCorrect":true},{"text":"One large diploid cell","isCorrect":false},{"text":"Two genetically identical diploid cells","isCorrect":false}]'::jsonb,
 null, 'Meiosis involves two successive divisions, ultimately producing four genetically varied haploid gametes from a single diploid parent cell.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'A dominant allele is one that:',
 '[{"text":"Is never expressed","isCorrect":false},{"text":"Expresses its phenotype even in the heterozygous state","isCorrect":true},{"text":"Can only be expressed in the homozygous state","isCorrect":false},{"text":"Always causes disease","isCorrect":false}]'::jsonb,
 null, 'A dominant allele masks the effect of a recessive allele and expresses its phenotype even when only one copy is present (heterozygous state).'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'The Golgi apparatus is primarily involved in:',
 '[{"text":"DNA replication","isCorrect":false},{"text":"Packaging and modifying proteins for secretion","isCorrect":true},{"text":"Photosynthesis","isCorrect":false},{"text":"Cell wall formation only","isCorrect":false}]'::jsonb,
 null, 'The Golgi apparatus modifies, sorts, and packages proteins and lipids, preparing them for secretion or delivery to other cellular destinations.'),

-- Botany: Ecology and Environment
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'The largest terrestrial biome, characterized by dense tree cover and high annual rainfall, is the:',
 '[{"text":"Desert","isCorrect":false},{"text":"Tropical rainforest","isCorrect":true},{"text":"Tundra","isCorrect":false},{"text":"Grassland","isCorrect":false}]'::jsonb,
 null, 'Tropical rainforests, found near the equator, are characterized by dense vegetation and consistently high rainfall, and host exceptional biodiversity.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'Which of the following is a renewable source of energy?',
 '[{"text":"Coal","isCorrect":false},{"text":"Solar energy","isCorrect":true},{"text":"Natural gas","isCorrect":false},{"text":"Petroleum","isCorrect":false}]'::jsonb,
 null, 'Solar energy is a renewable resource, continuously replenished by the sun, unlike fossil fuels like coal, natural gas, and petroleum.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'In situ conservation of biodiversity primarily involves:',
 '[{"text":"Conserving species within their natural habitat (e.g. national parks)","isCorrect":true},{"text":"Conserving species only in zoos and botanical gardens","isCorrect":false},{"text":"Storing seeds in gene banks only","isCorrect":false},{"text":"Cloning endangered species in laboratories only","isCorrect":false}]'::jsonb,
 null, 'In situ conservation protects species within their natural habitats, such as through national parks, wildlife sanctuaries, and biosphere reserves.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'A species that is at high risk of extinction in the near future is termed:',
 '[{"text":"Extinct","isCorrect":false},{"text":"Endangered","isCorrect":true},{"text":"Common","isCorrect":false},{"text":"Invasive","isCorrect":false}]'::jsonb,
 null, 'An endangered species is one facing a very high risk of extinction in the near future, typically due to habitat loss, hunting, or other threats.'),

-- Botany: Plant Morphology and Anatomy
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The part of a plant that anchors it to the soil and absorbs water and minerals is the:',
 '[{"text":"Stem","isCorrect":false},{"text":"Root","isCorrect":true},{"text":"Leaf","isCorrect":false},{"text":"Flower","isCorrect":false}]'::jsonb,
 null, 'The root system anchors the plant in the soil and is primarily responsible for absorbing water and dissolved minerals.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Which type of root system is typically found in dicot plants?',
 '[{"text":"Fibrous root system","isCorrect":false},{"text":"Tap root system","isCorrect":true},{"text":"Adventitious root system only","isCorrect":false},{"text":"Prop root system only","isCorrect":false}]'::jsonb,
 null, 'Dicot plants typically develop a tap root system, with one main dominant root growing straight down and smaller lateral roots branching off.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Guard cells primarily regulate the opening and closing of the:',
 '[{"text":"Xylem vessels","isCorrect":false},{"text":"Stomata","isCorrect":true},{"text":"Phloem sieve tubes","isCorrect":false},{"text":"Root hairs","isCorrect":false}]'::jsonb,
 null, 'Guard cells surround each stomatal pore and control its opening and closing in response to environmental conditions, regulating gas exchange and water loss.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The male reproductive part of a flower, collectively, is called the:',
 '[{"text":"Gynoecium","isCorrect":false},{"text":"Androecium (stamens)","isCorrect":true},{"text":"Calyx","isCorrect":false},{"text":"Corolla","isCorrect":false}]'::jsonb,
 null, 'The androecium refers collectively to the stamens, the male reproductive organs of a flower, each consisting of a filament and anther.'),

-- Zoology: Human Physiology
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'Red blood cells are primarily responsible for transporting:',
 '[{"text":"Carbon dioxide only","isCorrect":false},{"text":"Oxygen (via hemoglobin)","isCorrect":true},{"text":"Hormones","isCorrect":false},{"text":"Digested food particles","isCorrect":false}]'::jsonb,
 null, 'Red blood cells contain hemoglobin, which binds and transports oxygen from the lungs to tissues throughout the body.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Gaseous exchange in the human respiratory system primarily occurs in the:',
 '[{"text":"Trachea","isCorrect":false},{"text":"Alveoli","isCorrect":true},{"text":"Bronchi","isCorrect":false},{"text":"Larynx","isCorrect":false}]'::jsonb,
 null, 'The alveoli, tiny air sacs at the end of the bronchial tree, are the site of oxygen and carbon dioxide exchange between air and blood.'),
('NEET UG', 'Zoology', 'Human Physiology', 'hard', 'mcq',
 'Which hormone, secreted by the thyroid gland, helps regulate blood calcium levels alongside parathyroid hormone?',
 '[{"text":"Thyroxine","isCorrect":false},{"text":"Calcitonin","isCorrect":true},{"text":"Insulin","isCorrect":false},{"text":"Cortisol","isCorrect":false}]'::jsonb,
 null, 'Calcitonin, secreted by the thyroid gland, lowers blood calcium levels, working in balance with parathyroid hormone, which raises them.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Bile, which aids in the digestion of fats, is produced by the:',
 '[{"text":"Pancreas","isCorrect":false},{"text":"Liver (and stored in the gallbladder)","isCorrect":true},{"text":"Stomach","isCorrect":false},{"text":"Small intestine","isCorrect":false}]'::jsonb,
 null, 'Bile is produced by the liver and stored/concentrated in the gallbladder before being released into the small intestine to aid fat digestion.'),

-- Zoology: Human Reproduction and Reproductive Health
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'The functional unit of the mammary gland responsible for milk production is the:',
 '[{"text":"Alveolus (mammary alveoli)","isCorrect":true},{"text":"Areola","isCorrect":false},{"text":"Nipple","isCorrect":false},{"text":"Lactiferous duct only","isCorrect":false}]'::jsonb,
 null, 'The alveoli of the mammary gland are the functional units responsible for producing milk, which is then transported through ducts.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'In humans, the biological sex of the offspring is determined by the sex chromosome contributed by the:',
 '[{"text":"Mother, since she carries two X chromosomes","isCorrect":false},{"text":"Father, whose sperm carries either an X or Y chromosome","isCorrect":true},{"text":"Neither parent; sex is determined randomly after fertilization","isCorrect":false},{"text":"Both parents equally, through a combined mechanism","isCorrect":false}]'::jsonb,
 null, 'Since the mother always contributes an X chromosome, the father''s sperm -- carrying either an X or Y chromosome -- determines the offspring''s biological sex.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Menstruation occurs due to:',
 '[{"text":"Fertilization of the egg","isCorrect":false},{"text":"Shedding of the uterine lining (endometrium) in the absence of fertilization","isCorrect":true},{"text":"Implantation of the embryo","isCorrect":false},{"text":"Ovulation itself","isCorrect":false}]'::jsonb,
 null, 'If fertilization does not occur, hormone levels drop, causing the thickened endometrial lining to be shed as menstrual flow.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'In vitro fertilization (IVF) involves fertilization occurring:',
 '[{"text":"Inside the fallopian tube, as in natural conception","isCorrect":false},{"text":"Outside the body, in a laboratory setting","isCorrect":true},{"text":"Inside the uterus directly","isCorrect":false},{"text":"Inside the ovary","isCorrect":false}]'::jsonb,
 null, 'In vitro fertilization involves combining egg and sperm outside the body, in a laboratory dish, before transferring the resulting embryo into the uterus.'),

-- Zoology: Genetics and Evolution
('NEET UG', 'Zoology', 'Genetics and Evolution', 'easy', 'mcq',
 'The observable physical traits or appearance of an organism are collectively referred to as its:',
 '[{"text":"Genotype","isCorrect":false},{"text":"Phenotype","isCorrect":true},{"text":"Karyotype","isCorrect":false},{"text":"Genome","isCorrect":false}]'::jsonb,
 null, 'Phenotype refers to the observable physical or biochemical characteristics of an organism, resulting from the interaction of its genotype and environment.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'A genetic cross involving two different traits simultaneously (such as RrYy x RrYy) is called a:',
 '[{"text":"Monohybrid cross","isCorrect":false},{"text":"Dihybrid cross","isCorrect":true},{"text":"Test cross","isCorrect":false},{"text":"Back cross","isCorrect":false}]'::jsonb,
 null, 'A dihybrid cross examines the inheritance of two different traits simultaneously, as originally studied by Mendel with pea plants.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'Analogous organs are structures that:',
 '[{"text":"Share a common evolutionary origin","isCorrect":false},{"text":"Perform similar functions but have different origins (not indicating common ancestry)","isCorrect":true},{"text":"Are identical in both structure and function across all species","isCorrect":false},{"text":"Have no functional role","isCorrect":false}]'::jsonb,
 null, 'Analogous organs, like the wings of insects and birds, evolved independently to perform similar functions, illustrating convergent evolution rather than common ancestry.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'The process by which new species arise from existing ones over evolutionary time is called:',
 '[{"text":"Speciation","isCorrect":true},{"text":"Mutation alone","isCorrect":false},{"text":"Extinction","isCorrect":false},{"text":"Domestication","isCorrect":false}]'::jsonb,
 null, 'Speciation is the evolutionary process by which populations diverge and eventually become distinct, reproductively isolated species.'),

-- Zoology: Biotechnology and its Applications
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'The Bt toxin, used in genetically modified crops, works by:',
 '[{"text":"Being toxic to specific insect larvae when ingested, but harmless to humans","isCorrect":true},{"text":"Killing all insects and mammals indiscriminately","isCorrect":false},{"text":"Repelling insects through smell alone","isCorrect":false},{"text":"Preventing photosynthesis in weeds","isCorrect":false}]'::jsonb,
 null, 'Bt toxin becomes activated and toxic only in the specific alkaline gut environment of certain insect larvae, making it harmless to humans and most other organisms.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Which of the following is commonly referred to as "molecular scissors" used in genetic engineering?',
 '[{"text":"DNA ligase","isCorrect":false},{"text":"Restriction endonuclease","isCorrect":true},{"text":"DNA polymerase","isCorrect":false},{"text":"RNA polymerase","isCorrect":false}]'::jsonb,
 null, 'Restriction endonucleases (restriction enzymes) cut DNA at specific recognition sequences, earning them the nickname "molecular scissors".'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Gene therapy is primarily used to:',
 '[{"text":"Remove all genetic material from a cell","isCorrect":false},{"text":"Correct a genetic defect by introducing a normal gene","isCorrect":true},{"text":"Clone an entire organism","isCorrect":false},{"text":"Increase a person''s height","isCorrect":false}]'::jsonb,
 null, 'Gene therapy aims to treat or prevent disease by introducing, altering, or removing genetic material within a patient''s cells, often to correct a defective gene.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'hard', 'mcq',
 'The cloning of Dolly the sheep was achieved using which technique?',
 '[{"text":"In vitro fertilization","isCorrect":false},{"text":"Somatic cell nuclear transfer","isCorrect":true},{"text":"Gene therapy","isCorrect":false},{"text":"Polymerase chain reaction","isCorrect":false}]'::jsonb,
 null, 'Dolly the sheep was cloned using somatic cell nuclear transfer, in which the nucleus of a somatic cell was transferred into an enucleated egg cell.');
