-- supabase/sql/exam_question_bank_neet_pg_set7.sql
--
-- Seventh curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and Sets 1-6 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1 through 6.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical
-- Sciences, 4 Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/
-- Anesthesia) each get 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql through set6.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Injury to the radial nerve in the spiral (radial) groove of the humerus classically causes:',
 '[{"text":"Wrist drop","isCorrect":true},{"text":"Claw hand","isCorrect":false},{"text":"Foot drop","isCorrect":false},{"text":"Winging of the scapula","isCorrect":false}]'::jsonb,
 null, 'The radial nerve runs in the spiral groove of the humerus and, when injured there, causes wrist drop due to paralysis of the wrist and finger extensors.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The internal jugular vein primarily drains blood from the:',
 '[{"text":"Lower limbs","isCorrect":false},{"text":"Brain, face, and neck (via the dural venous sinuses)","isCorrect":true},{"text":"Abdominal organs","isCorrect":false},{"text":"Kidneys","isCorrect":false}]'::jsonb,
 null, 'The internal jugular vein drains blood from the dural venous sinuses of the brain, as well as the superficial structures of the face and neck.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'hard', 'mcq',
 'Meckel''s diverticulum is a congenital remnant of which embryological structure?',
 '[{"text":"The urachus","isCorrect":false},{"text":"The vitelline (omphalomesenteric) duct","isCorrect":true},{"text":"The neural tube","isCorrect":false},{"text":"The branchial arches","isCorrect":false}]'::jsonb,
 null, 'Meckel''s diverticulum arises from incomplete obliteration of the vitelline (omphalomesenteric) duct, which normally connects the yolk sac to the midgut in early development.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Below the inguinal ligament, the femoral artery is a direct continuation of the:',
 '[{"text":"Internal iliac artery","isCorrect":false},{"text":"External iliac artery","isCorrect":true},{"text":"Common iliac artery","isCorrect":false},{"text":"Popliteal artery","isCorrect":false}]'::jsonb,
 null, 'The external iliac artery becomes the femoral artery as it passes beneath the inguinal ligament into the lower limb.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'In adults, erythropoietin is primarily produced by the:',
 '[{"text":"Liver","isCorrect":false},{"text":"Kidney","isCorrect":true},{"text":"Spleen","isCorrect":false},{"text":"Bone marrow itself","isCorrect":false}]'::jsonb,
 null, 'In adults, the kidney is the primary site of erythropoietin production, released in response to hypoxia to stimulate red blood cell production.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which type of muscle contraction occurs when muscle tension increases without a change in muscle length?',
 '[{"text":"Isotonic contraction","isCorrect":false},{"text":"Isometric contraction","isCorrect":true},{"text":"Eccentric contraction","isCorrect":false},{"text":"Concentric contraction","isCorrect":false}]'::jsonb,
 null, 'An isometric contraction generates tension without any change in muscle length, as when pushing against an immovable object.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The Frank-Starling law of the heart states that:',
 '[{"text":"Heart rate always remains constant regardless of venous return","isCorrect":false},{"text":"Increased venous return (preload) increases the force of cardiac contraction","isCorrect":true},{"text":"Cardiac output is independent of venous return","isCorrect":false},{"text":"Decreased preload always increases stroke volume","isCorrect":false}]'::jsonb,
 null, 'The Frank-Starling law states that, within physiological limits, an increase in venous return (and hence ventricular filling/preload) leads to a stronger contraction and increased stroke volume.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which cranial nerve controls pupillary constriction (miosis)?',
 '[{"text":"Optic nerve (CN II)","isCorrect":false},{"text":"Oculomotor nerve (CN III)","isCorrect":true},{"text":"Trochlear nerve (CN IV)","isCorrect":false},{"text":"Abducens nerve (CN VI)","isCorrect":false}]'::jsonb,
 null, 'The oculomotor nerve (CN III) carries parasympathetic fibers that control pupillary constriction (miosis) via the pupillary light reflex.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Which amino acid serves as the precursor for the synthesis of serotonin?',
 '[{"text":"Tryptophan","isCorrect":true},{"text":"Tyrosine","isCorrect":false},{"text":"Glycine","isCorrect":false},{"text":"Lysine","isCorrect":false}]'::jsonb,
 null, 'Tryptophan is the amino acid precursor for the synthesis of serotonin (and subsequently melatonin).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Deficiency of the enzyme lactase leads to intolerance of which sugar?',
 '[{"text":"Sucrose","isCorrect":false},{"text":"Lactose","isCorrect":true},{"text":"Fructose","isCorrect":false},{"text":"Glucose","isCorrect":false}]'::jsonb,
 null, 'Lactase deficiency impairs the breakdown of lactose (milk sugar) into glucose and galactose, causing lactose intolerance.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Along with folate, which vitamin is essential for the proper maturation of red blood cells?',
 '[{"text":"Vitamin B12","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin E","isCorrect":false},{"text":"Vitamin A","isCorrect":false}]'::jsonb,
 null, 'Vitamin B12, alongside folate, is essential for DNA synthesis in developing red blood cells; deficiency of either causes megaloblastic anemia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Ketone bodies, produced during prolonged fasting or starvation, are primarily synthesized in the:',
 '[{"text":"Liver","isCorrect":true},{"text":"Kidney","isCorrect":false},{"text":"Brain","isCorrect":false},{"text":"Skeletal muscle","isCorrect":false}]'::jsonb,
 null, 'Ketone bodies are synthesized in the liver from fatty acid breakdown, providing an alternative energy source for tissues like the brain during prolonged fasting.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'easy', 'mcq',
 'Iron deficiency anemia is classically characterized by red blood cells that are:',
 '[{"text":"Microcytic and hypochromic","isCorrect":true},{"text":"Macrocytic and normochromic","isCorrect":false},{"text":"Normocytic and normochromic","isCorrect":false},{"text":"Macrocytic and hyperchromic","isCorrect":false}]'::jsonb,
 null, 'Iron deficiency anemia classically produces microcytic (small), hypochromic (pale) red blood cells due to insufficient hemoglobin synthesis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Multiple myeloma is characterized by the malignant proliferation of:',
 '[{"text":"Plasma cells","isCorrect":true},{"text":"T lymphocytes","isCorrect":false},{"text":"Neutrophils","isCorrect":false},{"text":"Red blood cell precursors","isCorrect":false}]'::jsonb,
 null, 'Multiple myeloma results from the malignant, clonal proliferation of plasma cells in the bone marrow, producing excess monoclonal antibody (M protein).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'The "Philadelphia chromosome" is classically associated with which malignancy?',
 '[{"text":"Chronic myeloid leukemia (CML)","isCorrect":true},{"text":"Acute lymphoblastic leukemia","isCorrect":false},{"text":"Hodgkin lymphoma","isCorrect":false},{"text":"Multiple myeloma","isCorrect":false}]'::jsonb,
 null, 'The Philadelphia chromosome, resulting from a t(9;22) translocation forming the BCR-ABL fusion gene, is the hallmark genetic abnormality of chronic myeloid leukemia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Unlike apoptosis, necrosis is characterized by:',
 '[{"text":"Cell shrinkage with no inflammatory response","isCorrect":false},{"text":"Cell swelling, membrane rupture, and an inflammatory response","isCorrect":true},{"text":"Orderly DNA fragmentation with no membrane damage","isCorrect":false},{"text":"Complete absence of any cellular changes","isCorrect":false}]'::jsonb,
 null, 'Necrosis involves cell swelling, membrane rupture, and spillage of cellular contents that triggers inflammation, in contrast to the orderly, non-inflammatory process of apoptosis.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Cholera is caused by which organism?',
 '[{"text":"Vibrio cholerae","isCorrect":true},{"text":"Salmonella typhi","isCorrect":false},{"text":"Shigella dysenteriae","isCorrect":false},{"text":"Escherichia coli","isCorrect":false}]'::jsonb,
 null, 'Cholera is caused by Vibrio cholerae, a gram-negative bacterium producing a potent enterotoxin that causes profuse watery diarrhea.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Gonorrhea is caused by which organism?',
 '[{"text":"Neisseria gonorrhoeae","isCorrect":true},{"text":"Chlamydia trachomatis","isCorrect":false},{"text":"Treponema pallidum","isCorrect":false},{"text":"Haemophilus ducreyi","isCorrect":false}]'::jsonb,
 null, 'Gonorrhea is caused by Neisseria gonorrhoeae, a gram-negative diplococcus transmitted primarily through sexual contact.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Genital warts are most commonly caused by which virus?',
 '[{"text":"Human papillomavirus (HPV)","isCorrect":true},{"text":"Herpes simplex virus","isCorrect":false},{"text":"Molluscum contagiosum virus","isCorrect":false},{"text":"Hepatitis B virus","isCorrect":false}]'::jsonb,
 null, 'Genital warts are caused by certain low-risk strains of human papillomavirus (HPV), distinct from the high-risk strains linked to cervical cancer.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Aspergillus is an example of which type of pathogen?',
 '[{"text":"A bacterium","isCorrect":false},{"text":"A mold (fungus)","isCorrect":true},{"text":"A virus","isCorrect":false},{"text":"A protozoan parasite","isCorrect":false}]'::jsonb,
 null, 'Aspergillus is a genus of mold (filamentous fungus), capable of causing invasive disease especially in immunocompromised patients.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Triple therapy for H. pylori-associated peptic ulcer disease typically includes two antibiotics plus a:',
 '[{"text":"Proton pump inhibitor (PPI)","isCorrect":true},{"text":"Beta-blocker","isCorrect":false},{"text":"Diuretic","isCorrect":false},{"text":"Antihistamine","isCorrect":false}]'::jsonb,
 null, 'H. pylori eradication regimens combine two antibiotics with a proton pump inhibitor to suppress acid secretion and improve antibiotic efficacy.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'Atropine is primarily used as an antidote in which type of poisoning?',
 '[{"text":"Organophosphorus poisoning","isCorrect":true},{"text":"Paracetamol overdose","isCorrect":false},{"text":"Iron poisoning","isCorrect":false},{"text":"Opioid overdose","isCorrect":false}]'::jsonb,
 null, 'Atropine, an anticholinergic agent, counteracts the excessive cholinergic stimulation caused by organophosphorus poisoning.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which class of drugs is used to manage benign prostatic hyperplasia by relaxing smooth muscle in the prostate and bladder neck?',
 '[{"text":"Alpha-1 blockers (e.g. tamsulosin)","isCorrect":true},{"text":"Beta-2 agonists","isCorrect":false},{"text":"Calcium channel blockers","isCorrect":false},{"text":"ACE inhibitors","isCorrect":false}]'::jsonb,
 null, 'Alpha-1 blockers, such as tamsulosin, relax smooth muscle in the prostate and bladder neck, improving urinary symptoms in benign prostatic hyperplasia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Lithium therapy requires close monitoring primarily because it has a narrow:',
 '[{"text":"Half-life","isCorrect":false},{"text":"Therapeutic index","isCorrect":true},{"text":"Route of administration","isCorrect":false},{"text":"Molecular weight","isCorrect":false}]'::jsonb,
 null, 'Lithium has a narrow therapeutic index, meaning the difference between an effective dose and a toxic dose is small, necessitating regular blood level monitoring.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'A "dying declaration" refers to a statement made by a person who believes:',
 '[{"text":"They will fully recover soon","isCorrect":false},{"text":"They are about to die, regarding the cause of their impending death","isCorrect":true},{"text":"They are being falsely accused","isCorrect":false},{"text":"They witnessed an unrelated crime","isCorrect":false}]'::jsonb,
 null, 'A dying declaration is a statement made by a person who believes death is imminent, describing the circumstances or cause of their fatal injury, and is admissible as evidence in many legal systems.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Rigor mortis typically begins to appear how many hours after death?',
 '[{"text":"1-2 hours","isCorrect":true},{"text":"24-36 hours","isCorrect":false},{"text":"48-72 hours","isCorrect":false},{"text":"Immediately at the moment of death","isCorrect":false}]'::jsonb,
 null, 'Rigor mortis typically begins to appear 1-2 hours after death, becomes fully established by around 12 hours, and then gradually resolves.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'hard', 'mcq',
 'The "Stas-Otto process," a classic forensic toxicology technique, is used to extract and detect which class of poisons?',
 '[{"text":"Heavy metals","isCorrect":false},{"text":"Alkaloids (e.g. morphine, strychnine)","isCorrect":true},{"text":"Corrosive acids","isCorrect":false},{"text":"Volatile gases","isCorrect":false}]'::jsonb,
 null, 'The Stas-Otto process is a classic extraction technique used in forensic toxicology to isolate and detect alkaloid poisons, such as morphine and strychnine, from body tissues.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'easy', 'mcq',
 'A contusion (bruise) is best described as:',
 '[{"text":"An injury causing bleeding into the tissues without a break in the skin","isCorrect":true},{"text":"A deep, penetrating wound through the skin","isCorrect":false},{"text":"A superficial scrape of the skin surface only","isCorrect":false},{"text":"A burn injury","isCorrect":false}]'::jsonb,
 null, 'A contusion is caused by blunt trauma that ruptures small blood vessels beneath intact skin, causing bleeding into the surrounding tissue without breaking the skin surface.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The "positive predictive value" of a diagnostic test refers to:',
 '[{"text":"The probability that a person with a positive test result actually has the disease","isCorrect":true},{"text":"The overall accuracy of the test regardless of results","isCorrect":false},{"text":"The probability that a healthy person will test negative","isCorrect":false},{"text":"The cost of performing the test","isCorrect":false}]'::jsonb,
 null, 'Positive predictive value is the probability that an individual who tests positive on a diagnostic test truly has the disease.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which study design examines both exposure and outcome simultaneously, at a single point in time?',
 '[{"text":"Cross-sectional study","isCorrect":true},{"text":"Cohort study","isCorrect":false},{"text":"Randomized controlled trial","isCorrect":false},{"text":"Case-control study","isCorrect":false}]'::jsonb,
 null, 'A cross-sectional study collects data on exposure and outcome simultaneously at a single point in time, providing a snapshot of a population.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The Expanded Programme on Immunization (EPI) primarily aims to:',
 '[{"text":"Increase immunization coverage against vaccine-preventable diseases","isCorrect":true},{"text":"Fund research into new surgical techniques","isCorrect":false},{"text":"Provide nutritional supplements only","isCorrect":false},{"text":"Focus exclusively on adult healthcare","isCorrect":false}]'::jsonb,
 null, 'The Expanded Programme on Immunization is a global initiative aimed at increasing vaccination coverage to reduce the burden of vaccine-preventable diseases.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The Under-5 Mortality Rate is an important indicator of:',
 '[{"text":"Overall child health and development in a population","isCorrect":true},{"text":"Adult literacy rates only","isCorrect":false},{"text":"Hospital infrastructure only","isCorrect":false},{"text":"Vaccine manufacturing capacity","isCorrect":false}]'::jsonb,
 null, 'The Under-5 Mortality Rate reflects the overall health status of children and is widely used as a key indicator of a population''s health and socioeconomic development.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Systemic lupus erythematosus (SLE) is characterized by the presence of which antibody?',
 '[{"text":"Antinuclear antibodies (ANA)","isCorrect":true},{"text":"Anti-CCP antibodies exclusively","isCorrect":false},{"text":"Anti-HAV antibodies","isCorrect":false},{"text":"Anti-Rh antibodies","isCorrect":false}]'::jsonb,
 null, 'Antinuclear antibodies (ANA) are present in the vast majority of patients with systemic lupus erythematosus and serve as an important screening test.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Which condition presents with chest pain that classically worsens with inspiration and is relieved by sitting forward?',
 '[{"text":"Pericarditis","isCorrect":true},{"text":"Stable angina","isCorrect":false},{"text":"Gastroesophageal reflux disease","isCorrect":false},{"text":"Pulmonary embolism exclusively","isCorrect":false}]'::jsonb,
 null, 'Pericarditis classically causes sharp chest pain that worsens with inspiration or lying flat, and is characteristically relieved by sitting up and leaning forward.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Overall, the most common type of stroke is:',
 '[{"text":"Ischemic (thrombotic/embolic) stroke","isCorrect":true},{"text":"Hemorrhagic stroke","isCorrect":false},{"text":"Subarachnoid hemorrhage","isCorrect":false},{"text":"Venous sinus thrombosis","isCorrect":false}]'::jsonb,
 null, 'Ischemic strokes, caused by thrombotic or embolic occlusion of a cerebral artery, account for the large majority of all strokes, far more common than hemorrhagic stroke.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'In endemic regions, acute viral hepatitis is most commonly caused by:',
 '[{"text":"Hepatitis A virus","isCorrect":true},{"text":"Hepatitis D virus","isCorrect":false},{"text":"Hepatitis E virus exclusively in all regions","isCorrect":false},{"text":"Hepatitis C virus exclusively in all regions","isCorrect":false}]'::jsonb,
 null, 'In many endemic regions with poor sanitation, Hepatitis A virus, transmitted via the fecal-oral route, is the most common cause of acute viral hepatitis.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common cause of severe diarrhea in young children worldwide is:',
 '[{"text":"Rotavirus","isCorrect":true},{"text":"Salmonella","isCorrect":false},{"text":"Giardia lamblia","isCorrect":false},{"text":"Entamoeba histolytica","isCorrect":false}]'::jsonb,
 null, 'Rotavirus is the leading cause of severe, dehydrating diarrhea in infants and young children worldwide.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Which vitamin is routinely given to newborns shortly after birth to prevent hemorrhagic disease of the newborn?',
 '[{"text":"Vitamin K","isCorrect":true},{"text":"Vitamin D","isCorrect":false},{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin E","isCorrect":false}]'::jsonb,
 null, 'Newborns have low vitamin K stores at birth, so a prophylactic vitamin K injection is routinely given to prevent hemorrhagic disease of the newborn.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Precocious puberty refers to:',
 '[{"text":"The onset of pubertal changes at an unusually delayed age","isCorrect":false},{"text":"The onset of pubertal changes before the expected age","isCorrect":true},{"text":"A complete absence of puberty","isCorrect":false},{"text":"Normal puberty occurring at the average age","isCorrect":false}]'::jsonb,
 null, 'Precocious puberty describes the onset of secondary sexual characteristics earlier than the expected age range, typically before 8 years in girls and 9 years in boys.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'The umbilical cord stump in a newborn typically falls off within approximately:',
 '[{"text":"1-2 weeks after birth","isCorrect":true},{"text":"1-2 hours after birth","isCorrect":false},{"text":"6 months after birth","isCorrect":false},{"text":"1 year after birth","isCorrect":false}]'::jsonb,
 null, 'The umbilical cord stump typically dries up and falls off within about 1 to 2 weeks after birth.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'easy', 'mcq',
 'Which condition is characterized by persistent sadness, loss of interest, and functional impairment lasting at least 2 weeks?',
 '[{"text":"Major depressive disorder","isCorrect":true},{"text":"Generalized anxiety disorder","isCorrect":false},{"text":"Bipolar disorder (manic phase)","isCorrect":false},{"text":"Adjustment disorder only","isCorrect":false}]'::jsonb,
 null, 'Major depressive disorder is diagnosed based on persistent depressed mood and/or loss of interest, along with other symptoms causing functional impairment, lasting at least 2 weeks.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which class of drugs is considered first-line pharmacological treatment for schizophrenia?',
 '[{"text":"Antipsychotics","isCorrect":true},{"text":"Benzodiazepines","isCorrect":false},{"text":"SSRIs","isCorrect":false},{"text":"Mood stabilizers alone","isCorrect":false}]'::jsonb,
 null, 'Antipsychotic medications are the first-line pharmacological treatment for schizophrenia, targeting positive symptoms like hallucinations and delusions.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Separation anxiety disorder is most commonly diagnosed in which age group?',
 '[{"text":"Elderly adults","isCorrect":false},{"text":"Children","isCorrect":true},{"text":"Middle-aged adults","isCorrect":false},{"text":"Adolescents exclusively","isCorrect":false}]'::jsonb,
 null, 'Separation anxiety disorder, involving excessive fear or anxiety about separation from attachment figures, is most commonly diagnosed in childhood.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which type of therapy focuses on identifying and changing negative thought patterns and behaviors?',
 '[{"text":"Cognitive Behavioral Therapy (CBT)","isCorrect":true},{"text":"Psychoanalysis exclusively","isCorrect":false},{"text":"Electroconvulsive therapy","isCorrect":false},{"text":"Pharmacotherapy alone","isCorrect":false}]'::jsonb,
 null, 'Cognitive Behavioral Therapy (CBT) focuses on identifying and restructuring negative thought patterns and maladaptive behaviors to improve emotional well-being.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Ichthyosis is a group of conditions characterized by:',
 '[{"text":"Excessive dryness and scaling of the skin, often inherited","isCorrect":true},{"text":"Excess oiliness of the skin","isCorrect":false},{"text":"Loss of skin pigmentation only","isCorrect":false},{"text":"Chronic itching with no visible skin changes","isCorrect":false}]'::jsonb,
 null, 'Ichthyosis refers to a group of often-inherited skin disorders characterized by dry, thickened, and scaling skin resembling fish scales.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'hard', 'mcq',
 'Pemphigus vulgaris is an autoimmune blistering disease that primarily targets which structure?',
 '[{"text":"Desmosomes (intercellular adhesion proteins between keratinocytes)","isCorrect":true},{"text":"The basement membrane zone","isCorrect":false},{"text":"Melanocytes","isCorrect":false},{"text":"Hair follicles","isCorrect":false}]'::jsonb,
 null, 'Pemphigus vulgaris involves autoantibodies against desmosomal proteins that hold keratinocytes together, causing intraepidermal blister formation.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Trichotillomania is a condition characterized by:',
 '[{"text":"Chronic hair loss due to habitual hair pulling","isCorrect":true},{"text":"Excessive hair growth","isCorrect":false},{"text":"Fungal infection of the scalp","isCorrect":false},{"text":"Autoimmune destruction of hair follicles","isCorrect":false}]'::jsonb,
 null, 'Trichotillomania is a psychiatric condition involving a recurrent, irresistible urge to pull out one''s own hair, resulting in noticeable hair loss.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Acanthosis nigricans, presenting as dark, velvety skin patches (often on the neck and axillae), is most commonly associated with:',
 '[{"text":"Insulin resistance (e.g. obesity, Type 2 diabetes)","isCorrect":true},{"text":"Vitamin C deficiency","isCorrect":false},{"text":"Iron deficiency anemia","isCorrect":false},{"text":"Hyperthyroidism","isCorrect":false}]'::jsonb,
 null, 'Acanthosis nigricans is most commonly associated with insulin resistance, seen in conditions like obesity and Type 2 diabetes mellitus.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common cause of acute cholecystitis is:',
 '[{"text":"Gallstones obstructing the cystic duct","isCorrect":true},{"text":"Viral infection of the gallbladder","isCorrect":false},{"text":"Autoimmune inflammation","isCorrect":false},{"text":"Direct trauma alone","isCorrect":false}]'::jsonb,
 null, 'Acute cholecystitis is most commonly caused by a gallstone obstructing the cystic duct, leading to gallbladder inflammation.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'hard', 'mcq',
 'A "strawberry gallbladder" appearance, seen on gross pathology, is associated with:',
 '[{"text":"Cholesterolosis of the gallbladder","isCorrect":true},{"text":"Acute bacterial cholecystitis alone","isCorrect":false},{"text":"Gallbladder cancer exclusively","isCorrect":false},{"text":"Normal gallbladder anatomy","isCorrect":false}]'::jsonb,
 null, 'The "strawberry gallbladder" appearance results from cholesterol deposits within the lamina propria of the gallbladder mucosa, a condition called cholesterolosis.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'A hernia passing through the femoral canal, more common in women, is called a:',
 '[{"text":"Inguinal hernia","isCorrect":false},{"text":"Femoral hernia","isCorrect":true},{"text":"Umbilical hernia","isCorrect":false},{"text":"Hiatus hernia","isCorrect":false}]'::jsonb,
 null, 'A femoral hernia passes through the femoral canal below the inguinal ligament and is more common in women than men.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common benign tumor of the liver is:',
 '[{"text":"Hepatic hemangioma","isCorrect":true},{"text":"Hepatocellular adenoma","isCorrect":false},{"text":"Focal nodular hyperplasia","isCorrect":false},{"text":"Hepatoblastoma","isCorrect":false}]'::jsonb,
 null, 'Hepatic hemangioma, a benign vascular tumor, is the most common benign tumor of the liver.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'hard', 'mcq',
 'A Monteggia fracture involves a fracture of the ulna along with dislocation of the:',
 '[{"text":"Radial head","isCorrect":true},{"text":"Distal radius","isCorrect":false},{"text":"Carpal bones","isCorrect":false},{"text":"Humeral head","isCorrect":false}]'::jsonb,
 null, 'A Monteggia fracture combines a fracture of the proximal ulna with dislocation of the radial head at the elbow.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Ankylosing spondylitis primarily affects which part of the skeleton?',
 '[{"text":"The sacroiliac joints and spine","isCorrect":true},{"text":"The small joints of the hands only","isCorrect":false},{"text":"The knee joint exclusively","isCorrect":false},{"text":"The skull only","isCorrect":false}]'::jsonb,
 null, 'Ankylosing spondylitis is a chronic inflammatory condition primarily affecting the sacroiliac joints and the spine, potentially leading to spinal fusion over time.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Slipped Capital Femoral Epiphysis (SCFE), a condition common in adolescents, involves:',
 '[{"text":"Slippage of the femoral head at the growth plate","isCorrect":true},{"text":"A fracture of the tibial shaft","isCorrect":false},{"text":"Dislocation of the shoulder joint","isCorrect":false},{"text":"A tear of the rotator cuff","isCorrect":false}]'::jsonb,
 null, 'Slipped Capital Femoral Epiphysis involves displacement of the femoral head relative to the femoral neck at the growth plate, typically occurring during adolescent growth spurts.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common cause of avascular necrosis of the femoral head in adults is:',
 '[{"text":"Long-term corticosteroid use (or chronic alcohol abuse)","isCorrect":true},{"text":"Vitamin C deficiency","isCorrect":false},{"text":"Excessive calcium intake","isCorrect":false},{"text":"Mild, everyday physical activity","isCorrect":false}]'::jsonb,
 null, 'Long-term corticosteroid use and chronic alcohol abuse are among the most common risk factors for avascular necrosis of the femoral head in adults.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Eclampsia is defined as the occurrence of:',
 '[{"text":"Generalized seizures in a woman with preeclampsia","isCorrect":true},{"text":"High blood pressure alone, without seizures","isCorrect":false},{"text":"Gestational diabetes","isCorrect":false},{"text":"Normal labor pain","isCorrect":false}]'::jsonb,
 null, 'Eclampsia is defined as the occurrence of generalized tonic-clonic seizures in a woman with preeclampsia, representing a severe obstetric emergency.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'After uterine atony, the second most common cause of primary postpartum hemorrhage is:',
 '[{"text":"Genital tract trauma (lacerations)","isCorrect":true},{"text":"Ectopic pregnancy","isCorrect":false},{"text":"Molar pregnancy","isCorrect":false},{"text":"Preeclampsia","isCorrect":false}]'::jsonb,
 null, 'After uterine atony, genital tract trauma (lacerations of the cervix, vagina, or perineum) is the next most common cause of primary postpartum hemorrhage.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'Twins resulting from the splitting of a single fertilized egg are called:',
 '[{"text":"Dizygotic (fraternal) twins","isCorrect":false},{"text":"Monozygotic (identical) twins","isCorrect":true},{"text":"Conjoined twins only","isCorrect":false},{"text":"Superfetation twins","isCorrect":false}]'::jsonb,
 null, 'Monozygotic (identical) twins arise from the splitting of a single fertilized egg into two separate embryos, resulting in genetically identical offspring.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Amniotic fluid volume in later pregnancy is primarily regulated by fetal:',
 '[{"text":"Urine production and swallowing","isCorrect":true},{"text":"Hair growth","isCorrect":false},{"text":"Bone development","isCorrect":false},{"text":"Heart rate alone","isCorrect":false}]'::jsonb,
 null, 'In later pregnancy, amniotic fluid volume is primarily regulated by the balance between fetal urine production (adding fluid) and fetal swallowing (removing fluid).'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The normal range for arterial partial pressure of carbon dioxide (PaCO2) is approximately:',
 '[{"text":"10-20 mmHg","isCorrect":false},{"text":"35-45 mmHg","isCorrect":true},{"text":"60-70 mmHg","isCorrect":false},{"text":"80-90 mmHg","isCorrect":false}]'::jsonb,
 null, 'Normal arterial PaCO2 is approximately 35 to 45 mmHg, reflecting adequate alveolar ventilation.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Which induction agent is often preferred for rapid sequence induction in critically ill or hemodynamically unstable patients, due to its cardiovascular stability?',
 '[{"text":"Etomidate","isCorrect":true},{"text":"Ketamine only in all cases","isCorrect":false},{"text":"Thiopental in all cases","isCorrect":false},{"text":"Diazepam","isCorrect":false}]'::jsonb,
 null, 'Etomidate is often favored for induction in hemodynamically unstable patients due to its relatively favorable cardiovascular stability compared to other induction agents.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The "lethal triad" (or "triad of death") in severely injured trauma patients refers to hypothermia, coagulopathy, and:',
 '[{"text":"Acidosis","isCorrect":true},{"text":"Hyperglycemia","isCorrect":false},{"text":"Jaundice","isCorrect":false},{"text":"Hypercalcemia","isCorrect":false}]'::jsonb,
 null, 'The lethal triad of trauma consists of hypothermia, coagulopathy, and metabolic acidosis, which together worsen outcomes in severely injured patients.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'In volume-controlled mechanical ventilation, which setting determines the volume of air delivered with each breath?',
 '[{"text":"Tidal volume","isCorrect":true},{"text":"Respiratory rate alone","isCorrect":false},{"text":"FiO2 (fraction of inspired oxygen)","isCorrect":false},{"text":"PEEP (positive end-expiratory pressure)","isCorrect":false}]'::jsonb,
 null, 'Tidal volume is the ventilator setting that determines the fixed volume of air delivered to the patient with each mechanical breath in volume-controlled ventilation.');
