-- supabase/sql/exam_question_bank_ssc_gd_set1.sql
--
-- First curated question-bank batch for 'SSC-GD Constable' (see exam_patterns_ssc_gd.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Pitched at a 10th-standard level, similar difficulty to SSC-MTS (see
-- exam_question_bank_ssc_mts_set1.sql) -- entry-level constable recruitment rather than a
-- graduate-level clerical exam. Non-Verbal Reasoning again uses text-describable grid/cube/clock
-- puzzles in place of figure-based questions, which need images this schema can't provide. 16
-- chapters (4 per section x 4 sections) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_gd.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General Intelligence and Reasoning: Analogies and Classification
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Pen is to Write as Scissors is to:',
 '[{"text":"Cut","isCorrect":true},{"text":"Sharp","isCorrect":false},{"text":"Paper","isCorrect":false},{"text":"Metal","isCorrect":false}]'::jsonb,
 null, 'A pen is used to write, just as scissors are used to cut.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Delhi","isCorrect":false},{"text":"Mumbai","isCorrect":false},{"text":"Kolkata","isCorrect":false},{"text":"India","isCorrect":true}]'::jsonb,
 null, 'Delhi, Mumbai and Kolkata are cities, while India is a country.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Fish is to Water as Bird is to:',
 '[{"text":"Nest","isCorrect":false},{"text":"Sky","isCorrect":true},{"text":"Tree","isCorrect":false},{"text":"Egg","isCorrect":false}]'::jsonb,
 null, 'A fish lives in water, just as a bird lives/flies in the sky.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Triangle","isCorrect":false},{"text":"Square","isCorrect":false},{"text":"Circle","isCorrect":false},{"text":"Cube","isCorrect":true}]'::jsonb,
 null, 'Triangle, Square and Circle are two-dimensional shapes, while a Cube is a three-dimensional shape.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 3, 6, 9, 12, ?',
 '[{"text":"14","isCorrect":false},{"text":"15","isCorrect":true},{"text":"16","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'The series increases by 3 each time, so the next number is 12 + 3 = 15.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'In a certain code, DOG is written as EPH. How is CAT written in that code?',
 '[{"text":"DBU","isCorrect":true},{"text":"DBV","isCorrect":false},{"text":"EBU","isCorrect":false},{"text":"DCU","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: C->D, A->B, T->U, giving DBU.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 1, 4, 9, 16, 25, ?',
 '[{"text":"30","isCorrect":false},{"text":"35","isCorrect":false},{"text":"36","isCorrect":true},{"text":"49","isCorrect":false}]'::jsonb,
 null, 'This is a series of perfect squares (1^2, 2^2, 3^2...), so the next term is 6^2 = 36.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If RAIN is coded as SBJO, how is SUN coded in the same language?',
 '[{"text":"TVO","isCorrect":true},{"text":"TVN","isCorrect":false},{"text":"TUO","isCorrect":false},{"text":"UVO","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so SUN becomes TVO.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'A is the father of B. B is the sister of C. How is A related to C?',
 '[{"text":"Father","isCorrect":true},{"text":"Uncle","isCorrect":false},{"text":"Brother","isCorrect":false},{"text":"Grandfather","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s father and B is C''s sister, B and C are siblings, so A is also C''s father.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Ravi walks 4 km north, then turns right and walks 3 km. How far is he from his starting point?',
 '[{"text":"5 km","isCorrect":true},{"text":"7 km","isCorrect":false},{"text":"3 km","isCorrect":false},{"text":"4 km","isCorrect":false}]'::jsonb,
 null, 'The path forms a right angle, so by the Pythagorean theorem, the distance is sqrt(4^2 + 3^2) = sqrt(25) = 5 km.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a woman, a man said, "Her mother is the only daughter of my mother." How is the man related to the woman?',
 '[{"text":"Father","isCorrect":false},{"text":"Uncle","isCorrect":true},{"text":"Grandfather","isCorrect":false},{"text":"Brother","isCorrect":false}]'::jsonb,
 null, 'The only daughter of the man''s mother is the man''s sister, so the woman''s mother is the man''s sister -- making the man the woman''s (maternal) uncle.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A man starts walking south, walks 5 km, turns left, walks 3 km, then turns left again and walks 5 km. In which direction and how far is he from the starting point?',
 '[{"text":"3 km East","isCorrect":true},{"text":"3 km West","isCorrect":false},{"text":"8 km South","isCorrect":false},{"text":"5 km North","isCorrect":false}]'::jsonb,
 null, 'Walking south 5 km, then left (east) 3 km, then left (north) 5 km cancels the initial southward distance, leaving him 3 km east of the start.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many total squares (of any size) are there in a figure made of a 2x2 grid of small squares?',
 '[{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A 2x2 grid has 4 small squares plus 1 large square formed by the whole grid, giving 5 squares in total.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A cube is painted on all faces and then cut into 8 equal smaller cubes. How many of the smaller cubes have exactly 3 faces painted?',
 '[{"text":"0","isCorrect":false},{"text":"4","isCorrect":false},{"text":"8","isCorrect":true},{"text":"2","isCorrect":false}]'::jsonb,
 null, 'Cutting a cube into 8 equal pieces (a 2x2x2 cut) makes every piece a corner piece, so all 8 smaller cubes have exactly 3 painted faces.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'What time does a clock show in its mirror image when the actual time is 6:30?',
 '[{"text":"5:30","isCorrect":true},{"text":"6:30","isCorrect":false},{"text":"12:30","isCorrect":false},{"text":"7:30","isCorrect":false}]'::jsonb,
 null, 'A clock''s mirror image time is found by subtracting the actual time from 12:00, so 6:30 mirrors to 5:30.'),
('SSC-GD Constable', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'A pattern of dots forms triangular numbers: 1, 3, 6, 10, ... How many dots are in the 5th figure of the pattern?',
 '[{"text":"15","isCorrect":true},{"text":"12","isCorrect":false},{"text":"10","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Triangular numbers follow n(n+1)/2. For n=5, this is 5x6/2 = 15.'),

-- General Knowledge and General Awareness: Indian History and Culture
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who was the first Prime Minister of India?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"Jawaharlal Nehru","isCorrect":true},{"text":"Sardar Patel","isCorrect":false},{"text":"Rajendra Prasad","isCorrect":false}]'::jsonb,
 null, 'Jawaharlal Nehru became India''s first Prime Minister in 1947.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'In which year did India gain independence?',
 '[{"text":"1945","isCorrect":false},{"text":"1947","isCorrect":true},{"text":"1950","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'India gained independence from British rule on 15 August 1947.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Who built the Taj Mahal?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Shah Jahan","isCorrect":true},{"text":"Aurangzeb","isCorrect":false},{"text":"Jahangir","isCorrect":false}]'::jsonb,
 null, 'The Taj Mahal was built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'In which year did the Jallianwala Bagh massacre take place?',
 '[{"text":"1919","isCorrect":true},{"text":"1920","isCorrect":false},{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'The Jallianwala Bagh massacre took place on 13 April 1919 in Amritsar.'),

-- General Knowledge and General Awareness: Indian Polity and Geography
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Who is the Supreme Commander of the Indian Armed Forces?',
 '[{"text":"President","isCorrect":true},{"text":"Prime Minister","isCorrect":false},{"text":"Chief of Army Staff","isCorrect":false},{"text":"Defence Minister","isCorrect":false}]'::jsonb,
 null, 'The President of India is the Supreme Commander of the Indian Armed Forces.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the smallest state in India by area?',
 '[{"text":"Sikkim","isCorrect":false},{"text":"Goa","isCorrect":true},{"text":"Tripura","isCorrect":false},{"text":"Nagaland","isCorrect":false}]'::jsonb,
 null, 'Goa is the smallest state in India by area, at about 3,702 square kilometers.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'How many states are there in India?',
 '[{"text":"28","isCorrect":true},{"text":"29","isCorrect":false},{"text":"27","isCorrect":false},{"text":"30","isCorrect":false}]'::jsonb,
 null, 'India currently has 28 states and 8 union territories.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which is the highest civilian award in India?',
 '[{"text":"Padma Shri","isCorrect":false},{"text":"Padma Bhushan","isCorrect":false},{"text":"Bharat Ratna","isCorrect":true},{"text":"Padma Vibhushan","isCorrect":false}]'::jsonb,
 null, 'Bharat Ratna is the highest civilian award in India.'),

-- General Knowledge and General Awareness: General Science
('SSC-GD Constable', 'General Knowledge and General Awareness', 'General Science', 'easy', 'mcq',
 'Which organ pumps blood in the human body?',
 '[{"text":"Lungs","isCorrect":false},{"text":"Heart","isCorrect":true},{"text":"Liver","isCorrect":false},{"text":"Kidney","isCorrect":false}]'::jsonb,
 null, 'The heart pumps blood throughout the human body.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'General Science', 'easy', 'mcq',
 'What is the chemical formula of water?',
 '[{"text":"CO2","isCorrect":false},{"text":"H2O","isCorrect":true},{"text":"O2","isCorrect":false},{"text":"NaCl","isCorrect":false}]'::jsonb,
 null, 'Water is chemically represented as H2O, made of two hydrogen atoms and one oxygen atom.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'General Science', 'medium', 'mcq',
 'Which vitamin is produced in the human body when skin is exposed to sunlight?',
 '[{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":true},{"text":"Vitamin K","isCorrect":false}]'::jsonb,
 null, 'Vitamin D is synthesized in the skin upon exposure to sunlight.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'General Science', 'medium', 'mcq',
 'Which part of a plant primarily carries out photosynthesis?',
 '[{"text":"Root","isCorrect":false},{"text":"Stem","isCorrect":false},{"text":"Leaf","isCorrect":true},{"text":"Flower","isCorrect":false}]'::jsonb,
 null, 'The leaf, containing chlorophyll, is the primary site of photosynthesis in a plant.'),

-- General Knowledge and General Awareness: Current Affairs and Sports
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Current Affairs and Sports', 'easy', 'mcq',
 'How many players are there in a cricket team on the field?',
 '[{"text":"9","isCorrect":false},{"text":"10","isCorrect":false},{"text":"11","isCorrect":true},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'A cricket team fields 11 players at a time.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Current Affairs and Sports', 'easy', 'mcq',
 'The Summer Olympic Games are held every how many years?',
 '[{"text":"2","isCorrect":false},{"text":"3","isCorrect":false},{"text":"4","isCorrect":true},{"text":"5","isCorrect":false}]'::jsonb,
 null, 'The Summer Olympic Games are held once every 4 years.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Current Affairs and Sports', 'medium', 'mcq',
 'Which sport is associated with the term "Grand Slam"?',
 '[{"text":"Cricket","isCorrect":false},{"text":"Tennis","isCorrect":true},{"text":"Football","isCorrect":false},{"text":"Hockey","isCorrect":false}]'::jsonb,
 null, 'The term "Grand Slam" refers to winning all four major tennis championships in a calendar year.'),
('SSC-GD Constable', 'General Knowledge and General Awareness', 'Current Affairs and Sports', 'medium', 'mcq',
 'In which year did India first win the ICC Cricket World Cup?',
 '[{"text":"1975","isCorrect":false},{"text":"1983","isCorrect":true},{"text":"2007","isCorrect":false},{"text":"2011","isCorrect":false}]'::jsonb,
 null, 'India won its first ICC Cricket World Cup in 1983 under the captaincy of Kapil Dev.'),

-- Elementary Mathematics: Number System and Simplification
('SSC-GD Constable', 'Elementary Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 36 / 6 x 2',
 '[{"text":"3","isCorrect":false},{"text":"12","isCorrect":true},{"text":"6","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'Following order of operations: 36/6 = 6, then 6 x 2 = 12.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following is an even number?',
 '[{"text":"17","isCorrect":false},{"text":"23","isCorrect":false},{"text":"34","isCorrect":true},{"text":"41","isCorrect":false}]'::jsonb,
 null, '34 is divisible by 2, making it an even number.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the LCM of 4 and 6.',
 '[{"text":"10","isCorrect":false},{"text":"12","isCorrect":true},{"text":"24","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'The multiples of 4 are 4, 8, 12... and of 6 are 6, 12... so the LCM is 12.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the HCF of 12 and 18.',
 '[{"text":"3","isCorrect":false},{"text":"6","isCorrect":true},{"text":"9","isCorrect":false},{"text":"2","isCorrect":false}]'::jsonb,
 null, 'The highest common factor of 12 and 18 is 6.'),

-- Elementary Mathematics: Percentage and Ratio
('SSC-GD Constable', 'Elementary Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 '10% of 500 is:',
 '[{"text":"5","isCorrect":false},{"text":"50","isCorrect":true},{"text":"500","isCorrect":false},{"text":"100","isCorrect":false}]'::jsonb,
 null, '10% of 500 = (10/100) x 500 = 50.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 'Express the ratio 3:4 as a percentage.',
 '[{"text":"34%","isCorrect":false},{"text":"75%","isCorrect":true},{"text":"43%","isCorrect":false},{"text":"40%","isCorrect":false}]'::jsonb,
 null, '3:4 as a fraction is 3/4, which equals 75%.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'If A:B = 2:3 and B:C = 3:4, find A:B:C.',
 '[{"text":"2:3:4","isCorrect":true},{"text":"2:4:3","isCorrect":false},{"text":"3:2:4","isCorrect":false},{"text":"4:3:2","isCorrect":false}]'::jsonb,
 null, 'Since B is common to both ratios with the same value (3), the combined ratio is A:B:C = 2:3:4.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 '20% of a number is 40. Find the number.',
 '[{"text":"200","isCorrect":true},{"text":"100","isCorrect":false},{"text":"80","isCorrect":false},{"text":"160","isCorrect":false}]'::jsonb,
 null, 'If 20% of x = 40, then x = 40 / 0.20 = 200.'),

-- Elementary Mathematics: Profit Loss and Simple Interest
('SSC-GD Constable', 'Elementary Mathematics', 'Profit Loss and Simple Interest', 'easy', 'mcq',
 'A man buys an item for Rs. 50 and sells it for Rs. 60. Find his profit.',
 '[{"text":"Rs. 5","isCorrect":false},{"text":"Rs. 10","isCorrect":true},{"text":"Rs. 15","isCorrect":false},{"text":"Rs. 20","isCorrect":false}]'::jsonb,
 null, 'Profit = Selling Price - Cost Price = 60 - 50 = Rs. 10.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Profit Loss and Simple Interest', 'easy', 'mcq',
 'If the cost price of an item is Rs. 100 and the selling price is Rs. 90, find the loss percentage.',
 '[{"text":"5%","isCorrect":false},{"text":"10%","isCorrect":true},{"text":"15%","isCorrect":false},{"text":"20%","isCorrect":false}]'::jsonb,
 null, 'Loss = 100 - 90 = 10. Loss percentage = (10/100) x 100 = 10%.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Profit Loss and Simple Interest', 'medium', 'mcq',
 'Find the simple interest on Rs. 1000 at 10% per annum for 2 years.',
 '[{"text":"Rs. 100","isCorrect":false},{"text":"Rs. 200","isCorrect":true},{"text":"Rs. 150","isCorrect":false},{"text":"Rs. 250","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = (Principal x Rate x Time) / 100 = (1000 x 10 x 2) / 100 = Rs. 200.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Profit Loss and Simple Interest', 'medium', 'mcq',
 'A shopkeeper sells an item at a 20% profit for Rs. 600. Find the cost price.',
 '[{"text":"Rs. 480","isCorrect":false},{"text":"Rs. 500","isCorrect":true},{"text":"Rs. 520","isCorrect":false},{"text":"Rs. 450","isCorrect":false}]'::jsonb,
 null, 'If cost price is x, then x + 0.20x = 600, so 1.2x = 600, giving x = Rs. 500.'),

-- Elementary Mathematics: Mensuration and Basic Geometry
('SSC-GD Constable', 'Elementary Mathematics', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'How many sides does a pentagon have?',
 '[{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"7","isCorrect":false}]'::jsonb,
 null, 'A pentagon is a polygon with 5 sides.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Mensuration and Basic Geometry', 'easy', 'mcq',
 'Find the area of a square with side 6 cm.',
 '[{"text":"24 cm^2","isCorrect":false},{"text":"36 cm^2","isCorrect":true},{"text":"12 cm^2","isCorrect":false},{"text":"30 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a square = side x side = 6 x 6 = 36 cm^2.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Mensuration and Basic Geometry', 'medium', 'mcq',
 'Find the volume of a cube with side 3 cm.',
 '[{"text":"9 cm^3","isCorrect":false},{"text":"18 cm^3","isCorrect":false},{"text":"27 cm^3","isCorrect":true},{"text":"12 cm^3","isCorrect":false}]'::jsonb,
 null, 'Volume of a cube = side^3 = 3^3 = 27 cm^3.'),
('SSC-GD Constable', 'Elementary Mathematics', 'Mensuration and Basic Geometry', 'medium', 'mcq',
 'Find the perimeter of a rectangle with length 10 cm and breadth 6 cm.',
 '[{"text":"16 cm","isCorrect":false},{"text":"32 cm","isCorrect":true},{"text":"60 cm","isCorrect":false},{"text":"26 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a rectangle = 2 x (length + breadth) = 2 x (10 + 6) = 32 cm.'),

-- English: Grammar and Error Spotting
('SSC-GD Constable', 'English', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Choose the correct sentence.',
 '[{"text":"She go to market.","isCorrect":false},{"text":"She goes to market.","isCorrect":true},{"text":"She going to market.","isCorrect":false},{"text":"She gone to market.","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject in the present tense, the verb takes an -s: "goes".'),
('SSC-GD Constable', 'English', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Fill in the blank: "I ___ a student."',
 '[{"text":"am","isCorrect":true},{"text":"is","isCorrect":false},{"text":"are","isCorrect":false},{"text":"be","isCorrect":false}]'::jsonb,
 null, 'The first-person singular subject "I" takes the verb "am".'),
('SSC-GD Constable', 'English', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Identify the error in: "He are playing football now."',
 '[{"text":"He","isCorrect":false},{"text":"are","isCorrect":true},{"text":"playing","isCorrect":false},{"text":"football","isCorrect":false}]'::jsonb,
 null, 'The subject "He" is third-person singular, so the verb should be "is", not "are".'),
('SSC-GD Constable', 'English', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Choose the correct plural form of "child".',
 '[{"text":"Childs","isCorrect":false},{"text":"Childes","isCorrect":false},{"text":"Children","isCorrect":true},{"text":"Childern","isCorrect":false}]'::jsonb,
 null, '"Child" has an irregular plural form: "children".'),

-- English: Vocabulary (Synonyms, Antonyms, Spelling)
('SSC-GD Constable', 'English', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the synonym of "Big".',
 '[{"text":"Small","isCorrect":false},{"text":"Large","isCorrect":true},{"text":"Tiny","isCorrect":false},{"text":"Short","isCorrect":false}]'::jsonb,
 null, '"Large" means great in size, making it a synonym of "Big".'),
('SSC-GD Constable', 'English', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the antonym of "Fast".',
 '[{"text":"Quick","isCorrect":false},{"text":"Slow","isCorrect":true},{"text":"Speedy","isCorrect":false},{"text":"Rapid","isCorrect":false}]'::jsonb,
 null, '"Slow" is the opposite of "Fast".'),
('SSC-GD Constable', 'English', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the synonym of "Brave".',
 '[{"text":"Coward","isCorrect":false},{"text":"Fearful","isCorrect":false},{"text":"Courageous","isCorrect":true},{"text":"Timid","isCorrect":false}]'::jsonb,
 null, '"Courageous" means having courage, making it a synonym of "Brave".'),
('SSC-GD Constable', 'English', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the antonym of "Difficult".',
 '[{"text":"Hard","isCorrect":false},{"text":"Easy","isCorrect":true},{"text":"Tough","isCorrect":false},{"text":"Complex","isCorrect":false}]'::jsonb,
 null, '"Easy" is the opposite of "Difficult".'),

-- English: Fill in the Blanks and Cloze Test
('SSC-GD Constable', 'English', 'Fill in the Blanks and Cloze Test', 'easy', 'mcq',
 'Fill in the blank: "I go to school ___ bus."',
 '[{"text":"by","isCorrect":true},{"text":"in","isCorrect":false},{"text":"on","isCorrect":false},{"text":"with","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition for a mode of transport is "by bus".'),
('SSC-GD Constable', 'English', 'Fill in the Blanks and Cloze Test', 'easy', 'mcq',
 'Fill in the blank: "She is fond ___ music."',
 '[{"text":"with","isCorrect":false},{"text":"of","isCorrect":true},{"text":"for","isCorrect":false},{"text":"at","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "fond of" something.'),
('SSC-GD Constable', 'English', 'Fill in the Blanks and Cloze Test', 'medium', 'mcq',
 'Fill in the blank: "He was absent ___ the meeting."',
 '[{"text":"for","isCorrect":false},{"text":"from","isCorrect":true},{"text":"at","isCorrect":false},{"text":"in","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "absent from" a place or event.'),
('SSC-GD Constable', 'English', 'Fill in the Blanks and Cloze Test', 'medium', 'mcq',
 'Fill in the blank: "They arrived ___ the airport on time."',
 '[{"text":"in","isCorrect":false},{"text":"on","isCorrect":false},{"text":"at","isCorrect":true},{"text":"to","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition for arriving at a specific location like an airport is "at".'),

-- English: Reading Comprehension
('SSC-GD Constable', 'English', 'Reading Comprehension', 'easy', 'mcq',
 'Choose the word closest in meaning to "brave" as used in a passage about soldiers.',
 '[{"text":"Cowardly","isCorrect":false},{"text":"Courageous","isCorrect":true},{"text":"Weak","isCorrect":false},{"text":"Timid","isCorrect":false}]'::jsonb,
 null, '"Courageous" is closest in meaning to "brave".'),
('SSC-GD Constable', 'English', 'Reading Comprehension', 'medium', 'mcq',
 'What does the saying "Actions speak louder than words" mean?',
 '[{"text":"Words are more important","isCorrect":false},{"text":"What you do matters more than what you say","isCorrect":true},{"text":"Silence is golden","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'This saying means that a person''s actions demonstrate their true intentions better than their words.'),
('SSC-GD Constable', 'English', 'Reading Comprehension', 'medium', 'mcq',
 'Choose the grammatically correct sentence.',
 '[{"text":"She don''t know the answer.","isCorrect":false},{"text":"She doesn''t knows the answer.","isCorrect":false},{"text":"She doesn''t know the answer.","isCorrect":true},{"text":"She not know the answer.","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject, the correct negative form uses "doesn''t" followed by the base verb "know".'),
('SSC-GD Constable', 'English', 'Reading Comprehension', 'hard', 'mcq',
 'What does the proverb "A stitch in time saves nine" mean?',
 '[{"text":"Sewing saves time","isCorrect":false},{"text":"Timely action prevents bigger problems later","isCorrect":true},{"text":"Nine stitches are always needed","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'This proverb means that dealing with a small problem promptly prevents it from becoming a much bigger problem later.');
