-- supabase/sql/exam_question_bank_wbjee_set1.sql
--
-- First curated question-bank batch for 'WBJEE' (see exam_patterns_wbjee.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Real WBJEE questions span 3 marking categories (see exam_patterns_wbjee.sql), including a
-- one-or-more-correct category -- but to keep this batch's format consistent and simple, every
-- row here is format='mcq' with a single isCorrect:true option (the same simplification already
-- used for NEET/BITSAT/MHT-CET). 16 chapters (5 Physics, 5 Chemistry, 6 Mathematics) each get 4
-- classic, JEE-Main-adjacent-difficulty questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_wbjee.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('WBJEE', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The dimensional formula of torque is the same as the dimensional formula of:',
 '[{"text":"Force","isCorrect":false},{"text":"Work (energy)","isCorrect":true},{"text":"Power","isCorrect":false},{"text":"Momentum","isCorrect":false}]'::jsonb,
 null, 'Torque = force x perpendicular distance, giving dimensions [ML^2T^-2], identical to those of work/energy, even though the two quantities are physically distinct (torque is a vector product, work is a scalar).'),
('WBJEE', 'Physics', 'Mechanics', 'easy', 'mcq',
 'A particle moving with uniform (constant) velocity has:',
 '[{"text":"Zero acceleration","isCorrect":true},{"text":"Constant non-zero acceleration","isCorrect":false},{"text":"Increasing acceleration","isCorrect":false},{"text":"Acceleration equal to its velocity","isCorrect":false}]'::jsonb,
 null, 'Uniform velocity means both speed and direction are constant, so the rate of change of velocity -- acceleration -- is zero.'),
('WBJEE', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The coefficient of restitution for a perfectly inelastic collision is:',
 '[{"text":"1","isCorrect":false},{"text":"0","isCorrect":true},{"text":"Greater than 1","isCorrect":false},{"text":"-1","isCorrect":false}]'::jsonb,
 null, 'In a perfectly inelastic collision, the colliding bodies stick together and move with a common velocity afterward, giving a coefficient of restitution of 0.'),
('WBJEE', 'Physics', 'Mechanics', 'easy', 'mcq',
 'For a particle moving in a circle of radius r with angular velocity omega, the linear speed v is given by:',
 '[{"text":"v = omega/r","isCorrect":false},{"text":"v = omega * r","isCorrect":true},{"text":"v = omega + r","isCorrect":false},{"text":"v = r/omega","isCorrect":false}]'::jsonb,
 null, 'Linear speed and angular velocity are related by v = omega*r for circular motion.'),

-- Physics: Electrodynamics
('WBJEE', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The electric potential due to an isolated point charge, measured at an infinite distance from it, is:',
 '[{"text":"Infinite","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Equal to the charge itself","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'Electric potential V = kQ/r approaches zero as r approaches infinity, so the reference potential at infinite distance from a point charge is taken as zero.'),
('WBJEE', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'A transformer operates based on the principle of:',
 '[{"text":"Self-induction only","isCorrect":false},{"text":"Mutual induction","isCorrect":true},{"text":"Electrostatic induction","isCorrect":false},{"text":"Thermionic emission","isCorrect":false}]'::jsonb,
 null, 'A transformer works on mutual induction -- a changing current in the primary coil induces an EMF in the secondary coil through their shared magnetic flux.'),
('WBJEE', 'Physics', 'Electrodynamics', 'hard', 'mcq',
 'The average power dissipated in a pure inductor connected to an AC source, over one complete cycle, is:',
 '[{"text":"Maximum","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Equal to V*I","isCorrect":false},{"text":"Equal to half of V*I","isCorrect":false}]'::jsonb,
 null, 'In a pure inductor, current lags voltage by 90 degrees, so the average power over a full cycle (proportional to cos(90 degrees)=0) is zero.'),
('WBJEE', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of capacitance is the:',
 '[{"text":"Farad","isCorrect":true},{"text":"Henry","isCorrect":false},{"text":"Weber","isCorrect":false},{"text":"Tesla","isCorrect":false}]'::jsonb,
 null, 'Capacitance, the ability of a system to store charge per unit potential difference, is measured in farads (F).'),

-- Physics: Optics
('WBJEE', 'Physics', 'Optics', 'easy', 'mcq',
 'The focal length of a plane mirror is:',
 '[{"text":"Zero","isCorrect":false},{"text":"Infinity","isCorrect":true},{"text":"Equal to its width","isCorrect":false},{"text":"Negative","isCorrect":false}]'::jsonb,
 null, 'A plane mirror can be thought of as a spherical mirror with infinite radius of curvature, giving it an infinite focal length.'),
('WBJEE', 'Physics', 'Optics', 'medium', 'mcq',
 'Total internal reflection occurs when light travels:',
 '[{"text":"From a rarer medium to a denser medium","isCorrect":false},{"text":"From a denser medium to a rarer medium, beyond the critical angle","isCorrect":true},{"text":"Through a vacuum only","isCorrect":false},{"text":"Along the normal to the interface","isCorrect":false}]'::jsonb,
 null, 'Total internal reflection occurs when light travels from an optically denser medium to a rarer medium and strikes the interface at an angle greater than the critical angle.'),
('WBJEE', 'Physics', 'Optics', 'hard', 'mcq',
 'The resolving power of a microscope increases with:',
 '[{"text":"Increasing wavelength of light used","isCorrect":false},{"text":"Decreasing wavelength of light used","isCorrect":true},{"text":"Increasing the eyepiece focal length only","isCorrect":false},{"text":"Decreasing the objective aperture","isCorrect":false}]'::jsonb,
 null, 'Resolving power is inversely proportional to wavelength, so using shorter-wavelength light (or higher numerical aperture) improves the ability to distinguish closely spaced objects.'),
('WBJEE', 'Physics', 'Optics', 'medium', 'mcq',
 'A rainbow is formed in the sky primarily due to which combination of optical phenomena in water droplets?',
 '[{"text":"Diffraction and polarization","isCorrect":false},{"text":"Dispersion, refraction, and total internal reflection","isCorrect":true},{"text":"Interference only","isCorrect":false},{"text":"Scattering only","isCorrect":false}]'::jsonb,
 null, 'Sunlight entering a water droplet is refracted, undergoes total internal reflection at the back of the droplet, and disperses into its component colors, producing the rainbow.'),

-- Physics: Modern Physics and Semiconductor Devices
('WBJEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'In a full-wave rectifier circuit, the frequency of the output (ripple) compared to the input AC frequency is:',
 '[{"text":"The same as the input frequency","isCorrect":false},{"text":"Twice the input frequency","isCorrect":true},{"text":"Half the input frequency","isCorrect":false},{"text":"Four times the input frequency","isCorrect":false}]'::jsonb,
 null, 'A full-wave rectifier conducts during both halves of the input AC cycle, producing an output pulse for each half-cycle, so the output ripple frequency is twice the input frequency.'),
('WBJEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The threshold frequency in the photoelectric effect refers to:',
 '[{"text":"The frequency at which maximum photoelectrons are emitted","isCorrect":false},{"text":"The minimum frequency below which no photoemission occurs, regardless of intensity","isCorrect":true},{"text":"The frequency of the incident light source only","isCorrect":false},{"text":"The frequency corresponding to maximum kinetic energy","isCorrect":false}]'::jsonb,
 null, 'Below the threshold frequency, no photoelectrons are emitted no matter how intense the light is, since each individual photon lacks the energy needed to overcome the work function.'),
('WBJEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The binding energy per nucleon is highest for nuclei with mass number close to:',
 '[{"text":"1","isCorrect":false},{"text":"56 (near iron)","isCorrect":true},{"text":"238","isCorrect":false},{"text":"300","isCorrect":false}]'::jsonb,
 null, 'The binding energy per nucleon curve peaks around mass number 56, near iron, making these nuclei the most stable per nucleon.'),
('WBJEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'In an n-type semiconductor, the doping impurity added to pure silicon or germanium is:',
 '[{"text":"Trivalent (group 13)","isCorrect":false},{"text":"Pentavalent (group 15)","isCorrect":true},{"text":"Tetravalent (group 14)","isCorrect":false},{"text":"A noble gas element","isCorrect":false}]'::jsonb,
 null, 'An n-type semiconductor is created by doping with a pentavalent (group 15) impurity, which contributes extra free electrons as majority carriers.'),

-- Physics: Heat and Thermodynamics
('WBJEE', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'The change in internal energy of a given amount of an ideal gas depends only on its:',
 '[{"text":"Volume","isCorrect":false},{"text":"Temperature","isCorrect":true},{"text":"Pressure alone","isCorrect":false},{"text":"Shape of the container","isCorrect":false}]'::jsonb,
 null, 'For an ideal gas, internal energy is a function of temperature alone, so a change in internal energy depends only on the change in temperature.'),
('WBJEE', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'For an adiabatic process on an ideal gas, the relationship between pressure P and volume V is:',
 '[{"text":"PV = constant","isCorrect":false},{"text":"PV^gamma = constant","isCorrect":true},{"text":"P/V = constant","isCorrect":false},{"text":"P + V = constant","isCorrect":false}]'::jsonb,
 null, 'For an adiabatic process, PV^gamma = constant, where gamma is the ratio of specific heats of the gas.'),
('WBJEE', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'The number of translational degrees of freedom for a monatomic ideal gas molecule is:',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":false},{"text":"3","isCorrect":true},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'A monatomic gas molecule, treated as a point mass, has 3 translational degrees of freedom (along the x, y, and z axes) and no rotational or vibrational modes.'),
('WBJEE', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'Which thermodynamic process involves zero heat exchange between the system and its surroundings?',
 '[{"text":"Isothermal process","isCorrect":false},{"text":"Adiabatic process","isCorrect":true},{"text":"Isobaric process","isCorrect":false},{"text":"Isochoric process","isCorrect":false}]'::jsonb,
 null, 'An adiabatic process is defined by the condition Q=0, meaning no heat is exchanged with the surroundings.'),

-- Chemistry: Physical Chemistry
('WBJEE', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'According to Le Chatelier''s principle, increasing the temperature of an exothermic reaction at equilibrium shifts the equilibrium toward:',
 '[{"text":"The products","isCorrect":false},{"text":"The reactants","isCorrect":true},{"text":"Neither side; no shift occurs","isCorrect":false},{"text":"Whichever side has fewer moles of gas","isCorrect":false}]'::jsonb,
 null, 'Since an exothermic reaction releases heat, increasing temperature favors the endothermic (reverse) direction, shifting equilibrium back toward the reactants.'),
('WBJEE', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The SI unit of surface tension is:',
 '[{"text":"N/m","isCorrect":true},{"text":"N*m","isCorrect":false},{"text":"N/m^2","isCorrect":false},{"text":"J/m^2 only","isCorrect":false}]'::jsonb,
 null, 'Surface tension, defined as force per unit length along the surface, has SI unit N/m (equivalent to J/m^2).'),
('WBJEE', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'Osmotic pressure, as a colligative property, depends primarily on:',
 '[{"text":"The nature (identity) of the solute particles","isCorrect":false},{"text":"The number of solute particles in solution","isCorrect":true},{"text":"The color of the solute","isCorrect":false},{"text":"The molar mass of the solvent","isCorrect":false}]'::jsonb,
 null, 'Colligative properties, including osmotic pressure, depend on the number of solute particles present in a solution, not their chemical identity.'),
('WBJEE', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'Molality of a solution is defined as:',
 '[{"text":"Moles of solute per liter of solution","isCorrect":false},{"text":"Moles of solute per kilogram of solvent","isCorrect":true},{"text":"Grams of solute per liter of solution","isCorrect":false},{"text":"Moles of solute per mole of solvent","isCorrect":false}]'::jsonb,
 null, 'Molality is defined as moles of solute dissolved per kilogram of solvent, distinguishing it from molarity, which uses solution volume.'),

-- Chemistry: Organic Chemistry
('WBJEE', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Which of the following compounds exhibits geometrical (cis-trans) isomerism?',
 '[{"text":"But-2-ene","isCorrect":true},{"text":"Propane","isCorrect":false},{"text":"Methanol","isCorrect":false},{"text":"Ethane","isCorrect":false}]'::jsonb,
 null, 'But-2-ene has a C=C double bond with two different groups on each carbon, restricting rotation and allowing cis and trans configurations.'),
('WBJEE', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The reaction between an alcohol and a carboxylic acid to form an ester is called:',
 '[{"text":"Esterification","isCorrect":true},{"text":"Saponification","isCorrect":false},{"text":"Hydrolysis","isCorrect":false},{"text":"Halogenation","isCorrect":false}]'::jsonb,
 null, 'Esterification is the acid-catalyzed reaction of a carboxylic acid with an alcohol to produce an ester and water.'),
('WBJEE', 'Chemistry', 'Organic Chemistry', 'hard', 'mcq',
 'Among acetic acid and trichloroacetic acid, which is the stronger acid, and why?',
 '[{"text":"Acetic acid, because methyl is electron-donating","isCorrect":false},{"text":"Trichloroacetic acid, because chlorine atoms are electron-withdrawing","isCorrect":true},{"text":"Both are equally strong","isCorrect":false},{"text":"Acetic acid, because it has fewer atoms","isCorrect":false}]'::jsonb,
 null, 'The three electron-withdrawing chlorine atoms in trichloroacetic acid stabilize the conjugate base (carboxylate) by dispersing negative charge, making it a considerably stronger acid than acetic acid.'),
('WBJEE', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Aniline (C6H5NH2) is an example of a:',
 '[{"text":"Secondary aliphatic amine","isCorrect":false},{"text":"Primary aromatic amine","isCorrect":true},{"text":"Tertiary aromatic amine","isCorrect":false},{"text":"Quaternary ammonium salt","isCorrect":false}]'::jsonb,
 null, 'Aniline has one -NH2 group directly attached to a benzene ring, making it a primary aromatic amine.'),

-- Chemistry: Inorganic Chemistry
('WBJEE', 'Chemistry', 'Inorganic Chemistry', 'hard', 'mcq',
 'Among the alkali metals, which has the highest melting point?',
 '[{"text":"Lithium","isCorrect":true},{"text":"Sodium","isCorrect":false},{"text":"Potassium","isCorrect":false},{"text":"Cesium","isCorrect":false}]'::jsonb,
 null, 'Lithium, being the smallest alkali metal, has the strongest metallic bonding among the group, giving it the highest melting point of the alkali metals.'),
('WBJEE', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The hybridization of carbon atoms in diamond is:',
 '[{"text":"sp","isCorrect":false},{"text":"sp2","isCorrect":false},{"text":"sp3","isCorrect":true},{"text":"sp3d","isCorrect":false}]'::jsonb,
 null, 'Each carbon in diamond is bonded to four other carbons in a tetrahedral arrangement, corresponding to sp3 hybridization.'),
('WBJEE', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'When dilute HCl reacts with sodium bicarbonate, which gas is evolved?',
 '[{"text":"Hydrogen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":true},{"text":"Chlorine","isCorrect":false},{"text":"Oxygen","isCorrect":false}]'::jsonb,
 null, 'Sodium bicarbonate reacts with dilute HCl to release carbon dioxide gas, along with water and sodium chloride.'),
('WBJEE', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The oxidation number of sulfur in H2SO4 is:',
 '[{"text":"+4","isCorrect":false},{"text":"+6","isCorrect":true},{"text":"+2","isCorrect":false},{"text":"+8","isCorrect":false}]'::jsonb,
 null, 'In H2SO4, H is +1 and O is -2; balancing the neutral molecule''s charge gives sulfur an oxidation state of +6.'),

-- Chemistry: Chemical Bonding and States of Matter
('WBJEE', 'Chemistry', 'Chemical Bonding and States of Matter', 'medium', 'mcq',
 'According to VSEPR theory, the shape of a water molecule is:',
 '[{"text":"Linear","isCorrect":false},{"text":"Bent (angular)","isCorrect":true},{"text":"Trigonal planar","isCorrect":false},{"text":"Tetrahedral","isCorrect":false}]'::jsonb,
 null, 'Water has 2 bond pairs and 2 lone pairs around oxygen; the lone pairs compress the H-O-H angle, giving a bent (angular) molecular shape.'),
('WBJEE', 'Chemistry', 'Chemical Bonding and States of Matter', 'medium', 'mcq',
 'Hydrogen bonding is strongest in which of the following compounds?',
 '[{"text":"HCl","isCorrect":false},{"text":"HF","isCorrect":true},{"text":"HBr","isCorrect":false},{"text":"HI","isCorrect":false}]'::jsonb,
 null, 'Fluorine''s small size and very high electronegativity make the H-F bond highly polar, giving HF the strongest hydrogen bonding among the hydrogen halides.'),
('WBJEE', 'Chemistry', 'Chemical Bonding and States of Matter', 'medium', 'mcq',
 'The ideal gas equation fails to accurately describe the behavior of real gases under conditions of:',
 '[{"text":"Low pressure and high temperature","isCorrect":false},{"text":"High pressure and low temperature","isCorrect":true},{"text":"Standard temperature and pressure","isCorrect":false},{"text":"Very low density conditions","isCorrect":false}]'::jsonb,
 null, 'At high pressure and low temperature, intermolecular forces and the finite volume of gas molecules become significant, causing real gases to deviate substantially from ideal behavior.'),
('WBJEE', 'Chemistry', 'Chemical Bonding and States of Matter', 'medium', 'mcq',
 'The bond order of the N2 molecule, according to molecular orbital theory, is:',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":false},{"text":"3","isCorrect":true},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'N2 has a triple bond (one sigma and two pi bonds), giving it a bond order of 3 and accounting for its exceptional stability.'),

-- Chemistry: Environmental and Analytical Chemistry
('WBJEE', 'Chemistry', 'Environmental and Analytical Chemistry', 'easy', 'mcq',
 'Which gas is primarily responsible for acid rain, alongside nitrogen oxides?',
 '[{"text":"Sulfur dioxide","isCorrect":true},{"text":"Carbon monoxide","isCorrect":false},{"text":"Methane","isCorrect":false},{"text":"Helium","isCorrect":false}]'::jsonb,
 null, 'Sulfur dioxide, released from burning fossil fuels, reacts with atmospheric moisture to form sulfuric acid, a major contributor to acid rain.'),
('WBJEE', 'Chemistry', 'Environmental and Analytical Chemistry', 'easy', 'mcq',
 'The abbreviation BOD stands for:',
 '[{"text":"Biochemical Oxygen Demand","isCorrect":true},{"text":"Basic Organic Density","isCorrect":false},{"text":"Biological Ozone Depletion","isCorrect":false},{"text":"Bonded Oxide Deposit","isCorrect":false}]'::jsonb,
 null, 'BOD (Biochemical/Biological Oxygen Demand) measures the amount of dissolved oxygen consumed by microorganisms decomposing organic matter in water, indicating organic pollution.'),
('WBJEE', 'Chemistry', 'Environmental and Analytical Chemistry', 'medium', 'mcq',
 'The analytical technique used to separate the components of a mixture based on differential adsorption on a stationary phase is called:',
 '[{"text":"Chromatography","isCorrect":true},{"text":"Titration","isCorrect":false},{"text":"Distillation only","isCorrect":false},{"text":"Crystallization","isCorrect":false}]'::jsonb,
 null, 'Chromatography separates mixture components based on their differing rates of movement through a stationary phase, driven by differential adsorption or partition.'),
('WBJEE', 'Chemistry', 'Environmental and Analytical Chemistry', 'easy', 'mcq',
 'Which of the following is a greenhouse gas that contributes to global warming?',
 '[{"text":"Methane","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Argon","isCorrect":false},{"text":"Helium","isCorrect":false}]'::jsonb,
 null, 'Methane is a potent greenhouse gas, trapping infrared radiation in the atmosphere and contributing significantly to global warming despite its lower concentration than CO2.'),

-- Mathematics: Algebra
('WBJEE', 'Mathematics', 'Algebra', 'medium', 'mcq',
 'If the discriminant of a quadratic equation is negative, the roots of the equation are:',
 '[{"text":"Real and equal","isCorrect":false},{"text":"Real and distinct","isCorrect":false},{"text":"Complex conjugates (imaginary)","isCorrect":true},{"text":"Always rational","isCorrect":false}]'::jsonb,
 null, 'A negative discriminant (b^2-4ac<0) means the quadratic formula involves the square root of a negative number, producing a pair of complex conjugate roots.'),
('WBJEE', 'Mathematics', 'Algebra', 'easy', 'mcq',
 'The nth term of a geometric progression with first term a and common ratio r is given by:',
 '[{"text":"a + (n-1)r","isCorrect":false},{"text":"a * r^(n-1)","isCorrect":true},{"text":"a * n * r","isCorrect":false},{"text":"a / r^n","isCorrect":false}]'::jsonb,
 null, 'The nth term of a GP is a*r^(n-1), since each successive term is obtained by multiplying the previous term by the common ratio r.'),
('WBJEE', 'Mathematics', 'Algebra', 'medium', 'mcq',
 'For two sets A and B, n(A union B) is given by:',
 '[{"text":"n(A) + n(B)","isCorrect":false},{"text":"n(A) + n(B) - n(A intersect B)","isCorrect":true},{"text":"n(A) * n(B)","isCorrect":false},{"text":"n(A) - n(B)","isCorrect":false}]'::jsonb,
 null, 'The inclusion-exclusion principle gives n(A union B) = n(A) + n(B) - n(A intersect B), avoiding double-counting elements in both sets.'),
('WBJEE', 'Mathematics', 'Algebra', 'medium', 'mcq',
 'The sum of an infinite geometric series with first term a and common ratio r, where |r| < 1, is:',
 '[{"text":"a * r","isCorrect":false},{"text":"a / (1 - r)","isCorrect":true},{"text":"a / (1 + r)","isCorrect":false},{"text":"a * (1 - r)","isCorrect":false}]'::jsonb,
 null, 'For |r| < 1, an infinite geometric series converges to the sum a / (1 - r).'),

-- Mathematics: Differentiation and Applications
('WBJEE', 'Mathematics', 'Differentiation and Applications', 'easy', 'mcq',
 'The derivative of tan(x) with respect to x is:',
 '[{"text":"sec^2(x)","isCorrect":true},{"text":"sec(x)*tan(x)","isCorrect":false},{"text":"-csc^2(x)","isCorrect":false},{"text":"cot(x)","isCorrect":false}]'::jsonb,
 null, 'By standard differentiation rules, d/dx[tan(x)] = sec^2(x).'),
('WBJEE', 'Mathematics', 'Differentiation and Applications', 'easy', 'mcq',
 'If y = x^n, then dy/dx is:',
 '[{"text":"n * x^(n-1)","isCorrect":true},{"text":"x^(n-1)","isCorrect":false},{"text":"n * x^n","isCorrect":false},{"text":"x^n / n","isCorrect":false}]'::jsonb,
 null, 'The power rule states that for y = x^n, dy/dx = n*x^(n-1).'),
('WBJEE', 'Mathematics', 'Differentiation and Applications', 'medium', 'mcq',
 'The sign of the second derivative f''''(x) at a point is used to determine:',
 '[{"text":"Whether the function is increasing or decreasing","isCorrect":false},{"text":"The concavity of the function (and nature of extrema)","isCorrect":true},{"text":"The domain of the function","isCorrect":false},{"text":"The continuity of the function","isCorrect":false}]'::jsonb,
 null, 'The second derivative test uses the sign of f''''(x) at a critical point to determine concavity -- positive indicates a local minimum (concave up), negative a local maximum (concave down).'),
('WBJEE', 'Mathematics', 'Differentiation and Applications', 'medium', 'mcq',
 'The product rule for differentiating y = u*v (both functions of x) states that dy/dx equals:',
 '[{"text":"u''*v''","isCorrect":false},{"text":"u''*v + u*v''","isCorrect":true},{"text":"u*v''","isCorrect":false},{"text":"(u*v)/(u''+v'')","isCorrect":false}]'::jsonb,
 null, 'The product rule states that the derivative of a product of two functions is u''v + uv'', where primes denote derivatives with respect to x.'),

-- Mathematics: Integration and Differential Equations
('WBJEE', 'Mathematics', 'Integration and Differential Equations', 'easy', 'mcq',
 'The integral of sec^2(x) dx is:',
 '[{"text":"tan(x) + C","isCorrect":true},{"text":"sec(x)*tan(x) + C","isCorrect":false},{"text":"cot(x) + C","isCorrect":false},{"text":"-tan(x) + C","isCorrect":false}]'::jsonb,
 null, 'Since d/dx[tan(x)] = sec^2(x), the antiderivative of sec^2(x) is tan(x) plus a constant.'),
('WBJEE', 'Mathematics', 'Integration and Differential Equations', 'easy', 'mcq',
 'A definite integral of a non-negative function over an interval represents, geometrically, the:',
 '[{"text":"Slope of the curve","isCorrect":false},{"text":"Area under the curve over that interval","isCorrect":true},{"text":"Length of the curve","isCorrect":false},{"text":"Maximum value of the function","isCorrect":false}]'::jsonb,
 null, 'A definite integral of a non-negative function over an interval gives the area enclosed between the curve and the x-axis over that interval.'),
('WBJEE', 'Mathematics', 'Integration and Differential Equations', 'medium', 'mcq',
 'The integration by parts formula states that the integral of u dv equals:',
 '[{"text":"uv - integral of v du","isCorrect":true},{"text":"uv + integral of v du","isCorrect":false},{"text":"u*v alone","isCorrect":false},{"text":"integral of u * integral of v","isCorrect":false}]'::jsonb,
 null, 'Integration by parts states integral(u dv) = uv - integral(v du), derived from the product rule for differentiation.'),
('WBJEE', 'Mathematics', 'Integration and Differential Equations', 'medium', 'mcq',
 'The integral of 1/(1+x^2) dx is:',
 '[{"text":"arctan(x) + C","isCorrect":true},{"text":"arcsin(x) + C","isCorrect":false},{"text":"ln(1+x^2) + C","isCorrect":false},{"text":"1/(1+x) + C","isCorrect":false}]'::jsonb,
 null, 'The standard integral of 1/(1+x^2) is the inverse tangent function, arctan(x), plus a constant of integration.'),

-- Mathematics: Coordinate Geometry
('WBJEE', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The slope of a line making an angle theta with the positive x-axis is:',
 '[{"text":"sin(theta)","isCorrect":false},{"text":"tan(theta)","isCorrect":true},{"text":"cos(theta)","isCorrect":false},{"text":"cot(theta)","isCorrect":false}]'::jsonb,
 null, 'The slope of a line is defined as the tangent of the angle it makes with the positive x-axis.'),
('WBJEE', 'Mathematics', 'Coordinate Geometry', 'medium', 'mcq',
 'The equation of the directrix of the parabola y^2 = 4ax is:',
 '[{"text":"x = a","isCorrect":false},{"text":"x = -a","isCorrect":true},{"text":"y = a","isCorrect":false},{"text":"y = -a","isCorrect":false}]'::jsonb,
 null, 'For the standard parabola y^2 = 4ax (opening rightward, a>0), the directrix is the vertical line x = -a.'),
('WBJEE', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'Two circles are said to be concentric if they:',
 '[{"text":"Have the same radius but different centers","isCorrect":false},{"text":"Have the same center but different radii","isCorrect":true},{"text":"Intersect at exactly one point","isCorrect":false},{"text":"Do not intersect at all","isCorrect":false}]'::jsonb,
 null, 'Concentric circles share the same center point but generally have different radii.'),
('WBJEE', 'Mathematics', 'Coordinate Geometry', 'hard', 'mcq',
 'The condition for the line y = mx + c to be tangent to the circle x^2 + y^2 = r^2 is:',
 '[{"text":"c^2 = r^2 * (1 + m^2)","isCorrect":true},{"text":"c = r * m","isCorrect":false},{"text":"c^2 = r^2 - m^2","isCorrect":false},{"text":"c = r + m","isCorrect":false}]'::jsonb,
 null, 'A line is tangent to a circle centered at the origin when the perpendicular distance from the center to the line equals the radius, giving the condition c^2 = r^2(1+m^2).'),

-- Mathematics: Trigonometry
('WBJEE', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'The value of tan(45 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"sqrt(3)","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'tan(45 degrees) = sin(45)/cos(45) = 1, a standard trigonometric value.'),
('WBJEE', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'For any angle x, sin^2(x) + cos^2(x) equals:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"2","isCorrect":false},{"text":"tan(x)","isCorrect":false}]'::jsonb,
 null, 'This is the fundamental Pythagorean trigonometric identity, holding for all real values of x.'),
('WBJEE', 'Mathematics', 'Trigonometry', 'medium', 'mcq',
 'The general solution of the equation tan(x) = 0 is:',
 '[{"text":"x = n*pi","isCorrect":true},{"text":"x = (2n+1)*pi/2","isCorrect":false},{"text":"x = n*pi/2","isCorrect":false},{"text":"x = 2n*pi","isCorrect":false}]'::jsonb,
 null, 'tan(x) = 0 whenever sin(x) = 0 (and cos(x) is nonzero), which occurs at integer multiples of pi, i.e. x = n*pi.'),
('WBJEE', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'The expansion of cos(A - B) is:',
 '[{"text":"cosA*cosB + sinA*sinB","isCorrect":true},{"text":"cosA*cosB - sinA*sinB","isCorrect":false},{"text":"sinA*cosB - cosA*sinB","isCorrect":false},{"text":"sinA*sinB - cosA*cosB","isCorrect":false}]'::jsonb,
 null, 'The angle subtraction formula for cosine states cos(A-B) = cosA*cosB + sinA*sinB.'),

-- Mathematics: Vectors and Statistics
('WBJEE', 'Mathematics', 'Vectors and Statistics', 'easy', 'mcq',
 'A unit vector is a vector whose magnitude is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"Equal to its direction","isCorrect":false},{"text":"Always negative","isCorrect":false}]'::jsonb,
 null, 'A unit vector is, by definition, a vector with magnitude exactly 1, used to indicate direction alone.'),
('WBJEE', 'Mathematics', 'Vectors and Statistics', 'easy', 'mcq',
 'The standard deviation of a data set is:',
 '[{"text":"The square of the variance","isCorrect":false},{"text":"The square root of the variance","isCorrect":true},{"text":"Equal to the mean","isCorrect":false},{"text":"Always negative","isCorrect":false}]'::jsonb,
 null, 'Standard deviation is defined as the square root of the variance, bringing the measure of spread back to the same units as the original data.'),
('WBJEE', 'Mathematics', 'Vectors and Statistics', 'medium', 'mcq',
 'Two vectors are said to be equal if they have the same:',
 '[{"text":"Magnitude only","isCorrect":false},{"text":"Magnitude and direction","isCorrect":true},{"text":"Direction only","isCorrect":false},{"text":"Starting point only","isCorrect":false}]'::jsonb,
 null, 'Two vectors are equal precisely when they have both the same magnitude and the same direction, regardless of their initial point in space.'),
('WBJEE', 'Mathematics', 'Vectors and Statistics', 'medium', 'mcq',
 'The correlation coefficient between two variables always lies in the range:',
 '[{"text":"0 to 1","isCorrect":false},{"text":"-1 to 1","isCorrect":true},{"text":"-infinity to infinity","isCorrect":false},{"text":"0 to infinity","isCorrect":false}]'::jsonb,
 null, 'The Pearson correlation coefficient is bounded between -1 (perfect negative correlation) and +1 (perfect positive correlation).');
