-- supabase/sql/exam_question_bank_upsc_epfo_set1.sql
--
-- First curated question-bank batch for 'UPSC EPFO' (see exam_patterns_upsc_epfo.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (100% single-best-response,
-- matching the real exam). The "Current Affairs" chapter sticks to durable, evergreen facts
-- (ministry affiliations, founding years, headquarters) rather than time-sensitive news. 16
-- chapters (2 English, 4 GK/Social Studies, 2 Accounting, 2 Industrial Relations/Labour Law, 2
-- Science/Computer, 4 Quant/Reasoning) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_upsc_epfo.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General English: Grammar and Usage
('UPSC EPFO', 'General English', 'Grammar and Usage', 'medium', 'mcq',
 'Choose the grammatically correct sentence:',
 '[{"text":"The team of players are practicing hard for the tournament.","isCorrect":false},{"text":"The team of players is practicing hard for the tournament.","isCorrect":true},{"text":"The team of players is practicing hard for the tournaments.","isCorrect":false},{"text":"The team of players were practicing hard for the tournament, is it.","isCorrect":false}]'::jsonb,
 null, '"Team" is a singular collective noun (treated as one unit here), so it takes the singular verb "is", not the plural "are".'),
('UPSC EPFO', 'General English', 'Grammar and Usage', 'easy', 'mcq',
 'Choose the correct preposition to complete: "He is responsible ___ the project''s success."',
 '[{"text":"of","isCorrect":false},{"text":"for","isCorrect":true},{"text":"with","isCorrect":false},{"text":"about","isCorrect":false}]'::jsonb,
 null, 'The idiomatic preposition used with "responsible" is "for" -- "responsible for the project''s success".'),
('UPSC EPFO', 'General English', 'Grammar and Usage', 'medium', 'mcq',
 'Which of the following sentences is correctly punctuated?',
 '[{"text":"After the meeting the manager, left for the airport.","isCorrect":false},{"text":"After the meeting, the manager left for the airport.","isCorrect":true},{"text":"After, the meeting the manager left for the airport.","isCorrect":false},{"text":"After the meeting the manager left, for the airport.","isCorrect":false}]'::jsonb,
 null, 'A comma correctly follows the introductory phrase "After the meeting" to separate it from the main clause "the manager left for the airport".'),
('UPSC EPFO', 'General English', 'Grammar and Usage', 'medium', 'mcq',
 'What is the correct passive voice form of "The manager approved the proposal"?',
 '[{"text":"The proposal was approved by the manager.","isCorrect":true},{"text":"The proposal is approved by the manager.","isCorrect":false},{"text":"The proposal has approved the manager.","isCorrect":false},{"text":"The manager was approved by the proposal.","isCorrect":false}]'::jsonb,
 null, 'The past simple active sentence "The manager approved the proposal" becomes "The proposal was approved by the manager" in the passive voice, keeping the same past tense.'),

-- General English: Vocabulary and Comprehension
('UPSC EPFO', 'General English', 'Vocabulary and Comprehension', 'medium', 'mcq',
 'Choose the word closest in meaning to "Prudent".',
 '[{"text":"Judicious","isCorrect":true},{"text":"Reckless","isCorrect":false},{"text":"Careless","isCorrect":false},{"text":"Impulsive","isCorrect":false}]'::jsonb,
 null, '"Prudent" means acting with care and good judgment; "judicious" is its closest synonym among the options.'),
('UPSC EPFO', 'General English', 'Vocabulary and Comprehension', 'medium', 'mcq',
 'Choose the antonym of "Frugal".',
 '[{"text":"Thrifty","isCorrect":false},{"text":"Extravagant","isCorrect":true},{"text":"Economical","isCorrect":false},{"text":"Sparing","isCorrect":false}]'::jsonb,
 null, '"Frugal" means economical or sparing in the use of resources; its antonym is "extravagant", meaning spending lavishly.'),
('UPSC EPFO', 'General English', 'Vocabulary and Comprehension', 'easy', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Neccessary","isCorrect":false},{"text":"Necessary","isCorrect":true},{"text":"Neccesary","isCorrect":false},{"text":"Necesary","isCorrect":false}]'::jsonb,
 null, '"Necessary" is the correct spelling, with a single "c" and double "s".'),
('UPSC EPFO', 'General English', 'Vocabulary and Comprehension', 'medium', 'mcq',
 'Choose the word that best completes the sentence: "The auditor''s ___ review uncovered several discrepancies."',
 '[{"text":"Thorough","isCorrect":true},{"text":"Careless","isCorrect":false},{"text":"Superficial","isCorrect":false},{"text":"Hasty","isCorrect":false}]'::jsonb,
 null, '"Thorough" means complete and detailed, fitting the context of a review careful enough to uncover discrepancies.'),

-- Indian Freedom Struggle and Modern History
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Freedom Struggle and Modern History', 'medium', 'mcq',
 'The Non-Cooperation Movement, led by Mahatma Gandhi, was launched in the year:',
 '[{"text":"1915","isCorrect":false},{"text":"1920","isCorrect":true},{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'The Non-Cooperation Movement was launched in 1920 in response to the Jallianwala Bagh massacre and the Rowlatt Act.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Freedom Struggle and Modern History', 'medium', 'mcq',
 'Who led the Indian National Army (INA / Azad Hind Fauj) after 1943?',
 '[{"text":"Mohan Singh","isCorrect":false},{"text":"Subhas Chandra Bose","isCorrect":true},{"text":"Rash Behari Bose","isCorrect":false},{"text":"Bhagat Singh","isCorrect":false}]'::jsonb,
 null, 'Subhas Chandra Bose took over leadership of the Indian National Army in 1943, having earlier organized it with support from Japan.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Freedom Struggle and Modern History', 'medium', 'mcq',
 'The Simon Commission visited India in the year:',
 '[{"text":"1919","isCorrect":false},{"text":"1928","isCorrect":true},{"text":"1935","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'The Simon Commission arrived in India in 1928 to review the working of the Government of India Act, 1919, and was met with widespread protests since it had no Indian members.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Freedom Struggle and Modern History', 'medium', 'mcq',
 'The Government of India Act, 1935 primarily provided for:',
 '[{"text":"Complete independence for India","isCorrect":false},{"text":"Provincial autonomy","isCorrect":true},{"text":"Abolition of the Indian Civil Service","isCorrect":false},{"text":"Partition of India","isCorrect":false}]'::jsonb,
 null, 'The Government of India Act, 1935 introduced provincial autonomy, granting elected provincial legislatures greater self-governing powers.'),

-- Indian Polity and Governance
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Polity and Governance', 'medium', 'mcq',
 'The Right to Constitutional Remedies is guaranteed under which article of the Indian Constitution?',
 '[{"text":"Article 21","isCorrect":false},{"text":"Article 32","isCorrect":true},{"text":"Article 14","isCorrect":false},{"text":"Article 19","isCorrect":false}]'::jsonb,
 null, 'Article 32 guarantees the Right to Constitutional Remedies, allowing citizens to directly approach the Supreme Court to enforce their Fundamental Rights.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Polity and Governance', 'easy', 'mcq',
 'The Chief Justice of India is appointed by:',
 '[{"text":"The Prime Minister","isCorrect":false},{"text":"The President of India","isCorrect":true},{"text":"The Parliament","isCorrect":false},{"text":"The Chief Justice''s predecessor directly","isCorrect":false}]'::jsonb,
 null, 'The President of India formally appoints the Chief Justice of India, conventionally on the recommendation of the outgoing Chief Justice.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Polity and Governance', 'hard', 'mcq',
 'The Union Public Service Commission (UPSC) is established under which article of the Constitution?',
 '[{"text":"Article 280","isCorrect":false},{"text":"Article 315","isCorrect":true},{"text":"Article 324","isCorrect":false},{"text":"Article 356","isCorrect":false}]'::jsonb,
 null, 'Article 315 of the Indian Constitution provides for the establishment of a Public Service Commission for the Union (UPSC) and for the states.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Polity and Governance', 'medium', 'mcq',
 'The concept of "Directive Principles of State Policy" in the Indian Constitution was borrowed from the constitution of:',
 '[{"text":"United States","isCorrect":false},{"text":"Ireland","isCorrect":true},{"text":"United Kingdom","isCorrect":false},{"text":"Canada","isCorrect":false}]'::jsonb,
 null, 'The Directive Principles of State Policy were inspired by the Irish Constitution, which contains similar non-justiciable guiding principles for governance.'),

-- Indian Economy
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Economy', 'easy', 'mcq',
 'Inflation is best described as:',
 '[{"text":"A sustained increase in the general price level","isCorrect":true},{"text":"A sustained decrease in the general price level","isCorrect":false},{"text":"A one-time price spike only","isCorrect":false},{"text":"An increase in the value of currency","isCorrect":false}]'::jsonb,
 null, 'Inflation refers to a sustained, general rise in the price level of goods and services in an economy over time.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Economy', 'medium', 'mcq',
 'Which of the following is an example of a direct tax?',
 '[{"text":"Goods and Services Tax","isCorrect":false},{"text":"Income tax","isCorrect":true},{"text":"Customs duty","isCorrect":false},{"text":"Excise duty","isCorrect":false}]'::jsonb,
 null, 'Income tax is levied directly on an individual''s or entity''s income and cannot be shifted to another party, making it a direct tax.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Economy', 'medium', 'mcq',
 'Disinvestment, as a government economic policy, refers to:',
 '[{"text":"Increasing government spending on infrastructure","isCorrect":false},{"text":"The sale of government stake in public sector enterprises","isCorrect":true},{"text":"Raising taxes on imports","isCorrect":false},{"text":"Printing additional currency","isCorrect":false}]'::jsonb,
 null, 'Disinvestment refers to the government selling or liquidating its equity stake in public sector undertakings, often to raise revenue or improve efficiency.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Indian Economy', 'medium', 'mcq',
 'The Monetary Policy Committee (MPC) in India is primarily responsible for determining:',
 '[{"text":"The fiscal deficit target","isCorrect":false},{"text":"The policy repo rate","isCorrect":true},{"text":"Income tax slabs","isCorrect":false},{"text":"Import tariffs","isCorrect":false}]'::jsonb,
 null, 'The Monetary Policy Committee, headed by the RBI Governor, is responsible for setting the policy repo rate to control inflation and support growth.'),

-- Current Affairs and General Knowledge
('UPSC EPFO', 'General Knowledge and Social Studies', 'Current Affairs and General Knowledge', 'medium', 'mcq',
 'The Employees'' Provident Fund Organisation (EPFO) functions under which ministry of the Government of India?',
 '[{"text":"Ministry of Finance","isCorrect":false},{"text":"Ministry of Labour and Employment","isCorrect":true},{"text":"Ministry of Corporate Affairs","isCorrect":false},{"text":"Ministry of Commerce and Industry","isCorrect":false}]'::jsonb,
 null, 'EPFO operates under the Ministry of Labour and Employment, Government of India, administering retirement and social security schemes for the organized workforce.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Current Affairs and General Knowledge', 'easy', 'mcq',
 'The headquarters of the Employees'' Provident Fund Organisation (EPFO) is located in:',
 '[{"text":"Mumbai","isCorrect":false},{"text":"New Delhi","isCorrect":true},{"text":"Chennai","isCorrect":false},{"text":"Kolkata","isCorrect":false}]'::jsonb,
 null, 'EPFO''s Head Office is located in New Delhi.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Current Affairs and General Knowledge', 'medium', 'mcq',
 'The official symbol for the Indian Rupee (₹) was adopted by the Government of India in the year:',
 '[{"text":"2005","isCorrect":false},{"text":"2010","isCorrect":true},{"text":"2015","isCorrect":false},{"text":"2000","isCorrect":false}]'::jsonb,
 null, 'The Indian Rupee symbol (₹) was officially adopted in 2010, designed by D. Udaya Kumar.'),
('UPSC EPFO', 'General Knowledge and Social Studies', 'Current Affairs and General Knowledge', 'medium', 'mcq',
 'The Digital India programme, aimed at transforming India into a digitally empowered society, was launched by the Government of India in the year:',
 '[{"text":"2010","isCorrect":false},{"text":"2015","isCorrect":true},{"text":"2018","isCorrect":false},{"text":"2020","isCorrect":false}]'::jsonb,
 null, 'The Digital India programme was launched in 2015 to improve online infrastructure and digital service delivery across India.'),

-- General Accounting Principles: Basic Accounting Concepts
('UPSC EPFO', 'General Accounting Principles', 'Basic Accounting Concepts', 'medium', 'mcq',
 'The fundamental accounting equation is expressed as:',
 '[{"text":"Assets = Liabilities + Capital","isCorrect":true},{"text":"Assets = Capital - Liabilities","isCorrect":false},{"text":"Liabilities = Assets + Capital","isCorrect":false},{"text":"Capital = Assets + Liabilities","isCorrect":false}]'::jsonb,
 null, 'The fundamental accounting equation states that a business''s total assets equal the sum of its liabilities and owner''s capital (equity).'),
('UPSC EPFO', 'General Accounting Principles', 'Basic Accounting Concepts', 'medium', 'mcq',
 'The accounting concept that treats a business as a separate entity from its owner is called the:',
 '[{"text":"Going concern concept","isCorrect":false},{"text":"Business entity concept","isCorrect":true},{"text":"Money measurement concept","isCorrect":false},{"text":"Matching concept","isCorrect":false}]'::jsonb,
 null, 'The business entity concept requires that a business''s financial transactions be recorded separately from the personal transactions of its owner(s).'),
('UPSC EPFO', 'General Accounting Principles', 'Basic Accounting Concepts', 'hard', 'mcq',
 'Under the accrual concept of accounting, revenue is recognized when it is:',
 '[{"text":"Earned, regardless of when cash is received","isCorrect":true},{"text":"Received in cash, regardless of when earned","isCorrect":false},{"text":"Budgeted for the year","isCorrect":false},{"text":"Approved by the auditor","isCorrect":false}]'::jsonb,
 null, 'The accrual concept requires revenue to be recognized when it is earned (goods delivered or services performed), not necessarily when cash is actually received.'),
('UPSC EPFO', 'General Accounting Principles', 'Basic Accounting Concepts', 'easy', 'mcq',
 'Which of the following is classified as a current asset?',
 '[{"text":"Cash in hand","isCorrect":true},{"text":"Land and building","isCorrect":false},{"text":"Long-term investments","isCorrect":false},{"text":"Plant and machinery","isCorrect":false}]'::jsonb,
 null, 'Cash in hand is a current asset, since it is readily available and expected to be used within the normal operating cycle (typically one year).'),

-- General Accounting Principles: Financial Statements and Analysis
('UPSC EPFO', 'General Accounting Principles', 'Financial Statements and Analysis', 'medium', 'mcq',
 'The Balance Sheet of a business primarily shows:',
 '[{"text":"The financial position of the business at a particular point in time","isCorrect":true},{"text":"The profit or loss over a period","isCorrect":false},{"text":"Only the cash transactions of the business","isCorrect":false},{"text":"The tax liability for the year","isCorrect":false}]'::jsonb,
 null, 'A Balance Sheet is a snapshot of a business''s assets, liabilities, and capital as of a specific date, reflecting its financial position at that point in time.'),
('UPSC EPFO', 'General Accounting Principles', 'Financial Statements and Analysis', 'medium', 'mcq',
 'The Profit and Loss Account (Income Statement) of a business shows:',
 '[{"text":"The financial position at a point in time","isCorrect":false},{"text":"The net profit or loss over a period of time","isCorrect":true},{"text":"Only the fixed assets owned","isCorrect":false},{"text":"The share capital structure","isCorrect":false}]'::jsonb,
 null, 'The Profit and Loss Account reports a business''s revenues, expenses, and resulting net profit or loss accumulated over a specific accounting period.'),
('UPSC EPFO', 'General Accounting Principles', 'Financial Statements and Analysis', 'medium', 'mcq',
 'Depreciation is best described as:',
 '[{"text":"The systematic allocation of the cost of a fixed asset over its useful life","isCorrect":true},{"text":"An immediate cash outflow each year","isCorrect":false},{"text":"An increase in the market value of an asset","isCorrect":false},{"text":"A one-time write-off in the year of purchase","isCorrect":false}]'::jsonb,
 null, 'Depreciation systematically spreads the cost of a fixed (tangible) asset over the periods it is expected to be used, matching the expense to the revenue it helps generate.'),
('UPSC EPFO', 'General Accounting Principles', 'Financial Statements and Analysis', 'hard', 'mcq',
 'The current ratio, a key measure of short-term liquidity, is calculated as:',
 '[{"text":"Current Assets / Current Liabilities","isCorrect":true},{"text":"Current Liabilities / Current Assets","isCorrect":false},{"text":"Total Assets / Total Liabilities","isCorrect":false},{"text":"Net Profit / Current Assets","isCorrect":false}]'::jsonb,
 null, 'The current ratio is calculated by dividing current assets by current liabilities, indicating a business''s ability to meet its short-term obligations.'),

-- Industrial Relations and Labour Laws: Industrial Relations
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Industrial Relations', 'medium', 'mcq',
 'The term "collective bargaining" refers to:',
 '[{"text":"An individual employee negotiating their own salary alone","isCorrect":false},{"text":"Negotiation between employers and a group of employees (or their union) over employment terms","isCorrect":true},{"text":"A government order fixing wages","isCorrect":false},{"text":"A court ruling on an industrial dispute","isCorrect":false}]'::jsonb,
 null, 'Collective bargaining is the process by which employers and a group of employees (typically represented by a trade union) negotiate terms and conditions of employment.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Industrial Relations', 'medium', 'mcq',
 'A "lockout" in the context of industrial relations refers to:',
 '[{"text":"Employees refusing to enter the workplace","isCorrect":false},{"text":"The closure of a workplace by an employer to prevent employees from working, typically during a dispute","isCorrect":true},{"text":"A government-ordered factory inspection","isCorrect":false},{"text":"A scheduled holiday for all employees","isCorrect":false}]'::jsonb,
 null, 'A lockout is initiated by the employer, temporarily closing a workplace or refusing to allow employees to work, typically as a response to an ongoing industrial dispute.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Industrial Relations', 'hard', 'mcq',
 'Which official under the Industrial Disputes Act primarily handles industrial disputes through conciliation?',
 '[{"text":"Conciliation Officer","isCorrect":true},{"text":"Labour Court judge only","isCorrect":false},{"text":"Company auditor","isCorrect":false},{"text":"District Magistrate only","isCorrect":false}]'::jsonb,
 null, 'A Conciliation Officer, appointed under the Industrial Disputes Act, mediates between employers and employees to help resolve industrial disputes amicably.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Industrial Relations', 'easy', 'mcq',
 'The term "strike" refers to:',
 '[{"text":"A temporary stoppage of work by employees as a form of protest","isCorrect":true},{"text":"An employer closing the factory permanently","isCorrect":false},{"text":"A government-mandated holiday","isCorrect":false},{"text":"A permanent resignation by all employees","isCorrect":false}]'::jsonb,
 null, 'A strike is a temporary, collective work stoppage undertaken by employees, typically to press demands or protest against employer actions.'),

-- Industrial Relations and Labour Laws: Labour Laws and Social Security
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Labour Laws and Social Security', 'medium', 'mcq',
 'The Employees'' Provident Fund and Miscellaneous Provisions Act was enacted in the year:',
 '[{"text":"1948","isCorrect":false},{"text":"1952","isCorrect":true},{"text":"1965","isCorrect":false},{"text":"1972","isCorrect":false}]'::jsonb,
 null, 'The Employees'' Provident Fund and Miscellaneous Provisions Act, 1952 established the framework for provident fund, pension, and insurance schemes for employees.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Labour Laws and Social Security', 'medium', 'mcq',
 'Historically (before being subsumed into the Code on Wages), the concept of minimum wages in India was primarily governed by which Act?',
 '[{"text":"Minimum Wages Act, 1948","isCorrect":true},{"text":"Payment of Wages Act, 1936","isCorrect":false},{"text":"Factories Act, 1948","isCorrect":false},{"text":"Trade Unions Act, 1926","isCorrect":false}]'::jsonb,
 null, 'The Minimum Wages Act, 1948 empowered governments to fix minimum wage rates for specified employments, until its provisions were consolidated into the Code on Wages.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Labour Laws and Social Security', 'medium', 'mcq',
 'The Employees'' State Insurance (ESI) scheme primarily provides:',
 '[{"text":"Housing loans to employees","isCorrect":false},{"text":"Medical and cash benefits during sickness, maternity, and employment injury","isCorrect":true},{"text":"Retirement pension only","isCorrect":false},{"text":"Tax exemptions on salary","isCorrect":false}]'::jsonb,
 null, 'The Employees'' State Insurance scheme provides medical care and cash benefits to insured employees and their dependents in situations like sickness, maternity, disablement, and employment injury.'),
('UPSC EPFO', 'Industrial Relations and Labour Laws', 'Labour Laws and Social Security', 'medium', 'mcq',
 'The Payment of Gratuity Act, which provides for a lump-sum payment to employees on retirement or resignation after a minimum period of service, was enacted in the year:',
 '[{"text":"1965","isCorrect":false},{"text":"1972","isCorrect":true},{"text":"1980","isCorrect":false},{"text":"1990","isCorrect":false}]'::jsonb,
 null, 'The Payment of Gratuity Act, 1972 mandates a gratuity payment to employees who have rendered continuous service for a specified minimum period.'),

-- General Science and Computer Applications: General Science
('UPSC EPFO', 'General Science and Computer Applications', 'General Science', 'easy', 'mcq',
 'The chemical formula of common salt is:',
 '[{"text":"NaCl","isCorrect":true},{"text":"KCl","isCorrect":false},{"text":"CaCl2","isCorrect":false},{"text":"NaOH","isCorrect":false}]'::jsonb,
 null, 'Common table salt is sodium chloride, with the chemical formula NaCl.'),
('UPSC EPFO', 'General Science and Computer Applications', 'General Science', 'easy', 'mcq',
 'Photosynthesis in green plants occurs in the presence of:',
 '[{"text":"Sunlight and chlorophyll","isCorrect":true},{"text":"Darkness only","isCorrect":false},{"text":"Oxygen alone","isCorrect":false},{"text":"Nitrogen alone","isCorrect":false}]'::jsonb,
 null, 'Photosynthesis requires sunlight as the energy source and chlorophyll as the light-absorbing pigment, converting carbon dioxide and water into glucose and oxygen.'),
('UPSC EPFO', 'General Science and Computer Applications', 'General Science', 'easy', 'mcq',
 'The SI unit of frequency is the:',
 '[{"text":"Hertz","isCorrect":true},{"text":"Watt","isCorrect":false},{"text":"Joule","isCorrect":false},{"text":"Newton","isCorrect":false}]'::jsonb,
 null, 'Frequency, the number of oscillations per second, is measured in hertz (Hz).'),
('UPSC EPFO', 'General Science and Computer Applications', 'General Science', 'easy', 'mcq',
 'Which gas is most abundant in the Earth''s atmosphere?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Nitrogen","isCorrect":true},{"text":"Carbon dioxide","isCorrect":false},{"text":"Argon","isCorrect":false}]'::jsonb,
 null, 'Nitrogen makes up about 78% of the Earth''s atmosphere by volume, making it the most abundant atmospheric gas, well ahead of oxygen (about 21%).'),

-- General Science and Computer Applications: Computer Applications and IT Awareness
('UPSC EPFO', 'General Science and Computer Applications', 'Computer Applications and IT Awareness', 'easy', 'mcq',
 'RAM in a computer stands for:',
 '[{"text":"Random Access Memory","isCorrect":true},{"text":"Read Access Memory","isCorrect":false},{"text":"Rapid Access Module","isCorrect":false},{"text":"Read-only Access Memory","isCorrect":false}]'::jsonb,
 null, 'RAM (Random Access Memory) is the computer''s volatile working memory, used to store data and instructions currently being processed.'),
('UPSC EPFO', 'General Science and Computer Applications', 'Computer Applications and IT Awareness', 'easy', 'mcq',
 'Which of the following is an example of an operating system?',
 '[{"text":"Microsoft Word","isCorrect":false},{"text":"Windows","isCorrect":true},{"text":"Google Chrome","isCorrect":false},{"text":"Adobe Photoshop","isCorrect":false}]'::jsonb,
 null, 'Windows is an operating system, managing hardware resources and providing a platform for application software, unlike Word, Chrome, or Photoshop, which are application programs.'),
('UPSC EPFO', 'General Science and Computer Applications', 'Computer Applications and IT Awareness', 'medium', 'mcq',
 'The full form of "URL" (as used in web addresses) is:',
 '[{"text":"Uniform Resource Locator","isCorrect":true},{"text":"Universal Reference Link","isCorrect":false},{"text":"Unified Resource Language","isCorrect":false},{"text":"User Resource Locator","isCorrect":false}]'::jsonb,
 null, 'URL stands for Uniform Resource Locator, the address used to specify the location of a resource on the internet.'),
('UPSC EPFO', 'General Science and Computer Applications', 'Computer Applications and IT Awareness', 'medium', 'mcq',
 'A firewall in computer networking is primarily used for:',
 '[{"text":"Increasing internet speed","isCorrect":false},{"text":"Protecting a network from unauthorized access","isCorrect":true},{"text":"Compressing large files","isCorrect":false},{"text":"Formatting a hard disk","isCorrect":false}]'::jsonb,
 null, 'A firewall monitors and controls incoming and outgoing network traffic based on security rules, protecting a network from unauthorized access.'),

-- Quantitative Aptitude - Arithmetic
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Arithmetic', 'medium', 'mcq',
 'If the simple interest on a sum for 2 years at 5% per annum is Rs. 100, find the principal.',
 '[{"text":"Rs. 500","isCorrect":false},{"text":"Rs. 1000","isCorrect":true},{"text":"Rs. 2000","isCorrect":false},{"text":"Rs. 1500","isCorrect":false}]'::jsonb,
 null, 'Using SI = P*R*T/100, P = SI*100/(R*T) = 100*100/(5*2) = 1000.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Arithmetic', 'easy', 'mcq',
 'A shopkeeper sells an item at a 20% profit. If the cost price is Rs. 500, find the selling price.',
 '[{"text":"Rs. 550","isCorrect":false},{"text":"Rs. 600","isCorrect":true},{"text":"Rs. 620","isCorrect":false},{"text":"Rs. 700","isCorrect":false}]'::jsonb,
 null, 'Selling price = Cost price + 20% of cost price = 500 + 100 = 600.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Arithmetic', 'easy', 'mcq',
 'The value of 25% of 400 is:',
 '[{"text":"100","isCorrect":true},{"text":"80","isCorrect":false},{"text":"120","isCorrect":false},{"text":"90","isCorrect":false}]'::jsonb,
 null, '25% of 400 = (25/100)*400 = 100.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Arithmetic', 'medium', 'mcq',
 'Two numbers are in the ratio 3:4, and their sum is 70. Find the larger number.',
 '[{"text":"30","isCorrect":false},{"text":"40","isCorrect":true},{"text":"35","isCorrect":false},{"text":"45","isCorrect":false}]'::jsonb,
 null, 'Let the numbers be 3x and 4x; 3x+4x=70 gives x=10, so the larger number is 4*10=40.'),

-- Quantitative Aptitude - Algebra and Data Interpretation
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Algebra and Data Interpretation', 'medium', 'mcq',
 'If x + y = 10 and x - y = 4, find the value of x.',
 '[{"text":"6","isCorrect":false},{"text":"7","isCorrect":true},{"text":"3","isCorrect":false},{"text":"5","isCorrect":false}]'::jsonb,
 null, 'Adding the two equations: 2x=14, so x=7.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Algebra and Data Interpretation', 'easy', 'mcq',
 'The expansion of (a+b)^2 is:',
 '[{"text":"a^2 + b^2","isCorrect":false},{"text":"a^2 + 2ab + b^2","isCorrect":true},{"text":"a^2 - 2ab + b^2","isCorrect":false},{"text":"2a + 2b","isCorrect":false}]'::jsonb,
 null, 'The standard algebraic identity gives (a+b)^2 = a^2 + 2ab + b^2.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Algebra and Data Interpretation', 'medium', 'mcq',
 'In a pie chart representing a total of 360 degrees, a sector representing 25% of the total corresponds to an angle of:',
 '[{"text":"60 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":true},{"text":"120 degrees","isCorrect":false},{"text":"45 degrees","isCorrect":false}]'::jsonb,
 null, '25% of 360 degrees = 0.25*360 = 90 degrees.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Quantitative Aptitude - Algebra and Data Interpretation', 'easy', 'mcq',
 'If the average of 4 numbers is 15, find their total sum.',
 '[{"text":"45","isCorrect":false},{"text":"60","isCorrect":true},{"text":"15","isCorrect":false},{"text":"30","isCorrect":false}]'::jsonb,
 null, 'Sum = average * count = 15*4 = 60.'),

-- Logical and Analytical Reasoning
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Logical and Analytical Reasoning', 'medium', 'mcq',
 'Given: "All mangoes are fruits" and "All fruits are edible." Which conclusion follows?',
 '[{"text":"All mangoes are edible.","isCorrect":true},{"text":"All edible things are mangoes.","isCorrect":false},{"text":"No mangoes are edible.","isCorrect":false},{"text":"Some fruits are not edible.","isCorrect":false}]'::jsonb,
 null, 'By transitive syllogism, since all mangoes are fruits and all fruits are edible, it necessarily follows that all mangoes are edible.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Logical and Analytical Reasoning', 'easy', 'mcq',
 'Find the odd one out: Cat, Dog, Lion, Table.',
 '[{"text":"Cat","isCorrect":false},{"text":"Dog","isCorrect":false},{"text":"Lion","isCorrect":false},{"text":"Table","isCorrect":true}]'::jsonb,
 null, 'Cat, Dog, and Lion are all animals, while Table is a piece of furniture, making it the odd one out.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Logical and Analytical Reasoning', 'medium', 'mcq',
 'Find the next number in the series: 2, 6, 12, 20, ?',
 '[{"text":"26","isCorrect":false},{"text":"30","isCorrect":true},{"text":"28","isCorrect":false},{"text":"32","isCorrect":false}]'::jsonb,
 null, 'The differences between consecutive terms are 4, 6, 8, 10 -- increasing by 2 each time -- so the next difference is 10, giving 20+10=30.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Logical and Analytical Reasoning', 'hard', 'mcq',
 'In a certain code, "SUN" is written as "TVO". How is "MOON" written in the same code?',
 '[{"text":"NPPO","isCorrect":true},{"text":"NPOP","isCorrect":false},{"text":"MPPO","isCorrect":false},{"text":"NPPN","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one position in the alphabet (S to T, U to V, N to O); applying the same shift to M-O-O-N gives N-P-P-O.'),

-- Verbal and Non-verbal Reasoning
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Verbal and Non-verbal Reasoning', 'easy', 'mcq',
 'Complete the analogy: Pen is to Write as Knife is to:',
 '[{"text":"Cut","isCorrect":true},{"text":"Sharpen","isCorrect":false},{"text":"Kitchen","isCorrect":false},{"text":"Metal","isCorrect":false}]'::jsonb,
 null, 'Just as a pen''s primary function is to write, a knife''s primary function is to cut.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Verbal and Non-verbal Reasoning', 'medium', 'mcq',
 'A is the father of B. B is the brother of C. What is A''s relationship to C?',
 '[{"text":"A is the father of C.","isCorrect":true},{"text":"A is the brother of C.","isCorrect":false},{"text":"A is the grandfather of C.","isCorrect":false},{"text":"There is no relation between A and C.","isCorrect":false}]'::jsonb,
 null, 'Since B and C are siblings and A is B''s father, A is also C''s father.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Verbal and Non-verbal Reasoning', 'medium', 'mcq',
 'If today is Wednesday, what day of the week will it be after 15 days?',
 '[{"text":"Tuesday","isCorrect":false},{"text":"Thursday","isCorrect":true},{"text":"Friday","isCorrect":false},{"text":"Wednesday","isCorrect":false}]'::jsonb,
 null, '15 days is 2 full weeks (14 days) plus 1 extra day; 1 day after Wednesday is Thursday.'),
('UPSC EPFO', 'Quantitative Aptitude and Reasoning', 'Verbal and Non-verbal Reasoning', 'medium', 'mcq',
 'Find the missing number in the series: 4, 9, 16, 25, ?',
 '[{"text":"30","isCorrect":false},{"text":"36","isCorrect":true},{"text":"32","isCorrect":false},{"text":"49","isCorrect":false}]'::jsonb,
 null, 'The series consists of perfect squares: 2^2, 3^2, 4^2, 5^2, so the next term is 6^2=36.');
