-- supabase/sql/exam_question_bank_bitsat_set1.sql
--
-- First curated question-bank batch for 'BITSAT' (see exam_patterns_bitsat.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Like NEET UG/PG (and unlike the JEE sets), BITSAT's real format is 100% single-best-response
-- MCQ (4 options, exactly one correct) -- no multi-correct, numerical, or descriptive format in
-- the actual exam. Each of the 16 chapters (4 Physics, 4 Chemistry, 4 Mathematics, 2 English
-- Proficiency, 2 Logical Reasoning) gets 4 questions -- the English/Logical Reasoning sections are
-- unique to BITSAT among the exams curated so far (JEE/NEET have neither).
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_bitsat.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('BITSAT', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of power is the:',
 '[{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":true},{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'Power is the rate of doing work, measured in watts (1 W = 1 J/s).'),
('BITSAT', 'Physics', 'Mechanics', 'medium', 'mcq',
 'For a projectile launched with a fixed speed, the horizontal range is maximum when the angle of projection is:',
 '[{"text":"30 degrees","isCorrect":false},{"text":"45 degrees","isCorrect":true},{"text":"60 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":false}]'::jsonb,
 null, 'Range R = (v^2*sin(2*theta))/g is maximized when sin(2*theta)=1, i.e. theta=45 degrees.'),
('BITSAT', 'Physics', 'Mechanics', 'hard', 'mcq',
 'The moment of inertia of a solid sphere of mass M and radius R about its diameter is:',
 '[{"text":"(2/5)MR^2","isCorrect":true},{"text":"(2/3)MR^2","isCorrect":false},{"text":"MR^2","isCorrect":false},{"text":"(1/2)MR^2","isCorrect":false}]'::jsonb,
 null, 'The moment of inertia of a uniform solid sphere about an axis through its center (diameter) is (2/5)MR^2.'),
('BITSAT', 'Physics', 'Mechanics', 'medium', 'mcq',
 'In a perfectly elastic collision between two bodies, which quantity is conserved in addition to momentum?',
 '[{"text":"Kinetic energy","isCorrect":true},{"text":"Potential energy","isCorrect":false},{"text":"Angular momentum only","isCorrect":false},{"text":"Impulse only","isCorrect":false}]'::jsonb,
 null, 'By definition, an elastic collision conserves both total momentum and total kinetic energy of the system; only momentum is conserved in an inelastic collision.'),

-- Physics: Electrodynamics
('BITSAT', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The force between two long parallel wires carrying current in the same direction is:',
 '[{"text":"Attractive","isCorrect":true},{"text":"Repulsive","isCorrect":false},{"text":"Zero","isCorrect":false},{"text":"Perpendicular to both wires","isCorrect":false}]'::jsonb,
 null, 'Parallel currents flowing in the same direction attract each other, while currents in opposite directions repel, a consequence of the magnetic forces each wire''s field exerts on the other.'),
('BITSAT', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'For capacitors connected in series, the equivalent capacitance is found using which relation?',
 '[{"text":"C_eq = C1 + C2 + ...","isCorrect":false},{"text":"1/C_eq = 1/C1 + 1/C2 + ...","isCorrect":true},{"text":"C_eq = C1*C2*...","isCorrect":false},{"text":"C_eq = (C1+C2)/2","isCorrect":false}]'::jsonb,
 null, 'Capacitors in series combine like resistors in parallel: the reciprocal of the equivalent capacitance equals the sum of the reciprocals of the individual capacitances.'),
('BITSAT', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of magnetic flux is the:',
 '[{"text":"Tesla","isCorrect":false},{"text":"Weber","isCorrect":true},{"text":"Henry","isCorrect":false},{"text":"Gauss","isCorrect":false}]'::jsonb,
 null, 'Magnetic flux is measured in webers (Wb); magnetic flux density (field strength) is measured in tesla.'),
('BITSAT', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'Kirchhoff''s voltage law (the loop rule) is a direct consequence of which principle?',
 '[{"text":"Conservation of charge","isCorrect":false},{"text":"Conservation of energy","isCorrect":true},{"text":"Conservation of momentum","isCorrect":false},{"text":"Conservation of mass","isCorrect":false}]'::jsonb,
 null, 'Kirchhoff''s voltage law states the sum of potential differences around any closed loop is zero, reflecting conservation of energy for a charge traversing the loop.'),

-- Physics: Heat, Thermodynamics and Waves
('BITSAT', 'Physics', 'Heat, Thermodynamics and Waves', 'easy', 'mcq',
 'The first law of thermodynamics is fundamentally a statement of:',
 '[{"text":"Conservation of energy","isCorrect":true},{"text":"Conservation of entropy","isCorrect":false},{"text":"Conservation of momentum","isCorrect":false},{"text":"Increase of disorder","isCorrect":false}]'::jsonb,
 null, 'The first law of thermodynamics, deltaU = Q - W, expresses conservation of energy applied to a thermodynamic system.'),
('BITSAT', 'Physics', 'Heat, Thermodynamics and Waves', 'medium', 'mcq',
 'The speed of sound in air increases with:',
 '[{"text":"Increasing temperature","isCorrect":true},{"text":"Decreasing temperature","isCorrect":false},{"text":"Increasing pressure at constant temperature","isCorrect":false},{"text":"Increasing wavelength","isCorrect":false}]'::jsonb,
 null, 'The speed of sound in a gas is proportional to the square root of absolute temperature, so it increases as temperature rises.'),
('BITSAT', 'Physics', 'Heat, Thermodynamics and Waves', 'medium', 'mcq',
 'In simple harmonic motion, the phase difference between velocity and displacement is:',
 '[{"text":"0","isCorrect":false},{"text":"pi/2 (90 degrees)","isCorrect":true},{"text":"pi (180 degrees)","isCorrect":false},{"text":"2*pi","isCorrect":false}]'::jsonb,
 null, 'For x(t)=A*sin(omega*t), velocity v(t)=A*omega*cos(omega*t), which leads displacement by a phase of pi/2.'),
('BITSAT', 'Physics', 'Heat, Thermodynamics and Waves', 'easy', 'mcq',
 'An ideal gas obeys which equation of state?',
 '[{"text":"PV = nRT","isCorrect":true},{"text":"PV^2 = constant","isCorrect":false},{"text":"P + V = nRT","isCorrect":false},{"text":"P/V = nRT","isCorrect":false}]'::jsonb,
 null, 'The ideal gas equation PV = nRT relates pressure, volume, moles, and temperature for an ideal gas.'),

-- Physics: Optics and Modern Physics
('BITSAT', 'Physics', 'Optics and Modern Physics', 'medium', 'mcq',
 'The critical angle for total internal reflection at an interface depends on:',
 '[{"text":"The refractive indices of the two media","isCorrect":true},{"text":"The intensity of incident light only","isCorrect":false},{"text":"The wavelength of light only, regardless of media","isCorrect":false},{"text":"The angle of incidence alone","isCorrect":false}]'::jsonb,
 null, 'The critical angle theta_c satisfies sin(theta_c) = n2/n1, so it depends on the refractive indices of the two media at the interface.'),
('BITSAT', 'Physics', 'Optics and Modern Physics', 'medium', 'mcq',
 'The de Broglie wavelength of a particle is inversely proportional to its:',
 '[{"text":"Mass alone","isCorrect":false},{"text":"Momentum","isCorrect":true},{"text":"Charge","isCorrect":false},{"text":"Kinetic energy directly (not via momentum)","isCorrect":false}]'::jsonb,
 null, 'The de Broglie wavelength lambda = h/p is inversely proportional to a particle''s momentum p.'),
('BITSAT', 'Physics', 'Optics and Modern Physics', 'easy', 'mcq',
 'The energy of a photon of frequency f is given by:',
 '[{"text":"E = hf","isCorrect":true},{"text":"E = h/f","isCorrect":false},{"text":"E = mc","isCorrect":false},{"text":"E = f/h","isCorrect":false}]'::jsonb,
 null, 'Planck''s relation E = hf gives the energy of a photon in terms of Planck''s constant h and its frequency f.'),
('BITSAT', 'Physics', 'Optics and Modern Physics', 'medium', 'mcq',
 'A convex mirror, for a real object placed anywhere in front of it, always forms an image that is:',
 '[{"text":"Real, inverted, and magnified","isCorrect":false},{"text":"Virtual, erect, and diminished","isCorrect":true},{"text":"Real, erect, and diminished","isCorrect":false},{"text":"Virtual, inverted, and magnified","isCorrect":false}]'::jsonb,
 null, 'A convex mirror always produces a virtual, erect, and diminished image for a real object, regardless of object distance, since diverging reflected rays never actually converge.'),

-- Chemistry: Physical Chemistry
('BITSAT', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The order of a chemical reaction (with respect to a reactant) is determined by:',
 '[{"text":"The stoichiometric coefficients in the balanced equation","isCorrect":false},{"text":"Experimentally, from the observed rate law","isCorrect":true},{"text":"The number of moles of reactants","isCorrect":false},{"text":"The enthalpy of the reaction","isCorrect":false}]'::jsonb,
 null, 'Unlike molecularity, the order of a reaction cannot generally be predicted from the balanced equation alone -- it must be determined experimentally from the observed rate law.'),
('BITSAT', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'For a spontaneous process, the total entropy of the universe:',
 '[{"text":"Decreases","isCorrect":false},{"text":"Increases","isCorrect":true},{"text":"Remains constant","isCorrect":false},{"text":"Becomes zero","isCorrect":false}]'::jsonb,
 null, 'The second law of thermodynamics states that the total entropy of the universe increases for any spontaneous process.'),
('BITSAT', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'A substance that increases the rate of a reaction without itself being consumed is called a:',
 '[{"text":"Catalyst","isCorrect":true},{"text":"Reactant","isCorrect":false},{"text":"Inhibitor","isCorrect":false},{"text":"Solvent","isCorrect":false}]'::jsonb,
 null, 'A catalyst provides an alternative reaction pathway with lower activation energy, speeding up the reaction while remaining chemically unchanged at the end.'),
('BITSAT', 'Chemistry', 'Physical Chemistry', 'hard', 'mcq',
 'The unit of the rate constant for a first-order reaction is:',
 '[{"text":"mol L^-1 s^-1","isCorrect":false},{"text":"s^-1","isCorrect":true},{"text":"L mol^-1 s^-1","isCorrect":false},{"text":"mol^2 L^-2 s^-1","isCorrect":false}]'::jsonb,
 null, 'For a first-order reaction, rate = k[A], so k must have units of inverse time (s^-1) for the rate to come out in mol L^-1 s^-1.'),

-- Chemistry: Organic Chemistry
('BITSAT', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Butan-1-ol and butan-2-ol are examples of which type of isomerism?',
 '[{"text":"Chain isomerism","isCorrect":false},{"text":"Positional isomerism","isCorrect":true},{"text":"Functional group isomerism","isCorrect":false},{"text":"Metamerism","isCorrect":false}]'::jsonb,
 null, 'Butan-1-ol and butan-2-ol have the same carbon skeleton and functional group but differ in the position of the -OH group, making them positional isomers.'),
('BITSAT', 'Chemistry', 'Organic Chemistry', 'hard', 'mcq',
 'An SN1 nucleophilic substitution reaction proceeds through which type of intermediate?',
 '[{"text":"Carbanion","isCorrect":false},{"text":"Carbocation","isCorrect":true},{"text":"Free radical","isCorrect":false},{"text":"Carbene","isCorrect":false}]'::jsonb,
 null, 'SN1 reactions proceed via a two-step mechanism through a carbocation intermediate, formed after the leaving group departs in the rate-determining step.'),
('BITSAT', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The functional group that characterizes an amine is:',
 '[{"text":"-OH","isCorrect":false},{"text":"-NH2","isCorrect":true},{"text":"-COOH","isCorrect":false},{"text":"-CHO","isCorrect":false}]'::jsonb,
 null, 'Amines are characterized by the amino functional group, -NH2 (or its substituted forms), attached to a carbon chain.'),
('BITSAT', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Benzene predominantly undergoes electrophilic substitution rather than addition reactions mainly because of:',
 '[{"text":"Its aromatic stability from delocalized pi electrons","isCorrect":true},{"text":"Its high boiling point","isCorrect":false},{"text":"The presence of single bonds only","isCorrect":false},{"text":"Its low molecular weight","isCorrect":false}]'::jsonb,
 null, 'Benzene''s delocalized ring of pi electrons gives it substantial aromatic stability, which addition reactions would disrupt -- so substitution, which preserves the ring, is strongly favored.'),

-- Chemistry: Inorganic Chemistry
('BITSAT', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which element has the highest electronegativity on the periodic table?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Fluorine","isCorrect":true},{"text":"Chlorine","isCorrect":false},{"text":"Nitrogen","isCorrect":false}]'::jsonb,
 null, 'Fluorine, being the smallest halogen with the strongest pull on bonding electrons, has the highest electronegativity of all elements.'),
('BITSAT', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The general outer electronic configuration of alkali metals (group 1) is:',
 '[{"text":"ns1","isCorrect":true},{"text":"ns2","isCorrect":false},{"text":"ns2np1","isCorrect":false},{"text":"ns2np5","isCorrect":false}]'::jsonb,
 null, 'Alkali metals (group 1) have a single electron in their outermost s-orbital, giving the general configuration ns1.'),
('BITSAT', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Which of the following oxides is amphoteric (reacts with both acids and bases)?',
 '[{"text":"Na2O","isCorrect":false},{"text":"Al2O3","isCorrect":true},{"text":"SO3","isCorrect":false},{"text":"MgO","isCorrect":false}]'::jsonb,
 null, 'Aluminum oxide, Al2O3, is amphoteric, reacting with both strong acids (forming Al3+ salts) and strong bases (forming aluminate ions).'),
('BITSAT', 'Chemistry', 'Inorganic Chemistry', 'hard', 'mcq',
 'The molecular shape of PCl5, according to VSEPR theory, is:',
 '[{"text":"Tetrahedral","isCorrect":false},{"text":"Trigonal bipyramidal","isCorrect":true},{"text":"Octahedral","isCorrect":false},{"text":"Square planar","isCorrect":false}]'::jsonb,
 null, 'PCl5 has 5 bonding electron domains around phosphorus with no lone pairs, giving it a trigonal bipyramidal geometry.'),

-- Chemistry: States of Matter and Environmental Chemistry
('BITSAT', 'Chemistry', 'States of Matter and Environmental Chemistry', 'easy', 'mcq',
 'The gas law stating that pressure is inversely proportional to volume at constant temperature is:',
 '[{"text":"Boyle''s law","isCorrect":true},{"text":"Charles'' law","isCorrect":false},{"text":"Gay-Lussac''s law","isCorrect":false},{"text":"Avogadro''s law","isCorrect":false}]'::jsonb,
 null, 'Boyle''s law states that at constant temperature, the pressure of a fixed amount of gas is inversely proportional to its volume.'),
('BITSAT', 'Chemistry', 'States of Matter and Environmental Chemistry', 'medium', 'mcq',
 'Real gases deviate most from ideal gas behavior under conditions of:',
 '[{"text":"High temperature and low pressure","isCorrect":false},{"text":"High pressure and low temperature","isCorrect":true},{"text":"Low pressure and low temperature","isCorrect":false},{"text":"High temperature and high pressure equally","isCorrect":false}]'::jsonb,
 null, 'At high pressure and low temperature, intermolecular forces and the finite volume of gas molecules become significant, causing the greatest deviation from ideal gas behavior.'),
('BITSAT', 'Chemistry', 'States of Matter and Environmental Chemistry', 'easy', 'mcq',
 'The greenhouse effect is primarily caused by certain gases trapping which type of radiation?',
 '[{"text":"Ultraviolet radiation","isCorrect":false},{"text":"Infrared radiation","isCorrect":true},{"text":"Visible light","isCorrect":false},{"text":"X-rays","isCorrect":false}]'::jsonb,
 null, 'Greenhouse gases absorb and re-radiate infrared (heat) radiation emitted by the Earth''s surface, trapping heat within the atmosphere.'),
('BITSAT', 'Chemistry', 'States of Matter and Environmental Chemistry', 'medium', 'mcq',
 'Which of the following is classified as a secondary air pollutant?',
 '[{"text":"Carbon monoxide","isCorrect":false},{"text":"Ozone (ground-level)","isCorrect":true},{"text":"Sulfur dioxide","isCorrect":false},{"text":"Soot","isCorrect":false}]'::jsonb,
 null, 'Ground-level ozone is a secondary pollutant, formed by photochemical reactions between primary pollutants (like nitrogen oxides and volatile organic compounds) in sunlight, rather than being emitted directly.'),

-- Mathematics: Algebra and Trigonometry
('BITSAT', 'Mathematics', 'Algebra and Trigonometry', 'easy', 'mcq',
 'The sum of the roots of the quadratic equation x^2 - 5x + 6 = 0 is:',
 '[{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"-5","isCorrect":false},{"text":"11","isCorrect":false}]'::jsonb,
 null, 'For x^2-5x+6=0, the sum of roots equals -(-5)/1 = 5, by the standard sum-of-roots formula -b/a.'),
('BITSAT', 'Mathematics', 'Algebra and Trigonometry', 'easy', 'mcq',
 'The value of sin(30 degrees) is:',
 '[{"text":"1","isCorrect":false},{"text":"1/2","isCorrect":true},{"text":"sqrt(3)/2","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'sin(30 degrees) is a standard trigonometric value equal to 1/2.'),
('BITSAT', 'Mathematics', 'Algebra and Trigonometry', 'medium', 'mcq',
 'The number of ways to choose 3 objects from a set of 5 distinct objects (order not mattering) is:',
 '[{"text":"10","isCorrect":true},{"text":"15","isCorrect":false},{"text":"20","isCorrect":false},{"text":"60","isCorrect":false}]'::jsonb,
 null, 'C(5,3) = 5!/(3!*2!) = 10.'),
('BITSAT', 'Mathematics', 'Algebra and Trigonometry', 'medium', 'mcq',
 'If a, b, c are three terms in arithmetic progression, then:',
 '[{"text":"2b = a + c","isCorrect":true},{"text":"b^2 = a*c","isCorrect":false},{"text":"b = a*c","isCorrect":false},{"text":"2a = b + c","isCorrect":false}]'::jsonb,
 null, 'For three terms in arithmetic progression, the middle term is the average of the outer two, so 2b = a + c.'),

-- Mathematics: Calculus
('BITSAT', 'Mathematics', 'Calculus', 'easy', 'mcq',
 'The derivative of sin(x) with respect to x is:',
 '[{"text":"cos(x)","isCorrect":true},{"text":"-cos(x)","isCorrect":false},{"text":"-sin(x)","isCorrect":false},{"text":"tan(x)","isCorrect":false}]'::jsonb,
 null, 'By standard differentiation rules, d/dx[sin(x)] = cos(x).'),
('BITSAT', 'Mathematics', 'Calculus', 'medium', 'mcq',
 'The value of the integral of 1/x dx is:',
 '[{"text":"x^2/2 + C","isCorrect":false},{"text":"ln|x| + C","isCorrect":true},{"text":"1/x^2 + C","isCorrect":false},{"text":"-1/x + C","isCorrect":false}]'::jsonb,
 null, 'The antiderivative of 1/x is the natural logarithm of the absolute value of x, plus a constant of integration.'),
('BITSAT', 'Mathematics', 'Calculus', 'medium', 'mcq',
 'A function f is said to be continuous at a point x=a if:',
 '[{"text":"f is differentiable at x=a","isCorrect":false},{"text":"The limit of f(x) as x approaches a equals f(a)","isCorrect":true},{"text":"f(a) is defined, regardless of the limit","isCorrect":false},{"text":"f is bounded near x=a","isCorrect":false}]'::jsonb,
 null, 'Continuity at a point requires that the limit of f(x) as x approaches a exists and equals f(a) -- differentiability is a stricter, additional condition.'),
('BITSAT', 'Mathematics', 'Calculus', 'easy', 'mcq',
 'The derivative of a constant function f(x) = k is:',
 '[{"text":"k","isCorrect":false},{"text":"0","isCorrect":true},{"text":"1","isCorrect":false},{"text":"x","isCorrect":false}]'::jsonb,
 null, 'A constant function does not change as x varies, so its rate of change (derivative) is always 0.'),

-- Mathematics: Coordinate Geometry
('BITSAT', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The distance between the points (0,0) and (3,4) is:',
 '[{"text":"5","isCorrect":true},{"text":"7","isCorrect":false},{"text":"25","isCorrect":false},{"text":"3.5","isCorrect":false}]'::jsonb,
 null, 'Distance = sqrt(3^2+4^2) = sqrt(9+16) = sqrt(25) = 5.'),
('BITSAT', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The equation of a circle centered at the origin with radius r is:',
 '[{"text":"x^2 + y^2 = r^2","isCorrect":true},{"text":"x + y = r","isCorrect":false},{"text":"x^2 - y^2 = r^2","isCorrect":false},{"text":"x^2 + y^2 = r","isCorrect":false}]'::jsonb,
 null, 'A circle centered at the origin consists of all points whose distance from the origin is r, giving the equation x^2+y^2=r^2.'),
('BITSAT', 'Mathematics', 'Coordinate Geometry', 'medium', 'mcq',
 'Two lines with slopes m1 and m2 are perpendicular to each other if:',
 '[{"text":"m1 = m2","isCorrect":false},{"text":"m1*m2 = -1","isCorrect":true},{"text":"m1 + m2 = 0","isCorrect":false},{"text":"m1*m2 = 1","isCorrect":false}]'::jsonb,
 null, 'Two lines are perpendicular precisely when the product of their slopes equals -1 (assuming neither is vertical).'),
('BITSAT', 'Mathematics', 'Coordinate Geometry', 'easy', 'mcq',
 'The midpoint of the line segment joining (2,3) and (6,7) is:',
 '[{"text":"(4,5)","isCorrect":true},{"text":"(8,10)","isCorrect":false},{"text":"(3,4)","isCorrect":false},{"text":"(2,7)","isCorrect":false}]'::jsonb,
 null, 'The midpoint formula gives ((2+6)/2, (3+7)/2) = (4,5).'),

-- Mathematics: Vectors, 3D Geometry and Statistics
('BITSAT', 'Mathematics', 'Vectors, 3D Geometry and Statistics', 'easy', 'mcq',
 'The dot product of two mutually perpendicular vectors is:',
 '[{"text":"1","isCorrect":false},{"text":"0","isCorrect":true},{"text":"Equal to the product of their magnitudes","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'The dot product a.b = |a||b|cos(theta); for perpendicular vectors, theta=90 degrees and cos(90)=0, so the dot product is 0.'),
('BITSAT', 'Mathematics', 'Vectors, 3D Geometry and Statistics', 'easy', 'mcq',
 'The magnitude of the vector (3,4) is:',
 '[{"text":"5","isCorrect":true},{"text":"7","isCorrect":false},{"text":"12","isCorrect":false},{"text":"25","isCorrect":false}]'::jsonb,
 null, '|(3,4)| = sqrt(3^2+4^2) = sqrt(25) = 5.'),
('BITSAT', 'Mathematics', 'Vectors, 3D Geometry and Statistics', 'easy', 'mcq',
 'The mean of the numbers 2, 4, 6, 8, 10 is:',
 '[{"text":"6","isCorrect":true},{"text":"5","isCorrect":false},{"text":"8","isCorrect":false},{"text":"30","isCorrect":false}]'::jsonb,
 null, 'Mean = (2+4+6+8+10)/5 = 30/5 = 6.'),
('BITSAT', 'Mathematics', 'Vectors, 3D Geometry and Statistics', 'medium', 'mcq',
 'Variance, as a statistical measure, describes:',
 '[{"text":"The average value of a data set","isCorrect":false},{"text":"The spread (dispersion) of data around the mean","isCorrect":true},{"text":"The most frequently occurring value","isCorrect":false},{"text":"The middle value when data is sorted","isCorrect":false}]'::jsonb,
 null, 'Variance quantifies how spread out data points are from the mean, computed as the average of squared deviations from the mean.'),

-- English Proficiency: Grammar and Usage
('BITSAT', 'English Proficiency', 'Grammar and Usage', 'medium', 'mcq',
 'Which sentence is grammatically correct?',
 '[{"text":"Neither of the boys have finished their homework.","isCorrect":false},{"text":"Neither of the boys has finished his homework.","isCorrect":true},{"text":"Neither of the boys have finished his homework.","isCorrect":false},{"text":"Neither of the boys has finished their homeworks.","isCorrect":false}]'::jsonb,
 null, '"Neither" is a singular subject, so it takes the singular verb "has" and the singular possessive "his" (or "her"), not the plural "have"/"their".'),
('BITSAT', 'English Proficiency', 'Grammar and Usage', 'easy', 'mcq',
 'Choose the correct preposition to complete the sentence: "She is good ___ mathematics."',
 '[{"text":"in","isCorrect":false},{"text":"at","isCorrect":true},{"text":"on","isCorrect":false},{"text":"with","isCorrect":false}]'::jsonb,
 null, 'The idiomatic preposition used with "good" to describe skill in a subject is "at" -- "good at mathematics".'),
('BITSAT', 'English Proficiency', 'Grammar and Usage', 'medium', 'mcq',
 'Which of the following sentences is free of a comma splice?',
 '[{"text":"It was raining, we still went for a walk.","isCorrect":false},{"text":"It was raining, but we still went for a walk.","isCorrect":true},{"text":"It was raining we still went for a walk.","isCorrect":false},{"text":"It was raining, therefore, we still went for a walk without therefore making sense here.","isCorrect":false}]'::jsonb,
 null, 'Joining two independent clauses with only a comma creates a comma splice; adding a coordinating conjunction like "but" correctly joins the clauses.'),
('BITSAT', 'English Proficiency', 'Grammar and Usage', 'medium', 'mcq',
 'What is the correct passive voice form of "She writes a letter"?',
 '[{"text":"A letter is written by her.","isCorrect":true},{"text":"A letter was written by her.","isCorrect":false},{"text":"A letter has written her.","isCorrect":false},{"text":"She is written a letter.","isCorrect":false}]'::jsonb,
 null, 'The present simple active "She writes a letter" becomes "A letter is written by her" in the passive voice, keeping the same present tense.'),

-- English Proficiency: Vocabulary and Reading Comprehension
('BITSAT', 'English Proficiency', 'Vocabulary and Reading Comprehension', 'medium', 'mcq',
 'Choose the word closest in meaning to "Ubiquitous".',
 '[{"text":"Rare","isCorrect":false},{"text":"Omnipresent","isCorrect":true},{"text":"Ancient","isCorrect":false},{"text":"Fragile","isCorrect":false}]'::jsonb,
 null, '"Ubiquitous" means present or found everywhere, making "omnipresent" its closest synonym.'),
('BITSAT', 'English Proficiency', 'Vocabulary and Reading Comprehension', 'medium', 'mcq',
 'Choose the antonym of "Benevolent".',
 '[{"text":"Generous","isCorrect":false},{"text":"Malevolent","isCorrect":true},{"text":"Kind","isCorrect":false},{"text":"Charitable","isCorrect":false}]'::jsonb,
 null, '"Benevolent" means kind and well-meaning; its direct antonym is "malevolent", meaning having harmful or evil intent.'),
('BITSAT', 'English Proficiency', 'Vocabulary and Reading Comprehension', 'easy', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Definately","isCorrect":false},{"text":"Definitely","isCorrect":true},{"text":"Definitly","isCorrect":false},{"text":"Deffinitely","isCorrect":false}]'::jsonb,
 null, '"Definitely" is the correct spelling; "definately" is a common misspelling.'),
('BITSAT', 'English Proficiency', 'Vocabulary and Reading Comprehension', 'medium', 'mcq',
 'Choose the word that best completes the sentence: "The detective''s ___ observations helped solve the case."',
 '[{"text":"Astute","isCorrect":true},{"text":"Careless","isCorrect":false},{"text":"Vague","isCorrect":false},{"text":"Trivial","isCorrect":false}]'::jsonb,
 null, '"Astute" means shrewd and perceptive, fitting the context of observations that were sharp enough to help solve a case.'),

-- Logical Reasoning: Verbal Reasoning
('BITSAT', 'Logical Reasoning', 'Verbal Reasoning', 'easy', 'mcq',
 'Find the odd one out: Apple, Banana, Carrot, Mango.',
 '[{"text":"Apple","isCorrect":false},{"text":"Banana","isCorrect":false},{"text":"Carrot","isCorrect":true},{"text":"Mango","isCorrect":false}]'::jsonb,
 null, 'Apple, Banana, and Mango are all fruits, while Carrot is a vegetable, making it the odd one out.'),
('BITSAT', 'Logical Reasoning', 'Verbal Reasoning', 'easy', 'mcq',
 'Complete the analogy: Doctor is to Hospital as Teacher is to:',
 '[{"text":"Classroom","isCorrect":false},{"text":"School","isCorrect":true},{"text":"Book","isCorrect":false},{"text":"Student","isCorrect":false}]'::jsonb,
 null, 'A doctor primarily works at a hospital; the analogous primary workplace for a teacher is a school (the broader institution, rather than just a classroom within it).'),
('BITSAT', 'Logical Reasoning', 'Verbal Reasoning', 'medium', 'mcq',
 'Given: "All cats are animals" and "All animals need food." Which conclusion logically follows?',
 '[{"text":"All cats need food.","isCorrect":true},{"text":"All animals are cats.","isCorrect":false},{"text":"Some animals are not cats.","isCorrect":false},{"text":"No cats need food.","isCorrect":false}]'::jsonb,
 null, 'By transitive syllogism, since all cats are animals and all animals need food, it logically follows that all cats need food.'),
('BITSAT', 'Logical Reasoning', 'Verbal Reasoning', 'hard', 'mcq',
 'In a certain code, "CAT" is written as "DBU". How is "DOG" written in the same code?',
 '[{"text":"EPH","isCorrect":true},{"text":"EPI","isCorrect":false},{"text":"DPH","isCorrect":false},{"text":"EOH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one position in the alphabet (C to D, A to B, T to U), so applying the same shift to D-O-G gives E-P-H.'),

-- Logical Reasoning: Nonverbal and Analytical Reasoning
('BITSAT', 'Logical Reasoning', 'Nonverbal and Analytical Reasoning', 'easy', 'mcq',
 'Find the next number in the series: 2, 4, 8, 16, ?',
 '[{"text":"20","isCorrect":false},{"text":"24","isCorrect":false},{"text":"32","isCorrect":true},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'Each term is double the previous term, so after 16 the next term is 16*2=32.'),
('BITSAT', 'Logical Reasoning', 'Nonverbal and Analytical Reasoning', 'medium', 'mcq',
 'Find the next number in the series: 1, 1, 2, 3, 5, 8, ?',
 '[{"text":"11","isCorrect":false},{"text":"13","isCorrect":true},{"text":"12","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'This is the Fibonacci sequence, where each term is the sum of the two preceding terms: 5+8=13.'),
('BITSAT', 'Logical Reasoning', 'Nonverbal and Analytical Reasoning', 'easy', 'mcq',
 'A is taller than B. B is taller than C. Who is the tallest among the three?',
 '[{"text":"A","isCorrect":true},{"text":"B","isCorrect":false},{"text":"C","isCorrect":false},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'Since A is taller than B, and B is taller than C, by transitivity A is taller than both B and C, making A the tallest.'),
('BITSAT', 'Logical Reasoning', 'Nonverbal and Analytical Reasoning', 'medium', 'mcq',
 'If today is Monday, what day of the week will it be after 10 days?',
 '[{"text":"Wednesday","isCorrect":false},{"text":"Thursday","isCorrect":true},{"text":"Friday","isCorrect":false},{"text":"Tuesday","isCorrect":false}]'::jsonb,
 null, '10 days is 1 full week (7 days) plus 3 extra days; 3 days after Monday is Thursday.');
