-- supabase/sql/exam_question_bank_neet_pg_set4.sql
--
-- Fourth curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and Sets 1-3 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1, 2, or 3.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical
-- Sciences, 4 Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/
-- Anesthesia) each get 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql / set2.sql / set3.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The median nerve passes through which structure at the wrist?',
 '[{"text":"Carpal tunnel","isCorrect":true},{"text":"Cubital tunnel","isCorrect":false},{"text":"Tarsal tunnel","isCorrect":false},{"text":"Inguinal canal","isCorrect":false}]'::jsonb,
 null, 'The median nerve passes through the carpal tunnel at the wrist, alongside the flexor tendons; its compression there causes carpal tunnel syndrome.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'easy', 'mcq',
 'The greater omentum is a fold of which membrane?',
 '[{"text":"Pleura","isCorrect":false},{"text":"Peritoneum","isCorrect":true},{"text":"Pericardium","isCorrect":false},{"text":"Meninges","isCorrect":false}]'::jsonb,
 null, 'The greater omentum is a large fold of peritoneum that hangs from the stomach, covering the abdominal viscera.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Which coronary artery typically supplies the anterior two-thirds of the interventricular septum?',
 '[{"text":"Right coronary artery","isCorrect":false},{"text":"Left anterior descending artery (LAD)","isCorrect":true},{"text":"Circumflex artery","isCorrect":false},{"text":"Posterior descending artery","isCorrect":false}]'::jsonb,
 null, 'The left anterior descending (LAD) artery typically supplies the anterior two-thirds of the interventricular septum, along with the anterior left ventricular wall.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'easy', 'mcq',
 'The pyloric sphincter is located between the stomach and the:',
 '[{"text":"Esophagus","isCorrect":false},{"text":"Duodenum","isCorrect":true},{"text":"Jejunum","isCorrect":false},{"text":"Ileum","isCorrect":false}]'::jsonb,
 null, 'The pyloric sphincter regulates the passage of stomach contents into the duodenum, the first part of the small intestine.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'The normal respiratory rate in a healthy adult at rest is approximately:',
 '[{"text":"4-8 breaths per minute","isCorrect":false},{"text":"12-20 breaths per minute","isCorrect":true},{"text":"30-40 breaths per minute","isCorrect":false},{"text":"50-60 breaths per minute","isCorrect":false}]'::jsonb,
 null, 'A normal resting respiratory rate in healthy adults typically ranges from 12 to 20 breaths per minute.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'Which blood cells are primarily responsible for clot formation?',
 '[{"text":"Red blood cells","isCorrect":false},{"text":"Platelets (thrombocytes)","isCorrect":true},{"text":"White blood cells","isCorrect":false},{"text":"Plasma cells","isCorrect":false}]'::jsonb,
 null, 'Platelets (thrombocytes) aggregate at sites of vascular injury and are essential for initiating clot (thrombus) formation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which hormone is primarily responsible for stimulating milk ejection during breastfeeding?',
 '[{"text":"Prolactin","isCorrect":false},{"text":"Oxytocin","isCorrect":true},{"text":"Estrogen","isCorrect":false},{"text":"Progesterone","isCorrect":false}]'::jsonb,
 null, 'Oxytocin triggers the milk ejection (let-down) reflex, while prolactin primarily stimulates milk production itself.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which part of the inner ear is primarily responsible for maintaining balance?',
 '[{"text":"Cochlea","isCorrect":false},{"text":"Vestibular apparatus (semicircular canals)","isCorrect":true},{"text":"Eardrum (tympanic membrane)","isCorrect":false},{"text":"Ossicles","isCorrect":false}]'::jsonb,
 null, 'The vestibular apparatus, including the semicircular canals, detects head movement and orientation, playing the primary role in maintaining balance.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Urea, the primary nitrogenous waste product excreted by humans, is synthesized in the:',
 '[{"text":"Kidney","isCorrect":false},{"text":"Liver (via the urea cycle)","isCorrect":true},{"text":"Pancreas","isCorrect":false},{"text":"Spleen","isCorrect":false}]'::jsonb,
 null, 'Urea is synthesized in the liver through the urea cycle, converting toxic ammonia into a less toxic, excretable form.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Deficiency of which vitamin classically causes megaloblastic anemia?',
 '[{"text":"Vitamin B12 (or folate)","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin E","isCorrect":false}]'::jsonb,
 null, 'Deficiency of vitamin B12 or folate impairs DNA synthesis in rapidly dividing cells, causing megaloblastic anemia with abnormally large red blood cell precursors.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'The enzyme responsible for converting angiotensin I to angiotensin II is:',
 '[{"text":"Renin","isCorrect":false},{"text":"Angiotensin-converting enzyme (ACE)","isCorrect":true},{"text":"Aldosterone synthase","isCorrect":false},{"text":"Cholinesterase","isCorrect":false}]'::jsonb,
 null, 'Angiotensin-converting enzyme (ACE), found mainly in pulmonary capillaries, converts the relatively inactive angiotensin I into the potent vasoconstrictor angiotensin II.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Which lipoprotein is often referred to as "bad cholesterol" due to its association with atherosclerosis?',
 '[{"text":"HDL (high-density lipoprotein)","isCorrect":false},{"text":"LDL (low-density lipoprotein)","isCorrect":true},{"text":"Chylomicrons","isCorrect":false},{"text":"Albumin","isCorrect":false}]'::jsonb,
 null, 'LDL cholesterol is termed "bad cholesterol" because elevated levels contribute to the buildup of arterial plaques and atherosclerosis.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which type of shock is characterized by widespread vasodilation due to a severe infection?',
 '[{"text":"Cardiogenic shock","isCorrect":false},{"text":"Septic shock","isCorrect":true},{"text":"Hypovolemic shock","isCorrect":false},{"text":"Anaphylactic shock only","isCorrect":false}]'::jsonb,
 null, 'Septic shock results from an overwhelming systemic inflammatory response to infection, causing widespread vasodilation and dangerously low blood pressure.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'A "signet ring cell" appearance on histology is classically associated with which malignancy?',
 '[{"text":"Signet ring cell carcinoma of the stomach","isCorrect":true},{"text":"Basal cell carcinoma","isCorrect":false},{"text":"Squamous cell carcinoma of the skin","isCorrect":false},{"text":"Osteosarcoma","isCorrect":false}]'::jsonb,
 null, 'Signet ring cells, containing a large mucin vacuole that pushes the nucleus to the periphery, are classically associated with signet ring cell carcinoma of the stomach.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Dysplasia is best described as:',
 '[{"text":"Irreversible malignant transformation","isCorrect":false},{"text":"Abnormal but potentially reversible changes in cell size, shape, and organization","isCorrect":true},{"text":"Complete cell death","isCorrect":false},{"text":"Normal cell replacement","isCorrect":false}]'::jsonb,
 null, 'Dysplasia refers to disordered but potentially reversible cellular growth, characterized by variation in cell size, shape, and architectural organization -- a precursor to, but distinct from, cancer.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'Which type of hypersensitivity reaction involves the deposition of antigen-antibody immune complexes?',
 '[{"text":"Type I hypersensitivity","isCorrect":false},{"text":"Type III hypersensitivity","isCorrect":true},{"text":"Type IV hypersensitivity","isCorrect":false},{"text":"Type II hypersensitivity","isCorrect":false}]'::jsonb,
 null, 'Type III hypersensitivity reactions are mediated by the deposition of antigen-antibody immune complexes in tissues, triggering complement activation and inflammation.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Dengue fever is caused by which type of organism?',
 '[{"text":"Dengue virus (a Flavivirus)","isCorrect":true},{"text":"A bacterium","isCorrect":false},{"text":"A protozoan parasite","isCorrect":false},{"text":"A fungus","isCorrect":false}]'::jsonb,
 null, 'Dengue fever is caused by the dengue virus, a Flavivirus transmitted by Aedes mosquitoes.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'The BCG vaccine provides protection primarily against which disease?',
 '[{"text":"Tuberculosis","isCorrect":true},{"text":"Measles","isCorrect":false},{"text":"Polio","isCorrect":false},{"text":"Diphtheria","isCorrect":false}]'::jsonb,
 null, 'BCG (Bacillus Calmette-Guerin) vaccine is used to provide protection against severe forms of tuberculosis, particularly in children.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Leprosy is caused by which organism?',
 '[{"text":"Mycobacterium tuberculosis","isCorrect":false},{"text":"Mycobacterium leprae","isCorrect":true},{"text":"Treponema pallidum","isCorrect":false},{"text":"Corynebacterium diphtheriae","isCorrect":false}]'::jsonb,
 null, 'Leprosy (Hansen''s disease) is caused by Mycobacterium leprae, an acid-fast bacterium affecting skin and peripheral nerves.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Which type of hepatitis virus is primarily transmitted via the fecal-oral route?',
 '[{"text":"Hepatitis A","isCorrect":true},{"text":"Hepatitis B","isCorrect":false},{"text":"Hepatitis C","isCorrect":false},{"text":"Hepatitis D","isCorrect":false}]'::jsonb,
 null, 'Hepatitis A virus is transmitted via the fecal-oral route, often through contaminated food or water, unlike hepatitis B and C, which spread through blood and body fluids.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which drug serves as the specific antidote for benzodiazepine overdose?',
 '[{"text":"Naloxone","isCorrect":false},{"text":"Flumazenil","isCorrect":true},{"text":"Atropine","isCorrect":false},{"text":"N-acetylcysteine","isCorrect":false}]'::jsonb,
 null, 'Flumazenil is a competitive benzodiazepine receptor antagonist used as the specific antidote to reverse benzodiazepine overdose.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Corticosteroids exert their anti-inflammatory effects primarily by:',
 '[{"text":"Directly killing bacteria","isCorrect":false},{"text":"Inhibiting the synthesis of inflammatory mediators (e.g. suppressing phospholipase A2)","isCorrect":true},{"text":"Increasing histamine release","isCorrect":false},{"text":"Blocking sodium channels","isCorrect":false}]'::jsonb,
 null, 'Corticosteroids suppress the enzyme phospholipase A2, reducing the production of prostaglandins and leukotrienes, thereby exerting broad anti-inflammatory effects.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which class of drugs lowers LDL cholesterol by inhibiting HMG-CoA reductase?',
 '[{"text":"Statins","isCorrect":true},{"text":"Beta-blockers","isCorrect":false},{"text":"ACE inhibitors","isCorrect":false},{"text":"Loop diuretics","isCorrect":false}]'::jsonb,
 null, 'Statins inhibit HMG-CoA reductase, a key rate-limiting enzyme in cholesterol synthesis, thereby lowering LDL cholesterol levels.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Furosemide, a commonly used diuretic, acts primarily on which part of the nephron?',
 '[{"text":"Proximal convoluted tubule","isCorrect":false},{"text":"Loop of Henle","isCorrect":true},{"text":"Collecting duct only","isCorrect":false},{"text":"Bowman''s capsule","isCorrect":false}]'::jsonb,
 null, 'Furosemide is a loop diuretic that inhibits sodium, potassium, and chloride reabsorption in the thick ascending limb of the loop of Henle.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'easy', 'mcq',
 'The term "asphyxia" refers to:',
 '[{"text":"A skin rash","isCorrect":false},{"text":"A condition of oxygen deprivation leading to unconsciousness or death","isCorrect":true},{"text":"A type of fracture","isCorrect":false},{"text":"A bleeding disorder","isCorrect":false}]'::jsonb,
 null, 'Asphyxia refers to a state of severely deficient oxygen supply to the body, which can lead to unconsciousness or death if not corrected.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Which class of poisons is classically associated with pinpoint pupils (miosis)?',
 '[{"text":"Opioids (e.g. morphine, heroin)","isCorrect":true},{"text":"Atropine and anticholinergics","isCorrect":false},{"text":"Alcohol","isCorrect":false},{"text":"Amphetamines","isCorrect":false}]'::jsonb,
 null, 'Opioid overdose classically presents with the triad of pinpoint pupils (miosis), respiratory depression, and decreased consciousness.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Exhumation, in medico-legal practice, refers to:',
 '[{"text":"A routine autopsy on a fresh body","isCorrect":false},{"text":"The legal disinterment of a buried body for examination","isCorrect":true},{"text":"Cremation of a body","isCorrect":false},{"text":"A living person''s medical examination","isCorrect":false}]'::jsonb,
 null, 'Exhumation is the legally authorized disinterment (digging up) of a buried body, typically for forensic examination in the course of an investigation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'In the later postmortem period, the time since death is often estimated primarily using:',
 '[{"text":"Body temperature alone","isCorrect":false},{"text":"The stage of decomposition/putrefaction","isCorrect":true},{"text":"Blood pressure readings","isCorrect":false},{"text":"Pupil size alone","isCorrect":false}]'::jsonb,
 null, 'While body temperature is useful in the early postmortem period, the progressive stages of decomposition and putrefaction become the primary indicator for estimating time since death later on.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Tertiary prevention in public health primarily focuses on:',
 '[{"text":"Preventing disease onset entirely","isCorrect":false},{"text":"Rehabilitation and minimizing complications of established disease","isCorrect":true},{"text":"Early screening for disease","isCorrect":false},{"text":"Vaccination programs only","isCorrect":false}]'::jsonb,
 null, 'Tertiary prevention aims to reduce the impact of an already-established disease through rehabilitation, minimizing disability, and preventing further complications.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'An "epidemic curve" is a graphical tool primarily used to:',
 '[{"text":"Show a patient''s vital signs over time","isCorrect":false},{"text":"Show the pattern and timing of cases during a disease outbreak","isCorrect":true},{"text":"Track hospital budgets","isCorrect":false},{"text":"Display a single patient''s lab results","isCorrect":false}]'::jsonb,
 null, 'An epidemic curve plots the number of new cases against time of onset, helping investigators understand the pattern, source, and spread of an outbreak.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which sampling method involves dividing a population into subgroups and randomly sampling from each?',
 '[{"text":"Convenience sampling","isCorrect":false},{"text":"Stratified random sampling","isCorrect":true},{"text":"Snowball sampling","isCorrect":false},{"text":"Purposive sampling","isCorrect":false}]'::jsonb,
 null, 'Stratified random sampling divides a population into relevant subgroups (strata) and then randomly samples from within each, improving representativeness.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'easy', 'mcq',
 'India''s Pulse Polio Programme primarily aims to:',
 '[{"text":"Treat tuberculosis patients","isCorrect":false},{"text":"Eradicate poliomyelitis through mass immunization","isCorrect":true},{"text":"Provide nutritional supplements only","isCorrect":false},{"text":"Screen for cancer","isCorrect":false}]'::jsonb,
 null, 'The Pulse Polio Programme is a mass immunization campaign in India aimed at eradicating poliomyelitis by ensuring high vaccination coverage among children.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'easy', 'mcq',
 'The most common cause of chronic obstructive pulmonary disease (COPD) is:',
 '[{"text":"Cigarette smoking","isCorrect":true},{"text":"Viral infection","isCorrect":false},{"text":"Genetic factors alone","isCorrect":false},{"text":"High altitude living","isCorrect":false}]'::jsonb,
 null, 'Cigarette smoking is by far the most common and significant risk factor for the development of chronic obstructive pulmonary disease.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Which condition is characterized by joint inflammation occurring alongside psoriasis?',
 '[{"text":"Rheumatoid arthritis","isCorrect":false},{"text":"Psoriatic arthritis","isCorrect":true},{"text":"Osteoarthritis","isCorrect":false},{"text":"Gout","isCorrect":false}]'::jsonb,
 null, 'Psoriatic arthritis is a form of inflammatory arthritis that occurs in some patients with psoriasis, affecting joints and sometimes the spine.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'hard', 'mcq',
 'Whipple''s classic triad for diagnosing insulinoma includes symptoms of hypoglycemia, documented low blood glucose during symptoms, and:',
 '[{"text":"Relief of symptoms after administration of glucose","isCorrect":true},{"text":"Persistent fever","isCorrect":false},{"text":"Elevated blood pressure","isCorrect":false},{"text":"Visible jaundice","isCorrect":false}]'::jsonb,
 null, 'Whipple''s triad for insulinoma consists of symptomatic hypoglycemia, a documented low blood glucose level at the time of symptoms, and resolution of symptoms upon glucose administration.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'easy', 'mcq',
 'Hypothyroidism commonly presents with which of the following features?',
 '[{"text":"Weight loss, heat intolerance, and tachycardia","isCorrect":false},{"text":"Fatigue, weight gain, and cold intolerance","isCorrect":true},{"text":"Excessive sweating and tremors","isCorrect":false},{"text":"Hyperactivity and insomnia","isCorrect":false}]'::jsonb,
 null, 'Hypothyroidism typically presents with fatigue, weight gain, cold intolerance, and other features of a slowed metabolism, in contrast to hyperthyroidism.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common cause of febrile seizures in young children is:',
 '[{"text":"A rapid rise in body temperature (fever), often due to viral infection","isCorrect":true},{"text":"Chronic epilepsy","isCorrect":false},{"text":"Vitamin deficiency alone","isCorrect":false},{"text":"Head trauma","isCorrect":false}]'::jsonb,
 null, 'Febrile seizures are most commonly triggered by a rapid rise in body temperature during a fever, frequently associated with viral illnesses.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Which condition, caused by surfactant deficiency, commonly affects premature infants?',
 '[{"text":"Respiratory Distress Syndrome (Hyaline Membrane Disease)","isCorrect":true},{"text":"Cystic fibrosis","isCorrect":false},{"text":"Asthma","isCorrect":false},{"text":"Croup","isCorrect":false}]'::jsonb,
 null, 'Respiratory Distress Syndrome (Hyaline Membrane Disease) results from insufficient surfactant production in premature infants, causing alveolar collapse and breathing difficulty.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'The BCG vaccine is typically administered at which site in newborns?',
 '[{"text":"Intradermally over the left deltoid/upper arm","isCorrect":true},{"text":"Orally","isCorrect":false},{"text":"Intravenously","isCorrect":false},{"text":"Into the eye","isCorrect":false}]'::jsonb,
 null, 'The BCG vaccine is administered intradermally, typically over the left deltoid region of the upper arm, in newborns.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Failure to thrive in infants refers to:',
 '[{"text":"Excessive weight gain compared to peers","isCorrect":false},{"text":"Inadequate physical growth compared to expected norms","isCorrect":true},{"text":"Delayed speech development only","isCorrect":false},{"text":"Excessive height for age","isCorrect":false}]'::jsonb,
 null, 'Failure to thrive describes inadequate physical growth (weight, height, or both) in an infant or child compared to established growth standards for their age.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which disorder is characterized by persistent, excessive worry about multiple areas of life?',
 '[{"text":"Generalized Anxiety Disorder (GAD)","isCorrect":true},{"text":"Specific phobia","isCorrect":false},{"text":"Obsessive-compulsive disorder","isCorrect":false},{"text":"Social anxiety disorder","isCorrect":false}]'::jsonb,
 null, 'Generalized Anxiety Disorder is characterized by persistent, excessive worry spanning multiple domains of life, lasting at least six months.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'Tardive dyskinesia, a long-term movement side effect, is most associated with which class of drugs?',
 '[{"text":"SSRIs","isCorrect":false},{"text":"Typical (first-generation) antipsychotics","isCorrect":true},{"text":"Benzodiazepines","isCorrect":false},{"text":"Beta-blockers","isCorrect":false}]'::jsonb,
 null, 'Tardive dyskinesia, characterized by involuntary repetitive movements, is a long-term side effect strongly associated with prolonged use of typical (first-generation) antipsychotics.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which eating disorder is characterized by episodes of binge eating followed by compensatory purging behaviors?',
 '[{"text":"Anorexia nervosa","isCorrect":false},{"text":"Bulimia nervosa","isCorrect":true},{"text":"Binge eating disorder alone (without purging)","isCorrect":false},{"text":"Pica","isCorrect":false}]'::jsonb,
 null, 'Bulimia nervosa is characterized by recurrent episodes of binge eating followed by compensatory behaviors like self-induced vomiting, laxative misuse, or excessive exercise.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Post-traumatic stress disorder (PTSD) develops following exposure to:',
 '[{"text":"A traumatic or life-threatening event","isCorrect":true},{"text":"Any minor stressful situation","isCorrect":false},{"text":"Normal childhood development","isCorrect":false},{"text":"Seasonal changes","isCorrect":false}]'::jsonb,
 null, 'PTSD develops in some individuals following exposure to a traumatic or life-threatening event, presenting with symptoms like intrusive memories, avoidance, and hyperarousal.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Rosacea is characterized by chronic inflammation and redness, commonly affecting which part of the body?',
 '[{"text":"The scalp","isCorrect":false},{"text":"The face","isCorrect":true},{"text":"The soles of the feet","isCorrect":false},{"text":"The palms of the hands","isCorrect":false}]'::jsonb,
 null, 'Rosacea is a chronic inflammatory skin condition that primarily affects the face, causing redness, flushing, and sometimes visible blood vessels or bumps.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Urticaria (hives) is primarily caused by:',
 '[{"text":"Release of histamine from mast cells","isCorrect":true},{"text":"Fungal infection of the skin","isCorrect":false},{"text":"Excess melanin production","isCorrect":false},{"text":"Chronic sun damage","isCorrect":false}]'::jsonb,
 null, 'Urticaria results from the release of histamine and other mediators from mast cells, causing itchy, raised welts on the skin.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Impetigo, a superficial bacterial skin infection common in children, is most commonly caused by:',
 '[{"text":"Staphylococcus aureus (or Streptococcus pyogenes)","isCorrect":true},{"text":"Candida albicans","isCorrect":false},{"text":"Herpes simplex virus","isCorrect":false},{"text":"Sarcoptes scabiei","isCorrect":false}]'::jsonb,
 null, 'Impetigo is most commonly caused by Staphylococcus aureus, and sometimes Streptococcus pyogenes, particularly affecting young children.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Which skin condition is classically characterized by honey-colored crusted lesions?',
 '[{"text":"Impetigo","isCorrect":true},{"text":"Psoriasis","isCorrect":false},{"text":"Eczema alone","isCorrect":false},{"text":"Vitiligo","isCorrect":false}]'::jsonb,
 null, 'Impetigo classically presents with honey-colored (golden), crusted lesions, typically on the face and other exposed areas.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common cause of upper gastrointestinal bleeding is:',
 '[{"text":"Peptic ulcer disease","isCorrect":true},{"text":"Colorectal cancer","isCorrect":false},{"text":"Hemorrhoids","isCorrect":false},{"text":"Appendicitis","isCorrect":false}]'::jsonb,
 null, 'Peptic ulcer disease (gastric or duodenal ulcers) is the most common cause of upper gastrointestinal bleeding.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'A positive Rovsing''s sign (pain in the right lower quadrant elicited by palpating the left lower quadrant) is associated with:',
 '[{"text":"Acute cholecystitis","isCorrect":false},{"text":"Acute appendicitis","isCorrect":true},{"text":"Acute pancreatitis","isCorrect":false},{"text":"Diverticulitis","isCorrect":false}]'::jsonb,
 null, 'Rovsing''s sign, in which palpation of the left lower quadrant causes referred pain in the right lower quadrant, is a classic finding suggestive of acute appendicitis.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Which condition, involving twisting of the testis and cutting off its blood supply, is a surgical emergency?',
 '[{"text":"Testicular torsion","isCorrect":true},{"text":"Varicocele","isCorrect":false},{"text":"Hydrocele","isCorrect":false},{"text":"Epididymitis","isCorrect":false}]'::jsonb,
 null, 'Testicular torsion, in which the spermatic cord twists and cuts off blood supply to the testis, is a surgical emergency requiring urgent intervention to prevent testicular loss.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common site for peptic ulcers is the:',
 '[{"text":"Esophagus","isCorrect":false},{"text":"Duodenum","isCorrect":true},{"text":"Jejunum","isCorrect":false},{"text":"Ileum","isCorrect":false}]'::jsonb,
 null, 'The duodenum (first part of the small intestine) is the most common site for peptic ulcers, followed by the stomach.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'A "boxer''s fracture" typically involves a fracture of which bone?',
 '[{"text":"The scaphoid","isCorrect":false},{"text":"The fifth metacarpal","isCorrect":true},{"text":"The radius","isCorrect":false},{"text":"The clavicle","isCorrect":false}]'::jsonb,
 null, 'A boxer''s fracture refers to a fracture of the neck of the fifth metacarpal, classically resulting from punching a hard object with a closed fist.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Rheumatoid arthritis primarily affects which type of joint?',
 '[{"text":"Synovial joints (typically small joints of hands and feet)","isCorrect":true},{"text":"Fibrous joints only","isCorrect":false},{"text":"Cartilaginous joints only","isCorrect":false},{"text":"Only weight-bearing joints","isCorrect":false}]'::jsonb,
 null, 'Rheumatoid arthritis is an autoimmune disease that primarily affects synovial joints, classically causing symmetric involvement of the small joints of the hands and feet.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'Osteoarthritis is best described as:',
 '[{"text":"An autoimmune inflammatory joint disease","isCorrect":false},{"text":"A degenerative joint disease due to wear and tear of cartilage","isCorrect":true},{"text":"A bacterial infection of the bone","isCorrect":false},{"text":"A congenital bone deformity","isCorrect":false}]'::jsonb,
 null, 'Osteoarthritis is a degenerative joint disease resulting from the gradual breakdown of articular cartilage, most commonly affecting weight-bearing joints with age and use.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common location for a herniated (slipped) intervertebral disc is the:',
 '[{"text":"Cervical spine","isCorrect":false},{"text":"Lumbar spine","isCorrect":true},{"text":"Thoracic spine","isCorrect":false},{"text":"Sacral spine","isCorrect":false}]'::jsonb,
 null, 'The lumbar spine, particularly the L4-L5 and L5-S1 levels, is the most common site for a herniated intervertebral disc due to the greater mechanical stress it bears.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The first stage of labor begins with the onset of regular contractions and ends with:',
 '[{"text":"Delivery of the baby","isCorrect":false},{"text":"Full cervical dilation (10 cm)","isCorrect":true},{"text":"Delivery of the placenta","isCorrect":false},{"text":"Rupture of membranes","isCorrect":false}]'::jsonb,
 null, 'The first stage of labor extends from the onset of regular contractions until the cervix is fully dilated to 10 cm.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Endometriosis is characterized by:',
 '[{"text":"Excess growth of the uterine muscle layer","isCorrect":false},{"text":"The presence of endometrial tissue outside the uterine cavity","isCorrect":true},{"text":"Complete absence of the endometrium","isCorrect":false},{"text":"Cancer of the cervix","isCorrect":false}]'::jsonb,
 null, 'Endometriosis occurs when tissue similar to the uterine lining (endometrium) grows outside the uterine cavity, often causing pain and infertility.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Which hormone level is used to help confirm the diagnosis of menopause?',
 '[{"text":"Follicle-stimulating hormone (FSH), which is elevated","isCorrect":true},{"text":"Beta-hCG","isCorrect":false},{"text":"Insulin","isCorrect":false},{"text":"Cortisol","isCorrect":false}]'::jsonb,
 null, 'As ovarian function declines at menopause, feedback inhibition weakens, causing follicle-stimulating hormone (FSH) levels to rise significantly.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'Cervical cancer is most strongly associated with persistent infection by:',
 '[{"text":"Human papillomavirus (HPV)","isCorrect":true},{"text":"Herpes simplex virus","isCorrect":false},{"text":"Hepatitis B virus","isCorrect":false},{"text":"HIV directly causing cancer","isCorrect":false}]'::jsonb,
 null, 'Persistent infection with high-risk strains of human papillomavirus (HPV) is the strongest known risk factor for the development of cervical cancer.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'easy', 'mcq',
 'Which drug is used to reverse the effects of an opioid overdose?',
 '[{"text":"Flumazenil","isCorrect":false},{"text":"Naloxone","isCorrect":true},{"text":"Atropine","isCorrect":false},{"text":"Protamine sulfate","isCorrect":false}]'::jsonb,
 null, 'Naloxone is an opioid receptor antagonist used to rapidly reverse the respiratory depression and sedation caused by opioid overdose.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'In the ABCDE approach to trauma assessment, the letters stand for Airway, Breathing, Circulation, Disability, and:',
 '[{"text":"Exposure","isCorrect":true},{"text":"Emergency","isCorrect":false},{"text":"Examination","isCorrect":false},{"text":"Evacuation","isCorrect":false}]'::jsonb,
 null, 'The ABCDE trauma assessment framework stands for Airway, Breathing, Circulation, Disability, and Exposure, ensuring a systematic evaluation of critically injured patients.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'easy', 'mcq',
 'Which type of anesthesia involves loss of consciousness and sensation throughout the entire body?',
 '[{"text":"Local anesthesia","isCorrect":false},{"text":"General anesthesia","isCorrect":true},{"text":"Regional anesthesia only","isCorrect":false},{"text":"Topical anesthesia","isCorrect":false}]'::jsonb,
 null, 'General anesthesia produces a reversible loss of consciousness and sensation throughout the entire body, unlike local or regional anesthesia, which numb only specific areas.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Sepsis is best defined as:',
 '[{"text":"Any localized bacterial skin infection","isCorrect":false},{"text":"A life-threatening organ dysfunction caused by a dysregulated host response to infection","isCorrect":true},{"text":"A mild, self-limiting viral illness","isCorrect":false},{"text":"An allergic reaction to medication","isCorrect":false}]'::jsonb,
 null, 'Sepsis is defined as life-threatening organ dysfunction resulting from a dysregulated host response to infection, distinguishing it from a simple, uncomplicated infection.');
