-- supabase/sql/exam_question_bank_neet_pg_set3.sql
--
-- Third curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and Sets 1-2 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Set 1 or Set 2.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical
-- Sciences, 4 Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/
-- Anesthesia) each get 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql / set2.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The brachial plexus is formed by the ventral rami of which spinal nerves?',
 '[{"text":"C1-C4","isCorrect":false},{"text":"C5-T1","isCorrect":true},{"text":"T1-T5","isCorrect":false},{"text":"L1-L5","isCorrect":false}]'::jsonb,
 null, 'The brachial plexus is formed by the ventral rami of spinal nerves C5 through T1, supplying the upper limb.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'easy', 'mcq',
 'The vagus nerve is which cranial nerve number?',
 '[{"text":"CN VII","isCorrect":false},{"text":"CN X","isCorrect":true},{"text":"CN XII","isCorrect":false},{"text":"CN IX","isCorrect":false}]'::jsonb,
 null, 'The vagus nerve is the tenth cranial nerve (CN X), with extensive parasympathetic distribution to the thorax and abdomen.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The diaphragm is primarily innervated by which nerve?',
 '[{"text":"Vagus nerve","isCorrect":false},{"text":"Phrenic nerve","isCorrect":true},{"text":"Intercostal nerves alone","isCorrect":false},{"text":"Sciatic nerve","isCorrect":false}]'::jsonb,
 null, 'The phrenic nerve (arising mainly from C4, with contributions from C3 and C5) provides the primary motor innervation to the diaphragm.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'hard', 'mcq',
 'The hepatic portal vein is formed by the union of which two veins?',
 '[{"text":"Renal vein and hepatic vein","isCorrect":false},{"text":"Superior mesenteric vein and splenic vein","isCorrect":true},{"text":"Inferior vena cava and superior vena cava","isCorrect":false},{"text":"Gastric vein and renal vein","isCorrect":false}]'::jsonb,
 null, 'The hepatic portal vein is formed behind the neck of the pancreas by the union of the superior mesenteric vein and the splenic vein.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The normal cardiac output in a resting healthy adult is approximately:',
 '[{"text":"1 L/min","isCorrect":false},{"text":"5 L/min","isCorrect":true},{"text":"15 L/min","isCorrect":false},{"text":"25 L/min","isCorrect":false}]'::jsonb,
 null, 'Resting cardiac output in a healthy adult is approximately 5 liters per minute, the product of heart rate and stroke volume.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which hormone primarily stimulates the reabsorption of water in the renal collecting ducts?',
 '[{"text":"Aldosterone","isCorrect":false},{"text":"Antidiuretic hormone (ADH/vasopressin)","isCorrect":true},{"text":"Insulin","isCorrect":false},{"text":"Cortisol","isCorrect":false}]'::jsonb,
 null, 'Antidiuretic hormone (ADH), released from the posterior pituitary, increases water reabsorption in the renal collecting ducts, concentrating urine.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The primary function of pulmonary surfactant is to:',
 '[{"text":"Increase surface tension in the alveoli","isCorrect":false},{"text":"Reduce surface tension in the alveoli, preventing collapse","isCorrect":true},{"text":"Increase mucus production in the airways","isCorrect":false},{"text":"Facilitate gas diffusion by thickening the alveolar membrane","isCorrect":false}]'::jsonb,
 null, 'Surfactant, produced by type II pneumocytes, reduces alveolar surface tension, preventing alveolar collapse (atelectasis) especially at low lung volumes.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'The normal fasting blood glucose level in a healthy adult is approximately:',
 '[{"text":"40-60 mg/dL","isCorrect":false},{"text":"70-100 mg/dL","isCorrect":true},{"text":"150-180 mg/dL","isCorrect":false},{"text":"200-250 mg/dL","isCorrect":false}]'::jsonb,
 null, 'Normal fasting plasma glucose in a healthy adult typically falls between 70 and 100 mg/dL.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Glycogen, the storage form of glucose in the body, is primarily stored in which two organs?',
 '[{"text":"Liver and skeletal muscle","isCorrect":true},{"text":"Brain and heart","isCorrect":false},{"text":"Kidney and spleen","isCorrect":false},{"text":"Lungs and pancreas","isCorrect":false}]'::jsonb,
 null, 'Glycogen is primarily stored in the liver (for maintaining blood glucose) and skeletal muscle (for local energy use).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'The genetic code is best described as a:',
 '[{"text":"Single-nucleotide code","isCorrect":false},{"text":"Triplet code (codons of three nucleotides)","isCorrect":true},{"text":"Four-nucleotide code","isCorrect":false},{"text":"Random, non-specific code","isCorrect":false}]'::jsonb,
 null, 'The genetic code is read in triplets (codons), with each set of three nucleotides specifying a particular amino acid or a stop signal.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Cholesterol serves as a precursor for the synthesis of:',
 '[{"text":"Steroid hormones, bile acids, and vitamin D","isCorrect":true},{"text":"All amino acids","isCorrect":false},{"text":"Glucose exclusively","isCorrect":false},{"text":"Hemoglobin","isCorrect":false}]'::jsonb,
 null, 'Cholesterol is a key precursor molecule for the synthesis of steroid hormones, bile acids, and vitamin D.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'hard', 'mcq',
 'Which enzyme is deficient in Gaucher''s disease?',
 '[{"text":"Glucocerebrosidase","isCorrect":true},{"text":"Hexosaminidase A","isCorrect":false},{"text":"Alpha-galactosidase A","isCorrect":false},{"text":"Sphingomyelinase","isCorrect":false}]'::jsonb,
 null, 'Gaucher''s disease is caused by a deficiency of the enzyme glucocerebrosidase, leading to accumulation of glucocerebroside in macrophages.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which type of necrosis is characteristic of ischemic injury to most solid organs, except the brain?',
 '[{"text":"Liquefactive necrosis","isCorrect":false},{"text":"Coagulative necrosis","isCorrect":true},{"text":"Caseous necrosis","isCorrect":false},{"text":"Fat necrosis","isCorrect":false}]'::jsonb,
 null, 'Coagulative necrosis, in which the tissue architecture is preserved despite cell death, is characteristic of ischemic injury in most solid organs like the heart and kidney.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Amyloidosis is characterized by:',
 '[{"text":"Intracellular accumulation of glycogen","isCorrect":false},{"text":"Abnormal extracellular deposition of misfolded protein fibrils","isCorrect":true},{"text":"Excess deposition of fat within cells","isCorrect":false},{"text":"Calcification of dead tissue","isCorrect":false}]'::jsonb,
 null, 'Amyloidosis results from the extracellular deposition of misfolded, insoluble protein fibrils (amyloid) that can damage organ function.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'The most common type of leukemia in adults (particularly in older adults) is:',
 '[{"text":"Acute lymphoblastic leukemia","isCorrect":false},{"text":"Chronic lymphocytic leukemia (CLL)","isCorrect":true},{"text":"Acute promyelocytic leukemia","isCorrect":false},{"text":"Juvenile myelomonocytic leukemia","isCorrect":false}]'::jsonb,
 null, 'Chronic lymphocytic leukemia is the most common type of leukemia in adults in Western countries, typically affecting older individuals.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Granuloma formation is a hallmark feature of which type of inflammation?',
 '[{"text":"Acute inflammation","isCorrect":false},{"text":"Chronic (granulomatous) inflammation","isCorrect":true},{"text":"Hyperacute inflammation","isCorrect":false},{"text":"Serous inflammation","isCorrect":false}]'::jsonb,
 null, 'Granulomas, organized collections of activated macrophages, are a hallmark of chronic granulomatous inflammation, seen in conditions like tuberculosis and sarcoidosis.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'The most common causative organism of urinary tract infections is:',
 '[{"text":"Escherichia coli","isCorrect":true},{"text":"Staphylococcus aureus","isCorrect":false},{"text":"Mycobacterium tuberculosis","isCorrect":false},{"text":"Streptococcus pyogenes","isCorrect":false}]'::jsonb,
 null, 'Escherichia coli, a gram-negative bacterium normally found in the gut, is the most common cause of urinary tract infections.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'The causative agent of malaria belongs to which group of organisms?',
 '[{"text":"Bacteria","isCorrect":false},{"text":"Protozoan parasites (Plasmodium species)","isCorrect":true},{"text":"Viruses","isCorrect":false},{"text":"Fungi","isCorrect":false}]'::jsonb,
 null, 'Malaria is caused by protozoan parasites of the genus Plasmodium, transmitted through the bite of infected female Anopheles mosquitoes.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Hepatitis B virus is primarily transmitted through:',
 '[{"text":"Contaminated food and water","isCorrect":false},{"text":"Blood and body fluids","isCorrect":true},{"text":"Airborne respiratory droplets","isCorrect":false},{"text":"Insect bites","isCorrect":false}]'::jsonb,
 null, 'Hepatitis B virus spreads primarily through exposure to infected blood and body fluids, including via sexual contact and from mother to child.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Which bacterium is strongly associated with peptic ulcer disease and chronic gastritis?',
 '[{"text":"Helicobacter pylori","isCorrect":true},{"text":"Escherichia coli","isCorrect":false},{"text":"Salmonella typhi","isCorrect":false},{"text":"Vibrio cholerae","isCorrect":false}]'::jsonb,
 null, 'Helicobacter pylori, a gram-negative bacterium colonizing the gastric mucosa, is strongly associated with peptic ulcer disease and chronic gastritis.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Aspirin exerts its antiplatelet effect by irreversibly inhibiting which enzyme?',
 '[{"text":"Cyclooxygenase (COX-1)","isCorrect":true},{"text":"Acetylcholinesterase","isCorrect":false},{"text":"Monoamine oxidase","isCorrect":false},{"text":"Xanthine oxidase","isCorrect":false}]'::jsonb,
 null, 'Aspirin irreversibly inhibits cyclooxygenase-1 (COX-1) in platelets, preventing thromboxane A2 synthesis and thereby reducing platelet aggregation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'hard', 'mcq',
 'Which class of antibiotics carries a rare but recognized risk of tendon rupture?',
 '[{"text":"Penicillins","isCorrect":false},{"text":"Fluoroquinolones","isCorrect":true},{"text":"Macrolides","isCorrect":false},{"text":"Tetracyclines","isCorrect":false}]'::jsonb,
 null, 'Fluoroquinolone antibiotics carry a rare but well-recognized risk of tendinitis and tendon rupture, particularly of the Achilles tendon.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Digoxin is primarily used in the treatment of:',
 '[{"text":"Heart failure and atrial fibrillation","isCorrect":true},{"text":"Bacterial infections","isCorrect":false},{"text":"Seizure disorders","isCorrect":false},{"text":"Peptic ulcer disease","isCorrect":false}]'::jsonb,
 null, 'Digoxin, a cardiac glycoside, is used in the management of heart failure and to control ventricular rate in atrial fibrillation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'Metformin is considered the first-line drug for the treatment of:',
 '[{"text":"Type 1 diabetes mellitus","isCorrect":false},{"text":"Type 2 diabetes mellitus","isCorrect":true},{"text":"Hypertension","isCorrect":false},{"text":"Hyperthyroidism","isCorrect":false}]'::jsonb,
 null, 'Metformin is the recommended first-line oral medication for managing Type 2 diabetes mellitus, working primarily by reducing hepatic glucose production.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'In medico-legal terminology, a "wound" refers to:',
 '[{"text":"Any internal disease process","isCorrect":false},{"text":"A break in the continuity of tissue caused by external violence","isCorrect":true},{"text":"A congenital deformity","isCorrect":false},{"text":"Any psychological trauma","isCorrect":false}]'::jsonb,
 null, 'In forensic medicine, a wound is defined as a break in the normal continuity of any bodily tissue, caused by the application of external violence.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Carbon monoxide poisoning is particularly dangerous because it:',
 '[{"text":"Directly destroys lung tissue","isCorrect":false},{"text":"Binds hemoglobin with much higher affinity than oxygen, causing hypoxia","isCorrect":true},{"text":"Causes immediate cardiac arrest in all cases","isCorrect":false},{"text":"Has no effect on blood at all","isCorrect":false}]'::jsonb,
 null, 'Carbon monoxide binds hemoglobin roughly 200 times more strongly than oxygen, forming carboxyhemoglobin and severely impairing oxygen delivery to tissues.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'The presence of fine, white froth at the mouth and nostrils of a body found in water is a classic sign of:',
 '[{"text":"Death by drowning","isCorrect":true},{"text":"Death by poisoning","isCorrect":false},{"text":"Death by strangulation","isCorrect":false},{"text":"Death by electrocution","isCorrect":false}]'::jsonb,
 null, 'A fine, white, mushroom-shaped froth at the mouth and nostrils is a classic (though not exclusive) sign suggesting death by drowning.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'hard', 'mcq',
 'Antemortem (before death) wounds can generally be distinguished from postmortem (after death) wounds by the presence of:',
 '[{"text":"Vital reaction (e.g. bleeding, inflammation, clot formation)","isCorrect":true},{"text":"Any wound at all, regardless of timing","isCorrect":false},{"text":"The wound''s exact size only","isCorrect":false},{"text":"The color of the surrounding skin alone","isCorrect":false}]'::jsonb,
 null, 'Antemortem wounds typically show signs of a living body''s response -- bleeding, inflammation, and clot formation -- known as vital reaction, which is absent or minimal in postmortem wounds.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'easy', 'mcq',
 'The "incubation period" of an infectious disease refers to:',
 '[{"text":"The time an infected person remains contagious","isCorrect":false},{"text":"The time between exposure to a pathogen and the onset of symptoms","isCorrect":true},{"text":"The duration of a full course of treatment","isCorrect":false},{"text":"The time needed for a vaccine to be manufactured","isCorrect":false}]'::jsonb,
 null, 'The incubation period is the interval between exposure to an infectious agent and the appearance of the first symptoms of disease.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which vaccine provides protection against the human papillomavirus (HPV), reducing the risk of cervical cancer?',
 '[{"text":"HPV vaccine","isCorrect":true},{"text":"BCG vaccine","isCorrect":false},{"text":"MMR vaccine","isCorrect":false},{"text":"Hepatitis B vaccine","isCorrect":false}]'::jsonb,
 null, 'The HPV vaccine protects against high-risk human papillomavirus strains, significantly reducing the risk of developing cervical cancer.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'India''s National Health Mission primarily aims to:',
 '[{"text":"Fund only private hospitals","isCorrect":false},{"text":"Improve healthcare access, especially in rural areas","isCorrect":true},{"text":"Focus exclusively on urban tertiary care","isCorrect":false},{"text":"Eliminate the need for public health programs","isCorrect":false}]'::jsonb,
 null, 'The National Health Mission aims to strengthen healthcare systems and improve access to affordable, quality healthcare, with a strong focus on rural and underserved populations.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Secondary prevention in public health primarily focuses on:',
 '[{"text":"Preventing exposure to risk factors altogether","isCorrect":false},{"text":"Early detection and treatment of disease","isCorrect":true},{"text":"Rehabilitation after disease has caused disability","isCorrect":false},{"text":"Building new hospitals only","isCorrect":false}]'::jsonb,
 null, 'Secondary prevention focuses on early detection (e.g. through screening) and prompt treatment of disease, aiming to halt or slow its progression.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'hard', 'mcq',
 'Charcot''s classic triad for multiple sclerosis includes nystagmus, intention tremor, and:',
 '[{"text":"Scanning (staccato) speech","isCorrect":true},{"text":"Jaundice","isCorrect":false},{"text":"Fever","isCorrect":false},{"text":"Hematuria","isCorrect":false}]'::jsonb,
 null, 'Charcot''s triad for multiple sclerosis classically includes nystagmus, intention tremor, and scanning (staccato) speech.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Which electrolyte abnormality is classically associated with peaked T waves on ECG?',
 '[{"text":"Hypokalemia","isCorrect":false},{"text":"Hyperkalemia","isCorrect":true},{"text":"Hyponatremia","isCorrect":false},{"text":"Hypercalcemia","isCorrect":false}]'::jsonb,
 null, 'Hyperkalemia classically produces tall, peaked T waves on ECG, and can progress to more severe conduction abnormalities if untreated.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common underlying cause of acute coronary syndrome is:',
 '[{"text":"Atherosclerotic plaque rupture with thrombosis","isCorrect":true},{"text":"Viral myocarditis","isCorrect":false},{"text":"Congenital heart defects","isCorrect":false},{"text":"Rheumatic heart disease alone","isCorrect":false}]'::jsonb,
 null, 'Acute coronary syndrome most commonly results from rupture of an atherosclerotic plaque in a coronary artery, triggering thrombus formation and vessel occlusion.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'easy', 'mcq',
 'Anemia is defined as a reduction in:',
 '[{"text":"White blood cell count","isCorrect":false},{"text":"Hemoglobin concentration below the normal range","isCorrect":true},{"text":"Platelet count","isCorrect":false},{"text":"Blood pressure","isCorrect":false}]'::jsonb,
 null, 'Anemia is defined as a reduction in hemoglobin concentration (or red blood cell mass) below the normal range for age and sex, reducing the blood''s oxygen-carrying capacity.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common cause of jaundice in the first week of life is:',
 '[{"text":"Physiological jaundice (immature liver conjugation)","isCorrect":true},{"text":"Biliary atresia","isCorrect":false},{"text":"Hepatitis A infection","isCorrect":false},{"text":"Wilson''s disease","isCorrect":false}]'::jsonb,
 null, 'Physiological jaundice, caused by the newborn liver''s temporary immaturity in conjugating bilirubin, is the most common cause of neonatal jaundice.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'hard', 'mcq',
 'Which pediatric condition is classically associated with "currant jelly" stool?',
 '[{"text":"Intussusception","isCorrect":true},{"text":"Appendicitis","isCorrect":false},{"text":"Pyloric stenosis","isCorrect":false},{"text":"Celiac disease","isCorrect":false}]'::jsonb,
 null, 'Intussusception, in which one segment of bowel telescopes into another, classically produces "currant jelly" stool due to mucosal bleeding and mucus mixing.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'The World Health Organization recommends exclusive breastfeeding for infants during:',
 '[{"text":"The first month of life only","isCorrect":false},{"text":"The first 6 months of life","isCorrect":true},{"text":"The first 2 years of life exclusively","isCorrect":false},{"text":"Only the first week of life","isCorrect":false}]'::jsonb,
 null, 'The WHO recommends exclusive breastfeeding for the first 6 months of an infant''s life, with continued breastfeeding alongside complementary foods thereafter.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Which of the following is a classic example of cyanotic congenital heart disease?',
 '[{"text":"Ventricular septal defect","isCorrect":false},{"text":"Tetralogy of Fallot","isCorrect":true},{"text":"Atrial septal defect","isCorrect":false},{"text":"Patent ductus arteriosus","isCorrect":false}]'::jsonb,
 null, 'Tetralogy of Fallot, involving right-to-left shunting, is the classic example of cyanotic congenital heart disease, unlike VSD, ASD, and PDA, which are typically acyanotic.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which therapeutic approach, based on gradual exposure, is considered first-line treatment for specific phobias?',
 '[{"text":"Exposure therapy (a form of cognitive behavioral therapy)","isCorrect":true},{"text":"Long-term psychoanalysis exclusively","isCorrect":false},{"text":"Electroconvulsive therapy","isCorrect":false},{"text":"High-dose antipsychotics","isCorrect":false}]'::jsonb,
 null, 'Exposure therapy, a core component of cognitive behavioral therapy, gradually exposes patients to the feared stimulus and is considered first-line treatment for specific phobias.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'A severe complication of alcohol withdrawal, characterized by confusion, tremors, and autonomic instability, is called:',
 '[{"text":"Delirium tremens","isCorrect":true},{"text":"Wernicke''s encephalopathy alone","isCorrect":false},{"text":"Korsakoff''s psychosis alone","isCorrect":false},{"text":"Alcoholic hepatitis","isCorrect":false}]'::jsonb,
 null, 'Delirium tremens is a severe, potentially life-threatening form of alcohol withdrawal characterized by confusion, tremors, hallucinations, and autonomic instability.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Autism spectrum disorder is primarily characterized by:',
 '[{"text":"Impaired social communication and repetitive, restricted behaviors","isCorrect":true},{"text":"Excessive sociability with strangers","isCorrect":false},{"text":"Only physical growth delay","isCorrect":false},{"text":"Loss of previously acquired memories","isCorrect":false}]'::jsonb,
 null, 'Autism spectrum disorder is characterized by persistent deficits in social communication and interaction, along with restricted, repetitive patterns of behavior or interests.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which class of drugs, when used for anxiety, carries the most notable risk of dependence with long-term use?',
 '[{"text":"SSRIs","isCorrect":false},{"text":"Benzodiazepines","isCorrect":true},{"text":"Beta-blockers","isCorrect":false},{"text":"Antipsychotics","isCorrect":false}]'::jsonb,
 null, 'Benzodiazepines, while effective for short-term anxiety relief, carry a significant risk of tolerance and dependence with prolonged use.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Atopic dermatitis (eczema) is often associated with a personal or family history of:',
 '[{"text":"Atopy (asthma, allergic rhinitis)","isCorrect":true},{"text":"Diabetes mellitus","isCorrect":false},{"text":"Tuberculosis","isCorrect":false},{"text":"Hypertension","isCorrect":false}]'::jsonb,
 null, 'Atopic dermatitis frequently occurs in individuals with a personal or family history of atopic conditions, such as asthma and allergic rhinitis.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Which skin cancer, strongly associated with chronic sun exposure, classically appears as a pearly nodule with visible blood vessels?',
 '[{"text":"Basal cell carcinoma","isCorrect":true},{"text":"Kaposi sarcoma","isCorrect":false},{"text":"Squamous cell carcinoma exclusively","isCorrect":false},{"text":"Dermatofibroma","isCorrect":false}]'::jsonb,
 null, 'Basal cell carcinoma, the most common skin cancer, classically presents as a pearly, translucent nodule with visible surface blood vessels (telangiectasia).'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Melanoma, an aggressive form of skin cancer, most commonly arises from:',
 '[{"text":"Melanocytes","isCorrect":true},{"text":"Keratinocytes","isCorrect":false},{"text":"Sweat gland cells","isCorrect":false},{"text":"Hair follicle cells","isCorrect":false}]'::jsonb,
 null, 'Melanoma arises from melanocytes, the pigment-producing cells of the skin, and is notable for its potential to metastasize.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Alopecia areata is characterized by:',
 '[{"text":"Uniform, generalized thinning of hair","isCorrect":false},{"text":"Patchy, autoimmune-mediated hair loss","isCorrect":true},{"text":"Excessive hair growth","isCorrect":false},{"text":"Hair loss only due to aging","isCorrect":false}]'::jsonb,
 null, 'Alopecia areata is an autoimmune condition causing sudden, patchy hair loss, typically in well-defined round or oval patches.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'In adults with a prior history of abdominal surgery, the most common cause of small bowel obstruction is:',
 '[{"text":"Adhesions","isCorrect":true},{"text":"Hernias","isCorrect":false},{"text":"Tumors","isCorrect":false},{"text":"Gallstones","isCorrect":false}]'::jsonb,
 null, 'Postoperative adhesions are the most common cause of small bowel obstruction in adults who have had prior abdominal or pelvic surgery.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'A positive Murphy''s sign, elicited during abdominal examination, is specific for:',
 '[{"text":"Acute appendicitis","isCorrect":false},{"text":"Acute cholecystitis","isCorrect":true},{"text":"Acute pancreatitis","isCorrect":false},{"text":"Peptic ulcer perforation","isCorrect":false}]'::jsonb,
 null, 'Murphy''s sign -- pain and inspiratory arrest on palpation of the right upper quadrant during deep inspiration -- is a classic finding in acute cholecystitis.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Which type of shock is characterized primarily by a low circulating blood volume?',
 '[{"text":"Cardiogenic shock","isCorrect":false},{"text":"Hypovolemic shock","isCorrect":true},{"text":"Septic shock","isCorrect":false},{"text":"Neurogenic shock","isCorrect":false}]'::jsonb,
 null, 'Hypovolemic shock results from a significant reduction in circulating blood volume, such as from severe hemorrhage or fluid loss.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common anatomical site of colorectal cancer is the:',
 '[{"text":"Cecum","isCorrect":false},{"text":"Rectosigmoid region","isCorrect":true},{"text":"Ascending colon exclusively","isCorrect":false},{"text":"Transverse colon exclusively","isCorrect":false}]'::jsonb,
 null, 'The rectosigmoid region (rectum and sigmoid colon) is the most common site for colorectal cancer to develop.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'A Pott''s fracture involves a fracture around which joint?',
 '[{"text":"The wrist","isCorrect":false},{"text":"The ankle","isCorrect":true},{"text":"The knee","isCorrect":false},{"text":"The shoulder","isCorrect":false}]'::jsonb,
 null, 'A Pott''s fracture is a fracture-dislocation involving the ankle joint, classically affecting the distal fibula (and often the tibia).'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'Osteomyelitis is best described as:',
 '[{"text":"Inflammation of a joint","isCorrect":false},{"text":"Infection of the bone","isCorrect":true},{"text":"Degeneration of cartilage","isCorrect":false},{"text":"A benign bone tumor","isCorrect":false}]'::jsonb,
 null, 'Osteomyelitis refers to an infection of the bone, most often caused by bacteria reaching the bone via the bloodstream, direct spread, or trauma.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common causative organism of osteomyelitis is:',
 '[{"text":"Staphylococcus aureus","isCorrect":true},{"text":"Escherichia coli","isCorrect":false},{"text":"Streptococcus pneumoniae","isCorrect":false},{"text":"Mycobacterium tuberculosis","isCorrect":false}]'::jsonb,
 null, 'Staphylococcus aureus is the most common causative organism of osteomyelitis across most age groups.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'Scoliosis is best described as:',
 '[{"text":"An abnormal lateral curvature of the spine","isCorrect":true},{"text":"A fracture of the vertebral column","isCorrect":false},{"text":"Inflammation of the spinal cord","isCorrect":false},{"text":"A tumor of the spine","isCorrect":false}]'::jsonb,
 null, 'Scoliosis refers to an abnormal sideways (lateral) curvature of the spine, which can be congenital, idiopathic, or secondary to other conditions.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The most common cause of infertility in women is:',
 '[{"text":"Ovulatory disorders (e.g. PCOS)","isCorrect":true},{"text":"Uterine malformation exclusively","isCorrect":false},{"text":"Cervical stenosis exclusively","isCorrect":false},{"text":"Vaginal infections exclusively","isCorrect":false}]'::jsonb,
 null, 'Ovulatory disorders, particularly polycystic ovary syndrome (PCOS), are among the most common causes of female infertility.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Polycystic ovary syndrome (PCOS) is classically associated with:',
 '[{"text":"Irregular periods, hyperandrogenism, and polycystic ovaries","isCorrect":true},{"text":"Only weight loss and regular periods","isCorrect":false},{"text":"Only elevated blood pressure","isCorrect":false},{"text":"Only excessive menstrual bleeding","isCorrect":false}]'::jsonb,
 null, 'PCOS is classically characterized by the triad of irregular menstrual cycles, signs of hyperandrogenism (like hirsutism/acne), and polycystic ovaries on ultrasound.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'In the APGAR score, the "activity" component specifically assesses:',
 '[{"text":"Muscle tone","isCorrect":true},{"text":"Skin color","isCorrect":false},{"text":"Heart rate","isCorrect":false},{"text":"Respiratory effort","isCorrect":false}]'::jsonb,
 null, 'The "Activity" component of the APGAR score assesses the newborn''s muscle tone.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Placenta previa is characterized by:',
 '[{"text":"Premature separation of a normally implanted placenta","isCorrect":false},{"text":"Abnormal implantation of the placenta over or near the cervical os","isCorrect":true},{"text":"Complete absence of the placenta","isCorrect":false},{"text":"Twin placentas fusing together","isCorrect":false}]'::jsonb,
 null, 'Placenta previa occurs when the placenta implants abnormally low in the uterus, covering or lying near the internal cervical os, which can cause painless vaginal bleeding.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Local anesthetics primarily act by blocking which type of ion channel?',
 '[{"text":"Voltage-gated potassium channels","isCorrect":false},{"text":"Voltage-gated sodium channels","isCorrect":true},{"text":"Calcium-activated chloride channels","isCorrect":false},{"text":"Ligand-gated channels only","isCorrect":false}]'::jsonb,
 null, 'Local anesthetics block voltage-gated sodium channels in nerve membranes, preventing the generation and conduction of action potentials.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The primary purpose of preoxygenation before endotracheal intubation is to:',
 '[{"text":"Sedate the patient more deeply","isCorrect":false},{"text":"Extend the safe apnea time by increasing oxygen reserve","isCorrect":true},{"text":"Reduce the risk of infection","isCorrect":false},{"text":"Paralyze the vocal cords","isCorrect":false}]'::jsonb,
 null, 'Preoxygenation increases the oxygen reserve in the lungs and blood, extending the safe period of apnea during intubation before desaturation occurs.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'easy', 'mcq',
 'A pulse oximeter is used to monitor which vital parameter?',
 '[{"text":"Blood pressure","isCorrect":false},{"text":"Oxygen saturation (SpO2)","isCorrect":true},{"text":"Body temperature","isCorrect":false},{"text":"Blood glucose","isCorrect":false}]'::jsonb,
 null, 'A pulse oximeter non-invasively measures the percentage of hemoglobin saturated with oxygen (SpO2) in the blood.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Epidural anesthesia involves injecting anesthetic agent into which space?',
 '[{"text":"The subarachnoid space","isCorrect":false},{"text":"The epidural space (outside the dura mater)","isCorrect":true},{"text":"Directly into the spinal cord","isCorrect":false},{"text":"The intramuscular space only","isCorrect":false}]'::jsonb,
 null, 'Epidural anesthesia involves injecting anesthetic into the epidural space, located outside the dura mater, distinguishing it from spinal (subarachnoid) anesthesia.');
