-- supabase/sql/exam_question_bank_viteee_set1.sql
--
-- First curated question-bank batch for 'VITEEE' (see exam_patterns_viteee.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Like MHT-CET/NEET/BITSAT (and unlike the JEE sets), VITEEE's real format is 100%
-- single-best-response MCQ (4 options, exactly one correct) -- no multi-correct, numerical, or
-- descriptive format in the actual exam. 16 chapters (4 Physics, 4 Chemistry, 4 Mathematics, 2
-- English, 2 Aptitude) each get 4 questions -- the English and Aptitude sections mirror BITSAT's
-- English Proficiency/Logical Reasoning sections but with fresh, distinct content here.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_viteee.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('VITEEE', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of pressure is the:',
 '[{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":true},{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'Pressure, defined as force per unit area, is measured in pascals (Pa), where 1 Pa = 1 N/m^2.'),
('VITEEE', 'Physics', 'Mechanics', 'easy', 'mcq',
 'A body dropped from a height, in the absence of air resistance, falls under:',
 '[{"text":"Uniform velocity","isCorrect":false},{"text":"Uniform acceleration","isCorrect":true},{"text":"Decreasing acceleration","isCorrect":false},{"text":"Zero acceleration","isCorrect":false}]'::jsonb,
 null, 'In free fall (ignoring air resistance), a body experiences a constant acceleration g due to gravity, so it undergoes uniformly accelerated motion.'),
('VITEEE', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The work-energy theorem states that the net work done on a body equals its:',
 '[{"text":"Change in potential energy","isCorrect":false},{"text":"Change in kinetic energy","isCorrect":true},{"text":"Total mechanical energy","isCorrect":false},{"text":"Change in momentum","isCorrect":false}]'::jsonb,
 null, 'The work-energy theorem states that the net work done on an object by all forces equals the change in its kinetic energy.'),
('VITEEE', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The dimensional formula of momentum is:',
 '[{"text":"[MLT^-1]","isCorrect":true},{"text":"[MLT^-2]","isCorrect":false},{"text":"[ML^2T^-2]","isCorrect":false},{"text":"[ML^2T^-1]","isCorrect":false}]'::jsonb,
 null, 'Momentum = mass x velocity, giving dimensions [M][LT^-1] = [MLT^-1].'),

-- Physics: Electrodynamics
('VITEEE', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'Ohm''s law relates voltage V, current I, and resistance R as:',
 '[{"text":"V = IR","isCorrect":true},{"text":"V = I/R","isCorrect":false},{"text":"V = I + R","isCorrect":false},{"text":"I = VR","isCorrect":false}]'::jsonb,
 null, 'Ohm''s law states that the voltage across a conductor is directly proportional to the current through it, with resistance as the constant of proportionality: V = IR.'),
('VITEEE', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The magnitude of the magnetic force on a charge q moving with velocity v at angle theta to a magnetic field B is given by:',
 '[{"text":"qvB*sin(theta)","isCorrect":true},{"text":"qvB*cos(theta)","isCorrect":false},{"text":"qvB","isCorrect":false},{"text":"qv/B","isCorrect":false}]'::jsonb,
 null, 'The magnitude of the Lorentz magnetic force is F = qvB*sin(theta), where theta is the angle between the velocity and magnetic field vectors.'),
('VITEEE', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'In a series LCR circuit at resonance, the impedance of the circuit is:',
 '[{"text":"Maximum, equal to (XL+XC)","isCorrect":false},{"text":"Minimum, equal to the resistance R","isCorrect":true},{"text":"Zero","isCorrect":false},{"text":"Infinite","isCorrect":false}]'::jsonb,
 null, 'At resonance, the inductive and capacitive reactances cancel (XL=XC), leaving only the resistance R, so the impedance is at its minimum possible value.'),
('VITEEE', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of magnetic flux density (magnetic field strength) is the:',
 '[{"text":"Weber","isCorrect":false},{"text":"Tesla","isCorrect":true},{"text":"Henry","isCorrect":false},{"text":"Farad","isCorrect":false}]'::jsonb,
 null, 'Magnetic flux density (B) is measured in tesla (T), while magnetic flux itself is measured in weber (Wb).'),

-- Physics: Optics and Wave Optics
('VITEEE', 'Physics', 'Optics and Wave Optics', 'medium', 'mcq',
 'In Young''s double slit experiment, constructive interference occurs when the path difference between the two waves is:',
 '[{"text":"An integral multiple of the wavelength","isCorrect":true},{"text":"An odd multiple of half the wavelength","isCorrect":false},{"text":"Always zero","isCorrect":false},{"text":"Equal to the slit separation","isCorrect":false}]'::jsonb,
 null, 'Constructive interference (bright fringes) occurs when the path difference equals n*lambda, an integral multiple of the wavelength, so the waves arrive in phase.'),
('VITEEE', 'Physics', 'Optics and Wave Optics', 'easy', 'mcq',
 'A converging (convex) lens used as a simple magnifying glass forms an image that is:',
 '[{"text":"Real, inverted, and magnified","isCorrect":false},{"text":"Virtual, erect, and magnified","isCorrect":true},{"text":"Real, erect, and diminished","isCorrect":false},{"text":"Virtual, inverted, and diminished","isCorrect":false}]'::jsonb,
 null, 'When the object is placed within the focal length of a convex lens, it produces a virtual, erect, magnified image -- the basis of a simple magnifying glass.'),
('VITEEE', 'Physics', 'Optics and Wave Optics', 'medium', 'mcq',
 'Polarization is a phenomenon that can be exhibited only by:',
 '[{"text":"Longitudinal waves","isCorrect":false},{"text":"Transverse waves","isCorrect":true},{"text":"Sound waves in air","isCorrect":false},{"text":"All types of waves equally","isCorrect":false}]'::jsonb,
 null, 'Polarization restricts the vibration of a wave to a single plane, which is possible only for transverse waves (like light), not longitudinal waves (like sound in air).'),
('VITEEE', 'Physics', 'Optics and Wave Optics', 'easy', 'mcq',
 'The power of a lens is measured in units of:',
 '[{"text":"Diopter","isCorrect":true},{"text":"Candela","isCorrect":false},{"text":"Lux","isCorrect":false},{"text":"Lumen","isCorrect":false}]'::jsonb,
 null, 'Lens power, defined as the reciprocal of focal length in meters, is measured in diopters (D).'),

-- Physics: Modern Physics and Semiconductor Devices
('VITEEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The stopping potential in the photoelectric effect depends on:',
 '[{"text":"The intensity of incident light only","isCorrect":false},{"text":"The frequency of incident light","isCorrect":true},{"text":"The area of the metal surface","isCorrect":false},{"text":"The distance of the light source","isCorrect":false}]'::jsonb,
 null, 'Stopping potential is determined by the maximum kinetic energy of photoelectrons, which depends on the frequency of incident light, not its intensity.'),
('VITEEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'A p-n junction diode conducts significantly when forward biased mainly because:',
 '[{"text":"The depletion region widens","isCorrect":false},{"text":"The depletion region narrows, lowering the potential barrier","isCorrect":true},{"text":"The diode''s temperature drops","isCorrect":false},{"text":"Majority carriers are repelled from the junction","isCorrect":false}]'::jsonb,
 null, 'Forward biasing reduces the width of the depletion region and lowers the potential barrier, allowing majority carriers to flow easily across the junction.'),
('VITEEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The mass defect observed in a nucleus, compared to the sum of masses of its individual nucleons, is converted into the nucleus''s:',
 '[{"text":"Kinetic energy","isCorrect":false},{"text":"Binding energy","isCorrect":true},{"text":"Electric charge","isCorrect":false},{"text":"Magnetic moment","isCorrect":false}]'::jsonb,
 null, 'The mass defect, via E=mc^2, corresponds to the binding energy that holds the nucleons together in the nucleus.'),
('VITEEE', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'In a common-emitter transistor configuration, the current gain is denoted by:',
 '[{"text":"Alpha","isCorrect":false},{"text":"Beta","isCorrect":true},{"text":"Gamma","isCorrect":false},{"text":"Delta","isCorrect":false}]'::jsonb,
 null, 'In common-emitter configuration, current gain (ratio of collector current to base current) is denoted by beta (also written hFE).'),

-- Chemistry: Physical Chemistry
('VITEEE', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'According to the first law of thermodynamics, the change in internal energy deltaU of a system is given by:',
 '[{"text":"deltaU = q + w","isCorrect":true},{"text":"deltaU = q * w","isCorrect":false},{"text":"deltaU = q/w","isCorrect":false},{"text":"deltaU = w - q","isCorrect":false}]'::jsonb,
 null, 'The first law of thermodynamics (IUPAC convention) states deltaU = q + w, where q is heat absorbed by the system and w is work done on the system.'),
('VITEEE', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The half-life of a first-order reaction is:',
 '[{"text":"Directly proportional to initial concentration","isCorrect":false},{"text":"Independent of initial concentration","isCorrect":true},{"text":"Inversely proportional to initial concentration","isCorrect":false},{"text":"Proportional to the square of initial concentration","isCorrect":false}]'::jsonb,
 null, 'For a first-order reaction, t(1/2) = 0.693/k, which does not depend on the initial concentration of the reactant.'),
('VITEEE', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'An ideal solution is best described as one that:',
 '[{"text":"Obeys Raoult''s law at all concentrations","isCorrect":true},{"text":"Shows large positive deviation from Raoult''s law","isCorrect":false},{"text":"Cannot be formed from two liquids","isCorrect":false},{"text":"Has zero vapor pressure","isCorrect":false}]'::jsonb,
 null, 'An ideal solution obeys Raoult''s law across the entire concentration range, with zero enthalpy and volume change on mixing.'),
('VITEEE', 'Chemistry', 'Physical Chemistry', 'hard', 'mcq',
 'The unit of the equilibrium constant Kp for a gaseous reaction depends on:',
 '[{"text":"The temperature of the reaction only","isCorrect":false},{"text":"The change in the number of moles of gas (delta n) in the reaction","isCorrect":true},{"text":"The total pressure of the system","isCorrect":false},{"text":"The catalyst used","isCorrect":false}]'::jsonb,
 null, 'Kp = Kc(RT)^(delta n), so its units depend on delta n, the difference between moles of gaseous products and reactants; if delta n = 0, Kp is dimensionless.'),

-- Chemistry: Organic Chemistry
('VITEEE', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The hybridization of carbon atoms in ethyne (acetylene, HC≡CH) is:',
 '[{"text":"sp","isCorrect":true},{"text":"sp2","isCorrect":false},{"text":"sp3","isCorrect":false},{"text":"sp3d","isCorrect":false}]'::jsonb,
 null, 'Each carbon in ethyne forms a triple bond, involving one sigma and two pi bonds, corresponding to sp hybridization with a linear geometry.'),
('VITEEE', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The IUPAC name of the compound commonly known as formaldehyde is:',
 '[{"text":"Methanal","isCorrect":true},{"text":"Ethanal","isCorrect":false},{"text":"Methanol","isCorrect":false},{"text":"Propanal","isCorrect":false}]'::jsonb,
 null, 'Formaldehyde, HCHO, is systematically named methanal under IUPAC nomenclature.'),
('VITEEE', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Grignard reagents are generally represented by the formula:',
 '[{"text":"RMgX","isCorrect":true},{"text":"RNaX","isCorrect":false},{"text":"RLiX","isCorrect":false},{"text":"RCuX","isCorrect":false}]'::jsonb,
 null, 'A Grignard reagent consists of an organic group R bonded to magnesium and a halogen X, represented as RMgX.'),
('VITEEE', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The addition of HCN to an aldehyde or ketone to form a cyanohydrin is an example of a:',
 '[{"text":"Nucleophilic addition reaction","isCorrect":true},{"text":"Electrophilic addition reaction","isCorrect":false},{"text":"Free radical substitution reaction","isCorrect":false},{"text":"Elimination reaction","isCorrect":false}]'::jsonb,
 null, 'The cyanide ion (CN-) acts as a nucleophile, attacking the electrophilic carbonyl carbon, making this a nucleophilic addition reaction.'),

-- Chemistry: Inorganic Chemistry
('VITEEE', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Transition elements are generally associated with which block of the periodic table?',
 '[{"text":"s-block","isCorrect":false},{"text":"p-block","isCorrect":false},{"text":"d-block","isCorrect":true},{"text":"f-block","isCorrect":false}]'::jsonb,
 null, 'Transition elements are defined as those with a partially filled d-subshell in the element or its common ions, placing them in the d-block of the periodic table.'),
('VITEEE', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Bleaching powder is commonly known chemically as:',
 '[{"text":"Calcium oxychloride","isCorrect":true},{"text":"Calcium carbonate","isCorrect":false},{"text":"Sodium hypochlorite","isCorrect":false},{"text":"Calcium sulfate","isCorrect":false}]'::jsonb,
 null, 'Bleaching powder is calcium oxychloride, Ca(OCl)Cl, produced by passing chlorine gas over slaked lime.'),
('VITEEE', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which noble gas is commonly used to fill balloons due to its low density and non-flammability?',
 '[{"text":"Neon","isCorrect":false},{"text":"Helium","isCorrect":true},{"text":"Argon","isCorrect":false},{"text":"Xenon","isCorrect":false}]'::jsonb,
 null, 'Helium, being lighter than air and chemically inert (non-flammable, unlike hydrogen), is the preferred gas for filling balloons.'),
('VITEEE', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The oxidation state of nitrogen in HNO3 is:',
 '[{"text":"+3","isCorrect":false},{"text":"+5","isCorrect":true},{"text":"+4","isCorrect":false},{"text":"-3","isCorrect":false}]'::jsonb,
 null, 'In HNO3, H is +1 and each O is -2; balancing the neutral molecule''s charge gives nitrogen an oxidation state of +5.'),

-- Chemistry: Analytical Chemistry and Environmental Chemistry
('VITEEE', 'Chemistry', 'Analytical Chemistry and Environmental Chemistry', 'easy', 'mcq',
 'Which technique is commonly used to separate a mixture of colored pigments?',
 '[{"text":"Chromatography","isCorrect":true},{"text":"Titration","isCorrect":false},{"text":"Neutralization","isCorrect":false},{"text":"Precipitation only","isCorrect":false}]'::jsonb,
 null, 'Chromatography separates mixture components (like pigments) based on their differing movement through a stationary phase, driven by differences in adsorption or solubility.'),
('VITEEE', 'Chemistry', 'Analytical Chemistry and Environmental Chemistry', 'easy', 'mcq',
 'Dissolved oxygen in water is essential mainly for:',
 '[{"text":"The survival of aerobic aquatic organisms","isCorrect":true},{"text":"Increasing water''s boiling point","isCorrect":false},{"text":"Making water acidic","isCorrect":false},{"text":"Preventing water from freezing","isCorrect":false}]'::jsonb,
 null, 'Aerobic aquatic organisms, such as fish, depend on adequate dissolved oxygen in water for respiration and survival.'),
('VITEEE', 'Chemistry', 'Analytical Chemistry and Environmental Chemistry', 'medium', 'mcq',
 'Which of the following is classified as a primary air pollutant (emitted directly)?',
 '[{"text":"Carbon monoxide","isCorrect":true},{"text":"Ozone (ground-level)","isCorrect":false},{"text":"Peroxyacetyl nitrate (PAN)","isCorrect":false},{"text":"Smog","isCorrect":false}]'::jsonb,
 null, 'Carbon monoxide is emitted directly from sources like vehicle exhaust, making it a primary pollutant, unlike ground-level ozone or PAN, which form secondarily through atmospheric reactions.'),
('VITEEE', 'Chemistry', 'Analytical Chemistry and Environmental Chemistry', 'medium', 'mcq',
 'In paper chromatography, the Rf value is defined as the ratio of the distance traveled by the:',
 '[{"text":"Solvent to the distance traveled by the solute","isCorrect":false},{"text":"Solute to the distance traveled by the solvent","isCorrect":true},{"text":"Paper to the container height","isCorrect":false},{"text":"Solute to the width of the paper","isCorrect":false}]'::jsonb,
 null, 'The retardation factor Rf is defined as (distance traveled by solute) / (distance traveled by solvent front), a characteristic value used to identify substances.'),

-- Mathematics: Algebra and Matrices
('VITEEE', 'Mathematics', 'Algebra and Matrices', 'easy', 'mcq',
 'The rank of a null (zero) matrix is:',
 '[{"text":"Equal to its number of rows","isCorrect":false},{"text":"0","isCorrect":true},{"text":"1","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'A null matrix has no linearly independent rows or columns, so its rank is defined to be 0.'),
('VITEEE', 'Mathematics', 'Algebra and Matrices', 'medium', 'mcq',
 'If a square matrix A is orthogonal, then A^T * A equals:',
 '[{"text":"The zero matrix","isCorrect":false},{"text":"The identity matrix","isCorrect":true},{"text":"A itself","isCorrect":false},{"text":"2A","isCorrect":false}]'::jsonb,
 null, 'A matrix A is orthogonal precisely when its transpose equals its inverse, so A^T * A = I, the identity matrix.'),
('VITEEE', 'Mathematics', 'Algebra and Matrices', 'easy', 'mcq',
 'The number of ways to arrange n distinct objects in a row is:',
 '[{"text":"n","isCorrect":false},{"text":"n!","isCorrect":true},{"text":"n^2","isCorrect":false},{"text":"2^n","isCorrect":false}]'::jsonb,
 null, 'The number of permutations of n distinct objects taken all at once is n factorial (n!).'),
('VITEEE', 'Mathematics', 'Algebra and Matrices', 'easy', 'mcq',
 'For the quadratic equation ax^2 + bx + c = 0, the sum of the roots is:',
 '[{"text":"-b/a","isCorrect":true},{"text":"c/a","isCorrect":false},{"text":"b/a","isCorrect":false},{"text":"-c/a","isCorrect":false}]'::jsonb,
 null, 'For ax^2+bx+c=0, the sum of the roots equals -b/a, by Vieta''s formulas.'),

-- Mathematics: Calculus
('VITEEE', 'Mathematics', 'Calculus', 'easy', 'mcq',
 'The derivative of cos(x) with respect to x is:',
 '[{"text":"sin(x)","isCorrect":false},{"text":"-sin(x)","isCorrect":true},{"text":"-cos(x)","isCorrect":false},{"text":"tan(x)","isCorrect":false}]'::jsonb,
 null, 'By standard differentiation rules, d/dx[cos(x)] = -sin(x).'),
('VITEEE', 'Mathematics', 'Calculus', 'medium', 'mcq',
 'A function has a point of inflection at x=a when:',
 '[{"text":"f''(a) = 0 only","isCorrect":false},{"text":"f''''(x) changes sign at x=a","isCorrect":true},{"text":"f(a) = 0","isCorrect":false},{"text":"f is discontinuous at x=a","isCorrect":false}]'::jsonb,
 null, 'A point of inflection occurs where the concavity of the function changes, identified by the second derivative changing sign at that point.'),
('VITEEE', 'Mathematics', 'Calculus', 'medium', 'mcq',
 'The integral of 1/x^2 dx is:',
 '[{"text":"ln|x| + C","isCorrect":false},{"text":"-1/x + C","isCorrect":true},{"text":"1/x + C","isCorrect":false},{"text":"x^-3/(-3) + C","isCorrect":false}]'::jsonb,
 null, 'Writing 1/x^2 as x^-2 and using the power rule for integration gives -x^-1 + C, i.e. -1/x + C.'),
('VITEEE', 'Mathematics', 'Calculus', 'medium', 'mcq',
 'The value of the limit of (sin x)/x as x approaches 0 is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"Infinity","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'This is a standard limit in calculus: lim(x->0) sin(x)/x = 1.'),

-- Mathematics: Coordinate Geometry and Vectors
('VITEEE', 'Mathematics', 'Coordinate Geometry and Vectors', 'easy', 'mcq',
 'The equation of a straight line in intercept form, with x-intercept a and y-intercept b, is:',
 '[{"text":"x/a + y/b = 1","isCorrect":true},{"text":"ax + by = 1","isCorrect":false},{"text":"x*a + y*b = 1","isCorrect":false},{"text":"a/x + b/y = 1","isCorrect":false}]'::jsonb,
 null, 'The intercept form of a straight line''s equation is x/a + y/b = 1, where a and b are the x- and y-intercepts respectively.'),
('VITEEE', 'Mathematics', 'Coordinate Geometry and Vectors', 'medium', 'mcq',
 'The angle theta between two vectors a and b can be found using:',
 '[{"text":"cos(theta) = (a.b)/(|a||b|)","isCorrect":true},{"text":"cos(theta) = |a| + |b|","isCorrect":false},{"text":"sin(theta) = a.b","isCorrect":false},{"text":"tan(theta) = |a|*|b|","isCorrect":false}]'::jsonb,
 null, 'The dot product formula a.b = |a||b|cos(theta) can be rearranged to find the angle between two vectors: cos(theta) = (a.b)/(|a||b|).'),
('VITEEE', 'Mathematics', 'Coordinate Geometry and Vectors', 'medium', 'mcq',
 'The perpendicular distance of the point (x1,y1) from the line ax + by + c = 0 is given by:',
 '[{"text":"|ax1+by1+c| / sqrt(a^2+b^2)","isCorrect":true},{"text":"(ax1+by1+c) / (a+b)","isCorrect":false},{"text":"|ax1+by1+c| / (a^2+b^2)","isCorrect":false},{"text":"ax1+by1+c","isCorrect":false}]'::jsonb,
 null, 'The perpendicular distance formula gives d = |ax1+by1+c| / sqrt(a^2+b^2) for a point (x1,y1) and a line ax+by+c=0.'),
('VITEEE', 'Mathematics', 'Coordinate Geometry and Vectors', 'medium', 'mcq',
 'Three vectors are coplanar if their scalar triple product is:',
 '[{"text":"Equal to 1","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Negative","isCorrect":false},{"text":"Equal to the sum of their magnitudes","isCorrect":false}]'::jsonb,
 null, 'The scalar triple product of three vectors gives the volume of the parallelepiped they form; if this volume is zero, the vectors lie in the same plane (are coplanar).'),

-- Mathematics: Trigonometry and Probability
('VITEEE', 'Mathematics', 'Trigonometry and Probability', 'easy', 'mcq',
 'The value of sin(90 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"1/2","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'sin(90 degrees) reaches its maximum value of 1, a standard trigonometric value.'),
('VITEEE', 'Mathematics', 'Trigonometry and Probability', 'medium', 'mcq',
 'If two events A and B are mutually exclusive, then P(A union B) equals:',
 '[{"text":"P(A) * P(B)","isCorrect":false},{"text":"P(A) + P(B)","isCorrect":true},{"text":"P(A) - P(B)","isCorrect":false},{"text":"P(A intersect B)","isCorrect":false}]'::jsonb,
 null, 'For mutually exclusive events, P(A intersect B) = 0, so the general addition rule P(A union B) = P(A)+P(B)-P(A intersect B) simplifies to just P(A)+P(B).'),
('VITEEE', 'Mathematics', 'Trigonometry and Probability', 'easy', 'mcq',
 'The value of cos(0 degrees) is:',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"-1","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'cos(0 degrees) equals 1, a standard trigonometric value.'),
('VITEEE', 'Mathematics', 'Trigonometry and Probability', 'easy', 'mcq',
 'The probability of an impossible event is:',
 '[{"text":"1","isCorrect":false},{"text":"0","isCorrect":true},{"text":"0.5","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'By definition, an event that can never occur has a probability of exactly 0.'),

-- English: Grammar and Sentence Correction
('VITEEE', 'English', 'Grammar and Sentence Correction', 'medium', 'mcq',
 'Which sentence is grammatically correct?',
 '[{"text":"Each of the students have submitted their assignment.","isCorrect":false},{"text":"Each of the students has submitted his or her assignment.","isCorrect":true},{"text":"Each of the students has submitted their assignments.","isCorrect":false},{"text":"Each of the students have submitted his assignment.","isCorrect":false}]'::jsonb,
 null, '"Each" is a singular subject, requiring the singular verb "has" and singular possessive "his or her", not the plural "have"/"their".'),
('VITEEE', 'English', 'Grammar and Sentence Correction', 'hard', 'mcq',
 'Choose the correct word to complete: "He is one of the best players who ___ ever played this game."',
 '[{"text":"has","isCorrect":false},{"text":"have","isCorrect":true},{"text":"having","isCorrect":false},{"text":"had","isCorrect":false}]'::jsonb,
 null, '"Who" here refers back to "players" (plural), from "one of the best players who...", so the verb must agree in the plural: "have ever played".'),
('VITEEE', 'English', 'Grammar and Sentence Correction', 'medium', 'mcq',
 'Choose the correct article to complete: "___ European Union has 27 member countries."',
 '[{"text":"A","isCorrect":false},{"text":"An","isCorrect":false},{"text":"The","isCorrect":true},{"text":"No article is needed","isCorrect":false}]'::jsonb,
 null, '"European Union" is a specific, unique organization, requiring the definite article "The" (and note "European" begins with a consonant sound, ruling out "An").'),
('VITEEE', 'English', 'Grammar and Sentence Correction', 'medium', 'mcq',
 'Which sentence uses the semicolon correctly?',
 '[{"text":"I have a big exam tomorrow; I can''t go out tonight.","isCorrect":true},{"text":"I have a big exam tomorrow; because I can''t go out tonight.","isCorrect":false},{"text":"I have a big exam tomorrow, I can''t go out tonight;","isCorrect":false},{"text":"I have a big; exam tomorrow I can''t go out tonight.","isCorrect":false}]'::jsonb,
 null, 'A semicolon correctly joins two closely related independent clauses without a conjunction, as in "I have a big exam tomorrow; I can''t go out tonight."'),

-- English: Vocabulary and Comprehension
('VITEEE', 'English', 'Vocabulary and Comprehension', 'medium', 'mcq',
 'Choose the word closest in meaning to "Meticulous".',
 '[{"text":"Careless","isCorrect":false},{"text":"Painstaking","isCorrect":true},{"text":"Reckless","isCorrect":false},{"text":"Indifferent","isCorrect":false}]'::jsonb,
 null, '"Meticulous" means showing great attention to detail; "painstaking" is its closest synonym among the options.'),
('VITEEE', 'English', 'Vocabulary and Comprehension', 'medium', 'mcq',
 'Choose the antonym of "Verbose".',
 '[{"text":"Wordy","isCorrect":false},{"text":"Concise","isCorrect":true},{"text":"Lengthy","isCorrect":false},{"text":"Talkative","isCorrect":false}]'::jsonb,
 null, '"Verbose" means using more words than needed; its antonym is "concise", meaning brief and to the point.'),
('VITEEE', 'English', 'Vocabulary and Comprehension', 'easy', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Occurence","isCorrect":false},{"text":"Occurrence","isCorrect":true},{"text":"Occurrance","isCorrect":false},{"text":"Ocurrence","isCorrect":false}]'::jsonb,
 null, '"Occurrence" is the correct spelling, with a double "r" and double "c".'),
('VITEEE', 'English', 'Vocabulary and Comprehension', 'easy', 'mcq',
 'Choose the word that best completes the sentence: "The company''s profits ___ significantly last quarter."',
 '[{"text":"Increased","isCorrect":true},{"text":"Increasing","isCorrect":false},{"text":"Increase","isCorrect":false},{"text":"Increases","isCorrect":false}]'::jsonb,
 null, 'The sentence requires the simple past tense to match "last quarter", making "increased" the grammatically and contextually correct choice.'),

-- Aptitude: Numerical Aptitude
('VITEEE', 'Aptitude', 'Numerical Aptitude', 'easy', 'mcq',
 'The cost price of an item is Rs. 80, and it is sold for Rs. 100. The profit percentage is:',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"15%","isCorrect":false},{"text":"30%","isCorrect":false}]'::jsonb,
 null, 'Profit = 100-80 = 20; Profit% = (20/80)*100 = 25%.'),
('VITEEE', 'Aptitude', 'Numerical Aptitude', 'easy', 'mcq',
 'The average of the first 10 natural numbers (1 to 10) is:',
 '[{"text":"5","isCorrect":false},{"text":"5.5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'Sum of first 10 natural numbers = 55; average = 55/10 = 5.5.'),
('VITEEE', 'Aptitude', 'Numerical Aptitude', 'medium', 'mcq',
 'A sum of money doubles itself in 5 years at simple interest. The annual rate of interest is:',
 '[{"text":"10%","isCorrect":false},{"text":"20%","isCorrect":true},{"text":"25%","isCorrect":false},{"text":"15%","isCorrect":false}]'::jsonb,
 null, 'If the sum doubles, simple interest earned equals the principal itself over 5 years; using SI = P*R*T/100 with SI=P and T=5 gives R = 100/5 = 20%.'),
('VITEEE', 'Aptitude', 'Numerical Aptitude', 'easy', 'mcq',
 'If 20% of a number is 50, the number is:',
 '[{"text":"100","isCorrect":false},{"text":"200","isCorrect":false},{"text":"250","isCorrect":true},{"text":"300","isCorrect":false}]'::jsonb,
 null, 'If 0.20*x=50, then x=50/0.20=250.'),

-- Aptitude: Reasoning and Data Interpretation
('VITEEE', 'Aptitude', 'Reasoning and Data Interpretation', 'easy', 'mcq',
 'Find the odd one out: Triangle, Square, Circle, Fast.',
 '[{"text":"Triangle","isCorrect":false},{"text":"Square","isCorrect":false},{"text":"Circle","isCorrect":false},{"text":"Fast","isCorrect":true}]'::jsonb,
 null, 'Triangle, Square, and Circle are all geometric shapes, while "Fast" is an adjective unrelated to shape, making it the odd one out.'),
('VITEEE', 'Aptitude', 'Reasoning and Data Interpretation', 'easy', 'mcq',
 'Find the next number in the series: 3, 6, 12, 24, ?',
 '[{"text":"30","isCorrect":false},{"text":"36","isCorrect":false},{"text":"48","isCorrect":true},{"text":"42","isCorrect":false}]'::jsonb,
 null, 'Each term is double the previous term, so after 24 the next term is 24*2=48.'),
('VITEEE', 'Aptitude', 'Reasoning and Data Interpretation', 'medium', 'mcq',
 'If A is the brother of B, and B is the sister of C, then A is C''s:',
 '[{"text":"Brother","isCorrect":true},{"text":"Sister","isCorrect":false},{"text":"Father","isCorrect":false},{"text":"Cousin","isCorrect":false}]'::jsonb,
 null, 'Since A is male (brother of B) and is related to C through sibling B, A is C''s brother.'),
('VITEEE', 'Aptitude', 'Reasoning and Data Interpretation', 'hard', 'mcq',
 'A clock shows 3:15. What is the angle between the hour hand and the minute hand at that time?',
 '[{"text":"0 degrees","isCorrect":false},{"text":"7.5 degrees","isCorrect":true},{"text":"15 degrees","isCorrect":false},{"text":"22.5 degrees","isCorrect":false}]'::jsonb,
 null, 'At 3:15, the minute hand points at the 3 (90 degrees from 12), while the hour hand has moved a quarter of the way from 3 to 4, i.e. 90 + (15/60)*30 = 97.5 degrees; the difference is 97.5-90 = 7.5 degrees.');
