-- supabase/sql/exam_question_bank_rrb_ntpc_set1.sql
--
-- First curated question-bank batch for 'RRB NTPC' (see exam_patterns_rrb_ntpc.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Non-Verbal Reasoning again uses text-describable puzzles in place of
-- figure-based questions, which need images this schema can't provide. General Awareness includes
-- a dedicated Railways General Knowledge chapter, matching the real exam's railway-specific GK
-- questions. 16 chapters (5 Mathematics + 5 General Intelligence and Reasoning + 6 General
-- Awareness) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_rrb_ntpc.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Mathematics: Number System and Simplification
('RRB NTPC', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 18 + 12 / 4 - 3',
 '[{"text":"18","isCorrect":true},{"text":"21","isCorrect":false},{"text":"6","isCorrect":false},{"text":"24","isCorrect":false}]'::jsonb,
 null, 'Following order of operations: 12/4 = 3, then 18 + 3 - 3 = 18.'),
('RRB NTPC', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following is a composite number?',
 '[{"text":"7","isCorrect":false},{"text":"11","isCorrect":false},{"text":"15","isCorrect":true},{"text":"13","isCorrect":false}]'::jsonb,
 null, '15 has factors other than 1 and itself (3 and 5), making it composite, while 7, 11 and 13 are prime.'),
('RRB NTPC', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the value of (0.5)^2 + (0.3)^2.',
 '[{"text":"0.25","isCorrect":false},{"text":"0.34","isCorrect":true},{"text":"0.58","isCorrect":false},{"text":"0.09","isCorrect":false}]'::jsonb,
 null, '(0.5)^2 = 0.25 and (0.3)^2 = 0.09, so their sum is 0.34.'),
('RRB NTPC', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'What is the smallest 4-digit number divisible by 9?',
 '[{"text":"1000","isCorrect":false},{"text":"1008","isCorrect":true},{"text":"1002","isCorrect":false},{"text":"999","isCorrect":false}]'::jsonb,
 null, '1000/9 is not a whole number; the next multiple of 9 after 1000 is 1008 (9 x 112).'),

-- Mathematics: Percentage and Ratio
('RRB NTPC', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 '40% of 250 is:',
 '[{"text":"100","isCorrect":true},{"text":"50","isCorrect":false},{"text":"80","isCorrect":false},{"text":"120","isCorrect":false}]'::jsonb,
 null, '40% of 250 = (40/100) x 250 = 100.'),
('RRB NTPC', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 'Express the ratio 3:5 as a percentage.',
 '[{"text":"35%","isCorrect":false},{"text":"60%","isCorrect":true},{"text":"53%","isCorrect":false},{"text":"65%","isCorrect":false}]'::jsonb,
 null, '3:5 as a fraction is 3/5, which equals 60%.'),
('RRB NTPC', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'The ratio of two numbers is 5:7 and their sum is 96. Find the larger number.',
 '[{"text":"40","isCorrect":false},{"text":"56","isCorrect":true},{"text":"48","isCorrect":false},{"text":"60","isCorrect":false}]'::jsonb,
 null, 'Total parts = 5+7 = 12. Each part = 96/12 = 8. The larger number = 7 x 8 = 56.'),
('RRB NTPC', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'A number increased by 25% becomes 100. Find the original number.',
 '[{"text":"75","isCorrect":false},{"text":"80","isCorrect":true},{"text":"70","isCorrect":false},{"text":"90","isCorrect":false}]'::jsonb,
 null, 'If x + 0.25x = 100, then 1.25x = 100, giving x = 80.'),

-- Mathematics: Profit Loss and Simple/Compound Interest
('RRB NTPC', 'Mathematics', 'Profit Loss and Simple/Compound Interest', 'easy', 'mcq',
 'A man buys an item for Rs. 200 and sells it for Rs. 250. Find his profit percentage.',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"30%","isCorrect":false},{"text":"15%","isCorrect":false}]'::jsonb,
 null, 'Profit = 250 - 200 = 50. Profit percentage = (50/200) x 100 = 25%.'),
('RRB NTPC', 'Mathematics', 'Profit Loss and Simple/Compound Interest', 'easy', 'mcq',
 'The cost price of an item is Rs. 500 and the loss incurred is Rs. 50. Find the loss percentage.',
 '[{"text":"5%","isCorrect":false},{"text":"10%","isCorrect":true},{"text":"15%","isCorrect":false},{"text":"20%","isCorrect":false}]'::jsonb,
 null, 'Loss percentage = (50/500) x 100 = 10%.'),
('RRB NTPC', 'Mathematics', 'Profit Loss and Simple/Compound Interest', 'medium', 'mcq',
 'Find the compound interest on Rs. 1000 at 10% per annum for 2 years.',
 '[{"text":"Rs. 100","isCorrect":false},{"text":"Rs. 200","isCorrect":false},{"text":"Rs. 210","isCorrect":true},{"text":"Rs. 220","isCorrect":false}]'::jsonb,
 null, 'Amount = 1000 x (1.1)^2 = 1210. Compound Interest = 1210 - 1000 = Rs. 210.'),
('RRB NTPC', 'Mathematics', 'Profit Loss and Simple/Compound Interest', 'medium', 'mcq',
 'Find the simple interest on Rs. 5000 at 8% per annum for 3 years.',
 '[{"text":"Rs. 1000","isCorrect":false},{"text":"Rs. 1200","isCorrect":true},{"text":"Rs. 1500","isCorrect":false},{"text":"Rs. 800","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = (Principal x Rate x Time) / 100 = (5000 x 8 x 3) / 100 = Rs. 1200.'),

-- Mathematics: Time Speed Distance and Time and Work
('RRB NTPC', 'Mathematics', 'Time Speed Distance and Time and Work', 'easy', 'mcq',
 'A car travels 180 km in 3 hours. Find its speed.',
 '[{"text":"50 km/h","isCorrect":false},{"text":"60 km/h","isCorrect":true},{"text":"45 km/h","isCorrect":false},{"text":"70 km/h","isCorrect":false}]'::jsonb,
 null, 'Speed = Distance / Time = 180 / 3 = 60 km/h.'),
('RRB NTPC', 'Mathematics', 'Time Speed Distance and Time and Work', 'easy', 'mcq',
 'A can complete a work in 10 days. What fraction of the work does he complete in 1 day?',
 '[{"text":"1/5","isCorrect":false},{"text":"1/10","isCorrect":true},{"text":"1/15","isCorrect":false},{"text":"1/20","isCorrect":false}]'::jsonb,
 null, 'If A completes the work in 10 days, he completes 1/10 of the work per day.'),
('RRB NTPC', 'Mathematics', 'Time Speed Distance and Time and Work', 'medium', 'mcq',
 'A train 100 m long crosses a pole in 10 seconds. Find its speed in m/s.',
 '[{"text":"5 m/s","isCorrect":false},{"text":"10 m/s","isCorrect":true},{"text":"15 m/s","isCorrect":false},{"text":"20 m/s","isCorrect":false}]'::jsonb,
 null, 'Speed = Distance / Time = 100 / 10 = 10 m/s.'),
('RRB NTPC', 'Mathematics', 'Time Speed Distance and Time and Work', 'medium', 'mcq',
 'A and B together can complete a work in 6 days. A alone can do it in 10 days. In how many days can B alone complete it?',
 '[{"text":"12 days","isCorrect":false},{"text":"15 days","isCorrect":true},{"text":"18 days","isCorrect":false},{"text":"20 days","isCorrect":false}]'::jsonb,
 null, 'B''s one-day work = 1/6 - 1/10 = 1/15, so B alone takes 15 days.'),

-- Mathematics: Mensuration and Geometry
('RRB NTPC', 'Mathematics', 'Mensuration and Geometry', 'easy', 'mcq',
 'Find the area of a triangle with base 10 cm and height 6 cm.',
 '[{"text":"60 cm^2","isCorrect":false},{"text":"30 cm^2","isCorrect":true},{"text":"16 cm^2","isCorrect":false},{"text":"40 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a triangle = (1/2) x base x height = (1/2) x 10 x 6 = 30 cm^2.'),
('RRB NTPC', 'Mathematics', 'Mensuration and Geometry', 'easy', 'mcq',
 'How many sides does a hexagon have?',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":true},{"text":"7","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A hexagon is a polygon with 6 sides.'),
('RRB NTPC', 'Mathematics', 'Mensuration and Geometry', 'medium', 'mcq',
 'Find the volume of a cuboid with dimensions 4 cm x 3 cm x 2 cm.',
 '[{"text":"9 cm^3","isCorrect":false},{"text":"24 cm^3","isCorrect":true},{"text":"18 cm^3","isCorrect":false},{"text":"12 cm^3","isCorrect":false}]'::jsonb,
 null, 'Volume of a cuboid = length x breadth x height = 4 x 3 x 2 = 24 cm^3.'),
('RRB NTPC', 'Mathematics', 'Mensuration and Geometry', 'medium', 'mcq',
 'Find the area of a circle with radius 14 cm (use pi = 22/7).',
 '[{"text":"308 cm^2","isCorrect":false},{"text":"616 cm^2","isCorrect":true},{"text":"154 cm^2","isCorrect":false},{"text":"440 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area = pi x r^2 = (22/7) x 14 x 14 = 616 cm^2.'),

-- General Intelligence and Reasoning: Analogies and Classification
('RRB NTPC', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Teacher is to School as Doctor is to:',
 '[{"text":"Clinic","isCorrect":true},{"text":"Book","isCorrect":false},{"text":"Medicine","isCorrect":false},{"text":"Patient","isCorrect":false}]'::jsonb,
 null, 'A teacher works in a school, just as a doctor works in a clinic.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Cow","isCorrect":false},{"text":"Goat","isCorrect":false},{"text":"Sheep","isCorrect":false},{"text":"Tiger","isCorrect":true}]'::jsonb,
 null, 'Cow, Goat and Sheep are domestic animals, while a Tiger is a wild animal.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Water is to Thirst as Food is to:',
 '[{"text":"Hunger","isCorrect":true},{"text":"Taste","isCorrect":false},{"text":"Cook","isCorrect":false},{"text":"Plate","isCorrect":false}]'::jsonb,
 null, 'Water satisfies thirst, just as food satisfies hunger.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Delhi","isCorrect":false},{"text":"Mumbai","isCorrect":false},{"text":"Chennai","isCorrect":false},{"text":"Ganga","isCorrect":true}]'::jsonb,
 null, 'Delhi, Mumbai and Chennai are cities, while Ganga is a river.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('RRB NTPC', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 7, 14, 21, 28, ?',
 '[{"text":"32","isCorrect":false},{"text":"35","isCorrect":true},{"text":"36","isCorrect":false},{"text":"42","isCorrect":false}]'::jsonb,
 null, 'The series increases by 7 each time, so the next number is 28 + 7 = 35.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'In a certain code, CAT is written as DBU. How is DOG written in that code?',
 '[{"text":"EPH","isCorrect":true},{"text":"EPI","isCorrect":false},{"text":"FPH","isCorrect":false},{"text":"EQH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: D->E, O->P, G->H, giving EPH.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 3, 7, 15, 31, ?',
 '[{"text":"60","isCorrect":false},{"text":"62","isCorrect":false},{"text":"63","isCorrect":true},{"text":"64","isCorrect":false}]'::jsonb,
 null, 'Each term is double the previous term plus 1, so the next term is 31 x 2 + 1 = 63.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If TRAIN is coded as USBJO, how is METRO coded in the same language?',
 '[{"text":"NFUSP","isCorrect":true},{"text":"NFUSO","isCorrect":false},{"text":"NFVSP","isCorrect":false},{"text":"MFUSP","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so METRO becomes NFUSP.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('RRB NTPC', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many faces does a triangular prism have?',
 '[{"text":"3","isCorrect":false},{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'A triangular prism has 5 faces: 2 triangular faces and 3 rectangular faces.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'What is the angle between the hour and minute hands of a clock at 4:00?',
 '[{"text":"90 degrees","isCorrect":false},{"text":"120 degrees","isCorrect":true},{"text":"60 degrees","isCorrect":false},{"text":"100 degrees","isCorrect":false}]'::jsonb,
 null, 'Each hour mark represents 30 degrees. At 4:00, the hour hand is at the 4, giving an angle of 4 x 30 = 120 degrees from the 12.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'How many total squares (of all sizes) are there on a standard 8x8 chessboard?',
 '[{"text":"64","isCorrect":false},{"text":"100","isCorrect":false},{"text":"204","isCorrect":true},{"text":"144","isCorrect":false}]'::jsonb,
 null, 'Counting squares of every size (1x1 through 8x8) on an 8x8 grid gives a total of 204 squares.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'In a row of people, A is standing 15th from the left and 8th from the right. How many people are in the row?',
 '[{"text":"22","isCorrect":true},{"text":"23","isCorrect":false},{"text":"21","isCorrect":false},{"text":"24","isCorrect":false}]'::jsonb,
 null, 'Total = (position from left) + (position from right) - 1 = 15 + 8 - 1 = 22.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('RRB NTPC', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'A is the son of B. C is the mother of A. How is C related to B?',
 '[{"text":"Wife","isCorrect":true},{"text":"Sister","isCorrect":false},{"text":"Mother","isCorrect":false},{"text":"Daughter","isCorrect":false}]'::jsonb,
 null, 'Since C is A''s mother and A is B''s son, C is B''s wife.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A person walks 6 km north, then 8 km east. How far is he from his starting point?',
 '[{"text":"10 km","isCorrect":true},{"text":"14 km","isCorrect":false},{"text":"8 km","isCorrect":false},{"text":"12 km","isCorrect":false}]'::jsonb,
 null, 'By the Pythagorean theorem, the distance is sqrt(6^2 + 8^2) = sqrt(100) = 10 km.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a girl, a man said, "She is the daughter of my mother''s only son," and the man has no brothers. How is the girl related to the man?',
 '[{"text":"Daughter","isCorrect":true},{"text":"Sister","isCorrect":false},{"text":"Niece","isCorrect":false},{"text":"Wife","isCorrect":false}]'::jsonb,
 null, 'Since the man has no brothers, "my mother''s only son" refers to himself, so the girl is his own daughter.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A man walks 5 km east, turns left, walks 5 km, turns left again, walks 5 km. How far is he from his starting point?',
 '[{"text":"5 km","isCorrect":true},{"text":"10 km","isCorrect":false},{"text":"15 km","isCorrect":false},{"text":"0 km","isCorrect":false}]'::jsonb,
 null, 'Plotting the path shows the final position is 5 km from the starting point, directly north of it.'),

-- General Intelligence and Reasoning: Syllogism and Statement-Conclusion
('RRB NTPC', 'General Intelligence and Reasoning', 'Syllogism and Statement-Conclusion', 'easy', 'mcq',
 'Statement: All trains are vehicles. All vehicles have wheels. Conclusion: All trains have wheels. Is the conclusion valid?',
 '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false},{"text":"Cannot be determined","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'Since all trains are vehicles and all vehicles have wheels, it logically follows that all trains have wheels.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Syllogism and Statement-Conclusion', 'medium', 'mcq',
 'Statements: Some books are pens. All pens are ink-holders. Conclusion I: Some books are ink-holders. Conclusion II: All ink-holders are pens. Which conclusion(s) follow?',
 '[{"text":"Only I","isCorrect":true},{"text":"Only II","isCorrect":false},{"text":"Both I and II","isCorrect":false},{"text":"Neither I nor II","isCorrect":false}]'::jsonb,
 null, 'Since some books are pens and all pens are ink-holders, some books must be ink-holders (Conclusion I). Conclusion II reverses the relationship and does not follow.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Syllogism and Statement-Conclusion', 'medium', 'mcq',
 'Statement: No trains are buses. All buses are vehicles. Conclusion I: No trains are vehicles. Conclusion II: Some vehicles are buses. Which conclusion(s) follow?',
 '[{"text":"Only I","isCorrect":false},{"text":"Only II","isCorrect":true},{"text":"Both I and II","isCorrect":false},{"text":"Neither I nor II","isCorrect":false}]'::jsonb,
 null, 'Since all buses are vehicles, at least some vehicles must be buses (Conclusion II). Conclusion I does not follow, since trains could still be vehicles through another category.'),
('RRB NTPC', 'General Intelligence and Reasoning', 'Syllogism and Statement-Conclusion', 'hard', 'mcq',
 'Statements: All engineers are graduates. Some graduates are teachers. Conclusion I: Some engineers are teachers. Conclusion II: Some teachers are engineers. Which conclusion(s) follow?',
 '[{"text":"Only I","isCorrect":false},{"text":"Only II","isCorrect":false},{"text":"Both I and II","isCorrect":false},{"text":"Neither I nor II","isCorrect":true}]'::jsonb,
 null, 'The graduates who are teachers are not guaranteed to overlap with the graduates who are engineers, so neither conclusion necessarily follows.'),

-- General Awareness: Indian History and Culture
('RRB NTPC', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who was the first President of India?',
 '[{"text":"Dr. Rajendra Prasad","isCorrect":true},{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Dr. S. Radhakrishnan","isCorrect":false},{"text":"Zakir Hussain","isCorrect":false}]'::jsonb,
 null, 'Dr. Rajendra Prasad served as the first President of India from 1950 to 1962.'),
('RRB NTPC', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'The Salt March (Dandi March) was led by whom?',
 '[{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Mahatma Gandhi","isCorrect":true},{"text":"Subhas Chandra Bose","isCorrect":false},{"text":"Sardar Patel","isCorrect":false}]'::jsonb,
 null, 'Mahatma Gandhi led the Salt March (Dandi March) in 1930 to protest the British salt tax.'),
('RRB NTPC', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Who founded the Vijayanagara Empire?',
 '[{"text":"Krishnadevaraya","isCorrect":false},{"text":"Harihara and Bukka","isCorrect":true},{"text":"Ashoka","isCorrect":false},{"text":"Akbar","isCorrect":false}]'::jsonb,
 null, 'The Vijayanagara Empire was founded by the brothers Harihara I and Bukka I in 1336.'),
('RRB NTPC', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'In which year was the First Battle of Panipat fought?',
 '[{"text":"1526","isCorrect":true},{"text":"1556","isCorrect":false},{"text":"1761","isCorrect":false},{"text":"1600","isCorrect":false}]'::jsonb,
 null, 'The First Battle of Panipat was fought in 1526 between Babur and Ibrahim Lodi.'),

-- General Awareness: Indian Polity and Geography
('RRB NTPC', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Who is the head of the Indian judiciary?',
 '[{"text":"President","isCorrect":false},{"text":"Prime Minister","isCorrect":false},{"text":"Chief Justice of India","isCorrect":true},{"text":"Attorney General","isCorrect":false}]'::jsonb,
 null, 'The Chief Justice of India is the head of the Indian judiciary.'),
('RRB NTPC', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the longest river in India?',
 '[{"text":"Yamuna","isCorrect":false},{"text":"Ganga","isCorrect":true},{"text":"Godavari","isCorrect":false},{"text":"Narmada","isCorrect":false}]'::jsonb,
 null, 'The Ganga is the longest river in India.'),
('RRB NTPC', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'How many Union Territories are there in India?',
 '[{"text":"7","isCorrect":false},{"text":"8","isCorrect":true},{"text":"9","isCorrect":false},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'India currently has 8 Union Territories.'),
('RRB NTPC', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which state is known as the "Land of Five Rivers"?',
 '[{"text":"Haryana","isCorrect":false},{"text":"Punjab","isCorrect":true},{"text":"Rajasthan","isCorrect":false},{"text":"Gujarat","isCorrect":false}]'::jsonb,
 null, 'Punjab, meaning "land of five rivers", is named for the five rivers that flow through it.'),

-- General Awareness: General Science
('RRB NTPC', 'General Awareness', 'General Science', 'easy', 'mcq',
 'What is the boiling point of water at sea level, in degrees Celsius?',
 '[{"text":"90","isCorrect":false},{"text":"100","isCorrect":true},{"text":"110","isCorrect":false},{"text":"120","isCorrect":false}]'::jsonb,
 null, 'Water boils at 100 degrees Celsius at sea level (standard atmospheric pressure).'),
('RRB NTPC', 'General Awareness', 'General Science', 'easy', 'mcq',
 'Which organ is primarily responsible for filtering blood in the human body?',
 '[{"text":"Liver","isCorrect":false},{"text":"Kidney","isCorrect":true},{"text":"Heart","isCorrect":false},{"text":"Lungs","isCorrect":false}]'::jsonb,
 null, 'The kidneys filter waste products and excess substances from the blood.'),
('RRB NTPC', 'General Awareness', 'General Science', 'medium', 'mcq',
 'Which type of mirror is commonly used in vehicle headlights?',
 '[{"text":"Plane mirror","isCorrect":false},{"text":"Concave mirror","isCorrect":true},{"text":"Convex mirror","isCorrect":false},{"text":"Cylindrical mirror","isCorrect":false}]'::jsonb,
 null, 'Concave mirrors are used in headlights because they can focus light into a parallel beam.'),
('RRB NTPC', 'General Awareness', 'General Science', 'medium', 'mcq',
 'The process by which plants lose water in the form of vapor is called:',
 '[{"text":"Respiration","isCorrect":false},{"text":"Transpiration","isCorrect":true},{"text":"Photosynthesis","isCorrect":false},{"text":"Osmosis","isCorrect":false}]'::jsonb,
 null, 'Transpiration is the process by which plants release water vapor, mainly through the stomata of their leaves.'),

-- General Awareness: Current Affairs and Sports
('RRB NTPC', 'General Awareness', 'Current Affairs and Sports', 'easy', 'mcq',
 'How many players are there in a football (soccer) team on the field?',
 '[{"text":"10","isCorrect":false},{"text":"11","isCorrect":true},{"text":"9","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'A football team fields 11 players at a time, including the goalkeeper.'),
('RRB NTPC', 'General Awareness', 'Current Affairs and Sports', 'easy', 'mcq',
 'The Asian Games are held every how many years?',
 '[{"text":"2","isCorrect":false},{"text":"3","isCorrect":false},{"text":"4","isCorrect":true},{"text":"5","isCorrect":false}]'::jsonb,
 null, 'The Asian Games are held once every 4 years.'),
('RRB NTPC', 'General Awareness', 'Current Affairs and Sports', 'medium', 'mcq',
 'Which trophy is associated with cricket test matches between India and Australia?',
 '[{"text":"The Ashes","isCorrect":false},{"text":"Border-Gavaskar Trophy","isCorrect":true},{"text":"World Cup","isCorrect":false},{"text":"Champions Trophy","isCorrect":false}]'::jsonb,
 null, 'The Border-Gavaskar Trophy is contested in test cricket series between India and Australia.'),
('RRB NTPC', 'General Awareness', 'Current Affairs and Sports', 'medium', 'mcq',
 'Who is the first Indian woman to win an Olympic medal?',
 '[{"text":"P.T. Usha","isCorrect":false},{"text":"Karnam Malleswari","isCorrect":true},{"text":"Saina Nehwal","isCorrect":false},{"text":"Mary Kom","isCorrect":false}]'::jsonb,
 null, 'Karnam Malleswari won a bronze medal in weightlifting at the 2000 Sydney Olympics, becoming the first Indian woman to win an Olympic medal.'),

-- General Awareness: Indian Economy
('RRB NTPC', 'General Awareness', 'Indian Economy', 'easy', 'mcq',
 'Which bank issues currency notes in India?',
 '[{"text":"SBI","isCorrect":false},{"text":"RBI","isCorrect":true},{"text":"NABARD","isCorrect":false},{"text":"Finance Ministry","isCorrect":false}]'::jsonb,
 null, 'The Reserve Bank of India (RBI) is the sole authority for issuing currency notes in India.'),
('RRB NTPC', 'General Awareness', 'Indian Economy', 'easy', 'mcq',
 'What does GST stand for?',
 '[{"text":"Goods and Services Tax","isCorrect":true},{"text":"General Sales Tax","isCorrect":false},{"text":"Government Service Tax","isCorrect":false},{"text":"Gross Sales Tax","isCorrect":false}]'::jsonb,
 null, 'GST stands for Goods and Services Tax, a unified indirect tax system in India.'),
('RRB NTPC', 'General Awareness', 'Indian Economy', 'medium', 'mcq',
 'In which year was the Indian rupee symbol officially adopted?',
 '[{"text":"2010","isCorrect":true},{"text":"2005","isCorrect":false},{"text":"2015","isCorrect":false},{"text":"2000","isCorrect":false}]'::jsonb,
 null, 'The Indian rupee symbol (Rs) was officially adopted in 2010.'),
('RRB NTPC', 'General Awareness', 'Indian Economy', 'medium', 'mcq',
 'Which Five-Year Plan of India focused on rapid industrialization?',
 '[{"text":"First","isCorrect":false},{"text":"Second","isCorrect":true},{"text":"Third","isCorrect":false},{"text":"Fourth","isCorrect":false}]'::jsonb,
 null, 'The Second Five-Year Plan, based on the Mahalanobis model, focused on rapid industrialization.'),

-- General Awareness: Railways General Knowledge
('RRB NTPC', 'General Awareness', 'Railways General Knowledge', 'easy', 'mcq',
 'In which year did the first passenger train run in India?',
 '[{"text":"1853","isCorrect":true},{"text":"1900","isCorrect":false},{"text":"1920","isCorrect":false},{"text":"1830","isCorrect":false}]'::jsonb,
 null, 'The first passenger train in India ran in 1853, between Bombay (Mumbai) and Thane.'),
('RRB NTPC', 'General Awareness', 'Railways General Knowledge', 'easy', 'mcq',
 'What is the name of India''s first bullet train corridor project?',
 '[{"text":"Delhi-Mumbai","isCorrect":false},{"text":"Mumbai-Ahmedabad","isCorrect":true},{"text":"Chennai-Bengaluru","isCorrect":false},{"text":"Kolkata-Delhi","isCorrect":false}]'::jsonb,
 null, 'The Mumbai-Ahmedabad High Speed Rail Corridor is India''s first bullet train project.'),
('RRB NTPC', 'General Awareness', 'Railways General Knowledge', 'medium', 'mcq',
 'How many railway zones are there in Indian Railways?',
 '[{"text":"16","isCorrect":false},{"text":"17","isCorrect":true},{"text":"18","isCorrect":false},{"text":"15","isCorrect":false}]'::jsonb,
 null, 'Indian Railways is currently divided into 17 railway zones.'),
('RRB NTPC', 'General Awareness', 'Railways General Knowledge', 'medium', 'mcq',
 'What is the headquarters building of Indian Railways called?',
 '[{"text":"Railway Bhawan","isCorrect":true},{"text":"Rail Sadan","isCorrect":false},{"text":"Rail Bhavan","isCorrect":false},{"text":"Railway House","isCorrect":false}]'::jsonb,
 null, 'Railway Bhawan in New Delhi houses the headquarters of Indian Railways and the Ministry of Railways.');
