-- supabase/sql/exam_question_bank_neet_pg_set6.sql
--
-- Sixth curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and Sets 1-5 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1 through 5.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical
-- Sciences, 4 Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/
-- Anesthesia) each get 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql through set5.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The Circle of Willis, an anastomotic ring of arteries, is formed at the base of which organ?',
 '[{"text":"The heart","isCorrect":false},{"text":"The brain","isCorrect":true},{"text":"The liver","isCorrect":false},{"text":"The kidney","isCorrect":false}]'::jsonb,
 null, 'The Circle of Willis is an anastomotic arterial ring located at the base of the brain, providing collateral blood supply between the anterior and posterior cerebral circulations.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'In males, the inguinal canal primarily transmits the:',
 '[{"text":"Spermatic cord","isCorrect":true},{"text":"Sciatic nerve","isCorrect":false},{"text":"Femoral artery","isCorrect":false},{"text":"Ureter","isCorrect":false}]'::jsonb,
 null, 'The inguinal canal in males transmits the spermatic cord, which contains the vas deferens, testicular vessels, and associated nerves.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Injury to the common peroneal nerve classically causes which deformity?',
 '[{"text":"Foot drop","isCorrect":true},{"text":"Claw hand","isCorrect":false},{"text":"Wrist drop","isCorrect":false},{"text":"Winging of the scapula","isCorrect":false}]'::jsonb,
 null, 'Common peroneal nerve injury paralyzes the dorsiflexors and evertors of the foot, causing the characteristic foot drop.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Taste sensation from the anterior two-thirds of the tongue is carried by which cranial nerve?',
 '[{"text":"Glossopharyngeal nerve (CN IX)","isCorrect":false},{"text":"Facial nerve (CN VII), via the chorda tympani","isCorrect":true},{"text":"Vagus nerve (CN X)","isCorrect":false},{"text":"Hypoglossal nerve (CN XII)","isCorrect":false}]'::jsonb,
 null, 'Taste sensation from the anterior two-thirds of the tongue is carried by the facial nerve via its chorda tympani branch, while the posterior third is served by the glossopharyngeal nerve.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The normal urine output considered adequate in an adult is at least:',
 '[{"text":"0.05 mL/kg/hour","isCorrect":false},{"text":"0.5 mL/kg/hour","isCorrect":true},{"text":"5 mL/kg/hour","isCorrect":false},{"text":"15 mL/kg/hour","isCorrect":false}]'::jsonb,
 null, 'A urine output of at least 0.5 mL/kg/hour is generally considered adequate to indicate sufficient renal perfusion in adults.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The Bohr effect describes how the oxygen affinity of hemoglobin decreases with:',
 '[{"text":"Increasing carbon dioxide and decreasing pH (acidity)","isCorrect":true},{"text":"Decreasing carbon dioxide and increasing pH","isCorrect":false},{"text":"Increasing temperature only, unrelated to CO2","isCorrect":false},{"text":"Decreasing 2,3-BPG levels","isCorrect":false}]'::jsonb,
 null, 'The Bohr effect describes how increased carbon dioxide and decreased pH (increased acidity), as seen in actively metabolizing tissues, reduce hemoglobin''s affinity for oxygen, promoting oxygen release.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The baroreceptor reflex, involving receptors in the carotid sinus and aortic arch, primarily helps regulate:',
 '[{"text":"Blood glucose levels","isCorrect":false},{"text":"Blood pressure","isCorrect":true},{"text":"Body temperature","isCorrect":false},{"text":"Respiratory rate alone","isCorrect":false}]'::jsonb,
 null, 'Baroreceptors in the carotid sinus and aortic arch detect changes in blood pressure and trigger reflex adjustments in heart rate and vascular tone to maintain stable blood pressure.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'Which reflex helps protect the airway by closing the epiglottis during swallowing?',
 '[{"text":"Gag/swallowing reflex","isCorrect":true},{"text":"Knee-jerk reflex","isCorrect":false},{"text":"Pupillary light reflex","isCorrect":false},{"text":"Babinski reflex","isCorrect":false}]'::jsonb,
 null, 'The swallowing (deglutition) reflex, which includes closure of the epiglottis over the airway, protects against aspiration of food or liquid into the trachea.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'hard', 'mcq',
 'The rate-limiting enzyme of the urea cycle is:',
 '[{"text":"Carbamoyl phosphate synthetase I","isCorrect":true},{"text":"Arginase","isCorrect":false},{"text":"Ornithine transcarbamylase","isCorrect":false},{"text":"Argininosuccinate synthetase","isCorrect":false}]'::jsonb,
 null, 'Carbamoyl phosphate synthetase I catalyzes the first, rate-limiting step of the urea cycle, combining ammonia with bicarbonate to form carbamoyl phosphate.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Deficiency of which vitamin causes pellagra, characterized by dermatitis, diarrhea, and dementia?',
 '[{"text":"Niacin (Vitamin B3)","isCorrect":true},{"text":"Thiamine (Vitamin B1)","isCorrect":false},{"text":"Riboflavin (Vitamin B2)","isCorrect":false},{"text":"Folate","isCorrect":false}]'::jsonb,
 null, 'Niacin (Vitamin B3) deficiency causes pellagra, classically remembered by the "3 Ds": dermatitis, diarrhea, and dementia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'hard', 'mcq',
 'Glucose-6-phosphate dehydrogenase (G6PD) deficiency primarily impairs which metabolic pathway?',
 '[{"text":"The urea cycle","isCorrect":false},{"text":"The pentose phosphate pathway","isCorrect":true},{"text":"The Krebs cycle","isCorrect":false},{"text":"Beta-oxidation of fatty acids","isCorrect":false}]'::jsonb,
 null, 'G6PD deficiency impairs the pentose phosphate pathway, reducing NADPH production and leaving red blood cells vulnerable to oxidative damage and hemolysis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Insulin primarily promotes glucose uptake in which tissues?',
 '[{"text":"Skeletal muscle and adipose tissue","isCorrect":true},{"text":"The brain exclusively","isCorrect":false},{"text":"Red blood cells exclusively","isCorrect":false},{"text":"The liver exclusively, with no effect elsewhere","isCorrect":false}]'::jsonb,
 null, 'Insulin promotes GLUT4-mediated glucose uptake primarily in skeletal muscle and adipose tissue, in contrast to insulin-independent tissues like the brain.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Graft rejection, a cell-mediated immune response, is classically an example of which type of hypersensitivity?',
 '[{"text":"Type I hypersensitivity","isCorrect":false},{"text":"Type IV hypersensitivity","isCorrect":true},{"text":"Type II hypersensitivity","isCorrect":false},{"text":"Type III hypersensitivity","isCorrect":false}]'::jsonb,
 null, 'Graft rejection is a classic example of Type IV (delayed/cell-mediated) hypersensitivity, driven by T lymphocytes rather than antibodies.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'A "starry sky" appearance on histology is a classic finding in:',
 '[{"text":"Burkitt lymphoma","isCorrect":true},{"text":"Hodgkin lymphoma","isCorrect":false},{"text":"Chronic lymphocytic leukemia","isCorrect":false},{"text":"Multiple myeloma","isCorrect":false}]'::jsonb,
 null, 'The "starry sky" appearance, caused by scattered macrophages engulfing apoptotic tumor cells amid a background of dark-staining lymphoma cells, is classic for Burkitt lymphoma.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Dystrophic calcification occurs in:',
 '[{"text":"Dead or damaged tissue, with normal serum calcium levels","isCorrect":true},{"text":"Only healthy, normal tissue","isCorrect":false},{"text":"Tissue with elevated serum calcium levels only","isCorrect":false},{"text":"Bone tissue exclusively","isCorrect":false}]'::jsonb,
 null, 'Dystrophic calcification refers to calcium deposition in dead or damaged tissue, occurring despite normal serum calcium levels, unlike metastatic calcification which is linked to hypercalcemia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'The most common site of distant metastasis for breast cancer is:',
 '[{"text":"Bone","isCorrect":true},{"text":"Spleen","isCorrect":false},{"text":"Skin exclusively","isCorrect":false},{"text":"Pancreas","isCorrect":false}]'::jsonb,
 null, 'Bone is the most common site of distant metastasis for breast cancer, though lung, liver, and brain metastases are also frequent.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'The most common cause of bacterial meningitis in neonates is:',
 '[{"text":"Group B Streptococcus (Streptococcus agalactiae)","isCorrect":true},{"text":"Neisseria meningitidis","isCorrect":false},{"text":"Streptococcus pneumoniae","isCorrect":false},{"text":"Haemophilus influenzae","isCorrect":false}]'::jsonb,
 null, 'Group B Streptococcus (Streptococcus agalactiae), acquired from the maternal genital tract, is the most common cause of bacterial meningitis in neonates.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'The Ziehl-Neelsen stain is used to identify which type of organism?',
 '[{"text":"Acid-fast bacilli (e.g. Mycobacterium)","isCorrect":true},{"text":"Gram-negative cocci","isCorrect":false},{"text":"Fungal spores","isCorrect":false},{"text":"Viruses","isCorrect":false}]'::jsonb,
 null, 'The Ziehl-Neelsen stain is a specialized acid-fast staining technique used to identify Mycobacterium species, including Mycobacterium tuberculosis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Infectious mononucleosis is most commonly caused by which virus?',
 '[{"text":"Epstein-Barr virus (EBV)","isCorrect":true},{"text":"Cytomegalovirus","isCorrect":false},{"text":"Varicella-zoster virus","isCorrect":false},{"text":"Herpes simplex virus","isCorrect":false}]'::jsonb,
 null, 'Epstein-Barr virus (EBV) is the most common cause of infectious mononucleosis, classically presenting with fever, pharyngitis, and lymphadenopathy.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Candida albicans is an example of which type of organism?',
 '[{"text":"A bacterium","isCorrect":false},{"text":"A fungus (yeast)","isCorrect":true},{"text":"A virus","isCorrect":false},{"text":"A protozoan parasite","isCorrect":false}]'::jsonb,
 null, 'Candida albicans is a fungal (yeast) organism, commonly causing opportunistic infections like oral thrush and vaginal candidiasis.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'The drug of choice for treating trigeminal neuralgia is:',
 '[{"text":"Carbamazepine","isCorrect":true},{"text":"Metformin","isCorrect":false},{"text":"Furosemide","isCorrect":false},{"text":"Salbutamol","isCorrect":false}]'::jsonb,
 null, 'Carbamazepine is the first-line drug of choice for managing trigeminal neuralgia, a condition causing severe facial pain.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Vancomycin is primarily used to treat infections caused by:',
 '[{"text":"Gram-negative bacteria only","isCorrect":false},{"text":"Gram-positive bacteria (including MRSA)","isCorrect":true},{"text":"Fungi only","isCorrect":false},{"text":"Viruses","isCorrect":false}]'::jsonb,
 null, 'Vancomycin is a glycopeptide antibiotic effective against gram-positive bacteria, including methicillin-resistant Staphylococcus aureus (MRSA).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which vitamin is co-administered with isoniazid to prevent drug-induced peripheral neuropathy?',
 '[{"text":"Vitamin B6 (pyridoxine)","isCorrect":true},{"text":"Vitamin B12","isCorrect":false},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":false}]'::jsonb,
 null, 'Pyridoxine (Vitamin B6) is co-administered with isoniazid to prevent the peripheral neuropathy caused by isoniazid-induced vitamin B6 depletion.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'hard', 'mcq',
 'Heparin exerts its anticoagulant effect primarily by activating:',
 '[{"text":"Antithrombin III","isCorrect":true},{"text":"Vitamin K","isCorrect":false},{"text":"Plasminogen directly","isCorrect":false},{"text":"Factor VIII","isCorrect":false}]'::jsonb,
 null, 'Heparin binds to and activates antithrombin III, greatly accelerating its inhibition of thrombin and other clotting factors.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'hard', 'mcq',
 '"Tache noire" refers to a postmortem change affecting the:',
 '[{"text":"Eyes (drying of the sclera where eyelids remain open)","isCorrect":true},{"text":"Fingernails","isCorrect":false},{"text":"Scalp hair","isCorrect":false},{"text":"Teeth","isCorrect":false}]'::jsonb,
 null, 'Tache noire refers to a brownish-black band of drying on the sclera, occurring where the eyelids fail to fully cover the eye after death.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Organophosphorus compound poisoning acts primarily by inhibiting which enzyme?',
 '[{"text":"Acetylcholinesterase","isCorrect":true},{"text":"Monoamine oxidase","isCorrect":false},{"text":"Cyclooxygenase","isCorrect":false},{"text":"Xanthine oxidase","isCorrect":false}]'::jsonb,
 null, 'Organophosphorus compounds inhibit acetylcholinesterase, leading to excess acetylcholine accumulation and a cholinergic toxidrome.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'In most modern jurisdictions, the legal definition of death is based on the irreversible cessation of:',
 '[{"text":"Cardiorespiratory function or whole brain function","isCorrect":true},{"text":"Skin sensation only","isCorrect":false},{"text":"Hair growth","isCorrect":false},{"text":"Digestive activity only","isCorrect":false}]'::jsonb,
 null, 'Legal death is generally defined by the irreversible cessation of either cardiorespiratory function or whole brain function (brain death).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Adipocere (grave wax) formation on a body typically occurs under which environmental conditions?',
 '[{"text":"Dry, hot, and well-ventilated conditions","isCorrect":false},{"text":"Moist, cool, and anaerobic conditions","isCorrect":true},{"text":"High altitude and freezing conditions only","isCorrect":false},{"text":"Direct sunlight exposure only","isCorrect":false}]'::jsonb,
 null, 'Adipocere, a waxy substance formed from body fat, develops under moist, cool, and anaerobic conditions that favor the hydrolysis and hydrogenation of fats.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The "specificity" of a diagnostic test refers to:',
 '[{"text":"The ability to correctly identify those without the disease (true negative rate)","isCorrect":true},{"text":"The ability to correctly identify those with the disease","isCorrect":false},{"text":"The cost of performing the test","isCorrect":false},{"text":"The time taken to get results","isCorrect":false}]'::jsonb,
 null, 'Specificity measures a test''s ability to correctly identify individuals who do not have the disease (the true negative rate).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which vaccine is given to prevent Japanese encephalitis in endemic areas of India?',
 '[{"text":"JE vaccine","isCorrect":true},{"text":"BCG vaccine","isCorrect":false},{"text":"OPV","isCorrect":false},{"text":"Hepatitis B vaccine","isCorrect":false}]'::jsonb,
 null, 'The Japanese Encephalitis (JE) vaccine is administered in endemic regions of India to prevent this mosquito-borne viral infection.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Maternal Mortality Ratio (MMR) is defined as the number of maternal deaths per:',
 '[{"text":"1,000 live births","isCorrect":false},{"text":"100,000 live births","isCorrect":true},{"text":"1,000,000 population","isCorrect":false},{"text":"10,000 pregnancies","isCorrect":false}]'::jsonb,
 null, 'Maternal Mortality Ratio is expressed as the number of maternal deaths per 100,000 live births in a given period.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'A randomized controlled trial is generally considered the gold standard for establishing:',
 '[{"text":"Causality between an intervention and an outcome","isCorrect":true},{"text":"The prevalence of a disease","isCorrect":false},{"text":"The cost of treatment only","isCorrect":false},{"text":"Patient satisfaction alone","isCorrect":false}]'::jsonb,
 null, 'Randomized controlled trials, by minimizing confounding through randomization, are considered the gold-standard study design for establishing causal relationships between an intervention and an outcome.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Hyperthyroidism is most commonly caused by:',
 '[{"text":"Graves'' disease","isCorrect":true},{"text":"Iodine deficiency","isCorrect":false},{"text":"Pituitary tumor exclusively","isCorrect":false},{"text":"Vitamin D deficiency","isCorrect":false}]'::jsonb,
 null, 'Graves'' disease, an autoimmune condition causing excess thyroid hormone production, is the most common cause of hyperthyroidism.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Virchow''s classic triad for venous thrombosis includes stasis, hypercoagulability, and:',
 '[{"text":"Endothelial injury","isCorrect":true},{"text":"Fever","isCorrect":false},{"text":"Hypertension","isCorrect":false},{"text":"Anemia","isCorrect":false}]'::jsonb,
 null, 'Virchow''s triad for thrombosis consists of venous stasis, hypercoagulability, and endothelial (vessel wall) injury.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Addison''s disease results from:',
 '[{"text":"Adrenal insufficiency (deficient cortisol and aldosterone production)","isCorrect":true},{"text":"Excess cortisol production","isCorrect":false},{"text":"Excess thyroid hormone production","isCorrect":false},{"text":"Pancreatic insulin deficiency","isCorrect":false}]'::jsonb,
 null, 'Addison''s disease is caused by primary adrenal insufficiency, resulting in deficient production of cortisol and aldosterone.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common overall cause of secondary hypertension is:',
 '[{"text":"Renal parenchymal disease","isCorrect":true},{"text":"Pheochromocytoma","isCorrect":false},{"text":"Cushing''s syndrome","isCorrect":false},{"text":"Coarctation of the aorta","isCorrect":false}]'::jsonb,
 null, 'Renal parenchymal disease is the most common overall cause of secondary hypertension, though renal artery stenosis is classically emphasized in younger patients.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common cause of chronic stridor in infants is:',
 '[{"text":"Laryngomalacia","isCorrect":true},{"text":"Croup","isCorrect":false},{"text":"Foreign body aspiration","isCorrect":false},{"text":"Epiglottitis","isCorrect":false}]'::jsonb,
 null, 'Laryngomalacia, caused by floppy supraglottic structures, is the most common cause of chronic stridor in infants, usually improving as the child grows.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'Which primitive reflex causes a newborn to turn toward a stimulus and open the mouth when the cheek is stroked?',
 '[{"text":"Rooting reflex","isCorrect":true},{"text":"Moro reflex","isCorrect":false},{"text":"Palmar grasp reflex","isCorrect":false},{"text":"Babinski reflex","isCorrect":false}]'::jsonb,
 null, 'The rooting reflex causes a newborn to turn their head toward a stimulus touching the cheek and open their mouth, aiding in breastfeeding.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Untreated congenital hypothyroidism in infants leads to which condition?',
 '[{"text":"Cretinism (severe growth and mental developmental delay)","isCorrect":true},{"text":"Gigantism","isCorrect":false},{"text":"Precocious puberty","isCorrect":false},{"text":"Rickets","isCorrect":false}]'::jsonb,
 null, 'If left untreated, congenital hypothyroidism leads to cretinism, characterized by severe growth retardation and intellectual disability.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common bacterial cause of acute otitis media in children is:',
 '[{"text":"Streptococcus pneumoniae","isCorrect":true},{"text":"Escherichia coli","isCorrect":false},{"text":"Mycobacterium tuberculosis","isCorrect":false},{"text":"Neisseria gonorrhoeae","isCorrect":false}]'::jsonb,
 null, 'Streptococcus pneumoniae is the most common bacterial cause of acute otitis media in children, followed by non-typeable Haemophilus influenzae.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Anorexia nervosa is characterized by:',
 '[{"text":"Severe restriction of food intake leading to significantly low body weight, with an intense fear of weight gain","isCorrect":true},{"text":"Excessive eating with no distress","isCorrect":false},{"text":"Normal body weight with no eating disturbance","isCorrect":false},{"text":"Compulsive overexercising only, with normal eating","isCorrect":false}]'::jsonb,
 null, 'Anorexia nervosa is characterized by restriction of energy intake leading to significantly low body weight, coupled with an intense fear of gaining weight and body image disturbance.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which personality disorder is characterized by a pervasive pattern of disregard for the rights of others?',
 '[{"text":"Antisocial personality disorder","isCorrect":true},{"text":"Avoidant personality disorder","isCorrect":false},{"text":"Dependent personality disorder","isCorrect":false},{"text":"Obsessive-compulsive personality disorder","isCorrect":false}]'::jsonb,
 null, 'Antisocial personality disorder is characterized by a pervasive pattern of disregard for and violation of the rights of others, often with deceit and lack of remorse.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'Serotonin syndrome, a potentially life-threatening condition, most commonly results from:',
 '[{"text":"Combining multiple serotonergic drugs (e.g. SSRIs with MAOIs)","isCorrect":true},{"text":"Taking a single dose of an antihistamine","isCorrect":false},{"text":"Vitamin deficiency","isCorrect":false},{"text":"Excessive caffeine intake alone","isCorrect":false}]'::jsonb,
 null, 'Serotonin syndrome typically arises from combining two or more serotonergic drugs, such as SSRIs with MAOIs, leading to excess serotonergic activity.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Dissociative identity disorder is characterized by:',
 '[{"text":"The presence of two or more distinct personality states within an individual","isCorrect":true},{"text":"A single, stable personality with mood swings","isCorrect":false},{"text":"Complete loss of all memories permanently","isCorrect":false},{"text":"Hallucinations without any personality change","isCorrect":false}]'::jsonb,
 null, 'Dissociative identity disorder involves the presence of two or more distinct personality (identity) states, often accompanied by gaps in memory.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Erythema multiforme is most often triggered by:',
 '[{"text":"Infections (e.g. herpes simplex virus) or certain medications","isCorrect":true},{"text":"Excess sun exposure alone","isCorrect":false},{"text":"Cold weather alone","isCorrect":false},{"text":"Dietary changes alone","isCorrect":false}]'::jsonb,
 null, 'Erythema multiforme is most commonly triggered by infections, especially herpes simplex virus, or as a reaction to certain medications.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Molluscum contagiosum is caused by which type of pathogen?',
 '[{"text":"A poxvirus","isCorrect":true},{"text":"A bacterium","isCorrect":false},{"text":"A dermatophyte fungus","isCorrect":false},{"text":"A mite","isCorrect":false}]'::jsonb,
 null, 'Molluscum contagiosum is caused by a poxvirus, presenting as small, firm, umbilicated skin papules.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Pityriasis rosea classically begins with which characteristic lesion?',
 '[{"text":"A herald patch","isCorrect":true},{"text":"A pearly nodule","isCorrect":false},{"text":"A honey-colored crust","isCorrect":false},{"text":"A bullous lesion","isCorrect":false}]'::jsonb,
 null, 'Pityriasis rosea classically begins with a single, larger "herald patch," followed days later by a widespread rash of smaller oval lesions.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'hard', 'mcq',
 'Xeroderma pigmentosum is a genetic condition characterized by:',
 '[{"text":"Extreme sensitivity to UV light due to defective DNA repair, with high skin cancer risk","isCorrect":true},{"text":"Excess pigmentation with no cancer risk","isCorrect":false},{"text":"Complete absence of skin pigmentation","isCorrect":false},{"text":"Resistance to all forms of skin cancer","isCorrect":false}]'::jsonb,
 null, 'Xeroderma pigmentosum results from defective DNA repair mechanisms, causing extreme sensitivity to UV radiation and a dramatically increased risk of skin cancers.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common type of thyroid cancer is:',
 '[{"text":"Papillary thyroid carcinoma","isCorrect":true},{"text":"Follicular thyroid carcinoma","isCorrect":false},{"text":"Medullary thyroid carcinoma","isCorrect":false},{"text":"Anaplastic thyroid carcinoma","isCorrect":false}]'::jsonb,
 null, 'Papillary thyroid carcinoma is the most common type of thyroid cancer, generally carrying a favorable prognosis.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'hard', 'mcq',
 'A "Cullen''s sign" (periumbilical bruising) is classically associated with:',
 '[{"text":"Hemorrhagic pancreatitis (or ruptured ectopic pregnancy)","isCorrect":true},{"text":"Simple appendicitis","isCorrect":false},{"text":"Uncomplicated gastritis","isCorrect":false},{"text":"A benign ovarian cyst","isCorrect":false}]'::jsonb,
 null, 'Cullen''s sign, periumbilical bruising, is classically associated with hemorrhagic (acute) pancreatitis or a ruptured ectopic pregnancy, reflecting intra-abdominal bleeding tracking to the umbilicus.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Volvulus refers to:',
 '[{"text":"Twisting of a loop of bowel, causing obstruction","isCorrect":true},{"text":"Inflammation of the appendix","isCorrect":false},{"text":"Formation of gallstones","isCorrect":false},{"text":"A hernia through the umbilicus","isCorrect":false}]'::jsonb,
 null, 'Volvulus refers to the twisting of a loop of bowel around its mesentery, which can cause both obstruction and compromised blood supply.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common site of diverticulosis in Western populations is the:',
 '[{"text":"Sigmoid colon","isCorrect":true},{"text":"Cecum","isCorrect":false},{"text":"Transverse colon","isCorrect":false},{"text":"Rectum","isCorrect":false}]'::jsonb,
 null, 'The sigmoid colon is the most common site of diverticulosis in Western populations, likely related to higher intraluminal pressures in this segment.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'hard', 'mcq',
 'A "waiter''s tip" deformity is associated with injury to which part of the brachial plexus?',
 '[{"text":"Upper trunk (Erb''s palsy, C5-C6)","isCorrect":true},{"text":"Lower trunk (Klumpke''s palsy)","isCorrect":false},{"text":"The radial nerve alone","isCorrect":false},{"text":"The median nerve alone","isCorrect":false}]'::jsonb,
 null, 'The "waiter''s tip" deformity, with the arm adducted, internally rotated, and the wrist flexed, is characteristic of Erb''s palsy, involving injury to the upper trunk (C5-C6) of the brachial plexus.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Ewing sarcoma, an aggressive malignant bone tumor, most commonly affects which population?',
 '[{"text":"Elderly adults","isCorrect":false},{"text":"Children and adolescents","isCorrect":true},{"text":"Middle-aged women exclusively","isCorrect":false},{"text":"Infants under 1 year","isCorrect":false}]'::jsonb,
 null, 'Ewing sarcoma is an aggressive malignant bone tumor that most commonly affects children and adolescents.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Bone mineral density is most commonly measured using which imaging technique?',
 '[{"text":"DEXA scan (dual-energy X-ray absorptiometry)","isCorrect":true},{"text":"Plain X-ray alone","isCorrect":false},{"text":"Ultrasound","isCorrect":false},{"text":"MRI exclusively","isCorrect":false}]'::jsonb,
 null, 'DEXA (dual-energy X-ray absorptiometry) scanning is the standard imaging technique used to measure bone mineral density and diagnose osteoporosis.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'A "bucket-handle tear" is a type of injury commonly seen in which knee structure?',
 '[{"text":"Meniscus","isCorrect":true},{"text":"Anterior cruciate ligament","isCorrect":false},{"text":"Patella","isCorrect":false},{"text":"Quadriceps tendon","isCorrect":false}]'::jsonb,
 null, 'A bucket-handle tear is a specific pattern of longitudinal meniscal tear in the knee, where the torn fragment can displace like the handle of a bucket.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'In a postmenopausal woman with vaginal bleeding, which diagnosis must be urgently excluded?',
 '[{"text":"Endometrial cancer","isCorrect":true},{"text":"Ovulation","isCorrect":false},{"text":"Normal menstruation","isCorrect":false},{"text":"Pregnancy","isCorrect":false}]'::jsonb,
 null, 'Postmenopausal bleeding requires prompt evaluation to exclude endometrial cancer, even though the most common cause is benign endometrial atrophy.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Which hormone is primarily responsible for maintaining the endometrium during the luteal phase of the menstrual cycle?',
 '[{"text":"Progesterone","isCorrect":true},{"text":"Follicle-stimulating hormone","isCorrect":false},{"text":"Luteinizing hormone","isCorrect":false},{"text":"Oxytocin","isCorrect":false}]'::jsonb,
 null, 'Progesterone, secreted by the corpus luteum, maintains and supports the endometrium during the luteal phase, preparing it for potential implantation.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'A missed abortion refers to:',
 '[{"text":"Fetal death in utero without expulsion of the products of conception","isCorrect":true},{"text":"An abortion performed intentionally","isCorrect":false},{"text":"Delivery of a live baby prematurely","isCorrect":false},{"text":"A normal, uncomplicated pregnancy","isCorrect":false}]'::jsonb,
 null, 'A missed abortion occurs when the fetus has died in utero, but the products of conception are not spontaneously expelled.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Primary amenorrhea is generally defined as the absence of menstruation by approximately what age?',
 '[{"text":"10 years","isCorrect":false},{"text":"15-16 years","isCorrect":true},{"text":"20-21 years","isCorrect":false},{"text":"25 years","isCorrect":false}]'::jsonb,
 null, 'Primary amenorrhea is generally defined as the absence of menarche by approximately 15-16 years of age, warranting further clinical evaluation.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The normal partial pressure of oxygen (PaO2) in arterial blood at sea level is approximately:',
 '[{"text":"40-50 mmHg","isCorrect":false},{"text":"80-100 mmHg","isCorrect":true},{"text":"150-160 mmHg","isCorrect":false},{"text":"200-220 mmHg","isCorrect":false}]'::jsonb,
 null, 'Normal arterial oxygen partial pressure (PaO2) at sea level is approximately 80 to 100 mmHg.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'For initial resuscitation of hemorrhagic shock, which type of fluid is generally preferred?',
 '[{"text":"Isotonic crystalloids (e.g. normal saline or Ringer''s lactate)","isCorrect":true},{"text":"Pure glucose solution","isCorrect":false},{"text":"Distilled water","isCorrect":false},{"text":"Hypotonic saline exclusively","isCorrect":false}]'::jsonb,
 null, 'Isotonic crystalloids, such as normal saline or Ringer''s lactate, are the standard initial fluids used for resuscitation in hemorrhagic shock.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'End-tidal CO2 monitoring (capnography) is primarily used to confirm:',
 '[{"text":"Correct placement of an endotracheal tube (and monitor ventilation)","isCorrect":true},{"text":"Blood glucose level","isCorrect":false},{"text":"Kidney function","isCorrect":false},{"text":"Body temperature","isCorrect":false}]'::jsonb,
 null, 'Capnography measures end-tidal CO2, confirming correct endotracheal tube placement and providing ongoing monitoring of ventilation adequacy.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The Ramsay sedation scale is used to assess:',
 '[{"text":"The level of sedation in a critically ill patient","isCorrect":true},{"text":"Blood pressure trends","isCorrect":false},{"text":"Nutritional status","isCorrect":false},{"text":"Wound healing progress","isCorrect":false}]'::jsonb,
 null, 'The Ramsay sedation scale is a clinical tool used to assess and grade the level of sedation in critically ill or mechanically ventilated patients.');
