-- supabase/sql/exam_question_bank_class6_set1.sql
--
-- First curated question-bank batch for 'Class 6' (see exam_patterns_class6.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 6's MCQ-only,
-- no-negative-marking pattern. 8 chapters (2 per subject x 4 subjects) each get 4 questions --
-- one easy, two medium, one hard -- reflecting the increased hard share in
-- exam_patterns_class6.sql. This is the first Schools set with 4 subjects (English, Mathematics,
-- Science, Social Science), matching NCERT's split of the combined EVS subject used through
-- Class 5 (see exam_question_bank_class5_set1.sql) into separate Science and Social Science.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class6.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Grammar: Nouns, Pronouns, Tenses and Punctuation
('Class 6', 'English', 'Grammar: Nouns, Pronouns, Tenses and Punctuation', 'easy', 'mcq',
 'Which of the following is an abstract noun?',
 '[{"text":"Table","isCorrect":false},{"text":"Honesty","isCorrect":true},{"text":"Dog","isCorrect":false},{"text":"River","isCorrect":false}]'::jsonb,
 null, 'An abstract noun names a quality, feeling, or idea that cannot be touched. ''Honesty'' is a quality, so it is abstract.'),
('Class 6', 'English', 'Grammar: Nouns, Pronouns, Tenses and Punctuation', 'medium', 'mcq',
 'Choose the correct possessive pronoun: "This bag is ___."',
 '[{"text":"I","isCorrect":false},{"text":"me","isCorrect":false},{"text":"mine","isCorrect":true},{"text":"my","isCorrect":false}]'::jsonb,
 null, '''Mine'' is a possessive pronoun that stands alone to show ownership, correctly completing the sentence.'),
('Class 6', 'English', 'Grammar: Nouns, Pronouns, Tenses and Punctuation', 'medium', 'mcq',
 'Which sentence correctly uses the present perfect tense?',
 '[{"text":"She has finished her homework.","isCorrect":true},{"text":"She have finished her homework.","isCorrect":false},{"text":"She finishing her homework.","isCorrect":false},{"text":"She finish her homework.","isCorrect":false}]'::jsonb,
 null, 'The present perfect tense uses ''has/have'' + past participle. With ''She'' (singular), the correct form is ''has finished''.'),
('Class 6', 'English', 'Grammar: Nouns, Pronouns, Tenses and Punctuation', 'hard', 'mcq',
 'Identify the correctly punctuated sentence.',
 '[{"text":"My friends Ravi, Sita and Amit are coming.","isCorrect":true},{"text":"My friends Ravi Sita and Amit are coming.","isCorrect":false},{"text":"My friends, Ravi Sita, and Amit are coming.","isCorrect":false},{"text":"My friends Ravi, Sita, and, Amit are coming.","isCorrect":false}]'::jsonb,
 null, 'Commas are correctly used to separate items in a list of three or more names.'),

-- English: Reading Comprehension and Vocabulary
('Class 6', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'Read: "The old lighthouse had guided ships safely to shore for over a hundred years." What did the lighthouse do?',
 '[{"text":"Guided ships safely to shore","isCorrect":true},{"text":"Sank ships","isCorrect":false},{"text":"Was destroyed","isCorrect":false},{"text":"Was built recently","isCorrect":false}]'::jsonb,
 null, 'The passage says the lighthouse had guided ships safely to shore for over a hundred years.'),
('Class 6', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'A word that means the same as ''diligent'' is:',
 '[{"text":"Lazy","isCorrect":false},{"text":"Hardworking","isCorrect":true},{"text":"Careless","isCorrect":false},{"text":"Slow","isCorrect":false}]'::jsonb,
 null, '''Hardworking'' means the same as ''diligent''.'),
('Class 6', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'Read: "Even though the trek was exhausting, the scenic view from the summit made every step worthwhile." What made the difficult trek worthwhile?',
 '[{"text":"The scenic view from the summit","isCorrect":true},{"text":"The exhausting climb","isCorrect":false},{"text":"Turning back early","isCorrect":false},{"text":"Bad weather","isCorrect":false}]'::jsonb,
 null, 'The passage says the scenic view from the summit made every step worthwhile.'),
('Class 6', 'English', 'Reading Comprehension and Vocabulary', 'hard', 'mcq',
 'A word that means the opposite of ''transparent'' is:',
 '[{"text":"Clear","isCorrect":false},{"text":"Opaque","isCorrect":true},{"text":"Visible","isCorrect":false},{"text":"Bright","isCorrect":false}]'::jsonb,
 null, '''Opaque'' means not allowing light through, the opposite of ''transparent''.'),

-- Mathematics: Knowing Numbers, Whole Numbers and Integers
('Class 6', 'Mathematics', 'Knowing Numbers, Whole Numbers and Integers', 'easy', 'mcq',
 'Which of the following is the smallest whole number?',
 '[{"text":"-1","isCorrect":false},{"text":"0","isCorrect":true},{"text":"1","isCorrect":false},{"text":"There is no smallest whole number","isCorrect":false}]'::jsonb,
 null, 'The whole numbers begin at 0, so 0 is the smallest whole number.'),
('Class 6', 'Mathematics', 'Knowing Numbers, Whole Numbers and Integers', 'medium', 'mcq',
 'What is (-8) + 5?',
 '[{"text":"-3","isCorrect":true},{"text":"3","isCorrect":false},{"text":"-13","isCorrect":false},{"text":"13","isCorrect":false}]'::jsonb,
 null, '(-8) + 5 = -3, since we subtract the smaller absolute value from the larger and keep the sign of the larger.'),
('Class 6', 'Mathematics', 'Knowing Numbers, Whole Numbers and Integers', 'medium', 'mcq',
 'Which of these integers is greater: -7 or -2?',
 '[{"text":"-7","isCorrect":false},{"text":"-2","isCorrect":true},{"text":"They are equal","isCorrect":false},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'On the number line, -2 is to the right of -7, so -2 is greater.'),
('Class 6', 'Mathematics', 'Knowing Numbers, Whole Numbers and Integers', 'hard', 'mcq',
 'What is (-15) - (-9)?',
 '[{"text":"-24","isCorrect":false},{"text":"-6","isCorrect":true},{"text":"6","isCorrect":false},{"text":"24","isCorrect":false}]'::jsonb,
 null, 'Subtracting a negative is the same as adding its positive: (-15) - (-9) = (-15) + 9 = -6.'),

-- Mathematics: Fractions, Decimals and Basic Geometry
('Class 6', 'Mathematics', 'Fractions, Decimals and Basic Geometry', 'easy', 'mcq',
 'Which of these is an improper fraction?',
 '[{"text":"3/4","isCorrect":false},{"text":"7/5","isCorrect":true},{"text":"1/2","isCorrect":false},{"text":"2/9","isCorrect":false}]'::jsonb,
 null, 'An improper fraction has a numerator greater than or equal to its denominator. 7/5 fits this, since 7 > 5.'),
('Class 6', 'Mathematics', 'Fractions, Decimals and Basic Geometry', 'medium', 'mcq',
 'Add: 1/3 + 1/6 = ?',
 '[{"text":"1/2","isCorrect":true},{"text":"2/9","isCorrect":false},{"text":"1/9","isCorrect":false},{"text":"2/6","isCorrect":false}]'::jsonb,
 null, 'Converting to a common denominator: 2/6 + 1/6 = 3/6 = 1/2.'),
('Class 6', 'Mathematics', 'Fractions, Decimals and Basic Geometry', 'medium', 'mcq',
 'How many degrees are there in a right angle?',
 '[{"text":"45 degrees","isCorrect":false},{"text":"90 degrees","isCorrect":true},{"text":"180 degrees","isCorrect":false},{"text":"360 degrees","isCorrect":false}]'::jsonb,
 null, 'A right angle measures exactly 90 degrees.'),
('Class 6', 'Mathematics', 'Fractions, Decimals and Basic Geometry', 'hard', 'mcq',
 'What is 2.75 + 1.6 - 0.85?',
 '[{"text":"3.5","isCorrect":true},{"text":"3.4","isCorrect":false},{"text":"4.4","isCorrect":false},{"text":"3.6","isCorrect":false}]'::jsonb,
 null, 'First 2.75 + 1.6 = 4.35, then 4.35 - 0.85 = 3.5.'),

-- Science: Food, Materials and the Living World
('Class 6', 'Science', 'Food, Materials and the Living World', 'easy', 'mcq',
 'Which of these nutrients mainly helps in building and repairing our body?',
 '[{"text":"Carbohydrates","isCorrect":false},{"text":"Proteins","isCorrect":true},{"text":"Fats","isCorrect":false},{"text":"Vitamins","isCorrect":false}]'::jsonb,
 null, 'Proteins mainly help in building and repairing body tissues.'),
('Class 6', 'Science', 'Food, Materials and the Living World', 'medium', 'mcq',
 'Which of these materials is a good conductor of heat?',
 '[{"text":"Wood","isCorrect":false},{"text":"Plastic","isCorrect":false},{"text":"Copper","isCorrect":true},{"text":"Rubber","isCorrect":false}]'::jsonb,
 null, 'Copper is a metal and metals are generally good conductors of heat.'),
('Class 6', 'Science', 'Food, Materials and the Living World', 'medium', 'mcq',
 'Organisms that can survive both on land and in water are called:',
 '[{"text":"Terrestrial","isCorrect":false},{"text":"Aquatic","isCorrect":false},{"text":"Amphibious","isCorrect":true},{"text":"Aerial","isCorrect":false}]'::jsonb,
 null, 'Organisms that can live both on land and in water, like frogs, are called amphibious.'),
('Class 6', 'Science', 'Food, Materials and the Living World', 'hard', 'mcq',
 'The process by which plants prepare their own food using sunlight, water, and carbon dioxide is called:',
 '[{"text":"Respiration","isCorrect":false},{"text":"Photosynthesis","isCorrect":true},{"text":"Transpiration","isCorrect":false},{"text":"Digestion","isCorrect":false}]'::jsonb,
 null, 'Photosynthesis is the process by which plants use sunlight, water, and carbon dioxide to make their own food.'),

-- Science: Motion, Measurement, Light and Electricity
('Class 6', 'Science', 'Motion, Measurement, Light and Electricity', 'easy', 'mcq',
 'Which of these instruments is used to measure length accurately?',
 '[{"text":"Thermometer","isCorrect":false},{"text":"Measuring tape","isCorrect":true},{"text":"Stopwatch","isCorrect":false},{"text":"Weighing scale","isCorrect":false}]'::jsonb,
 null, 'A measuring tape is used to accurately measure length.'),
('Class 6', 'Science', 'Motion, Measurement, Light and Electricity', 'medium', 'mcq',
 'The motion of a swing is an example of:',
 '[{"text":"Rectilinear motion","isCorrect":false},{"text":"Circular motion","isCorrect":false},{"text":"Periodic (oscillatory) motion","isCorrect":true},{"text":"Random motion","isCorrect":false}]'::jsonb,
 null, 'A swing moves back and forth repeatedly, making its motion periodic or oscillatory.'),
('Class 6', 'Science', 'Motion, Measurement, Light and Electricity', 'medium', 'mcq',
 'Which of these materials would allow electricity to pass through it?',
 '[{"text":"Rubber","isCorrect":false},{"text":"Copper wire","isCorrect":true},{"text":"Wood","isCorrect":false},{"text":"Plastic","isCorrect":false}]'::jsonb,
 null, 'Copper is a metal and a good conductor of electricity.'),
('Class 6', 'Science', 'Motion, Measurement, Light and Electricity', 'hard', 'mcq',
 'A shadow is formed because light travels:',
 '[{"text":"In a curved path","isCorrect":false},{"text":"In a straight line","isCorrect":true},{"text":"In a zigzag path","isCorrect":false},{"text":"Only at night","isCorrect":false}]'::jsonb,
 null, 'Light travels in a straight line, so an opaque object blocks it and creates a shadow behind the object.'),

-- Social Science: History and Geography (Early India, Earth and Maps)
('Class 6', 'Social Science', 'History and Geography (Early India, Earth and Maps)', 'easy', 'mcq',
 'The Indus Valley Civilization flourished mainly along which river?',
 '[{"text":"Ganga","isCorrect":false},{"text":"Indus","isCorrect":true},{"text":"Godavari","isCorrect":false},{"text":"Narmada","isCorrect":false}]'::jsonb,
 null, 'The Indus Valley Civilization developed along the banks of the Indus river.'),
('Class 6', 'Social Science', 'History and Geography (Early India, Earth and Maps)', 'medium', 'mcq',
 'Which imaginary line divides the Earth into the Northern and Southern Hemispheres?',
 '[{"text":"Prime Meridian","isCorrect":false},{"text":"Equator","isCorrect":true},{"text":"Tropic of Cancer","isCorrect":false},{"text":"International Date Line","isCorrect":false}]'::jsonb,
 null, 'The Equator is the imaginary line that divides the Earth into the Northern and Southern Hemispheres.'),
('Class 6', 'Social Science', 'History and Geography (Early India, Earth and Maps)', 'medium', 'mcq',
 'The famous Great Bath, used for ritual bathing, was found at which Indus Valley site?',
 '[{"text":"Harappa","isCorrect":false},{"text":"Mohenjo-daro","isCorrect":true},{"text":"Lothal","isCorrect":false},{"text":"Dholavira","isCorrect":false}]'::jsonb,
 null, 'The Great Bath was discovered at Mohenjo-daro, one of the major cities of the Indus Valley Civilization.'),
('Class 6', 'Social Science', 'History and Geography (Early India, Earth and Maps)', 'hard', 'mcq',
 'Which of these is the largest continent on Earth?',
 '[{"text":"Africa","isCorrect":false},{"text":"Asia","isCorrect":true},{"text":"Europe","isCorrect":false},{"text":"Australia","isCorrect":false}]'::jsonb,
 null, 'Asia is the largest continent on Earth by both area and population.'),

-- Social Science: Civics (Government, Diversity and Local Bodies)
('Class 6', 'Social Science', 'Civics (Government, Diversity and Local Bodies)', 'easy', 'mcq',
 'India is often described as a country of great diversity because it has people of many different:',
 '[{"text":"Religions, languages and cultures","isCorrect":true},{"text":"Only one religion","isCorrect":false},{"text":"Only one language","isCorrect":false},{"text":"Only one culture","isCorrect":false}]'::jsonb,
 null, 'India has people following many different religions, speaking many languages, and following many cultures, making it diverse.'),
('Class 6', 'Social Science', 'Civics (Government, Diversity and Local Bodies)', 'medium', 'mcq',
 'What type of government does India have?',
 '[{"text":"Monarchy","isCorrect":false},{"text":"Democracy","isCorrect":true},{"text":"Dictatorship","isCorrect":false},{"text":"Military rule","isCorrect":false}]'::jsonb,
 null, 'India is a democracy, where the government is elected by the people.'),
('Class 6', 'Social Science', 'Civics (Government, Diversity and Local Bodies)', 'medium', 'mcq',
 'The local government body that manages a village''s affairs is called a:',
 '[{"text":"Municipal Corporation","isCorrect":false},{"text":"Gram Panchayat","isCorrect":true},{"text":"Parliament","isCorrect":false},{"text":"Assembly","isCorrect":false}]'::jsonb,
 null, 'A Gram Panchayat is the local self-government body that manages a village''s affairs.'),
('Class 6', 'Social Science', 'Civics (Government, Diversity and Local Bodies)', 'hard', 'mcq',
 'The right that allows all adult citizens of India, regardless of religion, caste, or gender, to vote is called:',
 '[{"text":"Universal adult franchise","isCorrect":true},{"text":"Selective voting","isCorrect":false},{"text":"Restricted suffrage","isCorrect":false},{"text":"Class-based voting","isCorrect":false}]'::jsonb,
 null, 'Universal adult franchise gives all adult citizens the right to vote regardless of religion, caste, or gender.');
