-- supabase/sql/exam_question_bank_class3_set1.sql
--
-- First curated question-bank batch for 'Class 3' (see exam_patterns_class3.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 3's MCQ-only,
-- no-negative-marking pattern. 9 chapters (3 per subject x 3 subjects) each get 4 questions, mostly
-- easy with a couple of medium, reflecting the easy-skewed weightage in exam_patterns_class3.sql.
-- Pitched one notch above Class 2 (see exam_question_bank_class2_set1.sql) -- multiplication
-- tables, 4-digit numbers, and slightly broader EVS topics.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class3.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Nouns (Common, Proper, Collective) and Pronouns
('Class 3', 'English', 'Nouns (Common, Proper, Collective) and Pronouns', 'easy', 'mcq',
 'Which of the following is a proper noun?',
 '[{"text":"city","isCorrect":false},{"text":"Delhi","isCorrect":true},{"text":"river","isCorrect":false},{"text":"boy","isCorrect":false}]'::jsonb,
 null, 'A proper noun names a specific person, place, or thing and starts with a capital letter. ''Delhi'' is a specific city.'),
('Class 3', 'English', 'Nouns (Common, Proper, Collective) and Pronouns', 'easy', 'mcq',
 'What is the collective noun for a group of cows?',
 '[{"text":"Flock","isCorrect":false},{"text":"Herd","isCorrect":true},{"text":"Pack","isCorrect":false},{"text":"Swarm","isCorrect":false}]'::jsonb,
 null, 'A group of cows is called a ''herd''.'),
('Class 3', 'English', 'Nouns (Common, Proper, Collective) and Pronouns', 'easy', 'mcq',
 'Choose the correct pronoun: "___ is my best friend."',
 '[{"text":"Him","isCorrect":false},{"text":"She","isCorrect":true},{"text":"Her","isCorrect":false},{"text":"Them","isCorrect":false}]'::jsonb,
 null, '''She'' is used as the subject of a sentence, so it correctly fits before ''is my best friend''.'),
('Class 3', 'English', 'Nouns (Common, Proper, Collective) and Pronouns', 'medium', 'mcq',
 'What is the collective noun for a group of fish?',
 '[{"text":"Shoal","isCorrect":true},{"text":"Herd","isCorrect":false},{"text":"Litter","isCorrect":false},{"text":"Bunch","isCorrect":false}]'::jsonb,
 null, 'A group of fish is called a ''shoal''.'),

-- English: Adjectives, Rhyming Words and Opposites
('Class 3', 'English', 'Adjectives, Rhyming Words and Opposites', 'easy', 'mcq',
 'Which word describes the size of an object, making it an adjective?',
 '[{"text":"Run","isCorrect":false},{"text":"Big","isCorrect":true},{"text":"Table","isCorrect":false},{"text":"Sing","isCorrect":false}]'::jsonb,
 null, '''Big'' describes the size of a noun, making it an adjective.'),
('Class 3', 'English', 'Adjectives, Rhyming Words and Opposites', 'easy', 'mcq',
 'Which word rhymes with ''CHAIR''?',
 '[{"text":"Chalk","isCorrect":false},{"text":"Bear","isCorrect":true},{"text":"Chart","isCorrect":false},{"text":"Cheer","isCorrect":false}]'::jsonb,
 null, '''Bear'' rhymes with ''Chair'' because they both end with the same ''-air/-ear'' sound.'),
('Class 3', 'English', 'Adjectives, Rhyming Words and Opposites', 'easy', 'mcq',
 'What is the opposite of ''BRAVE''?',
 '[{"text":"Strong","isCorrect":false},{"text":"Afraid","isCorrect":true},{"text":"Kind","isCorrect":false},{"text":"Bold","isCorrect":false}]'::jsonb,
 null, 'The opposite of ''Brave'' is ''Afraid''.'),
('Class 3', 'English', 'Adjectives, Rhyming Words and Opposites', 'medium', 'mcq',
 'In the sentence "The tall boy ran quickly," which word is the adjective?',
 '[{"text":"Boy","isCorrect":false},{"text":"Tall","isCorrect":true},{"text":"Ran","isCorrect":false},{"text":"Quickly","isCorrect":false}]'::jsonb,
 null, '''Tall'' describes the noun ''boy'', making it the adjective in the sentence.'),

-- English: Reading Comprehension and Vocabulary
('Class 3', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'Read: "Aryan has a pet parrot. It can say ''hello'' and ''good morning''." What pet does Aryan have?',
 '[{"text":"A dog","isCorrect":false},{"text":"A parrot","isCorrect":true},{"text":"A cat","isCorrect":false},{"text":"A rabbit","isCorrect":false}]'::jsonb,
 null, 'The passage says Aryan has a pet parrot.'),
('Class 3', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'A word that means the same as ''happy'' is:',
 '[{"text":"Sad","isCorrect":false},{"text":"Glad","isCorrect":true},{"text":"Angry","isCorrect":false},{"text":"Tired","isCorrect":false}]'::jsonb,
 null, '''Glad'' means the same as ''happy''.'),
('Class 3', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'Read: "The farmer wakes up at dawn to water his crops before the sun gets too hot." Why does the farmer wake up at dawn?',
 '[{"text":"To water crops before it gets too hot","isCorrect":true},{"text":"To sleep more","isCorrect":false},{"text":"To watch television","isCorrect":false},{"text":"To go to school","isCorrect":false}]'::jsonb,
 null, 'The passage explains that the farmer wakes up at dawn to water his crops before the sun gets too hot.'),
('Class 3', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'A group of words that gives a complete meaning is called a:',
 '[{"text":"Letter","isCorrect":false},{"text":"Sentence","isCorrect":true},{"text":"Syllable","isCorrect":false},{"text":"Alphabet","isCorrect":false}]'::jsonb,
 null, 'A sentence is a group of words that together gives a complete meaning.'),

-- Mathematics: Numbers up to 10000 (Place Value, Before-After-Between)
('Class 3', 'Mathematics', 'Numbers up to 10000 (Place Value, Before-After-Between)', 'easy', 'mcq',
 'What number comes just after 2999?',
 '[{"text":"2998","isCorrect":false},{"text":"3000","isCorrect":true},{"text":"3001","isCorrect":false},{"text":"3009","isCorrect":false}]'::jsonb,
 null, 'Counting up from 2999, the next number is 3000.'),
('Class 3', 'Mathematics', 'Numbers up to 10000 (Place Value, Before-After-Between)', 'easy', 'mcq',
 'What number comes just before 5000?',
 '[{"text":"4999","isCorrect":true},{"text":"5001","isCorrect":false},{"text":"4990","isCorrect":false},{"text":"5010","isCorrect":false}]'::jsonb,
 null, 'Counting down from 5000, the number right before it is 4999.'),
('Class 3', 'Mathematics', 'Numbers up to 10000 (Place Value, Before-After-Between)', 'medium', 'mcq',
 'In the number 7328, what is the digit in the thousands place?',
 '[{"text":"7","isCorrect":true},{"text":"3","isCorrect":false},{"text":"2","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'In 7328, 7 is in the thousands place, 3 in the hundreds, 2 in the tens, and 8 in the ones place.'),
('Class 3', 'Mathematics', 'Numbers up to 10000 (Place Value, Before-After-Between)', 'medium', 'mcq',
 'Which number is between 6499 and 6501?',
 '[{"text":"6498","isCorrect":false},{"text":"6500","isCorrect":true},{"text":"6502","isCorrect":false},{"text":"6510","isCorrect":false}]'::jsonb,
 null, '6500 comes right between 6499 and 6501 when counting in order.'),

-- Mathematics: Addition, Subtraction and Multiplication Tables
('Class 3', 'Mathematics', 'Addition, Subtraction and Multiplication Tables', 'easy', 'mcq',
 '6 x 7 = ?',
 '[{"text":"36","isCorrect":false},{"text":"42","isCorrect":true},{"text":"48","isCorrect":false},{"text":"49","isCorrect":false}]'::jsonb,
 null, '6 x 7 = 42.'),
('Class 3', 'Mathematics', 'Addition, Subtraction and Multiplication Tables', 'easy', 'mcq',
 '1250 + 375 = ?',
 '[{"text":"1525","isCorrect":false},{"text":"1625","isCorrect":true},{"text":"1615","isCorrect":false},{"text":"1725","isCorrect":false}]'::jsonb,
 null, '1250 + 375 = 1625.'),
('Class 3', 'Mathematics', 'Addition, Subtraction and Multiplication Tables', 'easy', 'mcq',
 '9 x 8 = ?',
 '[{"text":"63","isCorrect":false},{"text":"72","isCorrect":true},{"text":"81","isCorrect":false},{"text":"64","isCorrect":false}]'::jsonb,
 null, '9 x 8 = 72.'),
('Class 3', 'Mathematics', 'Addition, Subtraction and Multiplication Tables', 'medium', 'mcq',
 '2000 - 350 + 150 = ?',
 '[{"text":"1800","isCorrect":true},{"text":"1700","isCorrect":false},{"text":"1900","isCorrect":false},{"text":"1600","isCorrect":false}]'::jsonb,
 null, 'First 2000 - 350 = 1650, then 1650 + 150 = 1800.'),

-- Mathematics: Shapes, Measurement, Time and Money
('Class 3', 'Mathematics', 'Shapes, Measurement, Time and Money', 'easy', 'mcq',
 'How many sides does a pentagon have?',
 '[{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"7","isCorrect":false}]'::jsonb,
 null, 'A pentagon has 5 sides.'),
('Class 3', 'Mathematics', 'Shapes, Measurement, Time and Money', 'easy', 'mcq',
 'How many days are there in the month of April?',
 '[{"text":"28","isCorrect":false},{"text":"30","isCorrect":true},{"text":"31","isCorrect":false},{"text":"29","isCorrect":false}]'::jsonb,
 null, 'April has 30 days.'),
('Class 3', 'Mathematics', 'Shapes, Measurement, Time and Money', 'easy', 'mcq',
 'How many rupees make one hundred paise?',
 '[{"text":"1","isCorrect":true},{"text":"10","isCorrect":false},{"text":"100","isCorrect":false},{"text":"50","isCorrect":false}]'::jsonb,
 null, '100 paise make 1 rupee.'),
('Class 3', 'Mathematics', 'Shapes, Measurement, Time and Money', 'medium', 'mcq',
 'If a clock shows 3:30, how many minutes are left until 4:00?',
 '[{"text":"20","isCorrect":false},{"text":"25","isCorrect":false},{"text":"30","isCorrect":true},{"text":"35","isCorrect":false}]'::jsonb,
 null, 'From 3:30 to 4:00 is 30 minutes.'),

-- EVS: Our Body, Food and Family
('Class 3', 'EVS', 'Our Body, Food and Family', 'easy', 'mcq',
 'Which organ in our body pumps blood?',
 '[{"text":"Lungs","isCorrect":false},{"text":"Heart","isCorrect":true},{"text":"Stomach","isCorrect":false},{"text":"Brain","isCorrect":false}]'::jsonb,
 null, 'The heart pumps blood throughout the body.'),
('Class 3', 'EVS', 'Our Body, Food and Family', 'easy', 'mcq',
 'Which of these foods gives us the most protein?',
 '[{"text":"Rice","isCorrect":false},{"text":"Lentils (dal)","isCorrect":true},{"text":"Sugar","isCorrect":false},{"text":"Butter","isCorrect":false}]'::jsonb,
 null, 'Lentils (dal) are a good source of protein.'),
('Class 3', 'EVS', 'Our Body, Food and Family', 'easy', 'mcq',
 'What do we call the children of your aunt or uncle?',
 '[{"text":"Siblings","isCorrect":false},{"text":"Cousins","isCorrect":true},{"text":"Nephews","isCorrect":false},{"text":"Grandchildren","isCorrect":false}]'::jsonb,
 null, 'The children of your aunt or uncle are called your cousins.'),
('Class 3', 'EVS', 'Our Body, Food and Family', 'medium', 'mcq',
 'Which organ helps us to breathe?',
 '[{"text":"Lungs","isCorrect":true},{"text":"Heart","isCorrect":false},{"text":"Kidney","isCorrect":false},{"text":"Liver","isCorrect":false}]'::jsonb,
 null, 'The lungs help us breathe by taking in oxygen and releasing carbon dioxide.'),

-- EVS: Plants, Animals and Habitats
('Class 3', 'EVS', 'Plants, Animals and Habitats', 'easy', 'mcq',
 'Where does a polar bear naturally live?',
 '[{"text":"Desert","isCorrect":false},{"text":"Cold, icy regions","isCorrect":true},{"text":"Rainforest","isCorrect":false},{"text":"Ocean floor","isCorrect":false}]'::jsonb,
 null, 'Polar bears live in cold, icy regions like the Arctic.'),
('Class 3', 'EVS', 'Plants, Animals and Habitats', 'easy', 'mcq',
 'Plants that store water in their thick stems and live in deserts are called:',
 '[{"text":"Ferns","isCorrect":false},{"text":"Cactus","isCorrect":true},{"text":"Moss","isCorrect":false},{"text":"Algae","isCorrect":false}]'::jsonb,
 null, 'Cactus plants store water in their thick stems, which helps them survive in deserts.'),
('Class 3', 'EVS', 'Plants, Animals and Habitats', 'easy', 'mcq',
 'Animals that eat only plants are called:',
 '[{"text":"Carnivores","isCorrect":false},{"text":"Herbivores","isCorrect":true},{"text":"Omnivores","isCorrect":false},{"text":"Predators","isCorrect":false}]'::jsonb,
 null, 'Animals that eat only plants are called herbivores.'),
('Class 3', 'EVS', 'Plants, Animals and Habitats', 'medium', 'mcq',
 'Animals that eat both plants and other animals are called:',
 '[{"text":"Herbivores","isCorrect":false},{"text":"Carnivores","isCorrect":false},{"text":"Omnivores","isCorrect":true},{"text":"Scavengers","isCorrect":false}]'::jsonb,
 null, 'Animals that eat both plants and other animals are called omnivores.'),

-- EVS: Our Community, Transport and Communication
('Class 3', 'EVS', 'Our Community, Transport and Communication', 'easy', 'mcq',
 'Who is responsible for maintaining law and order in our society?',
 '[{"text":"Police","isCorrect":true},{"text":"Postman","isCorrect":false},{"text":"Farmer","isCorrect":false},{"text":"Tailor","isCorrect":false}]'::jsonb,
 null, 'The police are responsible for maintaining law and order.'),
('Class 3', 'EVS', 'Our Community, Transport and Communication', 'easy', 'mcq',
 'Which of these is the fastest means of long-distance transport?',
 '[{"text":"Bicycle","isCorrect":false},{"text":"Bus","isCorrect":false},{"text":"Airplane","isCorrect":true},{"text":"Bullock cart","isCorrect":false}]'::jsonb,
 null, 'An airplane is the fastest means of long-distance transport among the options given.'),
('Class 3', 'EVS', 'Our Community, Transport and Communication', 'easy', 'mcq',
 'Which of these is a means of communication?',
 '[{"text":"Telephone","isCorrect":true},{"text":"Bicycle","isCorrect":false},{"text":"Umbrella","isCorrect":false},{"text":"Spoon","isCorrect":false}]'::jsonb,
 null, 'A telephone is used to communicate with people, making it a means of communication.'),
('Class 3', 'EVS', 'Our Community, Transport and Communication', 'medium', 'mcq',
 'Sending a message electronically using the internet is called:',
 '[{"text":"A letter","isCorrect":false},{"text":"An email","isCorrect":true},{"text":"A telegram","isCorrect":false},{"text":"A newspaper","isCorrect":false}]'::jsonb,
 null, 'A message sent electronically over the internet is called an email.');
