-- supabase/sql/exam_question_bank_set3.sql
--
-- Third curated batch for JEE Main, on top of Set 1 (exam_question_bank.sql) and Set 2
-- (exam_question_bank_set2.sql) — same table, same schema, nothing new to migrate. All-new
-- question content again (not duplicates of Set 1/Set 2), continuing to weave LaTeX notation
-- into question text and include one genuine multi-correct "which of the following statement(s)
-- is/are true" MCQ per chapter (still format='mcq' with more than one option marked isCorrect —
-- see exam_question_bank_set2.sql's header for why no schema change is needed for that).
--
-- Run this once in the Supabase SQL Editor, after exam_question_bank.sql and
-- exam_question_bank_set2.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'easy', 'mcq',
 'A ball is thrown vertically upward with speed $u=20$ m/s ($g=10$ m/s^2). Find the maximum height reached.',
 '[{"text":"10 m","isCorrect":false},{"text":"20 m","isCorrect":true},{"text":"30 m","isCorrect":false},{"text":"40 m","isCorrect":false}]'::jsonb,
 null, 'Maximum height = u^2/(2g) = 400/20 = 20 m.'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'mcq',
 'A 5 kg block rests on a rough horizontal surface with coefficient of friction 0.4 ($g=10$ m/s^2). A horizontal force of 15 N is applied. Which of the following statement(s) is/are TRUE? (A) The block remains stationary. (B) The friction force acting on the block is 15 N. (C) The block accelerates at 3 m/s^2. (D) The maximum possible static friction is 20 N.',
 '[{"text":"(A) Block remains stationary","isCorrect":true},{"text":"(B) Friction force is 15 N","isCorrect":true},{"text":"(C) Block accelerates at 3 m/s^2","isCorrect":false},{"text":"(D) Max static friction is 20 N","isCorrect":true}]'::jsonb,
 null, 'Maximum static friction = 0.4*5*10 = 20 N. Since the applied 15 N is less than this maximum, the block stays at rest (A true), and static friction adjusts to exactly balance the applied force, i.e. 15 N, not its maximum value (B true, D true). Since the block does not move, it does not accelerate at all (C false).'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'numerical',
 'A 2 kg body moving at 10 m/s comes to rest in 0.5 s after a collision. Find the average force (in N) acting on it, using $F=\Delta p/\Delta t$.',
 null, '40', 'Change in momentum = 2*10 = 20 kg m/s. Average force = 20/0.5 = 40 N.'),
('JEE Main', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'descriptive',
 'State Newton''s third law and clarify a common misconception about action-reaction pairs.',
 null, null, 'Newton''s third law states that every action force has an equal and opposite reaction force, acting on the OTHER body involved, not on the same body. A common misconception is thinking these two forces cancel out -- they cannot, since they act on two different objects, not the same one.'),

-- Physics: Electrodynamics
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'easy', 'mcq',
 'Three resistors of $2\,\Omega$, $4\,\Omega$, and $4\,\Omega$ are connected in parallel. Find the equivalent resistance.',
 '[{"text":"0.5 ohm","isCorrect":false},{"text":"1 ohm","isCorrect":true},{"text":"2 ohm","isCorrect":false},{"text":"10 ohm","isCorrect":false}]'::jsonb,
 null, '1/R = 1/2 + 1/4 + 1/4 = 1, so R = 1 ohm.'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'mcq',
 'A long solenoid carries a steady current. Which of the following statement(s) is/are TRUE? (A) The magnetic field inside is approximately uniform, away from the ends. (B) The magnetic field just outside the solenoid is approximately zero. (C) The field strength depends on the number of turns per unit length. (D) The field is strongest at the very ends of the solenoid.',
 '[{"text":"(A) Uniform field inside, away from ends","isCorrect":true},{"text":"(B) Field outside is approximately zero","isCorrect":true},{"text":"(C) Depends on turns per unit length","isCorrect":true},{"text":"(D) Strongest at the very ends","isCorrect":false}]'::jsonb,
 null, 'For a long solenoid, the interior field (away from the ends) is uniform and given by B = mu0 * n * I, so it depends on turns per unit length n (A, C true), and the field just outside is approximately zero (B true). The field AT the ends is actually about half the interior value, not stronger (D false).'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'numerical',
 'A straight wire carries a current of 5 A perpendicular to a magnetic field of 0.2 T, over a length of 0.4 m. Find the force on the wire (in N), using $F=BIL$.',
 null, '0.4', 'F = 0.2 * 5 * 0.4 = 0.4 N.'),
('JEE Main', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'descriptive',
 'Explain the right-hand rule for finding the direction of the magnetic force on a moving positive charge in a magnetic field.',
 null, null, 'Point the fingers of the right hand in the direction of the charge''s velocity, then curl them toward the direction of the magnetic field; the thumb then points in the direction of the force. Equivalently, the force equals q times v cross B, and its direction follows the right-hand rule for that cross product.'),

-- Physics: Modern Physics
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'easy', 'mcq',
 'The de Broglie wavelength of a particle is inversely proportional to its:',
 '[{"text":"Charge","isCorrect":false},{"text":"Momentum","isCorrect":true},{"text":"Mass alone","isCorrect":false},{"text":"Energy directly","isCorrect":false}]'::jsonb,
 null, 'The de Broglie wavelength is given by lambda = h/p, so it is inversely proportional to momentum p.'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'mcq',
 'Regarding nuclear fission and fusion, which of the following statement(s) is/are TRUE? (A) Fission splits a heavy nucleus into lighter fragments. (B) Fusion combines light nuclei into a heavier nucleus. (C) Both release energy because the products have higher binding energy per nucleon than the reactants. (D) Fusion reactions require lower temperatures than fission reactions to initiate.',
 '[{"text":"(A) Fission splits heavy nucleus","isCorrect":true},{"text":"(B) Fusion combines light nuclei","isCorrect":true},{"text":"(C) Both release energy via higher binding energy per nucleon","isCorrect":true},{"text":"(D) Fusion needs lower temperature than fission","isCorrect":false}]'::jsonb,
 null, 'Fission splits heavy nuclei (A true) and fusion combines light nuclei (B true); both processes move toward more stable products with higher binding energy per nucleon, releasing energy (C true). Fusion actually requires much HIGHER temperatures than fission to overcome the strong Coulomb repulsion between nuclei, not lower (D false).'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'numerical',
 'Find the energy (in eV) of a photon with wavelength 620 nm, using $E=\frac{hc}{\lambda}$ with $hc=1240$ eV nm.',
 null, '2', 'E = 1240/620 = 2 eV.'),
('JEE Main', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'descriptive',
 'Explain what a "half-life" represents statistically for a radioactive sample, and why it is independent of the sample''s initial size.',
 null, null, 'Half-life is the time in which, on average, half of the radioactive nuclei present decay -- it reflects a constant per-nucleus probability of decay per unit time. Since every nucleus decays independently with that same probability regardless of how many are present, the fractional decay rate -- and hence the half-life -- does not depend on the initial number of nuclei.'),

-- Physics: Heat and Thermodynamics
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'easy', 'mcq',
 'Convert $100^\circ C$ to Kelvin.',
 '[{"text":"273 K","isCorrect":false},{"text":"373 K","isCorrect":true},{"text":"473 K","isCorrect":false},{"text":"100 K","isCorrect":false}]'::jsonb,
 null, 'K = C + 273 = 100 + 273 = 373 K.'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'hard', 'mcq',
 'For a complete cyclic process undergone by an ideal gas, which of the following statement(s) is/are TRUE? (A) The net change in internal energy over one cycle is zero. (B) The net heat absorbed equals the net work done by the gas. (C) The change in entropy of the gas over one complete cycle is always positive. (D) The area enclosed by the cycle on a P-V diagram equals the net work done.',
 '[{"text":"(A) Net change in internal energy is zero","isCorrect":true},{"text":"(B) Net heat absorbed equals net work done","isCorrect":true},{"text":"(C) Entropy change of the gas is always positive","isCorrect":false},{"text":"(D) Enclosed P-V area equals net work done","isCorrect":true}]'::jsonb,
 null, 'Internal energy and entropy are both state functions, so both return to their starting value after a complete cycle: internal energy change is zero (A true), and the gas''s OWN entropy change is exactly zero over a cycle, not always positive (C false). Since dU=0, the first law gives net heat absorbed equal to net work done (B true), and this net work equals the enclosed area on a P-V diagram (D true).'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'medium', 'numerical',
 '2 moles of an ideal gas at 300 K are heated at constant pressure to 400 K. Find the work done by the gas (in J), using $W=nR\Delta T$ ($R=8.31$ J/mol K).',
 null, '1662', 'W = 2 * 8.31 * 100 = 1662 J.'),
('JEE Main', 'Physics', 'Heat and Thermodynamics', 'medium', 'descriptive',
 'Explain the difference between an isothermal and an adiabatic process for an ideal gas, in terms of what stays constant and what happens to heat.',
 null, null, 'In an isothermal process, temperature stays constant, and heat is exchanged with the surroundings to keep it so. In an adiabatic process, no heat is exchanged with the surroundings at all, so temperature necessarily changes as the gas does work.'),

-- Physics: Optics
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'easy', 'mcq',
 'For a real object, a concave (diverging) lens always forms an image that is:',
 '[{"text":"Real and inverted","isCorrect":false},{"text":"Virtual and erect","isCorrect":true},{"text":"Real and erect","isCorrect":false},{"text":"Virtual and inverted","isCorrect":false}]'::jsonb,
 null, 'A diverging (concave) lens always forms a virtual, erect, diminished image of a real object.'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'hard', 'mcq',
 'Regarding a compound microscope, which of the following statement(s) is/are TRUE? (A) The objective lens forms a real, inverted, magnified image. (B) The eyepiece acts as a simple magnifier for the image formed by the objective. (C) The final image seen by the eye is virtual. (D) Both lenses used are concave.',
 '[{"text":"(A) Objective forms real, inverted, magnified image","isCorrect":true},{"text":"(B) Eyepiece acts as simple magnifier","isCorrect":true},{"text":"(C) Final image is virtual","isCorrect":true},{"text":"(D) Both lenses are concave","isCorrect":false}]'::jsonb,
 null, 'In a compound microscope, the objective forms a real, inverted, magnified image of the object (A true), which the eyepiece then magnifies further as a simple magnifier (B true), producing a final virtual image (C true). Both lenses used are actually convex (converging), not concave (D false).'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'hard', 'numerical',
 'A double convex lens has radii of curvature 20 cm and 20 cm and refractive index 1.5. Find its focal length (in cm), using $\frac{1}{f}=(n-1)\left(\frac{1}{R_1}-\frac{1}{R_2}\right)$ with $R_1=20$, $R_2=-20$.',
 null, '20', '1/f = 0.5 * (1/20 - (-1/20)) = 0.5 * (2/20) = 0.05, so f = 20 cm.'),
('JEE Main', 'Physics', 'Optics (Ray and Wave)', 'medium', 'descriptive',
 'Explain why a rainbow forms, referencing both refraction and dispersion.',
 null, null, 'Sunlight entering a raindrop is refracted, reflected internally off the back of the drop, and refracted again on exiting. Since different wavelengths (colors) refract by slightly different amounts (dispersion), they separate and exit at slightly different angles, producing the familiar band of colors seen as a rainbow.'),

-- Physics: Waves and Oscillations
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'mcq',
 'For small oscillations, the time period of a simple pendulum depends on:',
 '[{"text":"Its mass","isCorrect":false},{"text":"Its length","isCorrect":true},{"text":"The material of the bob","isCorrect":false},{"text":"The color of the bob","isCorrect":false}]'::jsonb,
 null, 'For small oscillations, the period T = 2*pi*sqrt(L/g) depends only on the pendulum''s length and g, not on the bob''s mass, material, or color.'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'hard', 'mcq',
 'For a wave described by $y=A\sin(kx-\omega t)$, which of the following statement(s) is/are TRUE? (A) The wave travels in the positive x-direction. (B) The wave speed is $\omega/k$. (C) The wavelength is $2\pi/k$. (D) The wave''s amplitude decreases with time.',
 '[{"text":"(A) Travels in positive x-direction","isCorrect":true},{"text":"(B) Wave speed is omega/k","isCorrect":true},{"text":"(C) Wavelength is 2pi/k","isCorrect":true},{"text":"(D) Amplitude decreases with time","isCorrect":false}]'::jsonb,
 null, 'The form sin(kx - omega t) is a function of (x - vt) with v = omega/k, so the wave travels in the positive x-direction at speed omega/k (A, B true), and its wavelength is 2*pi/k by definition of the wave number k (C true). The amplitude A is a fixed constant here, not decreasing with time (D false).'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'numerical',
 'A sound wave has frequency 340 Hz and travels at 340 m/s. Find its wavelength (in m).',
 null, '1', 'Wavelength = speed / frequency = 340/340 = 1 m.'),
('JEE Main', 'Physics', 'Waves and Oscillations', 'easy', 'descriptive',
 'Explain what resonance is and give one everyday example.',
 null, null, 'Resonance occurs when a system is driven at its own natural frequency, causing the amplitude of oscillation to grow much larger than it would at other driving frequencies. Example: pushing a swing at the same rate as its natural back-and-forth frequency makes it swing higher and higher.'),

-- Physics: Properties of Matter and Fluids
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'easy', 'mcq',
 'The pressure at depth $h$ in a fluid of density $\rho$, with surface pressure $P_0$, is given by:',
 '[{"text":"P0 + rho g h","isCorrect":true},{"text":"P0 - rho g h","isCorrect":false},{"text":"rho g h","isCorrect":false},{"text":"P0 times rho g h","isCorrect":false}]'::jsonb,
 null, 'Pressure increases with depth in a fluid according to P = P0 + rho*g*h.'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'medium', 'mcq',
 'Regarding Archimedes'' principle, which of the following statement(s) is/are TRUE? (A) The buoyant force equals the weight of fluid displaced by the submerged object. (B) An object floats if its average density is less than the fluid''s density. (C) The buoyant force acts downward. (D) A fully submerged object experiences the same buoyant force regardless of how deep it is.',
 '[{"text":"(A) Buoyant force equals weight of displaced fluid","isCorrect":true},{"text":"(B) Floats if average density less than fluid","isCorrect":true},{"text":"(C) Buoyant force acts downward","isCorrect":false},{"text":"(D) Same buoyant force regardless of depth","isCorrect":true}]'::jsonb,
 null, 'The buoyant force equals the weight of displaced fluid (A true), so an object floats when its average density is less than the fluid''s (B true). This force acts upward, opposing gravity, not downward (C false). Since a fully submerged object always displaces its own full volume regardless of depth, the buoyant force stays the same at any depth (D true).'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'easy', 'numerical',
 'An object of volume 0.002 m^3 is fully submerged in water (density 1000 kg/m^3, $g=10$ m/s^2). Find the buoyant force (in N).',
 null, '20', 'Buoyant force = rho * V * g = 1000 * 0.002 * 10 = 20 N.'),
('JEE Main', 'Physics', 'Properties of Matter and Fluids', 'medium', 'descriptive',
 'Explain what viscosity is and how it affects the terminal velocity of a small sphere falling through a fluid.',
 null, null, 'Viscosity is a fluid''s internal resistance to flow, arising from friction between adjacent layers of fluid. A higher viscosity means a larger viscous drag force on a falling sphere at a given speed, so the sphere reaches terminal velocity -- where drag plus buoyancy balance weight -- at a lower speed.'),

-- Chemistry: Physical Chemistry
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'easy', 'mcq',
 'Find the number of moles of oxygen atoms in 1 mole of $CO_2$.',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"3","isCorrect":false},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'Each CO2 molecule has 2 oxygen atoms, so 1 mole of CO2 contains 2 moles of oxygen atoms.'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'hard', 'mcq',
 'For a first-order reaction, which of the following statement(s) is/are TRUE? (A) The half-life is independent of the initial concentration. (B) A plot of ln[A] versus time is a straight line. (C) The rate is proportional to the square of the concentration. (D) The rate constant has units of (time)^-1.',
 '[{"text":"(A) Half-life independent of initial concentration","isCorrect":true},{"text":"(B) ln[A] vs time is a straight line","isCorrect":true},{"text":"(C) Rate proportional to concentration squared","isCorrect":false},{"text":"(D) Rate constant has units of (time)^-1","isCorrect":true}]'::jsonb,
 null, 'For a first-order reaction, half-life = ln(2)/k does not depend on initial concentration (A true), and integrating the rate law gives ln[A] = ln[A]0 - kt, a straight line versus time (B true). The rate is proportional to concentration itself (first order), not its square (C false). The rate constant k has units of inverse time for a first-order reaction (D true).'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'easy', 'numerical',
 'A solution has $[H^+]=10^{-3}$ M. Find its pH.',
 null, '3', 'pH = -log10(10^-3) = 3.'),
('JEE Main', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'descriptive',
 'Explain what a buffer solution is and how it resists changes in pH.',
 null, null, 'A buffer solution contains a weak acid and its conjugate base (or a weak base and its conjugate acid) in comparable amounts. Added acid is neutralized by the conjugate base component, and added base is neutralized by the weak acid component, so the pH changes only slightly.'),

-- Chemistry: Organic Chemistry
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'easy', 'mcq',
 'Which of the following is an example of a nucleophile?',
 '[{"text":"H+","isCorrect":false},{"text":"OH-","isCorrect":true},{"text":"NO2+","isCorrect":false},{"text":"BF3","isCorrect":false}]'::jsonb,
 null, 'OH- is electron-rich and donates an electron pair, making it a nucleophile; the others are all electron-poor electrophiles/Lewis acids.'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'mcq',
 'Regarding SN1 and SN2 nucleophilic substitution reactions, which of the following statement(s) is/are TRUE? (A) SN2 proceeds via a single concerted step with backside attack. (B) SN1 proceeds through a carbocation intermediate. (C) SN1 reactions are favored by tertiary substrates. (D) The SN2 reaction rate depends only on substrate concentration, not the nucleophile.',
 '[{"text":"(A) SN2 is a concerted backside attack","isCorrect":true},{"text":"(B) SN1 goes through a carbocation","isCorrect":true},{"text":"(C) SN1 favored by tertiary substrates","isCorrect":true},{"text":"(D) SN2 rate depends only on substrate","isCorrect":false}]'::jsonb,
 null, 'SN2 is a single concerted step where the nucleophile attacks from the opposite side of the leaving group (A true). SN1 proceeds through a carbocation intermediate, which is more stable for tertiary substrates, favoring SN1 there (B, C true). The SN2 rate depends on BOTH the substrate and nucleophile concentrations, not the substrate alone (D false).'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'numerical',
 'How many sigma bonds are present in ethane ($C_2H_6$)?',
 null, '7', 'Ethane has one C-C sigma bond plus six C-H sigma bonds, giving 7 sigma bonds total (no pi bonds).'),
('JEE Main', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'descriptive',
 'Explain what a racemic mixture is and why it is optically inactive.',
 null, null, 'A racemic mixture contains equal amounts of both enantiomers (mirror-image forms) of a chiral compound. Since one enantiomer rotates plane-polarized light clockwise and the other rotates it counterclockwise by an equal amount, their rotations cancel out, making the mixture optically inactive overall.'),

-- Chemistry: Inorganic Chemistry
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'easy', 'mcq',
 'Between sodium (Na) and chlorine (Cl), both in Period 3, which has the larger atomic radius?',
 '[{"text":"Na","isCorrect":true},{"text":"Cl","isCorrect":false},{"text":"They are equal","isCorrect":false},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'Atomic radius decreases across a period from left to right, so Na (further left) has a larger atomic radius than Cl.'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'mcq',
 'Regarding coordination compounds, which of the following statement(s) is/are TRUE? (A) The coordination number is the number of donor atoms bonded to the central metal ion. (B) Ligands must always be negatively charged. (C) A chelating ligand can bind through more than one donor atom to the same metal. (D) [Co(NH3)6]3+ has a coordination number of 6.',
 '[{"text":"(A) Coordination number is number of donor atoms bonded","isCorrect":true},{"text":"(B) Ligands must always be negative","isCorrect":false},{"text":"(C) Chelating ligand binds via multiple donor atoms","isCorrect":true},{"text":"(D) [Co(NH3)6]3+ has coordination number 6","isCorrect":true}]'::jsonb,
 null, 'The coordination number counts donor atoms bonded to the metal (A true) -- for [Co(NH3)6]3+, all six NH3 ligands each donate one nitrogen, giving coordination number 6 (D true). Ligands can be neutral (like NH3, H2O) or negatively charged, not always negative (B false). A chelating ligand binds through more than one donor atom to the same metal center (C true).'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'numerical',
 'Find the oxidation state of chromium in $K_2Cr_2O_7$.',
 null, '6', '2(+1) + 2x + 7(-2) = 0, so 2x = 12, giving x = +6.'),
('JEE Main', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'descriptive',
 'Explain what is meant by "isomerism" in coordination compounds, giving one example of a type they can show.',
 null, null, 'Isomerism in coordination compounds occurs when two compounds share the same chemical formula but differ in how the ligands are arranged around the metal, giving different properties. One example is geometric (cis-trans) isomerism, where ligands occupy different relative positions around the central metal ion.'),

-- Mathematics: Algebra
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'easy', 'mcq',
 'Find the sum of the roots of $x^2-5x+6=0$.',
 '[{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"-5","isCorrect":false},{"text":"1","isCorrect":false}]'::jsonb,
 null, 'For ax^2+bx+c=0, the sum of roots is -b/a = -(-5)/1 = 5.'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'hard', 'mcq',
 'Let $A$ be the $2\times2$ matrix with first row $(1,2)$ and second row $(0,3)$. Which of the following statement(s) is/are TRUE? (A) $\det(A)=3$. (B) $A$ is invertible. (C) $A$ is a symmetric matrix. (D) The eigenvalues of $A$ are $1$ and $3$.',
 '[{"text":"(A) det(A) = 3","isCorrect":true},{"text":"(B) A is invertible","isCorrect":true},{"text":"(C) A is symmetric","isCorrect":false},{"text":"(D) Eigenvalues are 1 and 3","isCorrect":true}]'::jsonb,
 null, 'det(A) = 1*3 - 2*0 = 3 (A true), and since the determinant is nonzero, A is invertible (B true). A is upper triangular, not symmetric, since its two off-diagonal entries (2 and 0) differ (C false). For an upper (or lower) triangular matrix, the eigenvalues are exactly the diagonal entries, here 1 and 3 (D true).'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'numerical',
 'Find the number of terms in the arithmetic progression $2,5,8,\ldots,29$.',
 null, '10', 'Using last term = a + (n-1)d: 29 = 2 + (n-1)*3, giving n-1=9, so n=10.'),
('JEE Main', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'descriptive',
 'Explain the difference between a permutation and a combination, using a simple example.',
 null, null, 'A permutation counts arrangements where order matters (e.g. arranging 3 people in a line), while a combination counts selections where order does not matter (e.g. choosing 3 people for a team from a larger group). For the same selection size, the number of permutations is always at least as large as the number of combinations.'),

-- Mathematics: Calculus
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'mcq',
 'Find $\frac{d}{dx}(\sin x \cos x)$, simplified using a double-angle identity.',
 '[{"text":"cos(2x)","isCorrect":true},{"text":"sin(2x)","isCorrect":false},{"text":"-sin(2x)","isCorrect":false},{"text":"2cos(x)","isCorrect":false}]'::jsonb,
 null, 'By the product rule, d/dx(sinx cosx) = cos^2(x) - sin^2(x), which equals cos(2x).'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'hard', 'mcq',
 'Let $f(x)=\frac{1}{x}$ for $x>0$. Which of the following statement(s) is/are TRUE on this domain? (A) $f$ is continuous. (B) $f$ is decreasing. (C) $f$ has a local minimum. (D) $\lim_{x\to\infty}f(x)=0$.',
 '[{"text":"(A) f is continuous","isCorrect":true},{"text":"(B) f is decreasing","isCorrect":true},{"text":"(C) f has a local minimum","isCorrect":false},{"text":"(D) Limit as x approaches infinity is 0","isCorrect":true}]'::jsonb,
 null, '1/x is continuous everywhere on x>0 (A true). Its derivative -1/x^2 is always negative there, so f is strictly decreasing (B true) with no local minimum, since it is monotonic on this domain (C false). As x grows without bound, 1/x approaches 0 (D true).'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'easy', 'numerical',
 'Evaluate $\int_0^1 3x^2\,dx$.',
 null, '1', 'The antiderivative of 3x^2 is x^3; evaluating from 0 to 1 gives 1^3 - 0^3 = 1.'),
('JEE Main', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'descriptive',
 'Explain what it means for a function to be "differentiable" at a point, and how this relates to continuity there.',
 null, null, 'A function is differentiable at a point if its derivative -- the limit of the difference quotient -- exists there, meaning the function has a well-defined tangent line at that point. Differentiability at a point implies continuity there, but the converse is not true: a function can be continuous at a point (e.g. |x| at x=0) without being differentiable there.'),

-- Mathematics: Coordinate Geometry
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'easy', 'mcq',
 'Find the midpoint of the segment joining $(2,4)$ and $(6,8)$.',
 '[{"text":"(4,6)","isCorrect":true},{"text":"(8,12)","isCorrect":false},{"text":"(2,2)","isCorrect":false},{"text":"(4,4)","isCorrect":false}]'::jsonb,
 null, 'Midpoint = ((2+6)/2, (4+8)/2) = (4,6).'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'hard', 'mcq',
 'For the parabola $y^2=8x$, which of the following statement(s) is/are TRUE? (A) The focus is at $(2,0)$. (B) The directrix is $x=-2$. (C) The vertex is at the origin. (D) The parabola opens downward.',
 '[{"text":"(A) Focus at (2,0)","isCorrect":true},{"text":"(B) Directrix x=-2","isCorrect":true},{"text":"(C) Vertex at origin","isCorrect":true},{"text":"(D) Opens downward","isCorrect":false}]'::jsonb,
 null, 'Comparing y^2=8x to the standard form y^2=4ax gives 4a=8, so a=2, meaning focus (2,0) and directrix x=-2 (A, B true). Its vertex is at the origin, as in the standard form (C true). The parabola actually opens along the positive x-axis (rightward), not downward (D false).'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'easy', 'numerical',
 'Find the area of the triangle with vertices $(0,0)$, $(4,0)$, $(0,3)$.',
 null, '6', 'This is a right triangle with legs 4 and 3, so area = (1/2)*4*3 = 6.'),
('JEE Main', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'descriptive',
 'Explain what an "asymptote" of a hyperbola is, and how many asymptotes a standard hyperbola $\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$ has.',
 null, null, 'An asymptote is a line that the curve approaches ever more closely but never actually touches as it extends to infinity. A standard hyperbola of this form has exactly two asymptotes, given by the lines y = plus or minus (b/a)x.'),

-- Mathematics: Trigonometry
('JEE Main', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'Find $\cos(0^\circ)$.',
 '[{"text":"0","isCorrect":false},{"text":"1","isCorrect":true},{"text":"-1","isCorrect":false},{"text":"Undefined","isCorrect":false}]'::jsonb,
 null, 'cos(0 degrees) = 1.'),
('JEE Main', 'Mathematics', 'Trigonometry', 'medium', 'mcq',
 'Which of the following statement(s) is/are TRUE for all real $x$? (A) $\sin^2 x+\cos^2 x=1$. (B) $-1\le\sin x\le1$. (C) $\tan x$ is defined for all real $x$. (D) $\sin(-x)=-\sin(x)$.',
 '[{"text":"(A) sin^2(x)+cos^2(x)=1","isCorrect":true},{"text":"(B) -1<=sin(x)<=1","isCorrect":true},{"text":"(C) tan(x) defined for all real x","isCorrect":false},{"text":"(D) sin(-x) = -sin(x)","isCorrect":true}]'::jsonb,
 null, 'The Pythagorean identity sin^2(x)+cos^2(x)=1 holds for all real x (A true), and sin(x) is always bounded between -1 and 1 (B true). tan(x)=sin(x)/cos(x) is undefined wherever cos(x)=0, so it is NOT defined for all real x (C false). Sine is an odd function, so sin(-x)=-sin(x) always (D true).'),
('JEE Main', 'Mathematics', 'Trigonometry', 'medium', 'numerical',
 'If $\sin x=0.6$ and $x$ is in the first quadrant, find $\cos x$ (as a decimal).',
 null, '0.8', 'cos(x) = sqrt(1 - 0.6^2) = sqrt(1-0.36) = sqrt(0.64) = 0.8.'),
('JEE Main', 'Mathematics', 'Trigonometry', 'medium', 'descriptive',
 'Explain what the "period" of a trigonometric function means, and state the period of $\sin x$ and $\tan x$.',
 null, null, 'The period of a function is the smallest positive value T such that f(x+T)=f(x) for all x -- the graph repeats every T units. The period of sin(x) is 2*pi, while the period of tan(x) is pi, half as long, since tangent repeats twice as often.'),

-- Mathematics: Vectors and 3D Geometry
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'mcq',
 'Find $\vec{a}+\vec{b}$ for $\vec{a}=(1,2,3)$ and $\vec{b}=(4,5,6)$.',
 '[{"text":"(5,7,9)","isCorrect":true},{"text":"(3,3,3)","isCorrect":false},{"text":"(4,10,18)","isCorrect":false},{"text":"(5,7,10)","isCorrect":false}]'::jsonb,
 null, 'Adding component-wise: (1+4, 2+5, 3+6) = (5,7,9).'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'hard', 'mcq',
 'Regarding the direction cosines $l,m,n$ of a line in 3D space, which of the following statement(s) is/are TRUE? (A) $l^2+m^2+n^2=1$. (B) They are the cosines of the angles the line makes with the x, y, and z axes. (C) They can take any real value without restriction. (D) Direction ratios are proportional to direction cosines.',
 '[{"text":"(A) l^2+m^2+n^2 = 1","isCorrect":true},{"text":"(B) Cosines of angles with x, y, z axes","isCorrect":true},{"text":"(C) Any real value without restriction","isCorrect":false},{"text":"(D) Direction ratios proportional to direction cosines","isCorrect":true}]'::jsonb,
 null, 'Direction cosines are defined as the cosines of the angles a line makes with the three coordinate axes (B true), and they always satisfy l^2+m^2+n^2=1 (A true), so they cannot take arbitrary values without restriction (C false). Direction ratios are simply any numbers proportional to the direction cosines (D true).'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'numerical',
 'Find $|\vec{a}|$ for $\vec{a}=(3,0,4)$.',
 null, '5', '|a| = sqrt(3^2+0^2+4^2) = sqrt(25) = 5.'),
('JEE Main', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'descriptive',
 'Explain the difference between direction cosines and direction ratios of a line in 3D space.',
 null, null, 'Direction cosines are the actual cosines of the angles a line makes with the coordinate axes, satisfying l^2+m^2+n^2=1. Direction ratios are any set of numbers proportional to the direction cosines, not necessarily normalized that way -- they are often easier to read directly off a line''s equation.'),

-- Mathematics: Statistics and Probability
('JEE Main', 'Mathematics', 'Statistics and Probability', 'easy', 'mcq',
 'A card is drawn from a standard deck of 52 cards. Find the probability that it is a king.',
 '[{"text":"1/13","isCorrect":true},{"text":"1/52","isCorrect":false},{"text":"1/4","isCorrect":false},{"text":"4/13","isCorrect":false}]'::jsonb,
 null, 'There are 4 kings out of 52 cards, giving probability 4/52 = 1/13.'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'hard', 'mcq',
 'Events $A$ and $B$ are independent with $P(A)=0.5$ and $P(B)=0.4$. Which of the following statement(s) is/are TRUE? (A) $P(A\cap B)=0.2$. (B) $P(A\cup B)=0.7$. (C) $A$ and $B$ are mutually exclusive. (D) $P(A|B)=P(A)$.',
 '[{"text":"(A) P(A and B) = 0.2","isCorrect":true},{"text":"(B) P(A or B) = 0.7","isCorrect":true},{"text":"(C) A and B are mutually exclusive","isCorrect":false},{"text":"(D) P(A given B) = P(A)","isCorrect":true}]'::jsonb,
 null, 'For independent events, P(A and B) = P(A)*P(B) = 0.5*0.4 = 0.2 (A true), and P(A or B) = P(A)+P(B)-P(A and B) = 0.5+0.4-0.2 = 0.7 (B true). Independent events with nonzero probabilities can never be mutually exclusive, since both can occur together (C false). By definition of independence, P(A given B) = P(A) (D true).'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'medium', 'numerical',
 'A committee of 3 people is chosen from 5 people. How many different committees are possible?',
 null, '10', 'C(5,3) = 5!/(3!2!) = 10.'),
('JEE Main', 'Mathematics', 'Statistics and Probability', 'medium', 'descriptive',
 'Explain what the "expected value" of a random variable represents, using a simple dice example.',
 null, null, 'The expected value is the long-run average outcome of a random variable if the experiment were repeated many times, weighted by each outcome''s probability. For a fair six-sided die, the expected value is (1+2+3+4+5+6)/6 = 3.5 -- the long-run average result of many rolls, even though 3.5 is never an actual outcome of any single roll.');
