-- supabase/sql/exam_question_bank_neet_pg_set1.sql
--
-- First curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure). Same exam_question_bank table/schema as the JEE sets -- no migration needed.
--
-- Unlike the JEE sets, NEET PG's real format is 100% single-best-response MCQ (4 options, exactly
-- one correct) -- there is no multi-correct, numerical, or descriptive format in the actual exam,
-- so every row here is format='mcq' with a single isCorrect:true option. Each of the 16 chapters
-- gets 4 classic, high-yield MBBS/board-style questions covering standard textbook facts (the
-- kind of single-best-answer recall commonly tested in NEET PG and equivalent exams).
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Which nerve is most commonly injured in a surgical neck fracture of the humerus?',
 '[{"text":"Axillary nerve","isCorrect":true},{"text":"Radial nerve","isCorrect":false},{"text":"Musculocutaneous nerve","isCorrect":false},{"text":"Ulnar nerve","isCorrect":false}]'::jsonb,
 null, 'The axillary nerve winds around the surgical neck of the humerus and is at risk of injury in fractures at this site, resulting in deltoid paralysis and loss of sensation over the regimental badge area.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The femoral triangle is bounded laterally by which muscle?',
 '[{"text":"Adductor longus","isCorrect":false},{"text":"Sartorius","isCorrect":true},{"text":"Rectus femoris","isCorrect":false},{"text":"Gracilis","isCorrect":false}]'::jsonb,
 null, 'The femoral triangle is bounded superiorly by the inguinal ligament, medially by adductor longus, and laterally by sartorius.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'hard', 'mcq',
 'Which of the following is a direct branch of the external carotid artery?',
 '[{"text":"Ophthalmic artery","isCorrect":false},{"text":"Superior thyroid artery","isCorrect":true},{"text":"Posterior communicating artery","isCorrect":false},{"text":"Anterior cerebral artery","isCorrect":false}]'::jsonb,
 null, 'The superior thyroid artery is the first anterior branch of the external carotid artery. The internal carotid artery, by contrast, gives off no branches in the neck.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The recurrent laryngeal nerve is a branch of which cranial nerve?',
 '[{"text":"Glossopharyngeal nerve","isCorrect":false},{"text":"Vagus nerve","isCorrect":true},{"text":"Hypoglossal nerve","isCorrect":false},{"text":"Accessory nerve","isCorrect":false}]'::jsonb,
 null, 'The recurrent laryngeal nerve is a branch of the vagus nerve, supplying all intrinsic muscles of the larynx except cricothyroid, and is at surgical risk during thyroidectomy.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The plateau phase of the ventricular cardiac action potential corresponds to which phase?',
 '[{"text":"Phase 0","isCorrect":false},{"text":"Phase 1","isCorrect":false},{"text":"Phase 2","isCorrect":true},{"text":"Phase 4","isCorrect":false}]'::jsonb,
 null, 'Phase 2 is the plateau phase, maintained by a balance between slow inward calcium current and outward potassium current, prolonging the refractory period and preventing tetany of cardiac muscle.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'The primary pacemaker of the heart is located in the:',
 '[{"text":"AV node","isCorrect":false},{"text":"SA node","isCorrect":true},{"text":"Bundle of His","isCorrect":false},{"text":"Purkinje fibers","isCorrect":false}]'::jsonb,
 null, 'The sinoatrial (SA) node, located at the junction of the superior vena cava and right atrium, has the fastest intrinsic rate of depolarization and normally drives heart rate.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which hormone primarily stimulates erythropoiesis?',
 '[{"text":"Erythropoietin","isCorrect":true},{"text":"Thrombopoietin","isCorrect":false},{"text":"Aldosterone","isCorrect":false},{"text":"Angiotensin II","isCorrect":false}]'::jsonb,
 null, 'Erythropoietin, produced mainly by the kidney in response to hypoxia, stimulates proliferation and differentiation of erythroid precursors in the bone marrow.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'hard', 'mcq',
 'Which lung volume cannot be measured directly by simple spirometry?',
 '[{"text":"Tidal volume","isCorrect":false},{"text":"Inspiratory reserve volume","isCorrect":false},{"text":"Expiratory reserve volume","isCorrect":false},{"text":"Residual volume","isCorrect":true}]'::jsonb,
 null, 'Residual volume, the air remaining in the lungs after maximal expiration, cannot be exhaled and so cannot be measured by simple spirometry -- it requires methods like body plethysmography or gas dilution.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Phenylketonuria results from a deficiency of which enzyme?',
 '[{"text":"Tyrosinase","isCorrect":false},{"text":"Phenylalanine hydroxylase","isCorrect":true},{"text":"Homogentisate oxidase","isCorrect":false},{"text":"Branched-chain ketoacid dehydrogenase","isCorrect":false}]'::jsonb,
 null, 'Phenylketonuria is caused by deficiency of phenylalanine hydroxylase, which normally converts phenylalanine to tyrosine, leading to toxic phenylalanine accumulation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Deficiency of which vitamin causes beriberi?',
 '[{"text":"Vitamin B1 (Thiamine)","isCorrect":true},{"text":"Vitamin B2 (Riboflavin)","isCorrect":false},{"text":"Vitamin B3 (Niacin)","isCorrect":false},{"text":"Vitamin B6 (Pyridoxine)","isCorrect":false}]'::jsonb,
 null, 'Thiamine (vitamin B1) deficiency causes beriberi, presenting as either the dry (neurological) or wet (cardiovascular, with high-output failure) form.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'The rate-limiting enzyme of glycolysis is:',
 '[{"text":"Hexokinase","isCorrect":false},{"text":"Phosphofructokinase-1","isCorrect":true},{"text":"Pyruvate kinase","isCorrect":false},{"text":"Aldolase","isCorrect":false}]'::jsonb,
 null, 'Phosphofructokinase-1 (PFK-1), catalyzing fructose-6-phosphate to fructose-1,6-bisphosphate, is the key rate-limiting and most highly regulated step of glycolysis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'hard', 'mcq',
 'Which of the following amino acids is purely ketogenic (not glucogenic)?',
 '[{"text":"Alanine","isCorrect":false},{"text":"Leucine","isCorrect":true},{"text":"Glutamine","isCorrect":false},{"text":"Methionine","isCorrect":false}]'::jsonb,
 null, 'Leucine and lysine are the only two purely ketogenic amino acids in humans; all others are either purely glucogenic or both glucogenic and ketogenic.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'Psammoma bodies are a classic histological feature of which tumor?',
 '[{"text":"Follicular carcinoma of thyroid","isCorrect":false},{"text":"Papillary carcinoma of thyroid","isCorrect":true},{"text":"Medullary carcinoma of thyroid","isCorrect":false},{"text":"Anaplastic carcinoma of thyroid","isCorrect":false}]'::jsonb,
 null, 'Psammoma bodies (concentric, laminated calcified structures) are a classic feature of papillary thyroid carcinoma, though they can also occur in meningioma and serous ovarian cystadenoma.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Reed-Sternberg cells are pathognomonic of:',
 '[{"text":"Non-Hodgkin lymphoma","isCorrect":false},{"text":"Hodgkin lymphoma","isCorrect":true},{"text":"Multiple myeloma","isCorrect":false},{"text":"Chronic lymphocytic leukemia","isCorrect":false}]'::jsonb,
 null, 'Reed-Sternberg cells -- large binucleate cells with prominent "owl-eye" nucleoli -- are the diagnostic hallmark of classic Hodgkin lymphoma.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which type of necrosis is most characteristic of tuberculosis?',
 '[{"text":"Coagulative necrosis","isCorrect":false},{"text":"Liquefactive necrosis","isCorrect":false},{"text":"Caseous necrosis","isCorrect":true},{"text":"Fat necrosis","isCorrect":false}]'::jsonb,
 null, 'Caseous necrosis, with a cheese-like friable appearance combining features of coagulative and liquefactive necrosis, is characteristic of tuberculous granulomas.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'The most common histological subtype of renal cell carcinoma is:',
 '[{"text":"Clear cell carcinoma","isCorrect":true},{"text":"Papillary carcinoma","isCorrect":false},{"text":"Chromophobe carcinoma","isCorrect":false},{"text":"Collecting duct carcinoma","isCorrect":false}]'::jsonb,
 null, 'Clear cell (conventional) renal cell carcinoma accounts for the large majority of renal cell carcinomas and is associated with VHL gene alterations.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Whooping cough is caused by which organism?',
 '[{"text":"Bordetella pertussis","isCorrect":true},{"text":"Corynebacterium diphtheriae","isCorrect":false},{"text":"Haemophilus influenzae","isCorrect":false},{"text":"Mycoplasma pneumoniae","isCorrect":false}]'::jsonb,
 null, 'Bordetella pertussis, a gram-negative coccobacillus, causes whooping cough (pertussis), characterized by paroxysmal coughing with an inspiratory whoop.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'hard', 'mcq',
 'Which of the following is a treponemal test for the diagnosis of syphilis?',
 '[{"text":"VDRL","isCorrect":false},{"text":"RPR","isCorrect":false},{"text":"FTA-ABS","isCorrect":true},{"text":"ESR","isCorrect":false}]'::jsonb,
 null, 'FTA-ABS (fluorescent treponemal antibody absorption) is a treponemal test, specific for antibodies against Treponema pallidum, unlike the non-treponemal VDRL and RPR screening tests.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'AIDS is caused by which type of virus?',
 '[{"text":"DNA virus","isCorrect":false},{"text":"Retrovirus (RNA virus)","isCorrect":true},{"text":"Herpesvirus","isCorrect":false},{"text":"Adenovirus","isCorrect":false}]'::jsonb,
 null, 'HIV, the causative agent of AIDS, is a retrovirus -- an RNA virus that uses reverse transcriptase to integrate a DNA copy of its genome into the host cell.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'The most common cause of community-acquired pneumonia is:',
 '[{"text":"Streptococcus pneumoniae","isCorrect":true},{"text":"Klebsiella pneumoniae","isCorrect":false},{"text":"Pseudomonas aeruginosa","isCorrect":false},{"text":"Staphylococcus aureus","isCorrect":false}]'::jsonb,
 null, 'Streptococcus pneumoniae remains the most common bacterial cause of community-acquired pneumonia across most age groups.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'hard', 'mcq',
 'The first-line drug for acute management of status epilepticus is:',
 '[{"text":"Phenytoin","isCorrect":false},{"text":"Lorazepam (IV)","isCorrect":true},{"text":"Valproate","isCorrect":false},{"text":"Levetiracetam","isCorrect":false}]'::jsonb,
 null, 'IV lorazepam is the preferred first-line agent for acute termination of status epilepticus due to its rapid onset and relatively long duration of anticonvulsant action.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which class of antihypertensive drugs is contraindicated in pregnancy?',
 '[{"text":"Calcium channel blockers","isCorrect":false},{"text":"ACE inhibitors","isCorrect":true},{"text":"Beta blockers","isCorrect":false},{"text":"Methyldopa","isCorrect":false}]'::jsonb,
 null, 'ACE inhibitors (and ARBs) are contraindicated in pregnancy due to fetotoxic effects, including oligohydramnios, renal failure, and skull ossification defects.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Penicillin exerts its bactericidal action by inhibiting which process?',
 '[{"text":"Protein synthesis","isCorrect":false},{"text":"Cell wall synthesis","isCorrect":true},{"text":"DNA gyrase","isCorrect":false},{"text":"Folate synthesis","isCorrect":false}]'::jsonb,
 null, 'Penicillins inhibit transpeptidase enzymes (penicillin-binding proteins) involved in peptidoglycan cross-linking, blocking bacterial cell wall synthesis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'The antidote for paracetamol (acetaminophen) overdose is:',
 '[{"text":"N-acetylcysteine","isCorrect":true},{"text":"Naloxone","isCorrect":false},{"text":"Flumazenil","isCorrect":false},{"text":"Fomepizole","isCorrect":false}]'::jsonb,
 null, 'N-acetylcysteine replenishes hepatic glutathione stores, detoxifying the toxic metabolite NAPQI produced in paracetamol overdose, and is most effective when given early.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'In death by hanging, the ligature mark is typically:',
 '[{"text":"Horizontal and continuous, below the thyroid cartilage","isCorrect":false},{"text":"Oblique and non-continuous, above the thyroid cartilage","isCorrect":true},{"text":"Absent entirely","isCorrect":false},{"text":"Only present in homicidal cases","isCorrect":false}]'::jsonb,
 null, 'In hanging, the ligature mark is typically oblique, non-continuous (breaking at the point of suspension), and situated above the level of the thyroid cartilage -- distinguishing it from the horizontal, continuous mark of strangulation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Rigor mortis first becomes apparent in which muscles?',
 '[{"text":"Muscles of the face and jaw","isCorrect":true},{"text":"Muscles of the lower limb","isCorrect":false},{"text":"Muscles of the trunk","isCorrect":false},{"text":"Muscles of the upper limb only","isCorrect":false}]'::jsonb,
 null, 'Rigor mortis follows a cranio-caudal progression per Nysten''s law, appearing first in the small muscles of the face and jaw before involving larger muscle groups.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'easy', 'mcq',
 'Within the first few hours after death, which finding is most useful in estimating the time since death?',
 '[{"text":"Body temperature (algor mortis)","isCorrect":true},{"text":"Rigor mortis","isCorrect":false},{"text":"Putrefaction","isCorrect":false},{"text":"Adipocere formation","isCorrect":false}]'::jsonb,
 null, 'In the early post-mortem period, the progressive fall in body temperature (algor mortis) is the most reliable indicator, since rigor mortis takes hours to develop and putrefaction/adipocere take much longer.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'The antidote for organophosphorus compound poisoning is:',
 '[{"text":"Atropine","isCorrect":true},{"text":"Naloxone","isCorrect":false},{"text":"Physostigmine","isCorrect":false},{"text":"Protamine sulfate","isCorrect":false}]'::jsonb,
 null, 'Atropine, a muscarinic receptor antagonist, is used to counteract the cholinergic excess of organophosphorus poisoning, typically alongside pralidoxime to reactivate acetylcholinesterase.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'easy', 'mcq',
 'Under India''s Universal Immunization Programme, which vaccine is given at birth?',
 '[{"text":"BCG","isCorrect":true},{"text":"MMR","isCorrect":false},{"text":"DPT booster","isCorrect":false},{"text":"Typhoid vaccine","isCorrect":false}]'::jsonb,
 null, 'BCG (along with OPV-0 and the hepatitis B birth dose) is given at birth under India''s Universal Immunization Programme.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The herd immunity threshold for a disease primarily depends on which parameter?',
 '[{"text":"Case fatality rate","isCorrect":false},{"text":"Basic reproduction number (R0)","isCorrect":true},{"text":"Incubation period","isCorrect":false},{"text":"Attack rate","isCorrect":false}]'::jsonb,
 null, 'Herd immunity threshold is calculated as 1 - (1/R0), so it depends directly on the basic reproduction number of the disease.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which measure of association is calculated directly in a cohort study?',
 '[{"text":"Odds ratio","isCorrect":false},{"text":"Relative risk","isCorrect":true},{"text":"Prevalence ratio only","isCorrect":false},{"text":"Attributable fraction only","isCorrect":false}]'::jsonb,
 null, 'Cohort studies follow exposed and unexposed groups forward in time, allowing direct calculation of incidence and hence relative risk, unlike case-control studies which calculate odds ratios.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'easy', 'mcq',
 'For a skewed data distribution, which measure of central tendency is most appropriate?',
 '[{"text":"Mean","isCorrect":false},{"text":"Median","isCorrect":true},{"text":"Mode only","isCorrect":false},{"text":"Standard deviation","isCorrect":false}]'::jsonb,
 null, 'The median is less affected by extreme outliers than the mean, making it the preferred measure of central tendency for skewed distributions.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common cause of chronic kidney disease worldwide is:',
 '[{"text":"Diabetes mellitus","isCorrect":true},{"text":"Glomerulonephritis","isCorrect":false},{"text":"Polycystic kidney disease","isCorrect":false},{"text":"Analgesic nephropathy","isCorrect":false}]'::jsonb,
 null, 'Diabetic nephropathy is the leading cause of chronic kidney disease worldwide, reflecting the rising global burden of diabetes mellitus.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Kussmaul breathing (deep, labored breathing) is characteristically seen in:',
 '[{"text":"Metabolic acidosis","isCorrect":true},{"text":"Metabolic alkalosis","isCorrect":false},{"text":"Respiratory acidosis","isCorrect":false},{"text":"Respiratory alkalosis","isCorrect":false}]'::jsonb,
 null, 'Kussmaul breathing is a compensatory response to severe metabolic acidosis (classically diabetic ketoacidosis), increasing ventilation to blow off CO2 and raise blood pH.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'hard', 'mcq',
 'Which antibiotic is a preferred first-line treatment for typhoid fever, especially where fluoroquinolone resistance is common?',
 '[{"text":"Ceftriaxone","isCorrect":true},{"text":"Vancomycin","isCorrect":false},{"text":"Metronidazole","isCorrect":false},{"text":"Doxycycline","isCorrect":false}]'::jsonb,
 null, 'Ceftriaxone, a third-generation cephalosporin, is widely used for typhoid fever, particularly given rising fluoroquinolone resistance in Salmonella Typhi.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'hard', 'mcq',
 'The most common cause of nephrotic syndrome in children is:',
 '[{"text":"Minimal change disease","isCorrect":true},{"text":"Membranous nephropathy","isCorrect":false},{"text":"Focal segmental glomerulosclerosis","isCorrect":false},{"text":"IgA nephropathy","isCorrect":false}]'::jsonb,
 null, 'Minimal change disease is the most common cause of nephrotic syndrome in children, typically presenting with steroid-responsive proteinuria and normal-appearing glomeruli on light microscopy.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The Moro reflex normally disappears by which age?',
 '[{"text":"2-3 months","isCorrect":false},{"text":"4-6 months","isCorrect":true},{"text":"9-12 months","isCorrect":false},{"text":"It persists throughout infancy","isCorrect":false}]'::jsonb,
 null, 'The Moro (startle) reflex is present at birth and normally disappears by 4-6 months of age; persistence beyond this suggests a neurological abnormality.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The most common congenital heart disease overall is:',
 '[{"text":"Tetralogy of Fallot","isCorrect":false},{"text":"Ventricular septal defect","isCorrect":true},{"text":"Transposition of great arteries","isCorrect":false},{"text":"Coarctation of aorta","isCorrect":false}]'::jsonb,
 null, 'Ventricular septal defect is the single most common congenital heart disease, though patent ductus arteriosus is more common when isolated to preterm infants.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'Under India''s immunization schedule, the first dose of measles-containing (MR) vaccine is given at:',
 '[{"text":"6 weeks","isCorrect":false},{"text":"9 months","isCorrect":true},{"text":"5 years","isCorrect":false},{"text":"Birth","isCorrect":false}]'::jsonb,
 null, 'The first dose of measles-rubella (MR) vaccine is given at 9 months of age in India''s Universal Immunization Programme, with a second dose at 16-24 months.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Down syndrome is definitively diagnosed by which investigation?',
 '[{"text":"Karyotyping showing trisomy 21","isCorrect":true},{"text":"Serum alpha-fetoprotein alone","isCorrect":false},{"text":"Chest X-ray","isCorrect":false},{"text":"MRI brain","isCorrect":false}]'::jsonb,
 null, 'Karyotyping demonstrating trisomy of chromosome 21 is the definitive diagnostic test for Down syndrome, though clinical features and screening tests raise initial suspicion.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'easy', 'mcq',
 'Which class of drugs is first-line for major depressive disorder?',
 '[{"text":"SSRIs","isCorrect":true},{"text":"Typical antipsychotics","isCorrect":false},{"text":"Benzodiazepines","isCorrect":false},{"text":"Lithium alone","isCorrect":false}]'::jsonb,
 null, 'Selective serotonin reuptake inhibitors (SSRIs) are first-line pharmacotherapy for major depressive disorder due to their favorable efficacy and side-effect profile.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Flight of ideas and grandiosity are characteristic features of:',
 '[{"text":"Major depressive episode","isCorrect":false},{"text":"Manic episode","isCorrect":true},{"text":"Generalized anxiety disorder","isCorrect":false},{"text":"Obsessive-compulsive disorder","isCorrect":false}]'::jsonb,
 null, 'Flight of ideas, grandiosity, decreased need for sleep, and pressured speech are classic features of a manic episode, as seen in bipolar disorder.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Command hallucinations and persecutory delusions are most characteristic of:',
 '[{"text":"Schizophrenia","isCorrect":true},{"text":"Delirium","isCorrect":false},{"text":"Panic disorder","isCorrect":false},{"text":"Somatic symptom disorder","isCorrect":false}]'::jsonb,
 null, 'Auditory hallucinations (including command hallucinations) and persecutory delusions are core positive symptoms of schizophrenia.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'Extrapyramidal side effects are most associated with which class of drugs?',
 '[{"text":"Typical (first-generation) antipsychotics","isCorrect":true},{"text":"SSRIs","isCorrect":false},{"text":"Benzodiazepines","isCorrect":false},{"text":"Lithium","isCorrect":false}]'::jsonb,
 null, 'Typical antipsychotics have strong D2-receptor blockade in the nigrostriatal pathway, causing extrapyramidal side effects like parkinsonism, dystonia, akathisia, and tardive dyskinesia.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'A positive Nikolsky sign is characteristically seen in:',
 '[{"text":"Psoriasis","isCorrect":false},{"text":"Pemphigus vulgaris","isCorrect":true},{"text":"Lichen planus","isCorrect":false},{"text":"Vitiligo","isCorrect":false}]'::jsonb,
 null, 'A positive Nikolsky sign (sliding pressure causing epidermal separation) reflects intraepidermal acantholysis, classically seen in pemphigus vulgaris.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Silvery-white scales over extensor surfaces of the elbows and knees are characteristic of:',
 '[{"text":"Psoriasis","isCorrect":true},{"text":"Eczema","isCorrect":false},{"text":"Scabies","isCorrect":false},{"text":"Urticaria","isCorrect":false}]'::jsonb,
 null, 'Psoriasis classically presents with well-demarcated erythematous plaques covered by silvery-white scales, favoring extensor surfaces like elbows and knees.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Scabies is caused by which organism?',
 '[{"text":"Sarcoptes scabiei","isCorrect":true},{"text":"Pediculus humanus","isCorrect":false},{"text":"Demodex folliculorum","isCorrect":false},{"text":"Trichophyton rubrum","isCorrect":false}]'::jsonb,
 null, 'Scabies is caused by infestation with the mite Sarcoptes scabiei, which burrows into the epidermis causing intense pruritus, typically worse at night.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Wood''s lamp examination is most useful for diagnosing which condition?',
 '[{"text":"Tinea capitis","isCorrect":true},{"text":"Contact dermatitis","isCorrect":false},{"text":"Acne vulgaris","isCorrect":false},{"text":"Urticaria","isCorrect":false}]'::jsonb,
 null, 'Wood''s lamp (ultraviolet light) causes certain dermatophyte infections of the scalp (tinea capitis, especially Microsporum species) to fluoresce, aiding diagnosis.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common anatomical position of the appendix in adults is:',
 '[{"text":"Retrocecal","isCorrect":true},{"text":"Pelvic","isCorrect":false},{"text":"Subhepatic","isCorrect":false},{"text":"Preileal","isCorrect":false}]'::jsonb,
 null, 'The retrocecal position is the most common location of the vermiform appendix in adults, though its tip can point in several directions.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Charcot''s triad (fever, jaundice, right upper quadrant pain) is classically seen in:',
 '[{"text":"Acute pancreatitis","isCorrect":false},{"text":"Ascending cholangitis","isCorrect":true},{"text":"Acute appendicitis","isCorrect":false},{"text":"Peptic ulcer perforation","isCorrect":false}]'::jsonb,
 null, 'Charcot''s triad of fever, jaundice, and right upper quadrant pain is classic for ascending (acute) cholangitis, usually due to biliary obstruction with superimposed infection.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'hard', 'mcq',
 'The most common type of hiatus hernia is:',
 '[{"text":"Sliding (Type I) hiatus hernia","isCorrect":true},{"text":"Rolling (Type II) hiatus hernia","isCorrect":false},{"text":"Mixed (Type III) hiatus hernia","isCorrect":false},{"text":"Type IV hiatus hernia","isCorrect":false}]'::jsonb,
 null, 'Sliding (Type I) hiatus hernia, in which the gastroesophageal junction migrates above the diaphragm, accounts for the vast majority of hiatus hernias.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Virchow''s node, a sign of possible abdominal malignancy, is located in the:',
 '[{"text":"Right axilla","isCorrect":false},{"text":"Left supraclavicular fossa","isCorrect":true},{"text":"Right inguinal region","isCorrect":false},{"text":"Left popliteal fossa","isCorrect":false}]'::jsonb,
 null, 'Virchow''s node is an enlarged left supraclavicular lymph node, classically associated with metastatic spread from an abdominal malignancy, particularly gastric cancer.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common site of osteosarcoma is:',
 '[{"text":"Metaphysis of distal femur","isCorrect":true},{"text":"Diaphysis of humerus","isCorrect":false},{"text":"Epiphysis of tibia","isCorrect":false},{"text":"Skull","isCorrect":false}]'::jsonb,
 null, 'Osteosarcoma most commonly arises in the metaphysis of long bones around the knee, particularly the distal femur, reflecting regions of rapid bone growth.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'A Colles'' fracture involves a fracture of which bone, with characteristic dorsal displacement?',
 '[{"text":"Distal radius","isCorrect":true},{"text":"Distal ulna","isCorrect":false},{"text":"Scaphoid","isCorrect":false},{"text":"Distal humerus","isCorrect":false}]'::jsonb,
 null, 'A Colles'' fracture is a fracture of the distal radius with dorsal angulation and displacement, classically from a fall on an outstretched hand, producing a "dinner fork" deformity.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Which nerve is most at risk of injury in a fracture of the midshaft of the humerus?',
 '[{"text":"Axillary nerve","isCorrect":false},{"text":"Radial nerve","isCorrect":true},{"text":"Median nerve","isCorrect":false},{"text":"Ulnar nerve","isCorrect":false}]'::jsonb,
 null, 'The radial nerve runs in the spiral (radial) groove of the humerus and is at risk of injury in midshaft humeral fractures, resulting in wrist drop.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'hard', 'mcq',
 'Volkmann''s ischemic contracture is a well-known complication of which fracture?',
 '[{"text":"Supracondylar fracture of the humerus","isCorrect":true},{"text":"Colles'' fracture","isCorrect":false},{"text":"Fracture of the shaft of femur","isCorrect":false},{"text":"Fracture neck of femur","isCorrect":false}]'::jsonb,
 null, 'Volkmann''s ischemic contracture, a flexion contracture of the forearm and hand from compartment syndrome-related muscle ischemia, is a classic complication of supracondylar fracture of the humerus in children.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'The normal duration of pregnancy from the last menstrual period is approximately:',
 '[{"text":"280 days (40 weeks)","isCorrect":true},{"text":"260 days (37 weeks)","isCorrect":false},{"text":"300 days (43 weeks)","isCorrect":false},{"text":"240 days (34 weeks)","isCorrect":false}]'::jsonb,
 null, 'By Naegele''s rule, the estimated date of delivery is 280 days (40 weeks) from the first day of the last menstrual period.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The most common cause of primary postpartum hemorrhage is:',
 '[{"text":"Uterine atony","isCorrect":true},{"text":"Genital tract trauma","isCorrect":false},{"text":"Retained placental tissue","isCorrect":false},{"text":"Coagulation disorder","isCorrect":false}]'::jsonb,
 null, 'Uterine atony -- failure of the uterus to contract adequately after delivery -- accounts for the large majority of primary postpartum hemorrhage cases.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The triple/quadruple marker screening test for Down syndrome is typically performed in which trimester?',
 '[{"text":"First trimester only","isCorrect":false},{"text":"Second trimester","isCorrect":true},{"text":"Third trimester","isCorrect":false},{"text":"Pre-conception","isCorrect":false}]'::jsonb,
 null, 'The triple/quadruple marker test, measuring analytes like AFP, hCG, estriol, and inhibin-A, is performed in the second trimester (typically 15-20 weeks) to screen for Down syndrome and neural tube defects.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'A positive pregnancy test is based on detection of which hormone?',
 '[{"text":"Beta-hCG","isCorrect":true},{"text":"Progesterone","isCorrect":false},{"text":"Estriol","isCorrect":false},{"text":"Prolactin","isCorrect":false}]'::jsonb,
 null, 'Beta-human chorionic gonadotropin (beta-hCG), secreted by the syncytiotrophoblast soon after implantation, is the hormone detected in both urine and serum pregnancy tests.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The drug of choice for treating malignant hyperthermia is:',
 '[{"text":"Dantrolene","isCorrect":true},{"text":"Succinylcholine","isCorrect":false},{"text":"Neostigmine","isCorrect":false},{"text":"Naloxone","isCorrect":false}]'::jsonb,
 null, 'Dantrolene, a skeletal muscle relaxant that inhibits calcium release from the sarcoplasmic reticulum, is the specific treatment for malignant hyperthermia triggered by volatile anesthetics or succinylcholine.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'hard', 'mcq',
 'Among local anesthetics, which has the highest risk of cardiotoxicity?',
 '[{"text":"Lidocaine","isCorrect":false},{"text":"Bupivacaine","isCorrect":true},{"text":"Ropivacaine","isCorrect":false},{"text":"Prilocaine","isCorrect":false}]'::jsonb,
 null, 'Bupivacaine has a disproportionately high risk of cardiotoxicity relative to its neural blocking potency, due to slow dissociation from cardiac sodium channels -- prompting a shift toward safer agents like ropivacaine.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Which muscle relaxant is preferred for rapid sequence intubation due to its rapid onset of action?',
 '[{"text":"Succinylcholine","isCorrect":true},{"text":"Pancuronium","isCorrect":false},{"text":"Atracurium","isCorrect":false},{"text":"Vecuronium (standard dose)","isCorrect":false}]'::jsonb,
 null, 'Succinylcholine, a depolarizing neuromuscular blocker, has the fastest onset of all muscle relaxants, making it the classic choice for rapid sequence intubation.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'easy', 'mcq',
 'A healthy patient with no systemic disease is classified under which ASA physical status class?',
 '[{"text":"ASA I","isCorrect":true},{"text":"ASA II","isCorrect":false},{"text":"ASA III","isCorrect":false},{"text":"ASA IV","isCorrect":false}]'::jsonb,
 null, 'ASA I denotes a normal, healthy patient with no systemic disease, the lowest-risk category in the American Society of Anesthesiologists physical status classification.');
