-- supabase/sql/exam_question_bank_neet_pg_set5.sql
--
-- Fifth curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and Sets 1-4 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1, 2, 3, or 4.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical
-- Sciences, 4 Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/
-- Anesthesia) each get 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql / set2.sql / set3.sql / set4.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Injury to the ulnar nerve at the elbow classically produces which deformity?',
 '[{"text":"Wrist drop","isCorrect":false},{"text":"Claw hand","isCorrect":true},{"text":"Winging of the scapula","isCorrect":false},{"text":"Foot drop","isCorrect":false}]'::jsonb,
 null, 'Ulnar nerve injury classically causes a claw hand deformity, due to unopposed action of the long flexors and paralysis of the intrinsic hand muscles.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The pudendal nerve arises from which spinal segments?',
 '[{"text":"L1-L3","isCorrect":false},{"text":"S2-S4","isCorrect":true},{"text":"C5-T1","isCorrect":false},{"text":"T10-T12","isCorrect":false}]'::jsonb,
 null, 'The pudendal nerve arises from spinal segments S2 through S4, supplying the perineum and external genitalia.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'easy', 'mcq',
 'Which lobe of the brain is primarily responsible for processing visual information?',
 '[{"text":"Frontal lobe","isCorrect":false},{"text":"Occipital lobe","isCorrect":true},{"text":"Temporal lobe","isCorrect":false},{"text":"Parietal lobe","isCorrect":false}]'::jsonb,
 null, 'The occipital lobe, located at the back of the brain, houses the primary visual cortex and is responsible for processing visual information.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'hard', 'mcq',
 'The thoracic duct drains lymph into which venous structure?',
 '[{"text":"The junction of the left subclavian and left internal jugular veins","isCorrect":true},{"text":"The right atrium directly","isCorrect":false},{"text":"The hepatic portal vein","isCorrect":false},{"text":"The inferior vena cava directly","isCorrect":false}]'::jsonb,
 null, 'The thoracic duct, the largest lymphatic vessel, drains the majority of the body''s lymph into the venous system at the junction of the left subclavian and left internal jugular veins.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which layer of the epidermis is responsible for continuous cell division and renewal of the skin?',
 '[{"text":"Stratum corneum","isCorrect":false},{"text":"Stratum basale (basal layer)","isCorrect":true},{"text":"Stratum granulosum","isCorrect":false},{"text":"Stratum lucidum","isCorrect":false}]'::jsonb,
 null, 'The stratum basale, the deepest epidermal layer, contains actively dividing keratinocyte stem cells responsible for continuously renewing the skin.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'The normal range for intraocular pressure is approximately:',
 '[{"text":"1-5 mmHg","isCorrect":false},{"text":"10-21 mmHg","isCorrect":true},{"text":"30-40 mmHg","isCorrect":false},{"text":"50-60 mmHg","isCorrect":false}]'::jsonb,
 null, 'Normal intraocular pressure typically ranges from about 10 to 21 mmHg; sustained elevation above this range is a hallmark of glaucoma.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which part of the nephron is primarily responsible for the countercurrent multiplier mechanism that concentrates urine?',
 '[{"text":"Bowman''s capsule","isCorrect":false},{"text":"Loop of Henle","isCorrect":true},{"text":"Proximal convoluted tubule alone","isCorrect":false},{"text":"Glomerulus alone","isCorrect":false}]'::jsonb,
 null, 'The loop of Henle, through its countercurrent multiplier mechanism, establishes the medullary concentration gradient necessary for concentrating urine.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Peristalsis in the gastrointestinal tract is primarily coordinated by:',
 '[{"text":"The enteric nervous system","isCorrect":true},{"text":"The somatic nervous system exclusively","isCorrect":false},{"text":"Skeletal muscle reflexes alone","isCorrect":false},{"text":"The cerebellum directly","isCorrect":false}]'::jsonb,
 null, 'The enteric nervous system, often called the "gut''s own brain," coordinates the rhythmic, wave-like contractions (peristalsis) that move contents through the GI tract.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Which vitamin acts as a cofactor for carboxylation reactions and is also synthesized by gut bacteria?',
 '[{"text":"Vitamin K","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin B1","isCorrect":false},{"text":"Vitamin A","isCorrect":false}]'::jsonb,
 null, 'Vitamin K acts as a cofactor for the carboxylation of clotting factors and is also produced by gut bacteria, contributing to the body''s supply.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'hard', 'mcq',
 'The Cori cycle refers to the metabolic recycling of:',
 '[{"text":"Lactate from muscle back into glucose in the liver","isCorrect":true},{"text":"Fatty acids into ketone bodies","isCorrect":false},{"text":"Amino acids into urea only","isCorrect":false},{"text":"Cholesterol into bile acids","isCorrect":false}]'::jsonb,
 null, 'The Cori cycle describes the metabolic pathway in which lactate produced by anaerobic glycolysis in muscle is transported to the liver, converted back to glucose via gluconeogenesis, and returned to the muscle.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'In humans, purines are metabolized to which end product for excretion?',
 '[{"text":"Urea","isCorrect":false},{"text":"Uric acid","isCorrect":true},{"text":"Creatinine","isCorrect":false},{"text":"Ammonia directly","isCorrect":false}]'::jsonb,
 null, 'Purine nucleotides are degraded to uric acid in humans, which is then excreted primarily by the kidneys.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Which type of RNA is responsible for carrying amino acids to the ribosome during protein synthesis?',
 '[{"text":"Messenger RNA (mRNA)","isCorrect":false},{"text":"Transfer RNA (tRNA)","isCorrect":true},{"text":"Ribosomal RNA (rRNA) alone","isCorrect":false},{"text":"MicroRNA","isCorrect":false}]'::jsonb,
 null, 'Transfer RNA (tRNA) molecules carry specific amino acids to the ribosome, matching them to the corresponding codons on the mRNA during translation.'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which type of shock results primarily from impaired cardiac pumping function?',
 '[{"text":"Cardiogenic shock","isCorrect":true},{"text":"Hypovolemic shock","isCorrect":false},{"text":"Septic shock","isCorrect":false},{"text":"Anaphylactic shock","isCorrect":false}]'::jsonb,
 null, 'Cardiogenic shock occurs when the heart''s pumping function is severely impaired, most commonly following a large myocardial infarction, reducing cardiac output.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'hard', 'mcq',
 'Barrett''s esophagus is characterized by:',
 '[{"text":"Squamous cell hyperplasia of the esophagus","isCorrect":false},{"text":"Metaplastic change of esophageal squamous epithelium into columnar epithelium","isCorrect":true},{"text":"Complete absence of the esophageal lining","isCorrect":false},{"text":"Formation of esophageal varices","isCorrect":false}]'::jsonb,
 null, 'Barrett''s esophagus involves metaplasia of the normal squamous epithelium of the distal esophagus into columnar epithelium, typically due to chronic acid reflux, and is a risk factor for esophageal adenocarcinoma.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which tumor marker is classically associated with prostate cancer?',
 '[{"text":"CA-125","isCorrect":false},{"text":"Prostate-Specific Antigen (PSA)","isCorrect":true},{"text":"Alpha-fetoprotein","isCorrect":false},{"text":"CA 19-9","isCorrect":false}]'::jsonb,
 null, 'Prostate-Specific Antigen (PSA) is a widely used tumor marker for screening and monitoring prostate cancer.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Squamous cell carcinoma of the skin is most strongly associated with:',
 '[{"text":"Chronic ultraviolet (sun) exposure","isCorrect":true},{"text":"Viral hepatitis","isCorrect":false},{"text":"Iron deficiency","isCorrect":false},{"text":"High-fiber diet","isCorrect":false}]'::jsonb,
 null, 'Chronic ultraviolet radiation exposure is the most significant risk factor for developing cutaneous squamous cell carcinoma.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Syphilis is caused by which organism?',
 '[{"text":"Treponema pallidum","isCorrect":true},{"text":"Neisseria gonorrhoeae","isCorrect":false},{"text":"Chlamydia trachomatis","isCorrect":false},{"text":"Haemophilus ducreyi","isCorrect":false}]'::jsonb,
 null, 'Syphilis is caused by the spirochete bacterium Treponema pallidum, transmitted primarily through sexual contact.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Rabies is caused by which type of pathogen?',
 '[{"text":"A bacterium","isCorrect":false},{"text":"A virus (Lyssavirus, Rhabdoviridae family)","isCorrect":true},{"text":"A fungus","isCorrect":false},{"text":"A protozoan parasite","isCorrect":false}]'::jsonb,
 null, 'Rabies is caused by a Lyssavirus of the Rhabdoviridae family, typically transmitted through the bite of an infected animal.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Clostridium tetani produces a toxin that classically causes:',
 '[{"text":"Flaccid paralysis","isCorrect":false},{"text":"Tetanus (muscle spasm/rigidity)","isCorrect":true},{"text":"Hemolysis","isCorrect":false},{"text":"Severe diarrhea only","isCorrect":false}]'::jsonb,
 null, 'Clostridium tetani produces tetanospasmin, a potent neurotoxin that blocks inhibitory neurotransmitter release, causing the characteristic muscle spasms and rigidity of tetanus.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'Which parasite is responsible for causing amoebiasis?',
 '[{"text":"Entamoeba histolytica","isCorrect":true},{"text":"Giardia lamblia","isCorrect":false},{"text":"Plasmodium falciparum","isCorrect":false},{"text":"Toxoplasma gondii","isCorrect":false}]'::jsonb,
 null, 'Amoebiasis is caused by the protozoan parasite Entamoeba histolytica, which can cause intestinal disease and, in some cases, liver abscess.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Which class of drugs is used as first-line quick relief for acute bronchospasm in asthma?',
 '[{"text":"Short-acting beta-2 agonists (e.g. salbutamol)","isCorrect":true},{"text":"Long-acting beta-2 agonists alone","isCorrect":false},{"text":"Inhaled corticosteroids alone","isCorrect":false},{"text":"Leukotriene receptor antagonists","isCorrect":false}]'::jsonb,
 null, 'Short-acting beta-2 agonists, like salbutamol, provide rapid bronchodilation and are the first-line treatment for acute asthma symptoms.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'hard', 'mcq',
 'Methotrexate exerts its therapeutic action primarily by inhibiting:',
 '[{"text":"Dihydrofolate reductase","isCorrect":true},{"text":"Cyclooxygenase","isCorrect":false},{"text":"DNA gyrase","isCorrect":false},{"text":"Acetylcholinesterase","isCorrect":false}]'::jsonb,
 null, 'Methotrexate inhibits dihydrofolate reductase, blocking folate metabolism and thereby impairing DNA synthesis in rapidly dividing cells.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'The treatment of choice for anaphylaxis is:',
 '[{"text":"Oral antihistamines","isCorrect":false},{"text":"Adrenaline (epinephrine)","isCorrect":true},{"text":"Oral corticosteroids alone","isCorrect":false},{"text":"Intravenous fluids alone","isCorrect":false}]'::jsonb,
 null, 'Intramuscular adrenaline (epinephrine) is the immediate treatment of choice for anaphylaxis, rapidly reversing bronchospasm, hypotension, and airway edema.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Phenytoin is primarily used in the treatment of:',
 '[{"text":"Epilepsy (seizure disorders)","isCorrect":true},{"text":"Bacterial infections","isCorrect":false},{"text":"Diabetes mellitus","isCorrect":false},{"text":"Hypertension","isCorrect":false}]'::jsonb,
 null, 'Phenytoin is an antiepileptic drug widely used in the management of various types of seizure disorders.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'The medico-legal term "infanticide" refers to:',
 '[{"text":"The killing of a newborn infant","isCorrect":true},{"text":"A miscarriage occurring naturally","isCorrect":false},{"text":"A stillbirth","isCorrect":false},{"text":"Any death occurring during childbirth","isCorrect":false}]'::jsonb,
 null, 'Infanticide is defined as the killing of a newborn infant, a specific legal category distinct from general homicide in many jurisdictions.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'hard', 'mcq',
 'A "hesitation cut/wound" is a forensic finding classically associated with:',
 '[{"text":"Homicidal wounds","isCorrect":false},{"text":"Suicidal wounds (tentative cuts preceding the fatal wound)","isCorrect":true},{"text":"Accidental wounds only","isCorrect":false},{"text":"Postmortem artifacts only","isCorrect":false}]'::jsonb,
 null, 'Hesitation cuts are shallow, tentative wounds found near the main fatal wound, classically associated with suicidal cutting as the person builds up resolve.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Which classic chemical test is used to detect arsenic poisoning?',
 '[{"text":"Marsh test","isCorrect":true},{"text":"Widal test","isCorrect":false},{"text":"Schick test","isCorrect":false},{"text":"Mantoux test","isCorrect":false}]'::jsonb,
 null, 'The Marsh test is a classic chemical test used to detect the presence of arsenic in forensic toxicology.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'A medico-legal autopsy is primarily ordered in cases of:',
 '[{"text":"Expected death from a long-term chronic illness","isCorrect":false},{"text":"Unnatural, sudden, or suspicious death","isCorrect":true},{"text":"Any death occurring in a hospital","isCorrect":false},{"text":"Death after a routine surgery with no complications","isCorrect":false}]'::jsonb,
 null, 'Medico-legal autopsies are ordered specifically in cases of unnatural, sudden, unexplained, or suspicious death to determine the cause and manner of death for legal purposes.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The "sensitivity" of a diagnostic test refers to:',
 '[{"text":"The ability of the test to correctly identify those with the disease (true positive rate)","isCorrect":true},{"text":"The cost-effectiveness of the test","isCorrect":false},{"text":"The speed at which results are available","isCorrect":false},{"text":"The ability to rule out disease in healthy individuals only","isCorrect":false}]'::jsonb,
 null, 'Sensitivity measures a test''s ability to correctly identify individuals who truly have the disease (the true positive rate).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'A cohort study design follows a group of individuals over time based on their:',
 '[{"text":"Current disease status only","isCorrect":false},{"text":"Exposure status, to observe the development of outcomes","isCorrect":true},{"text":"Age at death","isCorrect":false},{"text":"Treatment preference alone","isCorrect":false}]'::jsonb,
 null, 'In a cohort study, participants are grouped by exposure status and followed forward in time to observe whether they develop the outcome of interest.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The concept of "Health for All" was central to which international declaration?',
 '[{"text":"Alma-Ata Declaration (1978)","isCorrect":true},{"text":"Geneva Convention","isCorrect":false},{"text":"Kyoto Protocol","isCorrect":false},{"text":"Paris Agreement","isCorrect":false}]'::jsonb,
 null, 'The Alma-Ata Declaration of 1978 established "Health for All" as a global goal, emphasizing primary healthcare as the key strategy to achieve it.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Immunization that protects an individual by directly administering antibodies (rather than stimulating the person''s own immune response) is called:',
 '[{"text":"Active immunization","isCorrect":false},{"text":"Passive immunization","isCorrect":true},{"text":"Herd immunization","isCorrect":false},{"text":"Autoimmunization","isCorrect":false}]'::jsonb,
 null, 'Passive immunization provides immediate but temporary protection by directly administering pre-formed antibodies, rather than stimulating the recipient''s own immune system as in active immunization.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Wilson''s disease is characterized by abnormal accumulation of which metal in the body?',
 '[{"text":"Iron","isCorrect":false},{"text":"Copper","isCorrect":true},{"text":"Zinc","isCorrect":false},{"text":"Lead","isCorrect":false}]'::jsonb,
 null, 'Wilson''s disease is an inherited disorder of copper metabolism, causing toxic copper accumulation primarily in the liver and brain.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Which condition is characterized by resting tremor, rigidity, and bradykinesia?',
 '[{"text":"Alzheimer''s disease","isCorrect":false},{"text":"Parkinson''s disease","isCorrect":true},{"text":"Multiple sclerosis","isCorrect":false},{"text":"Huntington''s disease","isCorrect":false}]'::jsonb,
 null, 'Parkinson''s disease classically presents with the triad of resting tremor, rigidity, and bradykinesia, due to loss of dopaminergic neurons in the substantia nigra.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common cause of end-stage renal disease worldwide is:',
 '[{"text":"Diabetic nephropathy","isCorrect":true},{"text":"Polycystic kidney disease","isCorrect":false},{"text":"Analgesic nephropathy","isCorrect":false},{"text":"Kidney stones","isCorrect":false}]'::jsonb,
 null, 'Diabetic nephropathy is the leading cause of end-stage renal disease globally, reflecting the rising worldwide burden of diabetes.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Which glomerular disease is the most common cause of primary nephrotic syndrome in adults?',
 '[{"text":"Minimal change disease","isCorrect":false},{"text":"Membranous nephropathy","isCorrect":true},{"text":"IgA nephropathy","isCorrect":false},{"text":"Post-streptococcal glomerulonephritis","isCorrect":false}]'::jsonb,
 null, 'Membranous nephropathy is the most common cause of primary nephrotic syndrome in adults, whereas minimal change disease predominates in children.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'Under India''s immunization schedule, the first dose of the DPT (diphtheria, pertussis, tetanus) vaccine is given at:',
 '[{"text":"Birth","isCorrect":false},{"text":"6 weeks","isCorrect":true},{"text":"6 months","isCorrect":false},{"text":"1 year","isCorrect":false}]'::jsonb,
 null, 'The first dose of DPT vaccine is administered at 6 weeks of age under India''s Universal Immunization Programme.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Which congenital condition is characterized by an extra copy of chromosome 18?',
 '[{"text":"Down syndrome (Trisomy 21)","isCorrect":false},{"text":"Edwards syndrome (Trisomy 18)","isCorrect":true},{"text":"Turner syndrome","isCorrect":false},{"text":"Klinefelter syndrome","isCorrect":false}]'::jsonb,
 null, 'Edwards syndrome results from an extra copy of chromosome 18 (Trisomy 18), typically associated with severe developmental abnormalities.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Kawasaki disease, an acute vasculitis with risk of coronary artery involvement, primarily affects which age group?',
 '[{"text":"Adolescents","isCorrect":false},{"text":"Young children (typically under 5 years)","isCorrect":true},{"text":"Adults over 60","isCorrect":false},{"text":"Newborns only","isCorrect":false}]'::jsonb,
 null, 'Kawasaki disease primarily affects young children, typically under the age of 5, and carries a risk of coronary artery aneurysms if untreated.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'The normal anterior fontanelle in an infant typically closes by approximately:',
 '[{"text":"2 months of age","isCorrect":false},{"text":"18 months of age","isCorrect":true},{"text":"5 years of age","isCorrect":false},{"text":"10 years of age","isCorrect":false}]'::jsonb,
 null, 'The anterior fontanelle typically closes by around 18 months of age, allowing for continued brain growth during infancy.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'easy', 'mcq',
 'Which psychiatric condition is characterized by alternating episodes of mania and depression?',
 '[{"text":"Major depressive disorder","isCorrect":false},{"text":"Bipolar disorder","isCorrect":true},{"text":"Generalized anxiety disorder","isCorrect":false},{"text":"Schizophrenia","isCorrect":false}]'::jsonb,
 null, 'Bipolar disorder is characterized by alternating episodes of mania (or hypomania) and depression.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Conversion disorder is characterized by:',
 '[{"text":"Neurological symptoms (e.g. paralysis, blindness) without an identifiable organic cause","isCorrect":true},{"text":"Deliberate faking of physical symptoms for financial gain","isCorrect":false},{"text":"A genuine structural brain lesion","isCorrect":false},{"text":"Persistent low mood only","isCorrect":false}]'::jsonb,
 null, 'Conversion disorder presents with neurological symptoms, such as paralysis or sensory loss, that cannot be explained by an identifiable medical or neurological condition, and are not intentionally produced.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which class of drugs is primarily used in the treatment of attention-deficit/hyperactivity disorder (ADHD)?',
 '[{"text":"Stimulants (e.g. methylphenidate)","isCorrect":true},{"text":"Benzodiazepines","isCorrect":false},{"text":"Typical antipsychotics","isCorrect":false},{"text":"Beta-blockers","isCorrect":false}]'::jsonb,
 null, 'Stimulant medications, such as methylphenidate, are the first-line pharmacological treatment for ADHD.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'Munchausen syndrome is characterized by:',
 '[{"text":"Deliberately feigning or inducing illness in oneself for attention","isCorrect":true},{"text":"A genuine, undiagnosed chronic illness","isCorrect":false},{"text":"Feigning illness in another person for personal gain","isCorrect":false},{"text":"Fear of medical settings","isCorrect":false}]'::jsonb,
 null, 'Munchausen syndrome (factitious disorder imposed on self) involves deliberately producing or exaggerating symptoms of illness in oneself, typically to assume the sick role and gain attention.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Painful, fluid-filled vesicles caused by herpes simplex virus, commonly around the mouth, are known as:',
 '[{"text":"Herpes labialis (cold sores)","isCorrect":true},{"text":"Impetigo","isCorrect":false},{"text":"Psoriasis","isCorrect":false},{"text":"Warts","isCorrect":false}]'::jsonb,
 null, 'Herpes labialis (cold sores), caused by herpes simplex virus (typically HSV-1), presents as painful, fluid-filled vesicles usually around the mouth.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'hard', 'mcq',
 'Lichen planus is classically characterized by the "6 Ps," which include purple, pruritic, polygonal, and:',
 '[{"text":"Planar papules and plaques","isCorrect":true},{"text":"Painful pustules only","isCorrect":false},{"text":"Painless patches only","isCorrect":false},{"text":"Peeling plaques only","isCorrect":false}]'::jsonb,
 null, 'Lichen planus is classically described by the "6 Ps": purple, pruritic, polygonal, planar papules and plaques.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'A benign, wart-like, "stuck-on" appearing skin growth commonly seen in older adults is called:',
 '[{"text":"Seborrheic keratosis","isCorrect":true},{"text":"Actinic keratosis","isCorrect":false},{"text":"Melanoma","isCorrect":false},{"text":"Basal cell carcinoma","isCorrect":false}]'::jsonb,
 null, 'Seborrheic keratosis is a common, benign skin growth in older adults, typically appearing waxy, "stuck-on," and well-demarcated.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Contact dermatitis is best described as:',
 '[{"text":"A viral skin infection","isCorrect":false},{"text":"An inflammatory skin reaction caused by direct contact with an irritant or allergen","isCorrect":true},{"text":"An autoimmune blistering disease","isCorrect":false},{"text":"A fungal skin infection","isCorrect":false}]'::jsonb,
 null, 'Contact dermatitis is an inflammatory skin reaction resulting from direct skin contact with an irritating substance or an allergen.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'easy', 'mcq',
 'A painless, gradually enlarging swelling of the thyroid gland is called a:',
 '[{"text":"Goiter","isCorrect":true},{"text":"Adenoma exclusively","isCorrect":false},{"text":"Cyst exclusively","isCorrect":false},{"text":"Abscess","isCorrect":false}]'::jsonb,
 null, 'A goiter refers to any enlargement of the thyroid gland, which may occur due to various underlying causes, including iodine deficiency or autoimmune disease.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common cause of large bowel obstruction in adults is:',
 '[{"text":"Adhesions","isCorrect":false},{"text":"Colorectal carcinoma","isCorrect":true},{"text":"Volvulus alone","isCorrect":false},{"text":"Hernia alone","isCorrect":false}]'::jsonb,
 null, 'Colorectal carcinoma is the most common cause of large bowel obstruction in adults, unlike small bowel obstruction, where adhesions predominate.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'easy', 'mcq',
 'Peritonitis is best described as:',
 '[{"text":"Inflammation of the peritoneum, often due to infection or perforation","isCorrect":true},{"text":"Inflammation of the pleura","isCorrect":false},{"text":"Inflammation of the pericardium","isCorrect":false},{"text":"A benign abdominal tumor","isCorrect":false}]'::jsonb,
 null, 'Peritonitis refers to inflammation of the peritoneum, commonly resulting from bacterial infection following perforation of an abdominal organ.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'hard', 'mcq',
 'A "Grey Turner''s sign" (bruising over the flanks) is associated with:',
 '[{"text":"Hemorrhagic (acute) pancreatitis","isCorrect":true},{"text":"Appendicitis","isCorrect":false},{"text":"Cholecystitis","isCorrect":false},{"text":"Simple gastritis","isCorrect":false}]'::jsonb,
 null, 'Grey Turner''s sign -- bruising or discoloration over the flanks -- is associated with severe hemorrhagic pancreatitis, reflecting retroperitoneal bleeding.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'A "clay shoveler''s fracture" involves fracture of which structure?',
 '[{"text":"The spinous process of a cervical/thoracic vertebra","isCorrect":true},{"text":"The femoral neck","isCorrect":false},{"text":"The distal radius","isCorrect":false},{"text":"The clavicle","isCorrect":false}]'::jsonb,
 null, 'A clay shoveler''s fracture involves an avulsion fracture of the spinous process of a lower cervical or upper thoracic vertebra, classically from repetitive strain.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Gout is caused by the deposition of which type of crystals in joints?',
 '[{"text":"Calcium pyrophosphate crystals","isCorrect":false},{"text":"Monosodium urate crystals","isCorrect":true},{"text":"Calcium oxalate crystals","isCorrect":false},{"text":"Cholesterol crystals","isCorrect":false}]'::jsonb,
 null, 'Gout results from the deposition of monosodium urate crystals in joints, triggering an acute inflammatory response and pain.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'Club foot (talipes equinovarus) is a congenital deformity primarily affecting which part of the body?',
 '[{"text":"The hand","isCorrect":false},{"text":"The foot and ankle","isCorrect":true},{"text":"The spine","isCorrect":false},{"text":"The hip joint alone","isCorrect":false}]'::jsonb,
 null, 'Club foot (talipes equinovarus) is a congenital deformity in which the foot is twisted out of its normal shape or position, primarily affecting the foot and ankle.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common benign bone tumor is:',
 '[{"text":"Osteochondroma","isCorrect":true},{"text":"Osteosarcoma","isCorrect":false},{"text":"Ewing sarcoma","isCorrect":false},{"text":"Chondrosarcoma","isCorrect":false}]'::jsonb,
 null, 'Osteochondroma is the most common benign bone tumor, typically arising near the growth plate of long bones in adolescents.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'The normal duration of the menstrual cycle is approximately:',
 '[{"text":"14 days","isCorrect":false},{"text":"28 days","isCorrect":true},{"text":"45 days","isCorrect":false},{"text":"60 days","isCorrect":false}]'::jsonb,
 null, 'The average menstrual cycle length is approximately 28 days, though normal cycles can range from about 21 to 35 days.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Premature Rupture of Membranes (PROM) refers to:',
 '[{"text":"Rupture of fetal membranes before the onset of labor","isCorrect":true},{"text":"A miscarriage in the first trimester","isCorrect":false},{"text":"An abnormally short pregnancy","isCorrect":false},{"text":"Premature delivery of the placenta","isCorrect":false}]'::jsonb,
 null, 'PROM refers to rupture of the amniotic membranes occurring before the onset of labor, which carries risks of infection and preterm birth.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Gestational diabetes is typically screened for using which test?',
 '[{"text":"Oral Glucose Tolerance Test (OGTT)","isCorrect":true},{"text":"Complete blood count","isCorrect":false},{"text":"Liver function test","isCorrect":false},{"text":"Urine culture","isCorrect":false}]'::jsonb,
 null, 'The Oral Glucose Tolerance Test (OGTT) is the standard screening and diagnostic test used to detect gestational diabetes during pregnancy.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The most common benign tumor of the uterus is the:',
 '[{"text":"Uterine fibroid (leiomyoma)","isCorrect":true},{"text":"Endometrial polyp exclusively","isCorrect":false},{"text":"Ovarian cyst","isCorrect":false},{"text":"Cervical polyp exclusively","isCorrect":false}]'::jsonb,
 null, 'Uterine fibroids (leiomyomas), benign smooth muscle tumors of the uterus, are the most common benign uterine tumors, particularly common in women of reproductive age.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Which drug is used to reverse the effects of non-depolarizing neuromuscular blocking agents?',
 '[{"text":"Succinylcholine","isCorrect":false},{"text":"Neostigmine","isCorrect":true},{"text":"Naloxone","isCorrect":false},{"text":"Flumazenil","isCorrect":false}]'::jsonb,
 null, 'Neostigmine, an acetylcholinesterase inhibitor, is used to reverse the effects of non-depolarizing neuromuscular blockers by increasing acetylcholine availability at the neuromuscular junction.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The normal range of central venous pressure is approximately:',
 '[{"text":"2-8 mmHg","isCorrect":true},{"text":"20-30 mmHg","isCorrect":false},{"text":"40-50 mmHg","isCorrect":false},{"text":"60-70 mmHg","isCorrect":false}]'::jsonb,
 null, 'Normal central venous pressure typically ranges from about 2 to 8 mmHg, reflecting right atrial filling pressure.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Malignant hyperthermia is classically triggered by which class of anesthetic agents?',
 '[{"text":"Volatile inhalational anesthetics (and succinylcholine)","isCorrect":true},{"text":"Local anesthetics only","isCorrect":false},{"text":"Intravenous opioids only","isCorrect":false},{"text":"Nitrous oxide alone","isCorrect":false}]'::jsonb,
 null, 'Malignant hyperthermia is classically triggered by volatile inhalational anesthetics and the depolarizing muscle relaxant succinylcholine in genetically susceptible individuals.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Which scoring system predicts the difficulty of endotracheal intubation based on visibility of oropharyngeal structures?',
 '[{"text":"Mallampati score","isCorrect":true},{"text":"Glasgow Coma Scale","isCorrect":false},{"text":"APGAR score","isCorrect":false},{"text":"ASA physical status classification","isCorrect":false}]'::jsonb,
 null, 'The Mallampati score assesses the visibility of oropharyngeal structures (like the uvula and soft palate) with the mouth open, helping predict the difficulty of intubation.');
