-- supabase/sql/exam_question_bank_class4_set1.sql
--
-- First curated question-bank batch for 'Class 4' (see exam_patterns_class4.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 4's MCQ-only,
-- no-negative-marking pattern. 9 chapters (3 per subject x 3 subjects) each get 4 questions, mostly
-- easy/medium with one hard per chapter, reflecting the small hard share introduced in
-- exam_patterns_class4.sql. Pitched one notch above Class 3 (see
-- exam_question_bank_class3_set1.sql) -- tenses, fractions, 5-digit numbers, and civics/heritage.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class4.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Tenses (Present, Past, Future) and Types of Sentences
('Class 4', 'English', 'Tenses (Present, Past, Future) and Types of Sentences', 'easy', 'mcq',
 'Choose the correct past tense of ''go''.',
 '[{"text":"Goed","isCorrect":false},{"text":"Went","isCorrect":true},{"text":"Gone","isCorrect":false},{"text":"Going","isCorrect":false}]'::jsonb,
 null, 'The past tense of ''go'' is the irregular verb ''went''.'),
('Class 4', 'English', 'Tenses (Present, Past, Future) and Types of Sentences', 'easy', 'mcq',
 'Which sentence is in the future tense?',
 '[{"text":"She sings a song.","isCorrect":false},{"text":"She sang a song.","isCorrect":false},{"text":"She will sing a song.","isCorrect":true},{"text":"She is singing a song.","isCorrect":false}]'::jsonb,
 null, '''Will sing'' shows an action that has not happened yet, marking the future tense.'),
('Class 4', 'English', 'Tenses (Present, Past, Future) and Types of Sentences', 'medium', 'mcq',
 'Which type of sentence is: "What a beautiful garden this is!"',
 '[{"text":"Assertive","isCorrect":false},{"text":"Interrogative","isCorrect":false},{"text":"Exclamatory","isCorrect":true},{"text":"Imperative","isCorrect":false}]'::jsonb,
 null, 'A sentence that expresses strong feeling and ends with an exclamation mark is an exclamatory sentence.'),
('Class 4', 'English', 'Tenses (Present, Past, Future) and Types of Sentences', 'hard', 'mcq',
 'Choose the sentence written in the correct simple present tense.',
 '[{"text":"He play cricket every day.","isCorrect":false},{"text":"He plays cricket every day.","isCorrect":true},{"text":"He playing cricket every day.","isCorrect":false},{"text":"He played cricket every day.","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject (''He'') in the simple present tense, the verb takes an -s: ''plays''.'),

-- English: Adverbs, Conjunctions and Prefixes-Suffixes
('Class 4', 'English', 'Adverbs, Conjunctions and Prefixes-Suffixes', 'easy', 'mcq',
 'Which word tells us HOW an action is done in "She sings sweetly"?',
 '[{"text":"She","isCorrect":false},{"text":"Sings","isCorrect":false},{"text":"Sweetly","isCorrect":true},{"text":"None","isCorrect":false}]'::jsonb,
 null, '''Sweetly'' describes how she sings, making it an adverb.'),
('Class 4', 'English', 'Adverbs, Conjunctions and Prefixes-Suffixes', 'easy', 'mcq',
 'Which word joins the two parts of "I was tired ___ I kept working"?',
 '[{"text":"but","isCorrect":true},{"text":"and","isCorrect":false},{"text":"because","isCorrect":false},{"text":"or","isCorrect":false}]'::jsonb,
 null, '''But'' is the conjunction that correctly joins two contrasting ideas.'),
('Class 4', 'English', 'Adverbs, Conjunctions and Prefixes-Suffixes', 'medium', 'mcq',
 'Adding the prefix ''un-'' to ''happy'' gives a word that means:',
 '[{"text":"Very happy","isCorrect":false},{"text":"Not happy","isCorrect":true},{"text":"More happy","isCorrect":false},{"text":"Happy again","isCorrect":false}]'::jsonb,
 null, 'The prefix ''un-'' means ''not'', so ''unhappy'' means ''not happy''.'),
('Class 4', 'English', 'Adverbs, Conjunctions and Prefixes-Suffixes', 'hard', 'mcq',
 'Adding the suffix ''-ful'' to ''care'' gives a word that means:',
 '[{"text":"Without care","isCorrect":false},{"text":"Full of care","isCorrect":true},{"text":"To take care","isCorrect":false},{"text":"One who cares for others professionally","isCorrect":false}]'::jsonb,
 null, 'The suffix ''-ful'' means ''full of'', so ''careful'' means ''full of care''.'),

-- English: Reading Comprehension and Vocabulary
('Class 4', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'Read: "Meera planted a mango sapling in her garden and watered it daily." What did Meera plant?',
 '[{"text":"A rose bush","isCorrect":false},{"text":"A mango sapling","isCorrect":true},{"text":"A vegetable","isCorrect":false},{"text":"A tomato plant","isCorrect":false}]'::jsonb,
 null, 'The passage says Meera planted a mango sapling.'),
('Class 4', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'A word that means the same as ''enormous'' is:',
 '[{"text":"Tiny","isCorrect":false},{"text":"Huge","isCorrect":true},{"text":"Narrow","isCorrect":false},{"text":"Slow","isCorrect":false}]'::jsonb,
 null, '''Huge'' means the same as ''enormous''.'),
('Class 4', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'Read: "Despite the heavy rain, the children walked to school wearing raincoats." Why did the children still go to school?',
 '[{"text":"Because it stopped raining","isCorrect":false},{"text":"Because they wore raincoats","isCorrect":true},{"text":"Because school was cancelled","isCorrect":false},{"text":"Because they stayed home","isCorrect":false}]'::jsonb,
 null, 'The passage says the children walked to school wearing raincoats despite the heavy rain.'),
('Class 4', 'English', 'Reading Comprehension and Vocabulary', 'hard', 'mcq',
 'A word that means the opposite of ''generous'' is:',
 '[{"text":"Kind","isCorrect":false},{"text":"Selfish","isCorrect":true},{"text":"Helpful","isCorrect":false},{"text":"Caring","isCorrect":false}]'::jsonb,
 null, '''Selfish'' means the opposite of ''generous''.'),

-- Mathematics: Numbers up to 1,00,000 (Place Value and Rounding)
('Class 4', 'Mathematics', 'Numbers up to 1,00,000 (Place Value and Rounding)', 'easy', 'mcq',
 'What number comes just after 49999?',
 '[{"text":"49998","isCorrect":false},{"text":"50000","isCorrect":true},{"text":"50001","isCorrect":false},{"text":"50009","isCorrect":false}]'::jsonb,
 null, 'Counting up from 49999, the next number is 50000.'),
('Class 4', 'Mathematics', 'Numbers up to 1,00,000 (Place Value and Rounding)', 'easy', 'mcq',
 'In the number 84205, what is the digit in the ten-thousands place?',
 '[{"text":"8","isCorrect":true},{"text":"4","isCorrect":false},{"text":"2","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'In 84205, 8 is in the ten-thousands place, 4 in the thousands, 2 in the hundreds, 0 in the tens, and 5 in the ones place.'),
('Class 4', 'Mathematics', 'Numbers up to 1,00,000 (Place Value and Rounding)', 'medium', 'mcq',
 'Round 3672 to the nearest hundred.',
 '[{"text":"3600","isCorrect":false},{"text":"3700","isCorrect":true},{"text":"3670","isCorrect":false},{"text":"3800","isCorrect":false}]'::jsonb,
 null, 'Since the tens digit (7) is 5 or more, 3672 rounds up to 3700.'),
('Class 4', 'Mathematics', 'Numbers up to 1,00,000 (Place Value and Rounding)', 'hard', 'mcq',
 'Round 45500 to the nearest thousand.',
 '[{"text":"45000","isCorrect":false},{"text":"46000","isCorrect":true},{"text":"45500","isCorrect":false},{"text":"44000","isCorrect":false}]'::jsonb,
 null, 'Since the hundreds digit (5) means the number is exactly halfway, it rounds up to 46000.'),

-- Mathematics: Multiplication, Division, Factors and Multiples
('Class 4', 'Mathematics', 'Multiplication, Division, Factors and Multiples', 'easy', 'mcq',
 '124 x 3 = ?',
 '[{"text":"362","isCorrect":false},{"text":"372","isCorrect":true},{"text":"382","isCorrect":false},{"text":"342","isCorrect":false}]'::jsonb,
 null, '124 x 3 = 372.'),
('Class 4', 'Mathematics', 'Multiplication, Division, Factors and Multiples', 'easy', 'mcq',
 '144 / 12 = ?',
 '[{"text":"11","isCorrect":false},{"text":"12","isCorrect":true},{"text":"13","isCorrect":false},{"text":"14","isCorrect":false}]'::jsonb,
 null, '144 / 12 = 12.'),
('Class 4', 'Mathematics', 'Multiplication, Division, Factors and Multiples', 'medium', 'mcq',
 'Which of these is a factor of 36?',
 '[{"text":"5","isCorrect":false},{"text":"7","isCorrect":false},{"text":"9","isCorrect":true},{"text":"11","isCorrect":false}]'::jsonb,
 null, '9 divides evenly into 36 (36 = 9 x 4), so it is a factor of 36.'),
('Class 4', 'Mathematics', 'Multiplication, Division, Factors and Multiples', 'hard', 'mcq',
 'What is the lowest common multiple (LCM) of 4 and 6?',
 '[{"text":"10","isCorrect":false},{"text":"12","isCorrect":true},{"text":"24","isCorrect":false},{"text":"18","isCorrect":false}]'::jsonb,
 null, 'The multiples of 4 are 4, 8, 12... and of 6 are 6, 12... The smallest common multiple is 12.'),

-- Mathematics: Fractions, Measurement and Geometry
('Class 4', 'Mathematics', 'Fractions, Measurement and Geometry', 'easy', 'mcq',
 'Which fraction represents half of a whole?',
 '[{"text":"1/4","isCorrect":false},{"text":"1/2","isCorrect":true},{"text":"1/3","isCorrect":false},{"text":"2/2","isCorrect":false}]'::jsonb,
 null, '1/2 represents one part out of two equal parts, or half.'),
('Class 4', 'Mathematics', 'Fractions, Measurement and Geometry', 'easy', 'mcq',
 'How many grams make one kilogram?',
 '[{"text":"100","isCorrect":false},{"text":"1000","isCorrect":true},{"text":"10000","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, '1000 grams make 1 kilogram.'),
('Class 4', 'Mathematics', 'Fractions, Measurement and Geometry', 'medium', 'mcq',
 'Which of these fractions is the largest?',
 '[{"text":"1/4","isCorrect":false},{"text":"1/2","isCorrect":true},{"text":"1/8","isCorrect":false},{"text":"1/6","isCorrect":false}]'::jsonb,
 null, 'When the numerator is the same (1), a smaller denominator means a larger fraction, so 1/2 is the largest.'),
('Class 4', 'Mathematics', 'Fractions, Measurement and Geometry', 'hard', 'mcq',
 'What is the perimeter of a rectangle with length 12 cm and breadth 5 cm?',
 '[{"text":"17 cm","isCorrect":false},{"text":"34 cm","isCorrect":true},{"text":"60 cm","isCorrect":false},{"text":"24 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a rectangle = 2 x (length + breadth) = 2 x (12 + 5) = 34 cm.'),

-- EVS: Food, Digestion and Health
('Class 4', 'EVS', 'Food, Digestion and Health', 'easy', 'mcq',
 'Which organ in our body digests food?',
 '[{"text":"Heart","isCorrect":false},{"text":"Stomach","isCorrect":true},{"text":"Lungs","isCorrect":false},{"text":"Skin","isCorrect":false}]'::jsonb,
 null, 'The stomach breaks down food as part of the digestion process.'),
('Class 4', 'EVS', 'Food, Digestion and Health', 'easy', 'mcq',
 'Which vitamin do we mainly get from sunlight?',
 '[{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":true},{"text":"Vitamin K","isCorrect":false}]'::jsonb,
 null, 'Our body produces Vitamin D when the skin is exposed to sunlight.'),
('Class 4', 'EVS', 'Food, Digestion and Health', 'medium', 'mcq',
 'Which of these food groups gives our body the most energy?',
 '[{"text":"Carbohydrates","isCorrect":true},{"text":"Vitamins","isCorrect":false},{"text":"Minerals","isCorrect":false},{"text":"Water","isCorrect":false}]'::jsonb,
 null, 'Carbohydrates are the body''s main source of energy.'),
('Class 4', 'EVS', 'Food, Digestion and Health', 'hard', 'mcq',
 'A diet that includes food from all the major food groups in the right amount is called a:',
 '[{"text":"Balanced diet","isCorrect":true},{"text":"Junk diet","isCorrect":false},{"text":"Liquid diet","isCorrect":false},{"text":"Single-food diet","isCorrect":false}]'::jsonb,
 null, 'A balanced diet includes the right amount of food from all major food groups.'),

-- EVS: Adaptations, Habitats and Natural Resources
('Class 4', 'EVS', 'Adaptations, Habitats and Natural Resources', 'easy', 'mcq',
 'A camel can survive in the desert for a long time without water mainly because of its:',
 '[{"text":"Long legs","isCorrect":false},{"text":"Hump storing fat","isCorrect":true},{"text":"Thick fur","isCorrect":false},{"text":"Big ears","isCorrect":false}]'::jsonb,
 null, 'A camel''s hump stores fat, which helps it survive without water for long periods.'),
('Class 4', 'EVS', 'Adaptations, Habitats and Natural Resources', 'easy', 'mcq',
 'Which of these is a natural resource?',
 '[{"text":"Plastic","isCorrect":false},{"text":"Water","isCorrect":true},{"text":"Glass","isCorrect":false},{"text":"Cement","isCorrect":false}]'::jsonb,
 null, 'Water is found in nature and is a natural resource, unlike man-made materials such as plastic, glass, and cement.'),
('Class 4', 'EVS', 'Adaptations, Habitats and Natural Resources', 'medium', 'mcq',
 'Fish have gills that help them to:',
 '[{"text":"See in the dark","isCorrect":false},{"text":"Breathe underwater","isCorrect":true},{"text":"Swim faster","isCorrect":false},{"text":"Stay warm","isCorrect":false}]'::jsonb,
 null, 'Gills allow fish to take in oxygen dissolved in water, letting them breathe underwater.'),
('Class 4', 'EVS', 'Adaptations, Habitats and Natural Resources', 'hard', 'mcq',
 'Which of these is a renewable source of energy?',
 '[{"text":"Coal","isCorrect":false},{"text":"Petroleum","isCorrect":false},{"text":"Solar energy","isCorrect":true},{"text":"Natural gas","isCorrect":false}]'::jsonb,
 null, 'Solar energy comes from the sun and does not get used up, making it a renewable source of energy.'),

-- EVS: Our State, Government and Heritage
('Class 4', 'EVS', 'Our State, Government and Heritage', 'easy', 'mcq',
 'Who is the head of a village-level local government body in India?',
 '[{"text":"Sarpanch","isCorrect":true},{"text":"Governor","isCorrect":false},{"text":"Prime Minister","isCorrect":false},{"text":"Mayor","isCorrect":false}]'::jsonb,
 null, 'A Sarpanch is the elected head of a village Panchayat, the local government body.'),
('Class 4', 'EVS', 'Our State, Government and Heritage', 'easy', 'mcq',
 'The Taj Mahal, a famous monument in India, is located in which state?',
 '[{"text":"Rajasthan","isCorrect":false},{"text":"Uttar Pradesh","isCorrect":true},{"text":"Punjab","isCorrect":false},{"text":"Bihar","isCorrect":false}]'::jsonb,
 null, 'The Taj Mahal is located in Agra, in the state of Uttar Pradesh.'),
('Class 4', 'EVS', 'Our State, Government and Heritage', 'medium', 'mcq',
 'Who is the elected head of a city-level local government body called a Municipal Corporation?',
 '[{"text":"Mayor","isCorrect":true},{"text":"Sarpanch","isCorrect":false},{"text":"Governor","isCorrect":false},{"text":"Collector","isCorrect":false}]'::jsonb,
 null, 'A Mayor heads the Municipal Corporation, the local government body for a city.'),
('Class 4', 'EVS', 'Our State, Government and Heritage', 'hard', 'mcq',
 'Which of these is an example of India''s cultural heritage passed down through generations?',
 '[{"text":"A folk dance","isCorrect":true},{"text":"A mobile phone","isCorrect":false},{"text":"A car","isCorrect":false},{"text":"A computer","isCorrect":false}]'::jsonb,
 null, 'A folk dance is a tradition passed down through generations, making it part of cultural heritage.');
