-- supabase/sql/exam_question_bank_rrb_group_d_set1.sql
--
-- First curated question-bank batch for 'RRB Group D' (see exam_patterns_rrb_group_d.sql for the
-- exam's structure). Same exam_question_bank table/schema as the other sets -- no migration
-- needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Pitched at a 10th-standard level, similar difficulty to SSC-GD
-- Constable (see exam_question_bank_ssc_gd_set1.sql). Non-Verbal Reasoning again uses
-- text-describable puzzles in place of figure-based questions, which need images this schema
-- can't provide. 16 chapters (4 per section x 4 sections) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_rrb_group_d.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Mathematics: Number System and Simplification
('RRB Group D', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Simplify: 25 + 5 x 3 - 10',
 '[{"text":"25","isCorrect":false},{"text":"30","isCorrect":true},{"text":"20","isCorrect":false},{"text":"40","isCorrect":false}]'::jsonb,
 null, 'Following order of operations: 5 x 3 = 15, then 25 + 15 - 10 = 30.'),
('RRB Group D', 'Mathematics', 'Number System and Simplification', 'easy', 'mcq',
 'Which of the following numbers is divisible by 5?',
 '[{"text":"23","isCorrect":false},{"text":"37","isCorrect":false},{"text":"45","isCorrect":true},{"text":"62","isCorrect":false}]'::jsonb,
 null, '45 ends in 5, making it divisible by 5.'),
('RRB Group D', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the value of 12^2 - 8^2.',
 '[{"text":"80","isCorrect":true},{"text":"100","isCorrect":false},{"text":"144","isCorrect":false},{"text":"64","isCorrect":false}]'::jsonb,
 null, '12^2 = 144 and 8^2 = 64, so 144 - 64 = 80.'),
('RRB Group D', 'Mathematics', 'Number System and Simplification', 'medium', 'mcq',
 'Find the LCM of 8 and 12.',
 '[{"text":"16","isCorrect":false},{"text":"24","isCorrect":true},{"text":"32","isCorrect":false},{"text":"48","isCorrect":false}]'::jsonb,
 null, 'The multiples of 8 are 8, 16, 24... and of 12 are 12, 24... so the LCM is 24.'),

-- Mathematics: Percentage and Ratio
('RRB Group D', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 '50% of 80 is:',
 '[{"text":"20","isCorrect":false},{"text":"40","isCorrect":true},{"text":"60","isCorrect":false},{"text":"30","isCorrect":false}]'::jsonb,
 null, '50% of 80 = (50/100) x 80 = 40.'),
('RRB Group D', 'Mathematics', 'Percentage and Ratio', 'easy', 'mcq',
 'Express the ratio 2:5 as a percentage.',
 '[{"text":"20%","isCorrect":false},{"text":"40%","isCorrect":true},{"text":"25%","isCorrect":false},{"text":"50%","isCorrect":false}]'::jsonb,
 null, '2:5 as a fraction is 2/5, which equals 40%.'),
('RRB Group D', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'If 15% of a number is 45, find the number.',
 '[{"text":"225","isCorrect":false},{"text":"300","isCorrect":true},{"text":"350","isCorrect":false},{"text":"270","isCorrect":false}]'::jsonb,
 null, 'If 15% of x = 45, then x = 45 / 0.15 = 300.'),
('RRB Group D', 'Mathematics', 'Percentage and Ratio', 'medium', 'mcq',
 'Rs. 500 is divided in the ratio 2:3. Find the smaller share.',
 '[{"text":"Rs. 150","isCorrect":false},{"text":"Rs. 200","isCorrect":true},{"text":"Rs. 250","isCorrect":false},{"text":"Rs. 300","isCorrect":false}]'::jsonb,
 null, 'Total parts = 2+3 = 5. Smaller share = (2/5) x 500 = Rs. 200.'),

-- Mathematics: Profit Loss and Simple Interest
('RRB Group D', 'Mathematics', 'Profit Loss and Simple Interest', 'easy', 'mcq',
 'A man buys an item for Rs. 100 and sells it for Rs. 120. Find his profit.',
 '[{"text":"Rs. 10","isCorrect":false},{"text":"Rs. 20","isCorrect":true},{"text":"Rs. 30","isCorrect":false},{"text":"Rs. 15","isCorrect":false}]'::jsonb,
 null, 'Profit = Selling Price - Cost Price = 120 - 100 = Rs. 20.'),
('RRB Group D', 'Mathematics', 'Profit Loss and Simple Interest', 'easy', 'mcq',
 'The selling price of an item is Rs. 90 and the loss is Rs. 10. Find the cost price.',
 '[{"text":"Rs. 80","isCorrect":false},{"text":"Rs. 90","isCorrect":false},{"text":"Rs. 100","isCorrect":true},{"text":"Rs. 110","isCorrect":false}]'::jsonb,
 null, 'Cost Price = Selling Price + Loss = 90 + 10 = Rs. 100.'),
('RRB Group D', 'Mathematics', 'Profit Loss and Simple Interest', 'medium', 'mcq',
 'Find the simple interest on Rs. 800 at 5% per annum for 4 years.',
 '[{"text":"Rs. 120","isCorrect":false},{"text":"Rs. 160","isCorrect":true},{"text":"Rs. 100","isCorrect":false},{"text":"Rs. 200","isCorrect":false}]'::jsonb,
 null, 'Simple Interest = (Principal x Rate x Time) / 100 = (800 x 5 x 4) / 100 = Rs. 160.'),
('RRB Group D', 'Mathematics', 'Profit Loss and Simple Interest', 'medium', 'mcq',
 'A shopkeeper sells an item at a 10% loss for Rs. 450. Find the cost price.',
 '[{"text":"Rs. 480","isCorrect":false},{"text":"Rs. 500","isCorrect":true},{"text":"Rs. 495","isCorrect":false},{"text":"Rs. 520","isCorrect":false}]'::jsonb,
 null, 'If cost price is x, then x - 0.10x = 450, so 0.9x = 450, giving x = Rs. 500.'),

-- Mathematics: Mensuration and Time Work
('RRB Group D', 'Mathematics', 'Mensuration and Time Work', 'easy', 'mcq',
 'Find the perimeter of a square with side 9 cm.',
 '[{"text":"18 cm","isCorrect":false},{"text":"36 cm","isCorrect":true},{"text":"27 cm","isCorrect":false},{"text":"81 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a square = 4 x side = 4 x 9 = 36 cm.'),
('RRB Group D', 'Mathematics', 'Mensuration and Time Work', 'easy', 'mcq',
 'A can finish a job in 5 days. What part of the job does he finish in 2 days?',
 '[{"text":"2/5","isCorrect":true},{"text":"1/5","isCorrect":false},{"text":"3/5","isCorrect":false},{"text":"5/2","isCorrect":false}]'::jsonb,
 null, 'If A finishes the whole job in 5 days, he completes 1/5 per day, so in 2 days he completes 2/5.'),
('RRB Group D', 'Mathematics', 'Mensuration and Time Work', 'medium', 'mcq',
 'Find the area of a rectangle with length 12 cm and breadth 7 cm.',
 '[{"text":"19 cm^2","isCorrect":false},{"text":"84 cm^2","isCorrect":true},{"text":"70 cm^2","isCorrect":false},{"text":"94 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a rectangle = length x breadth = 12 x 7 = 84 cm^2.'),
('RRB Group D', 'Mathematics', 'Mensuration and Time Work', 'medium', 'mcq',
 'A and B together can complete a task in 4 days. A alone takes 6 days. How long will B alone take?',
 '[{"text":"10 days","isCorrect":false},{"text":"12 days","isCorrect":true},{"text":"8 days","isCorrect":false},{"text":"14 days","isCorrect":false}]'::jsonb,
 null, 'B''s one-day work = 1/4 - 1/6 = 1/12, so B alone takes 12 days.'),

-- General Intelligence and Reasoning: Analogies and Classification
('RRB Group D', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Sun is to Day as Moon is to:',
 '[{"text":"Star","isCorrect":false},{"text":"Night","isCorrect":true},{"text":"Sky","isCorrect":false},{"text":"Light","isCorrect":false}]'::jsonb,
 null, 'The sun is associated with the day, just as the moon is associated with the night.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Dog","isCorrect":false},{"text":"Cat","isCorrect":false},{"text":"Cow","isCorrect":false},{"text":"Snake","isCorrect":true}]'::jsonb,
 null, 'Dog, Cat and Cow are mammals, while a Snake is a reptile.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Author is to Book as Sculptor is to:',
 '[{"text":"Chisel","isCorrect":false},{"text":"Statue","isCorrect":true},{"text":"Stone","isCorrect":false},{"text":"Museum","isCorrect":false}]'::jsonb,
 null, 'An author creates a book, just as a sculptor creates a statue.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Wheat","isCorrect":false},{"text":"Rice","isCorrect":false},{"text":"Maize","isCorrect":false},{"text":"Cotton","isCorrect":true}]'::jsonb,
 null, 'Wheat, Rice and Maize are food crops, while Cotton is a fiber crop.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('RRB Group D', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 2, 4, 8, 16, ?',
 '[{"text":"24","isCorrect":false},{"text":"28","isCorrect":false},{"text":"32","isCorrect":true},{"text":"36","isCorrect":false}]'::jsonb,
 null, 'Each term doubles the previous one, so the next term is 16 x 2 = 32.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'In a certain code, CAT is written as DBU. How is BAG written in that code?',
 '[{"text":"CBH","isCorrect":true},{"text":"CBI","isCorrect":false},{"text":"DBH","isCorrect":false},{"text":"CCH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: B->C, A->B, G->H, giving CBH.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 5, 11, 23, 47, ?',
 '[{"text":"90","isCorrect":false},{"text":"94","isCorrect":false},{"text":"95","isCorrect":true},{"text":"96","isCorrect":false}]'::jsonb,
 null, 'Each term doubles the previous term and adds 1, so the next term is 47 x 2 + 1 = 95.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If LION is coded as MJPO, how is TIGER coded in the same language?',
 '[{"text":"UJHFS","isCorrect":true},{"text":"UJGFS","isCorrect":false},{"text":"UIHFS","isCorrect":false},{"text":"VJHFS","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so TIGER becomes UJHFS.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('RRB Group D', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many vertices does a cube have?',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":true},{"text":"10","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'A cube has 8 vertices (corners), 12 edges, and 6 faces.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A clock''s mirror image shows 8:20. What is the actual time?',
 '[{"text":"3:40","isCorrect":true},{"text":"4:40","isCorrect":false},{"text":"8:40","isCorrect":false},{"text":"3:20","isCorrect":false}]'::jsonb,
 null, 'A clock''s mirror image time and actual time together add up to 11:60, so the actual time is 11:60 - 8:20 = 3:40.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'How many triangles are formed in a 5-pointed star (pentagram) figure?',
 '[{"text":"5","isCorrect":false},{"text":"10","isCorrect":true},{"text":"15","isCorrect":false},{"text":"8","isCorrect":false}]'::jsonb,
 null, 'A 5-pointed star (pentagram) contains 10 triangles when all points and intersections are counted.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'In a line of people, A is 20th from the left and 15th from the right. How many people are in the line?',
 '[{"text":"34","isCorrect":true},{"text":"35","isCorrect":false},{"text":"33","isCorrect":false},{"text":"36","isCorrect":false}]'::jsonb,
 null, 'Total = (position from left) + (position from right) - 1 = 20 + 15 - 1 = 34.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('RRB Group D', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'A is the brother of B. B is the daughter of C. How is A related to C?',
 '[{"text":"Son","isCorrect":true},{"text":"Nephew","isCorrect":false},{"text":"Father","isCorrect":false},{"text":"Brother","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s brother and B is C''s daughter, A is also C''s child, i.e. C''s son.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A person walks 9 km south, then 12 km east. How far is he from his starting point?',
 '[{"text":"15 km","isCorrect":true},{"text":"21 km","isCorrect":false},{"text":"12 km","isCorrect":false},{"text":"18 km","isCorrect":false}]'::jsonb,
 null, 'By the Pythagorean theorem, the distance is sqrt(9^2 + 12^2) = sqrt(225) = 15 km.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a man, a woman said, "His father is the only son of my grandfather," and her own father has no siblings. How is the man related to the woman?',
 '[{"text":"Brother","isCorrect":true},{"text":"Cousin","isCorrect":false},{"text":"Father","isCorrect":false},{"text":"Son","isCorrect":false}]'::jsonb,
 null, 'Since the woman''s father has no siblings, "my grandfather''s only son" refers to her own father, meaning the man shares the same father as the woman -- making him her brother.'),
('RRB Group D', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A man starts walking north, walks 4 km, turns right, walks 3 km, then turns right again and walks 4 km. How far and in which direction is he from his starting point?',
 '[{"text":"3 km East","isCorrect":true},{"text":"3 km West","isCorrect":false},{"text":"8 km North","isCorrect":false},{"text":"7 km","isCorrect":false}]'::jsonb,
 null, 'Walking north 4 km, then right (east) 3 km, then right (south) 4 km cancels the initial northward distance, leaving him 3 km east of the start.'),

-- General Science: Physics Basics
('RRB Group D', 'General Science', 'Physics Basics', 'easy', 'mcq',
 'What is the SI unit of length?',
 '[{"text":"Kilogram","isCorrect":false},{"text":"Meter","isCorrect":true},{"text":"Second","isCorrect":false},{"text":"Ampere","isCorrect":false}]'::jsonb,
 null, 'The SI unit of length is the meter.'),
('RRB Group D', 'General Science', 'Physics Basics', 'easy', 'mcq',
 'Which force pulls objects toward the Earth?',
 '[{"text":"Magnetic force","isCorrect":false},{"text":"Gravitational force","isCorrect":true},{"text":"Frictional force","isCorrect":false},{"text":"Electric force","isCorrect":false}]'::jsonb,
 null, 'Gravitational force is the force that pulls objects toward the Earth.'),
('RRB Group D', 'General Science', 'Physics Basics', 'medium', 'mcq',
 'What is the SI unit of power?',
 '[{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":true},{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'The SI unit of power is the Watt, defined as one Joule per second.'),
('RRB Group D', 'General Science', 'Physics Basics', 'medium', 'mcq',
 'Sound travels fastest through which medium?',
 '[{"text":"Air","isCorrect":false},{"text":"Water","isCorrect":false},{"text":"Solid","isCorrect":true},{"text":"Vacuum","isCorrect":false}]'::jsonb,
 null, 'Sound travels fastest through solids because their particles are most tightly packed, allowing faster vibration transfer.'),

-- General Science: Chemistry Basics
('RRB Group D', 'General Science', 'Chemistry Basics', 'easy', 'mcq',
 'What is the chemical symbol for Gold?',
 '[{"text":"Ag","isCorrect":false},{"text":"Au","isCorrect":true},{"text":"Fe","isCorrect":false},{"text":"Gd","isCorrect":false}]'::jsonb,
 null, 'The chemical symbol for Gold is Au, from its Latin name "aurum".'),
('RRB Group D', 'General Science', 'Chemistry Basics', 'easy', 'mcq',
 'Which gas do plants absorb from the atmosphere for photosynthesis?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Nitrogen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":true},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Plants absorb carbon dioxide from the air to use in photosynthesis.'),
('RRB Group D', 'General Science', 'Chemistry Basics', 'medium', 'mcq',
 'What is the pH value of pure water?',
 '[{"text":"5","isCorrect":false},{"text":"7","isCorrect":true},{"text":"9","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'Pure water is neutral, with a pH value of 7.'),
('RRB Group D', 'General Science', 'Chemistry Basics', 'medium', 'mcq',
 'Rust on iron is chemically known as:',
 '[{"text":"Iron oxide","isCorrect":true},{"text":"Iron sulfide","isCorrect":false},{"text":"Iron carbide","isCorrect":false},{"text":"Iron nitride","isCorrect":false}]'::jsonb,
 null, 'Rust is chemically iron oxide, formed when iron reacts with oxygen and moisture.'),

-- General Science: Biology Basics
('RRB Group D', 'General Science', 'Biology Basics', 'easy', 'mcq',
 'Which part of the human body pumps blood?',
 '[{"text":"Lungs","isCorrect":false},{"text":"Heart","isCorrect":true},{"text":"Liver","isCorrect":false},{"text":"Brain","isCorrect":false}]'::jsonb,
 null, 'The heart pumps blood throughout the human body.'),
('RRB Group D', 'General Science', 'Biology Basics', 'easy', 'mcq',
 'Which organ in the human body is responsible for producing insulin?',
 '[{"text":"Liver","isCorrect":false},{"text":"Pancreas","isCorrect":true},{"text":"Kidney","isCorrect":false},{"text":"Stomach","isCorrect":false}]'::jsonb,
 null, 'The pancreas produces insulin, a hormone that regulates blood sugar levels.'),
('RRB Group D', 'General Science', 'Biology Basics', 'medium', 'mcq',
 'How many chambers does the human heart have?',
 '[{"text":"2","isCorrect":false},{"text":"3","isCorrect":false},{"text":"4","isCorrect":true},{"text":"5","isCorrect":false}]'::jsonb,
 null, 'The human heart has 4 chambers: two atria and two ventricles.'),
('RRB Group D', 'General Science', 'Biology Basics', 'medium', 'mcq',
 'Deficiency of which vitamin causes night blindness?',
 '[{"text":"Vitamin A","isCorrect":true},{"text":"Vitamin B","isCorrect":false},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":false}]'::jsonb,
 null, 'A deficiency of Vitamin A causes night blindness.'),

-- General Science: Everyday Science and Technology
('RRB Group D', 'General Science', 'Everyday Science and Technology', 'easy', 'mcq',
 'Which device is used to measure temperature?',
 '[{"text":"Barometer","isCorrect":false},{"text":"Thermometer","isCorrect":true},{"text":"Hygrometer","isCorrect":false},{"text":"Anemometer","isCorrect":false}]'::jsonb,
 null, 'A thermometer is used to measure temperature.'),
('RRB Group D', 'General Science', 'Everyday Science and Technology', 'easy', 'mcq',
 'What does LED stand for?',
 '[{"text":"Light Emitting Diode","isCorrect":true},{"text":"Low Energy Device","isCorrect":false},{"text":"Light Energy Display","isCorrect":false},{"text":"Linear Electric Diode","isCorrect":false}]'::jsonb,
 null, 'LED stands for Light Emitting Diode.'),
('RRB Group D', 'General Science', 'Everyday Science and Technology', 'medium', 'mcq',
 'Which gas is commonly used to fill balloons so they float in air?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Helium","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":false}]'::jsonb,
 null, 'Helium is lighter than air and non-flammable, making it ideal for filling floating balloons.'),
('RRB Group D', 'General Science', 'Everyday Science and Technology', 'medium', 'mcq',
 'What is the full form of Wi-Fi, as commonly used?',
 '[{"text":"Wireless Fidelity","isCorrect":true},{"text":"Wide Fidelity","isCorrect":false},{"text":"Wireless Network","isCorrect":false},{"text":"Wide Internet","isCorrect":false}]'::jsonb,
 null, 'Wi-Fi is commonly understood to stand for "Wireless Fidelity", referring to wireless networking technology.'),

-- General Awareness and Current Affairs: Indian History and Culture
('RRB Group D', 'General Awareness and Current Affairs', 'Indian History and Culture', 'easy', 'mcq',
 'Who gave the slogan "Jai Hind"?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"Subhas Chandra Bose","isCorrect":true},{"text":"Bhagat Singh","isCorrect":false},{"text":"Jawaharlal Nehru","isCorrect":false}]'::jsonb,
 null, 'Subhas Chandra Bose gave the famous slogan "Jai Hind".'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian History and Culture', 'easy', 'mcq',
 'In which year did Mahatma Gandhi start the Non-Cooperation Movement?',
 '[{"text":"1920","isCorrect":true},{"text":"1930","isCorrect":false},{"text":"1942","isCorrect":false},{"text":"1919","isCorrect":false}]'::jsonb,
 null, 'The Non-Cooperation Movement was launched by Mahatma Gandhi in 1920.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian History and Culture', 'medium', 'mcq',
 'Who was the founder of the Slave Dynasty in India?',
 '[{"text":"Qutb-ud-din Aibak","isCorrect":true},{"text":"Iltutmish","isCorrect":false},{"text":"Balban","isCorrect":false},{"text":"Razia Sultan","isCorrect":false}]'::jsonb,
 null, 'Qutb-ud-din Aibak founded the Slave Dynasty (Mamluk Dynasty) in 1206.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian History and Culture', 'medium', 'mcq',
 'The Harappan (Indus Valley) civilization belongs to which age?',
 '[{"text":"Stone Age","isCorrect":false},{"text":"Bronze Age","isCorrect":true},{"text":"Iron Age","isCorrect":false},{"text":"Vedic Age","isCorrect":false}]'::jsonb,
 null, 'The Harappan civilization is classified as a Bronze Age civilization.'),

-- General Awareness and Current Affairs: Indian Polity and Geography
('RRB Group D', 'General Awareness and Current Affairs', 'Indian Polity and Geography', 'easy', 'mcq',
 'What is the minimum age required to become a member of the Lok Sabha?',
 '[{"text":"18 years","isCorrect":false},{"text":"21 years","isCorrect":false},{"text":"25 years","isCorrect":true},{"text":"30 years","isCorrect":false}]'::jsonb,
 null, 'A person must be at least 25 years old to become a member of the Lok Sabha.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the southernmost point of India?',
 '[{"text":"Kanyakumari","isCorrect":false},{"text":"Indira Point","isCorrect":true},{"text":"Rameswaram","isCorrect":false},{"text":"Kochi","isCorrect":false}]'::jsonb,
 null, 'Indira Point, located in the Andaman and Nicobar Islands, is the southernmost point of India.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian Polity and Geography', 'medium', 'mcq',
 'Who is the first woman President of India?',
 '[{"text":"Pratibha Patil","isCorrect":true},{"text":"Droupadi Murmu","isCorrect":false},{"text":"Sonia Gandhi","isCorrect":false},{"text":"Indira Gandhi","isCorrect":false}]'::jsonb,
 null, 'Pratibha Patil became the first woman President of India in 2007.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which is the smallest Union Territory of India by area?',
 '[{"text":"Chandigarh","isCorrect":false},{"text":"Lakshadweep","isCorrect":true},{"text":"Puducherry","isCorrect":false},{"text":"Daman and Diu","isCorrect":false}]'::jsonb,
 null, 'Lakshadweep is the smallest Union Territory of India by area.'),

-- General Awareness and Current Affairs: Current Affairs and Sports
('RRB Group D', 'General Awareness and Current Affairs', 'Current Affairs and Sports', 'easy', 'mcq',
 'How many rings are there in the Olympic flag?',
 '[{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false},{"text":"7","isCorrect":false}]'::jsonb,
 null, 'The Olympic flag has 5 interlocking rings representing the five continents.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Current Affairs and Sports', 'easy', 'mcq',
 'Which country hosted the 2020 Olympics (held in 2021)?',
 '[{"text":"China","isCorrect":false},{"text":"Japan","isCorrect":true},{"text":"Brazil","isCorrect":false},{"text":"United Kingdom","isCorrect":false}]'::jsonb,
 null, 'Japan hosted the 2020 Olympics in Tokyo, though it was actually held in 2021 due to the pandemic.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Current Affairs and Sports', 'medium', 'mcq',
 'Who captained the Indian cricket team to victory in the 2011 Cricket World Cup?',
 '[{"text":"Sourav Ganguly","isCorrect":false},{"text":"M.S. Dhoni","isCorrect":true},{"text":"Virat Kohli","isCorrect":false},{"text":"Rahul Dravid","isCorrect":false}]'::jsonb,
 null, 'M.S. Dhoni captained the Indian cricket team to victory in the 2011 Cricket World Cup.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Current Affairs and Sports', 'medium', 'mcq',
 'The Khelo India Youth Games primarily promote which sector?',
 '[{"text":"Agriculture","isCorrect":false},{"text":"Sports","isCorrect":true},{"text":"Education","isCorrect":false},{"text":"Health","isCorrect":false}]'::jsonb,
 null, 'The Khelo India Youth Games are a national initiative to promote sports and identify young talent.'),

-- General Awareness and Current Affairs: Railways General Knowledge
('RRB Group D', 'General Awareness and Current Affairs', 'Railways General Knowledge', 'easy', 'mcq',
 'What color is the standard Indian Railways signal light for "stop"?',
 '[{"text":"Green","isCorrect":false},{"text":"Yellow","isCorrect":false},{"text":"Red","isCorrect":true},{"text":"Blue","isCorrect":false}]'::jsonb,
 null, 'A red signal light indicates "stop" in Indian Railways signaling.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Railways General Knowledge', 'easy', 'mcq',
 'Which is the longest railway platform in India?',
 '[{"text":"Gorakhpur","isCorrect":true},{"text":"Kharagpur","isCorrect":false},{"text":"Kollam","isCorrect":false},{"text":"Bilaspur","isCorrect":false}]'::jsonb,
 null, 'Gorakhpur railway station has the longest railway platform in India.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Railways General Knowledge', 'medium', 'mcq',
 'What does "PNR" stand for in Indian Railways ticketing?',
 '[{"text":"Passenger Name Record","isCorrect":true},{"text":"Personal Number Record","isCorrect":false},{"text":"Public Number Registry","isCorrect":false},{"text":"Platform Number Record","isCorrect":false}]'::jsonb,
 null, 'PNR stands for Passenger Name Record, a unique reference number for a train ticket booking.'),
('RRB Group D', 'General Awareness and Current Affairs', 'Railways General Knowledge', 'medium', 'mcq',
 'Which is the fastest train currently operating in India?',
 '[{"text":"Rajdhani Express","isCorrect":false},{"text":"Shatabdi Express","isCorrect":false},{"text":"Vande Bharat Express","isCorrect":true},{"text":"Duronto Express","isCorrect":false}]'::jsonb,
 null, 'The Vande Bharat Express is currently the fastest train in operation in India.');
