-- supabase/sql/exam_question_bank_ssc_je_set1.sql
--
-- First curated question-bank batch for 'SSC-JE' (see exam_patterns_ssc_je.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). General Intelligence/Awareness questions are pitched similarly to the
-- other SSC exams already seeded; Civil Engineering questions are pitched at diploma/degree
-- level, since SSC JE recruits qualified engineers rather than general clerical staff. Non-Verbal
-- Reasoning again uses text-describable cube/geometry puzzles in place of figure-based questions,
-- which need images this schema can't provide. 16 chapters (4 General Intelligence + 4 General
-- Awareness + 8 Civil Engineering) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_je.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General Intelligence and Reasoning: Analogies and Classification
('SSC-JE', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Hammer is to Nail as Screwdriver is to:',
 '[{"text":"Screw","isCorrect":true},{"text":"Wood","isCorrect":false},{"text":"Metal","isCorrect":false},{"text":"Drill","isCorrect":false}]'::jsonb,
 null, 'A hammer is used to drive a nail, just as a screwdriver is used to drive a screw.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Circle","isCorrect":false},{"text":"Square","isCorrect":false},{"text":"Triangle","isCorrect":false},{"text":"Sphere","isCorrect":true}]'::jsonb,
 null, 'Circle, Square and Triangle are two-dimensional shapes, while a Sphere is a three-dimensional shape.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Compass is to Direction as Barometer is to:',
 '[{"text":"Temperature","isCorrect":false},{"text":"Pressure","isCorrect":true},{"text":"Humidity","isCorrect":false},{"text":"Speed","isCorrect":false}]'::jsonb,
 null, 'A compass measures direction, just as a barometer measures atmospheric pressure.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Ammeter","isCorrect":false},{"text":"Voltmeter","isCorrect":false},{"text":"Thermometer","isCorrect":true},{"text":"Wattmeter","isCorrect":false}]'::jsonb,
 null, 'Ammeter, Voltmeter and Wattmeter are electrical measuring instruments, while a Thermometer measures temperature.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('SSC-JE', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 5, 10, 20, 40, ?',
 '[{"text":"60","isCorrect":false},{"text":"70","isCorrect":false},{"text":"80","isCorrect":true},{"text":"90","isCorrect":false}]'::jsonb,
 null, 'Each term doubles the previous one, so the next term is 40 x 2 = 80.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'In a certain code, CAT is written as DBU. How is DOG written in that code?',
 '[{"text":"EPH","isCorrect":true},{"text":"EPI","isCorrect":false},{"text":"FPH","isCorrect":false},{"text":"EQH","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet: D->E, O->P, G->H, giving EPH.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 2, 3, 5, 8, 13, ?',
 '[{"text":"18","isCorrect":false},{"text":"20","isCorrect":false},{"text":"21","isCorrect":true},{"text":"24","isCorrect":false}]'::jsonb,
 null, 'Each term is the sum of the two preceding terms (a Fibonacci-like series), so 8 + 13 = 21.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If PENCIL is coded as QFODJM, how is ERASER coded in the same language?',
 '[{"text":"FSBTFS","isCorrect":true},{"text":"FSATFS","isCorrect":false},{"text":"FSBSFS","isCorrect":false},{"text":"GSBTFS","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so ERASER becomes FSBTFS.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('SSC-JE', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many edges does a cube have?',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":false},{"text":"12","isCorrect":true},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'A cube has 12 edges, 8 vertices, and 6 faces.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A cube is painted on all 6 faces and cut into 64 equal smaller cubes (a 4x4x4 cut). How many of the smaller cubes have no face painted?',
 '[{"text":"4","isCorrect":false},{"text":"8","isCorrect":true},{"text":"16","isCorrect":false},{"text":"27","isCorrect":false}]'::jsonb,
 null, 'The completely unpainted cubes form the inner (4-2) x (4-2) x (4-2) = 2x2x2 = 8 cubes.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'How many edges does a regular hexagonal prism have?',
 '[{"text":"12","isCorrect":false},{"text":"15","isCorrect":false},{"text":"18","isCorrect":true},{"text":"24","isCorrect":false}]'::jsonb,
 null, 'A hexagonal prism has 6 edges on the top face, 6 on the bottom face, and 6 vertical edges connecting them, giving 18 edges in total.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'A cube is painted on all faces and cut into 27 equal smaller cubes (a 3x3x3 cut). How many of the smaller cubes have exactly 2 faces painted?',
 '[{"text":"6","isCorrect":false},{"text":"8","isCorrect":false},{"text":"12","isCorrect":true},{"text":"9","isCorrect":false}]'::jsonb,
 null, 'The edge cubes (excluding corners) of a 3x3x3 cube each have exactly 2 painted faces, and there are 12 such edges.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('SSC-JE', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'Pointing to a man, a woman says, "He is the son of my mother''s only daughter," and she has no siblings. How is the man related to the woman?',
 '[{"text":"Son","isCorrect":true},{"text":"Brother","isCorrect":false},{"text":"Nephew","isCorrect":false},{"text":"Husband","isCorrect":false}]'::jsonb,
 null, 'Since the woman has no siblings, "my mother''s only daughter" refers to herself, making the man her son.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'A site engineer walks 6 km east, then 8 km north to reach the site office. What is the straight-line distance from his starting point?',
 '[{"text":"10 km","isCorrect":true},{"text":"14 km","isCorrect":false},{"text":"8 km","isCorrect":false},{"text":"12 km","isCorrect":false}]'::jsonb,
 null, 'By the Pythagorean theorem, the distance is sqrt(6^2 + 8^2) = sqrt(100) = 10 km.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'If every direction is rotated 90 degrees clockwise (so North becomes East, East becomes South, and so on), what would the original North direction now be called?',
 '[{"text":"East","isCorrect":true},{"text":"West","isCorrect":false},{"text":"South","isCorrect":false},{"text":"North","isCorrect":false}]'::jsonb,
 null, 'A 90 degree clockwise rotation turns North into East.'),
('SSC-JE', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A worker walks 4 m south, then 3 m west, then 4 m north. How far and in which direction is he from his starting point?',
 '[{"text":"3 m West","isCorrect":true},{"text":"3 m East","isCorrect":false},{"text":"7 m South","isCorrect":false},{"text":"4 m North","isCorrect":false}]'::jsonb,
 null, 'The 4 m south and 4 m north movements cancel out, leaving only the 3 m westward movement.'),

-- General Awareness: Indian History and Culture
('SSC-JE', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who built the Qutub Minar?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Qutb-ud-din Aibak","isCorrect":true},{"text":"Humayun","isCorrect":false},{"text":"Ashoka","isCorrect":false}]'::jsonb,
 null, 'Qutb-ud-din Aibak began construction of the Qutub Minar in Delhi.'),
('SSC-JE', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'In which year was the Indian National Congress founded?',
 '[{"text":"1885","isCorrect":true},{"text":"1905","isCorrect":false},{"text":"1857","isCorrect":false},{"text":"1920","isCorrect":false}]'::jsonb,
 null, 'The Indian National Congress was founded in 1885.'),
('SSC-JE', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Who founded the Maurya Empire?',
 '[{"text":"Ashoka","isCorrect":false},{"text":"Chandragupta Maurya","isCorrect":true},{"text":"Bindusara","isCorrect":false},{"text":"Samudragupta","isCorrect":false}]'::jsonb,
 null, 'Chandragupta Maurya founded the Maurya Empire around 322 BCE.'),
('SSC-JE', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'The Dandi March was associated with which movement?',
 '[{"text":"Quit India Movement","isCorrect":false},{"text":"Civil Disobedience Movement","isCorrect":true},{"text":"Non-Cooperation Movement","isCorrect":false},{"text":"Swadeshi Movement","isCorrect":false}]'::jsonb,
 null, 'The Dandi March in 1930, led by Mahatma Gandhi, launched the Civil Disobedience Movement.'),

-- General Awareness: Indian Polity and Geography
('SSC-JE', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'What is the maximum elected strength of the Lok Sabha as per the Constitution?',
 '[{"text":"543","isCorrect":true},{"text":"545","isCorrect":false},{"text":"552","isCorrect":false},{"text":"550","isCorrect":false}]'::jsonb,
 null, 'The Lok Sabha has a maximum elected strength of 543 members.'),
('SSC-JE', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the highest mountain peak located entirely within India?',
 '[{"text":"Nanda Devi","isCorrect":false},{"text":"Kanchenjunga","isCorrect":true},{"text":"K2","isCorrect":false},{"text":"Everest","isCorrect":false}]'::jsonb,
 null, 'Kanchenjunga, on the India-Nepal border area within Sikkim, is the highest peak entirely within India (Everest lies in Nepal/China, and K2 in Pakistan-administered territory).'),
('SSC-JE', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Who appoints the Chief Justice of India?',
 '[{"text":"Prime Minister","isCorrect":false},{"text":"President","isCorrect":true},{"text":"Parliament","isCorrect":false},{"text":"Chief Election Commissioner","isCorrect":false}]'::jsonb,
 null, 'The President of India appoints the Chief Justice of India.'),
('SSC-JE', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which is the largest desert in India?',
 '[{"text":"Thar Desert","isCorrect":true},{"text":"Rann of Kutch","isCorrect":false},{"text":"Deccan Plateau","isCorrect":false},{"text":"Ladakh","isCorrect":false}]'::jsonb,
 null, 'The Thar Desert, spread mainly across Rajasthan, is the largest desert in India.'),

-- General Awareness: General Science
('SSC-JE', 'General Awareness', 'General Science', 'easy', 'mcq',
 'What is the SI unit of electric current?',
 '[{"text":"Volt","isCorrect":false},{"text":"Ampere","isCorrect":true},{"text":"Ohm","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'The SI unit of electric current is the Ampere.'),
('SSC-JE', 'General Awareness', 'General Science', 'easy', 'mcq',
 'Which gas(es) are commonly used together in oxy-acetylene welding?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Acetylene","isCorrect":false},{"text":"Nitrogen","isCorrect":false},{"text":"Both Oxygen and Acetylene","isCorrect":true}]'::jsonb,
 null, 'Oxy-acetylene welding uses a mixture of oxygen and acetylene gas to produce a high-temperature flame.'),
('SSC-JE', 'General Awareness', 'General Science', 'medium', 'mcq',
 'What is the SI unit of pressure?',
 '[{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":true},{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'The SI unit of pressure is the Pascal (Pa), equal to one Newton per square meter.'),
('SSC-JE', 'General Awareness', 'General Science', 'medium', 'mcq',
 'What type of current is typically generated by a common household alternator/generator?',
 '[{"text":"Direct Current","isCorrect":false},{"text":"Alternating Current","isCorrect":true},{"text":"Static Current","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'A common alternator generates Alternating Current (AC), which periodically reverses direction.'),

-- General Awareness: Current Affairs and Static GK
('SSC-JE', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'Which is the national animal of India?',
 '[{"text":"Lion","isCorrect":false},{"text":"Tiger","isCorrect":true},{"text":"Elephant","isCorrect":false},{"text":"Leopard","isCorrect":false}]'::jsonb,
 null, 'The Bengal Tiger is the national animal of India.'),
('SSC-JE', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'The Statue of Unity, the tallest statue in the world, is dedicated to whom?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"Sardar Vallabhbhai Patel","isCorrect":true},{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"B.R. Ambedkar","isCorrect":false}]'::jsonb,
 null, 'The Statue of Unity in Gujarat is dedicated to Sardar Vallabhbhai Patel.'),
('SSC-JE', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'Which Indian government scheme aims to provide affordable housing for all?',
 '[{"text":"PM Awas Yojana","isCorrect":true},{"text":"PM Kisan Yojana","isCorrect":false},{"text":"MGNREGA","isCorrect":false},{"text":"Ayushman Bharat","isCorrect":false}]'::jsonb,
 null, 'The Pradhan Mantri Awas Yojana aims to provide affordable housing for all eligible citizens.'),
('SSC-JE', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'The headquarters of ISRO is located in which city?',
 '[{"text":"Bengaluru","isCorrect":true},{"text":"Hyderabad","isCorrect":false},{"text":"Chennai","isCorrect":false},{"text":"Thiruvananthapuram","isCorrect":false}]'::jsonb,
 null, 'ISRO (Indian Space Research Organisation) has its headquarters in Bengaluru.'),

-- Civil Engineering: Building Materials
('SSC-JE', 'Civil Engineering', 'Building Materials', 'easy', 'mcq',
 'What is the main ingredient of ordinary Portland cement?',
 '[{"text":"Sand","isCorrect":false},{"text":"Limestone","isCorrect":true},{"text":"Gravel","isCorrect":false},{"text":"Clay","isCorrect":false}]'::jsonb,
 null, 'Limestone (calcium carbonate) is the primary raw material used in manufacturing ordinary Portland cement.'),
('SSC-JE', 'Civil Engineering', 'Building Materials', 'easy', 'mcq',
 'As per standard specification, what is the minimum initial setting time of ordinary Portland cement?',
 '[{"text":"30 minutes","isCorrect":true},{"text":"45 minutes","isCorrect":false},{"text":"60 minutes","isCorrect":false},{"text":"90 minutes","isCorrect":false}]'::jsonb,
 null, 'The initial setting time of ordinary Portland cement should not be less than 30 minutes.'),
('SSC-JE', 'Civil Engineering', 'Building Materials', 'medium', 'mcq',
 'Which grade of concrete is most commonly used for RCC slab work in residential buildings?',
 '[{"text":"M10","isCorrect":false},{"text":"M15","isCorrect":false},{"text":"M20","isCorrect":true},{"text":"M5","isCorrect":false}]'::jsonb,
 null, 'M20 grade concrete is commonly used for RCC slabs, beams, and columns in residential construction.'),
('SSC-JE', 'Civil Engineering', 'Building Materials', 'medium', 'mcq',
 'What is the typical water-cement ratio used for good quality concrete?',
 '[{"text":"0.2","isCorrect":false},{"text":"0.45 to 0.6","isCorrect":true},{"text":"1.0","isCorrect":false},{"text":"1.5","isCorrect":false}]'::jsonb,
 null, 'A water-cement ratio of approximately 0.45 to 0.6 is generally used to achieve good workability and strength in concrete.'),

-- Civil Engineering: Surveying
('SSC-JE', 'Civil Engineering', 'Surveying', 'easy', 'mcq',
 'Which instrument is used to measure both horizontal and vertical angles in surveying?',
 '[{"text":"Chain","isCorrect":false},{"text":"Theodolite","isCorrect":true},{"text":"Level","isCorrect":false},{"text":"Compass","isCorrect":false}]'::jsonb,
 null, 'A theodolite is used to measure both horizontal and vertical angles precisely in surveying.'),
('SSC-JE', 'Civil Engineering', 'Surveying', 'easy', 'mcq',
 'What does GPS stand for, as used in modern surveying?',
 '[{"text":"Global Positioning System","isCorrect":true},{"text":"Ground Plot Survey","isCorrect":false},{"text":"Geo Placement Sensor","isCorrect":false},{"text":"General Position Setup","isCorrect":false}]'::jsonb,
 null, 'GPS stands for Global Positioning System, used for precise location surveying.'),
('SSC-JE', 'Civil Engineering', 'Surveying', 'medium', 'mcq',
 'In leveling, the vertical distance of a point above or below a datum is called its:',
 '[{"text":"Bench mark","isCorrect":false},{"text":"Reduced level","isCorrect":true},{"text":"Datum","isCorrect":false},{"text":"Backsight","isCorrect":false}]'::jsonb,
 null, 'The reduced level of a point is its elevation with respect to an assumed or standard datum.'),
('SSC-JE', 'Civil Engineering', 'Surveying', 'medium', 'mcq',
 'Which method of surveying uses a chain or tape as its main measuring instrument?',
 '[{"text":"Theodolite surveying","isCorrect":false},{"text":"Chain surveying","isCorrect":true},{"text":"Photogrammetry","isCorrect":false},{"text":"Tacheometry","isCorrect":false}]'::jsonb,
 null, 'Chain surveying uses a chain or tape to directly measure linear distances between survey points.'),

-- Civil Engineering: Strength of Materials
('SSC-JE', 'Civil Engineering', 'Strength of Materials', 'easy', 'mcq',
 'What is the SI unit of stress?',
 '[{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":true},{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'Stress is force per unit area, so its SI unit is the Pascal (equivalent to N/m^2).'),
('SSC-JE', 'Civil Engineering', 'Strength of Materials', 'easy', 'mcq',
 'Which type of stress is induced in a material when it is stretched?',
 '[{"text":"Compressive","isCorrect":false},{"text":"Tensile","isCorrect":true},{"text":"Shear","isCorrect":false},{"text":"Torsional","isCorrect":false}]'::jsonb,
 null, 'Tensile stress is induced when a material is pulled or stretched.'),
('SSC-JE', 'Civil Engineering', 'Strength of Materials', 'medium', 'mcq',
 'The ratio of stress to strain within the elastic limit of a material is called:',
 '[{"text":"Poisson''s ratio","isCorrect":false},{"text":"Young''s modulus","isCorrect":true},{"text":"Bulk modulus","isCorrect":false},{"text":"Shear modulus","isCorrect":false}]'::jsonb,
 null, 'Young''s modulus (modulus of elasticity) is defined as the ratio of stress to strain within the elastic limit.'),
('SSC-JE', 'Civil Engineering', 'Strength of Materials', 'medium', 'mcq',
 'In a simply supported beam carrying a single point load at its center, where does the maximum bending moment occur?',
 '[{"text":"At the supports","isCorrect":false},{"text":"At the center","isCorrect":true},{"text":"At one-quarter span","isCorrect":false},{"text":"Uniform throughout","isCorrect":false}]'::jsonb,
 null, 'For a simply supported beam with a central point load, the maximum bending moment occurs directly under the load, at the center.'),

-- Civil Engineering: Structural Analysis and Design
('SSC-JE', 'Civil Engineering', 'Structural Analysis and Design', 'easy', 'mcq',
 'Which material is commonly used for reinforcement in reinforced cement concrete (RCC)?',
 '[{"text":"Aluminum","isCorrect":false},{"text":"Steel","isCorrect":true},{"text":"Copper","isCorrect":false},{"text":"Wood","isCorrect":false}]'::jsonb,
 null, 'Steel bars are used as reinforcement in RCC because concrete is strong in compression but weak in tension, which steel provides.'),
('SSC-JE', 'Civil Engineering', 'Structural Analysis and Design', 'medium', 'mcq',
 'In a simply supported beam, what is the bending moment at the supports?',
 '[{"text":"Maximum","isCorrect":false},{"text":"Zero","isCorrect":true},{"text":"Negative","isCorrect":false},{"text":"Infinite","isCorrect":false}]'::jsonb,
 null, 'At the supports of a simply supported beam, the bending moment is zero since there is no resisting moment there.'),
('SSC-JE', 'Civil Engineering', 'Structural Analysis and Design', 'medium', 'mcq',
 'A load that changes position along a structure but not in magnitude is called a:',
 '[{"text":"Dead load","isCorrect":false},{"text":"Live load","isCorrect":false},{"text":"Moving load","isCorrect":true},{"text":"Impact load","isCorrect":false}]'::jsonb,
 null, 'A moving load, such as a vehicle crossing a bridge, changes position but keeps a constant magnitude.'),
('SSC-JE', 'Civil Engineering', 'Structural Analysis and Design', 'hard', 'mcq',
 'For a cantilever beam with a point load at its free end, where does the maximum bending moment occur?',
 '[{"text":"Free end","isCorrect":false},{"text":"Fixed end","isCorrect":true},{"text":"Mid-span","isCorrect":false},{"text":"Nowhere","isCorrect":false}]'::jsonb,
 null, 'For a cantilever beam, the bending moment increases with distance from the free end and is maximum at the fixed support.'),

-- Civil Engineering: Estimating and Costing
('SSC-JE', 'Civil Engineering', 'Estimating and Costing', 'easy', 'mcq',
 'The process of calculating the quantities of materials and labour required for a construction project is called:',
 '[{"text":"Costing","isCorrect":false},{"text":"Estimating","isCorrect":true},{"text":"Budgeting","isCorrect":false},{"text":"Auditing","isCorrect":false}]'::jsonb,
 null, 'Estimating is the process of calculating the quantities and costs of materials and labour needed for a project.'),
('SSC-JE', 'Civil Engineering', 'Estimating and Costing', 'easy', 'mcq',
 'Excavation work in an estimate is generally measured in which unit?',
 '[{"text":"Square meters","isCorrect":false},{"text":"Cubic meters","isCorrect":true},{"text":"Linear meters","isCorrect":false},{"text":"Kilograms","isCorrect":false}]'::jsonb,
 null, 'Excavation is a volumetric quantity of earthwork, so it is measured in cubic meters.'),
('SSC-JE', 'Civil Engineering', 'Estimating and Costing', 'medium', 'mcq',
 'A "Bill of Quantities" in an estimate primarily shows:',
 '[{"text":"Only the total cost","isCorrect":false},{"text":"Quantities and cost of each item of work","isCorrect":true},{"text":"Only the materials list","isCorrect":false},{"text":"Only labour cost","isCorrect":false}]'::jsonb,
 null, 'A Bill of Quantities itemizes each part of the work along with its quantity and cost.'),
('SSC-JE', 'Civil Engineering', 'Estimating and Costing', 'medium', 'mcq',
 'Contingencies included in a project estimate are provisions made for:',
 '[{"text":"Unforeseen expenses","isCorrect":true},{"text":"Labour wages","isCorrect":false},{"text":"Material cost only","isCorrect":false},{"text":"Profit margin","isCorrect":false}]'::jsonb,
 null, 'Contingencies are a reserve amount set aside in an estimate to cover unforeseen expenses during construction.'),

-- Civil Engineering: Soil Mechanics and Foundation Engineering
('SSC-JE', 'Civil Engineering', 'Soil Mechanics and Foundation Engineering', 'easy', 'mcq',
 'The ratio of the volume of voids to the total volume of a soil sample is called its:',
 '[{"text":"Porosity","isCorrect":false},{"text":"Void ratio","isCorrect":true},{"text":"Water content","isCorrect":false},{"text":"Density","isCorrect":false}]'::jsonb,
 null, 'Void ratio is defined as the ratio of the volume of voids to the total volume of the soil sample.'),
('SSC-JE', 'Civil Engineering', 'Soil Mechanics and Foundation Engineering', 'easy', 'mcq',
 'Which type of foundation is typically used for a heavy structure on soil with low bearing capacity?',
 '[{"text":"Isolated footing","isCorrect":false},{"text":"Pile foundation","isCorrect":true},{"text":"Strip footing","isCorrect":false},{"text":"Raft foundation","isCorrect":false}]'::jsonb,
 null, 'A pile foundation transfers heavy structural loads deep into stronger soil or rock layers, making it suitable for weak surface soils.'),
('SSC-JE', 'Civil Engineering', 'Soil Mechanics and Foundation Engineering', 'medium', 'mcq',
 'The maximum dry density of soil is typically determined using which test?',
 '[{"text":"Sieve analysis","isCorrect":false},{"text":"Proctor''s compaction test","isCorrect":true},{"text":"Atterberg limits test","isCorrect":false},{"text":"Permeability test","isCorrect":false}]'::jsonb,
 null, 'Proctor''s compaction test determines the maximum dry density and optimum moisture content of soil.'),
('SSC-JE', 'Civil Engineering', 'Soil Mechanics and Foundation Engineering', 'medium', 'mcq',
 'The pressure exerted by soil on a retaining wall when the soil is not moving is called:',
 '[{"text":"Active earth pressure","isCorrect":false},{"text":"Passive earth pressure","isCorrect":false},{"text":"Earth pressure at rest","isCorrect":true},{"text":"Surcharge pressure","isCorrect":false}]'::jsonb,
 null, '"Earth pressure at rest" refers to the lateral soil pressure on a wall when the soil mass is in its natural, undisturbed state.'),

-- Civil Engineering: Fluid Mechanics and Hydraulics
('SSC-JE', 'Civil Engineering', 'Fluid Mechanics and Hydraulics', 'easy', 'mcq',
 'What is the SI unit of pressure in fluid mechanics?',
 '[{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":true},{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":false}]'::jsonb,
 null, 'The SI unit of pressure is the Pascal, defined as one Newton per square meter.'),
('SSC-JE', 'Civil Engineering', 'Fluid Mechanics and Hydraulics', 'easy', 'mcq',
 'Which instrument is used to measure the velocity of flow of a fluid in a pipe?',
 '[{"text":"Barometer","isCorrect":false},{"text":"Venturimeter","isCorrect":true},{"text":"Thermometer","isCorrect":false},{"text":"Manometer","isCorrect":false}]'::jsonb,
 null, 'A venturimeter is used to measure the rate of flow (and hence velocity) of a fluid through a pipe.'),
('SSC-JE', 'Civil Engineering', 'Fluid Mechanics and Hydraulics', 'medium', 'mcq',
 'Bernoulli''s theorem for fluid flow is based on the principle of conservation of:',
 '[{"text":"Mass","isCorrect":false},{"text":"Energy","isCorrect":true},{"text":"Momentum","isCorrect":false},{"text":"Charge","isCorrect":false}]'::jsonb,
 null, 'Bernoulli''s theorem is derived from the principle of conservation of energy applied to fluid flow.'),
('SSC-JE', 'Civil Engineering', 'Fluid Mechanics and Hydraulics', 'medium', 'mcq',
 'The type of fluid flow in which particles move in parallel layers without mixing is called:',
 '[{"text":"Turbulent flow","isCorrect":false},{"text":"Laminar flow","isCorrect":true},{"text":"Uniform flow","isCorrect":false},{"text":"Non-uniform flow","isCorrect":false}]'::jsonb,
 null, 'Laminar flow is characterized by fluid particles moving in smooth, parallel layers without mixing.'),

-- Civil Engineering: Environmental Engineering (Water Supply and Sanitation)
('SSC-JE', 'Civil Engineering', 'Environmental Engineering (Water Supply and Sanitation)', 'easy', 'mcq',
 'Which process removes suspended impurities from water by allowing them to settle?',
 '[{"text":"Filtration","isCorrect":false},{"text":"Sedimentation","isCorrect":true},{"text":"Disinfection","isCorrect":false},{"text":"Aeration","isCorrect":false}]'::jsonb,
 null, 'Sedimentation allows suspended particles in water to settle out under gravity.'),
('SSC-JE', 'Civil Engineering', 'Environmental Engineering (Water Supply and Sanitation)', 'easy', 'mcq',
 'Which chemical is most commonly used for disinfection of drinking water?',
 '[{"text":"Chlorine","isCorrect":true},{"text":"Sulfur","isCorrect":false},{"text":"Nitrogen","isCorrect":false},{"text":"Carbon dioxide","isCorrect":false}]'::jsonb,
 null, 'Chlorine is widely used to disinfect drinking water and kill harmful microorganisms.'),
('SSC-JE', 'Civil Engineering', 'Environmental Engineering (Water Supply and Sanitation)', 'medium', 'mcq',
 'The process of exposing water to air to remove dissolved gases and odor is called:',
 '[{"text":"Sedimentation","isCorrect":false},{"text":"Aeration","isCorrect":true},{"text":"Coagulation","isCorrect":false},{"text":"Filtration","isCorrect":false}]'::jsonb,
 null, 'Aeration exposes water to air, removing dissolved gases like carbon dioxide and reducing unpleasant odors.'),
('SSC-JE', 'Civil Engineering', 'Environmental Engineering (Water Supply and Sanitation)', 'medium', 'mcq',
 'In water quality testing, what does BOD stand for?',
 '[{"text":"Biological Oxygen Demand","isCorrect":true},{"text":"Basic Organic Density","isCorrect":false},{"text":"Biochemical Oxidation Degree","isCorrect":false},{"text":"Bio Organic Demand","isCorrect":false}]'::jsonb,
 null, 'BOD stands for Biological Oxygen Demand, a measure of the organic pollution load in water.');
