-- supabase/sql/exam_question_bank_class7_set1.sql
--
-- First curated question-bank batch for 'Class 7' (see exam_patterns_class7.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 7's MCQ-only,
-- no-negative-marking pattern. 8 chapters (2 per subject x 4 subjects) each get 4 questions --
-- one easy, two medium, one hard -- reflecting the increased hard share in
-- exam_patterns_class7.sql. Pitched one notch above Class 6 (see
-- exam_question_bank_class6_set1.sql) -- clauses/reported speech, integers/simple equations,
-- nutrition/heat/acids-bases-salts, and Delhi Sultanate-Mughals/civics.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class7.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Tenses, Clauses and Reported Speech
('Class 7', 'English', 'Tenses, Clauses and Reported Speech', 'easy', 'mcq',
 'Which sentence is in the past perfect tense?',
 '[{"text":"She had left before I arrived.","isCorrect":true},{"text":"She leaves before I arrive.","isCorrect":false},{"text":"She will leave before I arrive.","isCorrect":false},{"text":"She is leaving before I arrive.","isCorrect":false}]'::jsonb,
 null, 'The past perfect tense uses ''had'' + past participle to show an action completed before another past action.'),
('Class 7', 'English', 'Tenses, Clauses and Reported Speech', 'medium', 'mcq',
 'In the sentence "The boy who won the race is my brother," which part is the clause describing the boy?',
 '[{"text":"The boy","isCorrect":false},{"text":"who won the race","isCorrect":true},{"text":"is my brother","isCorrect":false},{"text":"my brother","isCorrect":false}]'::jsonb,
 null, '''Who won the race'' is a relative clause that describes ''the boy''.'),
('Class 7', 'English', 'Tenses, Clauses and Reported Speech', 'medium', 'mcq',
 'Convert to reported speech: He said, "I will come tomorrow."',
 '[{"text":"He said that he will come tomorrow.","isCorrect":false},{"text":"He said that he would come the next day.","isCorrect":true},{"text":"He says that he would come tomorrow.","isCorrect":false},{"text":"He said that I will come tomorrow.","isCorrect":false}]'::jsonb,
 null, 'In reported speech, ''will'' shifts to ''would'' and ''tomorrow'' shifts to ''the next day''.'),
('Class 7', 'English', 'Tenses, Clauses and Reported Speech', 'hard', 'mcq',
 'Convert to reported speech: She asked, "Where are you going?"',
 '[{"text":"She asked where I was going.","isCorrect":true},{"text":"She asked where am I going.","isCorrect":false},{"text":"She asked where you are going.","isCorrect":false},{"text":"She asked that where I was going.","isCorrect":false}]'::jsonb,
 null, 'Reported questions drop the question-word inversion and shift the tense back: ''are'' becomes ''was''.'),

-- English: Reading Comprehension and Vocabulary
('Class 7', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'Read: "The scientist worked tirelessly for years before finally discovering the cure." What did the scientist eventually do?',
 '[{"text":"Give up the research","isCorrect":false},{"text":"Discover the cure","isCorrect":true},{"text":"Move to another field","isCorrect":false},{"text":"Retire early","isCorrect":false}]'::jsonb,
 null, 'The passage says the scientist finally discovered the cure after working tirelessly for years.'),
('Class 7', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'A word that means the same as ''meticulous'' is:',
 '[{"text":"Careless","isCorrect":false},{"text":"Careful and precise","isCorrect":true},{"text":"Quick","isCorrect":false},{"text":"Lazy","isCorrect":false}]'::jsonb,
 null, '''Meticulous'' means showing great attention to detail; ''careful and precise'' captures the same meaning.'),
('Class 7', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'Read: "The negotiations, though tense at first, eventually led to a peaceful agreement between the two nations." How did the negotiations conclude?',
 '[{"text":"In a peaceful agreement","isCorrect":true},{"text":"In a war","isCorrect":false},{"text":"Without any result","isCorrect":false},{"text":"In further tension","isCorrect":false}]'::jsonb,
 null, 'The passage says the negotiations eventually led to a peaceful agreement between the two nations.'),
('Class 7', 'English', 'Reading Comprehension and Vocabulary', 'hard', 'mcq',
 'A word that means the opposite of ''abundant'' is:',
 '[{"text":"Plentiful","isCorrect":false},{"text":"Scarce","isCorrect":true},{"text":"Rich","isCorrect":false},{"text":"Vast","isCorrect":false}]'::jsonb,
 null, '''Scarce'' means in short supply, the opposite of ''abundant''.'),

-- Mathematics: Integers, Rational Numbers and Simple Equations
('Class 7', 'Mathematics', 'Integers, Rational Numbers and Simple Equations', 'easy', 'mcq',
 'What is (-6) x 4?',
 '[{"text":"-24","isCorrect":true},{"text":"24","isCorrect":false},{"text":"-10","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'A negative number multiplied by a positive number gives a negative result: (-6) x 4 = -24.'),
('Class 7', 'Mathematics', 'Integers, Rational Numbers and Simple Equations', 'medium', 'mcq',
 'Which of these is a rational number between 1/2 and 3/4?',
 '[{"text":"5/8","isCorrect":true},{"text":"1/8","isCorrect":false},{"text":"1","isCorrect":false},{"text":"1/4","isCorrect":false}]'::jsonb,
 null, '1/2 = 4/8 and 3/4 = 6/8, so 5/8 lies between them.'),
('Class 7', 'Mathematics', 'Integers, Rational Numbers and Simple Equations', 'medium', 'mcq',
 'Solve for x: 3x + 5 = 20',
 '[{"text":"x = 3","isCorrect":false},{"text":"x = 5","isCorrect":true},{"text":"x = 15","isCorrect":false},{"text":"x = 25","isCorrect":false}]'::jsonb,
 null, '3x + 5 = 20 gives 3x = 15, so x = 5.'),
('Class 7', 'Mathematics', 'Integers, Rational Numbers and Simple Equations', 'hard', 'mcq',
 'What is (-18) / (-3)?',
 '[{"text":"-6","isCorrect":false},{"text":"6","isCorrect":true},{"text":"-15","isCorrect":false},{"text":"15","isCorrect":false}]'::jsonb,
 null, 'A negative number divided by a negative number gives a positive result: (-18) / (-3) = 6.'),

-- Mathematics: Percentage, Profit-Loss, Ratio-Proportion and Geometry
('Class 7', 'Mathematics', 'Percentage, Profit-Loss, Ratio-Proportion and Geometry', 'easy', 'mcq',
 'A shopkeeper buys an item for Rs. 400 and sells it for Rs. 500. What is the profit percentage?',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"30%","isCorrect":false},{"text":"15%","isCorrect":false}]'::jsonb,
 null, 'Profit = 500 - 400 = 100. Profit percentage = (100/400) x 100 = 25%.'),
('Class 7', 'Mathematics', 'Percentage, Profit-Loss, Ratio-Proportion and Geometry', 'medium', 'mcq',
 'If the ratio of boys to girls in a class is 3:2 and there are 30 students, how many boys are there?',
 '[{"text":"12","isCorrect":false},{"text":"18","isCorrect":true},{"text":"15","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Total parts = 3+2 = 5. Boys = (3/5) x 30 = 18.'),
('Class 7', 'Mathematics', 'Percentage, Profit-Loss, Ratio-Proportion and Geometry', 'medium', 'mcq',
 'The sum of the interior angles of a quadrilateral is:',
 '[{"text":"180 degrees","isCorrect":false},{"text":"270 degrees","isCorrect":false},{"text":"360 degrees","isCorrect":true},{"text":"540 degrees","isCorrect":false}]'::jsonb,
 null, 'The sum of the interior angles of any quadrilateral is always 360 degrees.'),
('Class 7', 'Mathematics', 'Percentage, Profit-Loss, Ratio-Proportion and Geometry', 'hard', 'mcq',
 'A shopkeeper sells an item at a loss of 10%. If the cost price was Rs. 800, what was the selling price?',
 '[{"text":"Rs. 720","isCorrect":true},{"text":"Rs. 880","isCorrect":false},{"text":"Rs. 790","isCorrect":false},{"text":"Rs. 700","isCorrect":false}]'::jsonb,
 null, 'A 10% loss means the selling price is 90% of the cost price: 0.9 x 800 = Rs. 720.'),

-- Science: Nutrition, Respiration and Reproduction in Organisms
('Class 7', 'Science', 'Nutrition, Respiration and Reproduction in Organisms', 'easy', 'mcq',
 'The mode of nutrition in which an organism prepares its own food is called:',
 '[{"text":"Heterotrophic nutrition","isCorrect":false},{"text":"Autotrophic nutrition","isCorrect":true},{"text":"Parasitic nutrition","isCorrect":false},{"text":"Saprophytic nutrition","isCorrect":false}]'::jsonb,
 null, 'Organisms like green plants that prepare their own food are called autotrophs, and their nutrition is autotrophic.'),
('Class 7', 'Science', 'Nutrition, Respiration and Reproduction in Organisms', 'medium', 'mcq',
 'Which type of respiration occurs in yeast without the use of oxygen, producing alcohol?',
 '[{"text":"Aerobic respiration","isCorrect":false},{"text":"Anaerobic respiration","isCorrect":true},{"text":"Photosynthesis","isCorrect":false},{"text":"Transpiration","isCorrect":false}]'::jsonb,
 null, 'Yeast performs anaerobic respiration (fermentation) without oxygen, producing alcohol and carbon dioxide.'),
('Class 7', 'Science', 'Nutrition, Respiration and Reproduction in Organisms', 'medium', 'mcq',
 'The fusion of a male and female gamete to form a new organism is called:',
 '[{"text":"Budding","isCorrect":false},{"text":"Fertilization","isCorrect":true},{"text":"Fission","isCorrect":false},{"text":"Fragmentation","isCorrect":false}]'::jsonb,
 null, 'Fertilization is the fusion of a male gamete and a female gamete to form a zygote.'),
('Class 7', 'Science', 'Nutrition, Respiration and Reproduction in Organisms', 'hard', 'mcq',
 'A method of asexual reproduction seen in the Amoeba, where the parent cell divides into two, is called:',
 '[{"text":"Budding","isCorrect":false},{"text":"Binary fission","isCorrect":true},{"text":"Grafting","isCorrect":false},{"text":"Pollination","isCorrect":false}]'::jsonb,
 null, 'In binary fission, seen in organisms like Amoeba, the parent cell divides into two equal daughter cells.'),

-- Science: Heat, Acids-Bases-Salts and Electric Current
('Class 7', 'Science', 'Heat, Acids-Bases-Salts and Electric Current', 'easy', 'mcq',
 'Which of these instruments is used to measure temperature?',
 '[{"text":"Barometer","isCorrect":false},{"text":"Thermometer","isCorrect":true},{"text":"Hygrometer","isCorrect":false},{"text":"Anemometer","isCorrect":false}]'::jsonb,
 null, 'A thermometer is used to measure temperature.'),
('Class 7', 'Science', 'Heat, Acids-Bases-Salts and Electric Current', 'medium', 'mcq',
 'Which of these substances turns blue litmus paper red?',
 '[{"text":"An acid","isCorrect":true},{"text":"A base","isCorrect":false},{"text":"A neutral salt","isCorrect":false},{"text":"Water","isCorrect":false}]'::jsonb,
 null, 'Acids turn blue litmus paper red, which is a standard test for acidity.'),
('Class 7', 'Science', 'Heat, Acids-Bases-Salts and Electric Current', 'medium', 'mcq',
 'The transfer of heat through a medium without the actual movement of the medium''s particles is called:',
 '[{"text":"Convection","isCorrect":false},{"text":"Conduction","isCorrect":true},{"text":"Radiation","isCorrect":false},{"text":"Reflection","isCorrect":false}]'::jsonb,
 null, 'Conduction is the transfer of heat through a medium (usually a solid) without the movement of its particles.'),
('Class 7', 'Science', 'Heat, Acids-Bases-Salts and Electric Current', 'hard', 'mcq',
 'The heating effect of electric current is used in which of these appliances?',
 '[{"text":"Electric bulb (LED)","isCorrect":false},{"text":"Electric iron","isCorrect":true},{"text":"Solar panel","isCorrect":false},{"text":"Battery","isCorrect":false}]'::jsonb,
 null, 'An electric iron uses the heating effect of electric current passing through its coil to generate heat.'),

-- Social Science: History (Delhi Sultanate to Mughals) and Geography (Environment)
('Class 7', 'Social Science', 'History (Delhi Sultanate to Mughals) and Geography (Environment)', 'easy', 'mcq',
 'Who founded the Mughal Empire in India?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Babur","isCorrect":true},{"text":"Humayun","isCorrect":false},{"text":"Aurangzeb","isCorrect":false}]'::jsonb,
 null, 'Babur founded the Mughal Empire in India after the First Battle of Panipat in 1526.'),
('Class 7', 'Social Science', 'History (Delhi Sultanate to Mughals) and Geography (Environment)', 'medium', 'mcq',
 'Which Delhi Sultanate ruler is known for introducing token currency and shifting the capital to Daulatabad?',
 '[{"text":"Alauddin Khilji","isCorrect":false},{"text":"Muhammad bin Tughlaq","isCorrect":true},{"text":"Balban","isCorrect":false},{"text":"Iltutmish","isCorrect":false}]'::jsonb,
 null, 'Muhammad bin Tughlaq introduced token currency and briefly shifted the capital from Delhi to Daulatabad.'),
('Class 7', 'Social Science', 'History (Delhi Sultanate to Mughals) and Geography (Environment)', 'medium', 'mcq',
 'The total surroundings in which living and non-living things interact is called the:',
 '[{"text":"Ecosystem","isCorrect":false},{"text":"Environment","isCorrect":true},{"text":"Habitat","isCorrect":false},{"text":"Biosphere","isCorrect":false}]'::jsonb,
 null, 'The environment refers to the total surroundings, including living and non-living things, that interact with each other.'),
('Class 7', 'Social Science', 'History (Delhi Sultanate to Mughals) and Geography (Environment)', 'hard', 'mcq',
 'Which Mughal emperor built the Taj Mahal in memory of his wife?',
 '[{"text":"Akbar","isCorrect":false},{"text":"Jahangir","isCorrect":false},{"text":"Shah Jahan","isCorrect":true},{"text":"Aurangzeb","isCorrect":false}]'::jsonb,
 null, 'Emperor Shah Jahan built the Taj Mahal in memory of his wife, Mumtaz Mahal.'),

-- Social Science: Civics (Equality, State Government and Media)
('Class 7', 'Social Science', 'Civics (Equality, State Government and Media)', 'easy', 'mcq',
 'The principle that all citizens are equal before the law is called:',
 '[{"text":"Equality","isCorrect":true},{"text":"Discrimination","isCorrect":false},{"text":"Hierarchy","isCorrect":false},{"text":"Favoritism","isCorrect":false}]'::jsonb,
 null, 'Equality means all citizens are treated the same and are equal before the law.'),
('Class 7', 'Social Science', 'Civics (Equality, State Government and Media)', 'medium', 'mcq',
 'Who is the head of a state government in India, appointed by the President?',
 '[{"text":"Chief Minister","isCorrect":false},{"text":"Governor","isCorrect":true},{"text":"Prime Minister","isCorrect":false},{"text":"Speaker","isCorrect":false}]'::jsonb,
 null, 'The Governor is the constitutional head of a state, appointed by the President of India.'),
('Class 7', 'Social Science', 'Civics (Equality, State Government and Media)', 'medium', 'mcq',
 'Who is the real executive head of a state government, leading the elected legislature?',
 '[{"text":"Chief Minister","isCorrect":true},{"text":"Governor","isCorrect":false},{"text":"President","isCorrect":false},{"text":"Chief Justice","isCorrect":false}]'::jsonb,
 null, 'The Chief Minister is the real executive head of a state, elected by and leading the state legislature.'),
('Class 7', 'Social Science', 'Civics (Equality, State Government and Media)', 'hard', 'mcq',
 'The role of the media in informing citizens about government actions and holding it accountable is often called:',
 '[{"text":"The judiciary","isCorrect":false},{"text":"The fourth pillar of democracy","isCorrect":true},{"text":"The executive branch","isCorrect":false},{"text":"The legislature","isCorrect":false}]'::jsonb,
 null, 'The media is often called the fourth pillar of democracy for its role in informing citizens and ensuring accountability.');
