-- supabase/sql/exam_question_bank_neet_ug_set4.sql
--
-- Fourth curated question-bank batch for 'NEET UG' (see exam_patterns_neet_ug.sql for the exam's
-- structure, and Sets 1-3 for the earlier batches -- same table/schema, no migration needed).
-- All-new questions, no overlap with Sets 1, 2, or 3.
--
-- Same format as the earlier sets: every row is format='mcq' with a single isCorrect:true option,
-- matching NEET UG's 100% single-best-response format. 16 chapters (4 each across Physics,
-- Chemistry, Botany, Zoology) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_ug.sql and
-- exam_question_bank_neet_ug_set1.sql / set2.sql / set3.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of power is the:',
 '[{"text":"Joule","isCorrect":false},{"text":"Watt","isCorrect":true},{"text":"Newton","isCorrect":false},{"text":"Pascal","isCorrect":false}]'::jsonb,
 null, 'Power, the rate of doing work, is measured in watts (1 W = 1 J/s).'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'Ignoring air resistance, the trajectory (path) followed by a projectile under gravity is a:',
 '[{"text":"Straight line","isCorrect":false},{"text":"Parabola","isCorrect":true},{"text":"Circle","isCorrect":false},{"text":"Ellipse","isCorrect":false}]'::jsonb,
 null, 'A projectile launched at an angle, under constant gravitational acceleration and no air resistance, follows a parabolic trajectory.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The center of mass of a system of particles is a point that:',
 '[{"text":"Must lie on one of the particles","isCorrect":false},{"text":"Represents the average position of the mass distribution of the system","isCorrect":true},{"text":"Is always at the geometric center of the container","isCorrect":false},{"text":"Moves independently of any external force","isCorrect":false}]'::jsonb,
 null, 'The center of mass represents the average (mass-weighted) position of a system of particles, and its motion is governed by the net external force on the system.'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'Torque is best defined as the:',
 '[{"text":"Turning effect of a force about an axis (moment of force)","isCorrect":true},{"text":"Total kinetic energy of a rotating body","isCorrect":false},{"text":"Rate of change of linear momentum","isCorrect":false},{"text":"Force acting along the axis of rotation","isCorrect":false}]'::jsonb,
 null, 'Torque is the rotational analogue of force, measuring the turning effect a force produces about a chosen axis or pivot point.'),

-- Physics: Electrodynamics
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of electric potential (voltage) is the:',
 '[{"text":"Ampere","isCorrect":false},{"text":"Volt","isCorrect":true},{"text":"Ohm","isCorrect":false},{"text":"Coulomb","isCorrect":false}]'::jsonb,
 null, 'Electric potential (voltage) is measured in volts (V), defined as energy per unit charge.'),
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'Which device is used to convert alternating current (AC) into direct current (DC)?',
 '[{"text":"Transformer","isCorrect":false},{"text":"Rectifier","isCorrect":true},{"text":"Generator","isCorrect":false},{"text":"Inverter","isCorrect":false}]'::jsonb,
 null, 'A rectifier, typically built using diodes, converts alternating current into direct current.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'The direction of the magnetic field around a straight current-carrying wire is given by the:',
 '[{"text":"Right-hand thumb rule","isCorrect":true},{"text":"Left-hand rule for force only","isCorrect":false},{"text":"Lenz''s law direction rule","isCorrect":false},{"text":"Fleming''s rule for motors only","isCorrect":false}]'::jsonb,
 null, 'The right-hand thumb rule states that if the thumb points in the direction of conventional current, the curled fingers indicate the direction of the surrounding magnetic field.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'Capacitance is defined as the:',
 '[{"text":"Ability of a system to store electric charge per unit potential difference","isCorrect":true},{"text":"Rate of flow of electric charge","isCorrect":false},{"text":"Opposition offered to current flow","isCorrect":false},{"text":"Total charge stored regardless of voltage","isCorrect":false}]'::jsonb,
 null, 'Capacitance (C=Q/V) quantifies how much electric charge a capacitor can store per unit of potential difference applied across it.'),

-- Physics: Optics and Wave Phenomena
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'The primary rainbow observed in the sky is formed due to:',
 '[{"text":"Diffraction of sunlight by dust particles","isCorrect":false},{"text":"Refraction, dispersion, and internal reflection of sunlight within raindrops","isCorrect":true},{"text":"Interference of sunlight with itself","isCorrect":false},{"text":"Polarization of sunlight by clouds","isCorrect":false}]'::jsonb,
 null, 'A primary rainbow forms when sunlight enters a raindrop, refracts, undergoes one internal reflection, and disperses into its component colors as it exits.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'Hypermetropia (long-sightedness/far-sightedness) is corrected using which type of lens?',
 '[{"text":"Concave lens","isCorrect":false},{"text":"Convex lens","isCorrect":true},{"text":"Cylindrical lens","isCorrect":false},{"text":"Plano-concave lens only","isCorrect":false}]'::jsonb,
 null, 'In hypermetropia, the image forms behind the retina; a convex (converging) lens helps focus the image correctly onto the retina.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The unit used to measure the power of a lens is the:',
 '[{"text":"Diopter","isCorrect":true},{"text":"Candela","isCorrect":false},{"text":"Lumen","isCorrect":false},{"text":"Lux","isCorrect":false}]'::jsonb,
 null, 'Lens power, the reciprocal of focal length in meters, is measured in diopters (D).'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The phenomenon in which a wave bounces back after striking a surface is called:',
 '[{"text":"Refraction","isCorrect":false},{"text":"Reflection","isCorrect":true},{"text":"Diffraction","isCorrect":false},{"text":"Absorption","isCorrect":false}]'::jsonb,
 null, 'Reflection occurs when a wave encounters a boundary and bounces back into the original medium, following the law of reflection.'),

-- Physics: Modern Physics and Semiconductor Devices
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'X-rays were discovered by:',
 '[{"text":"Wilhelm Roentgen","isCorrect":true},{"text":"Marie Curie","isCorrect":false},{"text":"Ernest Rutherford","isCorrect":false},{"text":"Niels Bohr","isCorrect":false}]'::jsonb,
 null, 'Wilhelm Roentgen discovered X-rays in 1895, a discovery for which he was awarded the first Nobel Prize in Physics.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'The process of converting alternating current into direct current using diodes is called:',
 '[{"text":"Amplification","isCorrect":false},{"text":"Rectification","isCorrect":true},{"text":"Modulation","isCorrect":false},{"text":"Oscillation","isCorrect":false}]'::jsonb,
 null, 'Rectification refers to the conversion of AC to DC, commonly achieved using one or more diodes in a rectifier circuit.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Radioactive decay in which a nucleus emits a helium nucleus (2 protons and 2 neutrons) is called:',
 '[{"text":"Beta decay","isCorrect":false},{"text":"Alpha decay","isCorrect":true},{"text":"Gamma decay","isCorrect":false},{"text":"Positron emission","isCorrect":false}]'::jsonb,
 null, 'Alpha decay involves the emission of an alpha particle, which is identical to a helium nucleus (2 protons and 2 neutrons).'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The wave nature of matter (matter waves) was first proposed by:',
 '[{"text":"Louis de Broglie","isCorrect":true},{"text":"Max Planck","isCorrect":false},{"text":"Albert Einstein","isCorrect":false},{"text":"Werner Heisenberg","isCorrect":false}]'::jsonb,
 null, 'Louis de Broglie proposed that particles, like electrons, also exhibit wave-like properties, with wavelength lambda=h/p.'),

-- Chemistry: Physical Chemistry
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'Le Chatelier''s principle predicts how a system at equilibrium responds to:',
 '[{"text":"A change in conditions, such as concentration, temperature, or pressure","isCorrect":true},{"text":"The addition of a catalyst only","isCorrect":false},{"text":"Changes in the container''s color","isCorrect":false},{"text":"The passage of time alone, with no external change","isCorrect":false}]'::jsonb,
 null, 'Le Chatelier''s principle states that a system at equilibrium shifts to counteract any imposed change in concentration, temperature, or pressure.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The number of moles of solute dissolved per kilogram of solvent is called:',
 '[{"text":"Molarity","isCorrect":false},{"text":"Molality","isCorrect":true},{"text":"Normality","isCorrect":false},{"text":"Mole fraction","isCorrect":false}]'::jsonb,
 null, 'Molality is defined as moles of solute per kilogram of solvent, distinct from molarity, which uses solution volume.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'A solution that contains the maximum amount of solute that can dissolve at a given temperature is called a:',
 '[{"text":"Dilute solution","isCorrect":false},{"text":"Saturated solution","isCorrect":true},{"text":"Unsaturated solution","isCorrect":false},{"text":"Colloidal solution","isCorrect":false}]'::jsonb,
 null, 'A saturated solution holds the maximum possible amount of dissolved solute at a given temperature, with any excess remaining undissolved.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'The energy required to break one mole of a particular chemical bond is called:',
 '[{"text":"Ionization energy","isCorrect":false},{"text":"Bond dissociation energy (bond energy)","isCorrect":true},{"text":"Lattice energy","isCorrect":false},{"text":"Activation energy","isCorrect":false}]'::jsonb,
 null, 'Bond dissociation energy (bond energy) is the energy required to break one mole of a specific type of chemical bond in the gaseous state.'),

-- Chemistry: Organic Chemistry
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The characteristic functional group of an amine is:',
 '[{"text":"-OH","isCorrect":false},{"text":"-NH2","isCorrect":true},{"text":"-COOH","isCorrect":false},{"text":"-CHO","isCorrect":false}]'::jsonb,
 null, 'Amines are characterized by the amino functional group, -NH2 (or its substituted forms).'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Vinegar is a dilute aqueous solution of:',
 '[{"text":"Formic acid","isCorrect":false},{"text":"Acetic acid","isCorrect":true},{"text":"Citric acid","isCorrect":false},{"text":"Oxalic acid","isCorrect":false}]'::jsonb,
 null, 'Vinegar is primarily a dilute (typically 4-8%) aqueous solution of acetic acid.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The reaction that converts an alkane into an alkyl halide by substituting a hydrogen atom with a halogen is called:',
 '[{"text":"Halogenation (free radical substitution)","isCorrect":true},{"text":"Hydrogenation","isCorrect":false},{"text":"Hydrolysis","isCorrect":false},{"text":"Esterification","isCorrect":false}]'::jsonb,
 null, 'Halogenation of alkanes typically proceeds via a free radical substitution mechanism, replacing a hydrogen atom with a halogen atom.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The simplest aldehyde is:',
 '[{"text":"Acetaldehyde","isCorrect":false},{"text":"Formaldehyde (methanal)","isCorrect":true},{"text":"Propionaldehyde","isCorrect":false},{"text":"Benzaldehyde","isCorrect":false}]'::jsonb,
 null, 'Formaldehyde (methanal, HCHO) is the simplest aldehyde, consisting of just one carbon atom.'),

-- Chemistry: Inorganic Chemistry
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The chemical formula of quicklime is:',
 '[{"text":"CaO","isCorrect":true},{"text":"Ca(OH)2","isCorrect":false},{"text":"CaCO3","isCorrect":false},{"text":"CaCl2","isCorrect":false}]'::jsonb,
 null, 'Quicklime is calcium oxide, with the chemical formula CaO, produced by heating limestone (calcium carbonate).'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'In the Haber process for manufacturing ammonia, hydrogen is combined with which other gas?',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Nitrogen","isCorrect":true},{"text":"Carbon dioxide","isCorrect":false},{"text":"Chlorine","isCorrect":false}]'::jsonb,
 null, 'The Haber process combines nitrogen and hydrogen gases under high pressure and temperature, with a catalyst, to produce ammonia (N2 + 3H2 -> 2NH3).'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'The most abundant metal in the Earth''s crust is:',
 '[{"text":"Iron","isCorrect":false},{"text":"Aluminum","isCorrect":true},{"text":"Copper","isCorrect":false},{"text":"Calcium","isCorrect":false}]'::jsonb,
 null, 'Aluminum is the most abundant metallic element in the Earth''s crust, though it is typically found combined in ores like bauxite rather than as a free metal.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Rust, formed when iron is exposed to moisture and oxygen, is chemically known as:',
 '[{"text":"Iron sulfide","isCorrect":false},{"text":"Hydrated iron(III) oxide","isCorrect":true},{"text":"Iron carbide","isCorrect":false},{"text":"Iron nitride","isCorrect":false}]'::jsonb,
 null, 'Rust is chemically hydrated iron(III) oxide, formed through the oxidation of iron in the presence of moisture and oxygen.'),

-- Chemistry: Biomolecules and Environmental Chemistry
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Lipids in the body are primarily used for:',
 '[{"text":"Energy storage and structural roles like cell membranes","isCorrect":true},{"text":"Carrying genetic information","isCorrect":false},{"text":"Catalyzing biochemical reactions exclusively","isCorrect":false},{"text":"Transporting oxygen in blood","isCorrect":false}]'::jsonb,
 null, 'Lipids serve important roles in long-term energy storage and as structural components of cell membranes (phospholipids).'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Chlorofluorocarbons (CFCs), a major cause of ozone layer depletion, contain which element besides carbon and fluorine?',
 '[{"text":"Chlorine","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Sulfur","isCorrect":false},{"text":"Phosphorus","isCorrect":false}]'::jsonb,
 null, 'Chlorofluorocarbons contain chlorine, fluorine, and carbon; the chlorine atoms, once released in the stratosphere, catalytically destroy ozone molecules.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Which of the following is classified as a fossil fuel?',
 '[{"text":"Coal","isCorrect":true},{"text":"Solar energy","isCorrect":false},{"text":"Wind energy","isCorrect":false},{"text":"Hydropower","isCorrect":false}]'::jsonb,
 null, 'Coal, formed from the remains of ancient plants over millions of years, is a classic example of a fossil fuel, alongside petroleum and natural gas.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Acid rain is primarily caused by atmospheric pollutants such as:',
 '[{"text":"Sulfur dioxide and nitrogen oxides","isCorrect":true},{"text":"Oxygen and nitrogen","isCorrect":false},{"text":"Water vapor alone","isCorrect":false},{"text":"Argon and helium","isCorrect":false}]'::jsonb,
 null, 'Sulfur dioxide and nitrogen oxides, released mainly from burning fossil fuels, react with atmospheric moisture to form acidic compounds that fall as acid rain.'),

-- Botany: Plant Physiology
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'Which structure on leaves is primarily responsible for gas exchange in plants?',
 '[{"text":"Stomata","isCorrect":true},{"text":"Cuticle","isCorrect":false},{"text":"Trichomes","isCorrect":false},{"text":"Veins","isCorrect":false}]'::jsonb,
 null, 'Stomata, tiny pores mainly on the leaf surface, are the primary sites of gas exchange (CO2 in, O2 out) and water vapor loss in plants.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Gibberellins, a class of plant hormones, are primarily associated with promoting:',
 '[{"text":"Leaf senescence","isCorrect":false},{"text":"Stem elongation","isCorrect":true},{"text":"Stomatal closure","isCorrect":false},{"text":"Root hair formation only","isCorrect":false}]'::jsonb,
 null, 'Gibberellins promote stem elongation and are also involved in seed germination and flowering.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The process by which plant roots absorb water due to a difference in solute concentration across the cell membrane is called:',
 '[{"text":"Diffusion of gases","isCorrect":false},{"text":"Osmosis","isCorrect":true},{"text":"Active transport of ions only","isCorrect":false},{"text":"Guttation","isCorrect":false}]'::jsonb,
 null, 'Osmosis is the movement of water across a selectively permeable membrane from a region of lower solute concentration to higher solute concentration, driving water absorption by root cells.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Nitrogen fixation in the root nodules of leguminous plants is carried out by which bacteria?',
 '[{"text":"Rhizobium","isCorrect":true},{"text":"Escherichia coli","isCorrect":false},{"text":"Lactobacillus","isCorrect":false},{"text":"Streptococcus","isCorrect":false}]'::jsonb,
 null, 'Rhizobium bacteria form a symbiotic relationship with leguminous plants, fixing atmospheric nitrogen into a usable form within root nodules.'),

-- Botany: Cell Biology and Genetics
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'Which cell organelle is primarily responsible for the digestion of waste materials within the cell?',
 '[{"text":"Lysosome","isCorrect":true},{"text":"Peroxisome only","isCorrect":false},{"text":"Nucleolus","isCorrect":false},{"text":"Centriole","isCorrect":false}]'::jsonb,
 null, 'Lysosomes contain digestive enzymes that break down waste materials, damaged organelles, and foreign particles within the cell.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'Which structure controls the entry and exit of substances into and out of the cell?',
 '[{"text":"Nucleus","isCorrect":false},{"text":"Plasma membrane (cell membrane)","isCorrect":true},{"text":"Golgi apparatus","isCorrect":false},{"text":"Ribosome","isCorrect":false}]'::jsonb,
 null, 'The plasma membrane is a selectively permeable barrier that regulates the movement of substances into and out of the cell.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'The number of chromosomes present in a haploid human gamete (sperm or egg) is:',
 '[{"text":"23","isCorrect":true},{"text":"46","isCorrect":false},{"text":"22","isCorrect":false},{"text":"44","isCorrect":false}]'::jsonb,
 null, 'Human gametes are haploid, containing 23 chromosomes, half the diploid number of 46 found in somatic cells.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'Crossing over during meiosis primarily results in:',
 '[{"text":"Genetic recombination (variation)","isCorrect":true},{"text":"Identical daughter cells with no variation","isCorrect":false},{"text":"Doubling of chromosome number","isCorrect":false},{"text":"Loss of genetic material entirely","isCorrect":false}]'::jsonb,
 null, 'Crossing over, the exchange of genetic material between homologous chromosomes during meiosis, generates new combinations of alleles, increasing genetic variation.'),

-- Botany: Ecology and Environment
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'A food web is best described as:',
 '[{"text":"A single, isolated food chain","isCorrect":false},{"text":"An interconnected network of multiple interlinked food chains","isCorrect":true},{"text":"A group of only producers in an ecosystem","isCorrect":false},{"text":"A single predator-prey relationship","isCorrect":false}]'::jsonb,
 null, 'A food web represents the complex, interconnected network formed by multiple overlapping food chains within an ecosystem.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'Which of the following is an example of an abiotic factor in an ecosystem?',
 '[{"text":"Bacteria","isCorrect":false},{"text":"Temperature","isCorrect":true},{"text":"Plants","isCorrect":false},{"text":"Animals","isCorrect":false}]'::jsonb,
 null, 'Abiotic factors are non-living components of an ecosystem, such as temperature, sunlight, soil, and water, that influence living organisms.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'The Wildlife Protection Act, a key Indian legislation for biodiversity conservation, was enacted in the year:',
 '[{"text":"1972","isCorrect":true},{"text":"1980","isCorrect":false},{"text":"1991","isCorrect":false},{"text":"2000","isCorrect":false}]'::jsonb,
 null, 'India''s Wildlife Protection Act was enacted in 1972 to provide legal protection for wild animals, birds, and plants.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'Deforestation primarily leads to:',
 '[{"text":"Increased biodiversity","isCorrect":false},{"text":"Loss of biodiversity and increased soil erosion","isCorrect":true},{"text":"Cooling of the local climate only","isCorrect":false},{"text":"Increased groundwater levels only","isCorrect":false}]'::jsonb,
 null, 'Deforestation removes habitats, causing loss of biodiversity, while exposed soil becomes more vulnerable to erosion by wind and rain.'),

-- Botany: Plant Morphology and Anatomy
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'Which part of the flower develops into a fruit after fertilization?',
 '[{"text":"Sepal","isCorrect":false},{"text":"Ovary","isCorrect":true},{"text":"Petal","isCorrect":false},{"text":"Anther","isCorrect":false}]'::jsonb,
 null, 'After fertilization, the ovary of a flower develops into the fruit, while the ovules within it develop into seeds.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'In a typical monocot stem, the vascular bundles are arranged:',
 '[{"text":"In a single ring near the periphery","isCorrect":false},{"text":"Scattered throughout the ground tissue","isCorrect":true},{"text":"Only at the very center","isCorrect":false},{"text":"In a perfect straight line","isCorrect":false}]'::jsonb,
 null, 'Monocot stems typically have vascular bundles scattered throughout the ground tissue, unlike dicot stems, where they are arranged in a distinct ring.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'Root hairs primarily function to:',
 '[{"text":"Anchor the plant deeply into rock","isCorrect":false},{"text":"Increase the surface area for water and mineral absorption","isCorrect":true},{"text":"Photosynthesize food","isCorrect":false},{"text":"Produce flowers","isCorrect":false}]'::jsonb,
 null, 'Root hairs are fine, tubular extensions of root epidermal cells that greatly increase the surface area available for absorbing water and dissolved minerals.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The arrangement pattern of veins in a leaf is called:',
 '[{"text":"Phyllotaxy","isCorrect":false},{"text":"Venation","isCorrect":true},{"text":"Aestivation","isCorrect":false},{"text":"Vernation","isCorrect":false}]'::jsonb,
 null, 'Venation refers to the pattern in which veins are arranged within a leaf blade, such as reticulate (net-like) or parallel venation.'),

-- Zoology: Human Physiology
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'The functional unit of the nervous system is the:',
 '[{"text":"Nephron","isCorrect":false},{"text":"Neuron","isCorrect":true},{"text":"Alveolus","isCorrect":false},{"text":"Sarcomere","isCorrect":false}]'::jsonb,
 null, 'The neuron (nerve cell) is the basic structural and functional unit of the nervous system, responsible for transmitting electrical and chemical signals.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which hormone, secreted by the adrenal medulla in response to stress, is often called the "fight or flight" hormone?',
 '[{"text":"Insulin","isCorrect":false},{"text":"Adrenaline (epinephrine)","isCorrect":true},{"text":"Thyroxine","isCorrect":false},{"text":"Estrogen","isCorrect":false}]'::jsonb,
 null, 'Adrenaline (epinephrine), secreted by the adrenal medulla, prepares the body for rapid action during stressful situations, hence its "fight or flight" nickname.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'A deficiency of which vitamin causes night blindness?',
 '[{"text":"Vitamin A","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":false},{"text":"Vitamin K","isCorrect":false}]'::jsonb,
 null, 'Vitamin A is essential for producing rhodopsin, the light-sensitive pigment in the retina''s rod cells; its deficiency impairs vision in low light, causing night blindness.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'The formation of urine in the nephron involves filtration, reabsorption, and:',
 '[{"text":"Digestion","isCorrect":false},{"text":"Secretion","isCorrect":true},{"text":"Respiration","isCorrect":false},{"text":"Fermentation","isCorrect":false}]'::jsonb,
 null, 'Urine formation involves three key processes: glomerular filtration, tubular reabsorption of useful substances, and tubular secretion of additional wastes into the filtrate.'),

-- Zoology: Human Reproduction and Reproductive Health
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'easy', 'mcq',
 'Which hormone is primarily responsible for the development of male secondary sexual characteristics?',
 '[{"text":"Estrogen","isCorrect":false},{"text":"Testosterone","isCorrect":true},{"text":"Progesterone","isCorrect":false},{"text":"Oxytocin","isCorrect":false}]'::jsonb,
 null, 'Testosterone, secreted by the testes, drives the development of male secondary sexual characteristics, such as facial hair and a deeper voice.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'easy', 'mcq',
 'The umbilical cord primarily connects the developing fetus to the:',
 '[{"text":"Placenta","isCorrect":true},{"text":"Ovary","isCorrect":false},{"text":"Uterus wall directly, bypassing the placenta","isCorrect":false},{"text":"Amniotic sac only","isCorrect":false}]'::jsonb,
 null, 'The umbilical cord connects the fetus to the placenta, allowing exchange of nutrients, gases, and waste between mother and fetus.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Amenorrhea refers to the:',
 '[{"text":"Excessive menstrual bleeding","isCorrect":false},{"text":"Absence of menstruation","isCorrect":true},{"text":"Painful menstruation","isCorrect":false},{"text":"Irregular ovulation only","isCorrect":false}]'::jsonb,
 null, 'Amenorrhea is the medical term for the absence of menstruation, which can be normal (e.g. before puberty, during pregnancy) or indicate an underlying condition.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'Which of the following is a permanent method of contraception in males?',
 '[{"text":"Condom","isCorrect":false},{"text":"Vasectomy","isCorrect":true},{"text":"Oral contraceptive pill","isCorrect":false},{"text":"Copper-T (IUD)","isCorrect":false}]'::jsonb,
 null, 'Vasectomy is a surgical procedure that permanently blocks the vas deferens, preventing sperm from being included in the ejaculate.'),

-- Zoology: Genetics and Evolution
('NEET UG', 'Zoology', 'Genetics and Evolution', 'easy', 'mcq',
 'The scientific study of heredity and variation among organisms is called:',
 '[{"text":"Ecology","isCorrect":false},{"text":"Genetics","isCorrect":true},{"text":"Taxonomy","isCorrect":false},{"text":"Physiology","isCorrect":false}]'::jsonb,
 null, 'Genetics is the branch of biology concerned with the study of heredity and the variation of inherited characteristics.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'A codominant trait is one in which:',
 '[{"text":"Only the dominant allele is ever expressed","isCorrect":false},{"text":"Both alleles are fully and simultaneously expressed in the phenotype","isCorrect":true},{"text":"Neither allele is ever expressed","isCorrect":false},{"text":"The alleles blend into an intermediate phenotype","isCorrect":false}]'::jsonb,
 null, 'In codominance, both alleles in a heterozygous individual are fully expressed simultaneously and distinctly in the phenotype, rather than blending or one masking the other.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'Fossils provide evidence for evolution primarily by showing:',
 '[{"text":"A chronological record of gradual change in organisms over geological time","isCorrect":true},{"text":"That all species have remained unchanged over time","isCorrect":false},{"text":"Only the existence of currently living species","isCorrect":false},{"text":"The exact future evolution of a species","isCorrect":false}]'::jsonb,
 null, 'Fossils, found in successive geological strata, reveal a chronological record showing gradual morphological changes in lineages of organisms over vast timescales.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'hard', 'mcq',
 'The Hardy-Weinberg principle describes the conditions under which:',
 '[{"text":"A population''s allele frequencies constantly change every generation","isCorrect":false},{"text":"Allele frequencies in a population remain constant (genetic equilibrium) across generations","isCorrect":true},{"text":"All individuals in a population are genetically identical","isCorrect":false},{"text":"Mutation rates increase indefinitely","isCorrect":false}]'::jsonb,
 null, 'The Hardy-Weinberg principle describes an idealized population (no mutation, migration, selection, or genetic drift) in which allele and genotype frequencies remain constant across generations.'),

-- Zoology: Biotechnology and its Applications
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'A commonly used vector for carrying foreign DNA into a host bacterial cell in genetic engineering is a:',
 '[{"text":"Plasmid","isCorrect":true},{"text":"Ribosome","isCorrect":false},{"text":"Mitochondrion","isCorrect":false},{"text":"Lysosome","isCorrect":false}]'::jsonb,
 null, 'Plasmids, small circular DNA molecules found in bacteria, are commonly used as vectors to carry and introduce foreign genes into host cells.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'The ELISA test, commonly used for molecular diagnosis of diseases, primarily detects:',
 '[{"text":"The presence of a specific antigen or antibody","isCorrect":true},{"text":"The exact DNA sequence of an organism","isCorrect":false},{"text":"Blood glucose levels only","isCorrect":false},{"text":"Body temperature","isCorrect":false}]'::jsonb,
 null, 'ELISA (Enzyme-Linked Immunosorbent Assay) detects and quantifies the presence of a specific antigen or antibody in a sample, widely used for disease diagnosis.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Transgenic organisms are those that:',
 '[{"text":"Have had all genetic material removed","isCorrect":false},{"text":"Contain a gene from another species introduced into their genome","isCorrect":true},{"text":"Are produced only through natural breeding","isCorrect":false},{"text":"Cannot reproduce at all","isCorrect":false}]'::jsonb,
 null, 'Transgenic organisms carry a gene (or genes) artificially introduced from another species, giving them new traits not naturally present in their genome.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Stem cells are characterized primarily by their ability to:',
 '[{"text":"Differentiate into multiple different cell types","isCorrect":true},{"text":"Only ever remain as blood cells","isCorrect":false},{"text":"Cause disease in all cases","isCorrect":false},{"text":"Never divide again once formed","isCorrect":false}]'::jsonb,
 null, 'Stem cells are unspecialized cells capable of both self-renewal and differentiation into various specialized cell types, making them valuable in research and regenerative medicine.');
