-- supabase/sql/exam_question_bank_class1_set1.sql
--
-- First curated question-bank batch for 'Class 1' (see exam_patterns_class1.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 1's MCQ-only,
-- no-negative-marking pattern. 9 chapters (3 per subject x 3 subjects) each get 4 questions, mostly
-- easy with one medium, reflecting the heavily easy-skewed weightage in exam_patterns_class1.sql.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class1.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Alphabets and Phonics
('Class 1', 'English', 'Alphabets and Phonics', 'easy', 'mcq',
 'Which letter comes just after ''B'' in the English alphabet?',
 '[{"text":"A","isCorrect":false},{"text":"C","isCorrect":true},{"text":"D","isCorrect":false},{"text":"E","isCorrect":false}]'::jsonb,
 null, 'The alphabet order is A, B, C, D... so the letter right after B is C.'),
('Class 1', 'English', 'Alphabets and Phonics', 'easy', 'mcq',
 'Which of these letters is a vowel?',
 '[{"text":"B","isCorrect":false},{"text":"C","isCorrect":false},{"text":"A","isCorrect":true},{"text":"D","isCorrect":false}]'::jsonb,
 null, 'A, E, I, O and U are vowels. A is a vowel; B, C and D are consonants.'),
('Class 1', 'English', 'Alphabets and Phonics', 'easy', 'mcq',
 'Which letter comes just before ''M'' in the English alphabet?',
 '[{"text":"N","isCorrect":false},{"text":"L","isCorrect":true},{"text":"K","isCorrect":false},{"text":"O","isCorrect":false}]'::jsonb,
 null, 'The alphabet order is ...K, L, M, N... so the letter right before M is L.'),
('Class 1', 'English', 'Alphabets and Phonics', 'medium', 'mcq',
 'How many letters are there in the English alphabet?',
 '[{"text":"24","isCorrect":false},{"text":"25","isCorrect":false},{"text":"26","isCorrect":true},{"text":"27","isCorrect":false}]'::jsonb,
 null, 'The English alphabet has 26 letters, from A to Z.'),

-- English: Vowels, Consonants and Simple Words
('Class 1', 'English', 'Vowels, Consonants and Simple Words', 'easy', 'mcq',
 'Which of the following is a consonant?',
 '[{"text":"A","isCorrect":false},{"text":"E","isCorrect":false},{"text":"I","isCorrect":false},{"text":"T","isCorrect":true}]'::jsonb,
 null, 'A, E and I are vowels. T is a consonant.'),
('Class 1', 'English', 'Vowels, Consonants and Simple Words', 'easy', 'mcq',
 'How many vowels are there in the English alphabet?',
 '[{"text":"3","isCorrect":false},{"text":"4","isCorrect":false},{"text":"5","isCorrect":true},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'There are 5 vowels: A, E, I, O and U.'),
('Class 1', 'English', 'Vowels, Consonants and Simple Words', 'easy', 'mcq',
 'Which of these words starts with a vowel sound?',
 '[{"text":"Apple","isCorrect":true},{"text":"Ball","isCorrect":false},{"text":"Cat","isCorrect":false},{"text":"Dog","isCorrect":false}]'::jsonb,
 null, '''Apple'' starts with the vowel letter A. Ball, Cat and Dog all start with consonants.'),
('Class 1', 'English', 'Vowels, Consonants and Simple Words', 'medium', 'mcq',
 'Which of these letters is NOT a vowel?',
 '[{"text":"A","isCorrect":false},{"text":"E","isCorrect":false},{"text":"O","isCorrect":false},{"text":"B","isCorrect":true}]'::jsonb,
 null, 'A, E and O are vowels. B is a consonant, so it is the one that is not a vowel.'),

-- English: Rhyming Words, Opposites and Picture Reading
('Class 1', 'English', 'Rhyming Words, Opposites and Picture Reading', 'easy', 'mcq',
 'Which word rhymes with ''CAT''?',
 '[{"text":"Dog","isCorrect":false},{"text":"Hat","isCorrect":true},{"text":"Sun","isCorrect":false},{"text":"Cup","isCorrect":false}]'::jsonb,
 null, '''Hat'' rhymes with ''Cat'' because they both end with the same ''-at'' sound.'),
('Class 1', 'English', 'Rhyming Words, Opposites and Picture Reading', 'easy', 'mcq',
 'What is the opposite of ''HOT''?',
 '[{"text":"Warm","isCorrect":false},{"text":"Cold","isCorrect":true},{"text":"Big","isCorrect":false},{"text":"Fast","isCorrect":false}]'::jsonb,
 null, 'The opposite of ''Hot'' is ''Cold''.'),
('Class 1', 'English', 'Rhyming Words, Opposites and Picture Reading', 'easy', 'mcq',
 'What is the opposite of ''UP''?',
 '[{"text":"Down","isCorrect":true},{"text":"Left","isCorrect":false},{"text":"Right","isCorrect":false},{"text":"In","isCorrect":false}]'::jsonb,
 null, 'The opposite of ''Up'' is ''Down''.'),
('Class 1', 'English', 'Rhyming Words, Opposites and Picture Reading', 'medium', 'mcq',
 'Which word rhymes with ''STAR''?',
 '[{"text":"Sun","isCorrect":false},{"text":"Moon","isCorrect":false},{"text":"Car","isCorrect":true},{"text":"Sky","isCorrect":false}]'::jsonb,
 null, '''Car'' rhymes with ''Star'' because they both end with the same ''-ar'' sound.'),

-- Mathematics: Numbers 1 to 100 (Counting, Before-After-Between)
('Class 1', 'Mathematics', 'Numbers 1 to 100 (Counting, Before-After-Between)', 'easy', 'mcq',
 'What number comes just after 19?',
 '[{"text":"18","isCorrect":false},{"text":"20","isCorrect":true},{"text":"21","isCorrect":false},{"text":"29","isCorrect":false}]'::jsonb,
 null, 'Counting up from 19, the next number is 20.'),
('Class 1', 'Mathematics', 'Numbers 1 to 100 (Counting, Before-After-Between)', 'easy', 'mcq',
 'What number comes just before 50?',
 '[{"text":"49","isCorrect":true},{"text":"51","isCorrect":false},{"text":"48","isCorrect":false},{"text":"52","isCorrect":false}]'::jsonb,
 null, 'Counting down from 50, the number right before it is 49.'),
('Class 1', 'Mathematics', 'Numbers 1 to 100 (Counting, Before-After-Between)', 'easy', 'mcq',
 'Which number is between 25 and 27?',
 '[{"text":"24","isCorrect":false},{"text":"26","isCorrect":true},{"text":"28","isCorrect":false},{"text":"29","isCorrect":false}]'::jsonb,
 null, '26 comes right between 25 and 27 when counting in order.'),
('Class 1', 'Mathematics', 'Numbers 1 to 100 (Counting, Before-After-Between)', 'medium', 'mcq',
 'What is the number name for 15?',
 '[{"text":"Fifty","isCorrect":false},{"text":"Fifteen","isCorrect":true},{"text":"Five","isCorrect":false},{"text":"Fifty-one","isCorrect":false}]'::jsonb,
 null, 'The number 15 is written in words as ''Fifteen''.'),

-- Mathematics: Addition and Subtraction (up to 20)
('Class 1', 'Mathematics', 'Addition and Subtraction (up to 20)', 'easy', 'mcq',
 '7 + 5 = ?',
 '[{"text":"11","isCorrect":false},{"text":"12","isCorrect":true},{"text":"13","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, '7 + 5 = 12.'),
('Class 1', 'Mathematics', 'Addition and Subtraction (up to 20)', 'easy', 'mcq',
 '18 - 6 = ?',
 '[{"text":"11","isCorrect":false},{"text":"12","isCorrect":true},{"text":"13","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, '18 - 6 = 12.'),
('Class 1', 'Mathematics', 'Addition and Subtraction (up to 20)', 'easy', 'mcq',
 '9 + 9 = ?',
 '[{"text":"16","isCorrect":false},{"text":"17","isCorrect":false},{"text":"18","isCorrect":true},{"text":"19","isCorrect":false}]'::jsonb,
 null, '9 + 9 = 18.'),
('Class 1', 'Mathematics', 'Addition and Subtraction (up to 20)', 'medium', 'mcq',
 '20 - 8 + 3 = ?',
 '[{"text":"15","isCorrect":true},{"text":"14","isCorrect":false},{"text":"13","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'First 20 - 8 = 12, then 12 + 3 = 15.'),

-- Mathematics: Shapes, Patterns and Measurement
('Class 1', 'Mathematics', 'Shapes, Patterns and Measurement', 'easy', 'mcq',
 'How many sides does a triangle have?',
 '[{"text":"2","isCorrect":false},{"text":"3","isCorrect":true},{"text":"4","isCorrect":false},{"text":"5","isCorrect":false}]'::jsonb,
 null, 'A triangle has 3 sides.'),
('Class 1', 'Mathematics', 'Shapes, Patterns and Measurement', 'easy', 'mcq',
 'Which shape has no corners?',
 '[{"text":"Square","isCorrect":false},{"text":"Triangle","isCorrect":false},{"text":"Circle","isCorrect":true},{"text":"Rectangle","isCorrect":false}]'::jsonb,
 null, 'A circle is round and has no corners, unlike a square, triangle or rectangle.'),
('Class 1', 'Mathematics', 'Shapes, Patterns and Measurement', 'easy', 'mcq',
 'How many sides does a square have?',
 '[{"text":"3","isCorrect":false},{"text":"4","isCorrect":true},{"text":"5","isCorrect":false},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'A square has 4 equal sides.'),
('Class 1', 'Mathematics', 'Shapes, Patterns and Measurement', 'medium', 'mcq',
 'In the pattern Circle, Square, Circle, Square, ___, what comes next?',
 '[{"text":"Circle","isCorrect":true},{"text":"Square","isCorrect":false},{"text":"Triangle","isCorrect":false},{"text":"Star","isCorrect":false}]'::jsonb,
 null, 'The pattern alternates Circle, Square, so after Square the next shape is Circle again.'),

-- EVS: Myself, My Family and My Body
('Class 1', 'EVS', 'Myself, My Family and My Body', 'easy', 'mcq',
 'Which part of the body do we use to see?',
 '[{"text":"Ears","isCorrect":false},{"text":"Eyes","isCorrect":true},{"text":"Nose","isCorrect":false},{"text":"Hands","isCorrect":false}]'::jsonb,
 null, 'We use our eyes to see things around us.'),
('Class 1', 'EVS', 'Myself, My Family and My Body', 'easy', 'mcq',
 'Which part of the body do we use to hear?',
 '[{"text":"Eyes","isCorrect":false},{"text":"Ears","isCorrect":true},{"text":"Nose","isCorrect":false},{"text":"Tongue","isCorrect":false}]'::jsonb,
 null, 'We use our ears to hear sounds.'),
('Class 1', 'EVS', 'Myself, My Family and My Body', 'easy', 'mcq',
 'What do we call the mother of your mother?',
 '[{"text":"Aunt","isCorrect":false},{"text":"Sister","isCorrect":false},{"text":"Grandmother","isCorrect":true},{"text":"Cousin","isCorrect":false}]'::jsonb,
 null, 'Your mother''s mother is called your grandmother.'),
('Class 1', 'EVS', 'Myself, My Family and My Body', 'medium', 'mcq',
 'Which part of the body helps us to smell?',
 '[{"text":"Eyes","isCorrect":false},{"text":"Ears","isCorrect":false},{"text":"Nose","isCorrect":true},{"text":"Skin","isCorrect":false}]'::jsonb,
 null, 'We use our nose to smell things.'),

-- EVS: Plants and Animals Around Us
('Class 1', 'EVS', 'Plants and Animals Around Us', 'easy', 'mcq',
 'Which of these is a plant?',
 '[{"text":"Cat","isCorrect":false},{"text":"Mango tree","isCorrect":true},{"text":"Dog","isCorrect":false},{"text":"Cow","isCorrect":false}]'::jsonb,
 null, 'A mango tree is a plant. Cat, Dog and Cow are all animals.'),
('Class 1', 'EVS', 'Plants and Animals Around Us', 'easy', 'mcq',
 'Which animal gives us milk?',
 '[{"text":"Cow","isCorrect":true},{"text":"Cat","isCorrect":false},{"text":"Dog","isCorrect":false},{"text":"Hen","isCorrect":false}]'::jsonb,
 null, 'A cow gives us milk.'),
('Class 1', 'EVS', 'Plants and Animals Around Us', 'easy', 'mcq',
 'Which of these animals can fly?',
 '[{"text":"Cow","isCorrect":false},{"text":"Bird","isCorrect":true},{"text":"Fish","isCorrect":false},{"text":"Dog","isCorrect":false}]'::jsonb,
 null, 'A bird has wings and can fly. Cow, Fish and Dog cannot.'),
('Class 1', 'EVS', 'Plants and Animals Around Us', 'medium', 'mcq',
 'Which part of a plant is usually found under the soil?',
 '[{"text":"Leaf","isCorrect":false},{"text":"Flower","isCorrect":false},{"text":"Root","isCorrect":true},{"text":"Stem","isCorrect":false}]'::jsonb,
 null, 'The root of a plant grows under the soil and holds the plant in place.'),

-- EVS: Good Habits, Safety and Our Surroundings
('Class 1', 'EVS', 'Good Habits, Safety and Our Surroundings', 'easy', 'mcq',
 'What should we do before eating food?',
 '[{"text":"Wash our hands","isCorrect":true},{"text":"Watch TV","isCorrect":false},{"text":"Sleep","isCorrect":false},{"text":"Run outside","isCorrect":false}]'::jsonb,
 null, 'We should always wash our hands before eating to stay clean and healthy.'),
('Class 1', 'EVS', 'Good Habits, Safety and Our Surroundings', 'easy', 'mcq',
 'Which colour on the traffic light means STOP?',
 '[{"text":"Green","isCorrect":false},{"text":"Red","isCorrect":true},{"text":"Yellow","isCorrect":false},{"text":"Blue","isCorrect":false}]'::jsonb,
 null, 'The red light means STOP at a traffic signal.'),
('Class 1', 'EVS', 'Good Habits, Safety and Our Surroundings', 'easy', 'mcq',
 'What should we do with garbage?',
 '[{"text":"Throw it anywhere","isCorrect":false},{"text":"Put it in the dustbin","isCorrect":true},{"text":"Burn it at home","isCorrect":false},{"text":"Hide it","isCorrect":false}]'::jsonb,
 null, 'Garbage should always be put in the dustbin to keep our surroundings clean.'),
('Class 1', 'EVS', 'Good Habits, Safety and Our Surroundings', 'medium', 'mcq',
 'Which of these is a good habit?',
 '[{"text":"Brushing teeth every day","isCorrect":true},{"text":"Not washing hands","isCorrect":false},{"text":"Sleeping very late every day","isCorrect":false},{"text":"Littering the street","isCorrect":false}]'::jsonb,
 null, 'Brushing our teeth every day keeps them clean and healthy -- a good habit.');
