-- supabase/sql/exam_question_bank_ssc_stenographer_set1.sql
--
-- First curated question-bank batch for 'SSC Stenographer' (see exam_patterns_ssc_stenographer.sql
-- for the exam's structure). Same exam_question_bank table/schema as the other sets -- no
-- migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option (single-best-response,
-- matching the real exam). Non-Verbal Reasoning again uses text-describable puzzles in place of
-- figure-based questions, which need images this schema can't provide. 16 chapters (4 General
-- Intelligence + 4 General Awareness + 8 English, reflecting English's larger real-exam share)
-- each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_ssc_stenographer.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- General Intelligence and Reasoning: Analogies and Classification
('SSC Stenographer', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Doctor is to Hospital as Teacher is to:',
 '[{"text":"Book","isCorrect":false},{"text":"School","isCorrect":true},{"text":"Student","isCorrect":false},{"text":"Chalk","isCorrect":false}]'::jsonb,
 null, 'A doctor works in a hospital, just as a teacher works in a school.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Analogies and Classification', 'easy', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Rose","isCorrect":false},{"text":"Lotus","isCorrect":false},{"text":"Jasmine","isCorrect":false},{"text":"Mango","isCorrect":true}]'::jsonb,
 null, 'Rose, Lotus and Jasmine are flowers, while Mango is a fruit.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Doctor is to Stethoscope as Carpenter is to:',
 '[{"text":"Saw","isCorrect":true},{"text":"Needle","isCorrect":false},{"text":"Brush","isCorrect":false},{"text":"Pen","isCorrect":false}]'::jsonb,
 null, 'A doctor uses a stethoscope as a primary tool, just as a carpenter uses a saw.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Analogies and Classification', 'medium', 'mcq',
 'Which of the following does not belong with the others?',
 '[{"text":"Guitar","isCorrect":false},{"text":"Violin","isCorrect":false},{"text":"Sitar","isCorrect":false},{"text":"Flute","isCorrect":true}]'::jsonb,
 null, 'Guitar, Violin and Sitar are string instruments, while a Flute is a wind instrument.'),

-- General Intelligence and Reasoning: Series and Coding-Decoding
('SSC Stenographer', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'Find the next number in the series: 4, 8, 16, 32, ?',
 '[{"text":"48","isCorrect":false},{"text":"56","isCorrect":false},{"text":"64","isCorrect":true},{"text":"72","isCorrect":false}]'::jsonb,
 null, 'Each term doubles the previous one, so the next term is 32 x 2 = 64.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'easy', 'mcq',
 'If BOOK is coded as CPPL, how is PAGE coded in the same language?',
 '[{"text":"QBHF","isCorrect":true},{"text":"QBGF","isCorrect":false},{"text":"PBHF","isCorrect":false},{"text":"QCHF","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so PAGE becomes QBHF.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'Find the next number in the series: 100, 50, 25, 12.5, ?',
 '[{"text":"5","isCorrect":false},{"text":"6","isCorrect":false},{"text":"6.25","isCorrect":true},{"text":"7","isCorrect":false}]'::jsonb,
 null, 'Each term is half the previous one, so the next term is 12.5 / 2 = 6.25.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Series and Coding-Decoding', 'medium', 'mcq',
 'If in a code language MADRAS is written as NBESBT, how is DELHI written in the same code?',
 '[{"text":"EFMIJ","isCorrect":true},{"text":"EFMJI","isCorrect":false},{"text":"EGMIJ","isCorrect":false},{"text":"FFMIJ","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one place in the alphabet, so DELHI becomes EFMIJ.'),

-- General Intelligence and Reasoning: Non-Verbal Reasoning
('SSC Stenographer', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'easy', 'mcq',
 'How many faces does a cylinder have?',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":false},{"text":"3","isCorrect":true},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'A cylinder has 3 faces: two flat circular faces and one curved surface.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'If today is Monday, what day will it be after 15 days?',
 '[{"text":"Monday","isCorrect":false},{"text":"Tuesday","isCorrect":true},{"text":"Wednesday","isCorrect":false},{"text":"Sunday","isCorrect":false}]'::jsonb,
 null, '15 days is 2 full weeks (14 days) plus 1 extra day, so the day advances from Monday to Tuesday.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'medium', 'mcq',
 'A cube is cut into two equal halves by a single straight plane cut through its center, parallel to one face. What is the shape of the cross-section?',
 '[{"text":"Circle","isCorrect":false},{"text":"Triangle","isCorrect":false},{"text":"Rectangle","isCorrect":true},{"text":"Pentagon","isCorrect":false}]'::jsonb,
 null, 'Cutting a cube parallel to one of its faces produces a square/rectangular cross-section.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Non-Verbal Reasoning', 'hard', 'mcq',
 'In a row of children, Rahul is 7th from the left and 12th from the right. How many children are in the row?',
 '[{"text":"18","isCorrect":true},{"text":"19","isCorrect":false},{"text":"17","isCorrect":false},{"text":"20","isCorrect":false}]'::jsonb,
 null, 'Total = (position from left) + (position from right) - 1 = 7 + 12 - 1 = 18.'),

-- General Intelligence and Reasoning: Blood Relations and Direction Sense
('SSC Stenographer', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'easy', 'mcq',
 'A is the mother of B. B is the father of C. How is A related to C?',
 '[{"text":"Grandmother","isCorrect":true},{"text":"Aunt","isCorrect":false},{"text":"Mother","isCorrect":false},{"text":"Sister","isCorrect":false}]'::jsonb,
 null, 'Since A is B''s mother and B is C''s father, A is C''s grandmother.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Suresh walks 10 km south, then 10 km west. How far is he from his starting point?',
 '[{"text":"10 km","isCorrect":false},{"text":"14.14 km","isCorrect":true},{"text":"20 km","isCorrect":false},{"text":"0 km","isCorrect":false}]'::jsonb,
 null, 'By the Pythagorean theorem, the distance is sqrt(10^2 + 10^2) = sqrt(200), approximately 14.14 km.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'medium', 'mcq',
 'Pointing to a boy, a woman said, "His mother is the only daughter of my father," and she has no siblings. How is the woman related to the boy?',
 '[{"text":"Mother","isCorrect":true},{"text":"Aunt","isCorrect":false},{"text":"Sister","isCorrect":false},{"text":"Grandmother","isCorrect":false}]'::jsonb,
 null, 'Since the woman has no siblings, "my father''s only daughter" refers to herself, so the boy''s mother is the woman -- making the boy her son.'),
('SSC Stenographer', 'General Intelligence and Reasoning', 'Blood Relations and Direction Sense', 'hard', 'mcq',
 'A man walks 3 km north, 4 km east, then 3 km south. How far and in which direction is he from his starting point?',
 '[{"text":"4 km East","isCorrect":true},{"text":"4 km West","isCorrect":false},{"text":"3 km North","isCorrect":false},{"text":"10 km","isCorrect":false}]'::jsonb,
 null, 'The 3 km north and 3 km south movements cancel out, leaving only the 4 km eastward movement.'),

-- General Awareness: Indian History and Culture
('SSC Stenographer', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'Who is known as the "Iron Man of India"?',
 '[{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Sardar Vallabhbhai Patel","isCorrect":true},{"text":"Subhas Chandra Bose","isCorrect":false},{"text":"Bhagat Singh","isCorrect":false}]'::jsonb,
 null, 'Sardar Vallabhbhai Patel is known as the "Iron Man of India" for unifying the princely states.'),
('SSC Stenographer', 'General Awareness', 'Indian History and Culture', 'easy', 'mcq',
 'The Sepoy Mutiny (First War of Independence) took place in which year?',
 '[{"text":"1857","isCorrect":true},{"text":"1885","isCorrect":false},{"text":"1905","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'The Sepoy Mutiny, also called the First War of Independence, began in 1857.'),
('SSC Stenographer', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'Who was the last Mughal emperor of India?',
 '[{"text":"Bahadur Shah Zafar","isCorrect":true},{"text":"Akbar II","isCorrect":false},{"text":"Shah Alam II","isCorrect":false},{"text":"Aurangzeb","isCorrect":false}]'::jsonb,
 null, 'Bahadur Shah Zafar was the last Mughal emperor, exiled by the British after the 1857 revolt.'),
('SSC Stenographer', 'General Awareness', 'Indian History and Culture', 'medium', 'mcq',
 'The Simon Commission visited India in which year?',
 '[{"text":"1928","isCorrect":true},{"text":"1919","isCorrect":false},{"text":"1935","isCorrect":false},{"text":"1942","isCorrect":false}]'::jsonb,
 null, 'The Simon Commission arrived in India in 1928 and faced widespread protests.'),

-- General Awareness: Indian Polity and Geography
('SSC Stenographer', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'What is the maximum strength of the Rajya Sabha?',
 '[{"text":"245","isCorrect":false},{"text":"250","isCorrect":true},{"text":"238","isCorrect":false},{"text":"230","isCorrect":false}]'::jsonb,
 null, 'The Rajya Sabha has a maximum strength of 250 members as per the Constitution.'),
('SSC Stenographer', 'General Awareness', 'Indian Polity and Geography', 'easy', 'mcq',
 'Which is the largest state in India by area?',
 '[{"text":"Madhya Pradesh","isCorrect":false},{"text":"Rajasthan","isCorrect":true},{"text":"Maharashtra","isCorrect":false},{"text":"Uttar Pradesh","isCorrect":false}]'::jsonb,
 null, 'Rajasthan is the largest Indian state by area.'),
('SSC Stenographer', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'The Right to Education is enshrined in which Article of the Indian Constitution?',
 '[{"text":"Article 21A","isCorrect":true},{"text":"Article 19","isCorrect":false},{"text":"Article 32","isCorrect":false},{"text":"Article 14","isCorrect":false}]'::jsonb,
 null, 'Article 21A guarantees the Right to Education for children aged 6 to 14 years.'),
('SSC Stenographer', 'General Awareness', 'Indian Polity and Geography', 'medium', 'mcq',
 'Which river is known as the "Sorrow of Bihar"?',
 '[{"text":"Ganga","isCorrect":false},{"text":"Kosi","isCorrect":true},{"text":"Yamuna","isCorrect":false},{"text":"Son","isCorrect":false}]'::jsonb,
 null, 'The Kosi river is known as the "Sorrow of Bihar" due to its frequent, devastating floods.'),

-- General Awareness: General Science
('SSC Stenographer', 'General Awareness', 'General Science', 'easy', 'mcq',
 'Which blood group is known as the universal donor?',
 '[{"text":"A","isCorrect":false},{"text":"B","isCorrect":false},{"text":"AB","isCorrect":false},{"text":"O negative","isCorrect":true}]'::jsonb,
 null, 'O negative blood can be given to patients of any blood group, making it the universal donor.'),
('SSC Stenographer', 'General Awareness', 'General Science', 'easy', 'mcq',
 'What is the powerhouse of the cell called?',
 '[{"text":"Nucleus","isCorrect":false},{"text":"Mitochondria","isCorrect":true},{"text":"Ribosome","isCorrect":false},{"text":"Golgi body","isCorrect":false}]'::jsonb,
 null, 'Mitochondria generate the cell''s energy (ATP), earning them the name "powerhouse of the cell".'),
('SSC Stenographer', 'General Awareness', 'General Science', 'medium', 'mcq',
 'Which part of the human body is primarily affected by arthritis?',
 '[{"text":"Lungs","isCorrect":false},{"text":"Joints","isCorrect":true},{"text":"Heart","isCorrect":false},{"text":"Kidney","isCorrect":false}]'::jsonb,
 null, 'Arthritis is a condition that causes inflammation and pain in the joints.'),
('SSC Stenographer', 'General Awareness', 'General Science', 'medium', 'mcq',
 'The study of heredity and genetic variation is called:',
 '[{"text":"Ecology","isCorrect":false},{"text":"Genetics","isCorrect":true},{"text":"Botany","isCorrect":false},{"text":"Zoology","isCorrect":false}]'::jsonb,
 null, 'Genetics is the branch of biology that studies heredity and variation in organisms.'),

-- General Awareness: Current Affairs and Static GK
('SSC Stenographer', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'Which is the national flower of India?',
 '[{"text":"Rose","isCorrect":false},{"text":"Lotus","isCorrect":true},{"text":"Sunflower","isCorrect":false},{"text":"Marigold","isCorrect":false}]'::jsonb,
 null, 'The Lotus is the national flower of India.'),
('SSC Stenographer', 'General Awareness', 'Current Affairs and Static GK', 'easy', 'mcq',
 'The Rajiv Gandhi Khel Ratna Award is given in which field?',
 '[{"text":"Literature","isCorrect":false},{"text":"Sports","isCorrect":true},{"text":"Cinema","isCorrect":false},{"text":"Science","isCorrect":false}]'::jsonb,
 null, 'The Rajiv Gandhi Khel Ratna (now Major Dhyan Chand Khel Ratna) is India''s highest sporting honor.'),
('SSC Stenographer', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 'Which Indian city hosted the G20 Summit in 2023?',
 '[{"text":"Mumbai","isCorrect":false},{"text":"New Delhi","isCorrect":true},{"text":"Bengaluru","isCorrect":false},{"text":"Chennai","isCorrect":false}]'::jsonb,
 null, 'New Delhi hosted the G20 Summit in September 2023.'),
('SSC Stenographer', 'General Awareness', 'Current Affairs and Static GK', 'medium', 'mcq',
 '"Beti Bachao Beti Padhao" is a scheme aimed at:',
 '[{"text":"Girl child welfare and education","isCorrect":true},{"text":"Farmer welfare","isCorrect":false},{"text":"Digital literacy","isCorrect":false},{"text":"Rural employment","isCorrect":false}]'::jsonb,
 null, '"Beti Bachao Beti Padhao" is a government scheme focused on the welfare and education of the girl child.'),

-- English Language and Comprehension: Grammar and Error Spotting
('SSC Stenographer', 'English Language and Comprehension', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Choose the correct sentence.',
 '[{"text":"She don''t like coffee.","isCorrect":false},{"text":"She doesn''t like coffee.","isCorrect":true},{"text":"She not like coffee.","isCorrect":false},{"text":"She isn''t like coffee.","isCorrect":false}]'::jsonb,
 null, 'With a third-person singular subject, the correct negative form uses "doesn''t".'),
('SSC Stenographer', 'English Language and Comprehension', 'Grammar and Error Spotting', 'easy', 'mcq',
 'Fill in the blank: "They ___ playing cricket now."',
 '[{"text":"is","isCorrect":false},{"text":"am","isCorrect":false},{"text":"are","isCorrect":true},{"text":"be","isCorrect":false}]'::jsonb,
 null, 'The plural subject "They" takes the verb "are".'),
('SSC Stenographer', 'English Language and Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Identify the error: "Each of the students have submitted their assignment."',
 '[{"text":"Each","isCorrect":false},{"text":"have","isCorrect":true},{"text":"their","isCorrect":false},{"text":"No error","isCorrect":false}]'::jsonb,
 null, '"Each" is singular, so the verb should be "has", not "have".'),
('SSC Stenographer', 'English Language and Comprehension', 'Grammar and Error Spotting', 'medium', 'mcq',
 'Choose the correct sentence.',
 '[{"text":"He is one of the best player in the team.","isCorrect":false},{"text":"He is one of the best players in the team.","isCorrect":true},{"text":"He is one of best player.","isCorrect":false},{"text":"He is the one best players.","isCorrect":false}]'::jsonb,
 null, 'The construction "one of the best ___" requires a plural noun: "players".'),

-- English Language and Comprehension: Vocabulary (Synonyms, Antonyms, Spelling)
('SSC Stenographer', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the synonym of "Honest".',
 '[{"text":"Dishonest","isCorrect":false},{"text":"Truthful","isCorrect":true},{"text":"Sly","isCorrect":false},{"text":"Deceitful","isCorrect":false}]'::jsonb,
 null, '"Truthful" means telling the truth, making it a synonym of "Honest".'),
('SSC Stenographer', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'easy', 'mcq',
 'Choose the antonym of "Generous".',
 '[{"text":"Kind","isCorrect":false},{"text":"Stingy","isCorrect":true},{"text":"Giving","isCorrect":false},{"text":"Charitable","isCorrect":false}]'::jsonb,
 null, '"Stingy" means unwilling to give, the opposite of "Generous".'),
('SSC Stenographer', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the correctly spelled word.',
 '[{"text":"Occassion","isCorrect":false},{"text":"Occasion","isCorrect":true},{"text":"Ocassion","isCorrect":false},{"text":"Ocasion","isCorrect":false}]'::jsonb,
 null, '"Occasion" is the correct spelling, with one "c" and one "s".'),
('SSC Stenographer', 'English Language and Comprehension', 'Vocabulary (Synonyms, Antonyms, Spelling)', 'medium', 'mcq',
 'Choose the synonym of "Meticulous".',
 '[{"text":"Careless","isCorrect":false},{"text":"Careful","isCorrect":true},{"text":"Hasty","isCorrect":false},{"text":"Sloppy","isCorrect":false}]'::jsonb,
 null, '"Careful" means showing great attention to detail, making it a synonym of "Meticulous".'),

-- English Language and Comprehension: Cloze Test and Fill in the Blanks
('SSC Stenographer', 'English Language and Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "She is afraid ___ dogs."',
 '[{"text":"of","isCorrect":true},{"text":"from","isCorrect":false},{"text":"with","isCorrect":false},{"text":"at","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "afraid of" something.'),
('SSC Stenographer', 'English Language and Comprehension', 'Cloze Test and Fill in the Blanks', 'easy', 'mcq',
 'Fill in the blank: "He succeeded ___ passing the exam."',
 '[{"text":"at","isCorrect":false},{"text":"in","isCorrect":true},{"text":"on","isCorrect":false},{"text":"for","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "succeed in" doing something.'),
('SSC Stenographer', 'English Language and Comprehension', 'Cloze Test and Fill in the Blanks', 'medium', 'mcq',
 'Fill in the blank: "The committee consists ___ five members."',
 '[{"text":"in","isCorrect":false},{"text":"of","isCorrect":true},{"text":"with","isCorrect":false},{"text":"for","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic preposition is "consists of" something.'),
('SSC Stenographer', 'English Language and Comprehension', 'Cloze Test and Fill in the Blanks', 'medium', 'mcq',
 'Fill in the blank: "I am looking forward ___ meeting you."',
 '[{"text":"to","isCorrect":true},{"text":"for","isCorrect":false},{"text":"at","isCorrect":false},{"text":"with","isCorrect":false}]'::jsonb,
 null, 'The correct idiomatic phrase is "looking forward to" something.'),

-- English Language and Comprehension: Reading Comprehension
('SSC Stenographer', 'English Language and Comprehension', 'Reading Comprehension', 'easy', 'mcq',
 'Choose the word closest in meaning to "diligent" as used in a passage praising a student.',
 '[{"text":"Lazy","isCorrect":false},{"text":"Hardworking","isCorrect":true},{"text":"Careless","isCorrect":false},{"text":"Slow","isCorrect":false}]'::jsonb,
 null, '"Diligent" means showing care and effort, closest in meaning to "Hardworking".'),
('SSC Stenographer', 'English Language and Comprehension', 'Reading Comprehension', 'medium', 'mcq',
 'What does the saying "Practice makes a man perfect" mean?',
 '[{"text":"Perfection requires constant practice","isCorrect":true},{"text":"Men are naturally perfect","isCorrect":false},{"text":"Practice is not necessary","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'This saying means that repeated practice leads to skill and eventual perfection.'),
('SSC Stenographer', 'English Language and Comprehension', 'Reading Comprehension', 'medium', 'mcq',
 'Choose the grammatically correct sentence.',
 '[{"text":"Neither of them are right.","isCorrect":false},{"text":"Neither of them is right.","isCorrect":true},{"text":"Neither of them be right.","isCorrect":false},{"text":"Neither of them right.","isCorrect":false}]'::jsonb,
 null, '"Neither" is singular, so it takes the singular verb "is".'),
('SSC Stenographer', 'English Language and Comprehension', 'Reading Comprehension', 'hard', 'mcq',
 'What does the saying "Every cloud has a silver lining" mean?',
 '[{"text":"Clouds contain silver","isCorrect":false},{"text":"Every difficulty has some positive aspect","isCorrect":true},{"text":"Silver is found in clouds","isCorrect":false},{"text":"None of these","isCorrect":false}]'::jsonb,
 null, 'This saying means that even the worst situations have some positive or hopeful aspect.'),

-- English Language and Comprehension: Sentence Improvement and Rearrangement
('SSC Stenographer', 'English Language and Comprehension', 'Sentence Improvement and Rearrangement', 'easy', 'mcq',
 'Improve the sentence: "He is senior than me."',
 '[{"text":"He is more senior than me.","isCorrect":false},{"text":"He is senior to me.","isCorrect":true},{"text":"He is senior from me.","isCorrect":false},{"text":"No improvement needed.","isCorrect":false}]'::jsonb,
 null, 'The correct comparative form is "senior to", not "senior than".'),
('SSC Stenographer', 'English Language and Comprehension', 'Sentence Improvement and Rearrangement', 'medium', 'mcq',
 'Improve the sentence: "Neither he nor his friends was present."',
 '[{"text":"was present","isCorrect":false},{"text":"were present","isCorrect":true},{"text":"is present","isCorrect":false},{"text":"No improvement needed.","isCorrect":false}]'::jsonb,
 null, 'With "neither...nor", the verb agrees with the nearer subject, "friends" (plural), so "were present" is correct.'),
('SSC Stenographer', 'English Language and Comprehension', 'Sentence Improvement and Rearrangement', 'medium', 'mcq',
 'Rearrange the words to form a correct question: "will / you / come / tomorrow"',
 '[{"text":"You will come tomorrow?","isCorrect":false},{"text":"Will you come tomorrow?","isCorrect":true},{"text":"Come will you tomorrow?","isCorrect":false},{"text":"Tomorrow will you come?","isCorrect":false}]'::jsonb,
 null, 'A yes/no question in English begins with the auxiliary verb: "Will you come tomorrow?"'),
('SSC Stenographer', 'English Language and Comprehension', 'Sentence Improvement and Rearrangement', 'hard', 'mcq',
 'Improve the sentence: "The number of students are increasing."',
 '[{"text":"is increasing","isCorrect":true},{"text":"are increase","isCorrect":false},{"text":"have increased","isCorrect":false},{"text":"No improvement needed.","isCorrect":false}]'::jsonb,
 null, '"The number of" takes a singular verb, so the correct form is "is increasing".'),

-- English Language and Comprehension: One-Word Substitution
('SSC Stenographer', 'English Language and Comprehension', 'One-Word Substitution', 'easy', 'mcq',
 'A person who studies birds is called a(n):',
 '[{"text":"Botanist","isCorrect":false},{"text":"Ornithologist","isCorrect":true},{"text":"Zoologist","isCorrect":false},{"text":"Entomologist","isCorrect":false}]'::jsonb,
 null, 'An ornithologist is a person who studies birds specifically.'),
('SSC Stenographer', 'English Language and Comprehension', 'One-Word Substitution', 'easy', 'mcq',
 'A place where books are kept for reading or borrowing is called a:',
 '[{"text":"Library","isCorrect":true},{"text":"Museum","isCorrect":false},{"text":"Gallery","isCorrect":false},{"text":"Archive","isCorrect":false}]'::jsonb,
 null, 'A library is a place where books are collected and kept for reading or borrowing.'),
('SSC Stenographer', 'English Language and Comprehension', 'One-Word Substitution', 'medium', 'mcq',
 'A person who cannot read or write is called:',
 '[{"text":"Illiterate","isCorrect":true},{"text":"Illegal","isCorrect":false},{"text":"Immoral","isCorrect":false},{"text":"Impolite","isCorrect":false}]'::jsonb,
 null, '"Illiterate" describes someone who cannot read or write.'),
('SSC Stenographer', 'English Language and Comprehension', 'One-Word Substitution', 'medium', 'mcq',
 'A person who is new to a job or activity is called a(n):',
 '[{"text":"Veteran","isCorrect":false},{"text":"Novice","isCorrect":true},{"text":"Expert","isCorrect":false},{"text":"Master","isCorrect":false}]'::jsonb,
 null, 'A "novice" is a person who is new to and inexperienced in a job, skill, or activity.'),

-- English Language and Comprehension: Idioms and Phrases
('SSC Stenographer', 'English Language and Comprehension', 'Idioms and Phrases', 'easy', 'mcq',
 'What does the idiom "to break the ice" mean?',
 '[{"text":"To start a conversation","isCorrect":true},{"text":"To break something literally","isCorrect":false},{"text":"To end a friendship","isCorrect":false},{"text":"To feel cold","isCorrect":false}]'::jsonb,
 null, '"To break the ice" means to initiate conversation or ease tension in a social setting.'),
('SSC Stenographer', 'English Language and Comprehension', 'Idioms and Phrases', 'easy', 'mcq',
 'What does the idiom "to beat around the bush" mean?',
 '[{"text":"To be direct","isCorrect":false},{"text":"To avoid the main point","isCorrect":true},{"text":"To hit a bush","isCorrect":false},{"text":"To go for a walk","isCorrect":false}]'::jsonb,
 null, '"To beat around the bush" means to avoid talking about the main point directly.'),
('SSC Stenographer', 'English Language and Comprehension', 'Idioms and Phrases', 'medium', 'mcq',
 'What does the idiom "once in a blue moon" mean?',
 '[{"text":"Every month","isCorrect":false},{"text":"Very rarely","isCorrect":true},{"text":"Every night","isCorrect":false},{"text":"Frequently","isCorrect":false}]'::jsonb,
 null, '"Once in a blue moon" means something that happens very rarely.'),
('SSC Stenographer', 'English Language and Comprehension', 'Idioms and Phrases', 'medium', 'mcq',
 'What does the idiom "to burn the midnight oil" mean?',
 '[{"text":"To waste oil","isCorrect":false},{"text":"To work late into the night","isCorrect":true},{"text":"To light a lamp","isCorrect":false},{"text":"To sleep early","isCorrect":false}]'::jsonb,
 null, '"To burn the midnight oil" means to work or study late into the night.'),

-- English Language and Comprehension: Active-Passive and Direct-Indirect Speech
('SSC Stenographer', 'English Language and Comprehension', 'Active-Passive and Direct-Indirect Speech', 'easy', 'mcq',
 'Change to passive voice: "The teacher teaches the students."',
 '[{"text":"The students are taught by the teacher.","isCorrect":true},{"text":"The students taught the teacher.","isCorrect":false},{"text":"The students were taught by the teacher.","isCorrect":false},{"text":"The teacher is taught by students.","isCorrect":false}]'::jsonb,
 null, 'The present tense active "teaches" becomes "are taught" in the passive voice.'),
('SSC Stenographer', 'English Language and Comprehension', 'Active-Passive and Direct-Indirect Speech', 'medium', 'mcq',
 'Change to indirect speech: He said, "I am going home."',
 '[{"text":"He said that he is going home.","isCorrect":false},{"text":"He said that he was going home.","isCorrect":true},{"text":"He said that I am going home.","isCorrect":false},{"text":"He said that he goes home.","isCorrect":false}]'::jsonb,
 null, 'In indirect speech, the present continuous "am going" shifts back to the past continuous "was going".'),
('SSC Stenographer', 'English Language and Comprehension', 'Active-Passive and Direct-Indirect Speech', 'medium', 'mcq',
 'Change to passive voice: "She wrote a letter."',
 '[{"text":"A letter is written by her.","isCorrect":false},{"text":"A letter was written by her.","isCorrect":true},{"text":"A letter has written by her.","isCorrect":false},{"text":"A letter written by her.","isCorrect":false}]'::jsonb,
 null, 'The simple past active "wrote" becomes "was written" in the passive voice.'),
('SSC Stenographer', 'English Language and Comprehension', 'Active-Passive and Direct-Indirect Speech', 'hard', 'mcq',
 'Change to indirect speech: She said, "Please help me."',
 '[{"text":"She requested to help her.","isCorrect":false},{"text":"She said to help her.","isCorrect":false},{"text":"She requested that I help her.","isCorrect":false},{"text":"She requested him to help her.","isCorrect":true}]'::jsonb,
 null, 'A polite request in direct speech is reported using "requested" followed by the object and infinitive: "requested him to help her".');
