-- supabase/sql/exam_question_bank_class5_set1.sql
--
-- First curated question-bank batch for 'Class 5' (see exam_patterns_class5.sql for the exam's
-- structure). Same exam_question_bank table/schema as the other sets -- no migration needed.
--
-- Every row here is format='mcq' with a single isCorrect:true option, matching Class 5's MCQ-only,
-- no-negative-marking pattern. 9 chapters (3 per subject x 3 subjects) each get 4 questions,
-- easy/medium with one hard per chapter, reflecting the larger medium/hard share in
-- exam_patterns_class5.sql. Pitched one notch above Class 4 (see
-- exam_question_bank_class4_set1.sql) -- active-passive voice, decimals/percentages/area, and
-- ecosystems/geography/government.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_class5.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- English: Articles, Prepositions and Punctuation
('Class 5', 'English', 'Articles, Prepositions and Punctuation', 'easy', 'mcq',
 'Choose the correct article: "She saw ___ elephant at the zoo."',
 '[{"text":"a","isCorrect":false},{"text":"an","isCorrect":true},{"text":"the","isCorrect":false},{"text":"no article needed","isCorrect":false}]'::jsonb,
 null, '''An'' is used before words that begin with a vowel sound, like ''elephant''.'),
('Class 5', 'English', 'Articles, Prepositions and Punctuation', 'easy', 'mcq',
 'Choose the correct preposition: "The book is ___ the table."',
 '[{"text":"on","isCorrect":true},{"text":"in","isCorrect":false},{"text":"at","isCorrect":false},{"text":"by","isCorrect":false}]'::jsonb,
 null, '''On'' correctly shows that the book is placed on top of the table.'),
('Class 5', 'English', 'Articles, Prepositions and Punctuation', 'medium', 'mcq',
 'Which punctuation mark is used at the end of a question?',
 '[{"text":"Full stop","isCorrect":false},{"text":"Question mark","isCorrect":true},{"text":"Exclamation mark","isCorrect":false},{"text":"Comma","isCorrect":false}]'::jsonb,
 null, 'A question mark (?) is used at the end of a sentence that asks something.'),
('Class 5', 'English', 'Articles, Prepositions and Punctuation', 'hard', 'mcq',
 'Choose the correctly punctuated sentence.',
 '[{"text":"Ravi said, I am going home.","isCorrect":false},{"text":"Ravi said, ''I am going home.''","isCorrect":true},{"text":"Ravi said ''I am going home''","isCorrect":false},{"text":"Ravi said. I am going home.","isCorrect":false}]'::jsonb,
 null, 'Direct speech needs quotation marks around the exact words spoken, with a comma before them.'),

-- English: Active-Passive Voice and Direct-Indirect Speech
('Class 5', 'English', 'Active-Passive Voice and Direct-Indirect Speech', 'easy', 'mcq',
 'Choose the passive voice of: "The boy kicks the ball."',
 '[{"text":"The ball is kicked by the boy.","isCorrect":true},{"text":"The ball kicks the boy.","isCorrect":false},{"text":"The boy is kicked by the ball.","isCorrect":false},{"text":"The ball was kicked by the boy.","isCorrect":false}]'::jsonb,
 null, 'In the passive voice, the object of the active sentence (''the ball'') becomes the subject: ''The ball is kicked by the boy.''.'),
('Class 5', 'English', 'Active-Passive Voice and Direct-Indirect Speech', 'medium', 'mcq',
 'Choose the passive voice of: "She wrote a letter."',
 '[{"text":"A letter is written by her.","isCorrect":false},{"text":"A letter was written by her.","isCorrect":true},{"text":"A letter has written by her.","isCorrect":false},{"text":"A letter writes by her.","isCorrect":false}]'::jsonb,
 null, 'The past tense active ''wrote'' becomes ''was written'' in the passive voice.'),
('Class 5', 'English', 'Active-Passive Voice and Direct-Indirect Speech', 'medium', 'mcq',
 'Convert to indirect speech: Riya said, "I am happy."',
 '[{"text":"Riya said that she is happy.","isCorrect":false},{"text":"Riya said that she was happy.","isCorrect":true},{"text":"Riya said that I am happy.","isCorrect":false},{"text":"Riya says that she was happy.","isCorrect":false}]'::jsonb,
 null, 'In indirect speech, the pronoun changes to ''she'' and the present tense ''am'' shifts back to the past tense ''was''.'),
('Class 5', 'English', 'Active-Passive Voice and Direct-Indirect Speech', 'hard', 'mcq',
 'Choose the passive voice of: "They are building a bridge."',
 '[{"text":"A bridge is being built by them.","isCorrect":true},{"text":"A bridge was built by them.","isCorrect":false},{"text":"A bridge builds them.","isCorrect":false},{"text":"A bridge is built by them.","isCorrect":false}]'::jsonb,
 null, 'The present continuous active ''are building'' becomes ''is being built'' in the passive voice.'),

-- English: Reading Comprehension and Vocabulary
('Class 5', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'Read: "The astronaut floated in space, marveling at the blue planet below." What did the astronaut see below?',
 '[{"text":"The moon","isCorrect":false},{"text":"The blue planet","isCorrect":true},{"text":"A star","isCorrect":false},{"text":"A rocket","isCorrect":false}]'::jsonb,
 null, 'The passage says the astronaut marveled at the blue planet below.'),
('Class 5', 'English', 'Reading Comprehension and Vocabulary', 'easy', 'mcq',
 'A word that means the same as ''courageous'' is:',
 '[{"text":"Timid","isCorrect":false},{"text":"Brave","isCorrect":true},{"text":"Weak","isCorrect":false},{"text":"Nervous","isCorrect":false}]'::jsonb,
 null, '''Brave'' means the same as ''courageous''.'),
('Class 5', 'English', 'Reading Comprehension and Vocabulary', 'medium', 'mcq',
 'Read: "Although the summit was steep and rocky, the climbers pressed on, determined to reach the top before sunset." What were the climbers determined to do?',
 '[{"text":"Turn back","isCorrect":false},{"text":"Reach the top before sunset","isCorrect":true},{"text":"Rest at the base","isCorrect":false},{"text":"Wait for sunrise","isCorrect":false}]'::jsonb,
 null, 'The passage says the climbers pressed on, determined to reach the top before sunset.'),
('Class 5', 'English', 'Reading Comprehension and Vocabulary', 'hard', 'mcq',
 'A word that means the opposite of ''ancient'' is:',
 '[{"text":"Old","isCorrect":false},{"text":"Contemporary","isCorrect":true},{"text":"Historic","isCorrect":false},{"text":"Aged","isCorrect":false}]'::jsonb,
 null, '''Contemporary'' means belonging to the present time, the opposite of ''ancient''.'),

-- Mathematics: Large Numbers and Roman Numerals
('Class 5', 'Mathematics', 'Large Numbers and Roman Numerals', 'easy', 'mcq',
 'What number comes just after 9,99,999?',
 '[{"text":"9,99,998","isCorrect":false},{"text":"10,00,000","isCorrect":true},{"text":"10,00,001","isCorrect":false},{"text":"9,00,000","isCorrect":false}]'::jsonb,
 null, 'Counting up from 9,99,999, the next number is 10,00,000 (ten lakh).'),
('Class 5', 'Mathematics', 'Large Numbers and Roman Numerals', 'easy', 'mcq',
 'What is the Roman numeral for 50?',
 '[{"text":"L","isCorrect":true},{"text":"C","isCorrect":false},{"text":"D","isCorrect":false},{"text":"X","isCorrect":false}]'::jsonb,
 null, 'The Roman numeral for 50 is L.'),
('Class 5', 'Mathematics', 'Large Numbers and Roman Numerals', 'medium', 'mcq',
 'In the number 7,45,682, what is the digit in the lakhs place?',
 '[{"text":"4","isCorrect":false},{"text":"7","isCorrect":true},{"text":"5","isCorrect":false},{"text":"6","isCorrect":false}]'::jsonb,
 null, 'In 7,45,682, 7 is in the lakhs place, 4 in the ten-thousands, 5 in the thousands, and so on.'),
('Class 5', 'Mathematics', 'Large Numbers and Roman Numerals', 'hard', 'mcq',
 'What is the Roman numeral for 94?',
 '[{"text":"XCIV","isCorrect":true},{"text":"IC","isCorrect":false},{"text":"XCVI","isCorrect":false},{"text":"LVL","isCorrect":false}]'::jsonb,
 null, '94 = 90 + 4 = XC + IV = XCIV.'),

-- Mathematics: Fractions, Decimals and Percentages
('Class 5', 'Mathematics', 'Fractions, Decimals and Percentages', 'easy', 'mcq',
 'What is 3/4 written as a decimal?',
 '[{"text":"0.34","isCorrect":false},{"text":"0.75","isCorrect":true},{"text":"0.43","isCorrect":false},{"text":"7.5","isCorrect":false}]'::jsonb,
 null, '3/4 = 0.75.'),
('Class 5', 'Mathematics', 'Fractions, Decimals and Percentages', 'easy', 'mcq',
 'What is 50% written as a fraction in its simplest form?',
 '[{"text":"1/2","isCorrect":true},{"text":"1/5","isCorrect":false},{"text":"1/4","isCorrect":false},{"text":"1/50","isCorrect":false}]'::jsonb,
 null, '50% means 50/100, which simplifies to 1/2.'),
('Class 5', 'Mathematics', 'Fractions, Decimals and Percentages', 'medium', 'mcq',
 'Add: 2.5 + 1.75 = ?',
 '[{"text":"4.15","isCorrect":false},{"text":"4.25","isCorrect":true},{"text":"3.25","isCorrect":false},{"text":"4.5","isCorrect":false}]'::jsonb,
 null, '2.5 + 1.75 = 4.25.'),
('Class 5', 'Mathematics', 'Fractions, Decimals and Percentages', 'hard', 'mcq',
 'What is 20% of 350?',
 '[{"text":"60","isCorrect":false},{"text":"70","isCorrect":true},{"text":"80","isCorrect":false},{"text":"75","isCorrect":false}]'::jsonb,
 null, '20% of 350 = (20/100) x 350 = 70.'),

-- Mathematics: Perimeter, Area, Volume and Data Handling
('Class 5', 'Mathematics', 'Perimeter, Area, Volume and Data Handling', 'easy', 'mcq',
 'What is the area of a square with side 6 cm?',
 '[{"text":"24 cm^2","isCorrect":false},{"text":"36 cm^2","isCorrect":true},{"text":"12 cm^2","isCorrect":false},{"text":"30 cm^2","isCorrect":false}]'::jsonb,
 null, 'Area of a square = side x side = 6 x 6 = 36 cm^2.'),
('Class 5', 'Mathematics', 'Perimeter, Area, Volume and Data Handling', 'easy', 'mcq',
 'What is the perimeter of a square with side 9 cm?',
 '[{"text":"18 cm","isCorrect":false},{"text":"27 cm","isCorrect":false},{"text":"36 cm","isCorrect":true},{"text":"81 cm","isCorrect":false}]'::jsonb,
 null, 'Perimeter of a square = 4 x side = 4 x 9 = 36 cm.'),
('Class 5', 'Mathematics', 'Perimeter, Area, Volume and Data Handling', 'medium', 'mcq',
 'A bar graph shows that 40 students like mangoes and 25 like apples. How many more students like mangoes than apples?',
 '[{"text":"10","isCorrect":false},{"text":"15","isCorrect":true},{"text":"20","isCorrect":false},{"text":"25","isCorrect":false}]'::jsonb,
 null, '40 - 25 = 15 more students like mangoes than apples.'),
('Class 5', 'Mathematics', 'Perimeter, Area, Volume and Data Handling', 'hard', 'mcq',
 'What is the volume of a cube with side 4 cm?',
 '[{"text":"16 cm^3","isCorrect":false},{"text":"48 cm^3","isCorrect":false},{"text":"64 cm^3","isCorrect":true},{"text":"12 cm^3","isCorrect":false}]'::jsonb,
 null, 'Volume of a cube = side x side x side = 4 x 4 x 4 = 64 cm^3.'),

-- EVS: Human Body Systems and Health
('Class 5', 'EVS', 'Human Body Systems and Health', 'easy', 'mcq',
 'Which system in our body helps in breathing?',
 '[{"text":"Digestive system","isCorrect":false},{"text":"Respiratory system","isCorrect":true},{"text":"Skeletal system","isCorrect":false},{"text":"Nervous system","isCorrect":false}]'::jsonb,
 null, 'The respiratory system helps us take in oxygen and release carbon dioxide.'),
('Class 5', 'EVS', 'Human Body Systems and Health', 'easy', 'mcq',
 'Which system in our body is made up of bones?',
 '[{"text":"Skeletal system","isCorrect":true},{"text":"Circulatory system","isCorrect":false},{"text":"Digestive system","isCorrect":false},{"text":"Muscular system","isCorrect":false}]'::jsonb,
 null, 'The skeletal system is made up of bones and gives the body its shape and support.'),
('Class 5', 'EVS', 'Human Body Systems and Health', 'medium', 'mcq',
 'Which organ acts as the control center of the nervous system?',
 '[{"text":"Heart","isCorrect":false},{"text":"Brain","isCorrect":true},{"text":"Liver","isCorrect":false},{"text":"Kidney","isCorrect":false}]'::jsonb,
 null, 'The brain is the control center of the nervous system, directing the body''s actions.'),
('Class 5', 'EVS', 'Human Body Systems and Health', 'hard', 'mcq',
 'Which system in our body is responsible for filtering waste from the blood?',
 '[{"text":"Excretory system","isCorrect":true},{"text":"Respiratory system","isCorrect":false},{"text":"Skeletal system","isCorrect":false},{"text":"Muscular system","isCorrect":false}]'::jsonb,
 null, 'The excretory system, including the kidneys, filters waste products from the blood.'),

-- EVS: Ecosystems, Water Cycle and Environment
('Class 5', 'EVS', 'Ecosystems, Water Cycle and Environment', 'easy', 'mcq',
 'The process by which water vapor turns into water droplets is called:',
 '[{"text":"Evaporation","isCorrect":false},{"text":"Condensation","isCorrect":true},{"text":"Precipitation","isCorrect":false},{"text":"Sublimation","isCorrect":false}]'::jsonb,
 null, 'Condensation is the process by which water vapor cools and turns into water droplets.'),
('Class 5', 'EVS', 'Ecosystems, Water Cycle and Environment', 'easy', 'mcq',
 'Plants that make their own food using sunlight are called:',
 '[{"text":"Consumers","isCorrect":false},{"text":"Producers","isCorrect":true},{"text":"Decomposers","isCorrect":false},{"text":"Predators","isCorrect":false}]'::jsonb,
 null, 'Plants make their own food using sunlight and are called producers.'),
('Class 5', 'EVS', 'Ecosystems, Water Cycle and Environment', 'medium', 'mcq',
 'Organisms that break down dead plants and animals into simpler substances are called:',
 '[{"text":"Producers","isCorrect":false},{"text":"Consumers","isCorrect":false},{"text":"Decomposers","isCorrect":true},{"text":"Herbivores","isCorrect":false}]'::jsonb,
 null, 'Decomposers, like fungi and bacteria, break down dead organisms into simpler substances.'),
('Class 5', 'EVS', 'Ecosystems, Water Cycle and Environment', 'hard', 'mcq',
 'The process by which liquid water changes into water vapor due to heat is called:',
 '[{"text":"Condensation","isCorrect":false},{"text":"Evaporation","isCorrect":true},{"text":"Precipitation","isCorrect":false},{"text":"Collection","isCorrect":false}]'::jsonb,
 null, 'Evaporation is the process by which liquid water changes into water vapor due to heat from the sun.'),

-- EVS: Indian Geography, Government and Freedom Struggle
('Class 5', 'EVS', 'Indian Geography, Government and Freedom Struggle', 'easy', 'mcq',
 'Which mountain range separates India from the rest of Asia in the north?',
 '[{"text":"Aravalli","isCorrect":false},{"text":"Himalayas","isCorrect":true},{"text":"Western Ghats","isCorrect":false},{"text":"Vindhya","isCorrect":false}]'::jsonb,
 null, 'The Himalayas form India''s northern mountain boundary.'),
('Class 5', 'EVS', 'Indian Geography, Government and Freedom Struggle', 'easy', 'mcq',
 'Who is known as the "Father of the Nation" in India?',
 '[{"text":"Jawaharlal Nehru","isCorrect":false},{"text":"Mahatma Gandhi","isCorrect":true},{"text":"Sardar Patel","isCorrect":false},{"text":"Subhas Chandra Bose","isCorrect":false}]'::jsonb,
 null, 'Mahatma Gandhi is known as the "Father of the Nation" in India.'),
('Class 5', 'EVS', 'Indian Geography, Government and Freedom Struggle', 'medium', 'mcq',
 'India got independence from British rule in which year?',
 '[{"text":"1942","isCorrect":false},{"text":"1947","isCorrect":true},{"text":"1950","isCorrect":false},{"text":"1935","isCorrect":false}]'::jsonb,
 null, 'India gained independence from British rule on 15 August 1947.'),
('Class 5', 'EVS', 'Indian Geography, Government and Freedom Struggle', 'hard', 'mcq',
 'Who was the first Prime Minister of independent India?',
 '[{"text":"Mahatma Gandhi","isCorrect":false},{"text":"Jawaharlal Nehru","isCorrect":true},{"text":"Sardar Patel","isCorrect":false},{"text":"Dr. Rajendra Prasad","isCorrect":false}]'::jsonb,
 null, 'Jawaharlal Nehru became the first Prime Minister of independent India in 1947.');
