-- supabase/sql/exam_question_bank_neet_ug_set2.sql
--
-- Second curated question-bank batch for 'NEET UG' (see exam_patterns_neet_ug.sql for the exam's
-- structure, and exam_question_bank_neet_ug_set1.sql for the first batch -- same table/schema, no
-- migration needed). All-new questions, no overlap with Set 1.
--
-- Same format as Set 1: every row is format='mcq' with a single isCorrect:true option, matching
-- NEET UG's 100% single-best-response format. 16 chapters (4 each across Physics, Chemistry,
-- Botany, Zoology) each get 4 questions.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_ug.sql and
-- exam_question_bank_neet_ug_set1.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'The SI unit of momentum is:',
 '[{"text":"kg m/s","isCorrect":true},{"text":"kg m/s^2","isCorrect":false},{"text":"N/s","isCorrect":false},{"text":"kg m^2/s","isCorrect":false}]'::jsonb,
 null, 'Momentum is the product of mass and velocity, giving it the SI unit kg m/s.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'A ball thrown vertically upward (ignoring air resistance) returns to the thrower''s hand with the same speed it was thrown. This is an example of:',
 '[{"text":"Conservation of momentum only","isCorrect":false},{"text":"Conservation of mechanical energy","isCorrect":true},{"text":"Newton''s third law","isCorrect":false},{"text":"Conservation of angular momentum","isCorrect":false}]'::jsonb,
 null, 'In the absence of air resistance, gravitational potential energy converts back fully to kinetic energy on the way down, so total mechanical energy is conserved, and speed is restored.'),
('NEET UG', 'Physics', 'Mechanics', 'medium', 'mcq',
 'The moment of inertia of a rigid body about a given axis depends on:',
 '[{"text":"Its mass alone","isCorrect":false},{"text":"Its mass and how that mass is distributed relative to the axis","isCorrect":true},{"text":"Its velocity alone","isCorrect":false},{"text":"Its temperature","isCorrect":false}]'::jsonb,
 null, 'Moment of inertia depends on both the total mass of a body and how that mass is distributed relative to the rotation axis -- mass farther from the axis contributes more.'),
('NEET UG', 'Physics', 'Mechanics', 'easy', 'mcq',
 'Newton''s third law of motion states that:',
 '[{"text":"An object at rest stays at rest unless acted upon by a force","isCorrect":false},{"text":"For every action, there is an equal and opposite reaction","isCorrect":true},{"text":"Force equals mass times acceleration","isCorrect":false},{"text":"Energy can neither be created nor destroyed","isCorrect":false}]'::jsonb,
 null, 'Newton''s third law states that for every action force exerted by one body on another, there is an equal and opposite reaction force exerted by the second body on the first.'),

-- Physics: Electrodynamics
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The electrostatic force between two like charges is:',
 '[{"text":"Attractive","isCorrect":false},{"text":"Repulsive","isCorrect":true},{"text":"Zero","isCorrect":false},{"text":"Dependent on temperature","isCorrect":false}]'::jsonb,
 null, 'Like charges (both positive or both negative) repel each other, while unlike charges attract.'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'A transformer operates based on the principle of:',
 '[{"text":"Self-induction only","isCorrect":false},{"text":"Mutual induction","isCorrect":true},{"text":"Electrostatic induction","isCorrect":false},{"text":"Thermionic emission","isCorrect":false}]'::jsonb,
 null, 'A transformer works on mutual induction -- a changing current in the primary coil induces an EMF in the secondary coil through their shared magnetic flux.'),
('NEET UG', 'Physics', 'Electrodynamics', 'easy', 'mcq',
 'The SI unit of electric charge is the:',
 '[{"text":"Ampere","isCorrect":false},{"text":"Coulomb","isCorrect":true},{"text":"Volt","isCorrect":false},{"text":"Farad","isCorrect":false}]'::jsonb,
 null, 'Electric charge is measured in coulombs (C).'),
('NEET UG', 'Physics', 'Electrodynamics', 'medium', 'mcq',
 'In a series circuit containing multiple resistors, the current through each resistor is:',
 '[{"text":"Different for each resistor","isCorrect":false},{"text":"The same throughout the circuit","isCorrect":true},{"text":"Proportional to each resistor''s resistance","isCorrect":false},{"text":"Zero for all but the first resistor","isCorrect":false}]'::jsonb,
 null, 'In a series circuit, there is only one path for current to flow, so the same current passes through every component.'),

-- Physics: Optics and Wave Phenomena
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'The bending of light waves around obstacles or through narrow openings is called:',
 '[{"text":"Reflection","isCorrect":false},{"text":"Diffraction","isCorrect":true},{"text":"Refraction","isCorrect":false},{"text":"Polarization","isCorrect":false}]'::jsonb,
 null, 'Diffraction refers to the bending of waves around obstacles or through narrow apertures, becoming significant when the opening size is comparable to the wavelength.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'A convex mirror is commonly used as a rear-view/side mirror in vehicles primarily because it:',
 '[{"text":"Forms a magnified image","isCorrect":false},{"text":"Provides a wider field of view","isCorrect":true},{"text":"Forms a real, inverted image","isCorrect":false},{"text":"Has no focal point","isCorrect":false}]'::jsonb,
 null, 'A convex mirror always forms a diminished, upright image and provides a wider field of view than a plane mirror, making it useful for vehicle mirrors despite the reduced image size.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'easy', 'mcq',
 'The speed of light in vacuum is approximately:',
 '[{"text":"3 x 10^5 m/s","isCorrect":false},{"text":"3 x 10^8 m/s","isCorrect":true},{"text":"3 x 10^10 m/s","isCorrect":false},{"text":"3 x 10^6 m/s","isCorrect":false}]'::jsonb,
 null, 'The speed of light in a vacuum is approximately 3 x 10^8 meters per second, a fundamental physical constant.'),
('NEET UG', 'Physics', 'Optics and Wave Phenomena', 'medium', 'mcq',
 'Sound waves are an example of which type of wave?',
 '[{"text":"Transverse waves","isCorrect":false},{"text":"Longitudinal waves","isCorrect":true},{"text":"Electromagnetic waves","isCorrect":false},{"text":"Standing waves only","isCorrect":false}]'::jsonb,
 null, 'Sound waves are longitudinal waves, where the particles of the medium vibrate parallel to the direction of wave propagation.'),

-- Physics: Modern Physics and Semiconductor Devices
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'easy', 'mcq',
 'The nucleus of an atom is composed of:',
 '[{"text":"Protons and electrons","isCorrect":false},{"text":"Protons and neutrons","isCorrect":true},{"text":"Electrons and neutrons","isCorrect":false},{"text":"Protons only","isCorrect":false}]'::jsonb,
 null, 'The atomic nucleus consists of protons and neutrons (collectively called nucleons), while electrons orbit around the nucleus.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'Which particle is emitted during beta-minus decay of a radioactive nucleus?',
 '[{"text":"Alpha particle","isCorrect":false},{"text":"Electron (beta particle)","isCorrect":true},{"text":"Proton","isCorrect":false},{"text":"Neutron","isCorrect":false}]'::jsonb,
 null, 'In beta-minus decay, a neutron converts into a proton, emitting an electron (beta particle) and an antineutrino.'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'A p-n junction diode allows current to flow easily when it is:',
 '[{"text":"Forward biased","isCorrect":true},{"text":"Reverse biased","isCorrect":false},{"text":"Unbiased","isCorrect":false},{"text":"Connected to AC only","isCorrect":false}]'::jsonb,
 null, 'Under forward bias, the depletion region narrows and the diode conducts current easily; under reverse bias, it blocks current (except a small leakage current).'),
('NEET UG', 'Physics', 'Modern Physics and Semiconductor Devices', 'medium', 'mcq',
 'The photoelectric effect provides evidence for which nature of light?',
 '[{"text":"Purely wave nature","isCorrect":false},{"text":"Particle nature (photons)","isCorrect":true},{"text":"Purely magnetic nature","isCorrect":false},{"text":"Purely electric nature","isCorrect":false}]'::jsonb,
 null, 'The photoelectric effect can only be explained by treating light as discrete particles (photons) carrying quantized energy, demonstrating light''s particle nature.'),

-- Chemistry: Physical Chemistry
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The SI-associated unit of molar concentration (molarity) is:',
 '[{"text":"mol/L","isCorrect":true},{"text":"g/L","isCorrect":false},{"text":"mol/kg","isCorrect":false},{"text":"L/mol","isCorrect":false}]'::jsonb,
 null, 'Molarity is defined as moles of solute per liter of solution, giving it the unit mol/L.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'An exothermic reaction is one that:',
 '[{"text":"Absorbs heat from the surroundings","isCorrect":false},{"text":"Releases heat to the surroundings","isCorrect":true},{"text":"Has no heat exchange at all","isCorrect":false},{"text":"Only occurs at high temperature","isCorrect":false}]'::jsonb,
 null, 'An exothermic reaction releases heat energy to its surroundings, typically causing a rise in the surrounding temperature.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'easy', 'mcq',
 'The pH of a strongly acidic solution is typically:',
 '[{"text":"Close to 7","isCorrect":false},{"text":"Less than 7 (close to 0-3)","isCorrect":true},{"text":"Greater than 7","isCorrect":false},{"text":"Exactly 14","isCorrect":false}]'::jsonb,
 null, 'Strongly acidic solutions have a high concentration of H+ ions, giving them a pH well below 7, typically in the 0-3 range.'),
('NEET UG', 'Chemistry', 'Physical Chemistry', 'medium', 'mcq',
 'Catalysts increase the rate of a chemical reaction by:',
 '[{"text":"Increasing the temperature of the reaction","isCorrect":false},{"text":"Lowering the activation energy required","isCorrect":true},{"text":"Increasing the concentration of reactants","isCorrect":false},{"text":"Changing the products formed","isCorrect":false}]'::jsonb,
 null, 'Catalysts provide an alternative reaction pathway with lower activation energy, speeding up the reaction without being consumed themselves.'),

-- Chemistry: Organic Chemistry
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'The characteristic functional group of an alcohol is:',
 '[{"text":"-OH","isCorrect":true},{"text":"-COOH","isCorrect":false},{"text":"-CHO","isCorrect":false},{"text":"-NH2","isCorrect":false}]'::jsonb,
 null, 'Alcohols are characterized by the hydroxyl (-OH) functional group attached to a carbon chain.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'Isomers are compounds that have the same:',
 '[{"text":"Molecular formula but different structures","isCorrect":true},{"text":"Structure but different molecular formulas","isCorrect":false},{"text":"Physical properties only","isCorrect":false},{"text":"Boiling point only","isCorrect":false}]'::jsonb,
 null, 'Isomers share the same molecular formula (same number and type of atoms) but differ in the arrangement of those atoms, giving them distinct structures and often different properties.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'easy', 'mcq',
 'Which of the following is an example of a saturated hydrocarbon?',
 '[{"text":"Ethene","isCorrect":false},{"text":"Methane","isCorrect":true},{"text":"Ethyne","isCorrect":false},{"text":"Benzene","isCorrect":false}]'::jsonb,
 null, 'Methane (CH4), an alkane, contains only single bonds between carbon atoms, making it a saturated hydrocarbon.'),
('NEET UG', 'Chemistry', 'Organic Chemistry', 'medium', 'mcq',
 'The process of converting an alkene to an alkane by addition of hydrogen is called:',
 '[{"text":"Dehydrogenation","isCorrect":false},{"text":"Hydrogenation","isCorrect":true},{"text":"Hydrolysis","isCorrect":false},{"text":"Halogenation","isCorrect":false}]'::jsonb,
 null, 'Hydrogenation is the addition of hydrogen (typically with a catalyst like nickel or palladium) across a carbon-carbon double bond, converting an alkene into a saturated alkane.'),

-- Chemistry: Inorganic Chemistry
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The most abundant gas in Earth''s atmosphere is:',
 '[{"text":"Oxygen","isCorrect":false},{"text":"Nitrogen","isCorrect":true},{"text":"Carbon dioxide","isCorrect":false},{"text":"Argon","isCorrect":false}]'::jsonb,
 null, 'Nitrogen makes up about 78% of Earth''s atmosphere by volume, making it the most abundant atmospheric gas.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'Which of the following is a noble gas?',
 '[{"text":"Chlorine","isCorrect":false},{"text":"Argon","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Oxygen","isCorrect":false}]'::jsonb,
 null, 'Argon is a noble gas, chemically inert due to its complete outer electron shell.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'easy', 'mcq',
 'The valency of oxygen in most of its common compounds is:',
 '[{"text":"1","isCorrect":false},{"text":"2","isCorrect":true},{"text":"3","isCorrect":false},{"text":"4","isCorrect":false}]'::jsonb,
 null, 'Oxygen typically forms 2 bonds in its common compounds, corresponding to a valency of 2.'),
('NEET UG', 'Chemistry', 'Inorganic Chemistry', 'medium', 'mcq',
 'Which acid is commonly known as "oil of vitriol"?',
 '[{"text":"Hydrochloric acid","isCorrect":false},{"text":"Sulfuric acid","isCorrect":true},{"text":"Nitric acid","isCorrect":false},{"text":"Acetic acid","isCorrect":false}]'::jsonb,
 null, 'Sulfuric acid (H2SO4) is historically known as "oil of vitriol" due to its oily appearance when concentrated.'),

-- Chemistry: Biomolecules and Environmental Chemistry
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'easy', 'mcq',
 'Proteins are biological polymers made up of repeating units of:',
 '[{"text":"Glucose","isCorrect":false},{"text":"Amino acids","isCorrect":true},{"text":"Fatty acids","isCorrect":false},{"text":"Nucleotides","isCorrect":false}]'::jsonb,
 null, 'Proteins are polymers formed by linking amino acid monomers through peptide bonds.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'The main structural component of cell membranes is the:',
 '[{"text":"Cellulose layer","isCorrect":false},{"text":"Phospholipid bilayer","isCorrect":true},{"text":"Protein shell only","isCorrect":false},{"text":"Starch layer","isCorrect":false}]'::jsonb,
 null, 'Cell membranes are primarily composed of a phospholipid bilayer, with embedded proteins performing various functions.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'Global warming is primarily attributed to increased atmospheric levels of:',
 '[{"text":"Nitrogen","isCorrect":false},{"text":"Carbon dioxide and other greenhouse gases","isCorrect":true},{"text":"Argon","isCorrect":false},{"text":"Helium","isCorrect":false}]'::jsonb,
 null, 'Increased concentrations of greenhouse gases, especially carbon dioxide from fossil fuel combustion, trap heat in the atmosphere, driving global warming.'),
('NEET UG', 'Chemistry', 'Biomolecules and Environmental Chemistry', 'medium', 'mcq',
 'DDT is a well-known example of a:',
 '[{"text":"Fertilizer","isCorrect":false},{"text":"Pesticide (organochlorine compound)","isCorrect":true},{"text":"Antibiotic","isCorrect":false},{"text":"Vitamin supplement","isCorrect":false}]'::jsonb,
 null, 'DDT (dichlorodiphenyltrichloroethane) is an organochlorine pesticide, notorious for its environmental persistence and bioaccumulation.'),

-- Botany: Plant Physiology
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'The green pigment primarily responsible for capturing light energy during photosynthesis is:',
 '[{"text":"Chlorophyll","isCorrect":true},{"text":"Carotene","isCorrect":false},{"text":"Xanthophyll","isCorrect":false},{"text":"Anthocyanin","isCorrect":false}]'::jsonb,
 null, 'Chlorophyll is the primary pigment responsible for absorbing light energy used in photosynthesis, giving plants their green color.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'Which plant hormone promotes cell elongation and is associated with phototropism?',
 '[{"text":"Auxin","isCorrect":true},{"text":"Cytokinin","isCorrect":false},{"text":"Abscisic acid","isCorrect":false},{"text":"Ethylene","isCorrect":false}]'::jsonb,
 null, 'Auxin promotes cell elongation and its uneven distribution in response to light causes phototropism, the bending of plants toward a light source.'),
('NEET UG', 'Botany', 'Plant Physiology', 'medium', 'mcq',
 'The upward movement of water from roots to leaves through the xylem, driven largely by transpiration, is called:',
 '[{"text":"Guttation","isCorrect":false},{"text":"Transpiration pull (ascent of sap)","isCorrect":true},{"text":"Osmosis alone","isCorrect":false},{"text":"Root pressure alone","isCorrect":false}]'::jsonb,
 null, 'Transpiration pull, generated by water evaporation from leaves creating negative pressure, is the primary mechanism driving the ascent of sap through the xylem.'),
('NEET UG', 'Botany', 'Plant Physiology', 'easy', 'mcq',
 'Which gas is released as a byproduct of photosynthesis?',
 '[{"text":"Carbon dioxide","isCorrect":false},{"text":"Oxygen","isCorrect":true},{"text":"Nitrogen","isCorrect":false},{"text":"Hydrogen","isCorrect":false}]'::jsonb,
 null, 'Photosynthesis splits water molecules, releasing oxygen as a byproduct while using carbon dioxide to produce glucose.'),

-- Botany: Cell Biology and Genetics
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'The basic structural and functional unit of all living organisms is the:',
 '[{"text":"Tissue","isCorrect":false},{"text":"Cell","isCorrect":true},{"text":"Organ","isCorrect":false},{"text":"Organelle","isCorrect":false}]'::jsonb,
 null, 'The cell is universally recognized as the basic structural and functional unit of life.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'Mitosis results in the formation of:',
 '[{"text":"Four genetically distinct daughter cells","isCorrect":false},{"text":"Two genetically identical daughter cells","isCorrect":true},{"text":"One large daughter cell","isCorrect":false},{"text":"Gametes only","isCorrect":false}]'::jsonb,
 null, 'Mitosis produces two daughter cells that are genetically identical to the parent cell and to each other, used for growth and repair.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'easy', 'mcq',
 'A gene is best described as a segment of:',
 '[{"text":"Protein","isCorrect":false},{"text":"DNA","isCorrect":true},{"text":"Carbohydrate","isCorrect":false},{"text":"Lipid","isCorrect":false}]'::jsonb,
 null, 'A gene is a segment of DNA that codes for a specific protein or functional RNA product.'),
('NEET UG', 'Botany', 'Cell Biology and Genetics (Plant/General)', 'medium', 'mcq',
 'The process by which messenger RNA (mRNA) is synthesized from a DNA template is called:',
 '[{"text":"Translation","isCorrect":false},{"text":"Transcription","isCorrect":true},{"text":"Replication","isCorrect":false},{"text":"Mutation","isCorrect":false}]'::jsonb,
 null, 'Transcription is the process by which the enzyme RNA polymerase synthesizes mRNA using a DNA strand as a template.'),

-- Botany: Ecology and Environment
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'A group of individuals of the same species living together in a particular area is called a:',
 '[{"text":"Community","isCorrect":false},{"text":"Population","isCorrect":true},{"text":"Ecosystem","isCorrect":false},{"text":"Biome","isCorrect":false}]'::jsonb,
 null, 'A population refers to a group of interbreeding individuals of the same species living in a specific geographic area.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'A relationship between two species in which one organism benefits while the other is harmed is called:',
 '[{"text":"Mutualism","isCorrect":false},{"text":"Parasitism","isCorrect":true},{"text":"Commensalism","isCorrect":false},{"text":"Amensalism only","isCorrect":false}]'::jsonb,
 null, 'Parasitism describes a relationship where the parasite benefits at the expense of the host, which is harmed.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'medium', 'mcq',
 'Biodiversity hotspots are regions characterized by:',
 '[{"text":"Low species richness and no threats","isCorrect":false},{"text":"High species richness and high endemism, but under significant threat","isCorrect":true},{"text":"Only agricultural land","isCorrect":false},{"text":"Uniform climate throughout the year","isCorrect":false}]'::jsonb,
 null, 'Biodiversity hotspots are regions with exceptionally high levels of species richness and endemism that are also facing significant habitat loss and threats.'),
('NEET UG', 'Botany', 'Ecology and Environment', 'easy', 'mcq',
 'Which layer of the atmosphere protects Earth from harmful ultraviolet radiation?',
 '[{"text":"Troposphere","isCorrect":false},{"text":"Ozone layer (in the stratosphere)","isCorrect":true},{"text":"Mesosphere","isCorrect":false},{"text":"Thermosphere","isCorrect":false}]'::jsonb,
 null, 'The ozone layer, located in the stratosphere, absorbs most of the sun''s harmful ultraviolet radiation.'),

-- Botany: Plant Morphology and Anatomy
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The part of a flower that produces pollen is the:',
 '[{"text":"Stigma","isCorrect":false},{"text":"Anther","isCorrect":true},{"text":"Ovary","isCorrect":false},{"text":"Sepal","isCorrect":false}]'::jsonb,
 null, 'The anther, part of the stamen (the male reproductive organ of a flower), produces pollen grains.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'medium', 'mcq',
 'Which plant tissue is primarily responsible for the transport of organic food (like sugars)?',
 '[{"text":"Xylem","isCorrect":false},{"text":"Phloem","isCorrect":true},{"text":"Cambium","isCorrect":false},{"text":"Epidermis","isCorrect":false}]'::jsonb,
 null, 'Phloem tissue transports organic nutrients, particularly sugars produced during photosynthesis, from source to sink tissues in the plant.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'A leaf with a single, undivided blade is called a:',
 '[{"text":"Compound leaf","isCorrect":false},{"text":"Simple leaf","isCorrect":true},{"text":"Pinnate leaf","isCorrect":false},{"text":"Palmate leaf","isCorrect":false}]'::jsonb,
 null, 'A simple leaf has a single, undivided lamina (blade), unlike a compound leaf, which is divided into multiple leaflets.'),
('NEET UG', 'Botany', 'Plant Morphology and Anatomy', 'easy', 'mcq',
 'The outermost protective layer of a young stem or root is called the:',
 '[{"text":"Cortex","isCorrect":false},{"text":"Epidermis","isCorrect":true},{"text":"Pith","isCorrect":false},{"text":"Endodermis","isCorrect":false}]'::jsonb,
 null, 'The epidermis is the single outermost layer of cells that provides protection to young stems and roots.'),

-- Zoology: Human Physiology
('NEET UG', 'Zoology', 'Human Physiology', 'easy', 'mcq',
 'The largest organ of the human body is the:',
 '[{"text":"Liver","isCorrect":false},{"text":"Skin","isCorrect":true},{"text":"Lungs","isCorrect":false},{"text":"Kidney","isCorrect":false}]'::jsonb,
 null, 'The skin is the largest organ of the human body by surface area and weight, serving as a protective barrier.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which type of blood cells are primarily responsible for fighting infections?',
 '[{"text":"Red blood cells","isCorrect":false},{"text":"White blood cells (leukocytes)","isCorrect":true},{"text":"Platelets","isCorrect":false},{"text":"Plasma cells only","isCorrect":false}]'::jsonb,
 null, 'White blood cells (leukocytes) are the primary immune cells responsible for detecting and fighting infections in the body.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'The enzyme pepsin, which digests proteins, is secreted in the:',
 '[{"text":"Mouth","isCorrect":false},{"text":"Stomach","isCorrect":true},{"text":"Small intestine only","isCorrect":false},{"text":"Liver","isCorrect":false}]'::jsonb,
 null, 'Pepsin is secreted by gastric glands in the stomach, where it digests proteins in the acidic gastric environment.'),
('NEET UG', 'Zoology', 'Human Physiology', 'medium', 'mcq',
 'Which part of a neuron primarily receives incoming signals from other neurons?',
 '[{"text":"Axon","isCorrect":false},{"text":"Dendrites","isCorrect":true},{"text":"Axon terminal","isCorrect":false},{"text":"Myelin sheath","isCorrect":false}]'::jsonb,
 null, 'Dendrites are branch-like extensions of a neuron that receive incoming signals from other neurons at synapses.'),

-- Zoology: Human Reproduction and Reproductive Health
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'easy', 'mcq',
 'The male gonads that produce sperm are called the:',
 '[{"text":"Testes","isCorrect":true},{"text":"Ovaries","isCorrect":false},{"text":"Epididymis","isCorrect":false},{"text":"Prostate","isCorrect":false}]'::jsonb,
 null, 'The testes are the male gonads responsible for producing sperm cells and the hormone testosterone.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'The process of release of a mature ovum from the ovary is called:',
 '[{"text":"Fertilization","isCorrect":false},{"text":"Ovulation","isCorrect":true},{"text":"Menstruation","isCorrect":false},{"text":"Implantation","isCorrect":false}]'::jsonb,
 null, 'Ovulation is the release of a mature ovum (egg) from the ovary, typically occurring midway through the menstrual cycle.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'medium', 'mcq',
 'The placenta primarily functions to:',
 '[{"text":"Store sperm cells","isCorrect":false},{"text":"Facilitate exchange of nutrients, gases, and waste between mother and fetus","isCorrect":true},{"text":"Produce mature ova","isCorrect":false},{"text":"Secrete digestive enzymes","isCorrect":false}]'::jsonb,
 null, 'The placenta is a specialized organ that allows exchange of nutrients, oxygen, and waste products between the mother''s and the developing fetus''s blood supplies.'),
('NEET UG', 'Zoology', 'Human Reproduction and Reproductive Health', 'hard', 'mcq',
 'Amniocentesis is a prenatal technique primarily used for:',
 '[{"text":"Inducing labor","isCorrect":false},{"text":"Diagnosis of genetic or chromosomal disorders in the fetus","isCorrect":true},{"text":"Determining the mother''s blood type","isCorrect":false},{"text":"Treating infertility","isCorrect":false}]'::jsonb,
 null, 'Amniocentesis involves sampling amniotic fluid to test for genetic or chromosomal abnormalities in the developing fetus.'),

-- Zoology: Genetics and Evolution
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'A cross between two heterozygous individuals for a single trait (Aa x Aa) typically produces offspring in a phenotypic ratio of:',
 '[{"text":"1:1","isCorrect":false},{"text":"3:1","isCorrect":true},{"text":"1:2:1","isCorrect":false},{"text":"9:3:3:1","isCorrect":false}]'::jsonb,
 null, 'A monohybrid cross between two heterozygotes (Aa x Aa) produces a 3:1 phenotypic ratio of dominant to recessive traits in the offspring.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'A mutation is best described as:',
 '[{"text":"A temporary change in gene expression","isCorrect":false},{"text":"A sudden, heritable change in the DNA sequence","isCorrect":true},{"text":"A normal process of cell division","isCorrect":false},{"text":"A change in an organism''s environment","isCorrect":false}]'::jsonb,
 null, 'A mutation is a permanent, heritable alteration in the DNA sequence of an organism, which can arise spontaneously or due to external factors.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'medium', 'mcq',
 'According to Darwin''s theory of evolution, the primary driving force of evolutionary change is:',
 '[{"text":"Natural selection","isCorrect":true},{"text":"Use and disuse of organs","isCorrect":false},{"text":"Inheritance of acquired characteristics","isCorrect":false},{"text":"Random mutation alone, without selection","isCorrect":false}]'::jsonb,
 null, 'Darwin proposed that natural selection -- the differential survival and reproduction of individuals with favorable heritable traits -- is the primary driver of evolution.'),
('NEET UG', 'Zoology', 'Genetics and Evolution', 'hard', 'mcq',
 'Homologous organs are organs that have:',
 '[{"text":"Similar structure and origin, indicating common ancestry, though they may serve different functions","isCorrect":true},{"text":"Similar function but different structure and origin","isCorrect":false},{"text":"No evolutionary significance at all","isCorrect":false},{"text":"Identical function and structure in unrelated species","isCorrect":false}]'::jsonb,
 null, 'Homologous organs share a similar underlying structure and evolutionary origin (from a common ancestor), even if they have since evolved to perform different functions, such as a bird''s wing and a human arm.'),

-- Zoology: Biotechnology and its Applications
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Recombinant DNA technology primarily involves:',
 '[{"text":"Combining DNA from different sources to create new genetic combinations","isCorrect":true},{"text":"Destroying DNA in bacteria","isCorrect":false},{"text":"Sequencing an entire genome without modification","isCorrect":false},{"text":"Removing all genes from an organism","isCorrect":false}]'::jsonb,
 null, 'Recombinant DNA technology involves combining DNA segments from different sources (often using restriction enzymes and ligases) to create novel genetic combinations.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Human insulin used to treat diabetes is commercially manufactured using:',
 '[{"text":"Extraction directly from human pancreases only","isCorrect":false},{"text":"Genetically modified bacteria (such as E. coli)","isCorrect":true},{"text":"Chemical synthesis from plant extracts","isCorrect":false},{"text":"Extraction from animal blood only","isCorrect":false}]'::jsonb,
 null, 'Human insulin is produced industrially by inserting the human insulin gene into bacteria (like E. coli), which then express and produce the insulin protein.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Gel electrophoresis is a technique primarily used to:',
 '[{"text":"Amplify DNA fragments","isCorrect":false},{"text":"Separate DNA fragments based on their size","isCorrect":true},{"text":"Sequence proteins","isCorrect":false},{"text":"Destroy bacterial cells","isCorrect":false}]'::jsonb,
 null, 'Gel electrophoresis separates DNA (or protein) fragments by size as they migrate through a gel matrix under an electric field, smaller fragments moving faster.'),
('NEET UG', 'Zoology', 'Biotechnology and its Applications', 'medium', 'mcq',
 'Golden rice is a genetically modified crop that has been enriched with a precursor of which vitamin?',
 '[{"text":"Vitamin A (beta-carotene)","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin D","isCorrect":false},{"text":"Vitamin B12","isCorrect":false}]'::jsonb,
 null, 'Golden rice is genetically engineered to produce beta-carotene, a precursor of Vitamin A, addressing Vitamin A deficiency in populations reliant on rice as a staple food.');
