-- supabase/sql/exam_question_bank_jee_advanced_set1.sql
--
-- First curated question-bank batch for 'JEE Advanced' (see exam_patterns_jee_advanced.sql for
-- the exam's structure). Same table/schema as the JEE Main sets -- no migration needed beyond the
-- base exam_question_bank.sql already being run.
--
-- Unlike the JEE Main sets (mostly single-correct, occasional multi-correct), this leans much more
-- heavily into JEE Advanced's actual signature format: EVERY chapter gets one single-correct MCQ
-- AND one genuine multi-correct "which of the following statement(s) is/are TRUE" MCQ (still
-- format='mcq' with more than one option marked isCorrect -- no schema change, same mechanism as
-- the JEE Main sets), plus a numerical-answer question and a short-answer descriptive one.
-- Difficulty is skewed harder throughout, matching exam_patterns_jee_advanced.sql's tougher
-- easy/medium/hard split.
--
-- Run this once in the Supabase SQL Editor, after exam_question_bank.sql and
-- exam_patterns_jee_advanced.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Physics: Mechanics
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'mcq',
 'A particle moves along a straight line with position $x(t) = t^3 - 6t^2 + 9t$ (meters, $t$ in seconds). Find the times (in seconds) at which the particle is momentarily at rest.',
 '[{"text":"1 and 3","isCorrect":true},{"text":"0 and 3","isCorrect":false},{"text":"1 and 4","isCorrect":false},{"text":"2 and 3","isCorrect":false}]'::jsonb,
 null, 'Velocity v(t) = 3t^2 - 12t + 9 = 0 gives t^2 - 4t + 3 = 0, so t = 1 and t = 3.'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'hard', 'mcq',
 'For the same particle, $x(t)=t^3-6t^2+9t$, over the interval $t \in (0,4)$, which of the following statement(s) is/are TRUE? (A) The particle is at rest at $t=1$. (B) The particle is at rest at $t=3$. (C) The acceleration at $t=2$ is zero. (D) The particle''s speed is maximum at $t=2$.',
 '[{"text":"(A) At rest at t=1","isCorrect":true},{"text":"(B) At rest at t=3","isCorrect":true},{"text":"(C) Acceleration zero at t=2","isCorrect":true},{"text":"(D) Speed is maximum at t=2","isCorrect":false}]'::jsonb,
 null, 'v(t)=0 at t=1 and t=3 (A, B true). Acceleration a(t)=6t-12=0 at t=2 (C true). Since v(t) is an upward parabola in t, t=2 is actually where the SPEED is minimum (|v(2)|=3), not maximum -- the endpoints t=0 and t=4 both give the larger speed of 9 (D false).'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'numerical',
 'For the particle $x(t)=t^3-6t^2+9t$, find the magnitude of the acceleration (in $m/s^2$) at $t=1$ s.',
 null, '6', 'a(t) = 6t - 12. At t=1, a = 6-12 = -6, magnitude 6 m/s^2.'),
('JEE Advanced', 'Physics', 'Mechanics (Kinematics, Laws of Motion, Work-Energy-Power, Rotational Motion, Gravitation)', 'medium', 'descriptive',
 'Explain the physical significance of the points where velocity is zero in this particle''s motion, and what happens to its direction at those points.',
 null, null, 'At t=1 and t=3, velocity is zero, meaning the particle is momentarily at rest -- these are turning points where the particle reverses its direction of motion, with velocity changing sign from positive to negative or vice versa.'),

-- Physics: Electrodynamics
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'mcq',
 'Two point charges $+q$ and $-q$ are separated by distance $d$. Find the electric potential at the midpoint of the line joining them.',
 '[{"text":"0","isCorrect":true},{"text":"2kq/d","isCorrect":false},{"text":"kq/d","isCorrect":false},{"text":"4kq/d","isCorrect":false}]'::jsonb,
 null, 'Potentials from +q and -q at the midpoint are equal in magnitude but opposite in sign, so they cancel, giving a net potential of 0.'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'mcq',
 'A parallel plate capacitor of capacitance $C_0$ is charged to potential $V_0$ and then disconnected from the battery. If the plate separation is now doubled, which of the following statement(s) is/are TRUE? (A) The capacitance becomes $C_0/2$. (B) The charge on the plates remains $C_0 V_0$. (C) The potential difference becomes $2V_0$. (D) The energy stored decreases.',
 '[{"text":"(A) Capacitance becomes C0/2","isCorrect":true},{"text":"(B) Charge remains C0*V0","isCorrect":true},{"text":"(C) Potential difference becomes 2*V0","isCorrect":true},{"text":"(D) Energy stored decreases","isCorrect":false}]'::jsonb,
 null, 'Capacitance is inversely proportional to plate separation, so doubling it halves C (A true). Since the capacitor is isolated, charge is conserved (B true). V=Q/C, so with Q fixed and C halved, V doubles (C true). Energy = Q^2/(2C); with Q fixed and C halved, energy actually DOUBLES, not decreases (D false).'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'medium', 'numerical',
 'A capacitor of $C=2\,\mu F$ is charged to $V=10$ V. Find the energy stored (in $\mu J$), using $U=\frac{1}{2}CV^2$.',
 null, '100', 'U = 0.5 * 2 * 10^2 = 100 microjoules.'),
('JEE Advanced', 'Physics', 'Electrodynamics (Electrostatics, Current Electricity, Magnetism, EMI, AC)', 'hard', 'descriptive',
 'Explain why the energy stored in an isolated, charged capacitor increases when its plate separation is increased, in terms of work done against the attractive force between the plates.',
 null, null, 'Since the capacitor is isolated, its charge stays fixed, but pulling the plates further apart requires doing work against their mutual electrostatic attraction. This work goes into increasing the electrostatic potential energy stored in the capacitor, which is why the stored energy increases even though capacitance itself decreases.'),

-- Physics: Modern Physics
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'medium', 'mcq',
 'In the Bohr model, find the energy of the electron in the $n=2$ state of a hydrogen atom (using $E_n=-13.6/n^2$ eV).',
 '[{"text":"-13.6 eV","isCorrect":false},{"text":"-3.4 eV","isCorrect":true},{"text":"-1.51 eV","isCorrect":false},{"text":"-6.8 eV","isCorrect":false}]'::jsonb,
 null, 'E_2 = -13.6/2^2 = -13.6/4 = -3.4 eV.'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'mcq',
 'A photon of energy greater than the work function strikes a metal surface, ejecting photoelectrons. Which of the following statement(s) is/are TRUE? (A) Increasing the intensity of light (same frequency) increases the number of photoelectrons emitted per second. (B) Increasing the intensity increases the maximum kinetic energy of each photoelectron. (C) There exists a threshold frequency below which no photoelectrons are emitted, regardless of intensity. (D) The stopping potential depends on the frequency of incident light, not its intensity.',
 '[{"text":"(A) More intensity means more photoelectrons per second","isCorrect":true},{"text":"(B) More intensity increases max KE per photoelectron","isCorrect":false},{"text":"(C) Threshold frequency exists regardless of intensity","isCorrect":true},{"text":"(D) Stopping potential depends on frequency, not intensity","isCorrect":true}]'::jsonb,
 null, 'More intense light means more photons per second, ejecting more photoelectrons per second (A true), but maximum kinetic energy depends only on frequency, not intensity (B false). Below the threshold frequency, no photoelectrons are emitted no matter how intense the light is (C true), and stopping potential is set by frequency alone (D true).'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'numerical',
 'Find the de Broglie wavelength (in picometers) of an electron accelerated through a potential difference of $150$ V, using $\lambda \text{(nm)} = \frac{1.226}{\sqrt{V}}$ (nearest whole number).',
 null, '100', 'lambda = 1.226/sqrt(150) = 1.226/12.247 = approximately 0.1 nm = 100 pm.'),
('JEE Advanced', 'Physics', 'Modern Physics (Atoms, Nuclei, Dual Nature of Matter, Semiconductors)', 'hard', 'descriptive',
 'Explain why the photoelectric effect could not be explained by classical wave theory, focusing specifically on the existence of a threshold frequency.',
 null, null, 'Classical wave theory predicts that sufficiently intense light of any frequency should eventually eject electrons, since energy could accumulate over time regardless of frequency. Experimentally, no electrons are emitted below a certain threshold frequency no matter how intense the light is -- this was only explained by Einstein''s photon model, where each photon carries a fixed energy hf, and ejection requires a single photon''s energy to exceed the work function.'),

-- Physics: Heat and Thermodynamics
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'hard', 'mcq',
 'An ideal gas undergoes a process where $PV^2=\text{constant}$. As the gas expands, its temperature:',
 '[{"text":"Increases","isCorrect":false},{"text":"Decreases","isCorrect":true},{"text":"Remains constant","isCorrect":false},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'Using PV=nRT, P=nRT/V, so PV^2 = nRT*V = constant, meaning TV = constant. As V increases, T must decrease.'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'medium', 'mcq',
 'For a Carnot engine operating between temperatures $T_1$ (source) and $T_2$ (sink), $T_1>T_2$, which of the following statement(s) is/are TRUE? (A) Efficiency is $1-T_2/T_1$. (B) Efficiency can theoretically reach 100% if $T_2=0$ K. (C) Efficiency is independent of the working substance. (D) Efficiency increases if $T_2$ is increased while $T_1$ stays fixed.',
 '[{"text":"(A) Efficiency is 1 - T2/T1","isCorrect":true},{"text":"(B) 100% efficiency if T2=0K","isCorrect":true},{"text":"(C) Independent of working substance","isCorrect":true},{"text":"(D) Efficiency increases if T2 increases","isCorrect":false}]'::jsonb,
 null, 'Carnot efficiency is 1-T2/T1 (A true), theoretically reaching 100% only if T2=0K, unreachable in practice (B true), and depends only on the two temperatures, not the working substance, per Carnot''s theorem (C true). Increasing T2 while T1 stays fixed DEcreases efficiency, since T2/T1 grows (D false).'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'medium', 'numerical',
 'A Carnot engine operates between 600 K and 300 K, absorbing 800 J of heat from the source per cycle. Find the work done (in J) per cycle.',
 null, '400', 'Efficiency = 1 - 300/600 = 0.5. Work = 0.5 * 800 = 400 J.'),
('JEE Advanced', 'Physics', 'Heat and Thermodynamics', 'hard', 'descriptive',
 'State the second law of thermodynamics in the form relevant to heat engines, and explain why no real engine can exceed the Carnot efficiency between two given temperatures.',
 null, null, 'The Kelvin-Planck statement says no engine operating in a cycle can convert heat completely into work with no other effect. The Carnot engine is the most efficient possible engine between two temperatures because it operates reversibly; any real engine has irreversibilities (friction, unrestrained expansion, etc.) that generate extra entropy, reducing its efficiency below the Carnot limit.'),

-- Physics: Optics
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'mcq',
 'In a Young''s double slit experiment, if the entire setup is immersed in a liquid of refractive index $\mu$, the fringe width:',
 '[{"text":"Increases by factor mu","isCorrect":false},{"text":"Decreases by factor mu","isCorrect":true},{"text":"Remains unchanged","isCorrect":false},{"text":"Decreases by factor mu squared","isCorrect":false}]'::jsonb,
 null, 'Fringe width beta = lambda*D/d. The wavelength inside the medium is lambda/mu, so beta decreases by a factor of mu.'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'hard', 'mcq',
 'Regarding a single-slit diffraction pattern, which of the following statement(s) is/are TRUE? (A) The central maximum is twice as wide as the secondary maxima. (B) The intensity of secondary maxima decreases moving away from the center. (C) The first minimum occurs at $\sin\theta=\lambda/a$, where $a$ is the slit width. (D) Diffraction effects become less noticeable as the slit width decreases.',
 '[{"text":"(A) Central maximum twice as wide","isCorrect":true},{"text":"(B) Secondary maxima intensity decreases outward","isCorrect":true},{"text":"(C) First minimum at sin(theta)=lambda/a","isCorrect":true},{"text":"(D) Diffraction less noticeable as slit narrows","isCorrect":false}]'::jsonb,
 null, 'The central maximum spans twice the angular width of each secondary maximum (A true), and secondary maxima intensity falls off further from center (B true). The first minimum condition is sin(theta)=lambda/a (C true). Diffraction actually becomes MORE noticeable as slit width approaches the wavelength, not less (D false).'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'numerical',
 'Light of wavelength 600 nm is incident on a single slit of width 0.2 mm. Find the angular position of the first minimum, in units of $10^{-3}$ radians (give just the coefficient), using $\theta \approx \lambda/a$ for small angles.',
 null, '3', 'theta = 600e-9 / 0.2e-3 = 3e-3 rad, so the coefficient is 3.'),
('JEE Advanced', 'Physics', 'Optics (Ray and Wave)', 'medium', 'descriptive',
 'Explain why diffraction effects are generally not noticeable for everyday-sized openings, but are noticeable for slits comparable to the wavelength of light.',
 null, null, 'Diffraction becomes significant only when the opening size is comparable to or smaller than the wavelength. Visible light has a wavelength of a few hundred nanometers, so ordinary openings (doors, windows) are far too large for diffraction to be noticeable, whereas a narrow slit comparable in width to the wavelength produces a clearly observable diffraction pattern.'),

-- Physics: Waves and Oscillations
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'medium', 'mcq',
 'A particle executes SHM with amplitude $A$. At what displacement from the mean position is its kinetic energy equal to its potential energy?',
 '[{"text":"A/2","isCorrect":false},{"text":"A/sqrt(2)","isCorrect":true},{"text":"A/sqrt(3)","isCorrect":false},{"text":"2A/3","isCorrect":false}]'::jsonb,
 null, 'KE equals PE when x = A/sqrt(2), found by setting (1/2)k(A^2-x^2) = (1/2)kx^2 and solving for x.'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'hard', 'mcq',
 'For a particle in SHM given by $x(t)=A\sin(\omega t)$, which of the following statement(s) is/are TRUE? (A) The maximum speed is $A\omega$, occurring at $x=0$. (B) The maximum acceleration is $A\omega^2$, occurring at $x=\pm A$. (C) The total mechanical energy is constant throughout the motion. (D) The period of oscillation depends on the amplitude $A$.',
 '[{"text":"(A) Max speed A*omega at x=0","isCorrect":true},{"text":"(B) Max acceleration A*omega^2 at x=+-A","isCorrect":true},{"text":"(C) Total mechanical energy constant","isCorrect":true},{"text":"(D) Period depends on amplitude","isCorrect":false}]'::jsonb,
 null, 'Speed is maximum at the mean position (A true) and acceleration is maximum at the extremes (B true). Mechanical energy stays constant throughout ideal SHM (C true). The period of SHM is independent of amplitude, not dependent on it (D false).'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'easy', 'numerical',
 'A particle in SHM has angular frequency $\omega=4$ rad/s and amplitude $A=5$ cm. Find its maximum speed (in cm/s).',
 null, '20', 'Maximum speed = A*omega = 5*4 = 20 cm/s.'),
('JEE Advanced', 'Physics', 'Waves and Oscillations', 'hard', 'descriptive',
 'Explain why the restoring force in simple harmonic motion must be proportional to displacement and directed toward the mean position, and what would happen if it were not.',
 null, null, 'SHM requires a restoring force F=-kx, proportional to displacement and directed toward equilibrium, which produces sinusoidal motion with a period independent of amplitude. If the force were not proportional to displacement, the motion could still oscillate in some cases, but the period would depend on amplitude and the motion would not follow a pure sine or cosine function.'),

-- Physics: Properties of Matter and Fluids
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'medium', 'mcq',
 'A liquid rises to height $h$ in a capillary tube of radius $r$. If the radius is doubled, the new height of rise is:',
 '[{"text":"h/2","isCorrect":true},{"text":"2h","isCorrect":false},{"text":"h/4","isCorrect":false},{"text":"4h","isCorrect":false}]'::jsonb,
 null, 'h = 2*T*cos(theta)/(rho*g*r) is inversely proportional to r, so doubling r halves h.'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'hard', 'mcq',
 'Regarding terminal velocity of a sphere falling through a viscous fluid, which of the following statement(s) is/are TRUE? (A) Terminal velocity is directly proportional to the square of the sphere''s radius. (B) Terminal velocity increases if the fluid''s viscosity increases. (C) At terminal velocity, the net force on the sphere is zero. (D) Terminal velocity depends on the density difference between the sphere and the fluid.',
 '[{"text":"(A) Proportional to radius squared","isCorrect":true},{"text":"(B) Increases with viscosity","isCorrect":false},{"text":"(C) Net force is zero at terminal velocity","isCorrect":true},{"text":"(D) Depends on density difference","isCorrect":true}]'::jsonb,
 null, 'By Stokes'' law, terminal velocity is proportional to r^2 (A true) and inversely proportional to viscosity, so it DEcreases as viscosity increases, not increases (B false). At terminal velocity, net force is zero by definition (C true), and terminal velocity depends on the density difference between sphere and fluid (D true).'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'medium', 'numerical',
 'A small sphere of radius $r$ reaches terminal velocity $v_1$. Find the terminal velocity of a sphere of the same material with radius $2r$, as a multiple of $v_1$ (give just the number), using $v_t \propto r^2$.',
 null, '4', '(2r)^2 / r^2 = 4, so the terminal velocity is 4 times v1.'),
('JEE Advanced', 'Physics', 'Properties of Matter and Fluids', 'hard', 'descriptive',
 'Explain conceptually why terminal velocity is proportional to the square of the radius for a sphere falling through a viscous fluid, referencing Stokes'' law.',
 null, null, 'By Stokes'' law, viscous drag force is proportional to radius, while the net driving force (weight minus buoyancy) is proportional to volume, i.e. radius cubed. Setting drag equal to net weight at terminal velocity and solving for velocity gives a result proportional to radius squared -- the extra factor of radius coming from the volume-to-drag ratio.'),

-- Chemistry: Physical Chemistry
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'hard', 'mcq',
 'For a reaction $A \to B$ with rate constant $k$ that is zero order, the half-life is:',
 '[{"text":"Independent of [A]0","isCorrect":false},{"text":"Directly proportional to [A]0","isCorrect":true},{"text":"Inversely proportional to [A]0","isCorrect":false},{"text":"Independent of k","isCorrect":false}]'::jsonb,
 null, 'For a zero-order reaction, half-life = [A]0 / (2k), which is directly proportional to the initial concentration.'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'mcq',
 'For an ideal solution obeying Raoult''s law, which of the following statement(s) is/are TRUE? (A) $\Delta H_{mixing}=0$. (B) $\Delta V_{mixing}=0$. (C) The vapor pressure of the solution is always higher than that predicted by Raoult''s law. (D) Intermolecular forces between different components are similar to those between like components.',
 '[{"text":"(A) Delta H mixing = 0","isCorrect":true},{"text":"(B) Delta V mixing = 0","isCorrect":true},{"text":"(C) Vapor pressure always higher than Raoult predicts","isCorrect":false},{"text":"(D) Similar intermolecular forces between components","isCorrect":true}]'::jsonb,
 null, 'An ideal solution has zero enthalpy and volume change on mixing (A, B true) because unlike and like molecule interactions are similar (D true). By definition, an ideal solution obeys Raoult''s law exactly with no deviation (C false).'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'numerical',
 'For a first-order reaction, 75% of the reactant decomposes in 40 minutes. Find the half-life (in minutes).',
 null, '20', '75% decomposition corresponds to exactly 2 half-lives, so the half-life is 40/2 = 20 minutes.'),
('JEE Advanced', 'Chemistry', 'Physical Chemistry (Mole Concept, Thermodynamics, Equilibrium, Electrochemistry, Chemical Kinetics, Solutions)', 'medium', 'descriptive',
 'Explain the difference between molarity and molality, and state which one is temperature-independent and why.',
 null, null, 'Molarity is moles of solute per liter of solution, while molality is moles of solute per kilogram of solvent. Molality is temperature-independent because it is defined by mass, which does not change with temperature, whereas molarity depends on solution volume, which can expand or contract with temperature.'),

-- Chemistry: Organic Chemistry
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'medium', 'mcq',
 'Which of the following carbocations is the most stable?',
 '[{"text":"Primary","isCorrect":false},{"text":"Secondary","isCorrect":false},{"text":"Tertiary","isCorrect":true},{"text":"Methyl","isCorrect":false}]'::jsonb,
 null, 'Tertiary carbocations are stabilized by hyperconjugation and the inductive effect from three alkyl groups, making them the most stable.'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'mcq',
 'Regarding the acidity of phenol compared to ethanol, which of the following statement(s) is/are TRUE? (A) Phenol is more acidic than ethanol. (B) The phenoxide ion is stabilized by resonance with the benzene ring. (C) The ethoxide ion is more stable than the phenoxide ion. (D) Electron-withdrawing groups on the ring, like $-NO_2$, increase phenol''s acidity.',
 '[{"text":"(A) Phenol more acidic than ethanol","isCorrect":true},{"text":"(B) Phenoxide stabilized by resonance","isCorrect":true},{"text":"(C) Ethoxide more stable than phenoxide","isCorrect":false},{"text":"(D) EWGs increase phenol acidity","isCorrect":true}]'::jsonb,
 null, 'Phenol is more acidic than ethanol (A true) because the phenoxide ion is stabilized by resonance delocalization into the benzene ring (B true) -- this makes phenoxide MORE stable than ethoxide, not less (C false). Electron-withdrawing groups further stabilize the phenoxide ion, increasing acidity (D true).'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'numerical',
 'How many distinct stereoisomers does 2,3-dibromobutane have, accounting for one meso form?',
 null, '3', 'With 2 stereocenters there are normally 4 combinations, but symmetry makes one pair identical (meso), giving 3 distinct stereoisomers: a pair of enantiomers plus 1 meso compound.'),
('JEE Advanced', 'Chemistry', 'Organic Chemistry (GOC, Hydrocarbons, Alcohols-Phenols-Ethers, Carbonyl Compounds, Amines, Biomolecules, Polymers)', 'hard', 'descriptive',
 'Explain what a "meso compound" is and why it is optically inactive despite having stereocenters.',
 null, null, 'A meso compound has multiple stereocenters but also an internal plane of symmetry, making it superimposable on its own mirror image. Because of this internal symmetry, the optical rotation from one half of the molecule exactly cancels that of the other half, making the whole molecule optically inactive despite having stereocenters.'),

-- Chemistry: Inorganic Chemistry
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'mcq',
 'Which of the following ions has the maximum number of unpaired electrons?',
 '[{"text":"Cr3+","isCorrect":false},{"text":"Mn2+","isCorrect":true},{"text":"Fe2+","isCorrect":false},{"text":"Co2+","isCorrect":false}]'::jsonb,
 null, 'Mn2+ has configuration 3d5, which is half-filled with all 5 electrons unpaired -- the maximum among these options.'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'mcq',
 'Regarding crystal field theory, which of the following statement(s) is/are TRUE? (A) Strong field ligands cause a large crystal field splitting energy. (B) $[Fe(CN)_6]^{4-}$ is a low-spin complex. (C) Weak field ligands favor high-spin complexes. (D) Crystal field splitting energy is the same for octahedral and tetrahedral complexes with the same ligands.',
 '[{"text":"(A) Strong field ligands cause large splitting","isCorrect":true},{"text":"(B) [Fe(CN)6]4- is low-spin","isCorrect":true},{"text":"(C) Weak field ligands favor high-spin","isCorrect":true},{"text":"(D) Same splitting for octahedral and tetrahedral","isCorrect":false}]'::jsonb,
 null, 'Strong field ligands like CN- cause large splitting and favor low-spin complexes (A, B true), while weak field ligands favor high-spin complexes (C true). Tetrahedral splitting is only about 4/9 of the octahedral value for the same ligands, not equal (D false).'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'medium', 'numerical',
 'Find the spin-only magnetic moment (in Bohr magnetons, nearest whole number) of $Mn^{2+}$ (5 unpaired electrons), using $\mu=\sqrt{n(n+2)}$.',
 null, '6', 'mu = sqrt(5*7) = sqrt(35) is approximately 5.92, which rounds to 6.'),
('JEE Advanced', 'Chemistry', 'Inorganic Chemistry (Periodic Table, Chemical Bonding, Coordination Compounds, p/d/f-Block Elements, Metallurgy)', 'hard', 'descriptive',
 'Explain what crystal field splitting energy represents and how it differs between octahedral and tetrahedral geometries.',
 null, null, 'Crystal field splitting energy is the energy gap created between a transition metal ion''s d-orbitals when surrounded by ligands, due to differing electrostatic repulsion depending on orbital orientation. In an octahedral field, the d-orbitals split into a lower t2g set and higher eg set; in a tetrahedral field the pattern is inverted and the overall splitting is smaller, about 4/9 of the octahedral value for the same ligands and metal.'),

-- Mathematics: Algebra
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'mcq',
 'If $\alpha,\beta$ are roots of $x^2-3x+2=0$, find $\alpha^2+\beta^2$.',
 '[{"text":"3","isCorrect":false},{"text":"5","isCorrect":true},{"text":"9","isCorrect":false},{"text":"7","isCorrect":false}]'::jsonb,
 null, 'Sum of roots = 3, product = 2. alpha^2+beta^2 = (sum)^2 - 2*(product) = 9 - 4 = 5.'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'hard', 'mcq',
 'For a non-zero complex number $z=x+iy$, which of the following statement(s) is/are TRUE? (A) $|z|^2=z\bar{z}$. (B) $\arg(z)+\arg(1/z)=0$ (for $z$ not a negative real number). (C) If $|z|=1$, then $\bar{z}=1/z$. (D) $z+\bar{z}$ is always purely imaginary.',
 '[{"text":"(A) |z|^2 = z times z-conjugate","isCorrect":true},{"text":"(B) arg(z)+arg(1/z)=0","isCorrect":true},{"text":"(C) If |z|=1 then conjugate = 1/z","isCorrect":true},{"text":"(D) z + conjugate always purely imaginary","isCorrect":false}]'::jsonb,
 null, '|z|^2 always equals z times its conjugate (A true), and 1/z has the negative argument of z (B true). If |z|=1, z times conjugate(z)=1, so conjugate(z)=1/z (C true). But z+conjugate(z)=2x is always REAL, never purely imaginary (D false).'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'numerical',
 'If the roots of $x^2-6x+k=0$ are equal, find $k$.',
 null, '9', 'For equal roots, the discriminant is zero: 36 - 4k = 0, giving k = 9.'),
('JEE Advanced', 'Mathematics', 'Algebra (Complex Numbers, Quadratic Equations, Sequences and Series, Permutations-Combinations, Binomial Theorem, Matrices and Determinants)', 'medium', 'descriptive',
 'Explain what it means for a quadratic equation to have "equal roots," and state the condition on the discriminant for this to happen.',
 null, null, 'Equal roots means the quadratic touches the x-axis at exactly one point (a repeated root), which happens precisely when the discriminant b^2-4ac equals zero for ax^2+bx+c=0.'),

-- Mathematics: Calculus
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'easy', 'mcq',
 'Find $\lim_{x\to 0}\frac{\sin(3x)}{x}$.',
 '[{"text":"1","isCorrect":false},{"text":"3","isCorrect":true},{"text":"1/3","isCorrect":false},{"text":"0","isCorrect":false}]'::jsonb,
 null, 'Using the standard limit sin(kx)/x -> k as x approaches 0, the answer is 3.'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'hard', 'mcq',
 'Let $f(x)=x^4-4x^2$. Which of the following statement(s) is/are TRUE? (A) $f$ has a local maximum at $x=0$. (B) $f$ has local minima at $x=\pm\sqrt{2}$. (C) $f$ is an even function. (D) $f$ has exactly one critical point.',
 '[{"text":"(A) Local maximum at x=0","isCorrect":true},{"text":"(B) Local minima at x=+-sqrt(2)","isCorrect":true},{"text":"(C) f is an even function","isCorrect":true},{"text":"(D) Exactly one critical point","isCorrect":false}]'::jsonb,
 null, 'f''(x)=4x^3-8x=4x(x^2-2)=0 at x=0 and x=+-sqrt(2). f''''(0)<0 gives a local max at x=0 (A true), and f''''(+-sqrt2)>0 gives local minima there (B true). Since f(-x)=f(x), f is even (C true). There are 3 critical points, not exactly one (D false).'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'numerical',
 'Evaluate $\int_0^{\pi/2}\cos x\,dx$, as an integer.',
 null, '1', 'The antiderivative of cos(x) is sin(x); evaluating from 0 to pi/2 gives sin(pi/2)-sin(0) = 1-0 = 1.'),
('JEE Advanced', 'Mathematics', 'Calculus (Limits-Continuity-Differentiability, Application of Derivatives, Integration, Differential Equations)', 'medium', 'descriptive',
 'Explain what an inflection point is and how the second derivative test is used to identify one.',
 null, null, 'An inflection point is where the concavity of a function changes, from concave up to concave down or vice versa. It is identified by finding where the second derivative equals zero (or is undefined) AND actually changes sign on either side of that point -- if the sign does not change, it is not an inflection point.'),

-- Mathematics: Coordinate Geometry
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'easy', 'mcq',
 'Find the equation of the circle with center $(0,0)$ passing through $(3,4)$.',
 '[{"text":"x^2+y^2=25","isCorrect":true},{"text":"x^2+y^2=5","isCorrect":false},{"text":"x^2+y^2=7","isCorrect":false},{"text":"x^2+y^2=12","isCorrect":false}]'::jsonb,
 null, 'The radius equals the distance from the origin to (3,4), which is sqrt(9+16)=5, giving x^2+y^2=25.'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'hard', 'mcq',
 'For the ellipse $\frac{x^2}{25}+\frac{y^2}{9}=1$, which of the following statement(s) is/are TRUE? (A) The semi-major axis length is 5. (B) The foci are at $(\pm4,0)$. (C) The eccentricity is $4/5$. (D) The ellipse is symmetric only about the x-axis, not the y-axis.',
 '[{"text":"(A) Semi-major axis is 5","isCorrect":true},{"text":"(B) Foci at (+-4, 0)","isCorrect":true},{"text":"(C) Eccentricity is 4/5","isCorrect":true},{"text":"(D) Symmetric only about x-axis","isCorrect":false}]'::jsonb,
 null, 'Here a^2=25, b^2=9, so a=5 (A true). c^2=a^2-b^2=16, c=4, giving foci at (+-4,0) (B true) and eccentricity c/a=4/5 (C true). The ellipse is symmetric about BOTH axes, not only the x-axis (D false).'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'numerical',
 'Find the length of the latus rectum of the parabola $y^2=12x$.',
 null, '12', 'For y^2=4ax, latus rectum = 4a. Here 4a=12, so a=3 and the latus rectum is 4*3=12.'),
('JEE Advanced', 'Mathematics', 'Coordinate Geometry (Straight Lines, Circles, Conic Sections)', 'medium', 'descriptive',
 'Explain what "eccentricity" represents for a conic section, and state its range of values for an ellipse, parabola, and hyperbola respectively.',
 null, null, 'Eccentricity measures how much a conic deviates from being circular -- it is the ratio of a point''s distance to a focus versus its distance to the corresponding directrix. For an ellipse it is between 0 and 1, for a parabola it equals exactly 1, and for a hyperbola it is greater than 1.'),

-- Mathematics: Trigonometry
('JEE Advanced', 'Mathematics', 'Trigonometry', 'easy', 'mcq',
 'Find the general solution of $\sin x=0$.',
 '[{"text":"n*pi","isCorrect":true},{"text":"2n*pi","isCorrect":false},{"text":"n*pi/2","isCorrect":false},{"text":"(2n+1)*pi/2","isCorrect":false}]'::jsonb,
 null, 'sin(x)=0 whenever x is an integer multiple of pi, i.e. x = n*pi.'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'hard', 'mcq',
 'For $2\sin^2 x-\sin x-1=0$ with $x\in[0,2\pi)$, which of the following statement(s) is/are TRUE? (A) $x=\pi/2$ is a solution. (B) $x=7\pi/6$ is a solution. (C) $x=11\pi/6$ is a solution. (D) There are exactly 2 solutions in $[0,2\pi)$.',
 '[{"text":"(A) x=pi/2 is a solution","isCorrect":true},{"text":"(B) x=7pi/6 is a solution","isCorrect":true},{"text":"(C) x=11pi/6 is a solution","isCorrect":true},{"text":"(D) Exactly 2 solutions in [0,2pi)","isCorrect":false}]'::jsonb,
 null, 'Letting s=sin(x), 2s^2-s-1=(2s+1)(s-1)=0 gives s=1 or s=-1/2. s=1 gives x=pi/2 (A true); s=-1/2 gives x=7pi/6 and x=11pi/6 in this interval (B, C true) -- a total of 3 solutions, not 2 (D false).'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'medium', 'numerical',
 'Find the number of solutions of $\sin x=1/2$ in the interval $[0,2\pi)$.',
 null, '2', 'sin(x)=1/2 at x=pi/6 and x=5pi/6 in this interval, giving 2 solutions.'),
('JEE Advanced', 'Mathematics', 'Trigonometry', 'medium', 'descriptive',
 'Explain the general method for solving a trigonometric equation of the form $a\sin^2 x+b\sin x+c=0$.',
 null, null, 'Treat sin(x) as a single variable and solve the resulting quadratic equation using the quadratic formula or factoring. Then, for each valid value of sin(x) within [-1,1], solve sin(x) equal to that value for x within the required interval using the general solution or reference angles.'),

-- Mathematics: Vectors and 3D Geometry
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'easy', 'mcq',
 'Find a unit vector in the direction of $\vec{a}=(3,4,0)$.',
 '[{"text":"(3/5, 4/5, 0)","isCorrect":true},{"text":"(3, 4, 0)","isCorrect":false},{"text":"(0.6, 0.8, 1)","isCorrect":false},{"text":"(3/4, 4/3, 0)","isCorrect":false}]'::jsonb,
 null, '|a| = sqrt(9+16) = 5, so the unit vector is (3/5, 4/5, 0).'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'hard', 'mcq',
 'For three vectors $\vec{a},\vec{b},\vec{c}$, which of the following statement(s) is/are TRUE? (A) If $\vec{a}\times\vec{b}=\vec{0}$ and both are non-zero, then $\vec{a}$ and $\vec{b}$ are parallel. (B) $\vec{a}\cdot(\vec{b}\times\vec{c})$ is a scalar. (C) $\vec{a}\times(\vec{b}\times\vec{c})=(\vec{a}\times\vec{b})\times\vec{c}$ always holds. (D) If $[\vec{a}\,\vec{b}\,\vec{c}]=0$, the three vectors are coplanar.',
 '[{"text":"(A) Zero cross product means parallel","isCorrect":true},{"text":"(B) Scalar triple product is a scalar","isCorrect":true},{"text":"(C) Cross product is associative","isCorrect":false},{"text":"(D) Zero scalar triple product means coplanar","isCorrect":true}]'::jsonb,
 null, 'A zero cross product between two non-zero vectors means they are parallel (A true), and the scalar triple product is indeed a scalar (B true). The cross product is NOT associative in general, so (C) is false. A zero scalar triple product means the three vectors are coplanar (D true).'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'numerical',
 'Find the projection of $\vec{a}=(3,4,0)$ onto $\vec{b}=(1,0,0)$, as a scalar.',
 null, '3', 'Projection = (a.b)/|b| = 3/1 = 3.'),
('JEE Advanced', 'Mathematics', 'Vectors and 3D Geometry', 'medium', 'descriptive',
 'Explain the difference between the scalar (dot) product and vector (cross) product of two vectors, in terms of the result each produces and what it represents geometrically.',
 null, null, 'The dot product produces a SCALAR, equal to the product of the two magnitudes and the cosine of the angle between them, related to projection and work done. The cross product produces a VECTOR perpendicular to both original vectors, with magnitude equal to the product of the magnitudes and the sine of the angle between them, representing the area of the parallelogram they span.'),

-- Mathematics: Statistics and Probability
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'mcq',
 'Two unbiased dice are rolled. Find the probability that the product of the numbers shown is even.',
 '[{"text":"1/4","isCorrect":false},{"text":"1/2","isCorrect":false},{"text":"3/4","isCorrect":true},{"text":"1/3","isCorrect":false}]'::jsonb,
 null, 'The product is odd only if both numbers are odd, with probability (3/6)*(3/6)=1/4. So the probability the product is even is 1 - 1/4 = 3/4.'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'hard', 'mcq',
 'A fair coin is tossed 3 times. Which of the following statement(s) is/are TRUE? (A) The probability of getting exactly 2 heads is $3/8$. (B) The probability of getting at least 1 head is $7/8$. (C) The probability of getting all heads or all tails is $1/4$. (D) The events "first toss is heads" and "second toss is heads" are dependent.',
 '[{"text":"(A) P(exactly 2 heads) = 3/8","isCorrect":true},{"text":"(B) P(at least 1 head) = 7/8","isCorrect":true},{"text":"(C) P(all heads or all tails) = 1/4","isCorrect":true},{"text":"(D) First and second toss are dependent","isCorrect":false}]'::jsonb,
 null, 'P(exactly 2 heads) = C(3,2)/8 = 3/8 (A true). P(at least 1 head) = 1 - 1/8 = 7/8 (B true). P(all heads or all tails) = 1/8+1/8 = 1/4 (C true). Coin tosses are independent of each other, not dependent (D false).'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'numerical',
 'A bag has 4 white and 6 black balls. Two balls are drawn without replacement. Find the probability that both are white, as a simplified fraction (e.g. 2/15).',
 null, '2/15', 'P = (4/10)*(3/9) = 12/90 = 2/15.'),
('JEE Advanced', 'Mathematics', 'Statistics and Probability', 'medium', 'descriptive',
 'Explain the difference between "with replacement" and "without replacement" sampling, and how it affects probability calculations for successive draws.',
 null, null, 'In sampling "with replacement," each draw is independent since the item is returned before the next draw, so probabilities stay the same each time. In sampling "without replacement," each draw changes the composition of the remaining pool, making subsequent draws dependent on what was already drawn.');
