-- supabase/sql/exam_question_bank_neet_pg_set2.sql
--
-- Second curated question-bank batch for 'NEET PG' (see exam_patterns_neet_pg.sql for the exam's
-- structure, and exam_question_bank_neet_pg_set1.sql for the first batch -- same table/schema, no
-- migration needed). All-new questions, no overlap with Set 1.
--
-- Same format as Set 1: every row is format='mcq' with a single isCorrect:true option, matching
-- NEET PG's 100% single-best-response format. 16 chapters (8 Pre-/Para-Clinical Sciences, 4
-- Clinical Medicine and Allied, 2 Surgery and Allied, 2 Obstetrics/Gynaecology/Anesthesia) each get
-- 4 questions, covering classic, high-yield MBBS/board-style facts.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_neet_pg.sql and
-- exam_question_bank_neet_pg_set1.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- Anatomy
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'The sciatic nerve, the largest nerve in the human body, arises from which plexus?',
 '[{"text":"Cervical plexus","isCorrect":false},{"text":"Brachial plexus","isCorrect":false},{"text":"Lumbosacral (sacral) plexus","isCorrect":true},{"text":"Coccygeal plexus","isCorrect":false}]'::jsonb,
 null, 'The sciatic nerve arises from the lumbosacral plexus (L4-S3), making it the largest and longest nerve in the human body.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'easy', 'mcq',
 'The largest artery in the human body is the:',
 '[{"text":"Pulmonary artery","isCorrect":false},{"text":"Aorta","isCorrect":true},{"text":"Renal artery","isCorrect":false},{"text":"Carotid artery","isCorrect":false}]'::jsonb,
 null, 'The aorta, arising from the left ventricle, is the largest artery in the body, distributing oxygenated blood to the systemic circulation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'medium', 'mcq',
 'Which cranial nerve is primarily responsible for the muscles of facial expression?',
 '[{"text":"Trigeminal nerve (CN V)","isCorrect":false},{"text":"Facial nerve (CN VII)","isCorrect":true},{"text":"Glossopharyngeal nerve (CN IX)","isCorrect":false},{"text":"Hypoglossal nerve (CN XII)","isCorrect":false}]'::jsonb,
 null, 'The facial nerve (CN VII) innervates the muscles of facial expression; its damage (as in Bell''s palsy) causes facial weakness or paralysis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Anatomy', 'hard', 'mcq',
 'The coronary sinus, which collects most of the heart''s venous blood, drains into which chamber?',
 '[{"text":"Left atrium","isCorrect":false},{"text":"Right atrium","isCorrect":true},{"text":"Left ventricle","isCorrect":false},{"text":"Right ventricle","isCorrect":false}]'::jsonb,
 null, 'The coronary sinus, which collects deoxygenated blood from the cardiac veins, drains directly into the right atrium.'),

-- Physiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'The normal resting heart rate in a healthy adult is approximately:',
 '[{"text":"40-60 beats per minute","isCorrect":false},{"text":"60-100 beats per minute","isCorrect":true},{"text":"100-140 beats per minute","isCorrect":false},{"text":"140-180 beats per minute","isCorrect":false}]'::jsonb,
 null, 'A normal resting heart rate in healthy adults typically ranges from 60 to 100 beats per minute.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which hormone is primarily responsible for mediating the "fight or flight" response?',
 '[{"text":"Insulin","isCorrect":false},{"text":"Adrenaline (epinephrine)","isCorrect":true},{"text":"Thyroxine","isCorrect":false},{"text":"Progesterone","isCorrect":false}]'::jsonb,
 null, 'Adrenaline, secreted by the adrenal medulla, prepares the body for rapid action during acute stress, mediating the "fight or flight" response.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'easy', 'mcq',
 'The functional and structural unit of the kidney is the:',
 '[{"text":"Nephron","isCorrect":true},{"text":"Glomerulus alone","isCorrect":false},{"text":"Renal pyramid","isCorrect":false},{"text":"Ureter","isCorrect":false}]'::jsonb,
 null, 'The nephron, comprising the glomerulus and its associated tubules, is the basic functional unit responsible for urine formation in the kidney.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Physiology', 'medium', 'mcq',
 'Which part of the brain primarily controls the automatic rhythm of respiration?',
 '[{"text":"Cerebellum","isCorrect":false},{"text":"Medulla oblongata","isCorrect":true},{"text":"Cerebrum","isCorrect":false},{"text":"Hypothalamus","isCorrect":false}]'::jsonb,
 null, 'The medulla oblongata houses the respiratory center, which generates the automatic rhythm of breathing.'),

-- Biochemistry
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Under aerobic conditions, the end product of glycolysis is:',
 '[{"text":"Lactate","isCorrect":false},{"text":"Pyruvate","isCorrect":true},{"text":"Acetyl-CoA directly, bypassing pyruvate","isCorrect":false},{"text":"Ethanol","isCorrect":false}]'::jsonb,
 null, 'Under aerobic conditions, glycolysis produces pyruvate, which is then converted to acetyl-CoA and enters the citric acid cycle.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'easy', 'mcq',
 'Which vitamin is essential for the synthesis of clotting factors and normal blood coagulation?',
 '[{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin K","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin E","isCorrect":false}]'::jsonb,
 null, 'Vitamin K is required for the gamma-carboxylation of clotting factors II, VII, IX, and X, essential for normal blood coagulation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'The Krebs cycle (citric acid cycle) primarily occurs in which part of the cell?',
 '[{"text":"Cytoplasm","isCorrect":false},{"text":"Mitochondrial matrix","isCorrect":true},{"text":"Nucleus","isCorrect":false},{"text":"Endoplasmic reticulum","isCorrect":false}]'::jsonb,
 null, 'The Krebs cycle enzymes are located in the mitochondrial matrix, where the cycle oxidizes acetyl-CoA to generate NADH, FADH2, and ATP.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Biochemistry', 'medium', 'mcq',
 'Which amino acid serves as the precursor for the synthesis of dopamine and norepinephrine?',
 '[{"text":"Tryptophan","isCorrect":false},{"text":"Tyrosine","isCorrect":true},{"text":"Glycine","isCorrect":false},{"text":"Lysine","isCorrect":false}]'::jsonb,
 null, 'Tyrosine is the amino acid precursor in the biosynthetic pathway leading to dopamine, norepinephrine, and epinephrine (catecholamines).'),

-- Pathology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Anaphylaxis is mediated by which type of hypersensitivity reaction?',
 '[{"text":"Type I hypersensitivity","isCorrect":true},{"text":"Type II hypersensitivity","isCorrect":false},{"text":"Type III hypersensitivity","isCorrect":false},{"text":"Type IV hypersensitivity","isCorrect":false}]'::jsonb,
 null, 'Anaphylaxis is a Type I (immediate) hypersensitivity reaction, mediated by IgE antibodies triggering mast cell and basophil degranulation.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Metaplasia is best described as:',
 '[{"text":"An irreversible malignant transformation","isCorrect":false},{"text":"A reversible change of one differentiated cell type into another","isCorrect":true},{"text":"Cell death due to injury","isCorrect":false},{"text":"An increase in cell size only","isCorrect":false}]'::jsonb,
 null, 'Metaplasia is a reversible adaptive change in which one mature, differentiated cell type is replaced by another, typically in response to chronic irritation or stress.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'medium', 'mcq',
 'Which tumor marker is classically elevated in hepatocellular carcinoma?',
 '[{"text":"CA-125","isCorrect":false},{"text":"Alpha-fetoprotein (AFP)","isCorrect":true},{"text":"PSA","isCorrect":false},{"text":"CEA","isCorrect":false}]'::jsonb,
 null, 'Alpha-fetoprotein (AFP) is a classic tumor marker elevated in hepatocellular carcinoma, also used in monitoring treatment response.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pathology', 'easy', 'mcq',
 'Apoptosis is best described as:',
 '[{"text":"Accidental cell death due to trauma","isCorrect":false},{"text":"Programmed cell death","isCorrect":true},{"text":"Uncontrolled cell division","isCorrect":false},{"text":"Cell enlargement","isCorrect":false}]'::jsonb,
 null, 'Apoptosis is a regulated, energy-dependent form of programmed cell death, distinct from necrosis, which occurs due to injury.'),

-- Microbiology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Tuberculosis is caused by which organism?',
 '[{"text":"Mycobacterium tuberculosis","isCorrect":true},{"text":"Mycobacterium leprae","isCorrect":false},{"text":"Corynebacterium diphtheriae","isCorrect":false},{"text":"Bordetella pertussis","isCorrect":false}]'::jsonb,
 null, 'Mycobacterium tuberculosis, an acid-fast bacillus, is the causative organism of tuberculosis.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'The Widal test is primarily used to diagnose which infection?',
 '[{"text":"Malaria","isCorrect":false},{"text":"Typhoid fever","isCorrect":true},{"text":"Dengue fever","isCorrect":false},{"text":"Tuberculosis","isCorrect":false}]'::jsonb,
 null, 'The Widal test detects antibodies against Salmonella Typhi antigens, used (with limitations) in the serological diagnosis of typhoid fever.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'easy', 'mcq',
 'Chickenpox is caused by which virus?',
 '[{"text":"Herpes simplex virus","isCorrect":false},{"text":"Varicella-zoster virus","isCorrect":true},{"text":"Epstein-Barr virus","isCorrect":false},{"text":"Cytomegalovirus","isCorrect":false}]'::jsonb,
 null, 'Chickenpox (varicella) is caused by primary infection with the varicella-zoster virus, which can later reactivate to cause herpes zoster (shingles).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Microbiology', 'medium', 'mcq',
 'In the Gram staining procedure, gram-positive bacteria retain which stain?',
 '[{"text":"Safranin","isCorrect":false},{"text":"Crystal violet","isCorrect":true},{"text":"Iodine alone","isCorrect":false},{"text":"Carbol fuchsin","isCorrect":false}]'::jsonb,
 null, 'Gram-positive bacteria have a thick peptidoglycan layer that retains the crystal violet-iodine complex even after alcohol decolorization, staining them purple.'),

-- Pharmacology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'medium', 'mcq',
 'Beta-blockers exert their pharmacological effects by blocking which type of receptor?',
 '[{"text":"Alpha-adrenergic receptors","isCorrect":false},{"text":"Beta-adrenergic receptors","isCorrect":true},{"text":"Muscarinic receptors","isCorrect":false},{"text":"Dopamine receptors","isCorrect":false}]'::jsonb,
 null, 'Beta-blockers competitively antagonize beta-adrenergic receptors, reducing heart rate, contractility, and blood pressure.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'Morphine belongs to which class of drugs?',
 '[{"text":"NSAID","isCorrect":false},{"text":"Opioid analgesic","isCorrect":true},{"text":"Antihistamine","isCorrect":false},{"text":"Antibiotic","isCorrect":false}]'::jsonb,
 null, 'Morphine is a classic opioid analgesic, acting on opioid receptors to produce potent pain relief.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'hard', 'mcq',
 'Warfarin exerts its anticoagulant effect primarily by:',
 '[{"text":"Directly inhibiting thrombin","isCorrect":false},{"text":"Inhibiting the synthesis of vitamin K-dependent clotting factors","isCorrect":true},{"text":"Dissolving existing blood clots","isCorrect":false},{"text":"Inhibiting platelet aggregation directly","isCorrect":false}]'::jsonb,
 null, 'Warfarin inhibits vitamin K epoxide reductase, blocking the synthesis of active vitamin K-dependent clotting factors (II, VII, IX, X).'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Pharmacology', 'easy', 'mcq',
 'Insulin is primarily used in the treatment of:',
 '[{"text":"Hypertension","isCorrect":false},{"text":"Diabetes mellitus","isCorrect":true},{"text":"Asthma","isCorrect":false},{"text":"Epilepsy","isCorrect":false}]'::jsonb,
 null, 'Insulin is the key hormone-replacement therapy used in the management of diabetes mellitus, especially Type 1 diabetes.'),

-- Forensic Medicine and Toxicology
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Postmortem lividity (livor mortis) is caused by:',
 '[{"text":"Bacterial decomposition","isCorrect":false},{"text":"Settling of blood due to gravity after death","isCorrect":true},{"text":"Muscle stiffening","isCorrect":false},{"text":"Loss of body heat","isCorrect":false}]'::jsonb,
 null, 'Postmortem lividity occurs as blood settles into the dependent parts of the body under gravity after circulation ceases.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Which poison is classically associated with a garlic-like odor on the breath?',
 '[{"text":"Arsenic (and organophosphorus compounds)","isCorrect":true},{"text":"Cyanide","isCorrect":false},{"text":"Alcohol","isCorrect":false},{"text":"Opium","isCorrect":false}]'::jsonb,
 null, 'Arsenic poisoning (and organophosphorus poisoning) is classically associated with a garlic-like odor on the breath.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'easy', 'mcq',
 'The term "autopsy" refers to:',
 '[{"text":"A routine physical checkup of a living patient","isCorrect":false},{"text":"Examination of a dead body to determine the cause of death","isCorrect":true},{"text":"A surgical procedure on a living patient","isCorrect":false},{"text":"Chemical analysis of blood samples only","isCorrect":false}]'::jsonb,
 null, 'An autopsy (post-mortem examination) is the medical examination of a dead body to determine the cause and manner of death.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'Forensic Medicine and Toxicology', 'medium', 'mcq',
 'Cyanide poisoning classically produces which characteristic odor on the victim''s breath?',
 '[{"text":"Bitter almond odor","isCorrect":true},{"text":"Garlic odor","isCorrect":false},{"text":"Fruity odor","isCorrect":false},{"text":"Rotten egg odor","isCorrect":false}]'::jsonb,
 null, 'Cyanide poisoning classically produces a bitter almond odor on the breath, though not everyone is genetically able to detect this smell.'),

-- PSM (Community Medicine)
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Herd immunity protects unvaccinated individuals in a population primarily by:',
 '[{"text":"Directly boosting their individual immune system","isCorrect":false},{"text":"Reducing the overall circulation of the pathogen in the population","isCorrect":true},{"text":"Making the pathogen less virulent","isCorrect":false},{"text":"Eliminating the need for any vaccination","isCorrect":false}]'::jsonb,
 null, 'When a sufficiently high proportion of a population is immune, disease transmission is reduced, indirectly protecting unvaccinated or non-immune individuals.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'easy', 'mcq',
 'Primary prevention in public health refers to:',
 '[{"text":"Treating a disease after diagnosis","isCorrect":false},{"text":"Preventing disease before it occurs (e.g. vaccination)","isCorrect":true},{"text":"Rehabilitating a patient after recovery","isCorrect":false},{"text":"Screening for early disease detection","isCorrect":false}]'::jsonb,
 null, 'Primary prevention aims to prevent disease onset altogether, through measures like vaccination, health education, and reducing risk factor exposure.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'The Infant Mortality Rate (IMR) is defined as:',
 '[{"text":"The number of deaths of infants under 1 year of age per 1000 live births","isCorrect":true},{"text":"The number of deaths of all ages per 1000 population","isCorrect":false},{"text":"The number of stillbirths per 1000 live births","isCorrect":false},{"text":"The number of maternal deaths per 1000 live births","isCorrect":false}]'::jsonb,
 null, 'Infant Mortality Rate measures the number of deaths of children under 1 year of age per 1000 live births in a given year, a key indicator of population health.'),
('NEET PG', 'Pre- and Para-Clinical Sciences', 'PSM (Community Medicine)', 'medium', 'mcq',
 'Which epidemiological study design is best suited for studying rare diseases?',
 '[{"text":"Case-control study","isCorrect":true},{"text":"Randomized controlled trial","isCorrect":false},{"text":"Cross-sectional study","isCorrect":false},{"text":"Ecological study","isCorrect":false}]'::jsonb,
 null, 'Case-control studies, which start by identifying cases (diseased individuals) and compare them to controls, are efficient for studying rare diseases without needing a huge cohort.'),

-- General Medicine
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common cause of community-acquired pneumonia is:',
 '[{"text":"Streptococcus pneumoniae","isCorrect":true},{"text":"Klebsiella pneumoniae","isCorrect":false},{"text":"Pseudomonas aeruginosa","isCorrect":false},{"text":"Mycoplasma pneumoniae","isCorrect":false}]'::jsonb,
 null, 'Streptococcus pneumoniae remains the most common bacterial cause of community-acquired pneumonia across most age groups.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'The most common causes of acute pancreatitis are:',
 '[{"text":"Gallstones and chronic alcohol use","isCorrect":true},{"text":"Viral hepatitis and malaria","isCorrect":false},{"text":"Tuberculosis and typhoid","isCorrect":false},{"text":"Diabetes and hypertension alone","isCorrect":false}]'::jsonb,
 null, 'Gallstones and chronic alcohol consumption together account for the majority of acute pancreatitis cases.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Type 1 diabetes mellitus is characterized by:',
 '[{"text":"Insulin resistance with relatively preserved insulin secretion","isCorrect":false},{"text":"Autoimmune destruction of pancreatic beta cells","isCorrect":true},{"text":"Excess glucagon secretion alone","isCorrect":false},{"text":"Purely dietary causes","isCorrect":false}]'::jsonb,
 null, 'Type 1 diabetes results from autoimmune destruction of insulin-producing pancreatic beta cells, leading to absolute insulin deficiency.'),
('NEET PG', 'Clinical Medicine and Allied', 'General Medicine', 'medium', 'mcq',
 'Worldwide, the most common causes of liver cirrhosis are:',
 '[{"text":"Chronic hepatitis B and C infection, and alcohol use","isCorrect":true},{"text":"Vitamin deficiency alone","isCorrect":false},{"text":"Bacterial infections of the liver","isCorrect":false},{"text":"Genetic disorders alone","isCorrect":false}]'::jsonb,
 null, 'Chronic viral hepatitis (B and C) and alcohol-related liver disease are the leading causes of liver cirrhosis worldwide.'),

-- Pediatrics
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'The APGAR score is used to assess a newborn''s:',
 '[{"text":"Physical condition immediately after birth","isCorrect":true},{"text":"Growth over the first year of life","isCorrect":false},{"text":"Genetic disorders","isCorrect":false},{"text":"Vaccination schedule","isCorrect":false}]'::jsonb,
 null, 'The APGAR score (Appearance, Pulse, Grimace, Activity, Respiration) is a quick assessment of a newborn''s physical condition immediately after birth.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Whooping cough (pertussis) is classically characterized by:',
 '[{"text":"A silent, painless cough","isCorrect":false},{"text":"Paroxysmal coughing with an inspiratory whoop","isCorrect":true},{"text":"A barking, seal-like cough only","isCorrect":false},{"text":"Coughing only at night","isCorrect":false}]'::jsonb,
 null, 'Whooping cough is classically characterized by paroxysmal (severe, fit-like) coughing episodes followed by a characteristic inspiratory "whoop" sound.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'easy', 'mcq',
 'The normal birth weight range for a healthy full-term newborn is approximately:',
 '[{"text":"1.0 to 1.5 kg","isCorrect":false},{"text":"2.5 to 3.5 kg","isCorrect":true},{"text":"4.5 to 5.5 kg","isCorrect":false},{"text":"5.5 to 6.5 kg","isCorrect":false}]'::jsonb,
 null, 'A healthy full-term newborn typically weighs between 2.5 and 3.5 kg at birth.'),
('NEET PG', 'Clinical Medicine and Allied', 'Pediatrics', 'medium', 'mcq',
 'Which primitive reflex causes a newborn to grasp an object placed in their palm?',
 '[{"text":"Rooting reflex","isCorrect":false},{"text":"Palmar grasp reflex","isCorrect":true},{"text":"Moro reflex","isCorrect":false},{"text":"Babinski reflex","isCorrect":false}]'::jsonb,
 null, 'The palmar grasp reflex causes a newborn to reflexively close their fingers around an object placed in their palm, normally disappearing by around 5-6 months.'),

-- Psychiatry
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which disorder is characterized by recurrent, unwanted intrusive thoughts and repetitive compulsive behaviors?',
 '[{"text":"Generalized anxiety disorder","isCorrect":false},{"text":"Obsessive-compulsive disorder (OCD)","isCorrect":true},{"text":"Panic disorder","isCorrect":false},{"text":"Social phobia","isCorrect":false}]'::jsonb,
 null, 'Obsessive-compulsive disorder is characterized by recurrent intrusive obsessions and repetitive compulsions performed to reduce the resulting anxiety.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'hard', 'mcq',
 'Delirium is best characterized by:',
 '[{"text":"A chronic, stable, progressive decline in memory","isCorrect":false},{"text":"Acute onset with a fluctuating course and disturbance of consciousness/attention","isCorrect":true},{"text":"A lifelong personality trait","isCorrect":false},{"text":"Isolated memory loss with normal attention","isCorrect":false}]'::jsonb,
 null, 'Delirium is characterized by an acute onset, fluctuating course, and disturbance of consciousness and attention, often due to an underlying medical cause, distinguishing it from dementia.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Which drug is classically used as a mood stabilizer in the treatment of bipolar disorder?',
 '[{"text":"Lithium","isCorrect":true},{"text":"Fluoxetine","isCorrect":false},{"text":"Diazepam","isCorrect":false},{"text":"Haloperidol alone","isCorrect":false}]'::jsonb,
 null, 'Lithium is a classic and effective mood stabilizer used in the long-term management of bipolar disorder.'),
('NEET PG', 'Clinical Medicine and Allied', 'Psychiatry', 'medium', 'mcq',
 'Panic disorder is characterized by recurrent:',
 '[{"text":"Sudden episodes of intense fear or discomfort (panic attacks)","isCorrect":true},{"text":"Persistent low mood lasting years","isCorrect":false},{"text":"Auditory hallucinations","isCorrect":false},{"text":"Memory loss episodes","isCorrect":false}]'::jsonb,
 null, 'Panic disorder involves recurrent, unexpected panic attacks -- sudden episodes of intense fear accompanied by physical symptoms like palpitations and shortness of breath.'),

-- Dermatology
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'easy', 'mcq',
 'Acne vulgaris is primarily caused by:',
 '[{"text":"Viral infection of the skin","isCorrect":false},{"text":"Blocked hair follicles with oil and dead skin cells, often involving Propionibacterium acnes","isCorrect":true},{"text":"Autoimmune destruction of skin cells","isCorrect":false},{"text":"Fungal infection of hair follicles","isCorrect":false}]'::jsonb,
 null, 'Acne vulgaris arises from blocked hair follicles due to excess sebum and dead skin cells, often complicated by bacterial colonization with Propionibacterium (Cutibacterium) acnes.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Which skin condition, caused by a fungal infection, classically presents as a ring-shaped, itchy rash?',
 '[{"text":"Tinea (ringworm)","isCorrect":true},{"text":"Eczema","isCorrect":false},{"text":"Psoriasis","isCorrect":false},{"text":"Urticaria","isCorrect":false}]'::jsonb,
 null, 'Tinea (ringworm) is a fungal skin infection that classically presents as a ring-shaped, scaly, itchy rash.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Vitiligo is characterized by:',
 '[{"text":"Excess pigmentation of the skin","isCorrect":false},{"text":"Loss of skin pigmentation due to destruction of melanocytes","isCorrect":true},{"text":"Excessive hair growth","isCorrect":false},{"text":"Thickening of the skin","isCorrect":false}]'::jsonb,
 null, 'Vitiligo is an autoimmune condition causing patchy loss of skin pigmentation due to destruction of melanocytes.'),
('NEET PG', 'Clinical Medicine and Allied', 'Dermatology', 'medium', 'mcq',
 'Herpes zoster (shingles) results from reactivation of which virus?',
 '[{"text":"Herpes simplex virus","isCorrect":false},{"text":"Varicella-zoster virus","isCorrect":true},{"text":"Cytomegalovirus","isCorrect":false},{"text":"Human papillomavirus","isCorrect":false}]'::jsonb,
 null, 'Herpes zoster occurs when latent varicella-zoster virus (the same virus that causes chickenpox) reactivates, typically along a single dermatome.'),

-- General Surgery
('NEET PG', 'Surgery and Allied', 'General Surgery', 'easy', 'mcq',
 'The most common type of hernia in males is the:',
 '[{"text":"Femoral hernia","isCorrect":false},{"text":"Inguinal hernia","isCorrect":true},{"text":"Umbilical hernia","isCorrect":false},{"text":"Incisional hernia","isCorrect":false}]'::jsonb,
 null, 'Inguinal hernia is the most common type of hernia overall, and is especially common in males due to anatomical factors related to testicular descent.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'McBurney''s point is a clinical landmark used to locate:',
 '[{"text":"The gallbladder","isCorrect":false},{"text":"The appendix (point of maximum tenderness in appendicitis)","isCorrect":true},{"text":"The spleen","isCorrect":false},{"text":"The kidney","isCorrect":false}]'::jsonb,
 null, 'McBurney''s point, located one-third of the way from the anterior superior iliac spine to the umbilicus, marks the typical location of the appendix and site of maximum tenderness in appendicitis.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'Which imaging modality is considered the gold standard for diagnosing gallstones?',
 '[{"text":"Ultrasound","isCorrect":true},{"text":"Plain X-ray abdomen","isCorrect":false},{"text":"MRI brain","isCorrect":false},{"text":"ECG","isCorrect":false}]'::jsonb,
 null, 'Abdominal ultrasound is the preferred and most sensitive first-line imaging modality for detecting gallstones.'),
('NEET PG', 'Surgery and Allied', 'General Surgery', 'medium', 'mcq',
 'The most common benign breast tumor in young women is the:',
 '[{"text":"Fibroadenoma","isCorrect":true},{"text":"Phyllodes tumor","isCorrect":false},{"text":"Ductal carcinoma in situ","isCorrect":false},{"text":"Lipoma","isCorrect":false}]'::jsonb,
 null, 'Fibroadenoma is the most common benign breast tumor in young women, typically presenting as a well-circumscribed, mobile, painless lump.'),

-- Orthopedics
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'A greenstick fracture, in which the bone bends and partially breaks, is most commonly seen in:',
 '[{"text":"Elderly adults","isCorrect":false},{"text":"Children (due to more flexible bones)","isCorrect":true},{"text":"Middle-aged adults","isCorrect":false},{"text":"Athletes exclusively","isCorrect":false}]'::jsonb,
 null, 'Greenstick fractures, where the bone bends and cracks on one side without completely breaking, are most common in children due to the greater flexibility of their bones.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'Osteoporosis is characterized by:',
 '[{"text":"Increased bone density","isCorrect":false},{"text":"Decreased bone density/mass, increasing fracture risk","isCorrect":true},{"text":"Excess bone formation","isCorrect":false},{"text":"Infection of the bone marrow","isCorrect":false}]'::jsonb,
 null, 'Osteoporosis involves a reduction in bone mineral density and mass, weakening bones and significantly increasing the risk of fractures.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'medium', 'mcq',
 'The most common site for a hip fracture in elderly patients is the:',
 '[{"text":"Shaft of the femur","isCorrect":false},{"text":"Neck of the femur","isCorrect":true},{"text":"Iliac crest","isCorrect":false},{"text":"Acetabulum","isCorrect":false}]'::jsonb,
 null, 'Fractures of the neck of the femur are the most common type of hip fracture in elderly patients, often related to osteoporosis and falls.'),
('NEET PG', 'Surgery and Allied', 'Orthopedics', 'easy', 'mcq',
 'Deficiency of which vitamin in children leads to rickets?',
 '[{"text":"Vitamin A","isCorrect":false},{"text":"Vitamin D","isCorrect":true},{"text":"Vitamin C","isCorrect":false},{"text":"Vitamin B12","isCorrect":false}]'::jsonb,
 null, 'Vitamin D deficiency in children impairs calcium and phosphate absorption, leading to defective bone mineralization known as rickets.'),

-- Obstetrics and Gynaecology
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'The normal fetal heart rate range is approximately:',
 '[{"text":"60-100 beats per minute","isCorrect":false},{"text":"110-160 beats per minute","isCorrect":true},{"text":"170-200 beats per minute","isCorrect":false},{"text":"200-220 beats per minute","isCorrect":false}]'::jsonb,
 null, 'A normal fetal heart rate typically ranges from 110 to 160 beats per minute.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Preeclampsia is characterized by:',
 '[{"text":"New-onset hypertension and proteinuria after 20 weeks of gestation","isCorrect":true},{"text":"Low blood pressure throughout pregnancy","isCorrect":false},{"text":"Excess amniotic fluid only","isCorrect":false},{"text":"Gestational diabetes","isCorrect":false}]'::jsonb,
 null, 'Preeclampsia is defined by new-onset hypertension along with proteinuria (or other organ dysfunction) developing after 20 weeks of gestation.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'easy', 'mcq',
 'The Pap smear test is primarily used to screen for:',
 '[{"text":"Breast cancer","isCorrect":false},{"text":"Cervical cancer","isCorrect":true},{"text":"Ovarian cancer","isCorrect":false},{"text":"Endometrial cancer","isCorrect":false}]'::jsonb,
 null, 'The Pap (Papanicolaou) smear screens for precancerous and cancerous changes in cervical cells, enabling early detection of cervical cancer.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Obstetrics and Gynaecology', 'medium', 'mcq',
 'Ectopic pregnancy most commonly occurs in which location?',
 '[{"text":"Ovary","isCorrect":false},{"text":"Fallopian tube","isCorrect":true},{"text":"Cervix","isCorrect":false},{"text":"Abdominal cavity","isCorrect":false}]'::jsonb,
 null, 'The fallopian tube (particularly the ampullary region) is the most common site of implantation in ectopic pregnancy.'),

-- Anesthesia and Critical Care
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The Glasgow Coma Scale is used to assess:',
 '[{"text":"Blood pressure trends","isCorrect":false},{"text":"Level of consciousness after a head injury","isCorrect":true},{"text":"Kidney function","isCorrect":false},{"text":"Lung capacity","isCorrect":false}]'::jsonb,
 null, 'The Glasgow Coma Scale evaluates eye-opening, verbal, and motor responses to assess a patient''s level of consciousness, especially after head injury.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'Which drug is commonly used as an induction agent for general anesthesia due to its rapid onset and short duration?',
 '[{"text":"Propofol","isCorrect":true},{"text":"Morphine","isCorrect":false},{"text":"Atropine","isCorrect":false},{"text":"Warfarin","isCorrect":false}]'::jsonb,
 null, 'Propofol is widely used as an induction agent for general anesthesia due to its rapid onset of action and short duration of effect.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'easy', 'mcq',
 'Cardiopulmonary resuscitation (CPR) primarily aims to:',
 '[{"text":"Cure the underlying cause of cardiac arrest","isCorrect":false},{"text":"Maintain circulation and oxygenation until advanced care is available","isCorrect":true},{"text":"Permanently restart the heart without further intervention","isCorrect":false},{"text":"Sedate the patient","isCorrect":false}]'::jsonb,
 null, 'CPR aims to maintain vital circulation and oxygen delivery to the brain and organs during cardiac arrest until advanced life support or defibrillation can be provided.'),
('NEET PG', 'Obstetrics and Gynaecology, Anesthesia', 'Anesthesia and Critical Care', 'medium', 'mcq',
 'The normal range for arterial blood pH is approximately:',
 '[{"text":"6.8 to 7.0","isCorrect":false},{"text":"7.35 to 7.45","isCorrect":true},{"text":"7.6 to 7.8","isCorrect":false},{"text":"8.0 to 8.2","isCorrect":false}]'::jsonb,
 null, 'Normal arterial blood pH is tightly regulated between 7.35 and 7.45, with values outside this range indicating acidosis or alkalosis.');
