-- supabase/sql/exam_question_bank_upsc_cse_set2.sql
--
-- Second curated question-bank batch for 'UPSC CSE (IAS)' (see exam_patterns_upsc_cse.sql for the
-- exam's structure, and exam_question_bank_upsc_cse_set1.sql for the first batch -- same
-- table/schema, no migration needed). All-new questions, no overlap with Set 1.
--
-- Same format as Set 1: every row is format='mcq' with a single isCorrect:true option. 16
-- chapters (10 GS Paper I, 6 CSAT Paper II) each get 4 questions; "Current Affairs" again sticks
-- to durable, evergreen facts rather than time-sensitive news.
--
-- Run this once in the Supabase SQL Editor, after exam_patterns_upsc_cse.sql and
-- exam_question_bank_upsc_cse_set1.sql.

insert into exam_question_bank (exam_name, subject, chapter, difficulty, format, text, options, numerical_answer, explanation) values

-- GS Paper I: Ancient Indian History
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'easy', 'mcq',
 'The Indus Valley Civilization is also commonly known as the:',
 '[{"text":"Vedic Civilization","isCorrect":false},{"text":"Harappan Civilization","isCorrect":true},{"text":"Gangetic Civilization","isCorrect":false},{"text":"Mauryan Civilization","isCorrect":false}]'::jsonb,
 null, 'The Indus Valley Civilization is also called the Harappan Civilization, named after Harappa, one of its first excavated sites.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'medium', 'mcq',
 'Which ancient Indian university was a renowned center of Buddhist learning, attracting scholars from across Asia?',
 '[{"text":"Takshashila","isCorrect":false},{"text":"Nalanda","isCorrect":true},{"text":"Vikramashila","isCorrect":false},{"text":"Somapura","isCorrect":false}]'::jsonb,
 null, 'Nalanda, in present-day Bihar, was one of the world''s first residential universities and a major center of Buddhist learning, attracting students from across Asia.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'medium', 'mcq',
 'The Gupta period in Indian history is often referred to as the:',
 '[{"text":"Golden Age of India","isCorrect":true},{"text":"Dark Age of India","isCorrect":false},{"text":"Age of Invasions","isCorrect":false},{"text":"Iron Age of India","isCorrect":false}]'::jsonb,
 null, 'The Gupta period (c. 320-550 CE) is often called the Golden Age of India due to significant achievements in science, art, literature, and mathematics.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Ancient Indian History', 'medium', 'mcq',
 'Chandragupta Maurya''s chief minister, credited with authoring the Arthashastra, was:',
 '[{"text":"Chanakya (Kautilya)","isCorrect":true},{"text":"Ashoka","isCorrect":false},{"text":"Bindusara","isCorrect":false},{"text":"Megasthenes","isCorrect":false}]'::jsonb,
 null, 'Chanakya (also known as Kautilya or Vishnugupta) served as Chandragupta Maurya''s chief advisor and is traditionally credited with authoring the Arthashastra, a treatise on statecraft and economics.'),

-- GS Paper I: Medieval Indian History
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'The Vijayanagara Empire, a major medieval Hindu kingdom, was founded primarily in which region of India?',
 '[{"text":"North India","isCorrect":false},{"text":"South India (Deccan)","isCorrect":true},{"text":"Eastern India","isCorrect":false},{"text":"Northwest India","isCorrect":false}]'::jsonb,
 null, 'The Vijayanagara Empire was founded in the Deccan region of South India in the 14th century, becoming a major center of Hindu culture and power.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'hard', 'mcq',
 'Akbar''s policy of religious tolerance and universal peace was known as:',
 '[{"text":"Din-i-Ilahi","isCorrect":false},{"text":"Sulh-i-Kul","isCorrect":true},{"text":"Jaziya","isCorrect":false},{"text":"Mansabdari","isCorrect":false}]'::jsonb,
 null, 'Sulh-i-Kul ("peace with all") was Akbar''s policy of religious tolerance, promoting harmony among his empire''s diverse religious communities.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'The Battle of Haldighati (1576) was fought between Akbar''s forces and:',
 '[{"text":"Maharana Pratap","isCorrect":true},{"text":"Rana Sanga","isCorrect":false},{"text":"Prithviraj Chauhan","isCorrect":false},{"text":"Chhatrapati Shivaji","isCorrect":false}]'::jsonb,
 null, 'The Battle of Haldighati (1576) was fought between the forces of Akbar (led by Man Singh) and Maharana Pratap of Mewar.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Medieval Indian History', 'medium', 'mcq',
 'Ibn Battuta, the famous medieval traveler who wrote extensively about India, hailed from:',
 '[{"text":"Morocco","isCorrect":true},{"text":"Persia","isCorrect":false},{"text":"China","isCorrect":false},{"text":"Portugal","isCorrect":false}]'::jsonb,
 null, 'Ibn Battuta was a Moroccan traveler and scholar who visited India during the Delhi Sultanate period and documented his extensive travels.'),

-- GS Paper I: Modern Indian History and Freedom Struggle
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'The Partition of Bengal, which sparked widespread protest and the Swadeshi Movement, was carried out in the year:',
 '[{"text":"1905","isCorrect":true},{"text":"1911","isCorrect":false},{"text":"1919","isCorrect":false},{"text":"1929","isCorrect":false}]'::jsonb,
 null, 'The Partition of Bengal was implemented in 1905 by Lord Curzon, triggering the Swadeshi Movement and widespread nationalist protest.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'The Dandi March (Salt Satyagraha), led by Mahatma Gandhi, took place in the year:',
 '[{"text":"1920","isCorrect":false},{"text":"1930","isCorrect":true},{"text":"1942","isCorrect":false},{"text":"1947","isCorrect":false}]'::jsonb,
 null, 'The Dandi March, in which Gandhi walked to the Arabian Sea coast to make salt in defiance of British salt laws, began in 1930.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'The Cripps Mission, aimed at securing Indian cooperation for the British war effort, came to India in the year:',
 '[{"text":"1935","isCorrect":false},{"text":"1942","isCorrect":true},{"text":"1945","isCorrect":false},{"text":"1947","isCorrect":false}]'::jsonb,
 null, 'The Cripps Mission arrived in India in 1942, offering a proposal for Indian self-governance after World War II, which was ultimately rejected by Indian leaders.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Modern Indian History and Freedom Struggle', 'medium', 'mcq',
 'Who, along with Annie Besant, founded the Indian Home Rule League movement?',
 '[{"text":"Bal Gangadhar Tilak","isCorrect":true},{"text":"Gopal Krishna Gokhale","isCorrect":false},{"text":"Lala Lajpat Rai","isCorrect":false},{"text":"Bipin Chandra Pal","isCorrect":false}]'::jsonb,
 null, 'Bal Gangadhar Tilak, along with Annie Besant, founded separate but allied Home Rule League movements in 1916 to demand self-government for India.'),

-- GS Paper I: Indian Art and Culture
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'easy', 'mcq',
 'The Sun Temple at Konark, a UNESCO World Heritage Site, is located in which state?',
 '[{"text":"Odisha","isCorrect":true},{"text":"West Bengal","isCorrect":false},{"text":"Andhra Pradesh","isCorrect":false},{"text":"Tamil Nadu","isCorrect":false}]'::jsonb,
 null, 'The Sun Temple at Konark, famous for its chariot-shaped architecture, is located in Odisha.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'medium', 'mcq',
 'Kathak, one of India''s classical dance forms, developed primarily in which region?',
 '[{"text":"South India","isCorrect":false},{"text":"North India","isCorrect":true},{"text":"Northeast India","isCorrect":false},{"text":"West India","isCorrect":false}]'::jsonb,
 null, 'Kathak developed primarily in North India, drawing on storytelling traditions and later flourishing in Mughal courts.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'easy', 'mcq',
 'The tabla and sitar are examples of instruments used in:',
 '[{"text":"Carnatic classical music","isCorrect":false},{"text":"Hindustani classical music","isCorrect":true},{"text":"Western classical music only","isCorrect":false},{"text":"Folk music of Kerala only","isCorrect":false}]'::jsonb,
 null, 'The tabla and sitar are prominent instruments in Hindustani classical music, the classical tradition of North India.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Art and Culture', 'medium', 'mcq',
 'Warli painting, a traditional tribal folk art form, is primarily associated with which state?',
 '[{"text":"Maharashtra","isCorrect":true},{"text":"Rajasthan","isCorrect":false},{"text":"Bihar","isCorrect":false},{"text":"Gujarat","isCorrect":false}]'::jsonb,
 null, 'Warli painting is a traditional folk art form practiced by the Warli tribe of Maharashtra, characterized by simple geometric shapes.'),

-- GS Paper I: Indian and World Geography
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'The Deccan Plateau is bordered on the west by which mountain range?',
 '[{"text":"Eastern Ghats","isCorrect":false},{"text":"Western Ghats","isCorrect":true},{"text":"Vindhya Range","isCorrect":false},{"text":"Aravalli Range","isCorrect":false}]'::jsonb,
 null, 'The Western Ghats form the western boundary of the Deccan Plateau, running along India''s western coast.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'easy', 'mcq',
 'The Amazon River is located primarily in which continent?',
 '[{"text":"Africa","isCorrect":false},{"text":"South America","isCorrect":true},{"text":"Asia","isCorrect":false},{"text":"Australia","isCorrect":false}]'::jsonb,
 null, 'The Amazon River, the largest river by discharge volume in the world, flows primarily through South America.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'Which Indian state has the longest coastline?',
 '[{"text":"Tamil Nadu","isCorrect":false},{"text":"Gujarat","isCorrect":true},{"text":"Andhra Pradesh","isCorrect":false},{"text":"Kerala","isCorrect":false}]'::jsonb,
 null, 'Gujarat has the longest coastline among Indian states, stretching along the Arabian Sea.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian and World Geography', 'medium', 'mcq',
 'The Palk Strait separates India from which neighboring country?',
 '[{"text":"Bangladesh","isCorrect":false},{"text":"Sri Lanka","isCorrect":true},{"text":"Myanmar","isCorrect":false},{"text":"Maldives","isCorrect":false}]'::jsonb,
 null, 'The Palk Strait, located between Tamil Nadu (India) and northern Sri Lanka, separates the two countries.'),

-- GS Paper I: Indian Polity and Governance
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'hard', 'mcq',
 'The concept of judicial review in India is primarily empowered by which constitutional provision?',
 '[{"text":"Article 13","isCorrect":true},{"text":"Article 370","isCorrect":false},{"text":"Article 356","isCorrect":false},{"text":"Article 74","isCorrect":false}]'::jsonb,
 null, 'Article 13 declares any law inconsistent with Fundamental Rights void, forming the constitutional basis for judicial review by Indian courts.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'The Election Commission of India is a:',
 '[{"text":"Statutory body only","isCorrect":false},{"text":"Constitutional (autonomous) body","isCorrect":true},{"text":"Non-governmental organization","isCorrect":false},{"text":"Judicial body under the Supreme Court","isCorrect":false}]'::jsonb,
 null, 'The Election Commission of India is a constitutional body, established under Article 324, independent of the executive.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'Money bills, under the Indian Constitution, can only originate in which house of Parliament?',
 '[{"text":"Rajya Sabha","isCorrect":false},{"text":"Lok Sabha","isCorrect":true},{"text":"Either house equally","isCorrect":false},{"text":"State legislatures","isCorrect":false}]'::jsonb,
 null, 'Money bills can only be introduced in the Lok Sabha, reflecting its primacy in matters of taxation and public expenditure.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Polity and Governance', 'medium', 'mcq',
 'The 73rd Constitutional Amendment primarily relates to:',
 '[{"text":"Urban local bodies (municipalities)","isCorrect":false},{"text":"Panchayati Raj institutions","isCorrect":true},{"text":"Reservation in higher education","isCorrect":false},{"text":"The Goods and Services Tax","isCorrect":false}]'::jsonb,
 null, 'The 73rd Constitutional Amendment (1992) gave constitutional status to Panchayati Raj institutions, strengthening rural local self-governance.'),

-- GS Paper I: Indian Economy
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'India''s First Five-Year Plan primarily focused on the development of:',
 '[{"text":"Heavy industries","isCorrect":false},{"text":"Agriculture","isCorrect":true},{"text":"Information technology","isCorrect":false},{"text":"Tourism","isCorrect":false}]'::jsonb,
 null, 'India''s First Five-Year Plan (1951-56) prioritized agriculture, given the urgent post-independence need to boost food production.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'Which index measures the rate of change in prices of goods and services at the wholesale level in India?',
 '[{"text":"Consumer Price Index (CPI)","isCorrect":false},{"text":"Wholesale Price Index (WPI)","isCorrect":true},{"text":"Human Development Index (HDI)","isCorrect":false},{"text":"Gini Index","isCorrect":false}]'::jsonb,
 null, 'The Wholesale Price Index tracks price changes at the wholesale (producer/trader) level, distinct from the Consumer Price Index, which tracks retail-level prices.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'medium', 'mcq',
 'The Fiscal Responsibility and Budget Management (FRBM) Act, aimed at ensuring fiscal discipline, was enacted in the year:',
 '[{"text":"1991","isCorrect":false},{"text":"2003","isCorrect":true},{"text":"2010","isCorrect":false},{"text":"2016","isCorrect":false}]'::jsonb,
 null, 'The FRBM Act was enacted in 2003 to institutionalize fiscal discipline and reduce India''s fiscal deficit over time.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Indian Economy', 'easy', 'mcq',
 'SEBI (Securities and Exchange Board of India) is the regulatory body for:',
 '[{"text":"Banking operations","isCorrect":false},{"text":"The securities and capital markets in India","isCorrect":true},{"text":"Insurance companies","isCorrect":false},{"text":"Telecommunications","isCorrect":false}]'::jsonb,
 null, 'SEBI regulates India''s securities markets, protecting investor interests and promoting fair capital market practices.'),

-- GS Paper I: Environment and Ecology
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'The Chipko Movement, a notable Indian environmental movement, was primarily focused on:',
 '[{"text":"Preventing river pollution","isCorrect":false},{"text":"Forest conservation (against deforestation)","isCorrect":true},{"text":"Wildlife poaching prevention only","isCorrect":false},{"text":"Reducing vehicular emissions","isCorrect":false}]'::jsonb,
 null, 'The Chipko Movement, originating in the Himalayan region in the 1970s, involved villagers embracing trees to prevent their felling, becoming a landmark forest conservation movement.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'The Kyoto Protocol primarily deals with:',
 '[{"text":"Conservation of wetlands","isCorrect":false},{"text":"Reduction of greenhouse gas emissions","isCorrect":true},{"text":"Protection of endangered species","isCorrect":false},{"text":"Regulation of ocean fishing","isCorrect":false}]'::jsonb,
 null, 'The Kyoto Protocol, adopted in 1997, committed industrialized countries to specific targets for reducing greenhouse gas emissions.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'Biosphere reserves are primarily established for the purpose of:',
 '[{"text":"Commercial logging","isCorrect":false},{"text":"Conservation of biodiversity, ecosystems, and genetic resources","isCorrect":true},{"text":"Urban development","isCorrect":false},{"text":"Mining operations","isCorrect":false}]'::jsonb,
 null, 'Biosphere reserves are designated areas aimed at conserving biodiversity, ecosystems, and genetic resources while promoting sustainable development.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Environment and Ecology', 'medium', 'mcq',
 'The Montreal Protocol is an international agreement aimed at protecting the:',
 '[{"text":"Ozone layer","isCorrect":true},{"text":"Coral reefs","isCorrect":false},{"text":"Rainforests","isCorrect":false},{"text":"Polar ice caps directly","isCorrect":false}]'::jsonb,
 null, 'The Montreal Protocol (1987) is an international treaty designed to phase out substances responsible for depleting the ozone layer.'),

-- GS Paper I: General Science and Technology
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'The full form of "LASER" is:',
 '[{"text":"Light Amplification by Stimulated Emission of Radiation","isCorrect":true},{"text":"Light Absorption by Simulated Energy Radiation","isCorrect":false},{"text":"Linear Amplification of Solar Energy Rays","isCorrect":false},{"text":"Light Application by Stimulated Electron Radiation","isCorrect":false}]'::jsonb,
 null, 'LASER stands for Light Amplification by Stimulated Emission of Radiation, describing the physical process by which laser light is produced.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'easy', 'mcq',
 'DNA stands for:',
 '[{"text":"Deoxyribonucleic Acid","isCorrect":true},{"text":"Diribonucleic Acid","isCorrect":false},{"text":"Dioxyribonuclear Acid","isCorrect":false},{"text":"Deoxyribose Nuclear Acid","isCorrect":false}]'::jsonb,
 null, 'DNA stands for Deoxyribonucleic Acid, the molecule that carries genetic information in living organisms.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'medium', 'mcq',
 'ISRO''s Mangalyaan mission was sent to explore:',
 '[{"text":"The Moon","isCorrect":false},{"text":"Mars","isCorrect":true},{"text":"Venus","isCorrect":false},{"text":"Jupiter","isCorrect":false}]'::jsonb,
 null, 'Mangalyaan (Mars Orbiter Mission), launched by ISRO in 2013, successfully sent a spacecraft to orbit Mars.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'General Science and Technology', 'medium', 'mcq',
 'Which blood group is considered the universal donor?',
 '[{"text":"AB positive","isCorrect":false},{"text":"O negative","isCorrect":true},{"text":"A positive","isCorrect":false},{"text":"B negative","isCorrect":false}]'::jsonb,
 null, 'O negative blood lacks A, B, and Rh antigens, making it compatible with recipients of any blood type, hence its designation as the universal donor.'),

-- GS Paper I: Current Affairs and International Relations
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'The G20 group primarily comprises:',
 '[{"text":"Only European nations","isCorrect":false},{"text":"Major advanced and emerging world economies","isCorrect":true},{"text":"Only Asian nations","isCorrect":false},{"text":"Only members of the United Nations Security Council","isCorrect":false}]'::jsonb,
 null, 'The G20 is a forum comprising major advanced and emerging economies, together representing a large share of global GDP and trade.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'The International Court of Justice is headquartered in:',
 '[{"text":"Geneva","isCorrect":false},{"text":"The Hague","isCorrect":true},{"text":"New York","isCorrect":false},{"text":"Brussels","isCorrect":false}]'::jsonb,
 null, 'The International Court of Justice, the UN''s principal judicial organ, is headquartered in The Hague, Netherlands.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'easy', 'mcq',
 'NATO stands for:',
 '[{"text":"North Atlantic Treaty Organization","isCorrect":true},{"text":"National Association of Trade Organizations","isCorrect":false},{"text":"North American Trade Organization","isCorrect":false},{"text":"New Atlantic Treaty Organization","isCorrect":false}]'::jsonb,
 null, 'NATO stands for North Atlantic Treaty Organization, a military alliance of North American and European countries.'),
('UPSC CSE (IAS)', 'General Studies Paper I', 'Current Affairs and International Relations', 'medium', 'mcq',
 'The headquarters of the International Monetary Fund (IMF) is located in:',
 '[{"text":"Washington D.C.","isCorrect":true},{"text":"New York","isCorrect":false},{"text":"Geneva","isCorrect":false},{"text":"London","isCorrect":false}]'::jsonb,
 null, 'The International Monetary Fund is headquartered in Washington D.C., United States.'),

-- CSAT Paper II: Reading Comprehension
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Sustainable development seeks to meet the needs of the present without compromising the ability of future generations to meet their own needs." According to the passage, sustainable development primarily balances:',
 '[{"text":"Economic growth against environmental destruction only","isCorrect":false},{"text":"Present needs with the needs of future generations","isCorrect":true},{"text":"Urban development against rural development","isCorrect":false},{"text":"Individual rights against collective rights","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly defines sustainable development as meeting present needs without compromising future generations'' ability to meet their own needs.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Bureaucracy, while often criticized for its rigidity, provides consistency and accountability in the implementation of public policy." According to the passage, the main benefit of bureaucracy is:',
 '[{"text":"Speed of decision-making","isCorrect":false},{"text":"Consistency and accountability in policy implementation","isCorrect":true},{"text":"Complete flexibility in all situations","isCorrect":false},{"text":"Elimination of all rules","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states bureaucracy "provides consistency and accountability in the implementation of public policy", despite criticism of its rigidity.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'hard', 'mcq',
 'Read the passage: "Federalism divides powers between the central and regional governments, allowing for both national unity and regional autonomy." According to the passage, federalism enables:',
 '[{"text":"Only national unity, at the expense of regional autonomy","isCorrect":false},{"text":"National unity alongside regional autonomy","isCorrect":true},{"text":"Complete independence of regions from the center","isCorrect":false},{"text":"Centralization of all powers","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly states federalism allows for "both national unity and regional autonomy" by dividing power between central and regional governments.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Reading Comprehension', 'medium', 'mcq',
 'Read the passage: "Innovation often arises not from isolated genius, but from the exchange of ideas across diverse groups of people." According to the passage, innovation primarily stems from:',
 '[{"text":"Isolated individual genius alone","isCorrect":false},{"text":"The exchange of ideas across diverse groups","isCorrect":true},{"text":"Strict adherence to established methods","isCorrect":false},{"text":"Government funding alone","isCorrect":false}]'::jsonb,
 null, 'The passage explicitly contrasts "isolated genius" with "the exchange of ideas across diverse groups of people" as the true source of innovation.'),

-- CSAT Paper II: Logical Reasoning and Analytical Ability
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'medium', 'mcq',
 'Given: "All squares are rectangles" and "All rectangles are quadrilaterals." Which conclusion follows?',
 '[{"text":"All squares are quadrilaterals.","isCorrect":true},{"text":"All quadrilaterals are squares.","isCorrect":false},{"text":"No squares are quadrilaterals.","isCorrect":false},{"text":"Some rectangles are not quadrilaterals.","isCorrect":false}]'::jsonb,
 null, 'By transitive syllogism, since all squares are rectangles and all rectangles are quadrilaterals, it follows that all squares are quadrilaterals.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'easy', 'mcq',
 'Find the next number in the series: 1, 1, 2, 3, 5, 8, ?',
 '[{"text":"11","isCorrect":false},{"text":"13","isCorrect":true},{"text":"12","isCorrect":false},{"text":"10","isCorrect":false}]'::jsonb,
 null, 'This is the Fibonacci sequence, where each term is the sum of the two preceding terms: 5+8=13.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'medium', 'mcq',
 'A is taller than B. C is shorter than B. Who among the three is the shortest?',
 '[{"text":"A","isCorrect":false},{"text":"B","isCorrect":false},{"text":"C","isCorrect":true},{"text":"Cannot be determined","isCorrect":false}]'::jsonb,
 null, 'Since A is taller than B, and C is shorter than B, C must be the shortest of the three.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Logical Reasoning and Analytical Ability', 'hard', 'mcq',
 'In a certain code, "TABLE" is written as "UBCMF". How is "CHAIR" written in the same code?',
 '[{"text":"DIBJS","isCorrect":true},{"text":"DIBJR","isCorrect":false},{"text":"DHBJS","isCorrect":false},{"text":"DIAJS","isCorrect":false}]'::jsonb,
 null, 'Each letter is shifted forward by one position in the alphabet (T to U, A to B, B to C, L to M, E to F); applying the same shift to C-H-A-I-R gives D-I-B-J-S.'),

-- CSAT Paper II: Decision Making and Problem Solving
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'If you discover a factual error in a report you have already submitted to your supervisor, the best course of action is to:',
 '[{"text":"Ignore it since the report has already been submitted","isCorrect":false},{"text":"Promptly inform your supervisor and provide a correction","isCorrect":true},{"text":"Wait to see if anyone notices the error first","isCorrect":false},{"text":"Blame a colleague for the error","isCorrect":false}]'::jsonb,
 null, 'Promptly informing your supervisor and providing a correction demonstrates responsibility and integrity, minimizing any negative impact of the error.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'When two team members provide conflicting information about a project''s status, the best approach is to:',
 '[{"text":"Believe whichever person you trust more personally","isCorrect":false},{"text":"Verify the facts independently before making a decision","isCorrect":true},{"text":"Ignore both accounts and proceed as planned","isCorrect":false},{"text":"Ask a third, uninvolved colleague to guess","isCorrect":false}]'::jsonb,
 null, 'Independently verifying the facts ensures decisions are based on accurate information rather than personal bias or unconfirmed claims.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'If a subordinate consistently underperforms despite feedback, an effective manager should first:',
 '[{"text":"Terminate the subordinate immediately","isCorrect":false},{"text":"Understand the root cause through a private conversation","isCorrect":true},{"text":"Publicly criticize the subordinate''s performance","isCorrect":false},{"text":"Ignore the issue entirely","isCorrect":false}]'::jsonb,
 null, 'Understanding the underlying cause of underperformance through a private, constructive conversation allows for a fair and effective resolution.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Decision Making and Problem Solving', 'medium', 'mcq',
 'In an emergency situation with incomplete information, the most effective decision-making approach is to:',
 '[{"text":"Wait indefinitely until complete information is available","isCorrect":false},{"text":"Act on the best available information while continuing to gather more","isCorrect":true},{"text":"Make no decision at all","isCorrect":false},{"text":"Randomly choose an option without any evaluation","isCorrect":false}]'::jsonb,
 null, 'In emergencies, acting on the best available information while continuing to gather more balances the need for timely action with informed decision-making.'),

-- CSAT Paper II: Basic Numeracy
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 'Find the value of 18% of 250.',
 '[{"text":"40","isCorrect":false},{"text":"45","isCorrect":true},{"text":"50","isCorrect":false},{"text":"55","isCorrect":false}]'::jsonb,
 null, '18% of 250 = (18/100)*250 = 45.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 'If a train covers 300 km in 5 hours, its average speed is:',
 '[{"text":"50 km/hr","isCorrect":false},{"text":"60 km/hr","isCorrect":true},{"text":"65 km/hr","isCorrect":false},{"text":"70 km/hr","isCorrect":false}]'::jsonb,
 null, 'Average speed = distance/time = 300/5 = 60 km/hr.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'easy', 'mcq',
 'The HCF (highest common factor) of 12 and 18 is:',
 '[{"text":"3","isCorrect":false},{"text":"6","isCorrect":true},{"text":"9","isCorrect":false},{"text":"12","isCorrect":false}]'::jsonb,
 null, 'The factors of 12 are 1,2,3,4,6,12 and of 18 are 1,2,3,6,9,18; the highest common factor is 6.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Basic Numeracy', 'medium', 'mcq',
 'If the perimeter of a square is 40 cm, find its area.',
 '[{"text":"80 sq cm","isCorrect":false},{"text":"100 sq cm","isCorrect":true},{"text":"120 sq cm","isCorrect":false},{"text":"160 sq cm","isCorrect":false}]'::jsonb,
 null, 'Side = perimeter/4 = 40/4 = 10 cm; area = side^2 = 10^2 = 100 sq cm.'),

-- CSAT Paper II: Data Interpretation
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'medium', 'mcq',
 'A pie chart shows a company''s revenue sources as: Product sales 50%, Services 30%, Licensing 20%. What percentage comes from Product sales and Services combined?',
 '[{"text":"70%","isCorrect":false},{"text":"80%","isCorrect":true},{"text":"90%","isCorrect":false},{"text":"60%","isCorrect":false}]'::jsonb,
 null, 'Product sales (50%) + Services (30%) = 80% of total revenue.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'medium', 'mcq',
 'If a company''s profit increased from Rs. 40 lakh to Rs. 50 lakh, find the percentage increase.',
 '[{"text":"20%","isCorrect":false},{"text":"25%","isCorrect":true},{"text":"10%","isCorrect":false},{"text":"15%","isCorrect":false}]'::jsonb,
 null, 'Percentage increase = (50-40)/40 * 100 = 25%.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'easy', 'mcq',
 'Find the median of the data set: 4, 8, 15, 16, 23.',
 '[{"text":"8","isCorrect":false},{"text":"15","isCorrect":true},{"text":"16","isCorrect":false},{"text":"13.2","isCorrect":false}]'::jsonb,
 null, 'When sorted, the middle (third) value of the five numbers (4,8,15,16,23) is 15, making it the median.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Data Interpretation', 'easy', 'mcq',
 'In a dataset, the mode represents:',
 '[{"text":"The average of all values","isCorrect":false},{"text":"The most frequently occurring value","isCorrect":true},{"text":"The middle value when sorted","isCorrect":false},{"text":"The difference between the highest and lowest values","isCorrect":false}]'::jsonb,
 null, 'The mode is the value that appears most frequently in a dataset, distinct from the mean (average) and median (middle value).'),

-- CSAT Paper II: Interpersonal and Communication Skills
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'medium', 'mcq',
 'Which of the following best describes assertive communication?',
 '[{"text":"Aggressively insisting on one''s own views regardless of others","isCorrect":false},{"text":"Expressing one''s views confidently while respecting others'' viewpoints","isCorrect":true},{"text":"Avoiding expressing any opinion at all","isCorrect":false},{"text":"Agreeing with everyone to avoid conflict","isCorrect":false}]'::jsonb,
 null, 'Assertive communication involves expressing one''s own views and needs confidently and clearly, while still respecting the perspectives of others.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'easy', 'mcq',
 'Non-verbal communication primarily includes:',
 '[{"text":"Written reports only","isCorrect":false},{"text":"Body language, facial expressions, and tone of voice","isCorrect":true},{"text":"Formal legal documents only","isCorrect":false},{"text":"Email communication only","isCorrect":false}]'::jsonb,
 null, 'Non-verbal communication encompasses body language, facial expressions, gestures, and tone of voice, conveying meaning beyond spoken or written words.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'medium', 'mcq',
 'Empathy in communication primarily involves:',
 '[{"text":"Ignoring the other person''s emotions","isCorrect":false},{"text":"Understanding and sharing the feelings of another person","isCorrect":true},{"text":"Only focusing on facts, not feelings","isCorrect":false},{"text":"Dominating the conversation","isCorrect":false}]'::jsonb,
 null, 'Empathy involves genuinely understanding and being able to share in the feelings and perspective of another person during communication.'),
('UPSC CSE (IAS)', 'CSAT (General Studies Paper II)', 'Interpersonal and Communication Skills', 'medium', 'mcq',
 'Constructive feedback is most effective when it is:',
 '[{"text":"Vague and general","isCorrect":false},{"text":"Specific, timely, and focused on behavior rather than personality","isCorrect":true},{"text":"Delivered publicly to embarrass the recipient","isCorrect":false},{"text":"Delayed as long as possible","isCorrect":false}]'::jsonb,
 null, 'Effective constructive feedback is specific about the behavior in question, delivered in a timely manner, and focuses on actions rather than attacking personal character.');
